### ISSUE TITLE
Transform immediately ignored GraphQL and incorrect mime type

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#10126]
### Description

Probably unrelated but combining two issues into one just in case.

Currently we are seeing that image transforms are always being executed immediately even if we tell it not to in the GraphQL query.

Input:
```gql
imageSliderFullscreen: images @transform(handle: "imageSliderFullscreen", immediately: false) {
    title
    url
    focalPoint
    mimeType
    srcset(sizes: ["1x", "2x"])
}
```

Output:
```json
{
    "title": "Photo 1636312058374 ac0ffdb40d37",
    "url": "/uploads/primary/_imageSliderFullscreen/184/photo-1636312058374-ac0ffdb40d37.webp",
    "focalPoint": [
        0.5,
        0.5
    ],
    "mimeType": "image/jpeg",
    "srcset": "/uploads/primary/_imageSliderFullscreen/184/photo-1636312058374-ac0ffdb40d37.webp, /uploads/primary/_3840x2160_fit_center-center_82_none/184/photo-1636312058374-ac0ffdb40d37.webp 2x"
},
{
    "title": "Photo 1635323979696 a0279890cf25",
    "url": "/uploads/primary/_imageSliderFullscreen/183/photo-1635323979696-a0279890cf25.webp",
    "focalPoint": [
        0.5,
        0.5
    ],
    "mimeType": "image/jpeg",
    "srcset": "/uploads/primary/_imageSliderFullscreen/183/photo-1635323979696-a0279890cf25.webp, /uploads/primary/_3840x2160_fit_center-center_82_none/183/photo-1635323979696-a0279890cf25.webp 2x"
},
```

Also the returning `mimeType` is still the original JPEG and not WebP even though the transformed image is actually a valid `image/webp` image.

### Additional info

- Craft version: 3.7.21
- PHP version: 7.4.24

In case it matters (doesn't seem to effect the outcome I think):
- `upscaleImages` is overwritten to `false`
- `generateTransformsBeforePageLoad` is unchanged, `false`

**Comment by andris-sevcenko** [comment]
FTR even if the issues are related, it's safer to submit separate issues that can later be merged. Now it's more work to separate them.

1) The `mimeType` returned is for the original asset and is not even supposed to change to a different value for transforms. Same goes for the `size` field. Related: https://github.com/craftcms/cms/discussions/8993

2) It's because the `immediately` argument is not part of Craft transforms, but is rather a switch that GraphQL layer uses. When applying the transform directive on the Asset itself, this nuance is lost so, when requesting the URL, the transform set on the asset element is used, but there's no information about at which point the transform should be generated. For GraphQL requests, the fallback is always "immediately", because that's what is required 99% of the time, so you see the URL generated immediately.

To work around this, you can do

```graphql
imageSliderFullscreen: images @transform(handle: "imageSliderFullscreen", immediately: false) {
    title
    url (immediately: false)
    focalPoint
    mimeType
    srcset(sizes: ["1x", "2x"])
}
```

It won't work for `srcset`, though, as that does not support the `immediately` argument.

Obviously, this is suboptimal. We'll look into improving that.

**Comment by Wiejeben** [comment]
Alright, will create a separate issue next time!

Regarding `srcset` not being able to transform later is a shame, would be awesome if srcset could gain a `immediately` parameter next to `sizes`!

**Comment by brandonkelly** [comment]
Related: https://github.com/craftcms/cms/issues/10108

**Comment by stephanedemotte** [comment]
any news on that? the query take a loooong time if we have 3 sizes in srcset and a lot of images... and sometimes we get a `504 Gateway Time-out`

**Comment by brandonkelly** [comment]
The `immediately` argument is deprecated in Craft 4, and no longer has any effect (fc10c5d29788f3b68e11da95e9a5f5e69ff9c3b9).

If you’re having issues generating transforms with GD or ImageMagick, you might want to consider swapping to something like Imgix, using [Imager X](https://plugins.craftcms.com/imager-x?cmsConstraint=%5E4.0) or [ImageOptimize](https://plugins.craftcms.com/image-optimize?cmsConstraint=%5E4.0).
