### ISSUE TITLE
Matrix blocks duplicate on save when creating a new entry

### ISSUE THREAD

**Issue by chrismlusk** [craftcms/cms#10130]
### Description

I have a section that has a Matrix field with various blocks. A client recently informed me that sometimes when they create a new entry in this particular section, each Matrix block type is duplicated after they save the entry for the first time. They have not encountered this consistently, but it happens occasionally. I can confirm that I tested this and was able to recreated the issue. Also, this behavior doesn't seem to be happening on other sections with other Matrix blocks.

(I was unable to get specifics, but they said it's been happening "for a while; probably a few months." So it's spanned multiple Craft versions. FWIW.)

### Steps to reproduce

1. Create a new entry
2. Add Matrix blocks and content
3. Click "Create entry"

### Additional info

- Craft version: 3.7.21
- PHP version: 7.4.21
- Database driver & version: MySQL 5.7.34

**Comment by brandonkelly** [comment]
Can you think of anything unique about this section, compared to the other sections where it’s working properly?

Maybe try reproducing on a fresh Craft install, and try to work up to a reproducible build.

**Comment by chrismlusk** [comment]
Nothing that strikes me as out of the ordinary. This approach is fairly standard to our projects, and to my knowledge we have not encountered something like this before.

## Not working properly
### Section
- Name: Blog
- Versioning: enabled
- Type: Channel
- Entry URI Format: `{slug}-{id}`
- Entry Types: 1

### Matrix Field
- Name: Blog Content
- Field values as search keywords: false

## Working properly
### Section
- Name: Pages
- Versioning: enabled
- Type: Section
- Entry URI Format: `{parent.uri}/{slug}`
- Entry Types: 3

### Matrix Field
- Name: Page Content
- Field values as search keywords: false

**Comment by brandonkelly** [comment]
Are you able to reproduce on a fresh Craft install?

**Comment by sidedwards** [comment]
@brandonkelly, we have a customer experiencing this issue as well; I was able to reproduce this issue on a fresh multisite install. It seems this issue occurs with localized fields within localized Matrix blocks.

### ⚙️ Setup

Given a fresh multisite install of Craft, proceed with the following steps:

1. Create a localized Matrix field (i.e., "Only save blocks to the site they were created in")
2. Add a localized plain text or redactor field within the localized Matrix block
3. Create a new Entry that uses the above field layout

### 👣 Reproduction steps
Steps to reproduce the behavior:

1. Click "Create a draft," switch to a new site, and update the field values.
2. Switch back to the current Entry version, create another draft, switch to a different site, and update the field values.
3. Go back to the first draft and click "Apply draft."
4. Switch to the second draft and see the block duplication error for the localized field within the localized Matrix.

### 📚 Resources

https://user-images.githubusercontent.com/11489608/144136932-ff246bc7-7732-498d-a982-a2f87717f8e9.mp4

**Comment by brandonkelly** [comment]
Thanks – that helped a ton. Just got to the bottom of it and fixed for the next release 🙌🏻

**Comment by brandonkelly** [comment]
Craft 3.7.24 is out now with that fix. Thanks again!

**Comment by sidedwards** [comment]
Excellent, thanks, @brandonkelly, for the quick fix!

**Comment by KarlBishop** [comment]
We have a client reporting a similar issue on Craft 3.8.11

Their config is a bit different though because the Matrix field propagation method is "Save blocks to all sites the owner element is saved in" (rather than "Only save blocks to the site they were created in").

More details:

- Section propagation method = Save entries to all sites enabled for this section
- Matrix field propagation method = Save blocks to all sites the owner element is saved in
- Fields within Matrix blocks:
    - Some Plain text, URL and Redactor fields with Translation Method = Translate for each site
    - Some Lightswitch fields with Translation Method = Not translatable
    - Some Asset fields with Manage relations on a per-site basis = true

The issue doesn't happen every time they create a new entry but has occurred on a number of occasions.

I've not been able to reproduce it but the user I've spoken to said their process when it occurs is usually very simple: they just start a New Entry, enter content and Save without switching between Sites etc.

I can't see anything obviously related in the logs. But the site is experiencing a lot of failed queue jobs for 'Could not acquire a mutex lock for the queue'. We are planning to switch to using Redis for mutex to hopefully fix those. I don't see how they'd be connected to this duplication issue but am mentioning just in case.

**Comment by brandonkelly** [comment]
@KarlBishop Could you send your Composer files and database backup to support@craftcms.com? And point out which section you’ve seen this happen in.

**Comment by KarlBishop** [comment]
@brandonkelly Thanks for the response. I'll need to run this past the client for clearance (they're in the EU so gotta respect GDPR etc!)

I might need to clear out or obfuscate the `users` table before sending a db backup. Will that be OK/does it matter which approach I take?
