### ISSUE TITLE
Config setting for license file location

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1015]
> Created by: Chris Chiles (chris@mightyinthemidwest.com) on 2015/03/11 18:06:19 +0000
> Votes at time of UserVoice import: 5

-----------------------------------

On installs that are used for multiple sites, it'd be great to be able to configure the location of the license file. This would allow us to change that on a site-by-site basis and keep all license keys in version control.

**Comment by phoob** [comment]
How about making it possible to add the content of `license.key` to `.env`?

**Comment by Wiejeben** [comment]
I get where you are coming from, but I think this would just make things a bit more complicated than they have to. The `license.key` is generated by Craft up on first load because it is required, however the `.env` file is fully optional I believe.

However Laravel does something comparable I think, with the application key. Without it I don't think Laravel can function.

**Comment by brandonkelly** [comment]
The key that Laravel generates is its security key, similar to Craft’s `validationKey` config setting (about to be renamed to `securityKey`).
