### ISSUE TITLE
Wrong timezone in control panel when timezone is set in general.php

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#10151]
### Description

When timezone is set via general.php the control shows near the timezone `'This is being overridden by the timezone config setting.'`, which is great. But the timezone in the dropdown isn't set to the timezone as set in the general.php and shows another timezone instead. 

This is the way I'm using for setting the timezone and AFAIK that's the right way:

``` php
'timezone' => 'Europe/Riga'
```

I would expect the timezone to be shown correctly in the control panel, but no matter what timezone I set in general.php, it always shows Los Angeles in the control panel.

### Steps to reproduce

1. set a timezone in general.php
2. look in the control panel

### Additional info

- Craft version: 3.7.22
- PHP version: 8.0.12

**Comment by brandonkelly** [comment]
The setting is still operable; it’s showing you the value that is stored in your project config. The warning is just clarifying that its value won’t have any effect, due to the `timezone` config setting.

(Now that the time zone can be set to an environment variable, as of Craft 3.7.22, we’ll probably just deprecate the config setting in Craft 4 and suggest you do that instead, which will clear up this confusion.)

**Comment by bencresty** [comment]
@brandonkelly  Please re-read the issue post. It is NOT working

**Comment by brandonkelly** [comment]
Right… I’m saying it’s NOT working, _as expected_. The setting will still show what it is set to, and remember changes you make to it. But as long as you have the `timezone` general config setting set, its value has no effect on the actual system time zone.
