### ISSUE TITLE
"2006 MySQL server has gone away" error is reported quite often

### ISSUE THREAD

**Issue by martinhellwagner** [craftcms/cms#10178]
### Description

In a large project with around 80 multisites, we're receiving a large amount of "2006 MySQL Error has gone away" errors, which more often than not result in failing Queue Jobs. The query that's executed when the error is reported is always the same `SELECT GET_LOCK` query (see Screenshot attached below).

What could be the reason for this, and how could we solve it? Is it possible that the `wait_timeout` MySQL parameter is configured in a wrong way?

### Steps to reproduce

Not really any steps – the error arises during normal use of the Backend, e.g. when Queue Jobs are executed.

### Additional info

- Craft version: 3.7.21
- PHP version: 7.4.26
- Database driver & version: MariaDB 10.3.31

![Sentry Error](https://user-images.githubusercontent.com/19146752/143913126-b6b92372-e269-4323-b5b7-b71931afa7f2.png)

**Comment by angrybrad** [comment]
Are you using multiple queue runners?

**Comment by martinhellwagner** [comment]
Yes, indeed we are. We are running five queue listeners at the same time.

**Comment by angrybrad** [comment]
Likely... try dropping it down to one and see if you still get the same error. The database is the main bottleneck and the more queue runners you add, the higher the strain you put on the database, which leads to more resource contention issues like this.

**Comment by martinhellwagner** [comment]
Shouldn't MySQL be able to handle multiple queue runners at the same time? Sometimes we get quite a lot of queue jobs at once and want to process them quickly. Are there any MySQL parameters to speed up queue processing? We have enough CPU and RAM at our disposal. What's the recommended number of concurrent queue runners?

**Comment by angrybrad** [comment]
> What's the recommended number of concurrent queue runners?

For almost all Craft installs... one.

You can throw more CPU/memory at it and it might help some, but depending on the site (multi-site, complex IA with Matrix/Super Table/Neo, propagation settings, etc.), the type of jobs and the frequency of them being added to the queue, you can still hit database resource contention issues.

One thing that might help is to setup database read/write splitting (https://craftcms.com/docs/3.x/config/#database-component) so that at least read and write queries won't be competing for the resources on a single database.
