### ISSUE TITLE
Existing website suddenly wants connection with api.craft.cms.com and falls back to 'install'-screen once in a while

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#10207]
### Description

I don't know what version of Craft caused this, but it's either the latest or the before latest update. Suddenly a locally running website somethings wants to connect to api.craft.cms.com, which was never the case before.
When this happens the website also suddenly wants to 'install' (shows install page in the browser, the one with the red 'install' button in the middle and the background with little drawings).
When this happens I need to restart the dev server to be able to use the cms again instead of seeing the install screen (which is obviously wrong on an already installed and working website).

This happened here a few times now and it's pretty annoyng. It doesn't exactly add to the feeling of working with a stable CMS if things like this keep happening. It was working fine before. 

![Screenshot 2021-12-03 165159](https://user-images.githubusercontent.com/69322733/144632167-acdaa948-6bf1-4b0c-b3e4-4c797ca932e8.png)

### Steps to reproduce

Work with Craft. Latest or before latest version (using just the solo version while developing now)

### Additional info

- Craft version: 3.7.23
- PHP version: 8.0.12

**Comment by brandonkelly** [comment]
Craft uses api.craftcms.com check for available updates, as well as loads the Plugin Store data. That has always been the case, and you should allow it.



> When this happens the website also suddenly wants to 'install' (shows install page in the browser, the one with the red 'install' button in the middle and the background with little drawings).
> When this happens I need to restart the dev server to be able to use the cms again instead of seeing the install screen (which is obviously wrong on an already installed and working website).

Not sure what is happening when you click “Deny” but it sounds like it is somehow preventing Craft from being able to talk to the database successfully. Maybe because the API request isn’t getting terminated properly, which is causing some service to hang indefinitely. Not really sure. But you should definitely click “Allow”.

**Comment by bencresty** [comment]
@brandonkelly  Again, you're closing an issue that obviously is not solved. 

This issue makes it pretty clear that when there is't a connection with the craft API Craft isn't showing an error message, like we might expect, nor is it failing silently or putting something in the log, no it switches to an INSTALL screen... which is obviously wrong and dangerous for a working website and should never occur.

Reason why a website created by craft cannot reach the craft api could be several things. Like your api site is hacked, or there is some network issue somewhere. That should never result in each and every website in the world to suddenly show a INSTALL screen and so not only stop working, but potentionally be dangerous in disrupting the site.

Only because you'd like to have us check updates on each and every pageload. Which shouldn't be necesary.

I think you are way too easy skipping over obviously important issues. This happened quite some times now. This keeps on giving me the impression you guys don't want to strive for quality and stability, but more like to get rid of issue-messages on github.

I would appreciate it if you could take stuff like this a little more seriously and take a little more responsibiliy instead of just closing things you don't like to see.

**Comment by brandonkelly** [comment]
> This issue makes it pretty clear that when there isn't a connection with the craft API Craft isn't showing an error message, like we might expect, nor is it failing silently or putting something in the log, no it switches to an INSTALL screen... which is obviously wrong and dangerous for a working website and should never occur.
>
> Reason why a website created by craft cannot reach the craft api could be several things. Like your api site is hacked, or there is some network issue somewhere. That should never result in each and every website in the world to suddenly show a INSTALL screen and so not only stop working, but potentionally be dangerous in disrupting the site.
>
> Only because you'd like to have us check updates on each and every pageload. Which shouldn't be necesary.

I **guarantee** you that Craft is not showing you the install screen just because it wasn’t able to connect to its API. It will **only** show the install screen when it actually thinks it is uninstalled – either because it can’t connect to the database or the database doesn’t have the necessary tables.

In fact, absolutely nothing in Craft will break just because it wasn’t able to check for updates. (And when it does check for updates, it caches them for 24 hours by default, so not something that happens on every page load either.)

I don’t know exactly why Craft is unable to talk to the database after you deny one of its API requests, but whatever it is, it is outside of our control; it is an environmental issue. We can’t force PHP to magically connect to your database in some different way than we already do. It either can or can’t connect to it, period.

> Again, you're closing an issue that obviously is not solved.
>
> […]
>
> I would appreciate it if you could take stuff like this a little more seriously and take a little more responsibiliy instead of just closing things you don't like to see.

We close tickets when it appears there is nothing actionable in them; not ever because they contain something we “don’t like to see”. And just because an issue is closed doesn’t mean we are going to ignore follow-up comments. And we can always re-open if needed.
