### ISSUE TITLE
Graphql : unable to have the query working with RelatedTo on matrix field

### ISSUE THREAD

**Issue by charlyecho** [craftcms/cms#10242]
### Description

With graphql, I would like to get a list of entries related to a user linked via a matrix field.

The documentation for twig is quite clear but the graphql one is not or something is broken.  Documentation for relation in matrix field is [here](https://craftcms.com/docs/3.x/relations.html#going-through-matrix) 

### Steps to reproduce

```
query MyQuery {
  User: user {
    id
  }
  entries(
    section: "emissions", 
    relatedTo: {
      sourceElement: User, 
      field : "userList1.user"
    }
  ) {
    id
  }
}

```

Error returned by graphql :

`"debugMessage": "QueryArgument must be either a string, an integer, or a boolean value.",`

Matrix field name is userList1 and field inside it is user.

What am I missing ?

### Additional info

- Craft version: 3.7.25.1
- PHP version: 7.4
- Database driver & version: mysql
- Plugins & versions: none

**Comment by andris-sevcenko** [comment]
There are a few differences between using GraphQL and using Twig. One thing to definitely keep in mind going forward is that you can't use the results of one query in another query in the same request. This is because there is no guarantee that the queries will execute in order if they are in the same request.

Another thing is that GraphQL has a pretty strong type system, so it's not quite possible to just pass a User element as input.

For this reason, we have added some helper arguments, such as `relatedToUsers`.

In a regular situation, you would do 
```graphql
entries(section: "emissions", relatedToUsers: [{id: <userId>}] ) {
    id
  }
```

Substitute `<userId>` with the actual user id.

However, if you're looking for elements related via a matrix block, it gets tricky. This is because the user is related to the matrix block, and not the entry, so the above solution won't get you the results you want.

There's a bit of a convoluted workaround for this described here: https://craftcms.stackexchange.com/questions/38012/how-do-i-write-a-graphql-query-to-search-through-sub-entries-entries-as-fields-a

Admittedly, it requires some custom coding. I'll see if I can improve things going forward, but I can't promise anything.

**Comment by charlyecho** [comment]
Thanks you for your answer, 
I decided to make an entry in replacement of the matrix field. The graphql request is way simplier.
Will look forward for the enhancement of graphql queries if you improve it :)

**Comment by bryantwells** [comment]
I'm coming across this issue as well. For my case, at least, it seems like being able to query matrix fields independent of entries would help.

**Comment by brandonkelly** [comment]
Craft 5 added full support for querying for nested Matrix entries via GraphQL, using `fieldId` and `ownerId` arguments.
