### ISSUE TITLE
Slideout does not warn about unsaved changes after changing the entry type

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#10243]
### Description

When editing an entry in a slideout, the user is not presented with the "Are you sure you want to close the editor?" confirm dialog, if the only thing that they changed was the entry type.

Also, there's an odd behaviour where the slideout sometimes closes immediately, without any animation. Seems related as I can only make it happen after changing the entry type, it never occurs if there are other changes in the form (or no changes at all) or if the slideout is closed by saving the entry.

Screencast to demonstrate the issue (notice how the slideout closes without animation, intermittently):

https://user-images.githubusercontent.com/298510/145884133-3ec55113-a44d-4108-bb57-c94fecdd47a7.mp4

### Steps to reproduce

1. Create a section with multiple entry types
2. Create an entry
3. Open the entry in a slideout, either from an Entries field or via the entry index
4. Change the entry type via the form in the slideout
5. Close the slideout, either by clicking outside it or by tapping the slideout's "Cancel" button

### Additional info

Observed on Edge 96.0.1054.43, macOS 12.0

- Craft version: 3.7.25.1
- PHP version:
- Database driver & version:
- Plugins & versions: none

**Comment by brandonkelly** [comment]
Thanks for reporting! Craft 3.7.26 is out now with a fix for this. Can’t explain the immediate close thing… I’m able to sortof reproduce just by opening the editor and then closing it without making any changes, too. I’m able to see a very brief (sped up?) animation, so it feels like a CSS animation bug, possibly due to the complexity of the slideout contents.
