### ISSUE TITLE
Update voku/stringy to 6.4.3 to fix PHP 8.1 compatibility

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#10252]
### Description

See https://github.com/voku/Stringy/blob/master/CHANGELOG.md#643-2021-12-15 and https://github.com/voku/Stringy/issues/35 for context

P.S. it can't be updated in Craft right now because Craft requires voku/portable-utf8 5x instead of 6x

**Comment by brandonkelly** [comment]
Looks like the only reason we were explicitly requiring that package was to avoid a security vulnerability that was fixed in 5.4.28 (6fef82f4311509cb0b3dc4e6180dba7109c17263). We aren’t actually calling any of its methods directly in Craft’s source code, so I just removed the Composer requirement for 3.7.26 (already released).

**Comment by boboldehampsink** [comment]
Great, thanks

**Comment by boboldehampsink** [comment]
@brandonkelly just a heads up that yii2 doesn't have 8.1 support yet: https://github.com/yiisoft/yii2/pull/19041
