### ISSUE TITLE
`craft.rebrand.logo` not working from CLI-based queue job

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#10268]
We're using Formie to send out branded emails, but I suspect this to be the same behaviour for system emails.

We're trying to use the install's logo in emails using `craft.rebrand.logo`. When sending the email locally, and with `runQueueAutomatically => true` results in the path:

```
http://site.test/cpresources/f91296a0/logo-vert.svg?v=1639814034
```

Which works and displays great. Setting `runQueueAutomatically => false` and running the queue manually through the CLI via `./craft queue/run` results in:

```
http://site.test/assets/fe4b98b4/logo-vert.svg
```

Is there a reason for this path change? It makes the logo unreachable as `assets/fe4b98b4/logo-vert.svg` throws a 404.

**Comment by brandonkelly** [comment]
Most likely this is because the `resourceBaseUrl` config setting is set to `@web/cpresources` by default, and Craft isn’t able to resolve `@web` (the URL to the web root) automatically for console requests, so it must be [set explicitly](https://craftcms.com/docs/3.x/config/#aliases) to work there.

I really wouldn’t recommend including a CP resource URL in emails to begin with though. They are ephemeral and very unlikely to still exist long-term.

I’ve just added some new methods to `craft\web\twig\variables\Image` – `getContents()`, `getDataUrl()`, `getMimeType()`, and `getPath()` – which will make it possible to do what you want with it. For example, you could base64-encode the image and include it directly in the email body like so:

```php
use craft\helpers\Html;
use craft\web\twig\variables\Rebrand;

$logo = (new Rebrand())->getLogo();

if ($logo) {
    $logo = Html::img($logo->getDataUrl(), [
        'alt' => sprintf('%s logo', Craft::$app->getSystemName()),
    ]);
}
```

**Comment by engram-design** [comment]
I should've mentioned that we are also setting `@web` explicitly (as recommended).
```
'aliases' => [
    '@web' => App::env('BASE_URL'),
    '@webroot' => dirname(__DIR__) . '/public_html',
],
```

And yep, I thought either the original URL with `cpresources` was incorrect or not the recommended way, as you say, kinda like temporary files. I did think we could just add it as an asset, but sort of nice not having it floating around defined in multiple areas.

I'll give those options a go, but think that could work!

**Comment by brandonkelly** [comment]
Hm, maybe that environment variable isn’t getting defined for console requests?

**Comment by engram-design** [comment]
No trouble resolving `@web` which resolves to `http://site.test` in both cases. I've tried to go down the rabbit hole of figuring out why `cpresources` gets replaced with `assets` but it all got a bit too much.

Using `craft.rebrand.logo.getDataUrl()` works for us, as we're using MJML `<mj-image>` to create emails, so that's resolved enough for me!

**Comment by brandonkelly** [comment]
Alright, sweet!

**Comment by brandonkelly** [comment]
Craft 3.7.27 is out with those new image methods.
