### ISSUE TITLE
Uploaded images turn lighter

### ISSUE THREAD

**Issue by fabianhaef** [craftcms/cms#10282]
### Description
When I upload an image to craft cms it makes it way lighter. We don't use any plugins for image uploads and already tried to fix this by looking at the image-transform but we could not figure it out. Has anyone experienced the same problem? 

Original Image:
![11 Plampi](https://user-images.githubusercontent.com/55360588/147110646-8dbdf9f3-fb5c-4419-8807-74b0735289bc.jpeg)

Image in CMS:
![cms_11-Plampi](https://user-images.githubusercontent.com/55360588/147110730-481e5dd8-3c6a-423e-ab17-f0371977acb9.jpeg)

### Additional info

- Craft version: 3.6.18
- PHP version: 7.4.24
- Database driver & version: MySQL 5.7.26
- Plugins & versions:

**Comment by Mosnar** [comment]
The problem is that your image is in the CMYK color mode (used for print) instead of RGB (used for web.) I've run into this before and we just ended up converting all images outside of Craft prior to uploading. Unfortunately converting between RGB and CMYK isn't as straight-forward as one would hope, as it depends on having the appropriate color profile information in the original image.

**Comment by fabianhaef** [comment]
> 

Thanks for your fast response. Will try to change the color profile with my client, as he has the original pictures and should be able tochange it.

**Comment by brandonkelly** [comment]
Thanks for responding @Mosnar!
