### ISSUE TITLE
Placing a `<title>` string in a field's "Default Instructions" settings breaks the entry edit page

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#10290]
### Steps to reproduce

1. Have a fresh Craft installation.
2. Create a new Plain Text field.
3. Enter this into the "Default Instructions":

`This text goes within the <title> tag in the <head> of the HTML file.`

4. Save the field and add it to a section's entry type.
5. Create a new entry in that section.
6. Notice the broken edit entry layout.

### Additional info

- Craft version: 3.7.26
- PHP version: n/a
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Fixed for the next release. Now detecting unclosed tags such as `<title>` and `<head>` in your example, and encoding them so they appear as plain text.

**Comment by brandonkelly** [comment]
Craft 3.727 is out now with the fix.

**Comment by jkorff** [comment]
This bug seems to have crept back in. I have a matrix with a plain text field that has the following data in the "Instructions" field:

Copy the content of the "name" attribute of the hidden <input> field that belongs to your question set. E.g. for this: <input type="hidden" name="entry.644186258" ...  you would enter 644186258.

If I want to edit an entry I get a server 500 error unless I add spaces like so "< input >".

This is for Craft 3.7.37.

**Comment by brandonkelly** [comment]
@jkorff That error was caused by your unclosed `<input type="hidden" name="entry.644186258"` tag.

I’ve just tweaked `encodeInvalidTags()` to be defensive for that. It fixes the error, but the resulting output is still probably not desired, as the first `<input>` will get rendered as an actual text input. Assuming you want the instruction text to show the actual HTML code, you will need to wrap it in backticks:

```md
Copy the content of the `name` attribute of the hidden `<input>` field that belongs to your question set. E.g. for this: `<input type="hidden" name="entry.644186258" ...` you would enter `644186258`.
```

**Comment by jkorff** [comment]
Thank you Brandon. Knowing these rules might work for devs like me, but clients might struggle remembering. I appreciate that you are hardening the code.

**Comment by brandonkelly** [comment]
We are talking about field instructions right? Your clients shouldn’t have access to edit those in the first place.

**Comment by brandonkelly** [comment]
Craft 3.7.38 is out now with that fix.
