### ISSUE TITLE
New site duplicates an existing site homepage content

### ISSUE THREAD

**Issue by jamiematrix** [craftcms/cms#10326]
### Description
When creating a new site (in a multi-site setup) the new site has a duplicate of another sites homepage. All content, assets, matrix blocks, everything is a copy. I realise this could be an intentional thing if the multi sites were sharing content all the time, but I can't find an option to stop this happening.

Is it possible to have a homepage but have a new site's homepage with no content.

### Steps to reproduce

1. Create new site
2. Go to the homepage entry for the new site.

### Additional info

- Craft version: 3.7.20
- PHP version: 7.4

**Comment by brandonkelly** [comment]
Any time you enable a new site on an existing section (single or otherwise), the existing content will be copied over to the new site for existing entries.

If you want each site to have its own unique homepage, you can create completely separate homepage sections for each site, rather than sticking with a single homepage section that is enabled for all sites.
