### ISSUE TITLE
Optional parameter $scheme declared before required parameter $cpUrl is implicitly treated as a required parameter 

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#10374]
### Description

In UrlHelper.php line 623:
`Optional parameter $scheme declared before required parameter $cpUrl is implicitly treated as a required parameter`

This is breaking my tests with PHP 8.1.1

### Additional info

- Craft version: 3.7.28
- PHP version: 8.1.1
- Database driver & version: PostgreSQL 13.5
- Plugins & versions: -

**Comment by timkelty** [comment]
Thanks @boboldehampsink, fixed here https://github.com/craftcms/cms/pull/10375

**Comment by brandonkelly** [comment]
There were actually several places where that was happening. For the most part they were intentional – `sometype $foo = null` was the only way to do nullable types in PHP 7.0. I had already cleaned up all of them for Craft 4 (5bf636297372fb005b79cfd0230489333f9c818a) but just went through and cleaned up most of them for the next Craft 3 release as well (280d2e41bb5a66c0da66a357dfa6472b29fc5454). Only exception is three cases in `craft\base\ElementInterface` / `craft\base\Element`, where changing the method signatures would be a breaking change.
