### ISSUE TITLE
"Draft not found" when editing the an entry in different sites on the same time

### ISSUE THREAD

**Issue by carolineboeykens** [craftcms/cms#10381]
### Description
We have a multisite with multiple languages. The content for the FR and NL website already exists. Now the content manager wants to edit the EN pages. He does this by opening an entry in two tabs: one in NL and the other in EN.

When he tries to save the two entries the error 'Draft not found' appears, because there was another draft created when he started editing in the other tab too.

![Screenshot 2022-01-19 at 14 14 42](https://user-images.githubusercontent.com/42932673/150137962-2e22094b-e774-4225-bde9-9af5354e9931.png)

### Steps to reproduce

1. Create a multisite
2. Open an entry in site A
3. Open an entry in site B
4. Edit the entry in site A without saving
5. Edit the same entry in site B and save
6. Save entry in site A

### Additional info

- Craft version: 3.7.10
- PHP version: 7.4.3

**Comment by brandonkelly** [comment]
So this is actually _sortof_ expected behavior. When reproducing this, you may have noticed that after step 4, the site B browser tab automatically reloaded itself. Craft does this so its form is editing the same provisional draft that you just created for site A.

So the site B changes you made in step 5 were getting saved to the same draft that contained the side A changes in step 4. Which means, when you clicked Save in step 5, that was saving all of the provisional changes for the entry, across both sites.

The awkward thing is that the other tab never got notified about it, so its form was still stuck editing the provisional draft that no longer exists, hence the “Draft not found” error.

I just addressed this for the next release: now all browser tabs are notified when a draft is published, so they can reload themselves if they had been editing the same draft.
