### ISSUE TITLE
Prevented saving [asset] as an asset. It must be located within a temp directory or the project root (excluding system directories).

### ISSUE THREAD

**Issue by stevenvandemoortele** [craftcms/cms#10401]
### Description

After updating to 3.7.17 and beyond uploading files via a custom module / plugin is broken.
I'm also using deployer which creates a shared folder 
It looks like a combination of the following issues
https://github.com/craftcms/cms/issues/9980
https://github.com/craftcms/cms/issues/10382

We used the following code to set the tempFilePath:
`$asset->tempFilePath = Craft::getAlias('@storage') . '/' . 'foldername';`

This results in craft trying to save the tempfile in non existing storage folder in our current release folder when it should be in the symlinked storage folder in shared.

Rolling back to 3.7.16 fixed my problem.

### Additional info

- Craft version: 3.7.17 +
- PHP version: 7.4.25
- Database driver & version: MySQL 5.7.35

**Comment by brandonkelly** [comment]
This is expected – we tightened the allowed list of places temporary asset uploads can be stored for security reasons.

You can store the file in any of the following places:

- `storage/runtime/temp/`
- `storage/runtime/assets/tempuploads/`
- the system temp directory (whatever [sys_get_temp_dir()](https://www.php.net/manual/en/function.sys-get-temp-dir.php) returns)

Allowing arbitrary `storage/` subfolder would be problematic because we don’t know whether they might contain sensitive files that should not be pulled into Craft as assets.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Seems it was caused because your `storage/` folder lives outside your project root, which we didn’t account for in the initial logic. Just released 3.7.30.1 with a fix.
