### ISSUE TITLE
The `webp` format is not supported on this server!

### ISSUE THREAD

**Issue by iamkeir** [craftcms/cms#10588]
### Description

We are using Craft's Image Transforms on one of our client sites, generating `webp` images with ImageMagick which has, until recently, been working fine.

We have begun receiving the following error in logs:
`craft\errors\AssetTransformException: The `webp` format is not supported on this server! in /home/thesoupergirl/craft/vendor/craftcms/cms/src/services/AssetTransforms.php:1536`

We have checked with our hosting and they say ImageMagick is still enabled. WebP support is also shown as enabled in Craft's PHP Info.

The only thing we can pinpoint as having changed recently is we have upgraded Craft from 3.7.31 to 3.7.32 and then 3.7.33. There is mention of `Improved asset transform eager-loading performance` in 3.7.32 and [someone else mentioned this issue](https://github.com/craftcms/cms/discussions/10427#discussioncomment-2151818).

We are investigating with our hosting as well, but thought worth reporting in case anyone else experiencing/has a fix.

### Additional info

- Craft version: Craft Pro 3.7.33
- PHP version: 8.0.15
- Database driver & version: MySQL 5.5.5

**Comment by iamkeir** [comment]
Based on another user, [switching from Imagick to GD fixed the issue](https://github.com/craftcms/cms/discussions/10427#discussioncomment-2191332) for us. Still curious what could have caused this to happen.

**Comment by brandonkelly** [comment]
The performance improvement in 3.7.32 was just a new DB table index. Definitely unrelated to webp support.

**Comment by andris-sevcenko** [comment]
@iamkeir Can you go to `admin/utilities/php-info` and do a search for "WEBP"? Is it listed along "ImageMagick supported formats"?

**Comment by andris-sevcenko** [comment]
Sorry, just saw that you said it was listed there, indeed. The next step then is to run some custom code and see which part of [this check](https://github.com/craftcms/cms/blob/develop/src/services/Images.php#L187) is failing, then.

**Comment by iamkeir** [comment]
@andris-sevcenko I'll look into this and report back.

**Comment by andris-sevcenko** [comment]
Any updates, @iamkeir?

**Comment by iamkeir** [comment]
@andris-sevcenko sorry my bad, we switched to GD and got sucked into the rest of the project. I'll see if I can replicate and get more information.

**Comment by frank-laemmer** [comment]
Frank from fortrabbit (hosting) here. AFAIK: 

* GD is a PHP extension, there is a version that supports webp
* imageMagick is supported via PHP extension, there is a version that supports webp
* there is also a PHP native webp transformation function: [imagewebp](https://www.php.net/manual/en/function.imagewebp.php)

Since imageMagick is most used these days, we provide webp via imageMagick, but currently not via GD. You can see the supported image formats by printing a phpinfo. Here is an example: https://phpinfo-81.frb.io/ - search for webp on that page.

So, please check the settings with your hosting provider and not just switch to GD.
