### ISSUE TITLE
PHP 8.1 compatibility bug

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#10594]
### Description

```
yii\base\ErrorException: During inheritance of ArrayObject: Uncaught yii\base\ErrorException: Return type of craft\base\MemoizableArray::offsetSet($index, $newval) should either be compatible with ArrayObject::offsetSet(mixed $key, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/user/vendor/craftcms/cms/src/base/MemoizableArray.php:185
```

### Additional info

- Craft version: 3.7.33
- PHP version: 8.1.2
- Database driver & version: -
- Plugins & versions: -

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

Apparently it wasn’t such a great idea to extend `ArrayObject` and override most of its methods…

**Comment by boboldehampsink** [comment]
@brandonkelly I tried develop and now seeing this error:

```During inheritance of IteratorAggregate: Uncaught yii\base\ErrorException: Return type of craft\base\MemoizableArray::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/user/vendor/craftcms/cms/src/base/MemoizableArray.php:226```

**Comment by brandonkelly** [comment]
Sorry, that warning is suppressed now, as well as a few others (aa33376c3518f139b67366702475a36a283f3039).

**Comment by brandonkelly** [comment]
Yeah, tested on 7.4, 8.0, and 8.1.

The only one I was really worried about is 8.0, since attributes were added in 8.0 but `ReturnTypeWillChange` was added in 8.1, but looks like it just ignores it.

The actual `use` statement makes no difference either way. PHP doesn’t import anything based on the `use` statement; that just tells it the fully qualified classname, if anything further down ends up requiring it to be imported. Even doing something like

```php
use foo\bar\Baz;

echo Baz::class;
```

wouldn’t actually cause PHP to try to autoload/import `foo\bar\Baz` as nothing is referenced from inside the class there. It will just output the FQN string, regardless of whether the class even exists.

**Comment by brandonkelly** [comment]
(And worth noting none of these `ReturnTypeWillChange` attributes are needed in Craft 4. This is just a duck-tape solution for now since I don’t want to change the function signatures in case some plugin/module is overriding them.)

**Comment by brandonkelly** [comment]
Craft 3.7.34 is out with these fixes.
