### ISSUE TITLE
Deleted custom field data still persists

### ISSUE THREAD

**Issue by eclectiv** [craftcms/cms#10638]
### Description
I deleted a custom field from a Section, but I noticed that the data from the deleted custom field isn't deleted with each entry. For example, let's say I have a `section` called  "icecream" with a text field called `flavor`. If I delete the `flavor` field, the data for `flavor` still exists with each entry in the database. So in my template, although the `flavor` field no longer exists, `{{ entry.flavor }}` will still print the flavor data.

Btw - My section only has one Entry Type. I've also tried deleting the cache.

### Steps to reproduce

1. Create a custom text field in a Section
2. Populate newly created text field with some data in an entry
3. Delete custom text field from your Section 
4. Try to output now-deleted field in your template. Whatever text you populated the text field with will output.

### Additional info

- Craft version: 3.7.34
- PHP version: 8.0.13
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
That’s working as expected for now, at least until we get around to some planned content storage changes (#8404).

In the meantime you can clear out your existing field data with the [resave/entries](https://craftcms.com/docs/3.x/console-commands.html#resave-entries) command:

```sh
php craft resave/entries --section mySection --set myField --to :empty:
```

(Note that you will need to temporarily reattach the custom field to the field layout for this to work.)

**Comment by mmikkel** [comment]
FWIW, I personally don't *want* this behaviour to change. I've always looked at it like a sort of basic Craft-ism, that all elements essentially always have all (global) fields, regardless of which fields the developer decides to expose to authors via elements' field layouts.

The fact that field values are retained if, for example, an entry changes entry type, can be a valuable feature. I know authors on some of our sites have relied on it in the past.

I get that the behaviour can be confusing or unwanted, though. It's not intuitive, i.e. it's essentially something that ideally both the developer and authors should be aware of. So possibly there is a way to improve it. 

Instead of actually deleting those field values if/when a field is removed from a layout, what about simply making sure that any fields not in an element's layout always return `null`?

**Comment by brandonkelly** [comment]
@mmikkel Yeah I agree which is why it hasn’t changed to date.

However we need to look into splitting the `content` table up into smaller ones—perhaps one per field layout, or one per section, etc.—to work around MySQL row size limitations that people run into when creating a lot of custom fields. If we go that route, we would likely end up removing columns when the field is removed from the layout.

Alternatively, we might just go with `content2`, `content3`, etc., as `content` gets too big, in which case the behavior won’t change.

**Comment by eclectiv** [comment]
@mmikkel Thanks for the counterpoint. I could see how retaining the value of fields can be useful in various cases. On the flip side, there are situations where deleting the field values could be imperative (i.e. security reasons, data privacy). 

Likewise, as you already noted, it seems odd and counterintuitive that once a field is associated with a Section, its value is indelible and inextricably associated with its respective Section entry, even after the field is removed. 

To bridge both cases, perhaps there can be an option to "Hide" a field in the Field Layout, similar to how you can "Hide" the Field Label. That way, anyone who may want to retain the field value but hide the field from showing in an Entry page can do so. And those who want to remove the field and its associated data can do so as well by the current way you remove a field in the Field Layout (which is what, I'm figuring, is the expected outcome that most people would expect to happen).

**Comment by mmikkel** [comment]
> Likewise, as you already noted, it seems odd and counterintuitive that once a field is associated with a Section, its value is indelible and inextricably associated with its respective Section entry, even after the field is removed.

Yes, but I'd argue that the proposed behaviour could be equally odd or counterintuitive – it all depends on what the developer (or author) _assumes_ happens to existing content when elements' field layouts change, since there's nothing in the UI that makes this clear. And in the absence of such clarity, I'd much rather Craft err on the side of caution and not delete content unless specifically instructed to delete content – especially since that's how this has always worked.

In cases where you actually need to bulk delete sensitive data, there are already ways to do that; in addition to what Brandon outlined above, deleting the actual field itself would also do it.

**Comment by eclectiv** [comment]
Yeah, I agree it's the assumption of a developer/author that predicates whether the behavior is counterintuitive/unexpected. I think you also make a good point about, in the absence of clarity, not deleting the field values, given there's a precedent of content not being deleted.

All in all, I'm glad Brandon showed a way to delete the content. I often create generic fields that are used on multiple Sections, so deleting the actual field itself can sometimes not an option. Thanks again for weighing in and sharing your thoughts. I'm figuring someone else will have the same question and they'll hopefully find the dialogue to be helpful.
