### ISSUE TITLE
[3.x]: Next and Prev entries returning NULL

### ISSUE THREAD

**Issue by vitalijalbu** [craftcms/cms#10812]
### Description

Hi need t create a pagination of next & prev entries, but it return me null.
My website: [https://interno.publimax.eu/servizi/tinteggiatura](https://interno.publimax.eu/servizi/tinteggiatura)

### Steps to reproduce

1.

### Expected behavior

```
{# Fetch the next entry #}
{% set prevEntry = craft.entries().prevSiblingOf(entry).one %}
{% set nextEntry = craft.entries().nextSiblingOf(entry).one %}
{{ dump(nextEntry) }}
```

### Craft CMS version

3.7.37

### PHP version

7.2

### Installed plugins and versions

-

**Comment by mattstein** [comment]
Hi @vitalijalbu! Can you please provide a bit more context? You’re describing expected behavior if you’re working with a Structure section and there _isn’t_ a next entry to return.

If you’re working with Section entries, you’ll probably need to use the [{% paginate %}](https://craftcms.com/docs/3.x/dev/tags.html#paginate) tag in conjunction with an element query.

If I’m misunderstanding, please clarify what your content setup and the rest of your template look like.

**Comment by vitalijalbu** [comment]
Hi, I'm just trying to get the next and prev entries from a **channel**. Is it possible?

**Comment by brandonkelly** [comment]
`prevSiblingOf()` and `nextSiblingOf()` are specifically for entries within Structure sections, which have an explicit user-defined order.

For channel section entries, you would need to use [`getPrev()`](https://docs.craftcms.com/api/v3/craft-base-element.html#public-methods)/[`getNext()`](https://docs.craftcms.com/api/v3/craft-base-element.html#public-methods), and pass in an element query that identifies the expected entry order.

```twig
{% set entryQuery = craft.entries()
   .section('mySectionHandle')
  .orderBy('postDate desc') %}

{% set prevEntry = entry.getPrev(entryQuery) %}
{% set nextEntry = entry.getNext(entryQuery) %}
```
