### ISSUE TITLE
[4.x]: GraphQL: authorization silently fails on malformed authorization header

### ISSUE THREAD

**Issue by tremby** [craftcms/cms#10907]
### Description

If the authorization header is malformed in a particular way, the authorization of a graphql request silently fails.

### Steps to reproduce

1. Set the public schema to be somewhat cut-down in terms of what a user can query for
2. Set up a bearer token for a private schema with more access
3. Query your endpoint with a well-formed authorization header with the private schema bearer token, something like `curl -H "Authorization: Bearer abc123abc123" -H "Content-Type: application/graphql" your-host/graphql -d "{__schema{types{name}}}"`
4. Query it again but make a boneheaded mistake in the authorization header like I did, in particular adding a colon after `Bearer`, so something like `curl -H "Authorization: Bearer: abc123abc123" -H "Content-Type: application/graphql" your-host/graphql -d "{__schema{types{name}}}"`
5. See that both gave 200 responses
6. Compare the output (maybe `|wc -c` to compare length). See that the one with the bad authorization header returned fewer possible types but gave no error.

### Expected behavior

A 4xx-series response, probably 400 in this case.

### Actual behavior

A 200 response and reasonable-looking data, though not what was expected.

### Opinion

If there's an authorization header which wasn't understood, the likelihood is that the developer is an idiot like me and needs to be told about it before they spend an hour scratching their head and trawling logs.

I considered that it might have been parsed by Craft/Yii as a `Authorization: Bearer` header with value `abc123abc123` depending on parsing logic, and so wouldn't be seen as an authorization header, but I see in the logs that PHP has seen it as `HTTP_AUTHORIZATION` with `Bearer: abc123abc123`.

### Craft CMS version

4.0.x-dev at 38a1659

### PHP version

8.1.2

### Operating system and version

Linux 5.13.0

### Installed plugins and versions

n/a I think

**Comment by andris-sevcenko** [comment]
The [correct syntax](https://datatracker.ietf.org/doc/html/rfc6750#section-2.1) for a bearer token, as you noted, is without the colon. Since the authorization header can contain many different values for different schemes, it's not up to Craft to throw an error if an unrecognized type is present in the authorization header. For all Craft knows, maybe the webserver required a "Bearer:" token and just never bothered to strip the authorization header after allowing it.

As far as Craft is concerned, no bearer token passed, and Craft used the public schema. Similarly, if you meant to use "Basic" authentication and used "Basic:" instead you don't see web servers complaining about a malformed authorization header.

**Comment by tremby** [comment]
Makes sense. Fair enough. Thanks.
