### ISSUE TITLE
[3.x]: Entries not showing up in search results when phrase is associated with something from an asset field or an asset field within a matrix

### ISSUE THREAD

**Issue by piperhaywood** [craftcms/cms#10911]
# What happened?

## Description

When using the search form in a front end template or within the CMS directly, entries do not show up in search results when searching for a phrase that is within a field assigned to an asset that has been added to that entry.

In other words: I have an asset that has a searchable caption field. On my entry, I have a searchable asset field. When an entry has an asset with a caption, that entry doesn’t show up when I search for something that I know is within that caption.

This also happens when the asset field is nested within a searchable matrix. In my project, I have both use cases and neither are behaving as I would expect based on the search settings for these fields.

## Steps to reproduce

1. Create a text field such as “Caption”, set it to be searchable 
2. Create an asset volume and add your new “Caption” field created in step 1 
3. Create an assets field such as “Images” with the source set to your new asset volume from step 2, set it to be searchable
4. Create an entry type with your new assets field from step 3
5. Within your content, publish an entry of the type created in step 4 with an asset that has its caption filled out
6. In your templates, make sure you’ve got a search form somewhere and search from some term that is within your caption content. Alternatively, search within the Entries section of the CMS. The entry with the relevant image doesn’t show up.

## Expected behavior

Since all of the relevant fields are set to be searchable (the caption and the asset), I would expect the entry to show up in search results.

## Actual behavior

Entries do not show up for search results that should be relevant to a searchable asset field or a searchable asset field within a searchable matrix.

# Versions

## Craft CMS version

v3.7.27.2

## PHP version

v8.0.17

## Operating system and version

Darwin 21.4.0

## Database type and version

MySQL 5.7.32

## Image driver and version

GD 8.0.17

## Installed plugins and versions

- Isolate 1.4.4
- Redactor 2.10.5
- Retcon 2.3.0
- Typogrify 1.1.19

**Comment by brandonkelly** [comment]
This is currently expected. Relational fields only include the related elements’ titles in their search keywords currently.

We can [discuss making that configurable](https://github.com/craftcms/cms/discussions/new?category=ideas) perhaps, but it’s a little awkward either way, because the search keywords only get updated when the relational field value changes. They aren’t kept up-to-date as the related elements’ content changes.

If you want to show entries whose assets match a given search phrase, one way you could go about it is you could search the assets first, and get a list of matching asset IDs. Then fetch the entries that are related to the matching assets:

```twig
{% set assetIds = craft.assets()
  .search('caption:"the search text"')
  .ids() %}

{% if assetIds %}
  {% set entries = craft.entries()
    .section('mySection')
    .myAssetsField(assetIds)
    .all() %}
{% else %}
  {% set entries = [] %}
{% endif %}
```

Alternatively, you could create a new [Preparse field](https://plugins.craftcms.com/preparse-field) that stores the search keywords for the related assets, so they get registered as search keywords for the entry.

The Preparse field template would be:

```twig
{% set field = craft.app.fields.getFieldByHandle('myAssetsField') %}
{% for asset in element.myAssetsField.all() %}
  {{ field.getSearchKeywords(asset.myCaptionField, asset) }}
{% endfor %}
```

**Comment by piperhaywood** [comment]
@brandonkelly Ah, interesting, that does make sense. I guess I was confused since I hadn’t seen something along those lines in the docs, which is my fault. I missed the caveat / tip on [this page](https://craftcms.com/docs/3.x/searching.html#configuring-custom-fields-for-search). 

I don’t think it makes sense to make it configurable since it seems like it would make things overly complex, the solutions you mention above should work fine. Thanks for the clarification and tips!
