### ISSUE TITLE
[3.x] GQL and relatedToCategories returns nothing using a URI: 

### ISSUE THREAD

**Issue by cliveportman** [craftcms/cms#10956]
### Description
Graph QL entries queries using relatedToCategories with a URI don't return anything. It works fine with slug, and id, just not uri.

### Steps to reproduce

1. Query for entries related to a category in the built-in explorer, and use a URI to identify the category. 

```
query category($uri: [String]) {
  courses: entries(
    relatedToCategories: {uri: $uri}
  ) {
      title
  }
}
```

### Expected behavior
Related entries returned.

### Actual behavior
No entries returned.

### Craft CMS version

3.7.38

### PHP version

8.05

### Operating system and version

Linux 5.4.0-65-generic

### Database type and version

MySQL 8.0.21

### Image driver and version

Imagick 3.4.4 (ImageMagick 6.9.10-23)

### Installed plugins and versions

Amazon S3 1.3.0
Mailgun 2.0.1
Neo 2.13.4
Redactor	2.10.6
Super Table 2.7.1

**Comment by andris-sevcenko** [comment]
> Expected behavior
> Related category returned.

The `relatedToCategories` argument is used to narrow down whatever you're querying for by the relations. So, the query
```graphql
{
  entries(relatedToCategories: {uri: $uri}) {
    title
  }
}
```
would return any entries that are related to categories that match the URI. There's actually a [quite relevant example](https://craftcms.com/docs/3.x/graphql.html#relations) in the docs.

Does that clear things up a bit?

**Comment by cliveportman** [comment]
@andris-sevcenko That's exactly what I'm expecting. But nothing is returned. If, instead, I use:
```
{
  entries(relatedToCategories: {slug: $slug}) {
    title
  }
}
```

or

```
{
  entries(relatedToCategories: {uid: $uid}) {
    title
  }
}
```

or

```
{
  entries(relatedToCategories: {id: $id}) {
    title
  }
}
```

then the expected entries are returned. It's just an issue with URI.

**Comment by andris-sevcenko** [comment]
That's odd, as I was unable to reproduce this locally.

Can you try doing this in a twig template?
`{% set entries = craft.entries.relatedTo(craft.categories.slug(<SLUG>)).all() %}`, if memory serves.

Or, perhaps, just try searching for that category in GraphQL using the slug.

Also, are all the elements involved enabled for the given site and such?

**Comment by cliveportman** [comment]
Just searching for the category using a slug is fine:

```
query MyQuery {
  category(slug: "diplomas") {
    title
  }
}
```

But searching for the same category using the URI returns nothing:

```
query MyQuery {
  category(uri: "courses/type/professional/diplomas") {
    title
  }
}
```

**Comment by andris-sevcenko** [comment]
Hmm. Is this a multisite setup?

**Comment by cliveportman** [comment]
Yes.

**Comment by andris-sevcenko** [comment]
@cliveportman Ah, that will be it, then.

Queries defined by the `relatedTo*` argument in GraphQL are a bit of a cheating option we added, as it was impractical to pass element queries around as it is in Twig.

So, two things combine here:
1) Those arguments end up being parsed _before_ the query gets executed and the resulting IDs get injected into the `relatedTo` argument value. The key part here is that they invoke an element query.
2) When querying using GraphQL, unless you provide the `site` parameter, the _current_ site is being used. Which is the site that is resolved for the GraphQL endpoint.

So, I'm guessing you're firing this query against a different site (not `school`). You're doing the right thing by providing the `site` parameter to the original query, however, because the element queries executed based on `relatedTo*`  arguments are separate queries, they are executed against a different site, and Craft is unable to resolve it using the URI.

If you add `site` parameter to the `realatedToEntries` argument, does that get you the results you want?

**Comment by cliveportman** [comment]
Ah, that makes sense now. Aside from the fact I can use the slug without the site but not the URI. Which doesn't matter at all.
Thank you. I think you can close this.

**Comment by andris-sevcenko** [comment]
@cliveportman URIs can be different for a category in different sites, though, which might be the case here. It depends on the category group site settings.
Glad we got it solved!
