### ISSUE TITLE
[3.x]: Grapqhl error with @transform "webp" on .svg file

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/cms#11122]
### What happened?

Graphql crash when we try to transform to webp an SVG.

<img width="1919" alt="Screen Shot 2022-05-06 at 6 31 19 AM" src="https://user-images.githubusercontent.com/2158130/167115559-f17dd989-60bb-4479-a20f-eb27349b3d5b.png">

### Craft CMS version

3.7.41

### PHP version

8.1.4

### Operating system and version

Ubuntu

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting that. Fixed for the next release.

Although it is worth noting that each of your `@transform` directives will be applied separately to the asset. The first one will create a rasterized webp file with a max size of 1000×1000px, since no `width` or `height` is specified. The second one will give you the `url` of an unmodified SVG image, since no `format` is specified.

If you want a webp image with a 100px width, you will need to combine the parameters into a single `@transform` directive.
