### ISSUE TITLE
[4.x]: Image transform format 

### ISSUE THREAD

**Issue by pette87** [craftcms/cms#11161]
### Description

When I set format webp - transform will not generate

### Steps to reproduce

`<picture>
	{% for width in widths %}
		<source type="image/webp" srcset="{{ block.image.one.getUrl({ width: width , format: 'webp' }) }}" media="(min-width: {{ width }}px)"> ....`

![image](https://user-images.githubusercontent.com/11199719/167390991-684dcee3-183a-4db5-b97c-589b9394ef77.png)

this line is working with setup a transform in backend as webp

`<source type="image/webp" srcset="{{ block.image.one.getUrl('fullWidth') }}" media="(min-width: 1536px)">`

### Craft CMS version

4.0.1

### PHP version

8.1

### Image driver and version

GD 8.1.2 and Imagick 3.7.0 (ImageMagick 7.1.0-26)

### Installed plugins and versions

complete fresh installation without plugins

**Comment by brandonkelly** [comment]
If WebP images aren’t generating, most likely that’s because your copy of ImageMagick wasn’t compiled with support for it.

Tested locally and WebP generation is definitely working on my end, in Craft 4.

If you need additional help, you can write into support@craftcms.com and we can help troubleshoot.

**Comment by brandonkelly** [comment]
Just discovered a bug where the `format` param wasn’t being respected for dynamically-defined transforms, unless the `generateTransformsBeforePageLoad` config setting was enabled. The transforms were still generating, just without modifying the image format.

Not clear if that’s what your issue was, but seems likely.

You can test the fix on your end by changing your `craftcms/cms` requirement in composer.json to `dev-develop as 4.0.2`, and running `composer update`.
