### ISSUE TITLE
[4.x]: Can't retrieve an entry's draft

### ISSUE THREAD

**Issue by claus0618** [craftcms/cms#11237]
### Description
I'm trying to get a draft by its **draftId** that is not associated with a published entry yet but I keep getting null, it was working fine in craft 3.

### Steps to reproduce

1. New Entry
2. Save Draft
3. Execute
  3.1 `craft.entries().draftId(draftId).one()` OR
  3.2 `craft.entries().section('sectionHandle').draftOf(false).all()`

### Expected behavior
Element Result

### Actual behavior
null

### Craft CMS version

4.0.2

### PHP version

8.0.17

### Operating system and version

macOS Monterey 12.3.1

### Installed plugins and versions

-

**Comment by Wiejeben** [comment]
Could the entry possibly be disabled? Have you tried adding `.status(null)` before `one()` or `all()`, this will return entries with any status.

**Comment by claus0618** [comment]
The draft is **not disabled**, but by adding the `status(null)` to the query I was able to get the entry, and if I check its `{{ entry.status }}` it returns `enabled`. Is this going to be the normal behaviour for drafts?

<img width="572" alt="image" src="https://user-images.githubusercontent.com/788122/168819572-c3084128-bc17-4846-a22a-b0f52dbe5e22.png">

**Comment by brandonkelly** [comment]
Most likely, it didn’t show up without `status(null)` because the Post Date is blank. Craft 4 no longer sets a Post Date on new entries until they’re saved without their initial draft status.

The default `status` value for entry queries is `live`, which means the entries must be:

- enabled,
- with a Post Date in the past, and
- without an Expiry Date, or with an Expiry Date in the future.

`status(null)` skips each of those checks. You could also go with `status('enabled')` which only cares about whether the entries are enabled, but ignores their Post/Expiry Date values.

**Comment by claus0618** [comment]
Got it. 

FYI putting `status('enabled')` instead of `status(null)` still does not bring the draft entry, even tho when I print the `{{entry.status}}` it shows it as **enabled**

This is the part that is still confusing for me, if I'm doing the following query, I should be able  to get the draft?

`craft.entries().draftId(draftId).status('enabled').one()`

**Comment by brandonkelly** [comment]
@claus0618 If the draft is marked as enabled, then yes that should work. I just tested locally and it works on my end.

Is this a multi-site install? If so, make sure that the entry is enabled for the site you are accessing the template from.
