### ISSUE TITLE
Default Asset Folder

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1127]
> Created by: Anonymous (alan@theskyfloor.com) on 2015/03/10 17:00:50 +0000
> Votes at time of UserVoice import: 3

-----------------------------------

It would be great if you could specify a default folder for asset upload but still be able to browse around to other locations if need be... this would allow the settings for front end upload work similarly on the backend with the exception that you can see and still navigate in the full asset modal (with the sidebar, etc).

**Comment by cquinders** [comment]
This feature could be implemented using the already available *default upload folder* setting on an asset field.

Currently, if I specify the default upload folder on an asset field inside a matrix block like `{owner.section.handle}/{owner.postDate|date('Y')}/{owner.slug}/` for example, and then restrict uploading to this folder only, the asset modal will show this folder when it is launched. But because I restricted uploads to this folder only, the sidebar is missing on the modal.

It would be nice if the asset modal could show the *default upload folder* configured on an asset field if it is not restricted to this folder, too, and let me navigate away with the sidebar if I wish to.

**Comment by brandonkelly** [comment]
This is already possible via the Default Upload Location setting.
