### ISSUE TITLE
[4.x]: Deleting a field without first removing it from field layouts logs an ArgumentException "Invalid field UID"

### ISSUE THREAD

**Issue by mmikkel** [craftcms/cms#11333]
### Description

If a custom field is deleted, without first removing it from a field layout it is part of, the following `yii\base\InvalidArgumentException` is logged (not thrown) when that field layout's element is queried on the frontend. The error is also logged for (from what I can tell) all control panel requests:  

```
yii\base\InvalidArgumentException: Invalid field UID: 21423465-24a5-4823-8bcd-c34b3b598306 in /path/to/project/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php:106
```

**Resaving the field layout(s) that used to contain the now-deleted field, makes the error go away.**

Full stack trace is [here](https://pastebin.com/2sKsE6T6). I'm not able to reproduce this on Craft 3.7.43.

![CleanShot 2022-05-27 at 09 57 20](https://user-images.githubusercontent.com/298510/170657007-e67eb008-2d69-4adf-881c-29ea278789f1.png)

### Steps to reproduce

1. Add a custom field to a field layout, (e.g. add a Plain Text field to an entry type's field layout)
2. Delete the custom field
3. Pop open the debug bar inside the control panel, or when viewing the element on the front end, and notice the error logged
4. Resave the field layout that used to contain the deleted field
5. Pop open the debug bar again and observe that the error has gone away

### Craft CMS version

4.0.3

### PHP version

8.1.4

### Operating system and version

macOS 12.4

### Database type and version

MySQL 5.7.37

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-29)

### Installed plugins and versions

None

**Comment by brandonkelly** [comment]
This should also be the case in Craft 3 as the relevant code hasn’t changed at all – here it is from v3:

https://github.com/craftcms/cms/blob/7c58e9774db289725803c60f32b0d862a6e6e36c/src/fieldlayoutelements/CustomField.php#L108-L110

https://github.com/craftcms/cms/blob/7c58e9774db289725803c60f32b0d862a6e6e36c/src/models/FieldLayoutTab.php#L140-L146

Obviously the ideal behavior would be that we go and find all the field layouts and remove the deleted field from them immediately. I just spent some time attempting that, but it wasn’t feasible: once the field is deleted, we can’t tell which field layouts would have had it, because of this behavior where its layout elements get ignored. We could manipulate the project config directly, but not without potentially triggering a lot more changes. (Editing an entry type’s field layout in the project config triggers the entire entry type to be resaved, for example.)

So anyway, I’ve just tweaked it to have `CustomField` throw a special `FieldNotFoundException` in this case (fitting for Craft 4.0.4!), which gets special handling by `FieldLayoutTab` where it’s simply ignored rather than logging a warning.

**Comment by brandonkelly** [comment]
Craft 4.0.4 is out now with that change ✨
