### ISSUE TITLE
[4.x]: Changing between entry types doesn't update the fields

### ISSUE THREAD

**Issue by ThinkGraphical** [craftcms/cms#11537]
### Description

Changing between entry types in the backend ("Create an entry" view) doesn't update the view (fields).

### Steps to reproduce

1. Create a section with multiple entry types, attach different fields to each entry type
2. Create a new entry for that section & change the entry type in the right side panel

### Expected behavior

You would expect to see other fields when changing the entry type.

### Actual behavior

It looks like the view isn't updating and keep showing the fields from the first entry type.

### Craft CMS version

4.1.0.2

### PHP version

8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Are you disabling the `autosaveDrafts` config setting in `config/general.php`? If so that’s your issue. The setting is not really needed in Craft 4 thanks to several performance improvements around draft/revision creation, and prevents entry type switching and Live Preview from working properly, so it has been deprecated and will be fully removed in Craft 5.

**Comment by nateclonch** [comment]
I was having the same issue. Disabling the "Field Manager" plugin was my solution.

**Comment by nateclonch** [comment]
I'm not sure exactly what resolved the issue, but for me the issue resolved itself after disabling and re-enabling a couple plugins ("Field Manager" and "Control Panel Nav").

**Comment by brandonkelly** [comment]
Thanks @nateclonch. That sounds promising. I’ll go ahead and close for the time being. @ThinkGraphical if you have any more info you can provide, feel free to reply.
