### ISSUE TITLE
[4.x]: Attribute `label` of a dropdown field within a table field is not accessible

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#11549]
### Description
I have a table field with two columns: `type` (Dropdown field) and `url` (URL field):
```
<ul>
	{% for option in group.field | filter(option => option.url is not empty) %}
		<li>
			{% set attr = {
				href: option.url
			} %}
			<a {{ attr(attr) }}>
				{{ option.type.label }}
			</a>
		</li>
	{% endfor %}
</ul>
```

`option.type` is a string, and does not return the label of the Dropdown. It's just returning its `value`.

### Expected behavior

`option.type.label` should return the label of the selection in Dropdown.

### Actual behavior

It's just returning its `value`.

### Craft CMS version

4.1.0.2

### PHP version

8.1

### Database type and version

MySQL 5.7.34

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is working as intended. Dropdown columns within Table fields are not meant to be nearly as robust as dedicated Dropdown fields.

If you need access to their labels, your best bet would be to use [Super Table](https://plugins.craftcms.com/super-table) instead of the native Table field type.

**Comment by romainpoirier** [comment]
Ok, thank you. Doesn't it sound not so basic to be able to just print out the `label` + `value` and nothing else more?
That's a bit overkill to have to use a plugin only for this. I'll have to stick with the `| title` filter, or something like that...

**Comment by romainpoirier** [comment]
I'm not sure to understand how this would break.

Current value: `option.type` (string)

Suggestion:
- `option.type` (string): keep the current expected result, so no breaking change
- `option.type.label` (string): add the label of the option
- `option.type.value` (string): which is equal to the shorthand option.type (string)

This is in the context of looping trought `group.field` (see example), not trying to get directly the selected value without looping.

**Comment by brandonkelly** [comment]
Assume here that `option` is the row, and `type` is the column handle?

The value cannot both be a string _and_ an array with `label` and `value` options. We have to pick one or the other.

Dropdown fields make it possible because their values get set to a `craft\fields\data\SingleOptionFieldData` object, which has `value` and  `label` properties, as well as a `__toString()` method that returns the value (in case the object is referenced as a string). Switching to that would also be a breaking change though. For example if you are JSON-encoding the row, you would get a lot more data all of a sudden than a simple string. So it’s something to maybe consider down the road, but would need to be done as part of a major release like Craft 5.

**Comment by romainpoirier** [comment]
> Assume here that option is the row, and type is the column handle?


Yep, `option` is an iteration of the loop. And `url` or `type` are the field's handles.

> For example if you are JSON-encoding the row, you would get a lot more data all of a sudden than a simple string.


Ok thank you for all of these explanations, I understand.
If these additional data could be added to another node of the object, or if we could query their values later using a function, it would be nice.
