### ISSUE TITLE
[3.x]: Cache tags not working when running in console, eg: queues

### ISSUE THREAD

**Issue by gixxy22** [craftcms/cms#11551]
### Description

When a cache tag is used to cache the output of heavy queries, the cache is used when the queue runs in admin (runQueueAutomatically), but when the queue is run via console(cron), the cache isnt used and the heavy queries are always run.

### Steps to reproduce

1. for example, with feedme, create a feed with a twig cache tag to cache a particularly expensive query. 
2. If runQueueAutomatically is enabled the queue will run from admin and will use the cache tags.
3. Run the same feed with cron, and the speed will be much slower due to not utilising the cache

If for example, I want to fetch some globals to iterate over in a feedme feed, and I have 100k rows in the feed. Console/cron will run 100k of the same queries, whereas admin will only run it once and cache it.

The performance is night and day on large feeds.

### Craft CMS version

Craft Pro 3.7.46

### PHP version

8.0.20

### Operating system and version

Linux 4.18.0-348.23.1.el8_5.x86_64

### Database type and version

MySQL 10.6.8

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-33)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
That was working as intended, because template caching is scoped to the requested URI by default. Although there could have been an exception for `{% cache %}` tags using the [`globally`](https://craftcms.com/docs/4.x/dev/tags.html#globally) param.

I’ve just made that change, and got it into Craft 3.7.47 and 4.1.1 – both already tagged and released.
