### ISSUE TITLE
[4.x]: Renamed field labels keep old value in the source indexes

### ISSUE THREAD

**Issue by jesuismaxime** [craftcms/cms#11584]
### Description

I don't think it's a bug, but surely something unexpected when you rename a field label using the fieldlayout. Here it is :

Once customized/renamed, a field checked in a source index displayed the non-renamed label instead of the override value. 

Can't find any issue related to this, if there's already one, feel free to merge!

### Craft CMS version

4.1.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is expected. We can’t use the overridden label because the same field might actually be used across multiple field layouts within the same element source. For example if you’re viewing a section than has two entry types, those entry types may both be pulling in the same field, each with a different label. So we always just go with the main field label in that context.

**Comment by jesuismaxime** [comment]
But only the fields of the first entryType are available in the checklist to customize the columns (I am not talking about custom sources, a simple channel index page - although both use propably the same model)

**Comment by brandonkelly** [comment]
The native entry sources are based on the sections – each of which can have multiple entry types.
