### ISSUE TITLE
[4.x]: Lightswitch colors are no longer easily distinguishable

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#11653]
### Description

Recently, the colors for an activated vs deactivated lightswitch in the control panel have become dimmer, making it difficult to glance at. I don't have vision deficiencies and I struggle with it - especially on monitors that aren't as bright as my Mac's display.

![image](https://user-images.githubusercontent.com/3810939/180283982-ecf5d7af-c2dd-41c0-a106-0bfe1c2c8b68.png)

### Craft CMS version

4.1.4.1

### Related Conversations
- [Discord](https://discord.com/channels/456442477667418113/755149944247025857/999682759859650670)

**Comment by brandonkelly** [comment]
Looks like this was an unintended side effect of 84e10b797bab2a29017279db422dedb6a00a268c + 6a6199358d6ddf728d1b94b530f923075b0535cc. Just rolled lightswitches back to the lighter green color for the next release.

**Comment by brandonkelly** [comment]
Turns out the darker green was intentional, to achieve a 3:1 contrast ratio between the green and the handle. The green needed to be darker than normal because the handle became tinted gray when focused, but that style has been removed (eee66a07669915e1dd48cac465fdc8cc03fc43e1). Even then it wasn’t quite 3:1 so we’ve _slightly_ darkened the green color from where it was originally (#11699).

4.2.0 is out with each of those changes.
