### ISSUE TITLE
[4.x]: Question: What cause a `no_trials` response on plugins index page?

### ISSUE THREAD

**Issue by jesuismaxime** [craftcms/cms#11704]
### What happened?

We'got 2 websites in development with Craft4 and we got a notice banner in the top of our stagings CP stating that some plugin license keys need a payment.

`devMode` is set to `true` but for security/dev reasons, `allowAdminChanges` and `allowUpdates` are set to `false` on the staging environments, what are the other settings/contexts that you check on the pluginManager?

### Craft CMS version

4.2.0

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
It’s based on the server name you’re accessing Craft from. If you’re on a public domain, license validation is enforced; otherwise trials are allowed.

See https://craftcms.com/knowledge-base/how-craft-license-enforcement-works#how-do-we-determine-craft-is-running-on-a-public-domain for a full explanation of what we consider “public domains”.
