### ISSUE TITLE
[4.x]: Entries field on multisite project references incorrect instance of propagated entry after explicitly selecting specific site.

### ISSUE THREAD

**Issue by brionwolf** [craftcms/cms#11725]
### Description

I have a multisite project with a number of sections. Some sections save entries only to sites they were created in, and some are propagated to all sites with fields translated for each site _(namely the homepage for each site)_. If I have an entries type field and want to reference an entry from another site, there is no issue adding an entry created in a single site, but if I try to select an entry that has been propagated to all sites _(Like one of the singles)_, then field will save and reference the instance of the entry from the first site I created in the project _(even if I explicitly select an alternate site within the entries dialogue, and select the desired entry)_.

### Steps to reproduce

1. **Setup:** A project with multisite, and several sites. Include at least one Section of type `single` that is propagated to all sites with translated fields for each of those sites.
2. Add a field of type `entries` that can select that single, with options "Show the site menu". Add the field to a section that is saved only to a specific site.
3. Try to add the entry from step 1 to the field while explicitly selecting an alternate site from the multisite dropdown of the entries selection dialogue.
4. Save changes, and try to view the entry that was previously selected.

### Expected behavior

- Expect to see the instance of the entry from the site it was selected from, with content from that selected site.

### Actual behavior

- The selected entry now references the instance of the entry from the first site created/added to multisite, not from the site we selected.
- Trying to reference the field within twig will also return the instance of the entry from the first site from multisite, and not the site we wanted.

### Notes

Apologies if I'm missing something, if this is expected behavior, or if it's more of a feature request. Happy to provide additional details if needed.

### Craft CMS version

4.2.0.2

### PHP version

8.1.8

### Operating system and version

MacOS 12.5

### Database type and version

MySQL 8.0.29

### Image driver and version

GD 8.1.8

### Installed plugins and versions

Plugin | Version
----|----
Feed Me | 5.0.4
Neo | 3.2.2
SEOmatic | 4.0.7
Site Redirects | 4.0.2
Super Table | 3.0.0

**Comment by brionwolf** [comment]
Additionally: report mentions only `singles` in the **steps to reproduce**, but this occurs when trying to relate to entries from `structure` and `channel` type sections propagated to all sites, as well as categories on category fields.

**Comment by brandonkelly** [comment]
Relationships in Craft don’t ever track the target element’s site. The site your related entries will be queried in by default depends on the field’s “Relate entries from a specific site?” setting (under **Advanced**).

If that setting is enabled, the chosen site will be used. Otherwise the source element’s site will be used.

Examples:

Target site setting | Source element site | Default query site
-- | -- | --
_None_ | Site A | Site A
_None_ | Site B | Site B
_None_ | Site C | Site C
Site A | Site A | Site A
Site A | Site B | Site A
Site A | Site C | Site A

That’s just the default though. You are free to override the target site using the `site` or `siteId` query params:

```twig
{% set relatedEntry = entry.myRelationField
  .site('siteB')
  .one() %}
```

Or even have the query pull the entry from _any_ site, with a specific order of preference (say, the source element’s site above all others), using the `unique` and `preferSites` params:

```twig
{% set relatedEntry = entry.myRelationField
  .site('*')
  .unique()
  .preferSites([entry.siteId])
  .one() %}

**Comment by brionwolf** [comment]
Thank you for the clarification!
