### ISSUE TITLE
Garbage Collection not deleting users from DB [4.x]: 

### ISSUE THREAD

**Issue by ameliagroen** [craftcms/cms#11853]
### Description
I deleted all the users in a particular user group using the CMS, then I ran garbage collection. However, I can still see all the users in the database (with their sensitive information that I was specifically trying to get rid of). Is GC not expected to pick deleted users up? And if not, how do I safely delete all these users? (There's about 2000 of em)

### Steps to reproduce

1. Delete users in CMS
2. Run `craft php gc` in the console
3. Check user table to see if users are in fact removed from db

### Expected behavior

No more deleted users in the database

### Actual behavior
All the users are still in the db

### Craft CMS version

4.2.3

### PHP version

8.1.1

### Operating system and version

MacOS Catalina 10.15.6

### Database type and version

MySQL 5.5.5-10.4.12-MariaDB-1:10.4.12+maria~bionic

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
When you delete users, they are only soft-deleted initially, meaning their data will stick around in the database for a while longer, in case the deletion was accidental.

You can fully (“hard”) delete the user accounts from the UI, by selecting the “Trashed” status, selecting the users, and pressing “Delete permanently”.

<img width="172" alt="The status menu for a user index, with the “Trashed” option highlighted." src="https://user-images.githubusercontent.com/47792/187719130-881c986d-a866-406d-bbad-6dac92c20fbe.png">

<img width="301" alt="A soft-deleted user selected within a user index, showing the “Delete permanently” option above them." src="https://user-images.githubusercontent.com/47792/187719186-1b1395f7-eaca-4b42-a5b2-d2ad23dafad3.png">

By default, garbage collection will only hard-delete elements that were soft-deleted some time ago, per the [`softDeleteDuration`](https://craftcms.com/docs/4.x/config/config-settings.html#softdeleteduration)` config setting. You can tell it to delete **all** soft-deleted elements by passing the `--delete-all-trashed` option.

```sh
php craft gc --delete-all-trashed
```

Or if you run `gc` interactively, answer `yes` to the first question:

```sh
> php craft gc       
Delete all trashed items? (yes|no) [no]:yes
Running garbage collection ...
```

That said, we did find a bug related to this, which is that element caches weren’t getting cleared when elements were hard-deleted via garbage collection. So they might still show up in element index pages for a little while even though they are fully deleted. That’s fixed now for the next Craft 3 and 4 releases. (6ec9cc3c3a6e95a7c1d5305ed01faebaf7ad4d39) It doesn’t seem like that was your main issue though, since you said the data was still present in the DB.
