### ISSUE TITLE
[3.x]: Cannot empty categories field

### ISSUE THREAD

**Issue by clarisse-catacutan** [craftcms/cms#11869]
### Description
When trying to delete all the categories from the categories field, it doesn't do so and just brings back the old categories. But when you try and delete just one category from the categories field, it gets deleted.

### Steps to reproduce

1. Create a categories field and assign values to it.
2. Create a form with checkboxes to allow you to delete and add categories into the categories field.
3. Uncheck all checkboxes to empty out your categories field.
4. It will return with the previous value.

### Craft CMS version

3.7.52

**Comment by brandonkelly** [comment]
Make sure your form has a hidden input for your Categories field before any other inputs for the field, like [the docs example](https://craftcms.com/docs/3.x/categories-fields.html#saving-categories-fields):

```twig
{# Include a hidden input first so Craft knows to update the existing value
   if no checkboxes are checked. #}
{{ hiddenInput('fields[myFieldHandle]', '') }}
```

Otherwise, no post data will be sent for the Categories field when nothing is selected, and Craft will just assume that the field value should remain unchanged.
