### ISSUE TITLE
[4.x]: disallowRobots config doesnt listen to env var CREAFT_ENVIROMENT

### ISSUE THREAD

**Issue by williamhibberd** [craftcms/cms#11935]
### Description
Still getting the header `X-Robots-Tag: none, noimageindex` in a production environment with config settings:

```
    'production' => [
        'disallowRobots' => false,
        'devMode' => false,
    ],
```

Seem like the system isn't listening to `CRAFT_ENVIRONMENT` in .env and when I add both 
```
ENVIRONMENT=production
CRAFT_ENVIRONMENT=production
```
to my .env file everything works as it should.

### Expected behavior
`ENVIRONMENT=production` shouldnt be needed in .env file

### Actual behavior
`ENVIRONMENT=production` and `CRAFT_ENVIRONMENT=production` needed in .env file

### Craft CMS version

4.2.4

### PHP version

8.1.8

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Craft’s core code has only ever checked for `CRAFT_ENVIRONMENT`:

https://github.com/craftcms/cms/blob/d27e480afce05193d3ec253970b7807b011d752e/bootstrap/bootstrap.php#L92

The [`craftcms/craft`](https://github.com/craftcms/craft) starter project [used to](https://github.com/craftcms/craft/blob/c041b543fdad1b85785b5c61035d0bc286bd89d8/bootstrap.php#L22) define an `ENVIRONMENT` variable in `.env.example` set a `CRAFT_ENVIRONMENT` constant based on it, in `bootstrap.php` (and previously, in `web/index.php`). However that was [removed](https://github.com/craftcms/craft/commit/34e84a1edb6af4fd1ec59bce45060f5e1f6e807c) in favor of `CRAFT_ENVIRONMENT` alongside the release of Craft 4.

Updates to `craftcms/craft` have no way of affecting existing installs, though, so that change will only be present on new projects created after May 4, 2022.

Perhaps you created a new project and pushed to production, just assuming it still would support an `ENVIRONMENT` variable without checking `.env.example`?
