### ISSUE TITLE
Date/Time/Year

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1194]
> Created by: Rob (rob@layermade.com) on 2015/07/19 22:22:24 +0000
> Votes at time of UserVoice import: 2

-----------------------------------

The date/time is perfect for say, an upcoming event but not so great for historic or future dates. I'd suggest adding a "year only" option, or a better way to navigate through yearly views.

**Comment by tsawitzki** [comment]
+1 to this one! Something that simple shouldn’t rely on 3rd party plugins.

I am currently dealing with a portfolio that spans many projects from the last three decades. 

Craft’s „multiselect“ input is a bit of nightmare in terms of usability for editors, especially since it natively only shows 4 entries at first sight, then you have to scroll in the tiny list.
So I am now trying to switch to radio buttons, but having +30 radio buttons with year-options on the BE page seems quite dull, too.

A super-simple Dropdown menu, kind of like a "singleselect" field next to the "multiselect" one would make life much easier here. 

Or simply, as @takobell suggested, a native "Year" selector or fast option in the already implented Datepicker.

**Comment by yellostudio** [comment]
We have a few clients who have requested that a year can be selected rather than cycling through month after month trying to get it - irrespective of the fact you can type it in.

**Comment by brandonkelly** [comment]
A simple Number field could also work for storing years, I imagine.
