### ISSUE TITLE
PHP compile error when trying to update [3.x]: 

### ISSUE THREAD

**Issue by danfathom** [craftcms/cms#12126]
### Description
I'm attempting to update craft from 3.7.48 to 3.7.56, but keep getting an error that says "PHP Compile Error – Cannot use ::class with dynamic class name". See screenshot below with full error.

![screencapture-localhost-8888-office-principles-web-public-fitcms-2022-10-14-09_47_19](https://user-images.githubusercontent.com/92588022/195804451-310e1e23-1c1e-414b-9344-f3ecddc3b015.png)

I have attempted updating with composer and with the dashboard in the CMS but both result in this error. I also get this error when attempting to update any of the plugins on the site.

Do you have any ideas how to fix this?

### Craft CMS version

3.7.56

### PHP version

7.4.12

### Operating system and version

Darwin 16.7.0

### Database type and version

MySQL 5.7.32

### Image driver and version

GD 7.4.12

### Installed plugins and versions

Agent - 1.2.0
Feed Me - 4.5.3
Redactor - 2.10.10
Redirect Manager - 1.1.1
SEOmatic - 3.4.36
Super Table - 2.7.2
Typed link field - 1.0.25
Wheel Form - 2.7.2

**Comment by i-just** [comment]
Hi, thanks for reaching out. The problem lies with the SEOmatic plugin (or rather with twigfield that SEOmatic uses and only occurs when you're on PHP 7), if you try to update it above version 3.4.32. I can see that you already found the issue that was raised for it. 

Until it gets fixed, you can lock your SEOmatic version to 3.4.32 by making sure the `"nystudio107/craft-seomatic"` line under `require` in `composer.json` reads: `"nystudio107/craft-seomatic": "3.4.32"`. 

Once you do that, you can run `composer update` or trigger update from the control panel and Craft CMS will get updated, but SEOmatic won't. Once there's a fix for https://github.com/nystudio107/craft-seomatic/issues/1220, you can unlock the updates of SEOmatic by changing it to `^3.4`.

Hope this helps!

**Comment by khalwat** [comment]
This has been fixed.

Addressed in: https://github.com/nystudio107/craft-twigfield/commit/bff508e2e239fd55b8a17ea56fc60db5e655f418

Released as Twigfield 1.0.15: https://github.com/nystudio107/craft-twigfield/releases/tag/1.0.15

You can update to it by doing:

```
composer update nystudio107/craft-twigfield
```

**Comment by khalwat** [comment]
Anyone who had this issue, and updated to the latest Twigfield, if you could affirm that it has fixed the issue for you, I'd appreciate you posting that here.

**Comment by danfathom** [comment]
I updated yesterday and no longer had the twigfield error
