### ISSUE TITLE
[4.x]: getIdentity() returns different user?

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#12164]
### Description

So we ran into a bit of a weird issue. We have the following:
- User clicks a button to export a bunch of entries
- We push that task to a queue job
- When the file is ready we have a function to e-mail that file to the currently logged-in user (under the assumption that is the user requesting the export)

We're using this code to send the e-mail:

```
$currentUser = Craft::$app->getUser()->getIdentity();
$message = new Message();
$message->setTo($currentUser->email);
```

What happend this time is that the export was sent **to _another_ user**. (who was also logged in at the time)

---

We've been running this "pattern" for handling large custom exports for a while and this is the first time we've seen something like this.

Could this be caused by the fact that the identity check happens during the execution of the job?

### Craft CMS version

4.2.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Jobs have no memory of who was logged in when they were pushed to the queue. If you have [`runQueueAutomatically`](https://craftcms.com/docs/4.x/config/general.html#runqueueautomatically) still set to `true`, there’s a pretty good chance it will be the same user, since an Ajax-based queue runner will be kicked off on the subsequent control panel request. However if there’s already an active queue runner, the job will be executed by that original runner instead – which may not have been triggered by the same user if 2+ people are signed in at the same time.

Also if `runQueueAutomatically` is _disabled_, then no one will be signed it at all, since queue runners are typically created by a cron job or daemon in that case.

If your job needs to send an email, you should store the logged-in user’s ID on the job itself via a new `$userId` property, and fetch that user from `execute()` rather than trusting `User::getIdentity()`.

**Comment by janhenckens** [comment]
> If your job needs to send an email, you should store the logged-in user’s ID on the job itself via a new `$userId` property, and fetch that user from `execute()` rather than trusting `User::getIdentity()`.

That's how we "fixed" it.

Thanks for clearing things up!
