### ISSUE TITLE
[4.x] Upgrade from 4.2.7 to 4.3.0 destroys images

### ISSUE THREAD

**Issue by anbod-io** [craftcms/cms#12210]
### What happened?
[4.x]: I've just updated my site from Craft 4.2.7 to 4.3.0 and it seems that there is something very toxic in the update somewhere. After the upgrade I was seeing that several images were no longer being rendered.I then re-indexed my image assets, and afterwards no images at all were being rendered on the site.I think this would have already been reported from the field if this were a native image/transform problem, so without any investigation at all I am going to assume the problem is because I use ImageOptimize.There appears to be a little fight going on between ImageOptimimize and Craft 4.3.0

### Steps to reproduce

1. Upgrade Craft from 4.2.7 to 4.3.0

### Expected behavior
The site behaves normally, with whatever new functionality comes with the update

### Actual behavior
Images no longer render on the site.

### Craft CMS version

4.2.7 (Pro)

### PHP version

8.1.11

### Operating system and version

Linux 5.10.0-18-amd64

### Database type and version

MySQL 5.7.39

### Image driver and version

Imagick 3.6.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

- Asset Count 2.0.0
- Asset Usage 3.0.0
- Cloner 2.0.3
- CP Field Inspect 1.4.4
- Digital Download 2.2.1
- Environment Label 4.0.2
- Field Manager 3.0.4
- Freeform 4.0.6
- GDPR Cookie Consent 4.0.4
- ImageOptimize 4.0.2
- MatrixMate 2.1.1
- Navigate 3.0.2
- Obfuscator 1.1.1
- PDF Transform 2.0.0
- Redactor 3.0.2
- Redactor Tweaks 3.0.0
- SEO v4.0.3
- Super Table 3.0.2
- Tweet Feed 4.1.0.1
- Typogrify 4.0.0
- Wordsmith 4.0.1

**Comment by thijskaspers** [comment]
Can confirm. After disabling the "ImageOptimize" plugin, images are working as they should.

**Comment by j0h4n3s** [comment]
Can confirm as well. I've reported the issue @khalwat https://github.com/nystudio107/craft-imageoptimize/issues/360

**Comment by brandonkelly** [comment]
This was due to an unintended breaking change in 4.3.0, where `Asset::getUrl()` was respecting plugins which set `$event->url = null`, as Image Optimize is doing (https://github.com/craftcms/cms/commit/5c837e43ec2742571a1940f0245d4789bb33ace1).

Fixed for the next Craft 4 release (https://github.com/craftcms/cms/commit/3f00b8d3efb7e8ee1b0a2e20018c1d802c0b2ed8).

**Comment by anbod-io** [comment]
Outstanding, thanks for such a quick response!

**Comment by mightyfineyall** [comment]
@brandonkelly Not sure this is just a plugin issue - I use a custom twig function to render our imagery, and updating to 4.3 just broke asset indexes on a staging site. I had to define the webroot alias in general.php and then add the full path in .env in order to get it to index correctly again. It still broke all my asset relations in entries (thankfully not that many) and left a full /srv path in the assets folder: 
![image](https://user-images.githubusercontent.com/48531847/198339179-93653200-c0e5-4a1c-a44a-12727c5998d3.png)

**Comment by brandonkelly** [comment]
@mightyfineyall Not really sure what to make of that, but _probably_ unrelated to this issue? Can you please post a new issue with as much detail as you can think of:

- What was your `@webroot` alias set to, to begin with?
- Any relevant `.env` values for defining paths/URLs
- What are your filesystems’ Base Path settings set to?
- What is `/srv`?
- What happened after updating to 4.3?
- What all did you change when attempting to fix this?
- Anything else you can think of that might be relevant.

**Comment by brandonkelly** [comment]
Craft 4.3.1 has been released with the fix for ImageOptimize.
