### ISSUE TITLE
[3.x]: Unable to upload Assets images to AWS load balancer

### ISSUE THREAD

**Issue by noor8380** [craftcms/cms#12307]
### Description
The assets image uploads hang when an image upload is attempted.
It simply hangs and there is a system error.

### Steps to reproduce

1. Entries - Upload image to photo field

### Expected behavior
The image should be uploaded.

### Actual behavior
The image upload hangs.
See screenshot here: https://tinyurl.com/2cdn8mcc

### Craft CMS version

Craft Pro 3.7.59

### PHP version

8.0.25

### Operating system and version

Linux 5.10.147-133.644.amzn2.x86_64

### Database type and version

MySQL 10.7.6

### Image driver and version

GD 8.0.25

### Installed plugins and versions

Calendar Links	2.0.2
Control Panel Nav	3.0.17
CP Field Inspect	1.4.0.1
Embedded Assets	2.10.7
Freeform	3.13.20
Instagram Feed	1.1.8
Instagram Media	1.0.0
Navigation	1.4.25
Reasons	2.3.1
Redactor	2.10.10
Retcon	2.6.0
SEO	3.7.4
Site Switcher	2.2.0
Sprout Fields	3.8.5
Super Table	2.7.3
Typed link field	1.0.25
Wheel Form	2.7.2

**Comment by noor8380** [comment]
When we disabled the load balancer, the image uploads started working.

**Comment by brianjhanson** [comment]
I'm going to close the issue since it sounds like you've tracked it down to some config with your load balancer, but I'm here if you have more questions. 

If you look a the XHR request coming back when you try to upload you'll likely see an error that might have more specific clues. There also could be more information in the `storage/logs` files.
