### ISSUE TITLE
[4.3.3]: Not able to edit custom element types such as freeform or cal events submissions

### ISSUE THREAD

**Issue by amici-infotech** [craftcms/cms#12352]
### Description
I have recently upgraded from v4.2.7 to v4.3.3. After upgrade, I am not able to edit Freeform submissions or Calander events or any custom element type that uses Element view layout. Basically, it misses Edit link on element list table.

![image](https://user-images.githubusercontent.com/20450552/202893231-8a895f75-5326-442d-a5a2-e06a1f001a6a.png)

### Craft CMS version

4.3.3

### PHP version

8.1.9

### Operating system and version

Darwin 21.6.0

### Database type and version

MySQL 8.0.30

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-46)

### Installed plugins and versions

- Button Box 4.1.0
- CP Field Inspect 1.4.4
- Calendar 4.0.0
- Colour Swatches 4.2.1
- Freeform 4.0.7
- Icon Picker 2.0.0-beta.5
- Imager X 4.1.7
- Inventory 2.2.0
- Maps v4.0.3
- MatrixMate 2.1.2
- Minify 4.0.0-beta.2
- Mix 1.6.0
- Navigation 2.0.11
- Neo 3.5.2
- No-Cache 3.0.0
- Redactor 3.0.2
- Retour 4.1.5
- SEOmatic 4.0.13
- Table Maker 4.0.3
- Twig Perversion 3.0.0
- Typed link field 2.1.4

**Comment by brandonkelly** [comment]
This is a side effect of a bug fix in Craft 4.3.2 where non-viewable elements (e.g. entries in a section a user doesn’t have access to, but which are listed via a custom source) were getting hyperlinked to the element’s edit page, which would result in a 403 error (d7ad2a24635).

Freeform and Calendar elements are affected because they aren’t implementing the `canView()` method. Solspace are aware of the bug and [working on a fix](https://twitter.com/solspace/status/1594695908146688000?s=61&t=Je_mobyDVX1wh2av2NjEtQ).
