### ISSUE TITLE
[4.x]: EVENT_AFTER_DELETE on 'Delete entry for this site'

### ISSUE THREAD

**Issue by Romanavr** [craftcms/cms#12354]
### Description
Follow events `Entry::EVENT_BEFORE_DELETE` & `Entry::EVENT_AFTER_DELETE` are not fired when an entry is deleted by the 'Delete entry for this site' action 
https://i.imgur.com/epteQ7a.png

### Steps to reproduce
Attach any code to these events and delete the entry only on a specific site
```
        Event::on(
            Entry::class,
            Entry::EVENT_AFTER_DELETE,
            static function (Event $e) {
                var_dump('Trigger me');
            }
        );
```
### Expected behavior
The code in the events should fire

### Actual behavior
Code inside following events not fired

### Craft CMS version

Craft Pro 4.2.8

### PHP version

8.1.10

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Thanks for reporting! Deleting an element from a site isn't really a delete operation since the element still appears on other sites. I've opened a PR to add new events for this specific use case which is currently targeting a 4.4 release. 

In the mean time, you might be able to solve your use case with the events called when saving elements, but that will depend a bit on your exact use case.

**Comment by Romanavr** [comment]
Thanks for the answer & comment.

**Comment by brandonkelly** [comment]
PR #12363 has been merged for Craft 4.4 🎉

**Comment by brandonkelly** [comment]
Craft 4.4 is out now!

**Comment by Romanavr** [comment]
Sounds great, thanks.
