### ISSUE TITLE
[4.3]: Removing field group has caused error in project config

### ISSUE THREAD

**Issue by zizther** [craftcms/cms#12409]
### What happened?

Locally I updated Craft 4.3.3 to Craft 4.3.4, I also removed some fields and a field group, added a new field and renamed a section.

I went to deploy these changes to the staging server and on deployment I am now getting this error message
```
Applying changes from your project config files ...
- removing fieldGroups.ad9404f0-95b7-4b2f-8842-980d41c79218 ... 
error: Cannot assign null to property craft\events\FieldGroupEvent::$group of type craft\models\FieldGroup
```

I tried rebuilding locally from the staging DB and this did not work, may be because it had already removed the field group.

### Craft CMS version

4.3.3

### PHP version

8.1

### Database type and version

mysql

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. I'm having trouble replicating this one. Is there anything in the logs (`storage/logs/console*`) that could suggest why this is happening? Would you be able to send your `composer.json`, `composer.lock`, `config/project` files from local environment and database backup from staging to support@craftcms.com so that we can try to replicate this?

**Comment by brandonkelly** [comment]
@zizther Were you able to resolve this? Doesn’t look like you’ve written into support@craftcms.com yet.

**Comment by zizther** [comment]
@brandonkelly I did manage to resolve this in a round about way by using a production DB dump and some back and forth with the console.
