### ISSUE TITLE
[4.x]: truncate with splitSingleWord option is not working

### ISSUE THREAD

**Issue by Maybach91** [craftcms/cms#12419]
### Description
According to the [documentation](https://craftcms.com/docs/4.x/dev/filters.html#truncate) (latest paragraph), there is an `splitSingleWord` option to set as boolean, whether a word should be entirely removed or only characters. This leads to an error and its not working.

### Steps to reproduce

1. Try to run the code `{{ 'Hello world how are you'|truncate(2, splitSingleWord=false) }}`

### Expected behavior

`…`
Since `2` characters are not possible to truncate, and ensure full words, nothing except the default suffix `…` should be outputted.

### Actual behavior

Getting the following error:
`Unknown argument "split_single_word" for filter "truncate(length, substring)".`

### Craft CMS version

4.3.3

### PHP version

8.1.12

### Operating system and version

Darwin 22.1.0

### Database type and version

MySQL 8.0.31

### Image driver and version

GD 8.1.12

### Installed plugins and versions

<img width="629" alt="image" src="https://user-images.githubusercontent.com/1867543/205651221-9f685421-1a79-4d0b-862a-4dacc2cfd21c.png">

**Comment by i-just** [comment]
Hi, thanks for reaching out. This is happening because both Craft and Typogrify plugin provide the `truncate` filter. Typogrify's version only accepts one parameter - length: https://nystudio107.com/docs/typogrify/#text-manipulation. With that plugin installed, it's its filter that gets called. If you test by disabling Typogrify, you can see that the Craft's filter is behaving as expected.

**Comment by Maybach91** [comment]
Thanks for the hint @i-just, that was indeed my issue. :)
