### ISSUE TITLE
[3.x]: GraphQL collision when making two queries in different parameters

### ISSUE THREAD

**Issue by eduardoalonsoalbella** [craftcms/cms#12410]
### Description

If I make a query over two parameters (featured and branches), one call takes over the other one:

### Steps to reproduce

1. Create a entry query with

```json
featured: children(hasDescendants: false) {
   title
}
branches: children(hasDescendants: true) {
   title
}
```

The results of both results will be the same and it should not

### Expected behavior

Both results should be different

### Craft CMS version

3.7.61

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
Hey @eduardoalonsoalbella! I’ve been looking into this and just wanted to provide an update. 

This is a side effect of how we eager load elements when handling a graphql request. To make things as performant as possible, when a query comes in, we [traverse and parse](https://github.com/craftcms/cms/blob/0ac04a08983d9a72ffd08ec715aa55ff01bada6c/src/gql/ElementQueryConditionBuilder.php#L156) the query and look for any and all elements that we can eager load. Eager loadable elements are thrown into an eager loading plan to be executed when the query is run. 

Critically, for [a handful of fields](https://github.com/craftcms/cms/blob/0ac04a08983d9a72ffd08ec715aa55ff01bada6c/src/gql/ElementQueryConditionBuilder.php#L288-L300) we don’t differentiate the eager loading plans based on the alias. Tracking down the original reason for that is something I need to dig into further, but in the meantime the `EVENT_REGISTER_GQL_EAGERLOADABLE_FIELDS` event will let you enable the aliases for children if you want, which seems to resolve the issue for me. 

```php
use craft\events\RegisterGqlEagerLoadableFields;
use craft\fields\BaseRelationField;
use craft\gql\ElementQueryConditionBuilder;

Event::on(
    ElementQueryConditionBuilder::class,
    ElementQueryConditionBuilder::EVENT_REGISTER_GQL_EAGERLOADABLE_FIELDS,
    function(RegisterGqlEagerLoadableFields $event) {
        $event->fieldList['children'] = [BaseRelationField::class, 'canBeAliased' => true];
    }
);
```

I need to ask around internally before I know if that’s a change we can or should implement for everyone, but hopefully, it will get you over this issue for now. It will likely have performance implications, but it’s hard to know how severe they’ll be since that will depend on your particular project.

**Comment by brandonkelly** [comment]
Craft 3.7.63 and 4.3.6 are out with #12494 merged in, allowing `children` fields to be aliased.
