### ISSUE TITLE
[4.x]: changing the section's Uri format brings not saved draft as an untitled entry to the element index

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#12534]
### Description
it seems that changing the section's URI format and resaving job also applies to a draft with no content. I think appearing these drafts on the element index page is not maybe expected behavior and we should ignore resaving these drafts by checking the saved status on job criteria.?

### Steps to reproduce

1- create a section without URI format
2- create a new entry and leave the edit page without any change -draft is created but it is not shown on the element index page-
3- change the section's URI format - resave is happening-
4- that draft appears on the element index as "untitled draft"

### Craft CMS version

4.3.6.1

**Comment by i-just** [comment]
Hi, thanks for getting in touch. I’d say this is the expected behaviour. The same thing will happen if you add content (even just one letter) or change the post date, author, or any other field except for the title - the entry will show as an “Untitled entry” draft on the Entries index page. 

Also, changing this behaviour would have some undesired consequences for, e.g. multisite setups.
