### ISSUE TITLE
[4.x]: Entries that were formerly translations disappear after save if translations have been disabled. Content is lost.

### ISSUE THREAD

**Issue by stillhartkonzept** [craftcms/cms#12532]
### Description

We started with a bilingual site, German French, with the setting "save entries to all sites enabled for this section". We created some content. Then we realized we needed to keep our content separate, so we changed the setting to "only save entries to the site they were created in". At that point we could still see our content in German and French. But as soon as we edited an entry, its equivalent disappeared. 

### Steps to reproduce

1. Set up sites De and Fr.
2. make an entry type and set to "save entries to all sites enabled for this section."
3. Create a bilingual page, for example "Open data policy"
4. Change your entry type to "only save entries to the site they were created in."
5. Observe that Entry DE "Open Data Policy" exists
6. Under Entries FR find the equivalent page.
7. Edit the French entry
8. Note that the German entry has disappeared.

### Expected behavior
Content should continue to exist if this setting is changed, and changing something in one language should definitely not delete content in the other language, especially if this content is now supposed to be disconnected.

### Actual behavior
The formerly connected page disappears and is gone forever.

### Craft CMS version

Craft Pro 4.3.5

### PHP version

8.1.13

### Operating system and version

Linux 3.10.0-1160.76.1.el7.x86_64

### Database type and version

MySQL 10.3.36

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-54)

### Installed plugins and versions

Formie	2.0.20
Maps	v4.0.3
Neo	3.5.15
Redactor	3.0.2
Webhooks	3.0.4

**Comment by i-just** [comment]
Hi, thanks for getting in touch. Changing propagation methods can cause data loss in some instances, hence the warning in the control panel. That being said, I’m having trouble replicating this behaviour in version 4.3.5 (or in some previous and later versions too). Would you be able to please send your `composer.json`, `composer.lock` and database export (all from before you changed the propagation method) to support@craftcms.com so that we can try to replicate and investigate further?


If it helps, I remember experiencing it a while back when working on a Craft 3 project. Our “solution” back then was to change the propagation method for the section to “Let each entry choose which sites it should be saved to”, which then gives you the per-entry flexibility of being able to have the same entries across multiple sites or to keep them completely separate. It also provides an action of “delete for site” if you want to clean up your content.

**Comment by brandonkelly** [comment]
When you change the propagation method to be more restrictive, an “Applying new propagation method” job is added to the queue, which will go through and duplicate each of your entries for the sites they are no longer supposed to propagate to.

So for example, if you had an entry in two sites:

- Entry 1
  - Site A
  - Site B

By the time the job is complete, you would have:

- Entry 1
  - Site A
- Entry 2
  - Site B

However if you start editing entries before the job is complete, any sites that the entry isn’t supposed to exist for will simply be pruned out, because the entry-save action doesn’t realize that the entry was waiting on being processed by the background job.
