### ISSUE TITLE
[4.3.7.1]: loop.last throws and error

### ISSUE THREAD

**Issue by cookie10codes** [craftcms/cms#12629]
### Description
After updating CraftCMS to 4.3.7.1, I'm having issues with my loop.last syntax. It seems it's not inside of the twig for loop anymore

### Expected behavior
loop.first still works, but loop.last doesn't

### Actual behavior
<img width="698" alt="Screenshot 2023-02-06 at 14 44 34" src="https://user-images.githubusercontent.com/20947573/216991957-45e9b390-12d7-47cd-be42-e9deaa52c6b6.png">

### Craft CMS version

4.7.3.1

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
This changed in Craft 4 because element queries no longer implement the `Countable` interface, which [twig relies on for `loop.length`, `loop.revindex`, `loop.revindex0`, and `loop.last`](https://twig.symfony.com/doc/3.x/tags/for.html#the-loop-variable). Once you've called `.all()` or `.collect()` they'll be there though. 

We missed this in the upgrade docs, but we'll make sure to get those updated.

A special thank you to @mmikkel for noting this in Discord!

**Comment by AugustMiller** [comment]
Thanks for the tip! I've made some improvements to the _Templating_ section of [Updating from Craft 3](https://craftcms.com/docs/4.x/upgrade.html#templating). 💞

**Comment by cookie10codes** [comment]
@AugustMiller / @brianjhanson thanks for your replies.

I've updated again and it bumped it's version to 4.3.8.2, which seems to have solved the loop.last (without any code updates?)

Am I safe to think it's fine, or do I need to review?

**Comment by brianjhanson** [comment]
@cookie10codes, you should be good. I'm guessing you got caught in [#12631](https://github.com/craftcms/cms/issues/12631) which caused eager loading to break and was fixed in 4.3.8.2

**Comment by cookie10codes** [comment]
thanks @brianjhanson for the update
