### ISSUE TITLE
Control routing order

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#1292]
> Created by: Timothy Kelty (timkelty@gmail.com) on 2015/04/02 12:33:05 +0000
> Votes at time of UserVoice import: 1

-----------------------------------

From: https://craftcms.com/docs/routing
4. Is it an entry/category request?
5. Does the URI match any Dynamic Routes?

There are times I want these flipped (dynamic routes processed first).
It feels clunky to me to do routing logic in our twig templates, which is what that can force you into.

For example, consider a "Pages" structure, with templates going to `_page.twig`:
- One entry needs to go to a different template, but since 4. matches first, we have to include that routing logic in our template.,
- I would rather just have an exception for that in my `routes.php` file that got considered first.
- You could argue this should be a single, but if you're relying on that structure, that could be a deal breaker: https://github.com/craftcms/cms/issues/899

**Comment by Anubarak** [comment]
Is there any progress on this? We are facing the same issue right now, we have a dynamic route, that has the same route like an entry but we need our custom controller to handle it instead of the default Craft controller for certain reasons.

We don't want to set the slugs/urls of those entries to something else in order to keep the `entry.getUrl` functionality but we want to use a custom action.

**Comment by brandonkelly** [comment]
Craft 3 added the [EVENT_SET_ROUTE](https://docs.craftcms.com/api/v3/craft-base-element.html#EVENT_SET_ROUTE-detail) event, which can be used to customize the route of any element.
