### ISSUE TITLE
Cannot delete all trashed resources if there are folders[4..4.3]: 

### ISSUE THREAD

**Issue by vitalijalbu** [craftcms/cms#12927]
### Description

![Screenshot 2023-03-18 alle 16 59 05](https://user-images.githubusercontent.com/40239902/226117051-d3d32a9b-2487-4eb4-bc96-b948c014f0d5.png)

### Steps to reproduce

1. By selecting all trashed resources, button to delete them permanently is disabled because i also have 2 empty folders in trash... maybe it's not a bug?!::

### Craft CMS version

4.4.3

### PHP version

8

### Operating system and version

mac

### Database type and version

mysql

### Installed plugins and versions

-

**Comment by DenyEs** [comment]
I found that I can't even delete a folder itself, even if it's empty - Craft 4.4.3

**Comment by brandonkelly** [comment]
The bug here is that folders shouldn’t have been listed when viewing soft-deleted assets in the first place, as folders are not capable of being soft-deleted.

> I found that I can't even delete a folder itself, even if it's empty - Craft 4.4.3

Subfolders cannot be deleted via the “Delete” bulk asset action, as their deletion is a bit more involved and requires additional coordination with JavaScript. To delete a folder, you must first navigate into it, and then choose the **Delete folder** source path action:

<img width="246" alt="An action menu for a selected subfolder within the source path, including a “Delete folder” option." src="https://user-images.githubusercontent.com/47792/226437502-82a5e4d5-2554-4a6f-a32f-26966354d7ab.png">

**Comment by brandonkelly** [comment]
Craft 3.8.4 and 4.4.4 are out with that fix.

**Comment by DenyEs** [comment]
@brandonkelly Brilliant, thank you Brandon.
