### ISSUE TITLE
[4.x]: User with two first names is not recognised by user.firstName

### ISSUE THREAD

**Issue by carolineboeykens** [craftcms/cms#12933]
### Description
We are having an issue with a user who has two first names (in two different words).
But the user.firstName now only shows the first word. Is there a work around here?

### Steps to reproduce

1. Create a user and enter the name in full name: 'John Joe Smith'

### Expected behavior
First Name is here in two words: 'John Joe'

### Actual behavior
Only the word 'John' is recognised as the first name.

### Craft CMS version

4.3.5

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
If the user’s name is being submitted via a front-end form with a dedicated `firstName` field, the full first name should stay in-tact, since Craft was told explicitly. However if it’s coming from a `fullName` input (like in the control panel), then we use a name parsing library to make a best guess at what the individual name parts should be. In this case, `Joe` is most likely being interpreted as a middle name, rather than a second first name.

I think we need to make it possible to edit the first/last names individually from the control panel, for cases where the automatic name parsing isn’t working as expected, similar to what I [originally proposed](https://github.com/craftcms/cms/discussions/10405#discussioncomment-2036639).

**Comment by hwd7ypk** [comment]
@brandonkelly I heartily agree with your original approach of adding fields to the CP. 

Sidenote- the current setup caused some confusion when using Feed Me to import users. I have a coworker with a double first name who had already been added to Craft via the CP before implementing the feed. In other words, her Full Name field was manually completed when her user account was created. The feed contains separate First Name and Last Name fields, which are correctly mapped to the associated fields. But those were being overridden by the Full Name value, so only the first part of her first name was being displayed on the front end.

I've solved for this by deleting her Full Name value and rerunning the feed.

**Comment by cballenar** [comment]
The approached mentioned (multiple columns for all name parts) is particularly important for international users where we not only deal with multiple names but also **multiple last names**. Worsen by the fact that "official" dealings often require both last names to be used.

I've attempted to use similar parser libraries in the past for cases like this and they're "ok" for best guesses but we usually run into trouble when trying to find users while sorting or exporting data for marketing, leading to additional data clean up work. This is fine if the data goes through a filter, say a lead capturing form that then gets cleaned up. But it doesn't work if you're trying to capture and use data as is.

In such cases, even a simple two field setup is better than a single-best-guess type of field.

**Comment by brandonkelly** [comment]
I’ve gone ahead and added a new `showFirstAndLastNameFields` config setting, for Craft 4.6 (#14097).

Craft 4.6 doesn’t have any database changes, so it’s safe to try out without needing to create a database backup. You can switch to it by changing your `craftcms/cms` requirement to `4.6.x-dev as 4.6.0-alpha`, and running `composer update`.

**Comment by brandonkelly** [comment]
Craft 4.6.0 is out now with that new setting.
