### ISSUE TITLE
[4.x]: Composer error when updating from 4.4.4 to 4.4.5

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#12947]
### Description

I can't update Craft CMS from `4.4.4` to `4.4.5` using composer:

```
composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires craftcms/cms 4.4.5 -> satisfiable by craftcms/cms[4.4.5].
    - You can only install one version of a package, so only one of these can be installed: enshrined/svg-sanitize[0.15.2, 0.15.3, 0.15.4, 0.16.0].
    - enovatedesign/craft-style-inliner 3.0.0 requires enshrined/svg-sanitize ^0.15.2 -> satisfiable by enshrined/svg-sanitize[0.15.2, 0.15.3, 0.15.4].
    - craftcms/cms 4.4.5 requires enshrined/svg-sanitize ~0.16.0 -> satisfiable by enshrined/svg-sanitize[0.16.0].
    - Root composer.json requires enovatedesign/craft-style-inliner 3.0.0 -> satisfiable by enovatedesign/craft-style-inliner[3.0.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

Removing `/vendor` + `composer.lock` + run `composer install` + run `composer update --with-all-dependencies` does not fix it.

Probably linked to #12943.

### Steps to reproduce

1. Update composer.json to `"craftcms/cms": "4.4.5"`
2. Run `composer update`
3. Get the error

### Expected behavior
No error.

### Actual behavior
Error.

### Craft CMS version

4.4.5

### PHP version

8.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. This is happening because a plugin you use: `enovatedesign/craft-style-inliner` requires `"enshrined/svg-sanitize": "^0.15.2",`, whereas Craft 4.4.5 has bumped the required version of `enshrined/svg-sanitize` to `~0.16.0` due to a security vulnerability in the previous versions.

It would be best to open an issue with [enovatedesign](https://github.com/enovatedesign/craft-style-inliner) and ask them to bump their version too.
