### ISSUE TITLE
[4.x]: Multisite Live Preview doesn't work

### ISSUE THREAD

**Issue by handplant** [craftcms/cms#12979]
### What happened?

I have two sites (site1.de, site2.de) configured as multisite with IS_SYSTEM_LIVE=0.

After I logged in to site1.de/admin, the live preview works for site1 but not for site2 (503).

What can I do to make this work?

### Craft CMS version

Craft Pro 4.4.5

### PHP version

8.1.11

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Just tested locally and it’s working as expected here.

Try clicking the “View” button instead of “Preview”. It will open the same preview URL that gets loaded within Live Preview, except as a full browser tab rather than an iframe.

The resulting URL should have a `siteToken` URL param, which should grant you access to the disabled site, even though you don’t have an active user session there.

**Comment by brandonkelly** [comment]
Apologies, I misread the post initially and tested with a disabled _site_, rather than taking the entire Craft install offline.

I was able to reproduce when taking the system offline, and just fixed this for the next Craft 3 and 4 releases 👍

**Comment by handplant** [comment]
ok, thx Brandon.

**Comment by brandonkelly** [comment]
Craft 3.8.6 and 4.4.6 are out with that fix 🎉
