### ISSUE TITLE
[4.x]: Different outputs for https://domain.com, https://domain.com/index.html and https://domain.com/index.php

### ISSUE THREAD

**Issue by rbrv** [craftcms/cms#12980]
### Description
Visiting   https://domain.com, https://domain.com/index.html and https://domain.com/index.php returns 3 different outputs. Probably because the `entry` variable not being filled in.

Craft should handle this more elegantly imo...

Even the Craftcms.com site has this behaviour:

👍 https://craftcms.com | 👎 https://craftcms.com/index.html | 👎 https://craftcms.com/index.php
--- | --- | ---
![Screenshot 2023-03-24 at 14 28 44](https://user-images.githubusercontent.com/43676281/227534579-3545d408-d795-4f5d-887d-11a8cef0563b.png) | ![Screenshot 2023-03-24 at 14 29 06](https://user-images.githubusercontent.com/43676281/227534609-55f25bf6-06ae-4162-8fb8-dca41701e771.png) | ![Screenshot 2023-03-24 at 14 29 51](https://user-images.githubusercontent.com/43676281/227534639-3bd6eba2-b2bd-4474-966a-763db8fcfc81.png)

### Expected behavior
Same output as https://domain.com (or redirect?) for both https://domain.com/index.html and https://domain.com/index.php

### Craft CMS version

4

### Installed plugins and versions

-

**Comment by WilliamIsted** [comment]
Just out of curiosity I had a look into this and the behaviour is the same as in Craft CMS 3.x. This is a working theory.

What appears to be happening here is Craft is being told if the request was kicked off by the index file which results in an empty `$path` at: https://github.com/craftcms/cms/blob/ffdd85ffde5d243f3062df376a551bc521216f40/src/web/UrlManager.php#L393

This will be the case if you visit `/`, `/index.php`, or even if you set your DirectoryIndex to `foobar.php`, rename `index.php` to `foobar.php` and load it.

This matters because if you have a public homepage template such as `templates/index.html` or `templates/index.twig` and request it directly at `/index.html`, `/index.twig` or `/index` even though this triggers the public template it does not recognise the request as the homepage url as you mentioned "Probably because the entry variable not being filled in.".

To resolve this issue the homepage template should not be a public template, it should be prefixed with an underscore e.g. `_index.html` or `_homepage.twig` and pointed by the homepage section template. This prevents issues like differing title tags or content.

This could also be resolved by manually loading the associated sites' homepage entry in `index` the template with:
`{% set entry = craft.entries({ uri: '__home__' }).one() %}`

_Aside: It appears the Craft website has already been updated to resolve this issue since you posted it. Hopefully they'll push an update to match public indexes. The styling issue persists on their site but I think this is to do with a javascript file throwing an error on `/index.php`._

**Comment by brandonkelly** [comment]
@WilliamIsted Correct… this is all basically working as expected. If you don’t want a template to be accessed directly, it should be made private.

As for `/index.php`, that would need to be handled by a redirect. Craft shouldn’t redirect `/index.php` → `/` automatically because there are cases where accessing Craft via `index.php` explicitly is intentional, such as if Apache is configured to route `/` URLs to `/index.php` with a `.htaccess` rewrite rule.

And yeah, we’ve already fixed the `index.html` template issue on craftcms.com, and will be deploying an `index.php` redirect soon.
