### ISSUE TITLE
[4.4.5]: Dropdown field with empty title and value 0 not working anymore backend

### ISSUE THREAD

**Issue by eugenebroeren** [craftcms/cms#13041]
### Description
After upgrading from  4.3.11 cannot save dropdown field anymore.
The dropdown field starts with an empty value (with value 0).  
Till version 4.3.11 i could save those entries.

### Steps to reproduce

Create dropdown with values

Empty -> value 0
Blue -> 1
Red -> 2
Green -> 3

### Expected behavior
Just save the entry

### Actual behavior

Error <fieldname> is inValid" in red. So i must choose another value than the empty one.

Workaround / solution is to fill the title field with a space or value.

### Craft CMS version

4.4.5

### PHP version

8.1

### Operating system and version

Linux

### Database type and version

MariaDb

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out. Changes were made to the Dropdown field in `4.4`: https://github.com/craftcms/cms/discussions/12235.

Value `0` is not technically an empty value, and you don’t have an empty value defined for that dropdown. Craft considers this a validation error because what you try to save for this field doesn’t match the list of values defined for it (values defined for this field are 0, 1, 2, 3). 

If you want the first option (label: empty, value: 0) to be selected by default (without the user having to select it from the dropdown), you should check the “default” checkbox for it for that dropdown field. Then when you create a new entry with that field and don’t interact with the dropdown, the entry will be saved with the default value of 0.

I hope this helps!

**Comment by eugenebroeren** [comment]
It works now, i did have to to fix the entries made after i did the update.
I do understand the update

Thanx

Op di 4 apr 2023 om 13:46 schreef Iwona Just ***@***.***>:
