### ISSUE TITLE
[4.x]: UrlManager::_getRules should probably return an empty array under console

### ISSUE THREAD

**Issue by msbit** [craftcms/cms#13109]
### Description

When adding rules to the UrlManager via `addRules(...)` as part of a module `bootstrap(...)`, using the `craft` command, (via something like:

    php craft

) fails with the (wonderfully cryptic):

    Error: array_merge(): Argument #1 must be of type array, null given

This is due to the default behaviour being to append rules using:

    $this->rules = array_merge($this->rules, $rules);

in [`yii\web\UrlManager::addRules(...)`](https://github.com/yiisoft/yii2/blob/161526cd41beee62d0910333c3bd96034cf73186/framework/web/UrlManager.php#L206), but the `urlManager` component provided by craft (`craft\web\UrlManager`) sets the `rules` field based on the result of [`craft\web\UrlManager::_getRules()`](https://github.com/craftcms/cms/blob/ffdd85ffde5d243f3062df376a551bc521216f40/src/web/UrlManager.php#L302) which:

    if ($request->getIsConsoleRequest()) {
        return null;
    }

### Steps to reproduce

1. Add module
2. Add rules to URL manager in module bootstrap
3. Run `php craft`

### Expected behavior

The craft tool to run properly

### Actual behavior

`Error: array_merge(): Argument #1 must be of type array, null given`

### Craft CMS version

4.4.7.1

### Installed plugins and versions

-

**Comment by msbit** [comment]
@i-just, that's certainly a work around, but I have to ask, is there any reason why `craft\web\UrlManager::_getRules()` couldn't play nice and return an empty array in this case?

**Comment by brandonkelly** [comment]
@msbit Just made that change for the next Craft 3 and 4 releases. However this is not the recommended way of defining URL rules, since it will cause all rules to be defined for the request, which means any downstream plugins/modules that are registering URL rules via the [`EVENT_REGISTER_CP_URL_RULES`](https://docs.craftcms.com/api/v4/craft-web-urlmanager.html#event-register-cp-url-rules)/[`EVENT_REGISTER_SITE_URL_RULES`](https://docs.craftcms.com/api/v4/craft-web-urlmanager.html#event-register-site-url-rules) events will not have a chance to do so.

Instead, you should be using one of those events, depending on whether you want the rules added for control panel or front-end requests.

```php
use craft\events\RegisterUrlRulesEvent;
use craft\web\UrlManager;
use yii\base\Event;

Event::on(
    UrlManager::class,
    UrlManager::EVENT_REGISTER_SITE_URL_RULES,
    function(RegisterUrlRulesEvent $e
) {
    $e->rules['foo'] = 'bar/baz';
});
```

**Comment by msbit** [comment]
Thanks @brandonkelly.

> which means any downstream plugins/modules that are registering URL rules via the [EVENT_REGISTER_CP_URL_RULES](https://docs.craftcms.com/api/v4/craft-web-urlmanager.html#event-register-cp-url-rules)/[EVENT_REGISTER_SITE_URL_RULES](https://docs.craftcms.com/api/v4/craft-web-urlmanager.html#event-register-site-url-rules) events will not have a chance to do so

I may be missing something, but this doesn't seem to be the case; looking over the code for both `yii2` and `cms` it goes something like:

* `UrlManager::__construct`
  * `UrlManager::_getRules`
    * `UrlManager::trigger(EVENT_REGISTER_CP_URL_RULES)` or `UrlManager::trigger(EVENT_REGISTER_SITE_URL_RULES)`
* `UrlManager::addRules`

so by the time `addRules` was called (or even callable) any subscribers for the URL rule registration event would have been run.

As a more general question, is there some documentation describing what is or isn't supported/best practice when developing modules in Craft4? The [documentation](https://craftcms.com/docs/4.x/extend/module-guide.html) is good for getting a module started, but then hands off to the [yii documentation](https://www.yiiframework.com/doc/guide/2.0/en/structure-modules) implying that anything in that second set of documentation will work as expected (such as the bootstrapping that brought this issue up).

**Comment by brandonkelly** [comment]
> I may be missing something, but this doesn't seem to be the case; looking over the code for both `yii2` and `cms` it goes something like:

The problem is, once `_getRules()` has been called once, the URL rules are now considered defined, and it won’t be called a second time in the request. So for any plugins/modules that haven’t been instantiated yet, it’s now too late for them to register their URL rule event handler. (They will still end up registering the event handler, but the event has already been triggered so nothing will come of it.)

That said, I just realized we could solve this by deferring the `_getRules()` call until `parseRequest()`, and having the results merged in with any predefined rules (either via the `urlManager` config or `addRules()`). So I’ve just made that change for Craft 4.5 (41da83986f216274a992a09f0eb9c2c562272785).

In the meantime, the event handler route is the only safe option.

> As a more general question, is there some documentation describing what is or isn't supported/best practice when developing modules in Craft4? The [documentation](https://craftcms.com/docs/4.x/extend/module-guide.html) is good for getting a module started, but then hands off to the [yii documentation](https://www.yiiframework.com/doc/guide/2.0/en/structure-modules) implying that anything in that second set of documentation will work as expected (such as the bootstrapping that brought this issue up).

We touch on the `EVENT_REGISTER_CP_URL_RULES` event in a few places:

- [Control Panel Edit Pages](https://craftcms.com/docs/4.x/extend/cp-edit-pages.html)
- [Plugin Sections](https://craftcms.com/docs/4.x/extend/cp-section.html#plugin-sections)
- [Controllers → Routing → Control Panel Routes](https://craftcms.com/docs/4.x/extend/controllers.html#control-panel-routes)
- [Element Types → Element Index](https://craftcms.com/docs/4.x/extend/element-types.html#element-index)

Typically front-end routes will be defined via `config/routes.php` as explained on [Routing → Advanced Routing with URL Rules](https://craftcms.com/docs/4.x/routing.html#advanced-routing-with-url-rules), however it’s probably worth mentioning `EVENT_REGISTER_SITE_URL_RULES` there, and maybe adding a dedicated section on URL routing to the extending docs. We’ll discuss that internally.

**Comment by brandonkelly** [comment]
Craft 3.8.8 and 4.4.8 are out with that initial PHP error fix.

**Comment by msbit** [comment]
@brandonkelly yeah right, that is a bit of a footgun, good to have that deferred.

**Comment by brandonkelly** [comment]
Craft 4.5.0 is out now with that change to URL rule registration.
