### ISSUE TITLE
[4.x]: Missing translation strings

### ISSUE THREAD

**Issue by simplegr** [craftcms/cms#13226]
### Description

The following translation strings are missing from plugin-store/upgrade-craft:

Ultra-flexible content modeling
Powerful front-end tools
Multi-Site
Localization
Single admin account

Unlimited user accounts
Enhanced content previewing
GraphQL API
System branding
Basic developer support

Also 2 more:

Craft CMS edition changed.
Your cart is empty.

### Craft CMS version

4.4.11

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for reporting. Turns out there was a handful of other strings throughout the plugin store which weren’t getting translated either. I’ve hooked them up to receive translations, but that change won’t actually take effect until the next time we place a translation order – probably in a month or so.

I decided not to translate the Craft Solo/Pro edition feature comparison lists though, as they are likely to change more frequently and there’s not really any precedence. Similar feature comparison lists for multi-edition plugins aren’t getting translated, or any other plugin-specific content.
