### ISSUE TITLE
[4.x]: upscaleImages(false) not being respected

### ISSUE THREAD

**Issue by tyssen** [craftcms/cms#13254]
### Description

I have `->upscaleImages(false)` set it `config/general.php` and `upscale: false` set in each of my image transforms but smaller images are still being upscaled.

### Steps to reproduce

1. Create a transform that is 480x480, fit, `upscale: false`.
2. With this code which is working on an image that is only 220px wide, I still get a 480px image created.

    `{% set image = craft.assets.id(1638).one() %}`
    `<img src="{{ image.url('w480') }}" width="{{ image.width('w480') }}" height="{{ image.height('w480') }}">`

### Expected behavior
Images aren't scaled up.

### Actual behavior
Images smaller than transform sizes are still being created. In conjunction with the Retcon plugin, I have upscaled images being output when adding images to Redactor fields, e.g. `{{ column.body|retconSrcset(['w320', 'w480']) }}`. 
But it's not just when used in Retcon that it happens, with the code added in steps to reproduce, I get the same outcome.

### Craft CMS version

4.4.12

### PHP version

8.0

### Operating system and version

Mac OS 13.3.1 (a)

### Database type and version

mariadb 10.4

### Image driver and version

Whatever comes with DDEV

### Installed plugins and versions

- Button box: 4.2
- CP clearcache: 1.3
- CP field inspect: 1.4
- CP nav: 4.0
- Elements panel: 2.0
- Express forms: 2.0
- Inventory: 3.0
- Olive menus: 4.0
- Palette: 3.1.5
- Redactor custom styles: 4.0
- Environment label: 4.0
- Field manager: 3.0
- Logs: 4.0
- Patrol: 5.0
- Phpdotenv: 5.4.0
- Redactor: 3.0.4
- Retcon: 2.6
- SEO: 4.1
- Super table: 3.0.8.1

**Comment by i-just** [comment]
Hi, thanks for getting in touch. Craft on its own (and with the Redactor plugin) respects the `upscaleImages` settings, adding Retcon to the mix change things.

For example, if I set `upscaleImages(false)`, create transforms with allow upscaling: off and then grab and display images this way:
```
{% set image = craft.assets.id(150).one() %}

<img src="{{ image.url() }}" width="{{ image.width() }}" height="{{ image.height() }}">
{{ image.url() }}

<br />

<img src="{{ image.url('w480') }}" width="{{ image.width('w480') }}" height="{{ image.height('w480') }}">
{{ image.url('w480') }}
```
or add that image to the Redactor field, assign transform to it and display the redactor field via `{{ entry.myRedactorField }}`, the image doesn't get upscaled.

However if I start using Retcon: `{{ entry.myRedactorField|retconSrcset(['w320', 'w480']) }}` on an image that hasn't been transformed before - it will get upscaled.

It happens because of the 3rd parameter passed to those `scale...` methods in Retcon: https://github.com/mmikkel/Retcon-Craft/blob/master/src/helpers/RetconHelper.php#L233-L238

Please open an issue with in the Retcon's GitHub: https://github.com/mmikkel/Retcon-Craft/issues.

**Comment by tyssen** [comment]
Actually, sorry, I've just noticed that it's creating an image in the `_w480` folder but it's not actually being resized, it's the same size as they original. That wasn't what I was expecting. I thought that it wouldn't create a transformed version at all.

**Comment by i-just** [comment]
Cool, glad we're on the same page 🙂
