### ISSUE TITLE
[4.x]: Queue finish immediately when trigger from web browser

### ISSUE THREAD

**Issue by nhithanki** [craftcms/cms#13284]
### Description

We have a custom plugin to display the output of a shell script as run time as the program goes. Normally, It will take arround 30 minutes to complete. In craft 3, we push it into queue from web browser and it output all results from shell script unit it done. In craft 4, It finishes as soon as the queue start to run. When we try to trigger this queue from CLI, it works perfectly fine.

Code from this article: [https://stackoverflow.com/questions/20107147/php-reading-shell-exec-live-output](https://stackoverflow.com/questions/20107147/php-reading-shell-exec-live-output)
Example code:
```
        while (@ ob_end_flush()); // end all output buffers if any

        $proc = popen($cmd, 'r');

        while (!feof($proc))
        {
            echo  fread($proc, 4096);
            $this->setProgress($queue,0.5, 'Queue is running');
            @ flush();
        }
```
### Steps to reproduce
1. Create a job that using this example code
2. $cmd: any command that have sleep time.
3. Pusing job via web browser.

### Expected behavior
Executing all command in the shellscript until it done.

### Actual behavior
Finish a queue and not executing any code in the shellscript.

### Craft CMS version

4.4.13

### PHP version

8.1

### Operating system and version

ubuntu

### Database type and version

mysql

### Installed plugins and versions

- ostark/craft-async-queue : 3.1.0

**Comment by brandonkelly** [comment]
This is most likely due to d7f7fe03010. It was intended that queue runners triggered from front-end Ajax requests had their connections severed immediately (so it doesn’t hold the browser up with an unneeded connection, for a potentially long-running PHP request). However we just recently realized that this code wasn’t working as expected:

https://github.com/craftcms/cms/blob/d7f7fe0301012cf881a55146e51ce0d516844d83/src/controllers/QueueController.php#L77-L80

Because `Requet::getIsAjax()` is checking for a `X-Requested-With: XMLHttpRequest` header, which the previous front-end `XMLHttpRequest` code wasn’t sending.

So that was fixed for Craft 3.8.9+ and 4.4.9+ simultaneously.

If you really want the original behavior, you will need move your code to a custom controller, and send an Ajax request out to it.
