### ISSUE TITLE
[4.4.13]: Unable to delete folders

### ISSUE THREAD

**Issue by jan-thoma** [craftcms/cms#13294]
### Description

I'm unable to delete folders inside a Volume the option in the UI is greyed out.

### Steps to reproduce

1. Create a source and a volume
2. Create a folder
3. Try to delete it form menu

### Expected behavior

I should be able to delete folders

### Actual behavior

Option is greyed out

![Bildschirmfoto 2023-06-08 um 08 28 57](https://github.com/craftcms/cms/assets/24450307/fa2b205d-fdc1-4fd1-b081-226fe1ddb9e9)

### Craft CMS version

4.4.13

### PHP version

8.1

### Operating system and version

Craft Official Docker Container Image

### Database type and version

Mysql 8

### Image driver and version

gd

**Comment by i-just** [comment]
Hi, thanks for reaching out. In order to delete a folder, you need to go into it and then click on the arrow in the breadcrumbs, and there’s a “delete folder” option there. 

I’m going to go ahead and close this, but there’s a discussion open for this behaviour: https://github.com/craftcms/cms/discussions/13086, and you can follow along there.
