### ISSUE TITLE
[4.x]: Certain chinese characters not returning entries that contain the characters in their content

### ISSUE THREAD

**Issue by JamieC24** [craftcms/cms#13333]
### Description

This issue is in regards to https://github.com/w3c/w3c-website/issues/180. On the Chinese news item listing, the search form doesn't return the right results. Some of the news items contain the following characters '工作组备忘' in their titles, however, searching for that string does not return all relevant results.

I have tested this in the CMS entry search as well, and some of the newer entries with 工作组备忘 don't show up in the search results despite having 工作组备忘 in their content.

This content sits within a [CKEditor](https://plugins.craftcms.com/ckeditor) field and I have ensured the "Use this field's values as search keywords" checkbox is checked.

### Steps to reproduce

1. Create an entry in Craft with the characters 工作组备忘 in their content
2. Use the CraftCMS entry search to search for 工作组备忘
3. See if the entry you created is returned in the search results

### Expected behavior

The new entry is returned in the search for 工作组备忘

### Actual behavior

The new entry is not returned in the search for 工作组备忘

### Craft CMS version

4.4.14

### PHP version

8.2.0

### Operating system and version

macOS Ventura 13.4

### Database type and version

SQL - MySQL 5.7.39

### Installed plugins and versions

- Amazon S3 (2.0.3)
- Asset Usage (3.1.0)
- CKEditor (3.4.0)
- Comments (2.0.7)
- Feed Me (5.1.3.1)
- Field Manager (3.0.6)
- Icon Picker (2.0.13)
- Restrict Asset Delete (2.0.1)
- Shield (3.0.2)
- Super Table (3.0.9)
- Two-Factor Authentication (3.2.0)
- oEmbed (2.3.0)

**Comment by angrybrad** [comment]
@JamieC24 I see you’re using MySQL 5.7.39. can you confirm a few things?

* What is the storage engine set to for the `searchindex` table... MyISAM or InnoDB?
* What is the default charset and collation for the database?
* Can you confirm that the textual fields (text, varchar, etc.) in both the `searchindex` and `content` tables are using that default charset/collation?

**Comment by JamieC24** [comment]
@angrybrad thanks for the swift response!

Had a look at my local DB and found the following:

- The storage engine `searchindex` uses is InnoDB
- The default charset and collation (I believe) is `utf8` and `utf8_unicode_ci`
- Looks like the tables are also using `utf8` and `utf8_unicode_ci`

**Comment by angrybrad** [comment]
@JamieC24 interesting.

Just did a fresh install of Craft using 4.4.14 and MySQL 5.7.41 and a few tests using `utf8` for the charset `utf8_general_ci` and `utf8_unicode_ci` for the collations.

I installed CKEditor, and created a field and a test section.

I created an entry and put `工作组备忘` in the CKEditor field and saved it.

I got the matched entry on the entry index search bar when I searched for `工作组备忘`.

It could be that your search indexes are out of date. Can you try running `php craft resave/entries --update-search-index=1` and see if that changes the behavior? You could also try passing in `--section=mysectionhandle` if you have e a lot of entries and wanted to narrow the scope of this just for the purposes of the test.

**Comment by jean-gui** [comment]
@JamieC24 @angrybrad I think this is due to Craft not performing fuzzy searches by default. Entries that Craft doesn't find when looking for `工作组备忘` indeed contain that string as part of a longer "word" (emphasis on quotes as I don't know how Chinese define words), for example `的工作组备忘供业界参考`.

But searching for `*工作组备忘*` will return those entries. So I guess it's just a matter for us to either perform fuzzy searches, or enable it globally (https://craftcms.com/docs/4.x/config/general.html#defaultsearchtermoptions subLeft, subRight)

**Comment by angrybrad** [comment]
@jean-gui possibly, but @JamieC24's original post used `工作组备忘` for both the source string and the search string, so that should match whether Craft does a fuzzy search or not.

**Comment by angrybrad** [comment]
@jean-gui ahh, my bad. Based on https://github.com/w3c/w3c-website/issues/180 it looks like you might have found a workaround for this?

> As we have one site per language, is it possible to define [defaultSearchTermOptions](https://craftcms.com/docs/4.x/config/general.html#defaultsearchtermoptions) per site?

Assuming the first segment of your URI is the language identifier, I was going to suggest something like this in `config/general.php`:

```
use craft\helpers\App;

$defaultSearchTermOptions = match (\Craft::$app->getRequest()->getSegment(1)) {
    'ja', 'zh-hans' => ['subLeft' => true, 'subRight' => true],
    'en' => ['subLeft' => true],
    default => [],
};

return [
    ...
    'defaultSearchTermOptions' => $defaultSearchTermOptions,
    ...
];
```

> Also, @angrybrad, do you know how subLeft/subRight work with right-to-left languages?

Great question! I just did some basic testing in Hebrew, and I _think_ it’s working as I’d expect, but let us know if you see otherwise.

I’ll go ahead and close this out, but comment back for any further issues/questions, and we can re-open.

**Comment by jean-gui** [comment]
@angrybrad Thanks
