### ISSUE TITLE
[3.x]: Multi-site user permissions & revisions/drafts

### ISSUE THREAD

**Issue by mightyfineyall** [craftcms/cms#13331]
### Description
On a multi-site Craft 3 build with 5 sites, all of which share templates, I've created user groups assigned to each specific site, and made them not be able to access other sites, or edit other authors' drafts:

![image](https://github.com/craftcms/cms/assets/48531847/16de933c-6610-4f41-8013-c9c460d358c5)

When I impersonate a user in one user group, I can see revisions from users associated with other user groups:

![image](https://github.com/craftcms/cms/assets/48531847/fe5ae994-e68e-490c-b994-145e43c89dee)

I understand that revisions aren't drafts, and that entry revisions aren't limited to a site (and thus might be accessible across user groups) but this seems like an oversight. Specifically, staff from one user group being able to see staff names from other user groups in revisions, when they can't access this information anywhere else. Let me know if there's something I'm missing - I searched through the issues and couldn't find info about this specific thing.

### Steps to reproduce

1. Create a multisite setup, with two user groups limited to each site and their own drafts.
2. Edit a shared entry with one user, then log in as another user and view the revision in the revision list.

### Expected behavior

The revision and author's user name shouldn't be visible.

### Actual behavior

The revision is visible, as well as the revision author's user name (accessible nowhere else for the current user).

### Craft CMS version

3.8.14

### PHP version

7.3.33

### Operating system and version

Linux 4.15.0-212-generic

### Database type and version

MySQL 5.7.42

### Image driver and version

GD 7.3.33

### Installed plugins and versions

Architect	2.4.3
Calendar	3.3.21
Contact Form	2.5.2
Contact Form Extensions	1.3.2
Cookie Consent Banner	1.2.9
Expanded Singles	1.2.0
Feed Me	4.6.3.1
Field Manager	2.2.5
Freeform	3.13.29
Imager	v2.4.0
Instagram Feed	1.2.0
Navigation	1.4.33
Redactor	2.10.12
Retour	3.2.10
SEOmatic	3.4.57
Super Table	2.7.5.1
Typed link field	1.0.25

**Comment by i-just** [comment]
Hi, thanks for getting in touch. 

Based on the screenshots, you’re referring to a Single section enabled for more than one site. Singles don’t have as granular permissions as other sections. For Channels and Structures, you can choose whether the user can access other authors’ entries (and what they can do with them), but Singles are created on Section creation and therefore don’t have such permissions.

Because the Single is enabled for multiple sites, any revisions are created for all the enabled sites, but users from one site don’t have access to the (translatable) content created for another site.

For example:
- I have 2 sites: `site 1` and `site 2`
- a Single section enabled for both of them, with revisions turned on
- that Single section has a text field translatable for each site (meaning its content is independent for each site)
- I have 2 user groups, each set to have access to just one site and the ability to edit & publish live changes (Craft 3) (or view & save entries (Craft 4)) for that Single section
- I have an `admin` user (with access to everything), `user_s_1` with access to `site 1`, and `user_s_2` with access to `site 2`.

1. `admin` user edits the Single entry for `site 1` and adds content: “admin, site 1”
2. then `user_s_1` user edits the Single entry for `site 1` and changes the content to “user_s_1, site 1”
3. then the `user_s_2` user edits the Single entry for `site 2` and adds content “user_s_2, site 2” - note they didn’t see the content added by the `admin` or the `user_s_1` user as that content was added for `site 1`
4. `user_s_2` expands the revisions dropdown - they can see that revisions were made by `admin` and `user_s_1`, but if they go to the revision created by either of the others, they don’t see the content others created;
5. if you then switch to `user_s_1`, edit the content to “user_s_1, site 1, edited”, save, and expand the revisions, you can see the revision created by `user_s_2`, but if you choose it, the content you see is the last content edited for `site 1`, which is “user_s_1, site 1”; that’s because `user_s_2` edited the content, but only for `site 2`.

Now, if that entry had another field which is not translatable (the content is the same for both sites, regardless of who added/changed it) and in the above steps, each user added the same content they added to our translatable field to the non-translatable field too, then in step 4 you wouldn’t see the content for the translatable field, but you’d see the content for the non-translatable field. In step 5, in the latest revision, you’d see “user_s_1, site 1” in the translatable field and “user_s_2, site 2” in the non-translatable field.

All of the above is an expected behaviour. I hope this helps clarify things!
