### ISSUE TITLE
[4.x]: The word 'Bitmap' in extraFileKinds causes null width and height

### ISSUE THREAD

**Issue by mike-moreau** [craftcms/cms#13376]
### Description
Have uncovered what appears to be a bug. I have defined a few extra file kinds [via this general config setting](https://craftcms.com/docs/4.x/config/general.html#extrafilekinds).

If I use the word 'Bitmap' or 'Bitmap Image' as the label, then the uploaded asset has a null width and height in the assets table in the DB.

### Steps to reproduce

1. Add an extra file kind to general config as shown below.

```
->extraFileKinds([
        'static' => [
            'label' => 'Bitmap Image',
            'extensions' => [
                'jpg', 'jpeg', 'png', 'webp', 'avif'
            ]
        ]
    ])
```
2. Upload an asset such as jpeg that should support width and height
3. Check the width and height columns in the asset table row

### Expected behavior

Width and height would have a value.

### Actual behavior
They are null

### Craft CMS version

4.4.14

### PHP version

8.2

### Operating system and version

MacOS 13.4

### Database type and version

MySQL 5.7

**Comment by i-just** [comment]
Hi, thanks for reaching out. `extraFileKinds` config is for “additional file kinds Craft should support”. The extensions from your config are already registered under the existing `image` file kind.

Going further, the behaviour you’ve noticed is to do with sorting `extraFileKinds` by label (not specifically with the word “Bitmap”).

Only `image` file kinds get dimensions. File kind is determined by file extension (https://github.com/craftcms/cms/blob/develop/src/helpers/Assets.php#L408-L427), and which extension is classified as which file kind is determined by the config - both default and added via `config/general.php` (https://github.com/craftcms/cms/blob/develop/src/helpers/Assets.php#L447-L703).

The extensions from your config sit under the `image` file kind, but your config additionally assigns them to a new `static` file kind. Because `"static" !== "image"`, dimensions are not used for those files.

Now, if you were to use the label “My Bitmap Image”, it would appear to work as expected because “My Bitmap Image” is alphabetically after “Image”, which means `static` file kind is listed after `image` and so the files you’re uploading are classified as `image`, not `static` (`image` is the first match `getFileKindByExtension()` can find).

I’m not sure what your goal is, but if you want to rename “Image” to “Bitmap Image”, then this would do the trick: 
```
->extraFileKinds([
    'image' => [
        'label' => 'Bitmap Image'
    ]
]);
```

If you want to disallow some image kinds globally, then have a look at this config option: https://craftcms.com/docs/4.x/config/general.html#allowedfileextensions

There’s also [`EVENT_REGISTER_FILE_KINDS`](https://github.com/craftcms/cms/blob/develop/src/helpers/Assets.php#L693-L698), which allows you to manipulate the file kinds further.

I hope the above helps!

**Comment by mike-moreau** [comment]
That makes sense! Thank you for the detailed explanation.
