### ISSUE TITLE
[4.x]: A provisional draft created via GraphQL API is not visible in control panel UI

### ISSUE THREAD

**Issue by ivanBereznev** [craftcms/cms#13401]
### Description
A provisional draft created via GraphQL API is not visible in control panel UI when original entry has no author assigned.

### Steps to reproduce

1. Create an entry without assigning an author. On of the ways to achieve that is a Feed Me import.
2. Create a provisional draft for this entry using the `createDraft` GraphQL mutation.
3. Optionally modify the draft via GraphQL API, e.g. change title.
4. Open edit form for that entry in Control Panel

### Expected behavior
Control Panel should show that there is a provisional draft, i.e. there should be this "unsaved changes" bar:
![provisional_draft_bar](https://github.com/craftcms/cms/assets/18012861/96f519d2-1a7f-4bc0-9c2a-dedb5c89493f)

If that provisional draft contains some changes, they should be reflected in the edit form.

### Actual behavior
Control panel does not show that bar. Changes from the draft are not present in the form. Change made to the edit form causes creation of one more provisional draft.

### Craft CMS version

4.4.11

### PHP version

8.0.22

### Operating system and version

Debian GNU/Linux 11

### Database type and version

PostgreSQL 13.6

### Image driver and version

Imagick 3.7.0 (ImageMagick 7.1.0-35)

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reporting! 

It’s happening because, for drafts created via GraphQL, the creator is derived from the entry’s author. When the entry doesn’t have one, the draft creator will also be empty. A provisional draft will only show in the control panel for its creator, so if the creator is `null`, the provisional draft exists in the database but won’t be pulled in and shown to anyone.

I’ve added the `creatorId` argument to the `createDraft` mutation to mitigate this.

**Comment by brandonkelly** [comment]
Craft 4.4.16 is out with the new `creatorId` argument.
