### ISSUE TITLE
[4.x]: Craft CMS 3 update to craft CMS 4. Error: Column not found: 1054 Unknown column 'licenseKeyStatus' in 'field list'

### ISSUE THREAD

**Issue by nickyichov** [craftcms/cms#13501]
### What happened?

Error appears after I tried to update from craft 3 to craft 4

### Description

I want to update from craft CMS 3.8.2 to craft CMS ^4.0.0. This is the [doumentation](https://craftcms.com/docs/4.x/upgrade.html) how the update needs to be performed and what changes needs to be done.  Everything was okay until after `composer update` where the first problem appeard:

 `Exception 'yii\base\UnknownPropertyException' with message 'Invalid general config setting: stagingPassword. You can set custom config settings from config/custom.php.'` 

 And it was fixed by creating `custom.php` and transfering some of the code there.
 
 The next error that appeard is:

```
Error Info:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'licenseKeyStatus' in 'field list'
)

Caused by: Exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'licenseKeyStatus' in 'field list''

```

At first I thought that php craft migrate/all didn't migrate properly. That's why I backed up and I did the update again. This time I ran php craft before php craft migrate/all to check if works okay at this step. But the error was already occurring which means that migraion didn't happen at all.

### Steps to reproduce

1. Changed craft's current version to `craftcms/cms: ^4.0.0` in `composer.json`
2. Changed craft's plugins current versions to the versions compatible with craft ^4.0.0  in `composer.json`
3. Run `composer update`

### Expected behavior

Successful update from craft CMS 3.8.2 to craft CMS 4.0.0

### Actual behavior

Currently I am not able to run `php craft` because every time I run it the mentioned error appears.

### Craft CMS version

3.8.2

### PHP version

8.0.19

### Database type and version

MySQL 8.0.34

### Image driver and version

GD 8.0.19

### Installed plugins and versions
```
    "vlucas/phpdotenv": "^2.4.0",
    "craftcms/cms": "^4.0.0",
    "craftcms/redactor": "3.0.4",
    "spicyweb/craft-neo": "3.8.3",
    "craftcms/contact-form": "3.0.1",
    "ether/seo": "4.1.2",
    "putyourlightson/craft-blitz": "4.5.0",
    "verbb/formie": "2.0.33",
    "presseddigital/linkit": "4.0.4.1",
    "yiisoft/yii2": "2.0.46"
```

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

This is happening because of `"yiisoft/yii2": "2.0.46"` in your `composer.json`. It causes Craft CMS only to update as far as version 4.3, and when updating from 3.8, you need to go straight to 4.4 (a similar issue was reported here: https://github.com/craftcms/cms/issues/12836). 

If you remove `"yiisoft/yii2": "2.0.46"` from your composer.json, the update process should work as expected.

I’ll go ahead and close this now, but please feel free to reach out if you encounter any further issues.

**Comment by corneliusio** [comment]
@i-just I know this is an incredibly old issue, however I'm currently upgrading an extremely old project to Craft 5 and am running into this exact error when making the jump from 3.9 to 4.0, however we do not have `yiisoft/yii2` required in our project.

Is it possible there are any other factors I could investigate to address this error?

edit: Thinking about this more, something occurred to me. Did 3.9 start releasing AFTER 4.0? And is the issue here that I need to be upgrading to 4.x from 3.8?

**Comment by i-just** [comment]
@corneliusio, are you getting the `Unknown column 'licenseKeyStatus' in 'field list'` error? What’s the exact version you’re upgrading from and to? Is it 3.9.0 to 4.0.0 exactly, or the latest 3.9.x to the latest 4.x.x? 

Did you have a look at the related #12836 issue mentioned above?

**Comment by corneliusio** [comment]
@i-just 🤦🏼 That is entirely my mistake. I totally browsed right past that related issue.
Sorry for unnecessary ping—jumping straight to 4.4.x as noted in that related issue resolves the error on my end.

**Comment by i-just** [comment]
Not a problem, @corneliusio. Glad it’s working as expected!
