### ISSUE TITLE
[4.5.2]: Relational field not updating search indexes of category

### ISSUE THREAD

**Issue by arnout-poppr** [craftcms/cms#13615]
### Description

I have a Category `category` that has a field related to an entry `virtualTour`. The relational field `categoryVirtualTour` has the option for _Use this field’s values as search keywords?_ checked in its properties.

Now I have another entry `pano` which implements a category relational field `panoCategory` to my `category` Category. When I want to select one for this `pano`-entry, there will be a lot of these categories in the future on our platform so we need them to be searched on or filtered efficiently.

### Expected behavior and actual behavior

So when trying to select a category in a `pano`-entry I was expecting to be able to search on the title of the `virtualTour` as I thought to have understood in the documentation [here](https://craftcms.com/docs/4.x/searching.html#customizing-the-index). Filtering, on the related virtual tour, does work but takes too long. I can not seem to find the search index for the title of the virtual tour linked to the category id in the database. Even after trying to resave all related entries and categories.

![category-relational-field](https://github.com/craftcms/cms/assets/94955382/d277499e-5894-42d0-a179-93e39c76a0aa)

Additionally my first thought was to pre-filter these lazy-loaded results in the modal but I can not seem to find a way to do this. Any tips on how this could be accomplished? Where am I going wrong here?

### Relational fields properties

categoryVirtualTour

![screencapture-virtualtour-centerparcs-test-admin-settings-fields-edit-80-2023-08-29-10_36_16](https://github.com/craftcms/cms/assets/94955382/9fab9ee1-bafc-4726-bfff-9441a59795aa)

panoCategory

![screencapture-virtualtour-centerparcs-test-admin-settings-fields-edit-81-2023-08-29-10_36_38](https://github.com/craftcms/cms/assets/94955382/d06f89d1-cb84-4bb1-867b-4f200cb69f88)

### Craft CMS version

Craft Solo 4.5.2

### PHP version

8.1.17

### Operating system and version

Windows 11

### Database type and version

10.4.28-MariaDB

**Comment by brandonkelly** [comment]
This is working on my end.

> Even after trying to resave all related entries and categories.

Was “Use this field’s values as search keywords” enabled for `categoryVirtualTour` from the beginning, or did you enable it later on?

If it wasn’t enabled at first, how did you resave the categories? Using the [`resave/categories`](https://craftcms.com/docs/4.x/console-commands.html#resave-categories) CLI command? If so, note that you must pass `--update-search-index` if you want the search indexes to be updated. (It’s opt-in because updating search indexes can be expensive, and often isn’t necessary for the types of things `resave` commands are used for.)

Also worth noting that if your related entries’ titles are changed, the categories’ search indexes for the related entry titles won’t get updated automatically.

**Comment by arnout-poppr** [comment]
I was missing the `--update-search-index` when I had tried using the resave command. The search now does work as expected and my search indexes are updated correctly. The _Use this field’s values as search keywords_ checkbox was indeed enabled later on. Thank you so much Brandon!

**Comment by brandonkelly** [comment]
Glad that worked!
