### ISSUE TITLE
[5.0.0-alpha]: Use alternative text on asset card

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#13797]
### Description
When using the built-in alternative text field, it's not possible to mark it for usage on the element card. 

![Screenshot 20231007-174447-ZSllXNWj](https://github.com/craftcms/cms/assets/755428/b3bb5c03-d020-4c1d-9769-c72936185362)

### Steps to reproduce

1.

### Craft CMS version

5.0.0-alpha

### Installed plugins and versions

-

**Comment by gcamacho079** [comment]
Thanks for reaching out @janhenckens! I want to make sure I understand the issue fully. 

Right now, the Alternative Text value is being set on the image tag in element cards, but the field doesn’t include a setting to “Include this field in element cards”.

Is it your expectation that the Alternative Text field should include the setting to “Include this field in element cards” so that the value can be made **visible as text** in the card view?

**Comment by janhenckens** [comment]
> Is it your expectation that the Alternative Text field should include the setting to “Include this field in element cards” so that the value can be made visible as text in the card view?

Yes, that what I was trying to do - to make author more aware of the alt tag.

**Comment by brandonkelly** [comment]
Done! `composer update` and you’ll be able to start including Alternative Text in your cards.

**Comment by janhenckens** [comment]
Great, thanks @brandonkelly!
