### ISSUE TITLE
[4.x]: Long wait when switching between tabs with lots of data on the page

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/cms#13852]
### Description

I have a channel setup with 2 tabs defined in the field layout. 

Each tab contains a table field defined with a single row template. 

Each table has around 200 rows of data in it. Switching between tabs has become painfully slow. Sometimes a 6-7 second wait between each switch.

I'm using these tables for logging, so the website admins have some visibility over certain types of data in the right context. In hindsight, I might of chosen a different approach.

### Steps to reproduce

1. Create a channel
2. Define 2 tabs in the field layout
3. Assign each tab a table field with a one row template
4. Create an entry in the channel and populate each table field with around 100 - 200 rows of data
5. Try switching between tabs and notice the lag

### Expected behavior

For the switch between tabs to be faster despite there being lots of data within each tab (even if the data loads after)

### Actual behavior

Long wait (6-7 seconds) between each tab switch 

### Craft CMS version

4.5.7

### PHP version

8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
The tab switching probably only takes a while because that will trigger the Table field’s UI initialization, which can’t happen until the field is visible. I’m guessing once you’ve selected the Table field’s tab once, subsequent tab switching is faster?

We can look into optimizing Table fields for large row counts (the upcoming [`input-sizing`/`field-sizing`](https://front-end.social/@jensimmons/111217420404388282) CSS property is going to help a ton), but it was definitely not intended that they would be used for storing constantly-growing data sets like logs, so you may need to rethink how you are storing/displaying that data in the first place. Does it need to be an editable table at all? And should logs be stored in a custom field value, for that matter?

**Comment by brandonkelly** [comment]
It sounds like maybe a more optimal UI for this would just be a static `<table>`.

I don’t think that exists currently via any plugins, but you could build it yourself using [Craft Generator](https://github.com/craftcms/generator).

With that installed, run the `php craft make field-type` command, with either `--module=my-module-id` or `--plugin=my-plugin-handle`.

Your field type could even extend `craft\fields\Table` so none of your existing code around setting field values etc., needs to change.

You would just need to override `inputHtml()` with:

```php
use craft\elements\ElementInteface;
use craft\helpers\Html;

protected function inputHtml(mixed $value, ?ElementInterface $element = null): string
{
    if (empty($value) || !is_array($value)) {
        return Html::tag('div', 'No data yet.', ['class' => 'zilch']);
    }

    $html = Html::beginTag('table', ['class' => 'data']) .
        Html::beginTag('thead') .
        Html::beginTag('tr') .
        Html::tag('th', 'My Heading 1') .
        Html::tag('th', 'My Heading 2') .
        // ...
        Html::endTag('tr') .
        Html::endTag('thead') .
        Html::beginTag('tbody');

    foreach ($value as $row) {
        $html .= Html::beginTag('tr') .
            Html::tag('td', $row['value1'] ?? '') .
            Html::tag('td', $row['value2'] ?? '') .
            // ...
            Html::endTag('tr');
    }

    $html .= Html::endTag('tbody') .
        Html::endTag('table');

    return $html;
}
```

**Comment by jonleverrier** [comment]
Super. I hadn't considered my own custom field before but this sounds ideal. Thanks for all your suggestions and help.

**Comment by jonleverrier** [comment]
@brandonkelly Just to say, I went ahead and created a static table field. Works well! 

However, I've now noticed that it takes a while for the entry to load (36 seconds on average). Once the entry has loaded, tab switching is instant.

This entry has:
1. One tab with a native table field (1 row template) with 124 rows of data
2. Another tab with a matrix field (nothing to complex)
3. A final tab with my static table field which is rending 176 rows worth of data (some entries have more!)

Is there anything I can do to increase load time?

**Comment by jonleverrier** [comment]
FWIW - I've reverted back to a native table field for the time being. Whilst doing so, I setup the original table config for 1 column (opposed to 5) and the entry was notably faster, despite not showing the data set I fully require.

**Comment by brandonkelly** [comment]
I found a couple opportunities to improve the initial page rendering performance for large table fields (ed7939dd427b4696d5b6a62e78f4b731c73382b4), so that will get better as of the next release.

I also managed to drastically speed up JS initialization (487907f74d4d20caea122eccdb24feffea19fa88), but that change will have to wait until Craft 4.6 as it involved a very minor breaking change. (Table rows are no longer fully initialized until they’ve been interacted with, so `$tr.data('editable-table-row')` won’t return anything initially. `Craft.EditableTable::getRowObj($tr)` can be used instead.)

Craft 4.6 doesn’t (yet) contain any database migrations, so it’s safe to test out without making a database backup. If you want to try, change your `craftcms/cms` constraint to `4.6.x-dev as 4.6.0` in composer.json and then run `composer update`.

**Comment by jonleverrier** [comment]
This is wonderful news! I'll try and test and report back.

**Comment by brandonkelly** [comment]
> It still takes a while to load the entry though:

Which load, exactly? Initial page load for the edit page? Or when you switch to the tab with the table on it?

**Comment by jonleverrier** [comment]
> Which load, exactly? Initial page load for the edit page? Or when you switch to the tab with the table on it?

Going from entry index to an entry edit page

**Comment by brandonkelly** [comment]
Craft 4.6.0 is out with the JS initialization improvements to editable tables.

We’ll keep looking for opportunities to improve the initial rendering speed.
