### ISSUE TITLE
[4.4]: Database-error at rollback from 4.5 to 4.4

### ISSUE THREAD

**Issue by alexgit2k** [craftcms/cms#14007]
### Description
It is not possible to rollback from 4.5 to 4.4. Looks like with 4.5 the columns `licenseKeyStatus` and `licensedEdition` have been removed.

### Steps to reproduce
1. ./craft db/restore database-backup.zip --drop-all-tables --interactive=0

### Expected behavior

```
Extracting zip to a temp directory ...
done
Dropping all database tables ... 
...
done
Finished dropping all database tables.
Restoring database backup ...
done
Deleting the temp directory ...
done
```

### Actual behavior

```
Exception 'yii\db\Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'licenseKeyStatus' in 'field list'
The SQL being executed was: SELECT `id`, `handle`, `version`, `schemaVersion`, `licenseKeyStatus`, `licensedEdition`, `installDate`
FROM `plugins`
ORDER BY `handle`'
in vendor/yiisoft/yii2/db/Schema.php:676
Error Info:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'licenseKeyStatus' in 'field list'
)
Caused by:
Exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'licenseKeyStatus' in 'field list''
```

And also an error for `licensedEdition`.

### Workaround
Add columns before restore:
```
ALTER TABLE plugins \
 ADD licenseKeyStatus enum('valid','trial','invalid','mismatched','astray','unknown') NOT NULL DEFAULT 'unknown' AFTER schemaVersion, \
 ADD licensedEdition varchar(255) DEFAULT NULL AFTER licenseKeyStatus;
```

### Craft CMS version

4.4

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
If you want to restore your 4.4 database using Craft’s own `db/restore` command, you would need to do that _before_ downgrading `craftcms/cms` itself; otherwise the app will be in an instable state because 4.5 introduced database changes that 4.4 couldn’t have possible been aware of.

Alternatively you could use any external database client such as TablePlus, SequelPro, etc., or non-Craft CLI command such as `ddev import-db` or `mysql`.
