### ISSUE TITLE
[4.x]: Ambiguous error message when uploading multiple files

### ISSUE THREAD

**Issue by MoritzLost** [craftcms/cms#14003]
### Description

When uploading multiple files at once through the assets index, individual uploads sometimes fail. Not sure why this happens, probably due to timeouts when the server is at maximum capacity due to handling a bunch of files. In any case, you only get this error message as a notification:

> Uploads failed.

![craft-upload-failed](https://github.com/craftcms/cms/assets/10146880/82162dcf-1c0c-42e4-bb6a-eb60e23ded6b)

Other than that, there's no indicator that something has gone wrong. If you are uploading a bunch of files in the background while doing something else, you might even miss this notification entirely (since they disappear after a couple of seconds by default, unless you've changed that in the accessibility settings).

The error message is very ambiguous. Has the entire upload failed, or only _some_ of the files? It's the latter, but the error message should indicate that. It also doesn't tell you _which_ upload has failed, so you have to manually compare your local file folder with the uploaded assets to see which one is missing.

### Steps to reproduce

1. Upload a lot of files at once (unfortunately, I don't have a reproducible way to cause an upload to fail).

### Expected behavior

The error message should be improved to indicate that _some_ of your files have failed to upload. It should also tell you _which_ file has failed to upload, so you can upload that specific file again.

### Actual behavior

The error message is vague and unclear.

### Craft CMS version

4.5.11.1

### PHP version

8.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Thanks @MoritzLost. Specific error messages help with replication. Based on a quick look, we already have specific error messages that mention the filename if that data is made available to the uploading script, and the fallback is the generic “Upload failed.” message. I’ll have a closer look and keep you updated.

**Comment by i-just** [comment]
Hi @MoritzLost, I had a closer look into it, and the generic “Upload failed.” message is the expected behaviour when there’s no error/reason passed up the chain. I’ve triggered all sorts of errors related to uploading and saving an asset, which all resulted in a descriptive error message being presented to the user. I could only trigger the generic one when a 502 Bad Gateway was thrown.

Given all that, if you were to open developer tools in your browser before you start uploading multiple assets, you can follow the progress in the Network tab. If it happens again, you can then see what actually caused it (and which files didn’t upload). If you spot anything that you think should be passable up the chain, let me know, and I’ll have another look, but at the moment, it does look to be working as expected.

I’m going to close this now, but feel free to reply if you find further info that could mean that this is a bug.

**Comment by MoritzLost** [comment]
@i-just Thanks for looking into this issue, Iwona!

To test this issue, I've uploaded 600 images at once now to try to trigger the error. After about half, I've got this error again. Looks like a network timeout, network inspector shows NS_ERROR_NET_INTERRUPT with no response body. So this probably happens if the server is too busy to respond in time, so there's no error message from the server to display.

In the event of a network error like this, it would be nice to know which file failed to upload. I can see in the network tab that each image uses an individual request, and the request body includes the file name. I don't know how the JS code is structured, but in theory it should be possible to use the filename from the request body as a last fallback for the error message, in case of a network error where there's no other message to display. Right?

**Comment by i-just** [comment]
@MoritzLost, thanks for the suggestions! I found a way to improve those fallback error messages to contain the filename. PR has been raised and is pending review.

**Comment by MoritzLost** [comment]
@i-just That looks great, thanks Iwona!

**Comment by brandonkelly** [comment]
Craft 4.5.12 is out with the fix for this. Thanks again!
