### ISSUE TITLE
[4.x]: Mailer swallows exceptions

### ISSUE THREAD

**Issue by leevigraham** [craftcms/cms#14185]
### Description

Looks like the yii2-symfony-mailer swallows any transport exceptions: https://github.com/yiisoft/yii2-symfonymailer/blob/2.0.4/src/Mailer.php#L188-L216

I think the goal was to always have those exceptions bubble up? https://github.com/craftcms/cms/issues/1896 

### Steps to reproduce

1. Create a Postmark transport with an invalid api token (to trigger the error), or any other invalid smtp config.
2. Create a message and send it

```php

$message = \Craft::$app
->getMailer()
->compose()
//            ->setTo('leevi@mytiki.life')
->setTo($entry->author->email)
->setBcc('leevi@mytiki.life')
->setReplyTo($user->email)
->setSubject(sprintf('[mytiki.life] Trading Post - %s is interested in %s', $user->titleComputed, $entry->title))
->setHtmlBody($emailHtml)
->addHeader('X-PM-Tag', 'trading-post');

$success = $message->send();
```

### Expected behavior

The mailer should catch the exception: https://github.com/craftcms/cms/blob/develop/src/mail/Mailer.php#L178-L194

### Actual behaviour

No exception is thrown lower down in the call stack: https://github.com/yiisoft/yii2-symfonymailer/blob/2.0.4/src/Mailer.php#L188-L216

### Craft CMS version

4.6.1

### PHP version

8.2

### Installed plugins and versions

-

**Comment by timkelty** [comment]
@leevigraham that was the case [back then](https://github.com/craftcms/cms/issues/1896), but that was also before the yii2-swiftmailer was swapped for symfony mailer.

Changing it at this point would be a breaking change, so I think would have to wait until v5. That said, the catch [here](https://github.com/craftcms/cms/blob/develop/src/mail/Mailer.php#L180-L194) no longer makes sense and should be cleaned up.

Is there something in your use-case you aren't able to do because of the current behavior?

**Comment by brandonkelly** [comment]
The redundant try/catch has been removed via #14234.

**Comment by leevigraham** [comment]
> Is there something in your use-case you aren't able to do because of the current behavior?

I was just trying to figure out what the issue was with my email settings (wrong postmark token) and there was no way of knowing without breakpointing all the way down.

The try / catch in the Craft code confused me for a second until I went deeper… hence this ticket.
