### ISSUE TITLE
[4.x]: Eager loaded matrix blocks return wrong sort order in preview

### ISSUE THREAD

**Issue by daltonrooney** [craftcms/cms#14259]
### Description

When using an eager query to load matrix blocks, the preview returns the blocks with an incorrect sort order. Once saved, the returned sort order is correct.

### Steps to reproduce

1. Add a few matrix blocks to a new entry. Save and continue editing.
2. Open up the preview and drag and drop the blocks into a new order, or try adding a new block.

### Expected behavior

Eager loaded blocks should return the same sort order as normally loaded blocks.

### Actual behavior

The sort order for normally loaded blocks will update, but the sort order for eager loaded blocks will not update.

### Example

```twig
{% set blocks = entry.matrixBlocks.all() %}
{% set eagerLoadedEntry = craft.entries.id(entry.canonicalId).with(['matrixBlocks']).one() %}

<h2>Blocks</h2>
{% for block in blocks %}
  <pre>
    {{block.type.handle }}:{{block.sortOrder}}
  </pre>
{% endfor %}
<hr>
<h2>Eager Loaded Blocks</h2>
{% for block in eagerLoadedEntry['matrixBlocks'] %}
  <pre>
    {{block.type.handle }}:{{block.sortOrder}}
  </pre>
{% endfor %}
```

![eager-loaded-matrix-block-sort-order.mp4](https://github.com/craftcms/cms/assets/742045/7882753b-50c9-48d7-a56b-c48e7a612f96)

### Craft CMS version

4.7.1

### PHP version

8.1.26

### Operating system and version

Linux 6.5.13-orbstack-00121-ge428743e4e98

### Database type and version

MySQL 5.7.42

### Installed plugins and versions

No plugins installed.

**Comment by brandonkelly** [comment]
When you start editing an entry, a “provisional” draft is created for the entry, where your edits will be autosaved until you press the **Save** button.

So when you do this:

```twig
{% set eagerLoadedEntry = craft.entries.id(entry.canonicalId).with(['matrixBlocks']).one() %}
```

You’re going to get the _canonical_ entry’s blocks, rather than the draft’s. So it’s expected that their sort order (and everything else about them) wouldn’t change in Live Preview.

To eager-load the draft’s blocks instead, change `entry.canonicalId` to `entry.id`.

But there’s no point in eager-loading Matrix blocks for a single entry. In fact you’re _increasing_ the workload by doing that, since there’s no n+1 problem there to begin with; just one block query for one owner entry’s blocks.

If you have any relations on those blocks, like an Assets field, that’s where eager-loading would start making sense:

```twig
{% set blocks = entry.matrixBlocks.with(['blockTypeHandle:assetsFieldHandle']).all() %}
```
```

**Comment by daltonrooney** [comment]
> To eager-load the draft’s blocks instead, change entry.canonicalId to entry.id

Yeah I thought this might be the case, but I get a runtime error `Impossible to access a key ("matrixBlocks") on a null variable` when I try to use the entry.id? 

The example I gave is a reduced test case just to reproduce the issue, we're actually trying to load multiple matrix blocks as well as all of the relations in a single query. Perhaps a bit too ambitious:

```php
$query = Entry::find()
	 ->id($entry.canonicalId)
	 ->with([
		 ...$matrixHandles,
		 ...$eagerFields,
	 ])
	 ->site('*');
```

We worked around this in more or less the way you suggest, to move the "with" method to the relevant matrix handles. This results in a few more db queries, but that seems to be a pretty minimal impact.

```php
$entry = Entry::find()->id($entry.canonicalId);
foreach ($matrixHandles as $type) {
	 if (isset($entry->$type)) {
		 $blocks = $entry->$type->with($eagerFields)->all();
		 $result[$type] = $blocks;
	 }
 }
```
