### ISSUE TITLE
[4.X]: Uploads in File Field not possible 

### ISSUE THREAD

**Issue by shpfive** [craftcms/cms#14291]
### Description

I can't upload any Files in my Fields of Type File. They don't show the Upload / Select Buttons anymore.

![Bildschirmfoto 2024-02-05 um 12 27 13](https://github.com/craftcms/cms/assets/36002011/19983421-f89f-48d0-9179-66c22ff9aac9)

There are no Buttons in the SourceCode:

![Bildschirmfoto 2024-02-05 um 12 39 59](https://github.com/craftcms/cms/assets/36002011/63c0f4f8-731b-42aa-a0f6-6df3f050ca11)

And not issues in the console.

### Steps to reproduce

1. I have updated Craft CMS from 4.6.0 to 4.7.0 and just now to 4.7.1 and in the progress of the update from 4.6 to 4.7 the fields lost the Buttons.

### Expected behavior

Craft shows the Buttons for Upload and Select from Media Library

### Actual behavior

No Buttons visible. Drag and Drop is working, but thats not helpfull for some clients.

### Craft CMS version

4.7.1

### Installed plugins and versions

- Freeform | 4.1.13
- Instagram Feed | 2.2.1
- Navigation | 2.0.25
- Neo | 4.0.3
- Redactor | 3.0.4
- SEO | 4.2.1
- Typed link field | 2.1.5
- Vite | 4.0.8

**Comment by i-just** [comment]
Hi, thanks for reaching out!

This is most likely caused by the changes in `4.7.0`, where we prevent the use of the volume set as a temporary upload location for anything other than storing the temporary uploads. More details can be found at https://github.com/craftcms/cms/pull/14141 and https://github.com/craftcms/cms/pull/14246.

You have a few options here: 
- you can change the Temp Uploads Location (control panel > settings > assets > settings) to include a path to a subfolder that should be dedicated to temporary uploads
- you can set up a separate volume to store your Temp Uploads
- or switch to `In the local temp folder` if your hosting setup allows for this option to work

I hope this helps!

**Comment by shpfive** [comment]
Thank you for the quick support.
I created a new volume for the temp uploads and the buttons show up again.
