### ISSUE TITLE
Asset subfolder directory separator missing - missing slash

### ISSUE THREAD

**Issue by nlassiter** [craftcms/cms#1432]
### Description
I have an "images" asset type. I have created a "backgrounds" subfolder. When attempting to access the image, the slash is missing between the subfolder and image filename in the cp or between the subfolder and transform directory on the frontend.

### Steps to reproduce
1. In the control panel, within an asset type, create a subfolder
2. Upload files within the subfolder
3. Attempt to move files from subfolder to root folder within craft asset cp
4. Receive a browser alert similar to: "File was not found while attempting to rename backgroundsfilename.jpg"

Similarly, when I try to use the image in an entry template, via asset.getUrl(transform), the resulting url is missing the slash like above, between the subfolder and image transform directory name.

### Additional info

- Craft version: 3.0.0-beta.5
- PHP version: 7.1
- Database driver & version: mysql 5.7
- Plugins & versions:

**Comment by narration-sd** [comment]
Yes, I seem to be seeing a number of issues for Local File  Assets on beta5.
- testing on a totally fresh installation, via composer
- basically, Assets don't work -- don't show in the Assets view, even though their folders do. None.
- of course I have done things like clear caches, then asset index, which works its slow way and develops the folders at least seen in the Assets MiyVolume view
- It doesn't matter if I use old style tested or new @web etc. paths
- looking at the database results, they differ considerably
  = beta4, no data (!) in assetindexdata, all images listed, with folder ids, in craft_assets
  = beta5, all images in assetindexdata, including their paths, _no_ images listed in craft_assets
- similarly, 
  = beta4, transforms are in assettransforms, used images present with their _folders in assetttransformindex
 = beta5, transforms are in assetttransforms, but no images in assettransformindex, and in fact the _transform folders haven't been created, much less their tranformed images.

@andris-sevcenko to have comment on the situation? After weekend, of course, and I am going out to have mine also ;)

**Comment by narration-sd** [comment]
A little addition yet: uploading  an image seems to get treated more favorably.

- It has database entries mostly -- 
- I can use the image in a section field, and see it in a template that references it. 
- the image.url is at its normal url location per my web/ folder

So, the basic problem seems to be in importing Assets which are already there -- a site full of images

But then, there's another problem: transforms.
- I define the one I want to use
- I get back a 'make a transform' url instead of the transformed image url
- I run a debugger, and watch it step through the myriad steps to finally set a Task to do the transform creation
- but none is created; and the assettransformindex table remains empty, though the transform is defined sensibly in assettransforms
- all I see in craft_tasks by this point is a cleanup deleteStaleTemplateCaches.

Time for that remains-of-weekend, but I hope all this helps.
Again, a totally fresh and nearly empty beta5 is what's being run, and shows differencees to beta4 as above.

C.

**Comment by andris-sevcenko** [comment]
Looking into this. It looks like you guys managed to mix together at leat two separate issues here :)

I fixed some transform issues with c646dab but the subfolder issue would not be a part of that, so here's what we should do now:

@narration-sd can you pull the latest Craft code from repo and see if you can reproduce your issues? If you can, please open a separate issue for that. For organizational purposes I'll treat this issue as reported originally :)

**Comment by andris-sevcenko** [comment]
@nlassiter I am not able to reproduce this on my end. Can you please get in touch via support@craftcms.com? An attached dump of craft_volumes and craft_volumefolders tables would be appreciated!

**Comment by nlassiter** [comment]
I'll try to get the dump tonight. FWIW, I believe I originally uploaded the files to the root folder in the cp, then created the subfolder and moved them to the subfolder.

**Comment by nlassiter** [comment]
Here are the tables

[volumes_volumefolders.txt](https://github.com/craftcms/cms/files/805629/volumes_volumefolders.txt)

**Comment by andris-sevcenko** [comment]
@nlassiter if you create more subfolders, are all of them missing a trailing slash in the `path` field in the `craft_volumefolders` table? Because that shouldn't be possible and I'm trying to understand where that came from for your `backgrounds` folder entry there.

**Comment by nlassiter** [comment]
I'm having trouble reproducing this now. I upgraded from beta 3 to beta 5 around the time this originally happened. Maybe it was a bug in beta 3. I'll post if I get this issue again.
