### ISSUE TITLE
[4.x]: Asset fields file browser not remembering previously opened folder

### ISSUE THREAD

**Issue by joelzerner** [craftcms/cms#14325]
### What happened?

When selecting files/images using multiple asset fields, opening the asset browser does not remember the last folder you were in. (Instead it resets you to the root folder) We've noticed this after a recent update to 4.7.1 - previously <4.5.x

It would be nice if the default behaviour was for the asset browser to remember where you were last or this could possibly be controlled via a setting?

### Craft CMS version

4.7.1

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! 
What’s happening is - when you load the page, the default upload location is used. If that’s set to just the volume, without a subpath, the modal will be opened to the root folder of that volume. If you navigate to a different folder, close the modal (don’t reload the page) and open the modal again - the last selected location is remembered and used. If you then reload the page, the default location is used again.

We had a chat about this internally and decided that it would be best to change this behaviour so that we only enforce the default upload location on reload when the subpath is specified. I just raised a PR for this. Once approved and merged, the behaviour will be as follows:
- if a default upload location is set to the root of the volume, then after reload, we use the last remembered location (if there is one, if there isn’t, we use the default)
- if a default upload location was set to contain a subpath, then we’ll continue to always use the default location on reload

**Comment by brandonkelly** [comment]
That change has been made for Craft 4.8. (#14382)

**Comment by joelzerner** [comment]
Thanks, the functionality as you described does sound like a good way to handle it.

One follow-up question is in regards to _multiple_ assets fields. Let's say you've got a matrix/neo repeater which has items each containing an asset field and text field. When adding one item, you select the asset you need from a specific folder. Then when you add the next matrix item, and click to select an asset - it would be great if it follows the same behaviour and also remembers the last folder you navigated too. Does that make sense?

**Comment by i-just** [comment]
The same rules still apply. I attached a quick video that shows this. 
You can also test it early if you change your `craftcms/cms` requirement to `4.8.x-dev as 4.8.0-alpha` in `composer.json` and run `composer update`.

https://github.com/craftcms/cms/assets/4500340/c4600e17-e788-4b1b-a1e8-077cb490315f

**Comment by joelzerner** [comment]
Fantastic! This looks great. Appreciate you recording the video to demonstrate :)
