### ISSUE TITLE
[5.0.0-beta.2]: Field Layout designer unusable in slideout

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14401]
### Description

The new meta sidebar showing usages makes the layout designer unusable in slideouts:

1600px screen width:

![image](https://github.com/craftcms/cms/assets/60010597/9a8134cb-4e28-42a9-8fc2-b664efbf88c8)

1920px screen width: somehow usable, but doesn't show tabs in two columns:

![image](https://github.com/craftcms/cms/assets/60010597/5246faab-3069-4fe1-a2d6-39c213cea0d8)

### Steps to reproduce

1. Open entry type in slideout from matrix field edit

### Expected behavior

Don't use a sidebar, let the field layout designer take as much space as possible for tab columns. 

### Actual behavior

See screenshot

> Removes the “Used by” column from the Entry Types index page

I really liked that...

Edit:

Same for editing fields in slideouts

![image](https://github.com/craftcms/cms/assets/60010597/bb7eace4-87cf-490f-bd76-d55565bea116)

### Craft CMS version

5.0.0-beta.2

### PHP version

8.2.13

### Operating system and version

Linux 5.15.133.1-microsoft-standard-WSL2

### Database type and version

MySQL 8.0.33

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Thanks for pointing that out! I’ve addressed this for the next release in two ways:

- Field layout designers are now responsive, so their sidebars will only be visible when there’s enough room to show them alongside the configured tab(s). Otherwise, the element library pane will be accessible via disclosure menus within each tab. (#14411)
- Slideout sidebars are now always togglable; not just when they’re too narrow to display the sidebar alongside the content. (#14418)
