### ISSUE TITLE
[5.x]: deleteEntryType removes yaml config but not db entry

### ISSUE THREAD

**Issue by aedan-umd** [craftcms/cms#14422]
### Description

Tried to delete entryType using entryService -> ( entryType) it returns success and removes the projectConfig yaml files but the database.entryTypes table rows still exit.

Perhaps is not a bug but intended behaviour 🤷 I could not find documentation in Craft 4 Class Reference

### Steps to reproduce

1. $entryService = Craft::$app->getEntries();
2. $targetEntry = $entryService->getEntryTypeByHandle($entryType->handle);
3. $entryService->deleteEntryType($targetEntry);

### Expected behavior

db_table.entryTypes removes affected rows similar to how $fieldService -> deleteField () works

### Actual behavior

success is returned, yaml config files removed, db_table.entryTypes row(s) still exist

### Craft CMS version

 Craft CMS 5.0.0-beta1

### PHP version

PHP 8.3.1 

### Operating system and version

macOS Sonoma 14.2.1

### Database type and version

mysql: Ver 8.3.0 for macos14.2 on arm64 (Homebrew)

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
It’s expected that the row will remain for a while, but its `dateDeleted` value should be filled in, because it has been soft-deleted.

We keep the row around for a bit because fully deleting the row would cause all of its entries’ rows to be deleted as well.

The row and entries will get fully deleted once garbage collection runs, after some time has passed (per your [softDeleteDuration](https://craftcms.com/docs/4.x/config/general.html#softdeleteduration) setting). Or you can fully delete them immediately by running `php craft gc --delete-all-trashed`.
