### ISSUE TITLE
[5.x]: Templating settings in Craft 5

### ISSUE THREAD

**Issue by mikesnoeren** [craftcms/cms#14425]
### What happened?

While testing Craft 5, one thing that was a bit confusing was that the template settings are defined on sections.. 
With everything being made up of entry types, wouldn't it make more sense if templates are defined on Entry Type level? 

This would be beneficial for the following reasons:
- One Section can use multiple Entry Types, but only one template, meaning you would have to write the entry type logic in your one template.
- Using Entry types in a matrix would be simpler, because each entry type already has a template it loads.
- Using the "New Entry" option in a CKEdit field would have its template already assigned. (Note: I think this feature is currently broken/bugged? All it does is enter the linked entry title)

### Craft CMS version

5.x

**Comment by brandonkelly** [comment]
Sections are meant to loosely correspond to sections of your website, whereas entry types are a bit more portable. (An entry type could be used by both a section and a Matrix/CKEditor field, fore example.) So that’s why the routing and template settings are on sections.

You actually get the best of both worlds in Craft 5, though, thanks to [element partial templates](https://craftcms.com/docs/5.x/system/elements.html#rendering-elements). Each entry type can define its own dedicated partial template (`_partials/entry/<typeHandle>.twig`), and then if you want, your section template could pull that in via `Element::render()`:

```twig
{% extends '_layout.twig' %}

{% block content %}
  <h1>{{ entry.title }}</h1>
  {{ entry.render() }}
{% endblock %}
```

> Using the "New Entry" option in a CKEdit field would have its template already assigned. (Note: I think this feature is currently broken/bugged? All it does is enter the linked entry title)

That’s the default output for `render()` if a partial template hasn’t been defined for the entry type yet. Once you give the entry type its own partial template, that will be output instead.
