### ISSUE TITLE
[5.x]: Null value for `$asset->getFolder()->path`

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#14454]
### Description

I'm 90% certain that a bug has appeared in Craft 5, when trying to get the **folder path of an Asset**.

In short, the `$asset->getFolder()->path` is returning `null` instead of the expected string (`"uploads"`).

### Steps to reproduce

1. Set up a Filesystem and Volume.
2. Upload an Asset to that Volume.
3. Fetch the Asset, then try to get the folder path...

```php
$asset->getFolder()->path
```

<img src="https://github.com/craftcms/cms/assets/5309692/f554e018-9fab-404c-9b01-75a4c7fe13f5" width="600">

### Expected behavior

```php
// Should return "uploads"
$asset->getFolder()->path
```

### Actual behavior

```php
// Is actually returning `null`
$asset->getFolder()->path
```

---

There is a small chance that I'm simply misunderstanding how something here works. This issue was instigated by the Digital Download code, which has some ancient roots in the Craft ecosystem.

For more information, you can see where this issue is occurring in Digital Download...

https://github.com/doublesecretagency/craft-digitaldownload/blob/v3-dev/src/services/Download.php#L178

To trigger that line of code, you'd need to
1. [generate a download link](https://plugins.doublesecretagency.com/digital-download/displaying-a-link/) for an Asset, then
2. click the generated link to download the file
3. witness a "file not found" error.

Probably not worth tinkering with the plugin if you can identify the main issue with `$asset->getFolder()->path`.

Thanks for looking into this, let me know if you need any additional information! 🙏 

### Craft CMS version

5.0.0-beta.2

### PHP version

8.2

### Operating system and version

Mac

### Database type and version

MariaDB

### Installed plugins and versions

- Digital Download v3.0.0-beta.1

**Comment by i-just** [comment]
Hi, thanks for the detailed explanation!

This is expected behaviour. The `uploads` directory is a subpath of a `Volume`, and it does not affect the characteristics of a `VolumeFolder`. In other words, the `VolumeFolder`'s path is (still) relative to the `Volume`, and it’s the `Volume`'s base path that contains `uploads`, not the `VolumeFolder`'s. 

To achieve what you’re after, you need to throw in `Volume`'s subpath into the mix: 
`$volPath = $volume->getSubpath();`, 
and concatenate that into your `$filepath`: 
`$fsPath.$volPath.$folderPath`.

I hope this makes sense and clears things up! 
I’ll close this now, but feel free to reply if you have any further questions.

**Comment by lindseydiloreto** [comment]
This fix worked perfectly, thanks @i-just! 🍺 

https://github.com/doublesecretagency/craft-digitaldownload/commit/7d1328b6930f4297904c5bcdb0b89bc31266e7fb
