### ISSUE TITLE
Wonky sidebar behavior in latest Chrome on Windows 10

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#1448]
### Description

There is some general hard to reproduce wonkiness, but I've found a consistent way to reproduce some of it on the Rich Text field settings by toggling the available Asset Volumes and Asset Transforms checkbox.

![wonky sidebar](https://cloud.githubusercontent.com/assets/61869/23487794/40b55936-fe9d-11e6-80a3-5084d7a5fcbe.GIF)

### Steps to reproduce

1.  Go to Rich Text field settings.
2.  Toggle either Available Volumes or Available Transforms checkboxes.
3. Enjoy the trip.

### Additional info

- Craft version: 3.x
- PHP version: 7.x
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by narration-sd** [comment]
just a little side note, since it's you, @takobell -- the unicorn-level appreciated bar also overlays the bottom of the sidebar menu, so that you can't see or access My Account, Log Out, or any other future extras there.

Easy solution, that the Debug Bar should retreat as if you'd clicked its button again, whenever you are cursoring in the sidebar? And return as magnificently animated, of course...

**Comment by takobell** [comment]
Can't reproduce anymore, so assuming was fixed by magic fairies.

**Comment by benjamindavid** [comment]
@narration-sd We're looking into improving this behavior, thanks for the feedback!
