### ISSUE TITLE
[5.x]: Using enter/spacebar to activate breadcrumb links inside disclosures closes the menu

### ISSUE THREAD

**Issue by gcamacho079** [craftcms/cms#14598]
### Description
See title

### Steps to reproduce

1. Open a menu inside the global breadcrumb navigation (to choose a site or section)
2. Use enter/spacebar to activate a link

### Expected behavior
The user should go to the page selected

### Actual behavior
The disclosure menu closes

### Craft CMS version

5.0.0-beta.6

### Installed plugins and versions

-

**Comment by brianjhanson** [comment]
@gcamacho079 things seem to work with `enter` for me, just not `space`. Should both trigger the navigation?

**Comment by gcamacho079** [comment]
I may not have pulled recent changes, but that (`Enter` only for link activation) is indeed the native behavior. Our disclosures get tricky because some of our menus mix links and buttons, and it’s impossible to tell which you’re on. For example, in element action disclosures, we have a button to “Open in Image Editor” near a link to “Show in folder”

If we use the `activate` in instances like these, we’ll ensure both Enter/Space activate them and eliminate some of the guesswork about which key to use.

**Comment by brandonkelly** [comment]
I was on the fence about this because it felt a little weird to add a keypress listener to disclosure link items that were really just normal hyperlinks, but I agree it’s confusing since they are styled like other disclosure items. Just added the listener for the next release.

Note that for links with `target="_blank"`, the browser might end up blocking the new tab until you allow it.

![Screenshot of a message in Firefox about a new tab getting blocked](https://github.com/craftcms/cms/assets/47792/29d43d02-57a5-43bc-a569-120a897e80eb)
