### ISSUE TITLE
[5.x]: Can't query nested entries by type

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#14610]
### Description

`craft.entries.type('educationBlock').all()` does not find existing nested entries.

Quite sure this has worked before latest composer update...

### Craft CMS version

5.0.x-dev as 5.0.0-beta.7

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is due to a bug fix that just got pushed to `5.0` this morning (and is not included in 5.0.0-beta.8). Entry queries were not expected to return nested entries by default, unless any of the `owner`, `ownerId`, `primaryOwner`, `primaryOwnerId`, `field`, or `fieldId` params were specified (40ad3c92fb666585af2fea9c2edb9941df4c6d40).

(This is to ensure backwards compatibility with Craft 4 entry queries.)

**Comment by wsydney76** [comment]
OK, but how to query for entries regardless of nested or not? 

Thinking of a content model like this:

Section: Event (Stand alone)
* Types: Talk, ...

Section: Conference
* Matrix field: Agenda
 * * Types: Talk, Party

`craft.entries.type('talk').scheduledTime(...next2days...)`  
or `.type('talk').relatedTo(speaker)` 
or `.type('talk').hasLiveStreaming(true)` 
would be incomplete.

PS.

> (This is to ensure backwards compatibility with Craft 4 entry queries.)

Get that for queries by custom fields, relations etc. But as entry types get unique handles, I think existing queries like `.type('myOldEntryType')` will alway behave like before right after migration, because there can't be any ambiguity regarding former matrix block types?

**Comment by wsydney76** [comment]
@brandonkelly Probably related to this change, can't query for nested entry by its ID?

Getting this error when double clicking a card in a matrix field:

![image](https://github.com/craftcms/cms/assets/60010597/aa3d3c33-a702-41bb-830c-db567dc1726f)

**Comment by brandonkelly** [comment]
Sorry, yeah I can reproduce that, and just released 5.0.0-beta.9 which reverts that change.
