### ISSUE TITLE
[4.x]: Ignoring an entry in the search index will still add its matrix fields to the search index

### ISSUE THREAD

**Issue by dgsiegel** [craftcms/cms#14630]
### Description

Suppose I don't want to add any entry of a section called `foo` to the search index. In a custom module I hook into `Search::EVENT_BEFORE_INDEX_KEYWORDS` and set `isValid` to `false`:

```
Event::on(
  Search::class,
  Search::EVENT_BEFORE_INDEX_KEYWORDS,
  function (IndexKeywordsEvent $event) {
    $element = $event->element;
    if ($element instanceof Entry && $element->section->handle == 'foo') {
      $event->isValid = false;
    }
  }
);
``` 

This works fine when saving entries via the CLI (e.g. `craft resave/entries --update-search-index --section foo`). But if the section makes use of matrix fields *and* you save the entry via the control panel, the hook above will also be run for the matrix field and that will be added to the `searchindex` table:

```
select * from searchindex where elementId = 123456;
+-----------+-----------+---------+--------+---------------+
| elementId | attribute | fieldId | siteId | keywords      |
+-----------+-----------+---------+--------+---------------+
|    123456 | field     |       1 |      1 |  test foo 123 |
+-----------+-----------+---------+--------+---------------+
```
What I can do at this point is to check for matrix fields and load its parent:

```
Event::on(
  Search::class,
  Search::EVENT_BEFORE_INDEX_KEYWORDS,
  function (IndexKeywordsEvent $event) {
    $element = $event->element;

    if ($element instanceof MatrixBlock) {
      $element = $element->getOwner();
    }

    if ($element instanceof Entry && $element->section->handle == 'foo') {
      $event->isValid = false;
    }
  }
);
``` 

Now the entry and its matrix field will be ignored. But:

- why does the hook run for matrix fields as well?
- is this really the best way to ignore entries?
- what about other types like assets, categories, etc.?

### Craft CMS version

4.8.3

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
> * why does the hook run for matrix fields as well?

Because all elements will get their search keywords updated when saved, if any custom fields or attributes changed.

When you resave entries via `resave/entries`, Matrix blocks aren’t changing in the process, so there’s no need to update search indexes at that point.

> * is this really the best way to ignore entries?

Yeah probably. Craft doesn’t have any built-in way to toggle search indexing depending on the element.

You could simplify your code a little by fetching the root element via `ElementHelper::rootElement()`. (That will give you the root entry, if `$event->element` is a Matrix block, Neo block, Super Table row, etc.)

```php
v

> 
> * what about other types like assets, categories, etc.?

**Comment by brandonkelly** [comment]
> * why does the hook run for matrix fields as well?

Because all elements will get their search keywords updated when saved, if any custom fields or attributes changed.

When you resave entries via `resave/entries`, Matrix blocks aren’t changing in the process, so there’s no need to update search indexes at that point.

> * is this really the best way to ignore entries?

Yeah probably. Craft doesn’t have any built-in way to toggle search indexing depending on the element.

You could simplify your code a little by fetching the root element via `ElementHelper::rootElement()`. (That will give you the root entry, if `$event->element` is a Matrix block, Neo block, Super Table row, etc.)

```php
use craft\elements\Entry;
use craft\events\IndexKeywordsEvent;
use craft\helpers\ElementHelper;
use craft\services\Search;
use yii\base\Event;

Event::on(
    Search::class,
    Search::EVENT_BEFORE_INDEX_KEYWORDS,
    function (IndexKeywordsEvent $event) {
        try {
            $rootElement = ElementHelper::rootElement($event->element);
        } catch (Throwable) {
            return;
        }

        if ($rootElement instanceof Entry && $rootElement->section->handle === 'foo') {
            $event->isValid = false;
        }
    }
);
```

> * what about other types like assets, categories, etc.?

Those also get search keywords indexed.

**Comment by dgsiegel** [comment]
Thanks for the explanation @brandonkelly 💪️
