### ISSUE TITLE
[5.x]: Error when upgrading from Craft 4: "No entry types exist for section 4"

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#14708]
### Description

When upgrading a Craft 4 project, I see this happening:

web-1  | Applying changes from your project config files ...
web-1  | - removing sections.1d6b8da8-33fb-4983-a15c-44602365f901.entryTypes ... 
web-1  | 
web-1  | error: No entry types exist for section 4
web-1  |   - updating sections.1d6b8da8-33fb-4983-a15c-44602365f901 ...

It looks to be deleting the section's entry types, after which it fails to find them (duh).

### Steps to reproduce

1. If you can't reproduce this, I could mail my files

### Expected behavior

Upgrading works!

### Actual behavior

It doesn't

### Craft CMS version

5

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi @boboldehampsink, did you run `php craft project-config/rebuild` (and waited for any new background tasks to complete) before proceeding with the upgrade?

**Comment by boboldehampsink** [comment]
Hi @i-just, I did. Same error.

**Comment by i-just** [comment]
Thanks for confirming! Could you please send over the files? That error only triggers for Singles, but I’m unable to replicate it.

**Comment by boboldehampsink** [comment]
Just sent you the files via mail

**Comment by i-just** [comment]
@boboldehampsink, could you please check if the email was sent? I don’t see anything relating to this issue in our support@craftcms.com inbox.

**Comment by boboldehampsink** [comment]
@i-just done

**Comment by i-just** [comment]
Thanks for the files! 

When applying craft migrations, the `sections_entrytypes` table is created, and the relation between Entry Types and Sections is moved to that table. (In v4, it was a one-to-one relation, so it was stored in the `entrytypes` table.)

I can apply this PC to v4 without any problems. If I then do `composer update`, `craft migrate/all`, the "m230524_220029_global_entry_types" migration is applied, which moves the sections to entry types relations to the new `sections_entrytypes` table. I checked that table, and after the migration, it has the correct data in it. If I then run `craft project-config/apply,` it rightly says that there are no changes to apply and that the upgrade is finished. 

Going through the same process of first applying this PC to v4, running `composer update` and then `craft up` works as expected, too.

Any chance you could go through the upgrade process up until step 9 then instead of `craft up` in step 10, run `craft migrate/all` and check the `sections_entrytypes` table to see if it has all the sections to entry type relations you'd expect and let me know the outcome? (If it all looks good, in theory, you should then be able to run `craft project-config/apply`.)

**Comment by boboldehampsink** [comment]
Hi Iwona,

That did it, changing craft up to craft migrate/all fixed it. Is there a bug in craft up that needs adressing?

**Comment by boboldehampsink** [comment]
Too soon. Migrate/all worked, but didn't apply the PC ofcourse. After running project-config/apply, still getting this:

web-1 | error: No entry types exist for section 4
web-1 | - updating entryTypes.e8a2b2fd-e7ab-4419-9812-e17799f81f23 ... done

**Comment by i-just** [comment]
So after running `craft migrate/all ` did you check the contents of the `sections_entrytypes` table? Did it have a record with `sectionId` 4?

**Comment by boboldehampsink** [comment]
No, that is missing

**Comment by i-just** [comment]
Thanks for confirming! Could you send the database export from before the upgrade (for the Craft 4 site) to support@craftcms.com?

**Comment by boboldehampsink** [comment]
Here it is attached

Met vriendelijke groet,
Bob Olde Hampsink

Robuust · Digital Product Studio

Let op: wij zijn verhuisd, hier onder ons nieuwe adres en telefoonnummer.

Het Klooster
Philippus Robbenstraat 9
7665 AA Albergen
Tel. 0546 ‑ 898393

Mail naar ***@***.*** voor wijzigingen aan uw huidige website of applicatie. 

--- original message ---
On March 28, 2024 at 2:55 PM GMT+1 ***@***.*** wrote:



Thanks for confirming! Could you send the database export from before the upgrade (for the Craft 4 site) to ***@***.***?

—

Reply to this email directly, view it on GitHub, or unsubscribe.

You are receiving this because you were mentioned.Message ID: ***@***.***>
--- end of original message ---

**Comment by boboldehampsink** [comment]
Sent!

**Comment by i-just** [comment]
Thanks for the database export! I can only replicate what you’re experiencing if I use the Craft 4 database export in conjunction with the project config files you sent. If I only use the database export and rebuild the project config from it before starting the upgrade, everything works as expected (somewhat similar to this issue from a while ago: https://github.com/craftcms/cms/issues/13289).

The best way forward would be to restore the Craft 4 database backup, delete the `config/project` directory, ensure it’s rebuilt (e.g. by using the `ddev php craft project-config/rebuild`) and then start the upgrade again.

**Comment by boboldehampsink** [comment]
Thanks Iwona. I got it to work by upgrading to Craft 5 by using migrate/all (instead of up) only - then rebuild the PC.

**Comment by brandonkelly** [comment]
This is why step 3 of the [upgrade instructinos](https://craftcms.com/docs/5.x/upgrade.html#performing-the-upgrade) is to run `project-config/rebuild`.

If there are any pending project config changes at the start of running migrations, then any changes made by the migrations will be completely ignored – because Craft assumes that all the migrations’ project config changes were already made on another environment and will be applied once migrations are finished running.
