### ISSUE TITLE
[4.x]: Date field (without time) not working as expected due to timezone/time component in database

### ISSUE THREAD

**Issue by bgooren** [craftcms/cms#14732]
### Description

I use two date fields to indicate when a certain entry is the "active" one. 
So "Active from" and "Active to" (inclusive).

From my template I query for the active entry like so:

`craft.entries.section('mySectionWithActiveEntries').activeFrom('<= now').activeTo('>= now').one()`

... and this is mostly working but not fully correct.

For example: one entry is supposed to be active today (Sunday 31st of March); It is shown in the Craft admin as active from March 25th to March 31st.
But the query doesn't find it.

So I looked what is stored in the database, and found this:

activeFrom: 2024-03-24 23:00:00
activeTo: 2024-03-30 23:00:00

I'm pretty sure this is caused by using a date-only field, which puts the time to midnight. But, since my current timezone is UTC+1 (Amsterdam), it is converted to UTC which is one day earlier at 23:00.

However, when querying this with "now" (which is March 31st), it does not yield the expected result.

This is, of course, because the stored date does not match the one the user sees.

### Steps to reproduce

1. Add date field (without time component), when in a timezone +X UTC
2. Query this field with a date (e.g. "now")

### Expected behavior

The entry is found based on the date component in the query matching the date the user sees in the admin.

### Actual behavior

The entry is not found.

### Craft CMS version

4.8.1

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
Date-only Date fields will set the time to midnight of the date entered, for the system’s time zone, but then converted to UTC. In your case it looks like your system time zone is GMT+01:00, where midnight occurs at 11pm the night before, in UTC.

Time zones make everything more confusing, so to simplify, let’s pretend your system time zone is set to UTC. In that case, your `activeTo` field set to March 31st would be stored as `2024-03-31 00:00:00`.

And let’s say you are querying for entries with `activeTo('>= now')`, on March 31st at 10am on the dot. `now` is set to the current date **and time**, so that will look for entries where `activeTo >= 20224-03-31 10:00:00`.

The dates line up, but midnight (`00:00:00`) is _less than_ `10:00:00`, so your entry is going to be excluded from the results.

So what you really want to be looking for are entries where `activeTo` is greater than equal to _today at midnight_, not the exact current time.

Luckily, Craft defines a [`today`](https://craftcms.com/docs/5.x/reference/twig/global-variables.html#today) global variable (set to today at midnight) for exactly this purpose. So if you change your query param to `.activeTo(">= #{today|atom}")`, it should start working as expected.
