### ISSUE TITLE
[4.x]: TLS Email Encryption 

### ISSUE THREAD

**Issue by JordanMed** [craftcms/cms#14764]
### What happened?

This is less of a bug and more of a question. I've updated to craft 4 recently and I noticed that the option to select SSL or TLS. My emails from AWS are no longer working since upgrading. I used to have my port set to 587 using TLS but the option is just gone. 

### Craft CMS version

4.8.6

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out!

As per [this thread](https://github.com/craftcms/cms/issues/12387#issuecomment-1432043121), the encryption method dropdown was removed in Craft 4 because the Symfony Mailer didn’t respect this setting to begin with. The TLS verification will be performed [by default](https://symfony.com/doc/current/mailer.html#tls-peer-verification), though.
