### ISSUE TITLE
[5.x]: Horizontal clipping on element indexes

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#14765]
### Description

In element index pages the table can be clipped horizontally with no way to scroll:

![image](https://github.com/craftcms/cms/assets/19857599/41dcbc51-b6df-4b2c-971b-42a0c30726e6)

### Craft CMS version

5.0.2

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for reaching out! As in Craft 4, you should be able to scroll horizontally, and I just verified that it works as expected for me. If you can't scroll horizontally, can you please let me know what browser you’re using and if you see any errors in the console?

**Comment by thupsi** [comment]
Doh, you're right! I'm embarassed to say that, in the absence of a scrollbar, I didn't think to use the keyboard for horizontal scrolling. I wonder if the UI would benefit from a subtle scrollbar, even from an accessibility standpoint?

**Comment by brianjhanson** [comment]
The appearance of the scrollbars is handled on the OS level. If you're on Mac you can set them to be always visible via the "Show scrollbars" setting in Settings > Appearance. 

By default, the scrollbars appear at the bottom of the scrollable area. In this case, that means it's off the page and then hidden by the footer until you scroll all the way to the bottom. That's not ideal, but it's also the browser's default behavior, so it feels like swimming upstream to try to alter it too much. 

I did open #14781 to add some shadows to the scrollable area, but as I mentioned in the description, it's a lot of code for a relatively minor UX gain. We can't use some of the CSS hacks out there because those all seem to rely on a solid background for the illusion. 

We have a few other ideas that I'm going to explore, so hopefully, we can improve this a bit in the near future.

**Comment by thupsi** [comment]
Thanks @brianjhanson, that was impressively quick! Adding to the ideas (if you haven't already thought of it): When the 'scroll-timeline' CSS becomes stable it should help reduce the js too (no need to detect the overflow via javascript).

**Comment by brianjhanson** [comment]
We ended up dynamically setting the height of the `tablepane` and un-sticking the footer so the scrollbars will always be visible when there's an overflow. Since it's a slight change in behavior, [that change](https://github.com/craftcms/cms/pull/14786) is currently slotted for 5.1.

**Comment by thupsi** [comment]
Sounds good, thanks again!

**Comment by thupsi** [comment]
@brianjhanson I was thinking about this and even tried it manually on a project to see how it feels. One concern is that it could lead to double scrollbars (table and page), which generaly feels and looks kinda awkward. Also you have to move the mouse over the table to scroll. If people don't like it when this ships they will trace it back to me and burn my house 😜.

Was curious how others have solved it and Shopify has a pretty good version where the table height is not constrained, but the _horizontal scrollbar_ is _fixed to the viewport bottom_.

![image](https://github.com/craftcms/cms/assets/19857599/e01a7ba7-fa19-4471-a4fd-d916115430bb)

Maybe something worth considering. Just saying, in no way implying that you should blindly copy what Shopify does 🙂

**Comment by brandonkelly** [comment]
How is that even possible? Gotta be a hack, right? Maybe they are setting a parent container to the original height (so the full page height stays the same), then constraining the `<table>` height but adding `overflow-y: hidden`, and adjusting the table height as you scroll down.

**Comment by brianjhanson** [comment]
I'm guessing they do something like [this technique](https://stackoverflow.com/a/66470660) which throws a fake scrollbar down there and links up the scroll events between it and the container.

**Comment by thupsi** [comment]
Yes, I suppose they are doing something like the technique you shared. Did a quick search before and found [a fiddle](https://jsfiddle.net/1m1kegy3/4/) almost exactly like that.

**Comment by brandonkelly** [comment]
That seems like the ideal solution, if you want to give it a go, @brianjhanson!

**Comment by brandonkelly** [comment]
Craft 5.1 is out with the first pass at a fix for this.
