### ISSUE TITLE
[5.x]: Eager loading requires the original name of a field instead of its renamed value

### ISSUE THREAD

**Issue by brionwolf** [craftcms/cms#14823]
### Description

When using the eager loading, `with` parameter in entry queries, the array requires the original handle of a field, and fails to return anything if the renamed handle of a particular field is used.

### Steps to reproduce

1. Create a field and add it to a field layout _(ie: Label: `my favorite plaintext` handle: `myfavePlaintext`)_.
2. On the field layout rename the field and give it a new handle _(ie: relabel: `Some other label` rehandle: `someOtherHandle`)_.
3. At the template level, query for the entry, and include the handle of the field within the query's `with` parameter, using the field's new handle.

### Expected behavior

- The contents of the field are eager loaded, and available from the query.

### Actual behavior

- The query returns either null or an empty array for the specified field.

### Workaround

- If I use the original handle of the field in the query, I can still reference the field from its renamed handle within the template.

### Screenshot

![eager-loading-rehandled-field](https://github.com/craftcms/cms/assets/5532234/8d541252-0a92-4cbc-a273-4d541aa99953)

### Craft CMS version

Craft Pro 5.0.4

### PHP version

8.3.4

### Operating system and version

MacOS Sonoma 14.4.1 (23E224)

### Database type and version

MySQL 8.3.0

### Image driver and version

GD 8.3.4

### Installed plugins and versions

- CKEditor 4.0.3

**Comment by i-just** [comment]
Hi, thanks for reaching out!

I just tested this with an entries field with the original handle of `originalModel`, which has the handle changed to `model` in the entry type. If I eager load `model` I get the related entry (if one is added to the entry) and an empty collection if there aren’t any entries added to that field. 

I’m assuming that in the recording you attached, the `model` is the renamed handle and `modelsLandingSectionsMultiple` is the original one. If that’s correct, then the result you get for `page.model` when you query `with` `modelsLandingSectionsMultiple` is correct - you get the `EntryQuery` because you haven’t actually eager loaded the `model`.

I hope the above helps. I’m going to close this now, but feel free to reply if I misunderstood what you were saying!

**Comment by brionwolf** [comment]
Hi @i-just, sorry about mugging up the issues feed, Thanks for the support and feedback! got it working!

**Comment by i-just** [comment]
Great news. Thanks for confirming!
