### ISSUE TITLE
[4.x]: Slugs/URLs are Case insensitive

### ISSUE THREAD

**Issue by alexgit2k** [craftcms/cms#14835]
### Description

Craft CMS allows slugs to be case-insensitive. While this is not a problem for automatic generated internal links, it can happen if user type in the address manually.
In some cases that led to addresses with wrong-cases in searchengines.

The correct case can be set in the meta-tags as canonical. However, canonicals are for Google only an indication not a directive. So Google can ignore the canonicals.

### Steps to reproduce

1. Create a page with slug "apple"
2. Call <domain>/APPLE

### Expected behavior

<domain>/APPLE should redirect to <domain>/apple

### Actual behavior

<domain>/APPLE shows content of <domain>/apple

### Craft CMS version

 4.8.9

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
There are multiple ways to access an entry’s page from the “wrong” URL:

- alternate hostnames (e.g. `www.example.com` instead of `example.com`)
- `index.php` explicitly included in the URL
- trailing slash in the URI
- URI casing differences
- unique query string params
- etc.

Craft will always generate URLs consistently based on the actual site base URL (assuming it doesn’t start with `@web` which is not recommended), based on the [omitScriptNameInUrls](https://craftcms.com/docs/5.x/reference/config/general.html#omitscriptnameinurls), [usePathInfo](https://craftcms.com/docs/5.x/reference/config/general.html#omitscriptnameinurls), and [addTrailingSlashesToUrls](https://craftcms.com/docs/5.x/reference/config/general.html#addtrailingslashestourls) config settings. So as long as you’re sticking to Craft-generated URLs, any redundant URLs should never leak out in the first place. And even if they do, specifying a canonical URL will mitigate any potential SEO hit.

We did discuss whether it would make sense for Craft to start automatically redirecting when it can detect that a URL isn’t quite right. But there are edge cases where it might not be expected. In the case of URI casing, the point at which we’d want to enforce that would be before routing takes place, but it’s only by convention that all of Craft’s built-in routing is case insensitive. There could be modules and plugins out there which are intentionally routing other things in a case-sensitive way.

If you really want to force URIs to always be lowercase via a redirect, you can do that within your web server config.
