### ISSUE TITLE
Improving the understandability of Site-specific Asset Field setup

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1499]
### Description
This is further clarified by the work to tie down #1501, so I'm updating it. Into the fray, then, and apologies as felt needed, as the points come out as they will.

- On Asset field definition one can only guess what the item 'Target Site' means, while '_Source_  Site' would be so much more clear, no? We are talking about where Assets will come from, ergo. 

Going further, the meaning of the first and default choice, 'Same as Source', seems really obscure. Target is same as Source?? But as well, it strongly seems this should not be the default choice, as I don't think the usual nondefault site will have its own asset resources.

I think it's clear then also that a proper default choice isn't present. Shouldn't this be 'From default Site'? Adding this choice on top, and making it default, would be clear and cause expected operation to be the normal mode.

Now we are clear.

- Then, 'Manage relations on a per-site basis'. I get what it hints or possibly means, codey-wise, though the field is open on that, no pun.  But.  

How about matching the concept of Translation Method option for text fields, as: 'Asset Choice Method',, so that it's easy to see it's a similar thing?

I think you also want to offer  similar choices as text fields do, because you may well want the image/s to follow language, rather than Site. Example in my past, in complex multinational online learning, where for several locales as we understand them here, the cartoons had signpost signs in it, which need to speak in Chinese for several target countries, and maybe a different local dialect or customary saying which would not be covered by the two main ch variants, traditional and simplified-by-Mao.

Are there other meanings for the present 'Manage relations...' label? I could think of a possible few. In which case I feel you should simply add an as-usual smaller type note explaining what else will be affected, while keeping the non-obscure primary label as proposed.

Thank you, thanks for listening -- suspecting others will thank you also.

### Steps to reproduce

1. -- #1501's problems and sequence wouldn't be a bad way to try this from a CMS client's perspective and see...
2.

### Additional info

PHP version	7.1.2-3+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	GD 7.1.2-3+deb.sury.org~xenial+1
Craft edition & version	Craft Personal 3.0.0-beta.7
Yii version	2.0.11.2
Twig version	2.1.0
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins: none

**Comment by narration-sd** [comment]
A little addendum to this one, as I thought through another concern this morning, and think you have it well enough covered in principle, especially given above last item, but that it will probably be very useful to make the pattern clear in doc.

The concern  was in handling multiple images, some of which need to be per-Site or as above per-Language, but not to have to define a specific asset bundle for each one. 

Actually this is cleanly handled by having just two bundles: a siteably-defined one, and a normal one. Corallary is that you only need to have site-local asset folders and files for those siteable assets. Works.

I presume this will all continue to work if defining CRAFT_SITE from the web server and an environmental used to set it in the main web/index.php, thus without actually visiting the site folder in the Site definition....

**Comment by brandonkelly** [comment]
Thanks for pointing this out, Clive.

It’s a little awkward because multiple meanings of “source” are colliding on relational field pages.

- Element types have “sources”, which are what make up their source lists on their index pages and selection modals, as well as the Sources setting on relational fields.

- Relations have a “source element” (the element that has the field) and a “target element” (the element that was selected in the field).

So the “Sources” setting referred to the element sources; the “Target Site” setting referred to the site that the relations should be selected from. The word “source” in its “same as source” option referred to the “source element” of the relation.

Anyway, think I just cleared this up, for the next release. Initially, you will just see this:

<img src='https://shipusercontent.com/67085f88f770b880a4ebd9e4e3e5087d/Screen%20Shot%202017-04-04%20at%2011.20.17%20AM.png' title='Screen Shot 2017-04-04 at 11.20.17 AM.png' width=275>

And if you check the box, you will see this:

<img src='https://shipusercontent.com/bd51fa119402f7c054ef0fc8082daa88/Screen%20Shot%202017-04-04%20at%2011.21.08%20AM.png' title='Screen Shot 2017-04-04 at 11.21.08 AM.png' width=312>

**Comment by narration-sd** [comment]
Thanks, Brandon -- and that looks really clear, this reorganization of what concept is actually in view. 

Great careful thinking as ever -- I always appreciate when you do this, and it's a real talent, believe it.
