### ISSUE TITLE
[4.x]: License Popup shouldn't happen if licence only needs renewing 

### ISSUE THREAD

**Issue by DowleyDeveloped** [craftcms/cms#15137]
### What happened?

When a license runs out, should the license popup on the site still display? Renewing your licences are optional at this point to continue getting support & updates, however we're getting the control panel block anyway.

If we already own the license, but don't want to renew for a while (due to costs etc), should the popup really show?

### Craft CMS version

4.9.5

### PHP version

8.2

**Comment by brandonkelly** [comment]
Craft should only be nagging you about an expired license if you have installed a version that is beyond what your license allows. Is that the case here?

**Comment by DowleyDeveloped** [comment]
@brandonkelly not sure what you mean by license allows? 

We’ve had instances where the license has expired (can’t update until renewed) and the Craft license popup displays. Surely this shouldn’t show if the license was previously purchased?

**Comment by brandonkelly** [comment]
When a license expires, it’s locked at whatever version you were using at the time, and updating beyond that would require you to renew the license, otherwise you’ll get the nag screen.

(As of Craft 4.8.0 we loosened the license enforcement a little, to start allowing you to “trial” out-of-bounds versions of Craft/plugins locally. So you’ll only get nagged about renewing your license on production.)

You may have unintentionally updated an expired package by running `composer update`, if it has a range-based version requirement in `composer.json`, such as `^1.0.0`. We try to help avoid that by setting Craft/plugin package requirements to specific versions when installing/updating within the control panel or `update` command—both of which will also help guard against updating beyond the licenses’ allowed versions as well. But there’s nothing we can do to prevent `composer update` from working as designed when you have a range-based requirement.

**Comment by DowleyDeveloped** [comment]
Ah! That makes sense, thanks!
