### ISSUE TITLE
[5.x]: Primary site language not respected when replacing missing translations

### ISSUE THREAD

**Issue by gustavs-gutmanis** [craftcms/cms#15267]
### Description
A customer has notified us that their translations do not work as expected, but after investigating, it seems like that is the default Craft behavior.

https://github.com/solspace/craft-freeform/issues/920

In this GH Issue, they mention that they have set up a site who's primary language is not `en-US` (for the sake of the argument, lets assume it's `de`).  
If they have a key of, say, `Guten Tag`, and there is an entry in the `translation/en-US/app.php` of `'Guten Tag' => 'Hello'`, even though the site is currently opened in the `de` language, Craft will still fetch the `en-US` translation, since there is no entry for it in the german file (which doesn't even exist). 

![image](https://github.com/craftcms/cms/assets/709181/5a34925a-ba10-4f91-9541-d71aa3dbd4c8)
![image](https://github.com/craftcms/cms/assets/709181/7c12e40c-cc13-4301-8bd7-caca875de005)
![image](https://github.com/craftcms/cms/assets/709181/69b09aae-e792-474e-86db-8b8573128c71)

### Steps to reproduce

1. Create two sites `en` and `de`
2. Set `de` as the primary site
3. create a translation file `translations/en/site.php`
4. enter in it a key => value pair of `'Guten Tag' => 'Good Day',`
5. create a new template in the frontend
6. output `{{ "Guten Tag"|t('site') }}` in it
7. open the site in both `en` and `de` variations

### Expected behavior

* It should show up as `Good Day` in the `en` site  
* It should show up as `Guten Tag` in the `de` site

### Actual behavior

* It shows up as `Good Day` in both the `de` and the `en` variants

### Craft CMS version

5.2.0 (pro)

### PHP version

8.2.18

### Operating system and version

Ubuntu 20.04 (DDEV v1.23.0)

### Database type and version

MySQL v8.0.33

### Installed plugins and versions

- Freeform v5.5.0.1

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

Plugins get the [translation categories registered automatically](https://craftcms.com/docs/5.x/extend/translation-categories.html#plugin-translations). When this happens, they’re registered with a `sourceLanguage` set to `en-US`.

The language of the primary site doesn’t matter here. The same thing will happen when you have your primary site set to EN and a second one to DE.

The situation you’re describing will only occur if you’re trying to show a translated string on a site that’s not in English and you have no translation file for that site, but you have English translations. For example, if you’re showing a translated message in German while not having a German translation file and having an English translation file.

This is where it happens: https://github.com/craftcms/cms/blob/5.x/src/i18n/I18N.php#L315-L321.

Solution 1: if you have an English translation file, you should also create one for other languages you intend to support - otherwise, the English translation will be used as a fallback.

Solution 2: You can change the `sourceLanguage` for a given translation category (e.g. specific plugin) like mentioned here: https://craftcms.com/docs/5.x/extend/translation-categories.html

I hope this helps!

I will close this now, but feel free to reply if you run into any further issues.

**Comment by gustavs-gutmanis** [comment]
Thank you @i-just, as long as it works as expected, this is fine. Thank you for the information.
