### ISSUE TITLE
Allow Element::afterSave to roll back DB transaction

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1527]
I've asked this before and the method to cancel/roll back was to throw an Exception within the `Element::afterSave` method, but it seems like a very brute way of handling an error.

A use case:
Communicating with third party web services to push/pull data.  When pushing data, much of the time you cannot perform a 'dry run' to see if the update will stick so the only option we have is to use the afterSave event.  In a couple scenarios, if an error returns (and we display it to screen) the user can alter their input to resolve the error ... whereas an exception halts everything and they must re-populate the element.

**Comment by brandonkelly** [comment]
We spent a lot of time debating what the best control flow for actions like saving element, etc., is, taking a lot of different use cases into account. We decided that once the `before*` events have fired, anything short of an exception or fatal error should not halt the process.

If we changed it to what you’re suggesting, then you wouldn’t be able to rely on `after*` events. What if your plugin went through the trouble of passing the entry data off to a 3rd party API, but then another plugin comes along and cancels the whole transaction? I’d say that is a more worrisome scenario then API availability issues.

A better solution to API availability issues would be to separate the save event from the API call, with a queuing system. One example you could turn to is the [Apple News](https://github.com/pixelandtonic/AppleNews) plugin. It sets up its own News API queue, and attempts to publish articles to it through background tasks, rather than right when the entry is saved. That way it is not completely reliant on the API.
