### ISSUE TITLE
[5.2.5]: Craft CMS Multisite - viewing page under non-primary domain shows 404 

### ISSUE THREAD

**Issue by akiraWalk** [craftcms/cms#15334]
### Description
Hey guys, issues in a multisite environment. When I create an entry under the secondary site, I get a 404

### Steps to reproduce

1. I have set up aliases in general.php `@web` and `@webtsc`
2. assigned aliases to the base url respectively in site settings 
3. Settings > Sections > Site Content has the Propagation Method set to "Save entries to all sites enabled for this section" in my understanding i should be able to create entries and choose which site an entry should be shown on
4. Create an entry and only display on the secondary site
5. ![Screenshot_3](https://github.com/craftcms/cms/assets/157441252/76f72c9b-6645-4ca3-b9ef-358925b789ae)
6. save and view and I get the 404 error

### Expected behavior
I should see the page that I've created

### Actual behavior
I get a 404

an email has been sent with DB and domains in question

### Craft CMS version

5.2.5

### PHP version

8.2.20

### Operating system and version

Linux 4.18.0-553.5.1.lve.1.el8.x86_64

### Database type and version

MariaDB 10.6.18

### Image driver and version

GD 8.2.20

### Installed plugins and versions

-
![Screenshot_2](https://github.com/craftcms/cms/assets/157441252/b00d14ae-8899-41c3-b9b9-f42bf2bd6a19)

**Comment by brandonkelly** [comment]
> assigned aliases to the base url respectively in site settings

Can you post your `aliases` config setting, as well as any environment variables they might be referencing?

**Comment by akiraWalk** [comment]
From general.php
```
'aliases' => [
    '@web' => craft\helpers\App::env('SITE_URL'),
    '@web_tsc' => craft\helpers\App::env('TSC_SITE_URL'),
],
```

env
```
SITE_URL=https://port****.com.au/
TSC_SITE_URL=https://tsc******.com.au/
```

The actual domain is in support with Tommy. Let me know if you require anything more.

**Comment by brandonkelly** [comment]
Multiple issues here:

- `@web` is a special alias that should always resolve to the _requested_ base URL. So if you’re accessing Craft from `https://port****.com.au/`, it should be `https://port****.com.au/`; if you’re accessing Craft from `https://tsc******.com.au/`, it should be `https://tsc******.com.au/`.
- Since `@web` is supposed to vary based on the incoming request, you shouldn’t use it for site base URLs on multi-site installs. (We’re making that more clear starting in Craft 4.11 / 5.3 via #15347.)

So to fix:

1. Remove both of your aliases
2. Edit your site settings and set the Base URL settings to your environment variables directly (`$SITE_URL` and `$TSC_SITE_URL`).
