### ISSUE TITLE
[4.x]: Date Field isn't filtering >= now correctly

### ISSUE THREAD

**Issue by Jude867** [craftcms/cms#15340]
### Description
I'm not sure if this is a bug or something I'm doing wrong. Please advise
I have a date field 'eventEndDate'.
I want to show all entries with a date greater than or equal to today.
When I use >= now it doesn't show entries of the same day - if I change the end date to the day after it shows but not the same day.

### Steps to reproduce

1. Create events section with eventEndDate date field
2. Set the events with the following code

`{% set eventQuery = craft.entries().section('events').eventCategory(selectedEventCategory).eventEndDate('>= now').limit(30).orderBy('eventStartDate ASC').with(['thumbnailImage']) %}`

### Expected behavior

To be able to see entries with an end date up to and including today.

### Actual behavior

I only see entries with an end date up to today. Any events ending today aren't shown.
If I change the end date to one date after today it shows up

### Craft CMS version

Craft Pro 4.10.5

### PHP version

8.2.20

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
When you set a Date field (Date only, not Date + Time) to a date, the actual field value ends up being midnight of the selected date.

So unless the clock is exactly midnight, `>= now` isn’t going to give you what you want, because it’s going to look for Date values that are >= the current time of the current date; not midnight of the current date.

Instead of `now`, you can use `today`, which represents midnight of the current date.

```twig
{% set eventQuery = craft.entries()
  .section('events')
  .eventCategory(selectedEventCategory)
  .eventEndDate('>= today')
  .limit(30)
  .orderBy('eventStartDate ASC')
  .with(['thumbnailImage']) %}
```
