### ISSUE TITLE
Some strings are untranslatable

### ISSUE THREAD

**Issue by tu5** [craftcms/cms#1540]
### Description
Some strings are untranslatable.

"One-Time Price" (license buying pop-up)
"Simple", "Standard"(?) (Redactor config settings) 
"Content", "Default" (tabs in Design your field layout)
Default element names (in Design your field layout)
"Requirement Report" (server info)
reflection, pcre, spl, pdo, gd/imagemagick descriptions (server info)

### Additional info

- Craft version: 2.6.2967

**Comment by takobell** [comment]
> "One-Time Price"

Fixed for the next release.

> "Simple", "Standard"

Those are defined by the file names in `craft/config/redactor`.

> "Content", "Default" (tabs in Design your field layout)
> Default element names (in Design your field layout)
> "Requirement Report" (server info)

Fixed for the next release.

**Comment by brandonkelly** [comment]
Fixed in commits 282c60f43702a78db9fb52acfb3423f5e2f11472 and 531ef7aa8a9f62f3bde089a75cad48655ee017e1.

> reflection, pcre, spl, pdo, gd/imagemagick descriptions (server info)

We ended up deciding that _none_ of the requirement names/descriptions should be translated, since these issues generally end up becoming support tickets, and it's easier for us to support it if we're looking at the English string. (Plus, they’ve already lost their translations in Craft 3, since the requirements are no longer defined within the Craft application itself anymore.)
