### ISSUE TITLE
[5.x]: With autosaveDrafts disabled, saving entry with validation errors causes issues with Matrix/Neo blocks

### ISSUE THREAD

**Issue by ttempleton** [craftcms/cms#15418]
### Description

When the autosaveDrafts setting is disabled, when saving an entry that had previously failed to save due to validation errors, some of the non-field data for Matrix/Neo blocks is omitted from the POST data. This causes things like disabled state to be lost, and Neo block levels being lost leading to loss of Neo block structure (related issue: https://github.com/spicywebau/craft-neo/issues/907).

### Steps to reproduce

1. Set autosaveDrafts to false in CMS config
2. Create a new entry with a Matrix field set to display as blocks
3. Add a Matrix entry and set it as disabled
4. Don't put in a required field
5. Save the owner entry. Craft will give a validation error
6. Fix that validation error and save it again
7. After saving the owner entry, the Matrix entry is enabled

### Expected behavior

Matrix entry stays disabled after saving owner entry

### Actual behavior

Matrix entry is enabled after saving owner entry

### Craft CMS version

5.2.8

### PHP version

8.2.20

### Installed plugins and versions

- Neo 5.1.0

**Comment by brandonkelly** [comment]
Thanks for reporting that!

Culprit was that this code no longer really applies to newly-added nested Matrix entries, since we now create actual new entries immediately when you press “New [entry type]” over Ajax:

https://github.com/craftcms/cms/blob/c0a690ae58c795de61edb725460f87d9ddeae292/src/templates/_components/fieldtypes/Matrix/block.twig#L136-L138

So delta names were getting registered for every nested entry’s input namespace (which covers `…[enabled]`), even for entries that had just been created.

Fixed by [having newly-created nested entries start life as unpublished drafts](https://github.com/craftcms/cms/commit/330d848793583c9c6637ee2df839c82a6f577fdc), so we can check for in that condition:

https://github.com/craftcms/cms/blob/330d848793583c9c6637ee2df839c82a6f577fdc/src/templates/_components/fieldtypes/Matrix/block.twig#L136-L138

Since the fix was a bit involved, I decided to do it on the `5.3` branch, which will be going out in a couple weeks.
