### ISSUE TITLE
[4.x]/[5.x]: `Craft::debug()` no longer prints to logs

### ISSUE THREAD

**Issue by ghost** [craftcms/cms#15435]
### Description

We have an internal plugin that we use for many of our Craft CMS projects. It uses `Craft::debug()` to write debug logs in the dev environment. However, I've noticed that this no longer works in projects running Craft 4 **or later**.

### Steps to reproduce

1. Set up a fresh Craft CMS 5 install
2. Use the `php craft make module` command to setup a test module
3. Add a `Craft::debug()` line to the `init()` method of the module
4. Run `tail -f storage/logs/* | grep 'web.DEBUG'` to watch the logs in the terminal
5. Reload the index page in the browser and observer that no `debug` log entry is written

### Expected behavior

`debug` entries are written to the log.

### Actual behavior

No `debug` entries are written to the log.

### Craft CMS version

4+

**Comment by timkelty** [comment]
@seb-enovate Since Craft 4, when Craft started using Monolog for its logging, the default minimum level was changed to `info` [when dev mode is enabled](https://craftcms.com/knowledge-base/what-dev-mode-does). You're right that in Craft 3, it was `trace`, aka `debug`.

To print `Craft::debug()` logs, you can change the default logging level in `config/app.php` like so:

```php
<?php
use Psr\Log\LogLevel;

return [
    'components' => [
        'log' => [
            'monologTargetConfig' => [
                'level' => LogLevel::DEBUG,
            ],
        ],
    ],
];
```

Alternatively, if this is for a dedicated module/plugin, you can set up a dedicated log target with whatever level you specify. Examples of both of these configurations can be found [in the docs](https://craftcms.com/docs/5.x/system/logging.html#customizing-logs).

**Comment by ghost** [comment]
Thanks Tim. I'm just wondering if the docs ought to be tweaked slightly. For example in [this section of the docs](https://craftcms.com/docs/5.x/system/logging.html#using-craft-s-logger):

![image](https://github.com/user-attachments/assets/93f60a70-04aa-4fd5-8fb3-f66ac5040233)

It states the convenience methods, which includes `trace` and `debug`, and then says:

> By default, Craft logs all levels when [devMode](https://craftcms.com/docs/5.x/reference/config/general.html#devmode) is enabled. Otherwise, anything lower than warning will be ignored.

To me, "Craft logs all levels" suggests that `trace` and `debug` would work, even though as you've explained this is intentionally not the case?

**Comment by timkelty** [comment]
Indeed, that is misleading, and likely leftover from when that was the case. We'll get it updated!: https://github.com/craftcms/docs/pull/639
