### ISSUE TITLE
Matrix field individual instructions limited to 64 characters

### ISSUE THREAD

**Issue by marionnewlevant** [craftcms/cms#1543]
### Description
Instructions for a matrix field text box won't accept more than 64 characters (seems too short to me)

### Steps to reproduce

1. Create a matrix field, create a block type, create a field in that block type
2. Fail to enter more than 64 characters in the Instructions

### Additional info

- Craft version: Craft Personal 3.0.0-beta.7
- PHP version: 7.0.3-5+deb.sury.org~trusty+1
- Database driver & version: MySQL 5.7.11
- Plugins & versions: no plugins

**Comment by brandonkelly** [comment]
@marionnewlevant Is MySQL’s charset set to `utf8mb4` by chance?

**Comment by marionnewlevant** [comment]
I don't think so..
SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';
character_set_client	utf8
character_set_connection	utf8
character_set_database	utf8
character_set_filesystem	binary
character_set_results	utf8
character_set_server	latin1
character_set_system	utf8
collation_connection	utf8_general_ci
collation_database	utf8_unicode_ci
collation_server	latin1_swedish_ci

**Comment by takobell** [comment]
So weird... at first I could reproduce this with utf8 on MySQL.  Went to xDebug the issue and it worked and now I can't reproduce it anymore.

**Comment by narration-sd** [comment]
Here's a little more - got curious because of my little trip with utf8 last week. But au contraire to Brandon's first idea, I don't think it has anything to do with character classes. Though I looked all over that at first, right down to C3's dsn string, database field  defs, etc.. 

But:
- an old Matrix field I had would accept my test string, 386 characters, and save it fine too. Which is should, as `instructions` is a text database field type.
- when I created new block `Marion` and a simple text field `Newlevant`, I couldn't put more than (exactly) 64 characters into  the `instructions` textarea for it. It would save that.
- trying another fresh field, no maxlength is apparently set on the textarea, nor were there apparently any event listeners according to Chrome latest debugger. So I guess the limit to be monitored somewhere in Garnish's labyrinth on keypresses, pastes, etc.. But hmm??
- here's the thing. After I'd once saved the Matrix field, and gone back in, I could now type beyond 64 chars or paste in my large string, no problem. And save it successfully.

So: 
- what you saw is replicated here, if mystery, Brad
- if you really need to go forward, Marion, you can enter your full instructions on a second try.
- I would really like to know how the field length is limited in the first place, that I can't see it in the debugger .If you have the answer to that, you know where to look, and find what is different for it before and after the Matrix-block-field definition first saves.  Bringing coals to Newcastle, I know...had a long day with Docker...

**Comment by narration-sd** [comment]
Well, that's very simple, isn't it.

But educate me, Brandon. Looking again on the beta7 release, I see there's actually the maxlength=64 right there on the textarea html  - surprising me on both Chrome and Firefox latest debuggers. Because, this shows up nowhere in their Styles or Computed lists where I was expecting it, on either.

Why doen't it show as an inline style? Something to do with that you created it using JS, in a manner I remember now well as a pattern,  from earlier forays into that pretty-nice-indeed Garnish? If so, not a nice thing, and has to be watched out for.

Occams razor, anyway.  Sometimes a vivid imagination isn't a particular help in webcodey-land, generating false propositions...n'est-ce pas?

**Comment by narration-sd** [comment]
a pic - if useful

![maxnotmax](https://cloud.githubusercontent.com/assets/247945/24276324/23c792be-0ff3-11e7-9ea5-2f5f258fa226.png)

**Comment by narration-sd** [comment]
Ok, I looked into this, and well enough resolved -- as a case to watch out for, mainly.

No clear answer, and there have been many Developer Tools bugs in this  area, but after looking around, one might guess the actual reason `maxlength `might not be chosen to show under Styles is because it's not CSS - it's rather an HTML property only.

Frankly, that feels a bit blockheaded, such strict categorical thinking in the tool, but there you are....

Missing the tag in the first place came either by too-focused attention, or that certain spectacles and screen width don't always perfectly get along.
