### ISSUE TITLE
[5.x]: Custom Translation Category not picked up

### ISSUE THREAD

**Issue by svondervoort** [craftcms/cms#15502]
### Description
In Craft 4 we added the following to `config/app.php` to include our custom translation category. This works for Craft 4 but doing the same thing in Craft 5 doesn't seem to pick up the translation.

```
'i18n' => [
    'translations' => [
        'consent' => [
            'class' => craft\i18n\PhpMessageSource::class,
            'sourceLanguage' => 'en',
            'basePath' => dirname(__DIR__) . '/translations',
            'allowOverrides' => true,
        ],
    ],
],
```

We have this folder structure:
- translations
  - en
    - consent.php
    - site.php

This is a translation inside the consent category:
```
'consent.accept.marketing' => 'marketing cookies',
```
This is the twig logic used
```
{{ 'consent.accept.marketing' | t('consent') }}
```

### Steps to reproduce

1. Create a custom translation category
2. Add the logic to `config/app.php`
3. Add a translation to a template including the translation category

### Expected behavior

I'm expecting the template to pick up the translation from the custom translation category.

### Actual behavior

I just see the translation key instead of the translation from the file.

### Craft CMS version

5.2.8

### PHP version

5.3

**Comment by i-just** [comment]
Hi, thanks for reaching out! 

If the site you’re on is set to `en` and the `sourceLanguage` in your config is set to `en`, then [this check](https://github.com/craftcms/cms/blob/5.3.1/src/i18n/I18N.php#L318) will return `false` and cause the original message to be returned (in this case, `consent.accept.marketing`). (This logic is the same in v4 and v5.)

If you change the `sourceLanguage` in your config, e.g. to the default `en-US`, it should start working as expected.

In case you find it helpful, here’s a somewhat related issue with a bit more details: https://github.com/craftcms/cms/issues/15267.

Hope this helps!

**Comment by svondervoort** [comment]
Hi @i-just thanks for clarifying the logic.

I checked and the sites languages is also set to `en` just like the `sourceLanguage` in the config.

I'm also not sure how it works for multi-locale sites, do I have to add a config for each language to the `config/app.php` or just for the default site language? In a Craft 4 project it is working for a site with locale `nl` while the config is the same as shared above.

**Comment by i-just** [comment]
Not a problem!

> do I have to add a config for each language to the config/app.php

No, you add your translation category (`consent`) once and then add as many language-specific translation files as you wish to the translations directory. If you were to use the config with the `sourceLanguage` still set to `en` on a `nl` site, it would still work. It’ll do what you reported (show the original message string you have in your, e.g. twig file ) only if the source and target languages are the same.

**Comment by svondervoort** [comment]
@i-just the only thing is it is not working for Craft 5 even when the site language and sourceLanguage match. Any idea's / check I could try to pinpoint the problem?

**Comment by i-just** [comment]
If the site language and `sourceLanguage` match, then [this check](https://github.com/craftcms/cms/blob/5.3.1/src/i18n/I18N.php#L318) will return false and cause the original message from your e.g. twig file to be returned. In your case, the string is `'consent.accept.marketing'` so that’s what’s returned. I attached 4 screenshots that hopefully help visualise this.

en + en
<img width="563" alt="Screenshot 2024-08-08 at 14 24 25" src="https://github.com/user-attachments/assets/facdd526-a571-48cf-949b-f282e47e7177">

en + nl
<img width="574" alt="Screenshot 2024-08-08 at 14 24 45" src="https://github.com/user-attachments/assets/cc19c69b-e1a7-4964-8dbe-3576ed21c861">

en-US + en
<img width="548" alt="Screenshot 2024-08-08 at 14 25 13" src="https://github.com/user-attachments/assets/d92186cd-5f5a-4ad1-b4e2-09e0522fdd43">

en-US + nl
<img width="567" alt="Screenshot 2024-08-08 at 14 25 21" src="https://github.com/user-attachments/assets/a57ff253-7bfd-42d2-9602-468ef521fd3f">

Are you saying the translations don’t work for you even if the `sourceLanguage` differs from the site language?

**Comment by svondervoort** [comment]
@i-just oh sorry now I understand what your saying with the site language and sourceLanguage matching..

Isn't that a weird way of working though? What is the purpose of the `sourceLanguage` in this case? Or is it because I am using a descriptive key instead of a proper sentence? That has been the way for us of doing translations.

I mean the translation is correctly loading from the file now so you don't hear me complaining.

So I guess the reason it worked for the Craft 5 instance is because the sourceLanguage was set to `en` but the site language was `nl`..

**Comment by i-just** [comment]
> So I guess the reason it worked for the Craft 5 instance is because the sourceLanguage was set to en but the site language was nl..

Yes, that’s it.

> What is the purpose of the sourceLanguage in this case? 

`sourceLanguage` is supposed to be the language the application is written in and the language that the messages are written in: https://www.yiiframework.com/doc/api/2.0/yii-base-application#$sourceLanguage-detail

> Or is it because I am using a descriptive key instead of a proper sentence? That has been the way for us of doing translations.

Using a descriptive key is highlighting exactly how this feature works. You can still make it work this way if you wish, but you’ll have to be careful about the `sourceLanguage` you set up your custom translation category with so that it doesn’t match any languages used by the sites you set up.

I hope this helps!
