### ISSUE TITLE
AssetFileModel getUrl() adds "{siteUrl}" to path

### ISSUE THREAD

**Issue by SanboKyo** [craftcms/cms#1561]
### Steps to reproduce

1. "{{ entry.images.one().url() }}" in twig template.
2. get this "{siteUrl}/asssets/images/image.jpg" 

### Additional info

- Craft version: 3.0.0-beta.7
- PHP version: 7.0.13
- Database driver & version:
- Plugins & versions:

**Comment by carlcs** [comment]
You’re getting `{siteUrl}` in your path, because there is no "Environment Variables" in Craft 3:
https://github.com/craftcms/docs/blob/master/en/upgrade.md#environment-variables

Documentation for how to set paths from a config in Craft 3:
https://github.com/craftcms/docs/blob/master/en/configuration.md#overriding-volume-settings

**Comment by brandonkelly** [comment]
What @carlcs said.
