### ISSUE TITLE
[5.x]: Migration archiveTableIfExists doesn't work as expected

### ISSUE THREAD

**Issue by KlingeSean** [craftcms/cms#15621]
### Description
![image](https://github.com/user-attachments/assets/d25f2763-6d37-4766-aae9-812a2f0d3370)
This is what the "archiveTableIfExists" from the "craft\db\Migration" class tells me will happen.

But when we try to do an archive we get weird results like 
1. "craft__old" 
2. "craft_old1"
3. "craf_old10"

We make an archive using:
```php
foreach ($tables as $table => $data) {
    $tableName = "{{%$table}}";
    if (!empty($data['archive']) ? $data['archive'] : false) $this->archiveTableIfExists($tableName);
```

### Steps to reproduce

1. Archive a table. 

### Expected behavior
seeing an archived table like `$tableName . '_old'`

### Actual behavior
![image](https://github.com/user-attachments/assets/fc22a869-9524-4c0f-9c86-4e2ab27fc4ab)
![image](https://github.com/user-attachments/assets/7fbe750b-c166-41cb-949c-b0e39314a8f1)

### Craft CMS version

5.3.4

### PHP version

8.2

### Operating system and version

Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-119-generic x86_64)

### Database type and version

mariadb:10.11

### Installed plugins and versions

- Asset Usage 4.0.0
- CKEditor 4.2.0
- Control Panels CSS 3.0.0
- Control Panel JS 3.0.0
- Pixabay plugin 1.2.0
- Simple Logger 2.0.0

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

Having tables with a `_old` suffix with a number at the end is what’s supposed to happen. 

Once the `craft_old` table exists and a migration to archive the `craft` table is run, that table will be archived as `craft_old1`. This will happen up to `craft_old9`. 

At this point, the maximum table name length (set to 10 in the `archiveTableIfExists` method) will come into play. From that point on, the name of the archived table will be `craf_old10` - the original table name will be truncated so that the name with the suffix doesn’t exceed ten characters. If you were to get to 100, the name would be `cra_old100` and so on.

This is how the new name for the archived table is figured out: https://github.com/craftcms/cms/blob/5.x/src/db/Migration.php#L330-L341.

The `craft__old` table - with the double underscore - could be a result of there being a `craft_` table which was archived.

I hope this helps!
