### ISSUE TITLE
[5.x]: Deleting a user didn't change his status to "active" in users table

### ISSUE THREAD

**Issue by romarickb** [craftcms/cms#15628]
### Description

Is it by design that a user deletion didn't change `active` column value to `false` ?

### Steps to reproduce

1. Create and active a user
2. Delete a user in admin panel

### Expected behavior

`active` column in `users` table value change for `false` as user is not active (he was deleted)

### Actual behavior

`active` column value in `users` table is still `true`

### Craft CMS version

Craft Pro 5.3.5

### PHP version

8.2.22

### Database type and version

PostgreSQL 16.3

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi, thanks for getting in touch! Yes, that’s expected behaviour. When a user is deleted, a `dateDeleted` is set in the `elements` table, but nothing else about the user changes. (That’s assuming you haven’t disabled soft-deletes [in your config](https://craftcms.com/docs/4.x/config/general.html#softdeleteduration)).

If you would like to perform additional actions when a user is being deleted, you can do so via the [events](https://craftcms.com/docs/5.x/extend/events.html#event-code-generator), e.g. `User::EVENT_BEFORE_DELETE` or `User::EVENT_AFTER_DELETE`. 
It’s worth pointing out that users (and elements in general) that have been soft-deleted can also be restored, so if you choose to adjust them during deletion, you might want to think about what should happen if they’re restored.

I hope this helps!

**Comment by romarickb** [comment]
That's totally makes sense. Thanks for detailed answer !
