### ISSUE TITLE
[5.x]: 5.3.6 - Adding a second matrix entry even when locked to maximum 1

### ISSUE THREAD

**Issue by pnpaes** [craftcms/cms#15641]
### What happened?

I create a matrix field with a proper entry type.
I limited that Matrix field to have maximum 1 entry.
I added the matrix field (hero) to my homepage entry.
Entered the homepage and clicked to add a new Hero.
Started to edit but closed the hero editor. Clicked add hero again and a fresh Hero editor opened.
I finlized edititing and saved the hero. it showed up in the home.
but when I refreshed the other one that I started and closed also showed up.

Uploading Screen Recording 2024-09-02 at 2.29.39 PM.mov…

### Craft CMS version

5.3.6

### PHP version

8.3.3

### Operating system and version

Linux 6.6.32-linuxkit

### Database type and version

MariaDB 10.7.8

### Image driver and version

Imagick 3.7.0 (ImageMagick 6.9.11-60)

### Installed plugins and versions

CKEditor	4.2.0
Image Resizer	4.0.1

**Comment by brandonkelly** [comment]
Thanks for reporting this! Technically the nested entry is created as soon as you press “New entry”; it’s just not fully saved (in a way that would let it be shown on the front-end) until you press “Create entry”.

I fixed this for Craft 5.4 by having the field start showing the nested entry as soon as you start editing it, rather than after pressing “Create entry”. So in the above workflow, you could easily go back and continue editing the initial entry, or explicitly delete it if you want to start fresh, without any surprises about going over the field’s Max Entries limit when saving the owner element.

**Comment by brandonkelly** [comment]
Craft 5.4.0 is out with that change.

**Comment by pnpaes** [comment]
Thank you very much for looking into this :)



Best regards,

Paulo Paes
CTO @ Daytwo
+47 40 81 00 11
