### ISSUE TITLE
This is still happening. In my case, I had a **Channel** section that was working properly with Entries fields. I had to change the section to **Structure** due to project requirements and the entries fields started to duplicate the selected entries within the fields. My Craft version is 4.11.5.

### ISSUE THREAD

**Issue by Rodolfoaraki** [craftcms/cms#15677]
This is still happening. In my case, I had a **Channel** section that was working properly with Entries fields. I had to change the section to **Structure** due to project requirements and the entries fields started to duplicate the selected entries within the fields. My Craft version is 4.11.5.

_Originally posted by @Rodolfoaraki in https://github.com/craftcms/cms/issues/7104#issuecomment-2327315409_

**Comment by i-just** [comment]
Hi, thanks for getting in touch.
Any chance you could send your `composer.json`, `composer.lock`, and database backup to support@craftcms.com, so we can try to replicate and dig deeper?

**Comment by Rodolfoaraki** [comment]
Hi, @i-just. Thanks for your answer.

I will send the files attached on the email you've just provided.

Regards.

**Comment by i-just** [comment]
For posterity, this was also caused by duplicate structure data. The section’s entries were referenced by both structures; neither of those structures was soft-deleted, but only one was referenced from the `sections` table. Setting `dateDeleted` in the `structures` table for the structure not linked to from the `sections` table fixes the problem.

We’re not able to replicate the previously used structure not getting soft-deleted.
