### ISSUE TITLE
[5.x]: Multi-instance fields with same handle show in different columns

### ISSUE THREAD

**Issue by shifuma** [craftcms/cms#15799]
### Description
Matrix fields set to view as Element Index show multiple columns of the same field.

### Steps to reproduce

1. Create a Matrix field with two entry types
2. Create a generic plain text field
3. Add the plain text field to each entry type -> Settings > rename the handle to `myTextField`
4. Add `myTextField` columns to index (there will be two of them)

### Expected behavior
If a field has the same handle, the content will show in that column, even if it has been overwritten

### Actual behavior
Fields with the same handle show in different columns because the handle has been changed

![screenshot_2024_09_27 _12 57](https://github.com/user-attachments/assets/48ccc86a-bf05-4c7b-87ad-1a3aef42c199)

![screenshot_2024_09_27 _12 56](https://github.com/user-attachments/assets/1606aad5-70cc-4e8f-b326-9d926f3b9567)

### Craft CMS version

5.4.5

### Installed plugins and versions

-

**Comment by brandonkelly** [comment]
This is working as expected. Craft will only consolidate custom field columns across multiple entry types if their handle hasn’t been overridden. Otherwise the field will be identified by its field instance UUID, which is going to be unique for each entry type.

https://github.com/craftcms/cms/blob/d44a2d4628b02db2290ecff4248ba70f664c070d/src/services/ElementSources.php#L435-L444

If you’d like each of these fields to share the same column, remove their overridden handles. If that’s not possible because the same field already exists in the layout with the default handle, you can create a new custom field to hold that data instead. You can then migrate the existing field values over to the new field using this command:

```sh
php craft resave/entries \
  --field <matrixFieldHandle> \
  --type <entryTypeHandle> \
  --set <newTextFieldHandle> \
  --to <oldTextFieldHandle>
```
