### ISSUE TITLE
[5.x]: Entry ID's changing upon saving matrix field

### ISSUE THREAD

**Issue by iwingate-digistorm** [craftcms/cms#15874]
### Description

When adding two or more entries to a matrix field, the entry IDs and UIDs change upon saving the matrix. This only happens once after saving a matrix with newly added entries.

### Steps to reproduce

1. Create a matrix field (card view mode, I haven't tested others).
2. Add two or more entries to the matrix and take note of their IDs.
3. Save the matrix.
4. Check the entries in the matrix; their IDs and UIDs will have changed.

### Expected behavior

The entry IDs and UIDs should remain consistent after saving the matrix.

### Actual behavior

The entry IDs and UIDs change after saving the matrix.

### Craft CMS version

5.4.4

### PHP version

8.3

**Comment by i-just** [comment]
Hi, thanks for getting in touch!

This is expected behaviour. When you create a new nested entry for an existing owner, that nested entry first belongs only to the provisional draft of the owner. When the owner is saved, the nested entry is duplicated and assigned to the canonical version of the owner - hence the change of ID and UID. For a matrix field, this happens for all the view modes (cards, element index and inline-editable blocks). (It’s also the case for the matrix field in Craft 4.)

I hope this helps!
