### ISSUE TITLE
Error locating message source for uninstalled plugin

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1626]
### Description

Uninstalling a plugin of which you had widgets added to the dashboard, causes the dashboard page to throw an error:

> Internal Server Error
> Unable to locate message source for category 'myplugin'.

### Steps to reproduce

0. Install plugin.
1. Add plugin’s widget to the dashboard.
2. Uninstall plugin.
3. Visit dashboard.

### Additional info

- Craft version: 3.0.0-beta.10
- PHP version: 7.0.15
- Database driver & version: MySQL / MariaDB 10.1.21
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
@carlcs Can you provide a plugin that illustrates this issue? (Either its public repo URL or you can send into support@craftcms.com)

**Comment by carlcs** [comment]
Sure, just sent you a mail.

**Comment by carlcs** [comment]
@brandonkelly I just found out that the issue only occurs when the plugin was installed using composer. I have not tested it with a public repo though, only with the custom "path" repositories source set up for the plugin in my composer.json.

**Comment by carlcs** [comment]
Here is another way to reproduce:

1. Run `composer install me/myplugin`.
2. Visit dashboard (without installing the plugin).

**Comment by brandonkelly** [comment]
Ahh, great, thanks for the added info.

**Comment by brandonkelly** [comment]
Here’s the issue: if a plugin is installed via Composer, it’s classes will be auto-loadable regardless of whether the plugin is “installed” in Craft or not. If you have a Dashboard widget that uses a widget type defined by a plugin, and then you disable/uninstall the plugin, then Craft will still be able to load its widget classes, however there will likely be various errors due to the plugin itself never getting instantiated for the request. This could just as easily have been an error about calling a property on a non-object because `Plugin::getInstance()` returned `null`, or other issues. It’s also not limited to Dashboard widgets; it could have been a field type, asset volume type, mailer adapter, etc.

We talked a bit about it and couldn’t think of any elegant solutions. As long as Composer is the one auto-loading the plugin’s classes, the plugin is always “installed” in some form, regardless of what Craft thinks.

The best we could come up with is, we decided to remove the “Disable” button for Composer-installed plugins, since it’s misleading and could lead to errors like the one above, and plugin developers just need to make sure they are cleaning up after themselves on uninstall, either from an [install migration](https://github.com/craftcms/docs/blob/master/en/plugin-migrations.md#install-migrations), or the plugin’s `uninstall()` method. In this case, that means deleting any user widgets of the plugin’s supplied widget type(s).
