### ISSUE TITLE
Make URL-Enabled Section information available to SaveFieldLayout event

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#1654]
### Overview of Problem

We have a plugin (Sprout SEO) that adds behavior for all Element Types with URLs. While Elements with URLs are similar in many ways, there is currently a lot different about how they are implemented and how we need to watch each type of URL-Enabled Element to know what's going on and act on it. To address this, our plugin has an integration for URL-Enabled Section Types.

By our own definition, a URL-Enabled Section Type is the thing that defines where the URLs are managed for a particular Element. For Entries this is a Section, for Categories this is a Category Group, and for Craft Commerce Products, this is a Product Type.

Because we generate metadata based on certain settings in our Metadata Field Type we need to be aware when someone changes settings in that field type and dynamically update any entries that may use that field. We currently do this by watching the `fields.onSaveFieldLayout` Event and triggering a ResaveElements task for relevant Elements when a related Field Layout is modified.

This works, but not all of the information we need is available during the fields.onSaveFieldLayout Event. Specifically, we need ID of the URL-Enabled Element. Again, that could be a Section, Category Group, Product Type (or Custom Element group of some sort). We can currently grab this data from the URL, but it's in different places for each Field Layout (Sections and Category Groups have it as the third segment where Product Types use the fourth for the ID). In any case, that's not a very good solution as it also breaks if anybody triggers this method from the command line and no request is present.

### Feature Request

Standardize how the entity that is used as the URL-Enabled Section Type is identified within Craft and make available information about that specific URL-Enabled Section Type to the fields.onSaveFieldLayout event.

Please ask me for clarification if necessary. I understand that this is not an easy thing to clearly write out in words. 

To see all the things we are normalizing across URL-Enabled Section Types you can [request a demo copy](https://sprout.barrelstrengthdesign.com/craft-plugins/request/trial) of Sprout SEO and take a look at the `SproutSeoBaseUrlEnabledSectionType` Class and the three supported integrations in `integrations/sproutseo/sectiontypes`. It would be nice to see all of the things supported in that class more standardized across element types in the long run, where possible.

**Comment by brandonkelly** [comment]
This would involve passing additional information to `Fields::saveLayout()` that the method has zero need for, so it’s not going to happen.

Even if we did though, using field layout events is the wrong approach in the first place, for two reasons:

1. Custom fields and URLs are two independent features of element types; there could be an element type with one but not the other. So if an element type has fields but not URLs, you’re wasting cycles trying to record the URL format on save, and if an element type has URLs but not fields, you’re never going to find out about it.

2. Even if an element type does support both, nothing says it has to update both things at the same time. Illustrated by the element type you probably care most about: _entries_. Entry URL formats are indeed defined by their section, but their field layouts are saved on the section’s entry types. If someone changes the URL format, you won’t find out about it until some later point if/when they happen to resave the entry type(s). The only time a section’s URL format and field layout are saved at the same time is when the section is first created.

The cold, hard truth is that there is no single event that could cover when URL formats change, because it’s not a central concept of Craft in the first place. The only place Craft’s core APIs care about them is when saving an element, and it’s up to the element class to choose how it wants to define it. There is no architectural reason why entries, categories, and products each have relatively similar ways of setting URL formats; it’s just consistency for consistency’s sake.

So that said, if you do want to have some central, abstracted way of finding out what a URL format changes, you will need to create that abstraction yourself, and add support for new element types as they come about.

**Comment by BenParizek** [comment]
We'll look into alternatives here.

I wish there was another angle to consider this topic. Perhaps field layouts aren't the right approach, but a URL is a core concept to Content on the internet. Content does not exist without a URL on the internet. And Content doesn't exist without metadata that is related to that URL. 

Currently, Craft embraces the concept of Content's flexibility across Element Types but we're doing a lot of extra work to try to determine how to know when core information about that content (such as the URL and all the metadata that relates to that URL) changes. It feels like something is missing there, and while we can deal with it in a messy abstraction layer, it feels like a problem that relates to the core concept of Content on the internet to me.

**Comment by brandonkelly** [comment]
Agree Craft could do better here when it comes to URLs/information architecture. Check out #1662 - seems like that would be a big stepping stone to getting where you want.
