### ISSUE TITLE
Unable to click breadcrumb links whilst notification is in an active state

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#1675]
### Description

I've noticed that breadcrumbs aren't clickable while there is an active notification, I presume this is due to the notification overlaying the breadcrumbs during it's active state.

![image](https://cloud.githubusercontent.com/assets/24975058/25488077/fc4e6fa6-2b5d-11e7-9ab0-ace060eba344.png)

### Steps to reproduce

1. Save something (an entry type in this case)
2. Attempt to click a breadcrumb link

### Additional info

- Craft version: 2.6.2974

**Comment by cavellblood** [comment]
I've seen this too. I think it's been like this since 2.5 was released. Anyway, for whoever is able to make this change to the CP CSS I was able to fix that behavior with the following CSS:

```
#notifications-wrapper {
    pointer-events: none;
}

#notifications .notification {
    pointer-events: auto;
}
```
This still allows the text in the notification to be selected if that were important. If not then just the first rule would fix it.

**Comment by brandonkelly** [comment]
Fixed for the next release. Thanks!
