### ISSUE TITLE
Backend shortcuts for developers

### ISSUE THREAD

**Issue by mendiomon** [craftcms/cms#1726]
While working on site with craft cms i found myself constantly switching between specific entry page, fields list and section page. These fragments of backend are barely conncted witch each other in terms of user interface. In development mode we should have:

- Link to field settings next to each field on entry page
- Link to selected section settings on entry page
- Link to fields settings next to each field on section page
- .. and so on.

That woudl saved me some time, especially when application grows and there are many fields and sections to browse trough.

Additionally, there shoudl be field/entry/global handles displayed on entry pages as well,

**Comment by steveooo9** [comment]
@mendiomon Yeah, this is a great idea. Maybe we should brainstorm and create a list of some good shortcuts that primarily helps with the building/developing workflow with Craft for us developers.

A small feature, but still sooo great: CMD+S for saving an entry. I only use this shortcut because it's so well known (you don't have to learn a new shortcut) and it's so often used.

@brandonkelly For such features, it would be great if there is some idea collection platform to create a curated list of shortcuts we developers use often. This system is some kind of voting system to create a hierachy of importance ("+1"-like voting option). So we could brainstorm in a bigger way and at the end, we have a great list of shortcuts which can be implemented from most-requested to least.

**Comment by steveooo9** [comment]
A common shortcut that would be great is a shortcut to delete all Caches. This would be so helpful because in v2 you had to click 3 times to clean it (1. settings, 2. clean cache, 3. "clean" button). In v3 I think you even have to click more -.-

**Comment by brandonkelly** [comment]
I think a command palette (like [A&M Command](https://github.com/am-impact/amcommand)) makes more sense for these sorts of things than a bunch of complex keyboard shortcuts that no one will remember.
