### ISSUE TITLE
FR: Provide exception hooks or events

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#1738]
Craft 2 provided `craft()->onException` and `craft()->onError`, making it possible for plugins like [Craft-Bugsnag](https://github.com/sjelfull/Craft-Bugsnag) to react to exceptions. It was easy to extend [Craft 3's ErrorHandler via component to do the exact same thing](https://github.com/workingconcept/bugsnag-craft3), but my understanding with Yii2 is that you can only designate one component as the error handler. So if another plugin wanted to register its own exception handler, say for tracking 404's, the two would either need to work together very carefully (and create a fragile exception handling landscape) or clash.

Nobody wants me extending Craft classes, and my Bugsnag utility only needs to know about an exception and fire it off someplace else. There's no reason it _needs_ to be a module or touch the ErrorHandler class.

I couldn't find an exception event or `craft()->onException`/`craft()->onError` equivalent, but it seems like it'd be ideal to raise an exception event that plugins could subscribe to without fighting to be Mr. Manager.

**Comment by khalwat** [comment]
This would be really useful, IMO... because I need to do the same thing to catch 404 exceptions, which means that I replace the errorhandler too, in order to do so. Which means that only one of us can "win".

It seems like the Craft `\craft\web\ErrorHandler` should raise events that plugins can listen to and potentially handle, rather than resorting to sub-classing the `\craft\web\ErrorHandler` and stomping on each other when doing so.
