### ISSUE TITLE
Option to delete content when removing a field from a field layout

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#1772]
Currently when removing a field from a field layout, the content remains in the db. It would be nice if you were asked whether you want to keep or delete the data.

**Comment by dennisfrank** [comment]
I had this issue today (Craft 2):

After removing a Matrix field from an entry type the previously saved data from this field was still connected to the entry. The content is still there for entry types that no longer have the field.

The Matrix field is connected to a bunch of other entry types and I checked if the field is defined and not empty with a very global condition. I had to write a very specific condition to manage this exception because I couldn’t get the data deleted from the DB.

**Comment by brandonkelly** [comment]
This behavior will change when we implement #1524
