### ISSUE TITLE
Users site edit permission not reflected on entries screen

### ISSUE THREAD

**Issue by justjoolz** [craftcms/cms#1778]
## Problem 

A user can see entries that are status:disabled for sites they don’t have permission to edit.

## Solution 

Hide them :)

Or create granular user permissions similar to editing other authors entries:

- Edit other sites entries
  - Publish live changes for other sites entries
  - Delete other sites entries
- Edit other sites drafts
  - Publish other sites drafts
  - Delete other sites’ drafts

### Additional info

- Craft version: 3.0.0-beta.19

**Comment by brandonkelly** [comment]
What version of Craft are you on?

**Comment by justjoolz** [comment]
3.0.0-beta.19

**Comment by brandonkelly** [comment]
This is working as intended for me. The only entries that I can see when logged in as a user w/ access to a single site is the entries in sections enabled for that site.

> A user can see entries that are status:disabled for sites they don’t have permission to edit.

Maybe your expected behavior is just not aligned with the intended behavior here. Even if an entry is disabled for a site, it should still show up for that site, as a disabled entry.

**Comment by brandonkelly** [comment]
Here’s a Stack Exchange Q&A that shows how to hide entries that aren't enabled for the current site: https://craftcms.stackexchange.com/a/19904/9 (relies on the CP JS plugin, which hasn't been ported to Craft 3 yet, though.)
