### ISSUE TITLE
Field Groups - Make "default" the first entry in the dropdown

### ISSUE THREAD

**Issue by sam327** [craftcms/cms#1785]
The "Group" dropdown menu on new fields is sorted alphabetically. So if you have multiple groups, and one of those starts with a letter before "D" the group, it'll put that item first. 

<img width="287" alt="screen shot 2017-06-21 at 1 00 10 pm" src="https://user-images.githubusercontent.com/1746360/27396624-950b6a5c-5681-11e7-99a0-e62698b7a0ee.png">

Instead, Default should always be first. 

This is minor, and kind of stupid, but I just created 15 fields and put them all in the wrong group, because I wasn't paying attention. But it also seems like it might be something that's reasonably easy to update.

### Steps to reproduce

1. Create a group called "Banner"
2. Create a new field
3. The "Group" dropdown defaults to Banner instead of Default.

### Additional info

- Craft version: 2.6.2983
- PHP version: 5.6

**Comment by brandonkelly** [comment]
There’s nothing special about “Default” – that’s just a group name like all others, and can be renamed/removed. I don’t think it warrants any special treatment.

**Comment by sam327** [comment]
Sure there is. It's a word that has a particular meaning.

> **Default**: a preselected option adopted by a computer program or other mechanism when no alternative is specified by the user or programmer.

Now my 'default' is the banners group. And I don't want that. I want my default to be "Default."

I make 50 fields for various things; I shuffle some of them in 'banners,' some into 'product fields,' and others into 'customer field' - and anything uncategorized else _goes in default_.

I mean, I can create a group called _AAAAAAA_ - but I like using the word "default" because it's clear what that name means.

**Comment by brandonkelly** [comment]
But there’s no such thing as a “default field group”. Fields always belong to a single group, so the whole idea of naming a field group “Default” is a misnomer. (I realize that Craft does literally create a “Default” field group for you on install, but that is just because there’s no obvious name for it, since the installer doesn’t know anything about the site you’re about to build.)

Maybe it would make sense to let you choose which field group should be selected _by default_ (in which case, if you really wanted to keep a group named “Default” you could make that your selection), but that’s a slightly different request.

**Comment by sam327** [comment]
Well, the initial setup of the 'default' group gives me the expectation that it's "default" - so I anticipate it working in a particular way. Sure, that might be an incorrect assumption, but it's very leading.

At any rate, your suggestion of having a 'set a default group' option is a better fleshed out idea. But I'd then expect it to set that initially-configured-group "default" as the default... which gives me the same end result.

Sorry to be pedantic about this.
