### ISSUE TITLE
Event EVENT_AFTER_SAVE_ELEMENT return matrix object

### ISSUE THREAD

**Issue by eolitich** [craftcms/cms#1807]
### Description
When I subscribe to the EVENT_AFTER_SAVE_ELEMENT event, I expect to receive when I call 
` $event->element`  `craft\elements\Entry` object, `craft\elements\MatrixBlock` object is received, that is how it should be ?, When subscribing to EVENT_BEFORE_SAVE_ELEMENT `$event->elemen`t returns the `craft\elements\Entry` object.

This happens when I use matrix blocks

### Steps to reproduce
`Event::on(Elements::class, Elements::EVENT_AFTER_SAVE_ELEMENT, [$object, 'save']);`

### Additional info

- Craft version: 3.0.0-beta.19
- PHP version: 7.1.6
- Database driver & version: n/a
- Plugins & versions: n/a

**Comment by andris-sevcenko** [comment]
Since entries and matrix blocks are both elements, this does not seem like a bug to me.

When you are saving an entry, `EVENT_BEFORE_SAVE_ELEMENT` will be called. After that, the same event should be called on all matrix blocks the entry has, and then you would get the reverse - as matrix blocks are being saved before entry is being saved, you would get `EVENT_AFTER_SAVE_ELEMENT` for matrix blocks first and then, finally, for the entry.

The solution here is just to check for what type of element you're getting.

**Comment by brandonkelly** [comment]
You can specifically listen for entries like this:

```php
use craft\elements\Entry;
use craft\events\ModelEvent;
use yii\base\Event;

Event::on(Entry::EVENT_BEFORE_SAVE, function(ModelEvent $event) {
    /** @var Entry $entry */
    $entry = $event->sender;

    // ...
});
```

**Comment by eolitich** [comment]
I did so already
