### ISSUE TITLE
CKEditor instead of Redactor II

### ISSUE THREAD

**Issue by thaoms** [craftcms/cms#1811]
I noticed that Redactor just doesn't do the trick for our clients, it is just too lightweight.
Simply put, if you need more than just some simple paragraphs it is pretty useless.

I get it that you chose a lightweight editor, but even the features it has are not even that good or often act buggy.

I would recommend CKEditor. We have been using this one in EE before, it is just more reliable and mature.

It would be awesome if this got replaced or at least got a (third-party) plugin.

**Comment by brandonkelly** [comment]
We used to make a CKEditor-powered editor for ExpressionEngine. It's a beast, but agree that it's super solid. We’ve been keeping an eye on v5’s progress, which is a complete rewrite and looks like a major improvement, but we don’t want to invest time into implementing it until it's stable and the docs are written (nor do we want to waste time dealing with v4 at this point).

**Comment by steveooo9** [comment]
@brandonkelly Well. I have to agree with @thaoms that for us as an agency, probably one of the biggest weak points of Craft is Redactor. On previous CMSs we used, there was CKEditor which was a bloat in the early days, but still was stable enough.

Do you really think this upgrade from v4 to v5 is a big of a deal? It would be great if someone could talk with the CKEditor guys if there is a clean upgrade path, because the problems are:
1. You have to wait a long time until v5 releases
2. v5 is a complete rewrite so possibly more buggier in the first months than v4

So if the upgrade path from v4 to v5 isn't that deep, I really would think that nothing is against implementing v4 of CKEditor for Craft now.

What do you think?

**Comment by brandonkelly** [comment]
@steveooo9 For most sites I imagine the upgrade path will be quite simple, but it won’t be for Craft since we need to replicate all of the integration features we did for Redactor (linking to assets/entries/categories, etc.), which will require custom plugins. That’s a road we don’t want to go down with CKE v4 again, but from the looks of it, will be easier to do in v5.

Nothing’s stopping a 3rd party from building a more lightweight CKE integration in the meantime, if it’s really such a huge pain point.

**Comment by steveooo9** [comment]
@brandonkelly Okay. Good to know. Well, if some feature is requested by a lot of people, then you can create a plugin, which is good. But this could also mean that it should be integrated into core :)

Neo plugin is great, but a lot of features could easily be something you provide as some core feature. Do it like Apple with f.lux: Steal an idea from the community and integrate it as core :)

**Comment by brandonkelly** [comment]
We do that when it makes sense.

**Comment by thaoms** [comment]
That makes sense, thank you!

For now you can use TinyMCE editor
https://github.com/benjamminf/craft-tinymce

I reached out to the developer in an issue but he is currently not maintaining it anymore, but for now it is stable.

If someone has the knowledge and time to maintain it, that would be cool.

**Comment by theskyfloor** [comment]
I am just going to second this request. I am pretty sure my views on it are well known. It really is a pain point and not just for me personally but for multiple clients I have on Craft. Some of them have even told me they are looking at other platforms because of the way the text editor is so often confounding to them on Craft. They don't know what Redactor is... to them it is Craft that is buggy and unreliable... which in turn reflects badly on us for picking it.

**Comment by brandonkelly** [comment]
Hang tight.

**Comment by brandonkelly** [comment]
Earlier this week we [announced](https://craftcms.com/news/dot-all-2017-announcements) that we’re launching a CKEditor plugin alongside Craft 3 RC1. You can even see its progress here: https://github.com/craftcms/ckeditor
