### ISSUE TITLE
EVENT_AFTER_MOVE_ELEMENT gives old $event->el

### ISSUE THREAD

**Issue by phoob** [craftcms/cms#1828]
### Description
As discussed here: https://craftcms.slack.com/archives/C04C5JSBZ/p1499499421944860

When using named event, I get the old URI when using the $event->element in the callback function. I also tried "finding" the new element,  but even then I get the old URI... shouldn't it be possible to retrieve the updated structure/URI in this event?

### Steps to reproduce

        // TODO: not working yet. The old uri is indexed, not the new one
        Event::on(
            Structures::className(),
            Structures::EVENT_AFTER_MOVE_ELEMENT,
            function (MoveElementEvent $event) {
                if ( $event->element instanceof craft\elements\Entry ) {
                    $doc = ElasticDocument::withEntry( $event->element );
                    return $this->elasticraftService->indexDocument($doc);
                }
            }
        );

### Additional info
- Craft version: 3
- PHP version: 7
- Database driver & version: innodb
- Plugins & versions: element-api

**Comment by brandonkelly** [comment]
Updating the entry and its descendants’ URIs can take a while depending on how many descendants it has, and how many sites they’re all enabled for, so that process actually happens in a background task, after the initial move request is completed.

To work around that, I just added a couple new events for the next release (6865bd6699c3daf8915bbab1fc1bbc6cbaa62e6c). You could listen to the `afterUpdateSlugAndUri` event instead of `afterMoveElement`, at which point you can be confident that the URI has been updated. (One caveat: this event will get called once for each site, if you have a multi-site install.)

**Comment by phoob** [comment]
Thanks, @brandonkelly !
