### ISSUE TITLE
Replace tasks with Yii2 Queue Extension

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#1910]
Craft's current background task implementation sucks, because tasks/jobs run as web requests, making them susceptible to stingy memory and timeout restrictions, and incapable of recovering from fatal errors.

We should swap it with the [Yii 2 Queue Extension](https://github.com/yiisoft/yii2-queue/), which is much more robust. It should still be possible to run tasks via web requests for servers that can’t set up the daemon/don’t have `proc_open` available.

**Comment by narration-sd** [comment]
Quite glad to hear about this, Brandon. The yii2-queue thing ought to be about optimum for it, as you can choose from the variety of back-ends according to what may be favored or needed.

I suspect it's going to want to be a plugin or equivalently optional add-on module, as it appears to depend on having `supervisord` running to manage worker/s even with the DB driver, unless I've missed something. Supervisor has to be installed on the *nix box, indeed so there's a process monitor, which would let out shared hosting.

And Windows servers? There's a hairy sounding suggestion it could run under Cygwin, and rougher apparent bones of python clones.  Brad's background might gin a Windows service here, if wanting to.

But a great move, to make this, so that people with loads or reliability issues can 'get there'.  Cheers.

**Comment by takobell** [comment]
@narration-sd on Windows, I think you'd ditch `supervisord` completely and just create a custom service  https://support.microsoft.com/en-us/help/137890/how-to-create-a-user-defined-service

**Comment by narration-sd** [comment]
yeah, I ran across that, in fact led to tiptoeing in your direction...Sir Tako...:)

**Comment by narration-sd** [comment]
Remarkable amount of good things you guys have in this commit -- Great.

As can, I'lll reorganize the 3.0 version of my Standards Agent to use  the queue; not right away today. Glad I already ported other improvements in it to 2.0....

Anticipating installation of Linux supervisord for it,  yes?

The idea for a node substitute looks actually might be doable -- but probably wouldn't solve the problem for shared hosting, as it would killed on cycles used if not time. Though also imagine a self-renewing version??

Just glad I didn't put  the work into fully pursuing all the threads in code, since you guys now handle it.

**Comment by brandonkelly** [comment]
@narration-sd It’s possible to supervisor the `queue/listen` action, yes.

**Comment by 23d1** [comment]
Sorry to dig up an old issue/feature.

Currently running into proc_open/proc_close being disabled with a hosting partner (among other PHP functions).

Is there any way around this that still backs up the DB? Craft 2 worked flawlessly.

**Comment by angrybrad** [comment]
@23d1 I think you commented on the wrong issue (this is about queues and tasks), but the PHP proc_* methods are required for certain features of Craft to work properly.  

https://docs.craftcms.com/v3/requirements.html#optional-php-methods-and-configurations

If you're unable to backup because of proc errors, you'd need to set https://docs.craftcms.com/v3/config/config-settings.html#backupcommand to your own custom backup command (shell script, external request, etc.)
