### ISSUE TITLE
Content for multisite are not saving specifically for their selected site

### ISSUE THREAD

**Issue by hlldo** [craftcms/cms#1964]
### Description

I had two sites created. But whenever I save the content for one site, the content is also saved for the other site. So the content is not site specific. 

### Steps to reproduce

1. Create two sites 
2. Create a homepage and allow both sites to access the template
3. Create a body field that just have a plain text
4. Add the body field to the homepage section
5. Change the entry for site 1 and save
6. However, the change also saved for site 2 automatically.

### Additional info

- Craft version: Craft 3 Beta
- PHP version: 7.1.8
- Database driver & version:
- Plugins & versions:
#

**Comment by narration-sd** [comment]
@hildo -- it  sounds  like you may not have set the fields that transferred to be translatable.

You have to do this individually on each field of  interest -- which allows not translating fields you don't wish to.

On Craft 3, there's a drop-down menu for this on the Field definition -- Translation method, just below Field Type, and it has settings for however you'd like to do it.

**Comment by hlldo** [comment]
Hi, 
  Sorry, my mistake, the text field works but it was the Matrix field type assets that doesn't work. I made sure that the Translation method is set at "Translate for each site".

**Comment by narration-sd** [comment]
Well, this is a little confusing. If you really mean Assets, they don't have a 'Translate for each site'.

The situation there is anyway a little more complicated, and I think we have to call @andris-sevcenko in from Craft Development Latvia Division to clarify some preent semantics.

However, i was able to guess and get this to work, as it had before I think some beta changes.

I'm looking at a Sites test site I have, and switching between sites in an Entry shows both a standlone Asset and an Asset in a Matrix picking up appropriate and differing images as i've set them.

The key to this, for Assets whether they are on their own or within a Matrix, appears in the area hidden at  first by the label 'Advanced', at the bottom of the Field definiition.

If you open this, and check the box 'Manage relations on a per-site basis', you will get the behaviour I've described -- once you go through and set the Asset to something appropriate for each Site listed in an entry. You'll need to save (dropdown Save and continue editing, or simply Cntl-S) before moving from one site to another for the field.

Now, as far as Andris's oversight, the functional descriptions in this area don;t make a great deal of sense for a Craft developer, though maybe while programming for them. 'His English is always excellent; this is just a matter of expression in context. Maybe I would suggest something like the following -- and changing the order as shown, so that the 'multisite assets' question is presented and resolved first::

- 'Options when Sites are used', instead of 'Advanced'
- 'Allow using different Assets according to Site' instead of 'Manage relations on a per-site basis'
- 'Use assets only from a single site' instead of 'Relate assets from a specific site'
= the question that unrolls when you check this show also follow as 'Which site should Assets be use from?'

You can see my thought that the meaning of'relate' is entirely vague for use, if not in database terms. The 'allow' hints that unless you actually save differing assets, the initial asset defined will be at first copied across -- trying not to think about trickiness on that point, and imagining Andris has.

The last option as I've made it really needs some further notes, that it has to do with Volumes defined according to Site; usually not the 'main' volume, but just for those image which need to differ. A complicated subject, so deserves its own circle-question-mark Help link, would imagine.

Hope this gets you on your road, @hildo, and that the byplay with Andris may help concepts at least for later. For your case, I think it's just setting that one checkmark which will get what you ask. Salud -- and if i've got it this time....

**Comment by hlldo** [comment]
Thank you so much for your help @narration-sd. I clicked on the checkbox for the "Manage relations on a per-site basis" and that allowed each of my sites to have its own specific image.
 
However, I found that this method is very confusing because when you first make the assets field inside the matrix field, there isn't an option for "Translate for each site". But if you go back into the matrix field and click on the assets field, you see a drop down for "Translate for each site". This only seem to apply to assets within the matrix field. Assets field by itself does not have this option as you have mentioned.

**Comment by narration-sd** [comment]
Well, you are correct -- that 'Translate for each site' does show up on re-opening the Matrix field definition. This makes little sense (what would translating an image mean), so it's pretty clearly a bug.

As far as the different handling of images/Assets, I think that does make sense, for the same reason. We don't translate images, but we can choose different images per Site. Sites may not even involve  language differences, though they may; this is the advancement of ability in Craft 3, used for different market classifications on a business site, say.

Anyway, some good things for Andris to look at,, and so he'll want to deal with and close this when done.

I'm glad you can proceed, @hlldo, a smiile, and you are most welcome.

**Comment by brandonkelly** [comment]
Matrix & Assets fields should not have a Translation Mode setting as they aren’t translatable in the Craft sense of the word. (If you are seeing a Translation Mode setting for either of those field types, that’s a bug and please report it in a new issue.)

Instead, Matrix fields have a “Manage blocks on a per-site basis” setting, and Assets fields have a “Relate assets from a specific site?” setting (tucked away under “Advanced”). They will be available right when creating the field (assuming the Craft install is already set up with multiple sites) as well as later on.

**Comment by narration-sd** [comment]
Brandon, @hlldo (and I) did find the Translation Mode setting appearing -- on the second access to a newly created Matrix Assets field -- as noted above.

I noted @andris-sevcenko on this, but  if you want a second issue, will create. Do you?

**Comment by brandonkelly** [comment]
@narration-sd Ah yes, able to reproduce. I’ll create an issue for it.

**Comment by narration-sd** [comment]
Ok, thanks much-- was about to :)

**Comment by narration-sd** [comment]
...I'll do another for the wording, which is hyper-non-understandable, about 'relate'??? assets etc...

**Comment by brandonkelly** [comment]
@narration-sd The bug isn’t specific to Assets fields. “Relational” is still not quite accurate (applies to any fields that only offer a single translation method) but all of the built-in examples are relational. Anyway, fixed now.

**Comment by narration-sd** [comment]
Let me upgrade again, see what you have, as this last is about language only.

Great on the instant fix for bug -- @hildo should see this on next beta, or if using dev-develop, on composer update - magic :)
