### ISSUE TITLE
Add woff2 to accepted mimetypes

### ISSUE THREAD

**Issue by sjadema** [craftcms/cms#1966]
### Description
I'm routing assets through a controller. In `craft/app/helpers/HeaderHelper.php:70`, Yii's internal mimetypes file is used. This file is missing the mimetype for the `woff2` extension. Therefore i'm getting the wrong response headers and the font won't show.

### Steps to reproduce

1. Make a call to `\Craft\HeaderHelper::setContentTypeByExtension('woff2')`
2. Inspect the response headers

### Additional info

- Craft version: 2.6.2989
- PHP version: 7.1.9
- Database driver & version: MySQL 5.7.19
- Plugins & versions:

**Comment by narration-sd** [comment]
It looks like Yii are two years out of date themselves on this, maybe because there doesn't seem to have been any firm definition for a woff2 mimetype.

I would imagine the solution Craft might take, avoiding other issues, is to add a line to their distribution of framework/utils/mimetypes.php, and you could do that yourself, at least in the meantime.

`	'woff2'=>'application/font-woff2',
`

looks like it should work, type taken from [here](https://stackoverflow.com/questions/28235550/proper-mime-type-for-woff2-fonts), which turns up at top of  Google, in spite of 2015 date.

This is messy, but seems it should be stable over Craft updates -- until they themselves change this file. By the way, the situation isn't any better on Yii 2 -- hard to imagine why the designers don't add a patch-in-extras ability for a local added-mimetypes file. As the world does not stand still...

**Comment by sjadema** [comment]
Yeah, already did that. That file won't change anytime soon anyways. Too bad Yii 2 doesn't support this out-of-the-box :s The developers could always merge that file with their own ofcourse.

**Comment by takobell** [comment]
@narration-sd best I can tell from that SO link is that the `application/font-woff2` header is legacy and `font/woff2` is the standardize new one? https://www.w3.org/TR/WOFF2/#IMT

**Comment by takobell** [comment]
Although they're using `'application/font-woff'` for `woff`, so maybe that's good enough. https://github.com/yiisoft/yii/blob/master/framework/utils/mimeTypes.php#L908

**Comment by narration-sd** [comment]
Brad, no doubt you're right about the planned header; didn't look as far. I do note this spec is a 'recommendation' ...from a year and half ago.... W3C hmm.

Ah, but apparently this was an IANA/W3C squabble, or part of one.  Looking a little deeper yet, I found [https://stackoverflow.com/questions/2871655/proper-mime-type-for-fonts/43321601#43321601](https://stackoverflow.com/questions/2871655/proper-mime-type-for-fonts/43321601#43321601), with references where it appears  font/woff2 is indeed the way to go.  

Copy @sjadema

**Comment by takobell** [comment]
Fixed this for the next Craft 2 release.

**Comment by sjadema** [comment]
Cheers guys!
