### ISSUE TITLE
UrlHelper::actionUrl() -> unable to create link to front end action when in admin

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#1974]
It seems the UrlHelper::actionUrl() detects if the user is in the admin or not and generates an action url accordingly.  However, I would like to create a front end action url (to display via the admin) but am unable to.

Does it make sense to create a couple new methods called `siteActionUrl` and `cpActionUrl` which would allow explicit creation.

Also, why do action requests always show the script name?

**Comment by brandonkelly** [comment]
It’s just a shortcut method, and most of the time it makes sense for it to return a URL based on the current context, so not sure I want to split it into two different methods. If we did, we’d probably need to do the same for `resourceUrl()`. That said we do have `cpUrl()` and `siteUrl()` so maybe there's some precedence. Idk.

There’s at least two examples in the CP where we couldn't use it due to this issue – `craft\services\Users::getEmailVerifyUrl()` and `getPasswordResetUrl()`. In those cases we just manually construct the URL:

```php
if ($user->can('accessCp')) {
    // Only use getCpUrl() if the base CP URL has been explicitly set,
    // so UrlHelper won't use HTTP_HOST
    if ($generalConfig->baseCpUrl) {
        return UrlHelper::cpUrl($path, $params, $protocol);
    }

    $path = $generalConfig->cpTrigger.'/'.$path;
}

// todo: should we factor in the user's preferred language (as we did in v2)?
$siteId = Craft::$app->getSites()->getPrimarySite()->id;
return UrlHelper::siteUrl($path, $params, $protocol, $siteId);
```

> Also, why do action requests always show the script name?

Because most of the time these URLs are used for POST requests over Ajax. Having the script name in there helps ensure that the POST data won’t get lost by an index.php redirect on the server, and the fact that they are generally sent over Ajax means we don’t care as much about whether the URL looks pretty or not in the first place.

**Comment by nateiler** [comment]
My suggestion is to add two methods in addition to keeping the current `actionUrl()`.  The current `actionUrl()` would function as it does today, automagically serving the action link based on being in the admin or not.

**Comment by brandonkelly** [comment]
Yeah I’m not totally opposed to it. Feel free to submit a FR as a new issue (this one feels more like a question/bug report, but the current behavior is in fact intentional, even if not desired).
