### ISSUE TITLE
'looks like someone already updating' bug is still in there

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#1990]
### Description
I failed a latest test of updating Craft 3 from the Updates page, for a reason I don't reckon by the message, 'The .git directory is missing from /home/vagrant/dpprime_html/vendor/craftcms/cms'. Separate problem.

After this, the craft_info.maintenance bit wasn't reset, and so future attempts blocked.

### Steps to reproduce

1. As above
2.

### Additional info

PHP version	7.1.3-3+deb.sury.org~xenial+1
Database driver & version	MySQL 5.7.17-0ubuntu0.16.04.1
Image driver & version	Imagick 3.4.3RC2, ImageMagick 6.8.9-9
Craft edition & version	Craft Pro 3.0.0-beta.26
Yii version	2.0.12
Twig version	2.3.2
Guzzle version	6.2.1
Imagine version	0.7-dev
Plugins

Bactrian	1.0.0
Trimmer	1.0.0
Video Embed	3.0.0
Element API	2.4.2
ImageOptimize	1.2.2
Standards Agent	2.0.1

**Comment by brandonkelly** [comment]
This is expected behavior; if an update fails in a way Craft can’t recover from, or if it’s unsure about whether the initial update attempt is still ongoing, then the `info.maintenance` column value will be left at `1` or `true`.

Since there’s a decent chance that it will be mistaken, I’ve just updated the error to include a “Continue” button that forces the update to go through, despite the fact that it thinks someone else is doing it (1db3c793395072e46603c856d32ed5910ab72f25).

**Comment by narration-sd** [comment]
Sounds a good solution -- cheers, Brandon
