### ISSUE TITLE
.env File missing -> Error 500

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#1995]
### Description
If you do not have a .env file, you get a nondescript error looking like an Apache Error 500. No entries in the log or any other hint, that only the file is missing.

I think there should be some hint what's going wrong.

### Additional info

- Craft version: 3 beta 28
- PHP version: 7.1

**Comment by brandonkelly** [comment]
Nothing in Craft assumes you have a `.env` file. Can you give me steps to reproduce this?

**Comment by hiasl** [comment]
1. We set up a new project and configured the DB in .env file
2. We committed the project to our .git (not including the env file due to .gitignore)
3. We cloned it to another colleague's computer
4. We "composer install"ed Craft on the computer
5. We opened the project through the local webserver (MAMP pro) and got the error.
6. The error disappeared after added the .env file (which we simply forgot to create on that 2nd computer). After doing that, the error disappeared.

**Comment by brandonkelly** [comment]
This is what I get when I delete my `.env` file on a project based on the `craftcms/craft` Composer project (assume that was your starting point):

<img width="428" alt="screen shot 2017-09-18 at 10 59 24 am" src="https://user-images.githubusercontent.com/47792/30556708-9fc2aca6-9c60-11e7-99bb-0f92d4efc3d9.png">

From Craft’s perspective, this makes sense, since Craft has no idea where the DB settings are supposed to come from. The `.env` thing is just what the `craftcms/craft` project gives you by default.

(In fact even the `craftcms/craft` project can’t assume you want a `.env` file, as PHP dotenv [recommends](https://github.com/vlucas/phpdotenv#usage-notes) not using it in production. Which is why `web/index.php` checks if a `.env` file even exists before loading PHP dotenv.)

**Comment by hiasl** [comment]
hmm. then this seems to be a MAMP Pro issue, since your screenshot gives details, what the problem is. I only get "an error occured". good to know. ... thanks brandon!
