### ISSUE TITLE
Feature request: remove leading/trailing spaces from tags

### ISSUE THREAD

**Issue by adrienne** [craftcms/cms#1997]
Exactly what it says on the tin: tags shouldn't have leading/trailing spaces allowed. (Or at least there should be an option to disallow them.) We've got a situation where a tag keeps getting entered, and then the same tag but with a leading or trailing space gets entered via copy/paste, and then we have two identical-looking tags.

**Comment by brandonkelly** [comment]
@MakeilaLundy This could almost be considered a bug, so let’s fix it for v2 first. Will require writing a new Migration that finds any tags with leading/trailing spaces and strips them out (or merges with existing tags of same name w/out spaces), and then at in JS and PHP level we should be stripping out spaces so this isn't an issue going forward.

**Comment by brandonkelly** [comment]
Actually… this is more complicated than it seems at first glance.

- If two tags with the “same” name exist, no way to know which would should survive the merge. They could both have custom field content set on them, etc.
- On multi-lingual installs (or multi-site in Craft 3), two tags could have the “same” name in one locale/site, but different names in another. It may be too heavy handed to merge them just because they share the same name in one of the locales/sites.

Considering that, I don’t think we can fix this retroactively. We can update the JS and PHP to auto-trim tags as they are entered and saved, but I think any cleanup of existing tags would need to be left to admins, once we implement a tag management area (#820).

**Comment by adrienne** [comment]
Yay for the quick fix, thank you so much! (And yeah, i agree that retroactive fixing wouldn't work at this point, I just want it to happen on save/edit so my client doesn't get so aggravated about how he's ended up with duplicate tags.)
