### ISSUE TITLE
Setting `siteName` in config does nothing

### ISSUE THREAD

**Issue by mikefrancis** [craftcms/cms#2003]
### Description

When following the [docs](https://craftcms.com/docs/config-settings#siteName), setting a value for `siteName` doesn't actually override the value in the database.

### Steps to reproduce

1. Open Control Panel and change Settings -> General -> Site Name to `foo`
2. Open `config/general.php` and set `siteName` to `bar`
3. Add {{ siteName }} to template and see that `foo` is outputted instead of `bar`

### Additional info

- Craft version: 3.0.0-beta.28
- PHP version: 7.1.8
- Database driver & version: 5.7.19
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
Yeah that config setting was removed in Craft 3. (Now documented in the [Upgrading from Craft 2](https://github.com/craftcms/docs/blob/master/en/upgrade.md#config-settings) guide).

**Comment by mikefrancis** [comment]
How come it got removed - is it for i18n reasons?

**Comment by brandonkelly** [comment]
Sortof; because we would have needed to update it for the multi-site feature, and we just didn’t see many people wanting to set their site names from the config (unlike `siteUrl`, where you probably want to set that differently for each environment), so we just removed it.

We can bring it back though – do you have a use case where it would be helpful? Or just personal preference to have it defined by the config?

**Comment by mikefrancis** [comment]
I am trying to think of use cases but I think in the end it is just my personal preference 😅 

Things like the site info (like the the name, url, lang etc.) is something I could never see a client/end-user/stakeholder changing (and it might cause problems if they do) so would be great to set this in stone and have the message that it's being overridden.

**Comment by brandonkelly** [comment]
Interesting, personally seems like making it a config setting is a way of making it _less_ set-in-stone. As it is, you would need to be an admin to change those settings, and we don’t recommend giving clients admin access (at least as their primary user account).

**Comment by mikefrancis** [comment]
Apologies, I'm not sure what you mean by "less set in stone".

If it's overridden by config, then it doesn't really matter who is logging in, they won't have access to the codebase in order to change these kinds of settings.

Of course it's totally up to y'all whether you pursue this or not, just happy to have an ace CMS 😄

**Comment by brandonkelly** [comment]
Yeah I guess this is a little nuanced – generally if a CP setting has a config file counterpart, it’s because there’s a need for the setting to be set on a per-environment basis.

Honestly, it doesn’t matter to me, and I don’t think we had a good reason to remove it. Considering it’s already a config setting in v2 and bringing it back will be one less thing people need to deal with when updating to v3, I’m leaning toward just bringing it back.
