### ISSUE TITLE
More tag woes

### ISSUE THREAD

**Issue by adrienne** [craftcms/cms#2022]
I had previously submitted #1997 and it got incorporated - but the Javascript in my tag entry fields is now stripping out *all* spaces, not just leading/trailing spaces. That shouldn't be happening! I can fix it after the fact by double-clicking the tag to edit, of course, but that's less than helpful when nearly all the tags in question do in fact have internal spaces.

**Comment by takobell** [comment]
This has been fixed for the next release.

**Comment by narration-sd** [comment]
@adrienne  Haven't checked specifically, but since you're new in these parts lately, may want to know you can access anything they have by changing your `composer.json` to require dev-develop, then composer updating. 

Specifically, you want to use:
```
    "craftcms/cms": "dev-develop as 3.0.0-beta.99",
```

This will keep compatibility with all your other Craft things -- plugins, etc..

I've experienced no stability problems with dev-develop over many months, and it's a great way to be working with the latest...

Cheers, Adrienne

**Comment by takobell** [comment]
@narration-sd all perfectly valid and appreciated.  These particular bugs originated on Craft 2 and fixes haven't been merged into Craft 3 yet.
