### ISSUE TITLE
Background tasks slow down everything

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#2025]
### Description
In the backend background tasks seem to make my browser / the systems slow and they do not disappear. Below settings I have an additional row saying "Deleting stale template c...".
When I click on the row it takes almost a minute until Chrome is capable of opening and endlessly long list of background tasks? The one not disappearing is "Deleting stale template caches" and there it hangs.

1.) Why does this happen?
2.) Can I somehow reset it?
3.) Can I setup a server task for those background tasks (of course only if they do not kill my server in the same way they do with Chrome).?

### Steps to reproduce

1. Open backend under /admin/
2. Look at the navigation (of course only on my system).

I can provide a dump if needed via e-mail.

### Additional info
PHP version	7.1.9-1+ubuntu16.04.1+deb.sury.org+1
Database driver & version	MySQL 5.7.19-0ubuntu0.16.04.1
Image driver & version	Imagick 3.4.3, ImageMagick 6.8.9-9
Craft edition & version	Craft Pro 3.0.0-beta.28

**Comment by brandonkelly** [comment]
> 1.) Why does this happen?

Craft creates those tasks to look for template caches that should be deleted, due to some element query within the cached template that will start picking up a recently-saved element (where before the save, the element wasn’t showing up) – either because it’s a brand new element, or some property of the element changed such that it now gets picked up by the query.

> 2.) Can I somehow reset it?

You can clear out any rows in the `queue` DB table with the `description` set to “Deleting stale template caches”. And then just clear out your entire `templatecaches` table, so all caches get reset.

If it continues to be an issue, you can just disable query caching altogether, via the `cacheElementQueries` config setting in `config/general.php`:

```php
'cacheElementQueries' => false,
```

> 3.) Can I setup a server task for those background tasks (of course only if they do not kill my server in the same way they do with Chrome).?

You can run the tasks from the terminal (`./craft queue/listen` command). As per the yii2-queue extension [documentation](https://github.com/yiisoft/yii2-queue/blob/master/docs/guide/driver-db.md#console):

> `listen` command launches a daemon which infinitely queries the queue. If there are new tasks they're immediately obtained and executed. `delay` is time in seconds to wait between querying a queue next time. This method is most efficient when command is properly daemonized via [supervisor](https://github.com/yiisoft/yii2-queue/blob/master/docs/guide/worker.md#supervisor).
