### ISSUE TITLE
User Group Asset Source permissions not honoured when logged in as client user

### ISSUE THREAD

**Issue by joepagan** [craftcms/cms#2050]
### Description

Just had an issue where a client complained that they were having permission issues on upload. 

I logged in as the main admin user, go in to users, log in as the client user, I was able to upload an asset via an entry's asset field.

Looking at the user group permissions it revealed their user did not have permission, so, when I was logged in as them, I should not have been able to upload an asset.

### Steps to reproduce

1. Setup a new user & assign to a user group
2. Under the same user group, turn off all asset source permissions
3. Login as main admin user, then login as the new user through the dashboard "Login As ..."
4. Upload an asset through an asset field
5. Stare in awe at your uploaded asset that should not have been uploaded

### Additional info

- Craft version: 2.6.2986
- PHP version: 5.6.?!
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
What edition are you using? By “client user” do you mean the Client account on a Craft Client install? Confused because Craft Client doesn't have user groups.

**Comment by joepagan** [comment]
Sorry for the confusion, this is on Craft Pro.

It is not related to the "client" user on Craft Client. I regretfully just called it a client user as that's what it is in the context of this site. 

To confirm, it's a standard user on a Pro license, assigned to a group with group permissions.

**Comment by andris-sevcenko** [comment]
@joepagan in the current implementation, an Asset field settings override the User permissions. It's an issue that's been around (#887).

It's what makes sense in the majority of permission-related-scenarios, but it might not work for *all* scenarios.

The current state is that we'll be revisiting this issue in Craft 4.0 when RBAC comes around (#1646).

**Comment by joepagan** [comment]
I think that's the first time I've heard a bug _could_ be fixed in Craft 4.

Interesting that we are at that point now where a bug found being present in paid for software will not be addressed, until 2 full versions later (probably paid for license upgrades too I imagine?).

Your enthusiasm to support that particular version may have gone, because you're excited & nearing release of Craft 3. But currently, you are still selling licenses for Craft 2.

If you offer a feature in Craft 2, your customers expect it to work. If it doesn't work, you haven't really held up your part of the deal?

I wasted a good hour or more investigating an issue that I couldn't see before I realised something was wrong. I'm sure plenty of other devs may do the same.

At the very least you could put a warning suggesting that the feature doesn't fully mimic account permissions when logging in as another user?

**Comment by andris-sevcenko** [comment]
Logging in as another user has nothing to do with it.

If you have an Assets field in an entry that has either all or some Asset sources enabled on one hand and a user that has no Asset permissions and yet is able to edit an entry which has that Asset field on the other hand, there are two outcomes here:
* either the Asset field is unusable by the user because none of the Asset Source are available or
* what Asset Sources are defined by the Asset field takes precedence.

In case of Craft's implementation the user is granted upload permissions to the sources allowed/specified by the Assets field, even is the said user does not have those permissions.

In the rare cases where these two things (permissions and asset sources set up for a field) don't  align, this may seem to be a little counter-intuitive, but you would be disappointed too if we decided that user permissions overrule the permissions set up for an Assets field, because "why would you render an Assets field useless? I thought content was king!" Some problems just really are hard to solve and sometimes it's impossible to make everyone happy.

And all of that is a bit of a moot point, since there are ways of circumventing "read" permissions, anyway, as pointed out [here](https://github.com/craftcms/cms/issues/887#issuecomment-298459116). It would take a major effort to rewrite the permission system, probably breaking all of plugins that add their own permissions, making a major release for that a pre-requisite.

In the end, we must balance countless priorities to make sure that we finally deliver Craft 3 (not to mention Craft 2 that had three releases in October alone) on schedule and keep moving forward. It has nothing to do with enthusiasm at all.

**Comment by brandonkelly** [comment]
> I think that's the first time I've heard a bug _could_ be fixed in Craft 4.

To be clear, we don’t feel this is a bug. The current implementation already is the desired behavior for the vast majority of people. Sure, there are cases where it’s not desired,  which is why we do plan to address at some point, but as Andris said, it’s a matter of priorities. In the meantime if it’s really bugging you, it wouldn’t be too difficult to write a plugin that provides an alternative Assets field that takes user permissions into account. (And we’d be happy to offer guidance, if someone wants to tackle that.)
