### ISSUE TITLE
Drop cacheMethod config setting (and other cache-specific settings)

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#2053]
Considering (A) `db` and `memcache` cache methods require creating separate config files for configuring them, and even `file` requires a separate config file for overriding its `cachePath` and `gcProbability` settings; (B) the fact that we’ve never documented any of these settings; and (C) the fact that `redis` isn’t even supported anymore without installing the [yii2-redis](https://github.com/yiisoft/yii2-redis) extension, I think we should just drop the `cacheMethod` setting entirely, as well as support for the alternate cache method config files.

Then for anyone that needs something besides Craft’s default, our answer can be consistent: just override the `cache` component from `config/app.php`.

Would resolve #2045, and any other cache method-specific settings we’ve overlooked.

**Comment by ostark** [comment]
^^ https://github.com/ostark/craft-cache-config

**Comment by brandonkelly** [comment]
@ostark Added a few examples to the Craft docs here, fyi: https://github.com/craftcms/docs/blob/master/en/configuration.md#data-caching-config

**Comment by ostark** [comment]
I'm torn. On one hand the cache configuration in `config/app.php` is a good example for overriding core components. It helps to understand the whole Service Locator thing.

On the other hand the `CACHE_DRIVER` should be controlled by the ENV vars, since memcached or redis are maybe not available in testing environments but required in a prod env.

**Comment by brandonkelly** [comment]
Luckily config/app.php supports multi-evironment configs, so you could just override it in production.
