### ISSUE TITLE
Ajax getMoreElements not trigger "onUpdateElements"

### ISSUE THREAD

**Issue by lboaretto** [craftcms/cms#2054]
### Description

I'm using "Embedded assets for Craft" plugin from Benjamin Fleming that uses this function to update the thumbnails, which by default are displayed as JSON.

At the first request of the asset list, it's called "getElements" ajax which trigger "onUpdateElements". The same goes for search.

However, on pagination (getMoreElements) does not call "onUpdateElements".

### Steps to reproduce

1. Install craft with embedded assets plugin
2. insert some videos to get pagination
3. Scroll... wait for the second page and you will see the json icon instead of the video thumbnail.
4. Do a keyword search for a video that did not display the icon. It will show up.

### Additional info

- Craft version: 2.6.2993
- PHP version: 7.0.22
- Database driver & version: MariaDB 10
- Plugins & versions: embeddedassets 0.4.1

**Comment by brandonkelly** [comment]
That is expected since the `updateElement()` method is only called when the entire view/criteria is changing. When a view needs to load more elements, that goes through the view class’s `loadMore()` method instead. View classes have an `appendElements` event that the plugin could be listening to instead.
