### ISSUE TITLE
entry getChildren on channel entry will return entries from an entries field.

### ISSUE THREAD

**Issue by joepagan** [craftcms/cms#2093]
### Description

I have an issue on a project where `{{ entry.children }}` will return 3 entries when used on an entry in a channel, weirdly the entries it outputs are set on an entries field on the entry. The field's handle is: `pageRelatedProducts` in this case. I do use this field further down the page.

`{{ entry.getDescendants(1) }}` is meant to be an alias of `entry.children`, but, it will return 0 entries here.

This can be the case outside of a cache tag.

Just in case I have reset the var `entry.children` by accident, I commented literally everything out in my templates apart from the dump, it still returned 3 objects.

Here is the full markup for you:

    {# This turns the first entry from the field named entry.pageRelatedProducts  #}
    {% cache using key "l-listing-tile-grid - " ~ siteUrl %}
      {% set children = entry.children.type('listing') %}
      {% if children.first() %}
            {% for childEntry in children %}
              {% include "_partials/b-listing-tile" %}
            {% endfor %}
      {% endif %}
    {% endcache %}

    {# this returns all 3 as I want #}
    {% cache using key 'b-page-related-products - ' ~ siteUrl %}
      {% set relatedProducts = entry.pageRelatedProducts %}
      {% if relatedProducts.first %}
              {% for product in relatedProducts %}
                {% include "_partials/b-product-tile" %}
              {% endfor %}
      {% endif %}
    {% endcache %}

### Additional info

I presume this may not happen all the time, may just be project specific, let me know if you want me to try anything else or supply the DB etc.

- Craft version: 2.6.2986
- PHP version: 5.6.*
- Database driver & version: 5.6.32
- Plugins & versions: hacksaw, freeform, image resizer, stamp (tried without anything being loaded in templates), minify (tried without tags)

**Comment by brandonkelly** [comment]
This is because originally `getChildren()` was there to return “child” relations of the element. In Craft 1.3 we introduced the concept of Structure sections, and repurposed `getChildren()` to return nested structure entries instead. To prevent existing sites from breaking, the `getChildren()` function still does check to see if the section is a channel, and if so, will revert to its old, deprecated behavior, which is what you’re seeing here.

We’ve removed that check in Craft 3, so `getChildren()` will only ever return anything if it’s in a Structure section and there are actually nested entries.

**Comment by joepagan** [comment]
Are you really keeping backwards compatibility from 1.3 -> 2.6+? If someone wanted to do that, I'm sure there would be plenty more to review.

Are you going to mention this anywhere in your docs?

https://craftcms.com/docs/templating/entrymodel#getChildren

>Returns an ElementCriteriaModel prepped to return the entry’s children (if it lives in a Structure section). (This is an alias for getDescendants(1))

In this case `getChildren()` and `getDescendants(1)` return different results. So it is incorrect to suggest that it is an alias for `getDescendants(1)`.

**Comment by brandonkelly** [comment]
We like to give give people one full version cycle to deal with deprecation errors, when it’s feasible. So for all the things that are deprecated in 3.0, everyone will have until 4.0 is released to deal with them. In this case, since `getChildren()` behavior didn't change until 1.3, we are giving people until 3.0.

You’re right, due to keeping old behavior, it’s not technically an alias of `getDescendants(1)` when called from a Channel section’s entry. But there’s no point in calling it from a channel entry in the first place, since channel entries cannot have child entries, so doesn’t seem worth documenting the technicality. AFAIK this is the first time it has come up.

**Comment by joepagan** [comment]
I have identified behaviour which conflicts with how you say it should behave in your documentation. Isn't that a bug?

You may want to cater to the incredibly small percentile who _may_ want to update from 1.3 -> 2.6, but, ultimately, the burden is on them to check their website is working as it used to.

>But there’s no point in calling it from a channel entry in the first place

Unless a channel entry & a structure entry shared the same template because they're identical in every way apart from a list of children.

**Comment by brandonkelly** [comment]
> Unless a channel entry & a structure entry shared the same template because they're identical in every way apart from a list of children.

Fair enough. Just added a warning about this behavior. https://craftcms.com/docs/templating/entrymodel#getChildren

**Comment by joepagan** [comment]
Cheers mate
