### ISSUE TITLE
Incomplete support for `bodyClass` variable in CP

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#2141]
### Description

Found a few pages in the CP where the `bodyClass` variable isn't being respected:

    /admin/myaccount
    /admin/entries/mySection/new
    /admin/utilities/system-report

There may be other pages as well, I stopped looking for more examples.

In some places, it still works properly (ie: `/admin/settings`). I assume those are feeding off of different parent templates?

### Steps to reproduce

1. Dynamically set the `bodyClass` Twig variable in the CP.

    ```php
    Craft::$app->getUrlManager()->setRouteParams([
        'bodyClass' => 'example-class'
    ]);
    ```

2. Go to the above-mentioned pages in the control panel.
3. View the page source.
4. Notice that your `bodyClass` doesn't get included in the `<body>` tag.

### Additional info

- Craft version: Craft Pro 3.0.0-RC1

**Comment by brandonkelly** [comment]
This would happen on any page that gets routed to a controller action other than `templates/render`. Because `templates/render` is the only controller action that looks for additional route params and includes them in the variables it passes to the template.

Rather then try to change that behavior for every controller action, I just added a new hook to the `_layouts/base.html` template that you can use instead:

```php
if (Craft::$app->request->getIsCpRequest()) {
    Craft::$app->view->hook('cp.layouts.base', function(array &$context) {
        $context['bodyClass'] .= ' example-class';
    });
}
```

**Comment by lindseydiloreto** [comment]
Brilliant, that worked perfectly... Thanks @brandonkelly!

Which version of `craftcms/cms` should my plugin require to ensure compatibility?

**Comment by brandonkelly** [comment]
`^3.0.0-beta.36`

**Comment by lindseydiloreto** [comment]
Excellent, thanks Brandon!
