### ISSUE TITLE
ReflectionException: Class Swift_MailTransport does not exist

### ISSUE THREAD

**Issue by ryanfoote** [craftcms/cms#2149]
### Description

I believe this cropped up after installing beta 35. I'm using a plugin, dolphiq/craft3-forms for form management and email notification upon a form submission. When submitting a form, the following error is thrown:

```
ReflectionException

Class Swift_MailTransport does not exist
```

Stack trace gist: https://gist.github.com/ryanfoote/88e0ad51d3029c9b7e453007d827985b

At this point in time, I have not tested whether or not this affects other email functions in Craft, such as new user email notifications, etc.

### Steps to reproduce

1. Create a new form per dolphiq/craft3-forms instructions - include an email notification component.
2. Fill out & submit the form - above error will be thrown.

### Additional info

- Craft version: Craft Client 3.0.0-beta.35
- PHP version: 7.0.17
- Database driver & version: MySQL 5.6.32
- Plugins & versions:  dolphiq/craft3-forms v1.0.0

**Comment by brandonkelly** [comment]
Thanks for the heads up! Turns out Swift Mailer 6.0 removed support for the PHP mail adapter. So just changed the default to Sendmail instead. 

Both PHP mail() and Sendmail require server configuration to work, and either way you’re still going to be better off using SMTP, or a transactional email service like Postbox / Mailgun / Mandrill - which is now much easier in Craft 3 thanks to the like-named plugins.
