### ISSUE TITLE
Craft CMS 3.0.0 RC1: Color field not working (saving incorrect value)

### ISSUE THREAD

**Issue by dolphiq-allard** [craftcms/cms#2170]
### Description

If I implement the new color field in 3.0.0. RC1 it will show up nicely and allows me to pick a color or enter a value manually. However, after saving the entry, the color value is replaced by `#{}`

### Steps to reproduce

1. Add `Color` as field type to any section;
2. Select a color, or enter a value manually;
3. Safe the entry.

### Additional info

- Craft version: 3.0.0 RC1
- PHP version: 7.1.8
- Database driver & version: MySQL 5.5.41-MariaDB
- Plugins & versions: N.a.

**Comment by brandonkelly** [comment]
Thanks!

**Comment by dolphiq-allard** [comment]
No worries,

Thanks for the quick fix. 


Met vriendelijke groet,

Allard Rothengatter

Dolphiq
Creative

+31 (0)35 20 300 52  |  Rembrandtlaan 1b  | 3723 BG Bilthoven

**Comment by narration-sd** [comment]
If you're thoughtful about it, i.e. remember this will put you _not_ on a release, so that you need to change it back before actually intending to use a release, you could set your Craft composer.json line temporarily to

`    "craftcms/cms": "dev-develop as 3.0.0-RC1",
`
When a real release comes along, or you want to go back to real RC1, you'd reset this simlar to
`    "craftcms/cms": "^3.0.0-rc.N",
`
This will get you the latest improvements if you have enough need for them to deal with any possible instabilities along the way. minding that the rc.N version number was then correct.

**Comment by brandonkelly** [comment]
We'll get the next update out in a day or two.

**Comment by narration-sd** [comment]
cleared up the alternate method a little -- again, just if you're comfortable to do such.

Great that such effort comes as always from team, to keep the fixes very timely...

**Comment by RitterKnightCreative** [comment]
Appears to be broken in Safari as of RC2. Chrome and Firefox work though.

**Comment by brandonkelly** [comment]
@RitterKnightCreative Just re-tested and everything is working fine for me in Safari. And it was a server-side issue, anyway. Are you getting any JavaScript errors on the page?

**Comment by RitterKnightCreative** [comment]
@brandonkelly I take that back, appears it's a Safari issue.  Go figure, Apple.
