### ISSUE TITLE
Entry dates in CMS seem to be m/d/Y rather than respecting site Language setting

### ISSUE THREAD

**Issue by Harry-Harrison** [craftcms/cms#2218]
### Description

Upon creating a new site in Craft 3, the entry dates seem to be set to m/d/Y instead of using the site Language setting. As a side note, I've noticed the time suffix is lowercase in one spot but uppercase in another.

<img width="318" src="https://user-images.githubusercontent.com/140605/34016217-fd8dca30-e118-11e7-9bf0-3e47f8024cd2.png">

### Steps to reproduce

1. Set site language to en-GB
2. Create an entry and see how the date is 12/14/2017 for the Post Date, Created Date and Edited Date in the entry meta section.

### Additional info

- Craft version: Craft Personal 3.0.0-RC2
- PHP version: 7.1.12-1+ubuntu16.04.1+deb.sury.org+1
- Database driver & version: MySQL 5.5.5-10.2.11-MariaDB-10.2.11+maria~xenial-log
- Plugins & versions: None

**Comment by brandonkelly** [comment]
All dates are formatted based on your user account’s Language setting, not the current entry’s site’s language. So this is probably working as expected, assuming your account’s Language is set to US English (or some other locale that follows a similar date format).

> As a side note, I've noticed the time suffix is lowercase in one spot but uppercase in another.

Thanks for pointing that out! Turned out to be a Yii bug (#15380). Submitted a PR to fix it, so hopefully this will be fixed in Yii 2.0.14.
