### ISSUE TITLE
Change *Volume Type* does not work 

### ISSUE THREAD

**Issue by ostark** [craftcms/cms#2222]
### Description

Not sure what the expected behavior is, but in the CP there is a possibility to change the **Volume Type** for a Volume. 

If the option to change the type is not implemented, the Select Field should not exist. If there is an implementation, it should be fixed :-)

### Steps to reproduce

**Case 1**

1. In the CP > admin/settings/assets/volumes/{ID}
2. Change **Volume Type** from "Local Folder" to "Amazon S3"
3. [Save]

*It works! No errors, but no files get moved to S3.*

---

**Case 2**

1. In the CP > admin/settings/assets/volumes/{ANOTHER_ID}
2. Change **Volume Type** from "Amazon S3" to "Local Folder"
3. [Save]

*Error*

```
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: craft\volumes\Local::keyId
...
in controllers/VolumesController.php at line 192 – craft\services\Volumes::createVolume(['id' => '5', 'type' => 'craft\volumes\Local', 'name' => 'Remote Cloud', 'handle' => 'frbitObjects', ...])
```

---

### Additional info

- Craft version: 3 RC2
- PHP version: 7.1
- Plugins & versions: craftcms/aws-s3 1.0.7

**Comment by andris-sevcenko** [comment]
Regarding case 1, Craft isn't going to move your files for you. There are [ways](https://craftcms.stackexchange.com/questions/1212/is-it-possible-to-move-an-entire-asset-source/1215), though.

Regarding case 2, you probably have your AWS keys defined in a config file, so Craft tries to add them to the now-local Volume because the handle remains the same. Can you check if that's the case?

**Comment by ostark** [comment]
Yes, I know - that's the case.

**Comment by andris-sevcenko** [comment]
Okay. So I'm assuming there's no issue here and I'm closing this one. If you feel like that is not the case, feel free to respond.

**Comment by ostark** [comment]
@andris-sevcenko 
If files are not moved from one Volume Type to another (and that's okay), why provide the option to change the Type?
Plus, since overwrites via config file are possible others may run into this error as well.

**Comment by andris-sevcenko** [comment]
@ostark Well, because it's possible to move files outside of Craft in case somebody decides that S3 is too expensive or, conversely, local storage does not scale.

The second issue you have with it... I understand it might be annoying, but it should only happen when a system component (Volume) is misconfigured. It's definitely discussable whether it's the best way to have it, but that would have to be a Craft-wide change, as multiple components have config overrides. Maybe @brandonkelly has an opinion about it.
