### ISSUE TITLE
Globals set saving fails if field validation fails (even for non-required fields)

### ISSUE THREAD

**Issue by Tam** [craftcms/cms#2226]
### Description
When I attempt to save a globals set where one of the fields has a custom validator (in this case, my [SimpleMap plugin](https://github.com/ethercreative/simplemap)), the saving will fail because the fields validation fails. This probably shouldn't happen since the field isn't required, and I haven't had a chance to populate it yet!

I've managed to work around this by adding:
```php
if (strpos(\Craft::$app->request->url, 'settings/globals') !== false)
	return null;
```
to the validator, but this is obviously an aweful fix!

### Steps to reproduce

1. Create a new global set
2. Add a field with a custom validator (i.e. SimpleMap)
3. Attempt to save

### Additional info

- Craft version: Craft Pro 3.0.0-RC2
- PHP version: 7.1.8
- Database driver & version: PostgreSQL 10.0
- Plugins & versions:

Name | Version
-- | --
SimpleMap | 3.1.1
SEO | 3.0.0
Splash | 3.0.1
Logs | 3.0.0
CraftQL | dev-master

**Comment by brandonkelly** [comment]
Craft ensures that required fields have a value when the entry is enabled, but that’s it. Everything else should be left up to the field type, because there are cases where things should be validated even if the entry isn’t live yet. For example textual fields should validate that the content is going to fit inside the database column, to avoid a SQL error and data loss.

So in this case I would consider this a Simple Map bug.

**Comment by brandonkelly** [comment]
To fix this from Simple Map’s end, the `getElementValidationRules()` method should be changed to:

```php
return [
    [MapValidator::class, 'on' => Element::SCENARIO_LIVE],
];
```

**Comment by Tam** [comment]
Awesome, thanks for your help!
