### ISSUE TITLE
[bug] Entries Field Not Saving Data on Multisite

### ISSUE THREAD

**Issue by mzlock** [craftcms/cms#2229]
### Description

On Multisite, I have a content type that is not saving an Entries field. There is no error, the data is just not saved.

### Steps to reproduce

1. Create a Section that exists on both sites (Section A)
2. Create a Section that exists on one site (Section B)
3. Create a Field - Entries Field - that only lets you select from Section B
4. Assign the Field to Section A
5. Create an entry in Section B
6. Try to create an entry in Section A, picking a related entry from Section B

What I'm seeing: I can select something with the Entries field and the entry in Section A does save. But the Entries field does not save a relation and there is no error. Everything looks right, but then I go to edit the entry in Section A again and the relation is gone. And it's gone regardless of which "Site" I have selected at the top.

### Additional info

- Craft version: 3.0.0-rc3
- PHP version: 7.0.8

**Comment by mzlock** [comment]
This entries field was working for me when I was originally working on Craft 3.0.0-beta.34, I believe. So a recent change may have/ probably did introduce this bug.

**Comment by brandonkelly** [comment]
The issue is that relation fields (including Entries fields) don’t remember which site you had selected when you created the relation. By default they will just pull in related entries from the currently-selected site. So if you save the relations while editing Section A in the same site that Section B is enabled for, and you view the entry for that same site in the front-end, the relations should show up. For any other site, though, the field will come up empty, since the target entries aren’t available in that site.

The way to fix this is to edit your Entries field’s settings, open the Advanced section at the bottom, check the box “Relate entries from a specific site?”, and choose the site that Section B is enabled for. Then everything should start working, regardless of which site is selected.
