### ISSUE TITLE
Default User Group for Public Registration not honoured after renaming a Group?

### ISSUE THREAD

**Issue by shuckster** [craftcms/cms#2304]
### Description

As title, but perhaps problem is limited to submitting the form as an already logged-in admin, since that's the only path I've tested so far.

### Steps to reproduce

1. Create a group.
2. Set it as the Default User Group.
3. Rename the group.
4. Create a user-registration form.
5. Complete and submit it.
6. Selected "Default User Group" in CP User Settings is not applied to the new user.

Problem persists when deselecting and reselecting the renamed Group in the CP.

### Additional info

- Craft version: Craft Pro 3.0.0-RC5
- PHP version: 7.2.0
- Database driver & version: MySQL 5.5.28
- Plugins & versions: -

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. The default group is remembered by its ID, not its name (or even its handle), so unless you delete the group and create a new one, Craft will remember it.

I just tested, just to be sure there isn’t a general problem with default user group assignment, and it worked fine.

**Comment by shuckster** [comment]
The problem does not occur if the registration form is public.

It only occurs if I am already logged-in as an admin.

**Comment by brandonkelly** [comment]
Ah, that is expected behavior. The default user group is only factored in for _public_ registration. If you are already logged in, then it is _private_ registration (Craft doesn’t know or care that it came from a page that was meant for public registration).

If you really want admins to register users from your front-end registration form, you will need to explicitly tell the controller that you want the user assigned to a group, either with checkboxes (like the user form in the Control Panel) or a hidden input.

```html
<input type="hidden" name="groups[]" value="X">
```

(Replace `X` with the default group ID.)
