### ISSUE TITLE
Filling-in a new-user registration form as a logged-in admin will not assign the Default User Group to the new user

### ISSUE THREAD

**Issue by shuckster** [craftcms/cms#2311]
### Description

As title.

### Steps to reproduce

1. Create a group.
2. Set it as the Default User Group.
3. Create a user-registration form.
4. Log-in as an admin.
5. Complete and submit the user-registration form.

Leaving out step 4 does not produce the bug.

### Additional info

- Craft version: Craft Pro 3.0.0-RC5
- PHP version: 7.2.0
- Database driver & version: MySQL 5.5.28
- Plugins & versions: -

**Comment by brandonkelly** [comment]
This is expected behavior. The default user group is only factored in for _public_ registration. If you are already logged in, then it is _private_ registration (Craft doesn’t know or care that it came from a page that was meant for public registration).

If you really want admins to register users from your front-end registration form, you will need to explicitly tell the controller that you want the user assigned to a group, either with checkboxes (like the user form in the Control Panel) or a hidden input.

```twig
{% if currentUser %}
    <input type="hidden" name="groups[]" value="X">
{% endif %}
```

(Replace `X` with the default group ID.)

**Comment by shuckster** [comment]
Thanks for the tip. That would be great, but now I'm getting `This action may only be performed with an elevated session`. Dunno how much more elevated than `Admin` I can get, hehe. :)

**Comment by angrybrad** [comment]
@shuckster Even admins have to provide their current password to start an elevated session for certain sensitive actions.  It's lasts for 5 minutes by default, but is configurable. See the last half of this post: https://craftcms.com/news/new-security-features

**Comment by brandonkelly** [comment]
Sorry, forgot about that bit.

That’s a bit more complicated to get working – you’ll need to prompt the user for their password, and send an Ajax POST request before submitting the form, with the following body params:

```
action: users/start-elevated-session
password: <the user's password>
```

If it comes back with a `{"success": true}` body, then the form can be safely submitted with the `groups[]` input. (Otherwise they got their password wrong.)

Or maybe just don't have admins register new users on the front-end, unless they log out first.

**Comment by shuckster** [comment]
Ah, excellent! I do prefer the manual creation of accounts for this use-case, and I'm happy to implement the extra AJAX authentication step.

I can see from the CP that I can limit the permission of assigning a group on a per-group basis, so even non-admins (but user-moderators, for example) can use the form.

Thanks for the help. :)
