### ISSUE TITLE
Mcrypt is removed in PHP 7.2

### ISSUE THREAD

**Issue by thaoms** [craftcms/cms#2321]
So Craft 2 doesn't work on PHP 7.2. Not sure if this needs to be fixed as Craft 2 will become legacy.

> The mcrypt extension has been abandonware for nearly a decade now, and was also fairly complex to use. It has therefore been deprecated in favour of OpenSSL, where it will be removed from the core and into PECL in PHP 7.2.

http://php.net/manual/en/migration71.deprecated.php

**Comment by angrybrad** [comment]
Craft 2 supporting PHP 7.2 will depend on Yii 1 supporting it, which seems unlikely given how much effort it would take (https://github.com/yiisoft/yii/issues) and that Yii 1 is in maintenance mode (http://www.yiiframework.com/news/133/yii-1-1-18-is-released/).

Specifically that CSecurityManager would have to be rewritten in a backwards-compatible way and swap to using OpenSSL instead of mcrypt: https://github.com/yiisoft/yii/issues/4182

**Comment by neosin** [comment]
I just installed craft3 and get the error about mcrypt on php 7.2.2
So reading this thread....until yii updates, craft cms can't function on php 7.2+  
are you sticking with yii ? it seems like a bad choice if they aren't updating.

**Comment by andris-sevcenko** [comment]
@neosin Are you sure you installed Craft 3? Craft 3 does not use mcrypt.

**Comment by clarknelson** [comment]
I would like some kind of suggestion on what to do for Craft 2 sites on servers running php7.2 +

**Comment by angrybrad** [comment]
@clarknelson currently the answer is don't use Craft 2 with PHP 7.2. You can install mcrypt through PECL, but there are other PHP 7.2 issues with Yii 1 (https://github.com/yiisoft/yii/issues) as well as other dependencies like Twig 1.x. Craft 3 uses Twig 2, but that is a breaking change, so unlikely Craft 2 would start using it.

**Comment by justinmacleod** [comment]
I came across this ticket first before seeing that Craft 2.7.x was released with support for PHP 7.2. For future searchers: https://craftcms.com/blog/craft-2-7-released-with-php-7-2-compatibility

**Comment by brandonkelly** [comment]
@justinmacleod Thanks for mentioning!
