### ISSUE TITLE
Trying to create records to db using craft\records\... 

### ISSUE THREAD

**Issue by vladyslavhontar** [craftcms/cms#2329]
### Description
Hi, i am trying to install default content (sections, layout, fields and so on) using my service in my plugin. 
After installing data, Craft logout me from server and then i cannot login using my password and login, Craft just reloads the login page.
Can i create records in the database using ActiveRecords from craft cms, as Section, FieldLayout and so on and so forth.

### Steps to reproduce

1. Create ActiveRecord object from \craft\records\...
2. Call method save

```
use craft\records\FieldLayout;

$record = new FieldLayout();
$record->type = $data['type'];
if (!$record->save()) {
    die(\GuzzleHttp\json_encode($record->getErrors()));
}
```

### Additional info

- Craft version: 3.0.0-rc6
- PHP version: 7.0
- Database driver & version: mysql 5.6
- Plugins & versions: redactor (1.0.1)

**Comment by brandonkelly** [comment]
You should use Craft’s services to create those things, rather than saving records directly. For example, to save a section, use [craft\services\Sections::saveSection()](https://docs.craftcms.com/api/v3/craft-services-sections.html#saveSection()-detail).

As far as field layouts go, those will get saved in the process of saving the thing that they’re for. For example, an entry type’s field layout will be saved when the entry type is saved.

**Comment by vladyslavhontar** [comment]
thanks, i've already found it.
