### ISSUE TITLE
EVEN_INIT for Element Queries

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#2377]
Looks like the `craft\base\Component::init()` has a handy init event which would be really nice to have on element queries as well.  Thoughts?

**Comment by michaelrog** [comment]
I thought that was done in #1856... but now looking deeper I see that ElementQuery jumps the inheritance tracks and ends up extending `yii/base/Component` rather than `craft/base/Component`. Tricksy, that.

I second adding that lifecycle event to `craft\db\Query` so that I can, ahem, definitely never monkeypatch all manner of evil things onto `ElementQuery` objects.

**Comment by brandonkelly** [comment]
And done.

**Comment by nateiler** [comment]
Thank you sir.
