### ISSUE TITLE
FR: Disable propagation of entries on structures

### ISSUE THREAD

**Issue by Rias500** [craftcms/cms#2386]
### Description
The propagate entries toggle that was introduced in https://github.com/craftcms/cms/commit/a3cc52f0f13b3bd7288e599571adf5da0d70cc69 seems to only be available when using channels, is it impossible to have this for structures? 

### Steps to reproduce

1. Have a multisite
2. Edit a structure section
3. See no toggle :(

### Additional info

- Craft version: 3-RC8
- PHP version: 7.1

**Comment by brandonkelly** [comment]
In order to get this working, Structure sections will need to start managing entry hierarchies on a per-site basis (when site propagation is disabled). Which means moving the `structureId` out of the `sections` table and into the `sections_sites` table, etc.

**Comment by mattcdavis1** [comment]
@brandonkelly - any chance we can do this pre-3.0?  The current state pretty much renders structures useless for multisite installations.

**Comment by brandonkelly** [comment]
@mattcdavis1 We don’t have the resources, so no unless you want to submit a PR.

**Comment by lenvanessen** [comment]
Absolutely a must for Craft 3!

**Comment by jcherniak** [comment]
Any chance this might make it in soon?  I'm working on a big multi-site project and can't use Structures without this.

**Comment by brandonkelly** [comment]
@jcherniak it’s on the 3.1 list – so in the next 2 months or so.

**Comment by aaron-dotdev** [comment]
Another vote for this as in my mind it's not true multisite without being able to use Structures

**Comment by naboo** [comment]
+1 vote.

**Comment by estebancastro** [comment]
1+ vote, I need structures in a multi-site project, now they are useless without this.

**Comment by bfopma** [comment]
+1 vote. This is a major need.

**Comment by miro94** [comment]
+1 vote

**Comment by FrankZwiers** [comment]
+1 vote

**Comment by michaelhue** [comment]
@brandonkelly Are you still taking pull requests on this? I'd like to give it a shot. :)

**Comment by Raabye** [comment]
ETA on this? Multisite will be next level with this feature.

**Comment by brandonkelly** [comment]
@michaelhue No need, but thanks anyway :)

@Raabye Soonish.

**Comment by jerome2710** [comment]
@brandonkelly Would be nice to communicate a date to our paying Craft Pro clients hear what 'soonish' is, as this issue already exists since February.

**Comment by brandonkelly** [comment]
@jerome2710 As said it’s coming in 3.1. Not ready to give a release date for that so let’s just say by the end of the year.

**Comment by brandonkelly** [comment]
Just got around to implementing this for 3.1, and realized that I was drastically overcomplicating it in my head, and there’s no real reason that each site can’t just share the same nested set tree (“structure”) behind the scenes. So it’s now added for the next 3.0 release.

**Comment by narration-sd** [comment]
good on  ya ;)

**Comment by naboo** [comment]
Awesome Brandon :)

Den lör 20 okt. 2018 02:19Narration SD <notifications@github.com> skrev:

**Comment by richhayler** [comment]
This is friggin awesome!! Thanks amazing CraftCMS team 👌😊

**Comment by naboo** [comment]
Would it be possible to extend this to categories as well? (since categories are just structures, right?)

**Comment by brandonkelly** [comment]
@naboo We’re planning on adding this and other multi-site features to categories in 3.1.

**Comment by jcherniak** [comment]
Did this make the cut for 3.1?  I don’t see it in the release notes.  Are we kosher to use structures on a per site basis now?

**Comment by brandonkelly** [comment]
Unfortunately no it did not, but it’s on the short list for 3.2.

**Comment by brandonkelly** [comment]
@jcherniak This has been implemented for Structures since 3.0.28 (see https://github.com/craftcms/cms/issues/2386#issuecomment-431528881).

We weren’t able to implement it for category groups yet as we originally hoped to do in 3.1, but that’s on the short list for 3.2, which won’t be more than a few months out.

**Comment by jcherniak** [comment]
Wonderful!  Structures are where I needed it at least.




On January 17, 2019 at 10:01 PM, Brandon Kelly
(notifications@github.com) wrote:

@jcherniak ( https://github.com/jcherniak ) This has been
implemented for Structures since 3.0.28 (see #2386 (comment) 
( https://github.com/craftcms/cms/issues/2386#issuecomment-431528881 )

).
We weren’t able to implement it for category groups yet as we
originally hoped to do in 3.1, but that’s on the short list for

3.2, which won’t be more than a few months out.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
( https://github.com/craftcms/cms/issues/2386#issuecomment-455437096 )

, or mute the thread
