### ISSUE TITLE
Decouple Preview Link duration from defaultTokenDuration

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#2394]
It would be nice to be able to set a longer lasting duration for Preview Links without affecting site security by setting the same time for the default token duration.

**Comment by carlcs** [comment]
It looks like `defaultTokenDuration` isn’t actually used for anything else than preview link generating right now. Plugins might use it though, so simply re-naming it probably doesn’t work.

**Comment by brandonkelly** [comment]
Just added a new `previewTokenDuration` config setting for the next release ✨

**Comment by dlindberg** [comment]
This does turn out to be a breaking change. If `defaultTokenDuration` is set and `previewTokenDuration` is not, the preview token is set to `86400` instead of the value of `defaultTokenDuration`. Which means if you had been using the previous method to extend the preview duration, those links will expire sooner than anticipated and adding the new config setting is required to extend preview duration.

**Comment by brandonkelly** [comment]
@dlindberg Yeah that’s fair. Just tweaked it for the next release, so `previewTokenDuration` now uses the `defaultTokenDuration` value by default. (1b2a23a38cc7403398ca6d9a425a9b8b2469862b)

**Comment by brandonkelly** [comment]
Craft 3.7.26 is out with that change.
