### ISSUE TITLE
Ligthtswitch default value "enabled" state is not respected

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#2404]
### Description
When adding lightswitch to entry type with default value configured to enabled, the value of it when editing entry remains disabled

### Steps to reproduce

1. Create lightswitch field, default to on (enabled), translatable per site
2. Add this field to entry type
3. Edit an entry of this entry type
4. Notice that default value is disabled, while it should be enabled

### Additional info

- Craft version: Craft Pro 3.0.0-RC6
- PHP version: 7.1.12
- Database driver & version: PostgreSQL 9.6.2

**Comment by brandonkelly** [comment]
This was technically the intended behavior (default value generally should only apply to _brand new_ elements, not existing elements), but since Lightswitch fields are boolean, so `null` isn’t a relevant value for them in the first place, I guess an exception can be made. So just fixed this for the next release.
