### ISSUE TITLE
Craft CMS is not catching Unknown Property error on backend

### ISSUE THREAD

**Issue by andrelopez** [craftcms/cms#2415]
### Description

The weird behavior here is that when the error comes up, craft cms redirects to the login page. If you go to any front-end page you can see the error properly (devMode is enabled)

`Unknown Property – yii\base\UnknownPropertyException
`
### Steps to reproduce

1. Login to the CP
2. Go to craftcms/src/fields/PlainText.php
3. Remove the placeholder variable
4. Refresh the control panel

### Additional info

- Craft version: 3.0.0-RC9
- PHP version: 7.0.0
- Database driver & version: Mysql
- Plugins & versions: custom plugins

**Comment by brandonkelly** [comment]
The first time `yii\web\User::getIdentity()` is called, it’s within a try/catch in `craft\base\Application::getTargetLanguage()`:

https://github.com/craftcms/cms/blob/ed1714d61379a05d68cd82a30d4f0d92e360ad74/src/base/ApplicationTrait.php#L217-L221

Before `yii\web\getIdentity()` calls `$this->getAuthStatus()`, it will set `$this->_identity = null`, effectively saying that no one is logged in:

https://github.com/yiisoft/yii2/blob/24f4e3126a9f6562a78ea55ad058f9c155ef09af/framework/web/User.php#L188-L191

So in this case, since the exception gets caught, the application continues processing, but critically, Yii now thinks that no one is logged in.

Not much we can do about this directly in Craft, besides completely overriding the `user` component with a new instance, which isn’t ideal. So I've filed an issue with Yii about it (yiisoft/yii2#15621), and submitted a PR that fixes it (yiisoft/yii2#15622). Hopefully it gets accepted.

**Comment by brandonkelly** [comment]
And the PR is merged now, for Yii 2.0.14. So this will be fixed as soon as that comes out (which we hear is right around the corner).

**Comment by andrelopez** [comment]
Great news!
