### ISSUE TITLE
New users widget displaying 0 for all dates

### ISSUE THREAD

**Issue by craigh44** [craftcms/cms#2433]
### Description

Craft 3
New users widget on dashboard is displaying 0 new users, for any date range and user group

### Steps to reproduce

1. Add new users widget to dashboard

### Additional info

- Craft version: 3.0.0-RC9
- PHP version: 7.2.2
- Database driver & version:  MySQL 5.7.21
- Timezone: Europe/London

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you please send a database backup to support@craftcms.com and reference this issue?

**Comment by brandonkelly** [comment]
We were able to reproduce this on a Windows server. Turns out MySQL's `CONVERT_TZ()` function relies on time zone data that isn’t included by default on Windows servers (and possibly others, though this is the first we’ve heard of this bug).

We worked around it in 74dda704 by no longer relying on that function. So this is fixed for the next release.

**Comment by narration-sd** [comment]
While verify that this can happen on Linux servers also, if MySQL wasn't smartly installed. 

As at an otherwise pretty high class shared hosting involved with my database agent; had to code around for all time arithmetic.
