### ISSUE TITLE
Upon editing Field type - The config passed into Component::createComponent() did not specify a class.

### ISSUE THREAD

**Issue by mishellnovosel** [craftcms/cms#2434]
With the latest updates RC10 and RC10.1 I've lost some of the Matrix block fields ( most of them were Lightswitches ). The weird thing that is happening is that I now can't create more than one new block in matrix to already existing Field type. When I try to add second one I receive following error that is referring to the first newly added block:

Internal Server Error

The config passed into Component::createComponent() did not specify a class: {"type":null,"id":198,"name":"PlainTest","handle":"plaintest","instructions":"","required":false,"translationMethod":"none","translationKeyFormat":null,"settings":null}

When creating new Field type, I can add multiple Blocks without any problem.

### Steps to reproduce

1. Edit existing matrix field type
2. Add two or more Blocks to the end
6. Save ( error thrown )

### Additional info

- Craft version:  Craft Pro 3.0.0-RC10.1
- Multisite : enabled
- PHP version: 7.0.27
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
  - Redactor 1.0.1
  - Amazon S3 1.0.8

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Can you send in a database backup to support@craftcms.com ?

**Comment by brandonkelly** [comment]
I was able to reproduce this with your database backup on a stock Homestead box (on a site configured to run PHP 7.0).

The issue is that the POST data is getting cut off at the 1,000th item, so Craft isn’t getting a complete picture of what you’re trying to save. You can fix it by increasing your `max_input_vars` setting in php.ini from `1000` to something else – maybe `2000`.
