### ISSUE TITLE
Entries with the same postDate display in an inconsistent order.

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#2447]
### Description
I have 10 test entries in a channel. The first 3 all have the exact same postDate, down to the second.

```twig
{% set films = craft.entries({
  section: 'films',
  orderBy: 'postDate desc'
}) %}
```

When I paginate my entries on my channel's index, with a `.limit(9)` set, they display in the correct order, matching the order in the backend.

```twig
{% paginate films.limit(9) as pageInfo, pageEntries %}
{% for film in pageEntries %}
  <div class="films-list-item grid-item">
    {% include "films/_includes/film_widget" with { film: film } %}
  </div>
{% endfor %}
```

Having issues with getting the `nextEntry` in correct order on entry pages, I ran some tests on my entry.

Outputting two different loops for films on my entry.

```twig
{% set films = craft.entries({
  section: 'films',
  orderBy: 'postDate desc'
}) %}

<ul>
  <li>Films without limit:</li>
  {% for film in films.all() %}
    <li>{{ film.title }} {{ dump(film.postDate) }}</li>
  {% endfor %}
</ul>

<ul>
  <li>Films with limit:</li>
  {% for film in films.limit(9) %}
    <li>{{ film.title }} {{ dump(film.postDate) }}</li>
  {% endfor %}
</ul>
```

**Films without limit:** returns the first 3 entries (ones with the same postDate) in reverse order when compared to the backend.

**Films with limit:** returns films in the same order as the backend.

A really weird thing I found was that running `{% for film in films.limit(5) %}{% endfor %}` after my films declaration fixed the incorrect order of my **Films without limit:**, but the limit was passed on to the **Films without limit:** list.

### Additional info

- Craft version: 3.0.0-RC10.1
- PHP version: 7.1.13
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
This is just due to how MySQL orders results when the order is not explicitly defined, or the order is ambiguous (as in this case) – it will order rows arbitrarily and inconsistently. Since you happen to have multiple entries with the same Post Date, you should just override the entry query’s `orderBy` param to be a bit more specific:

```twig
{% set films = craft.entries({
  section: 'films',
  orderBy: 'postDate desc, elements.id asc'
}) %}
```

That will tell MySQL to order by Post Date first, but if two entries have the same one, to order those based on their IDs.

**Comment by narration-sd** [comment]
Just a little further clarity  -- this arbitrary ordering may and likely will happen with any relational database, 

The reason is that without the orderby in the query, you are just getting the result back as the records may be ordered internally, which could be by occasion entered, reordered by some efficiency action, etc.. 

This is the 'set' orientation of SQL -- the results are all there, all that's guaranteed without further instruction.
