### ISSUE TITLE
Entries Field within a Global not saving

### ISSUE THREAD

**Issue by himynameisphil** [craftcms/cms#2451]
### Description

When adding an entries field to a Global, it doesn't seem to save properly.

### Steps to reproduce

1. Create two sites (Site A and Site B).
2. Create a section that is only enabled for Site A.
3. Create at least one entry in the section.
4. Create an Entries field that relates entries from that section. (**Don’t** check the “Manage relations on a per-site basis” checkbox.)
5. Create a Global Set, and assign the Entries field to it.
6. Edit the Global Set for Site A, select an entry in the Entries field, and save it.

### Additional info

- Craft version: 3.0.0-RC10.1
- PHP version: 7.1.8

**Comment by brandonkelly** [comment]
I’m not able to reproduce. Can you please send an email to [suport@craftcms.com](mailto:support@craftcms.com?subject=Database%20backup%20for%20GitHub%20issue&body=GitHub%20issue%3A%20https%3A%2F%2Fgithub.com%2Fcraftcms%2Fcms%2Fissues%2F2451) with a database backup?

**Comment by brandonkelly** [comment]
OK I was able to reproduce this. It only occurs on multi-site installs, for relations that are not available in all of the sites. I just updated the initial post with a complete list of steps to reproduce.

**Comment by sckwebworks** [comment]
We're still experiencing this issue. Did a clean install, setup 3 sites and multiple global sets each with a entry field in it (the same field). Created a section with entries enabled in only 2 of the sites and created/linked entries within the global sets. Then saved the global sets from the third site (which doesn't have access to the section) this cleared the related entries.

**Comment by brandonkelly** [comment]
@sckwebworks Since you are relating to a section that’s not enabled for all sites, you should edit your Entries field, toggle the Advanced settings at the bottom, and check “Relate entries from a specific site?”, then choose a site that the section is enabled in.

(We’re planning on implementing #3584 in Craft 3.2, which will make it possible for relations to store the specific site that was selected at the time you created the relation.)
