### ISSUE TITLE
Multisite: debug toolbar only visible on primary site

### ISSUE THREAD

**Issue by mikegraham00** [craftcms/cms#2536]
### Description
The Yii debug toolbar is only visible on the front end of my primary site.

### Steps to reproduce

1. Enable debug toolbar on front end for current logged in user
2. Visit URL of any site other than primary.

### Additional info

- Craft version: 3.0.0-RC12
- PHP version: 7.1.1
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
It’s only available on sites you are logged into. If you want to enable it for additional domains, then you will just need to create a login form on each domain, so you can activate your user session.

**Comment by chasegiunta** [comment]
@brandonkelly Commenting here before I make an issue. Looks the debug toolbar also fails if I happen to be on a subdomain (not necessarily multisite). 

>Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://sub.domain.test' is therefore not allowed access. The response had HTTP status code 404.

Any thoughts on what I could I do on my end or is this something that could addressed in a future release?

**Comment by brandonkelly** [comment]
@chasegiunta What request are you seeing that on?

**Comment by chasegiunta** [comment]
@brandonkelly I get it on the OPTIONS request to `index.php?p=actions/debug/default/toolbar`. Will return a 404. I can actually open that URL it gives me in a new tab and I'm able see the content since I'm opening it directly on the correct domain. But trying to request it from my _subdomain_ won't work.

**Comment by chasegiunta** [comment]
No, but I am definitely doing some edge-casey stuff (wildcard subdomains - following your answer here https://craftcms.stackexchange.com/a/23734/3380). Just didn't know if this problem occurred in _normal_ subdomain instances (whatever those may be), and if there was a way around the CORS issue with unknown subdomains.

**Comment by brandonkelly** [comment]
OK yeah this is not a normal issue. It’s only happening to you because Craft doesn’t realize that a subdomain was requested in the first place, which is something you should be able to fix at the server level. Or you can configure your web server to send the correct CORS headers, so that it no longer matters if the Ajax requests are cross-domain.
