### ISSUE TITLE
FR: Add an event when saving in a Craft.ElementEditor hud

### ISSUE THREAD

**Issue by joshangell** [craftcms/cms#2689]
### Description
When saving in the `Craft.ElementEditor` hud it would be helpful for other JavaScript to be able know that that has happened.

For my current use-case I am building some more live preview tools that work inside a field type and whilst I can do similar things to the core `Craft.LivePreview` class in terms of regularly checking if field content has changed, I can’t do anything about updating my previews when someone clicks save in an element editor hud.

I have created a PR to illustrate the sort of behaviour I am after: #2688

### Steps to reproduce

1. Navigate to an entry with an element field attached
2. Select an element and save it on the field
3. Double-click the element once its on the field to edit, then press save

### Additional info

- Craft version: 2.6.3014
- PHP version: 7.1.x

**Comment by brandonkelly** [comment]
Solved this by adding support for [class-level event listeners](https://github.com/pixelandtonic/garnishjs/commit/f9e95a620b1a09e32df711d26a91b52280ad0f9f) to Garnish.

So now you can do this in your code:

```javascript
Garnish.on(Craft.BaseElementEditor, 'saveElement', callback);

// later, if you need to disable the event handler
Garnish.off(Craft.BaseElementEditor, 'saveElement', callback);
```

Make sure `callback` is the exact same function reference if you do in fact need to call `Garnish.off()` at some point.

I also updated the `Craft.LivePreview` class to use this method, rather than `Craft.BaseElementEditor` being the one to notify Live Preview when an element is saved: 6c52ddb949ec893cf7657567356717bfa7d1bb04

**Comment by joshangell** [comment]
Ah this is brilliant, works a treat - thank you Brandon.
