### ISSUE TITLE
Plugin::init() called before plugin Install migration is done

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#2700]
### Description

I’m getting the following error when installing my plugin
> Database Exception – yii\db\Exception
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'craft3.plugin_table' doesn't exist

There’s some code in my `Plugin::init()` that (for CP requests) queries a table created my Install migration.

Temporarily got around the issue using `isPluginInstalled()`, but I feel like this is something the installer could take care of.

```php
if (!Craft::$app->getPlugins()->isPluginInstalled('plugin-handle')) {
    return;
}
```

### Additional info

- Craft version: 3.0.0.2

**Comment by brandonkelly** [comment]
Technically your plugin installs itself, via its [install()](https://docs.craftcms.com/api/v3/craft-base-plugin.html#install()-detail) method, so this is expected behavior.

Rather than going through the Plugins service, you could just check the [$isInstalled](https://docs.craftcms.com/api/v3/craft-base-plugintrait.html#$isInstalled-detail) property on your plugin instance:

```php
if (!$this->isInstalled) {
    return;
}
```

**Comment by brandonkelly** [comment]
Nothing happens in `craft\base\Plugin::init()` that would break if the plugin isn’t installed, and if you are overriding it then yours will get called first anyway (and it’s up to your `init()` to even call `parent::init()` so it gets callled at all). So that wouldn’t help.
