### ISSUE TITLE
The removal of the 'Client' license

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/cms#2703]
Along with the release of Craft 3 the 'Client' license has been removed, leaving 'Solo' and 'Pro' as the only available licensing options. 

This has lead to a significant discussion on Slack based on whether or not the client license should have been removed, some people (including myself) have use-cases where the **only** project requirement that isn't satisfied by the solo license is the ability to create an account for the client. In my experience this is normally the case when we work with smaller clients and purchasing a pro license would be overkill.

I feel like there should still be some sort of middle ground where we can purchase something that gives us the ability to create an account for the client without having to pay for the additional pro features that won't be used. This could come in the form of a licensing option or as an official P&T plugin.

It would be great to hear the opinions of others on the matter.

**Comment by lindseydiloreto** [comment]
Paraphrasing from Slack (and echoing @lukeyouell)...

If it's possible for P&T to build a “Client User” plugin for $199, I think that would solve everyone's problems.

**Comment by lukeyouell** [comment]
@lindseydiloreto that's definitely the solution that makes the most sense to me, although I think it should cost a little less as it doesn't come with features such as system branding and custom email templates.

I think $100 would be a reasonable amount and hopefully entice those that use the Solo license to pay **something** in situations where they would normally stick with the free version.

**Comment by mildlygeeky** [comment]
I wonder if another possible compromise / middle ground may be making the Settings and Utilities pages less accessible on Solo edition — for example, some sort of overlay that makes a user tick a tickbox and then click a button to move into that section of the site. Could use a session cookie so that someone who intends to work in the admin section only has to hit it once per session.

I am personally glad to see the Client Edition gone — the price difference never seemed all that different from Pro, and whenever we've taken on a client who is on Client it seems like they have a negative opinion of Craft (sometimes because of Client, sometimes because the past agency cut other corners as well).

We've found that often other agencies were essentially looking to save $100 and just force their client to share passwords without knowing that Craft was capable of much more.

**Comment by bgarrant** [comment]
I have used Client for probably 30 mom and pop small sites.  It was a good price point and will be missed.  For people with no website or coming from WP it was great.  Many of these sites only needed one login as there was only one person making edits.

I understand the move to Pro.  It would have been nice to have these discussions before removing it.  While I appreciate the existing upgrades to Pro, that really is almost no benefit to the client projects already completed.

I think a "lite" version with just one non-admin user is a valuable version.  Sure you can scale it back, remove features, etc.  Most of these sites would not use multi-site or cloud storage so those don't really matter to me.

Just my $0.02

**Comment by marflow** [comment]
So I am not too happy to see that the Client editions has gone. It was a viable choice for smaller projects that needed one locale and one (branded ;) client login / account. 

Sure, $100 does not seem that much and in the end and worst case, we can decide for ourselves if we are willing to pay the difference because it will not only make the clients experience and safety that much better, but also make developing and maintenance much more productive, fun, and secure. But then again, the Craft license is one item, then there are plugins costs now, and then there are the update fees. (From my experience, a client with a project budget around 3.000 is willing to spend 350/year for quarterly updates in total. Higher costs / retainers are met with questions regarding the software quality, because those clients have no comparison.)

One thing to keep in mind as well: The smaller the client budget, the harder to compete with a WP / theme-based alternative. So it is also a question if P&T want to be a fit for those smaller sites as well. If you ask me, they should try.

**Comment by narration-sd** [comment]
I'm pretty much on the outside for this one, Brandon, but doing this on the allowUpdates model sure feels a center-of-concerns solution...

**Comment by lukeyouell** [comment]
@brandonkelly something like `allowAdmin` would be spot on!

**Comment by brandonkelly** [comment]
Just added a new `disableAdminFunctions` config setting to the `3.1` branch (8058b6c0b4c76b9c10476bf1cb169d6be497fd03).
