### ISSUE TITLE
Required Asset field fails validation even when non-empty

### ISSUE THREAD

**Issue by rungta** [craftcms/cms#2749]
### Description

A required asset field with an active asset element is failing with an `Craft\ContentModel->asset failed validation: Asset cannot be blank.` error when trying to re-save the entry from the console. 

First noticed this when queued jobs via the [Scheduler plugin][scheduler] started to fail. In order to isolate the issue, I tried to re-save a single entry via the [Walk plugin][walk] and that failed as well, with the same error message. If I removed the `required` condition on the asset field then the save operation would succeed. When I made the field required then the save operation would once again fail validation. The asset field's values had not been touched and had an asset at all times. Save operations on the same entries via the Control Panel do not throw any error.

### Steps to reproduce

1. Create an entry type with an asset field.
2. Select `Make required` for the asset field.
3. Add an entry of the type created in (1) and add an asset to the required field.
4. Save the entry.
5. Try to re-save the entry in (4) by calling `craft()->entries->saveEntry()` via the console.

### Additional info

- Craft version: 2.6.3015
- PHP version: 7.1.16
- Database driver & version: MySQL
- Plugins & versions: [Walk] 2.0.1

[walk]:https://github.com/TopShelfCraft/Walk
[scheduler]: https://github.com/supercool/Scheduler

**Comment by brandonkelly** [comment]
Yeah this is a known issue with Craft 2. For some field types, such as relational fields (e.g. Assets) and Matrix, you actually have to reconstruct the data in a way that the field type can understand, before calling `saveEntry()`. For example,

```php
$entry->setContentFromPost(array(
    'myAssetsField' => $entry->myAssetsField->ids(),
));
craft()->entries->saveEntry($entry);
```

It’s not an issue in Craft 3, due to tons of refactoring work, which unfortunately is not something we could possibly backport to Craft 2 without breaking several plugins.
