### ISSUE TITLE
Request: Task Manager

### ISSUE THREAD

**Issue by andrewfairlie** [craftcms/cms#2753]
### Description
As per a topic [on Twitter](https://twitter.com/simons1984/status/985887449456041985) I think it would be valuable if the utility section of the CMS allowed you to cancel tasks rather than having to delete them from the Database table.

**Comment by narration-sd** [comment]
Putting in a vote for this by thumb above, as it seems much a good idea.

There used to be a plugin for it on Craft 2, but in fact I'd gotten fingers pretty adept at clearing the tasks table manually, while bringing up something with kind of involved use of Task (Jobs now, converted).

As a Utilities function, you'd gain not just for development. Admins could clear a stuck site immediately, when/if this happens, do troubleshooting later or on staging. In fact, I build such UI abilities into the plugin, on top of a considering circumstances but automatic stuck-killer. Because you integrate...another frame of use.

If implementing, would suggest a kill-them-all ability as well as individual take-out. This would give the ability to  skip task which Craft knows are important to keep (or auto-restart them?). The same mechanism could intervene if you try to manually delete a special-handling task....

**Comment by brandonkelly** [comment]
We’ve added a new Queue Manager utility for Craft 3.4! This has completely replaced the queue HUD in the global sidebar – clicking on the active job there will just link you over to the utility (provided you have permission to access it).

![The Queue Manager utility in Craft 3.4](https://user-images.githubusercontent.com/47792/71934820-1c4f5400-315a-11ea-939e-2c1704739487.png)

![A job’s details view within the Queue Manager utility in Craft 3.4](https://user-images.githubusercontent.com/47792/71934931-63d5e000-315a-11ea-8c28-8dd6fced9c6e.png)

Special thanks to @gtettelaar for kickstarting this.

**Comment by bencroker** [comment]
> This has completely replaced the queue HUD in the global sidebar – clicking on the active job there will just link you over to the utility (provided you have permission to access it).

I'm loving the Task Manager so far, but does the queue HUD have to go completely? I realise that the actions may require permissions, but for (especially non-technical) users it is very helpful to see the current job summary (especially with the recent UI improvements) and what jobs are pending.

<img width="303" alt="Screenshot 2020-01-08 at 01 11 48" src="https://user-images.githubusercontent.com/57572400/71939821-3a49a280-31b4-11ea-9b68-434802a53d1b.png">

**Comment by brandonkelly** [comment]
Thinking maybe we’ll just start showing the job status text (“Warming 77 of 93 pages.”) in the sidebar below the main job description.

**Comment by bencroker** [comment]
Yeah that sounds reasonable. Then you don't need to worry about how a bloated HUD with 50 pending jobs in it appears.

**Comment by andrewfairlie** [comment]
Brilliant addition @brandonkelly and team!

**Comment by brandonkelly** [comment]
@bencroker Done now.

<img width="220" alt="An active job status in the sidebar" src="https://user-images.githubusercontent.com/47792/72069550-44df6700-329c-11ea-92da-dfe4641d1d99.png">

**Comment by narration-sd** [comment]
whole thing is great, @brandonkelly  - mention since @andrewfairlie did :)
