### ISSUE TITLE
Content of singles is not copied to other languages on first creation

### ISSUE THREAD

**Issue by buesing** [craftcms/cms#2777]
### Description

I have a multisite setup with 5 languages. English is the default language. When I add a new channel entry and fill in some fields in English, the content is copied into all the fields of all the different languages. Singles are missing this feature, if I add something into a field there, all other languages stay empty and require copy-pasting (if the translation is not ready yet).

### Steps to reproduce

1. Create a single section in a multisite setup
2. Add a field to the section
3. Go to entries, fill in the field
4. Switch language, field will still be empty

### Additional info

- Craft version: 3.0.1
- PHP version: 7.2.3
- Database driver & version: MYSQL 5.7.21
- Plugins & versions: -

**Comment by buesing** [comment]
A possible solution would be to add a button that copies the content from the current language into the fields of all other languages?

**Comment by brandonkelly** [comment]
@buesing This is expected behavior. The only times Craft will copy a field’s value from one site to another are:

- when the field’s Translation Method is set to “None”
- when a new site is enabled for the section

> A possible solution would be to add a button that copies the content from the current language into the fields of all other languages?

Yep, that’s planned for a future 3.x release. Already covered by issue #828 - feel free to add a 👍 reaction to that, so you can be notified when there’s activity on it :)
