### ISSUE TITLE
Selected site is not in-sync between Globals and other menu items

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#2779]
### Description
It would be nice if selected site would be consistent across CP pages. Works well across entries, categories and assets but not with Globals

### Steps to reproduce

1. Select one of the sites in Entries
2. Navigate to globals, notice that selected site is different

### Additional info

- Craft version: Craft Pro 3.0.1
- PHP version: 7.1.12
- Database driver & version: PostgreSQL 9.6.6
- Plugins & versions:

**Comment by richhayler** [comment]
Yes this can be a bit jarring when navigating from an entry for a selected site to globals and finding that the context is switched to the first site in the list instead of the selected site.

Would be great if the selected site could be maintained throughout navigating the CP interface and only changed when selecting a different site.

Would also be great if the selected site could be stored against the logged in user so when returning to the CP they can pick up where they left off.

**Comment by gregorterrill** [comment]
This is still an issue as of Craft 3.4.19.1 and can be very destructive. In Canada a lot of our sites are bilingual English/French and I've had several clients accidentally overwrite content in Globals for the wrong language because they didn't notice it had been switched on them when navigating from Entries to Globals. Please fix this!

**Comment by brandonkelly** [comment]
Just added this for the next 3.5 beta release!

**Comment by jsunsawyer** [comment]
I'm not sure if this is intentional or not, but switching the site within an entry does not save your desired site when going back to view all entries, globals, or anything else.

Would it make sense to make it so that any time a user switches the site, its setting persists?

**Comment by brandonkelly** [comment]
@jsunsawyer Can you post that as a new issue? Not really sure what the right behavior should be there.
