### ISSUE TITLE
Translatable General Settings

### ISSUE THREAD

**Issue by magnessjo** [craftcms/cms#2784]
### Description

I doubt there is a high use case scenario for this, but I would like to request making the general settings translatable by the different sites.  

My use case: I have a client who is managing 5 brands with one instance of Craft multi site manager.  They want to make their parent entity existence as obscure as possible. 

I looked into checking for the event 'EVENT_BEFORE_RENDER_TEMPLATE' in my module and possible rendering a template that I created rather than 'login.twig' so I could modify the site name and general name using the 'currentSite' properties (handle, name, etc), but that felt like a really really bad idea.  

### Additional info

- Craft version: Craft Pro 3.0.3.1
- PHP version:  7.0.19
- Database driver & version: MySQL 5.7.18
- Plugins & versions:

**Comment by brandonkelly** [comment]
What do you mean by “translatable”? What is the end result you’ve hoping for?

**Comment by brandonkelly** [comment]
Thanks, that makes sense. 

One limitation of Craft Multi-Site is that you still need to pick a single URL to access the Control Panel – otherwise you will start getting license validation errors. Considering that, I don’t think this FR would make sense, since (going with your example) the Beats CP login and the Apple CP login are one and the same.

**Comment by magnessjo** [comment]
@brandonkelly,

  That makes sense.  I never considered licensing while thinking over the problem.  Our goal is really just to obscure any reference to the parent company on the login page so we just changed the name to .... CraftCMS.  Now they get a double dose of craft branding.
