### ISSUE TITLE
Homepage EntryModel returns URI as __home__

### ISSUE THREAD

**Issue by evanwarner** [craftcms/cms#2795]
### Description
Calling `.uri` on an EntryModel always returns its correct full path, except for the homepage entry, which returns `__home__`. I think it would improve consistency for it to return an empty string. I can't think of a case where the special indicator that's currently returned would be more useful.

My use case: using root-relative URLs for my in-site links. I don't want to have to wrap every link to an entry in a macro that monitors for `__home__` and strips it.

I do realize I could just use `.url`, but a career-long use of root-relative (instead of absolute) URLs is hard to break.

**Comment by brandonkelly** [comment]
Craft uses `__home__` because it needs a way to distinguish between the homepage and an entry that doesn’t have a URI, and it’s expected that you’d generate URLs using `.url`.

You can still have root-relative URLs when using `.url` though – just go to your site’s settings and change the Base URL to `/`.
