### ISSUE TITLE
Bug: 'Author' not a reserved handle

### ISSUE THREAD

**Issue by andrewfairlie** [craftcms/cms#2797]
### Description
I think `author` is meant to be a reserved handle but isn't in 3.0.3.1

### Steps to reproduce

1. Create a new field "Author" (in my case it was an Entries field)
2. Use it in a template and it'll treat it like `craft\elements\User`

### Additional info

- Craft version: 3.0.3.1
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Yeah it’s a little awkward but since `author` is an entry-specific term, and fields are element agnostic, we decided not to prevent this. Someone might want to add an `author` field to assets or categories, etc., and that would be perfectly valid. Plus you can still access the field value on entries, via `entry.getFieldValue('author')`.

**Comment by angrybrad** [comment]
This will also be fixed when https://github.com/craftcms/cms/issues/1524 happens.

**Comment by brandonkelly** [comment]
Just got around to solving this for Craft 3.7:

- Category and tag groups no longer validate if their field layout contains a field called `group`.
- Entry types no longer validate if their field layout contains a field called `author`, `section`, or `type`.
- Volumes no longer validate if their field layout contains a field called `folder` or `volume`.
- The user field layout no longer validates if it contains a field called `groups` or `photo`.

<img width="1030" alt="A field layout designer on an entry type’s edit page, showing a validation error because “author” is a reserved word" src="https://user-images.githubusercontent.com/47792/121600281-19186180-c9f9-11eb-8e94-8a6cd5e444d7.png">
