### ISSUE TITLE
Matrix blocks don't appear correctly for Live Preview when using additional query parameters

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#2801]
I'm running into an issue where Matrix blocks aren't being shown - only in Live Preview - when used on a new (un-saved) entry, and using additional query parameters.

To unpack that, let we walk you through an example.

I have a Matrix Field with handle `matrixHeadingTest`, with a single Block Type with handle `heading` with a single Plain Text field with handle `headingText`. This is attached to a channel.

I create a new entry (without saving), and a single Matrix block, and don't enter any text in the plain text field. I open up Live Preview, with my template using the following code:

```
{{ entry.matrixHeadingTest.all() | length }}

{{ entry.matrixHeadingTest.type('heading').all() | length }}
```

The output is `1 0`, and have also attached the Live Preview screenshot to confirm.

![screen shot 2018-04-25 at 12 09 16 pm](https://user-images.githubusercontent.com/1221575/39222709-7e7a709c-4881-11e8-87ab-79a8bd34813d.png)

It seems that when including additional query parameters, the block query fails to return correctly? Removing this (as shown on the first output) works as expected

Now all of the above works fine once the entry is saved and Live Preview is run again - or if saved and viewed from the front-end of the site. Just seems to be before the entry is saved.

Any thoughts?

### Additional info

- Craft version: Craft CMS 3.0.3.1 Pro
- PHP version: 7.0.15

**Comment by carlcs** [comment]
@engram-design there is a post on StackExchange with an answer for how to work around the problem in Craft 2. But yes, it would be nice if it would just work.

https://craftcms.stackexchange.com/questions/8879/issue-with-matrix-type-property-and-live-preview

**Comment by brandonkelly** [comment]
Just added a Craft 3 code example to that Stack Exchange answer. Agree it would be nicer if it just worked, so leaving this open.

**Comment by engram-design** [comment]
@carlcs Cool, hadn't come across that, and thanks @brandonkelly for the consideration.

**Comment by brandonkelly** [comment]
@jonlongnecker Yeah same basic issue. Any time you add parameters to a Matrix block query, it will ignore its pre-cached blocks (the ones based on Live Preview data) and execute a new database query.

To fix you’d need to do something like this:

```twig
{% if craft.app.request.isLivePreview %}
    {% set firstGallery = entry.productVariants.all()[0:1] %}
    {% set offsetGallery = entry.productVariants).all()[1:100] %}
{% else %}
    {% set firstGallery = clone(entry.productVariants).limit(1).all() %}
    {% set offsetGallery = clone(entry.productVariants).offset(1).limit(100).all() %}
{% endif %}
```

Then update your for-loops to just:

```twig
{% for block in firstGallery %}
```

and

```twig
{% for block in offsetGallery %}
```

**Comment by jonlongnecker** [comment]
@brandonkelly Thanks, that made it work (had to get rid of that stray ) after the second entry.productVariants).

I guess I'm having trouble understanding what that syntax is and how why it's different even though it's producing the same kinds of results.

**Comment by brandonkelly** [comment]
The key to understanding it is to know that on Live Preview requests, relational and Matrix fields’ values (which are [element queries](https://docs.craftcms.com/v3/dev/element-queries)) are pre-loaded with their results, based on the posted Live Preview data. Which is why looping through `entry.productVariants.all()` will give you blocks with content based on what you’re typing in Live Preview, rather than what’s already saved in the database.

But as soon as you start adding parameters onto the element query, the element query will discard its pre-loaded results and execute a SQL query.

Here’s the relevant code:

https://github.com/craftcms/cms/blob/0e875dcd85c624a2718aaa0315f6f6eef2999067/src/elements/db/ElementQuery.php#L1162-L1170

https://github.com/craftcms/cms/blob/0e875dcd85c624a2718aaa0315f6f6eef2999067/src/elements/db/ElementQuery.php#L1236-L1249

So looking at your template code, both of these lines basically do the same thing:

```twig
{% set firstGallery = entry.productVariants.all()[0:1] %}
```
and
```twig
{% set firstGallery = clone(entry.productVariants).limit(1).all() %}
```

They both define a `firstGallery` variable set to an array with the first Product Variant block.

They do it in different ways, though.

The first one calls `.all()` immediately – getting the full (pre-loaded, in this case) block results. Then it uses the [slice filter](https://twig.symfony.com/doc/2.x/filters/slice.html) (shortcut syntax) to limit it to just the first block.

The second one sets the [limit](https://docs.craftcms.com/v3/dev/element-queries/matrix-block-queries.html#limit) parameter on the query, so that only at most one block will be returned by the query, and then calls `all()` to get its results array.

Had the `limit` parameter been set for a Live Preview request, then the pre-loaded results would have been discarded, and you would be stuck with whatever content is already in the database.

Technically, the first approach (loading all blocks and then using the `slice` filter to just get the first one) would work for non-Live Preview requests, too, but it would come with a performance hit. It’s always best to only load what you actually need when making database queries.

**Comment by carlcs** [comment]
@brandonkelly is this issue addressed by Live Preview updates in 3.2?

**Comment by brandonkelly** [comment]
Yep! Sorry forgot to tag this one but it’s fundamentally the same issue as #1787.

**Comment by carlcs** [comment]
Seems like it is 😍

**Comment by carlcs** [comment]
Despite loving Ajax/SPA support and multiple targets, no more conditional coding for live preview requests is my favorite change. Thanks for your fantastic work, @brandonkelly!
