### ISSUE TITLE
Downgrade Craft from PHP 7.1 to PHP 7.0

### ISSUE THREAD

**Issue by martinhellwagner** [craftcms/cms#2805]
I was wondering if it's possible to sort of "downgrade" Craft from PHP 7.1 to PHP 7.0. We've installed Craft on our stage environment with PHP 7.1, but need to run it on a production environment with PHP 7.0.

Everything works fine so far, but when wanting to submit the Freeform Lite plugin, Symfony errors out because it's trying to use nullable types (a PHP 7.1-specific feature). One example is in _vendor/symfony/Process.php_ in line 139:

`public function __construct($commandline, string $cwd = null, array $env = null, $input = null, ?float $timeout = 60)`

**Comment by brandonkelly** [comment]
Definitely possible. Your error is probably because the last time Composer was run, it was on an environment running PHP 7.1, so it grabbed dependencies that are PHP 7.1-compatible.

New Craft projects [explicitly configure Composer](https://github.com/craftcms/craft/blob/4803046098e8d2c0ee29e84c2882e8619a33d0f7/composer.json#L32-L34) to only use dependencies that are compatible with PHP 7.0, regardless of what the server is actually running, to avoid this sort of thing. You can get Composer to do the same thing for your project by adding the same `platform` config setting to your `composer.json`, and then run `composer update`.

**Comment by martinhellwagner** [comment]
That did the trick! Thank you very much!
