### ISSUE TITLE
Asset uploaded via asset modal are not selected if file name is not visible

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#2812]
### Description
Assets uploaded via the asset modal aren't selected if their file name would be positioned in a way that it would need to be scrolled to. The uploaded asset should always be selected, regardless of the users' sort order.

### Steps to reproduce

[Requires that enough assets exist in a volume to require scrolling in the asset modal.]

1. Click Add Image on an asset field.
2. Sort assets by File Modified Date (oldest first – to replicate issue).
3. Upload an image.

### Additional info

- Craft version: 3.0.4

**Comment by brandonkelly** [comment]
@andris-sevcenko I think to fix this, when a new file is uploaded, we should automatically change the index to be sorted by Date Uploaded - Descending, so that we can be sure that the newly-uploaded asset will be selected.

If that means that previously-selected assets might lose their selection if they go out of view, so be it; preference should be given to the newly-uploaded asset(s).
