### ISSUE TITLE
currentSite may not get set properly when Sites are setup using subdomains (instead of subfolders)

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#2849]
### Description

I'm not sure if I'm missing something or if this is a bug. But it appears that the `currentSite` variable may always get set to the default site when Sites are setup with subdomains instead of subfolders.

Two sites with Base URLs as subfolders work fine:

- website.com
- website.com/two

Two sites with Base URLs as subdomains don't behave as expected:

- website.com
- two.website.com

I believe the issue is happening in the `_getCurrentSite` method of the Request class:
https://github.com/craftcms/cms/blob/develop/src/web/Request.php#L957

It appears the score of the primary site always wins by one because both the primary domain and subdomain score the same on the $parsedPath value (as it's the base domain that is making the two URLs unique).

### Steps to reproduce

1. Create a default site: `whatever.dev`
2. Create a second site with a subdomain: `subdomain.whatever.dev`
3. Output `currentSite.handle` when loading both sites and see that they will always be the default handle

### Additional info

- Craft version: 3.0.5
- PHP version: 7.1
- Database driver & version: MySQL
- Plugins & versions: various under local dev

**Comment by brandonkelly** [comment]
If the requested host name doesn’t exactly match the host name in the site’s Base URL, then the site isn’t going to get scored in the first place. The only way the primary site would be used when its host name wasn’t explicitly requested is if Craft couldn't find any other site matches.

So I think the problem is going to be one of these:

- your subdomain site’s Base URL doesn’t actually include the subdomain
- your primary site’s Base URL starts with `@web/`

If the former, then the suddomain site won’t be an option.

If the latter, then realize that `@web` will get converted to whatever the requested base URL is, making it pretty much useless in multi-site setups, as it will make your primary site also apply to subdomain requests.

**Comment by brandonkelly** [comment]
Another thing to double check - make sure your index.php file isn’t setting the `CRAFT_SITE` or `CRAFT_LOCALE` constant.

**Comment by BenParizek** [comment]
Thanks for the clarification. I think we were getting tripped up by the `your primary site’s Base URL starts with @web/` scenario.

**Comment by KatieMFritz** [comment]
Oh my gosh, I was setting `CRAFT_SITE` in my `web/index.php` from the previous configuration. I've been trying to figure this out all week. Could you please update the docs to mention this, for other people who set up multisite with different `web` folders and now need to change?

**Comment by brandonkelly** [comment]
@KatieMFritz Done, thanks for the nudge, and sorry it tripped you up.
