### ISSUE TITLE
Craft upgrade lost font in control panel?

### ISSUE THREAD

**Issue by PanMan** [craftcms/cms#2879]
### Description
Hi!
I just upgraded our Craft 3 instance from Craft 3 RC2 to 3.0.7. Now the control pannel switched from a sans-serif font to a serif font?
Eg, compare these 2:

Before:
![image](https://user-images.githubusercontent.com/978501/39968696-85c94428-56d1-11e8-9f9b-f5fcc99bcfa1.png)
After:

![image](https://user-images.githubusercontent.com/978501/39968692-7751a41c-56d1-11e8-8689-cc7721d2f3a9.png)

I don't see any network errors, so it doesn't seem to be a non-loading font? Is this on purpose? I don't see anything in the changelog

### Steps to reproduce

1. Upgrade to craft 3.0.7

### Additional info
Not a mega breaking issue, as it doesn't affect our main site, and the control pannel does work, but seems to be less beautifull

**Comment by brandonkelly** [comment]
Weird, that is definitely not intentional. Is it the entire Control Panel or just the sidebar?

Do you have any custom CP styles defined? Try inspecting the text and filtering its CSS styles with `font-family`. Anything showing up?

<img width="377" alt="screen shot 2018-05-14 at 2 10 27 pm" src="https://user-images.githubusercontent.com/47792/40023632-96310ed6-5780-11e8-837d-c93350762121.png">

**Comment by PanMan** [comment]
Sorry, this is totally my fault :(. I thought we only had one style rule, which only changed one color, but we were also including a custom CSS file with more rules. I did see in the changelog how custom CSS is handled has changed, but since I thought we only had one rule, I thought this didn't apply. But disabling the custom styles fixes it, so it's my fault. Sorry for bothering you.

**Comment by brandonkelly** [comment]
Hah, no worries, glad you tracked it down!
