### ISSUE TITLE
Craftcms is not deleting users.

### ISSUE THREAD

**Issue by aliPunch** [craftcms/cms#2890]
### Description
I have tried to delete users from multiple installation of craft all are above 3.0.5 but its not able to delete users

### Steps to reproduce

1. Login with admin account
2. goto users section
3. Try deleting users

### Additional info

- Craft version: > 3.0.5
- PHP version: 7+
- Database driver & version: postgresql latest

**Comment by brandonkelly** [comment]
Not able to reproduce this locally. Usually when this sort of thing happens, it’s because Craft was installed/deployed on an environment where the database server doesn’t support foreign key constraints. Try installing the “Fix FKs” plugin in the plugin store, and then go to Utilities → Fix FKs, and run it.

If that doensn’t help, please send a database backup to support@craftcms.com.
