### ISSUE TITLE
Link to entry does not store locale in rich text editor (redactor)

### ISSUE THREAD

**Issue by jurriaanr** [craftcms/cms#2945]
### Description

When adding a link to entry  to a redactor rich text editor field, the locale of the selected entry is not saved. Only the id of the entry is saved and when it is shown in template or in the editor on reload it will show the url with the default locale set up in craft. I believe that it can be solved by saving the locale together with the id. {entry:5022:url} => {entry:5022:nl:url}

### Steps to reproduce

1. Clean install of craft 2 with 2 locales (english as default and dutch f.e.)
2. Add RTE field that is translatable and configured to allow link
3. Add a link to entry
4. select another entry with the dutch locale
5. save field
6. reload page

The link will now point to the english url, instead of the dutch.
Used in code, the url in the textfield content will again point to the english version

### Additional info

- Craft version: 2.6.3015
- PHP version: all versions
- Database driver & version: all versions
- Plugins & versions: clean install

Related to this craft 3 issue #https://github.com/craftcms/cms/issues/2006

**Comment by brandonkelly** [comment]
Entry URLs in Rich Text fields get saved as [reference tags](https://docs.craftcms.com/v2/reference-tags.html) (so that the URL stayl up-to-date when the entry’s URL changes), but reference tags aren’t currently localizalbe.

So to fix this we’d first need to make reference tags localizable. I just posted a new FR for that (#2956).

**Comment by brandonkelly** [comment]
This was resolved in Craft 3.2 + Redactor 2.5.
