### ISSUE TITLE
Creating a 2nd new entry from in a "select entries" modal fails when entry url format uses {id}

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#2950]
### Description
We have an entry type called **External Links** that we use to manage translated URLs for a localized site. These entries are set up to use the **Entry URL Format** `link/{id}`.

### Steps to reproduce

1. Create a section (structure) with **Entry URL Format** `link/{id}`.
2. Create a new entry from an entry modal in a redactor field link or entry field on a post.
3. Create another new entry before saving or reloading the current post.

### Additional info

What seems to be happening is that the full URL is not set at the point of creation. The URL shows `link` for the first item created this way, while other entries of this section show `link/12345` (as an example). I think that the 2nd entry doesn't want to save because it would use the same URL as the first one created.

- Craft version: 3.0.9
- PHP version: 7.1.18
- Database driver & version: MySQL 5.7.22

**Comment by brandonkelly** [comment]
I have a feeling this was fixed by 5f038f44564921b5f3d07d5e1a900fc6e4f6df2b (#2922). Can you try updating to the latest on the `develop` branch and see if it works as expected?

To do that, change your `craftcms/cms` version requirement in composer.json to `"dev-develop as 3.0.9"`, and then run `composer update`.

**Comment by jsunsawyer** [comment]
@brandonkelly Works! Thanks so much.
