### ISSUE TITLE
Redactor icons disappear when selecting entry from Entries field

### ISSUE THREAD

**Issue by steveooo9** [craftcms/cms#2978]
### Steps to reproduce

1. Add a Redactor field
2. Add a Entries field
3. Add entry and select entry from Entries field
4. After that, the icons disappear in Redactor editor

### Additional info

- Craft version: 2.6.3016
- PHP version: 7.1

<img width="555" alt="icon" src="https://user-images.githubusercontent.com/27959355/41228528-f830517e-6d78-11e8-814a-a55454775601.png">

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. Do you have any plugins installed?

**Comment by steveooo9** [comment]
No. This only happens when I select an entry or something that uses AJAX to load.

**Comment by brandonkelly** [comment]
Yeah I tried that, per your instructions.

@andris-sevcenko can you try reproducing this when you have a chance?

**Comment by andris-sevcenko** [comment]
@brandonkelly unable to reproduce either.

@steveooo9 Does this happen in every browser?

**Comment by steveooo9** [comment]
@andris-sevcenko Yes, tested on latest Chrome + Firefox for Mac.

What's the best way to share some access to our dev environment to see for yourself? Email?

**Comment by andris-sevcenko** [comment]
Probably, yeah. by sending that to support@craftcms.com

**Comment by steveooo9** [comment]
@andris-sevcenko I sent an email called "Access of #2978". If you have any further questions, don't hesitate to ask!

**Comment by steveooo9** [comment]
@andris-sevcenko Any time testing? The access we gave you will expire soon because we need the dev environment for an updated version of our project :)

**Comment by angrybrad** [comment]
@steveooo9 @andris-sevcenko is off on vacation, but will take a stab at this tomorrow!

**Comment by angrybrad** [comment]
@steveooo9 In the site you gave us access to, it looks like this is the context of a [Neo field](https://github.com/benjamminf/craft-neo) - can't verify that 100% because it isn't an admin account.

 Are you able to reproduce this outside of Neo?

Even if your original screenshot, it looks like other plugins might be involved.

![capture](https://user-images.githubusercontent.com/61869/41879593-26303c30-788f-11e8-8a1b-0abdeb19c0fc.PNG)

Can you reproduce this with no plugins installed?  If not, then you can at least start to re-enable them one at a time to see when the issue comes back to try and narrow things down.

**Comment by steveooo9** [comment]
Sorry, was an issue on my side.
