### ISSUE TITLE
Getting Empty results when filtering by ':notempty:' on an assets field

### ISSUE THREAD

**Issue by keithmancuso** [craftcms/cms#2993]
### Description

For some reason

```twig
{% set artists = craft.users.group('artistMembers').artwork(':notempty:').all() %}
```

returns artists where their artwork field is blank

### Additional info

- Craft version: 3.0.11
- PHP version: 7.2
- Database driver & version: Mysql
- Plugins & versions: Embedded Assets but i dont think thats related?

**Comment by brandonkelly** [comment]
I’m not able to reproduce this – both `:empty:` and `:notempty:` are working as expected for me on user queries + assets fields.

Can you send a DB backup and your composer.json + composer.lock files to support@craftcms.com ?

**Comment by Saboteur777** [comment]
In case anyone stumbles into this: I experienced an issue like this. 

While refreshing the Asset Indexes some assets were not found, so I let the asset indexer remove them. One of the asset was set as an `assetField` "value", the entry showed up when querying with `.assetField(':notempty:')`. Resaving that entry fixed the issue, probably because as it's `assetField` value was resaved.
