### ISSUE TITLE
Integrity constrant violation happens when saving fields

### ISSUE THREAD

**Issue by cstudios-slovakia** [craftcms/cms#3015]
### Description

This issue is quite uniqe, i recall we migrated from craft 2 to craft 3, then we've started to get these strange errors.
If someone would experience the same issues, then here is our solution yet.

Here is the error: [https://imgur.com/a/07aQfT9](https://imgur.com/a/07aQfT9)

### Temporary solution
Open craft\vendor\craftcms\cms\src\services\Fields.php
Around **line 1232** you should see this

`$fieldRecord = new FieldLayoutFieldRecord();`

Replace that with the following code

```
$fieldRecord = FieldLayoutFieldRecord::findOne(array(
   "layoutId"=>$layout->id,
   "fieldId"=>$field->id
));
if(!isset($fieldRecord)) $fieldRecord = new FieldLayoutFieldRecord();
```
What this does, is searching for an existing FieldLayoutField, and if one is found, then the data from $_POST is going to update the record's entry.
If it's a completely new record then legacy code runs.

**Comment by brandonkelly** [comment]
Looks like the Fields service has changed quite a bit since your version, judging from the bits of it I can see in your stack trace. Can you please make sure you’re running the latest version of Craft?

**Comment by cstudios-slovakia** [comment]
We are currently using Craft v3.0.12

**Comment by brandonkelly** [comment]
The code you referred to is on [line 1246](https://github.com/craftcms/cms/blob/3.0.12/src/services/Fields.php#L1246) in Craft  3.0.12, not 1232, which makes me suspicious that you’ve made custom changes to the source code, or Craft didn’t successfully update to 3.0.12 in full. Can you try updating  to the latest version?

**Comment by auralon** [comment]
I've just submitted a support request with trace and dump. It looks like I'm experiencing the same issue.

**Comment by auralon** [comment]
I can also confirm that the temporary solution given above does fix the issue for me.

**Comment by brandonkelly** [comment]
Looked through the code and the proposed change, and I think I understand what’s going on.

Before that `$fieldRecord = new FieldLayoutFieldRecord();` line is executed, the method will delete all existing tabs for the field layout:

https://github.com/craftcms/cms/blob/60ff090e4c4dbd3eccf8cbeacb4a25a07e73104d/src/services/Fields.php#L1209-L1213

That query _should_ also result in all the associated `fieldlayoutfields` rows getting deleted  as well, as they _should_ have foreign keys to the  `fieldlayouttabs` table, with `ON DELETE CASCADE`, which tells MySQL to automatically delete them when their referenced `fieldlayouttabs` row is deleted. In your  case, it sounds like that’s not happening, which  probably means that the foreign key got deleted somehow.

Foreign keys can go missing if Craft was ever deployed to an older MySQL environment that doesn’t support FKs. It happens from  time to time, which is why we built the [Fix FKs](https://github.com/craftcms/fix-fks) plugin. Search for that in the Plugin Store, install it, and then go to Utilities → Fix FKs and run it. You should stop getting these errors (unless you’re still running Craft on an older MySQL version).

Also make sure you undo the change you made to Fields.php. That will have negative side effects once you get your FKs restored.

**Comment by auralon** [comment]
@brandonkelly that seems odd, considering we have dozens of sites (Craft 2 and Craft 3) on this server (same LAMP config) without issue, this has only become a problem with this build of Craft 3.  I'll try running the Fix FKs plugin, but I have reservations as to whether this is the root of the problem!  This version of MySQL Server (5.6.33-0ubuntu0.14.04.1) has never posed a problem before with foreign keys (AFAIK).

**Comment by auralon** [comment]
Well, that seems to have worked, so I doff my cap to thee sir.  Thank you! :)

**Comment by brandonkelly** [comment]
Hah, glad that worked!

**Comment by cstudios-slovakia** [comment]
We can confirm that Fix FKs resolved our problem. Thank you!
