### ISSUE TITLE
Normalizing keywords for search index uses wrong language

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#3046]
### Description

The keywords for the search index are obviousliy built depending on the current users cp language. That should use the language of the site the entry is in.

Using Craft::$app->language in craft\helpers\Search

### Steps to reproduce

1. Create an entry with a title like 'Zauberflöte' on a site with language = german
2. Saved by an author with cp language = en, the search index will contain 'zauberflote'. The entry will not  be found by a search for 'Zauberflöte' on a german site.
3. Saved by an author with cp language = de, the search index will contain 'zauberfloete'. Now it can be found.

### Additional info

- Craft version: 3.0.13.2
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. I created a Craft install with two sites (EN and DE) with EN being the primary. Then created a section enabled for both sites, and created a new entry with DE selected, title = “Zauberflöte”. As expected the entry will show up in search results for “Zauberflöte” regardless of which site is selected.

Here is the `searchkeywords` table for the entry:

<img width="364" alt="screen shot 2018-06-29 at 7 26 59 pm" src="https://user-images.githubusercontent.com/47792/42120098-b3f58b42-7bd2-11e8-9acf-1a5b132a3f36.png">

Let me know if you can think of any other variables that could be affecting  this on your site. If  you’re not sure, please send your `composer.json`, `composer.lock`, and a database backup to support@craftcms.com, and tell us which section the bug is occurring on.

**Comment by wsydney76** [comment]
Thanks, but that's not the use case i tried to describe, sorry that my description was misleading.

It's about the language the author selected for his personal use in the backend.

So, if a user has this preferences: 

![image](https://user-images.githubusercontent.com/25308802/42122606-8f043820-7c44-11e8-959e-f937aa93035e.png)

and saves the item, the table shows:

![image](https://user-images.githubusercontent.com/25308802/42122748-ff524fc0-7c46-11e8-963c-37eeb1e94d63.png)


If you change the preferences to this:

![image](https://user-images.githubusercontent.com/25308802/42122650-2574f452-7c45-11e8-8165-48be19c38af2.png)

and resave the entry, the table content is:

![image](https://user-images.githubusercontent.com/25308802/42122779-58db9ba0-7c47-11e8-9ba5-eb60369e9170.png)


and that is what works with this search in the german site:

![image](https://user-images.githubusercontent.com/25308802/42122713-6ea78594-7c46-11e8-9d74-d72b7b0fa88c.png)

In helpers/Search.php line 88 there is 
`// This will replace accented chars with non-accented chars`
`$map = StringHelper::asciiCharMap(true, Craft::$app->language);`

where, if i don't get it wrong, `$app->language` is the language the cp is currently running in, and not the language of the site the entry belongs to.

I could find a temporary workaround with some configuration settings

`'customAsciiCharMappingss' => [
            'a' => ['ä', 'Ä'],
            'o' => ['ö', 'Ö'],
            'u' => ['ü', 'Ü'],
            's' => ['ß']
        ],`

but there might be some unwanted side effects (?), and it's deprecated anyway.

Thanks again for your efforts, the multilingual feature was one of the main reasons our clients switched from another wellknown CMS to Craft.

**Comment by brandonkelly** [comment]
Sorry, I missed the `oe` in `zauberfloete`. I’m following the issue now – will look into it.

**Comment by wsydney76** [comment]
Works now. Thanks for the quick fix.
