### ISSUE TITLE
Matrix with 30 block types will not allow creation of new block types

### ISSUE THREAD

**Issue by jolyonruss** [craftcms/cms#3114]
### Description
We have a large Matrix with ~30 block types defined each with various fields. When we try to create block type 31 and hit save we get the following error:

```
Internal Server Error
Server Error
```

After deleting block type 30 in order to try verify there was a limit to the number of block types - we were able to create 1 more block type, but not another block type 31.

### Steps to reproduce

1. Create 30 blocks
2. Try creating 1 more block 

### Additional info

- Craft version: 3.0.15
- PHP version: 7
- Database driver & version: MySQL
- Plugins & versions: Elements Api, Amazon S3, Preparse Field, Redactor

**Comment by msimpson** [comment]
@jolyonruss 
Just throwing this out there, but could this be related to either `post_max_size` or `upload_max_filesize` in your `php.ini`?

**Comment by jolyonruss** [comment]
Just edited to clarify this is about block types in `/settings/fields` not blocks in a post

**Comment by brandonkelly** [comment]
Most likely going to be due to PHP’s [max_input_vars](http://php.net/manual/en/info.configuration.php#ini.max-input-vars) php.ini setting. Can you try increasing that?

**Comment by andris-sevcenko** [comment]
@astronauta88 it's not that "30 matrix blocks are okay, 31 is not". It depends on how many fields you have per matrix block as well as any other fields on that same page. It's just that Matrix fields use a lot of input variables, so they're usually the ones to trigger this limit.

**Comment by brandonkelly** [comment]
Craft does its best to detect if too many input vars were submitted (21d13d4b053bd45e25082ac0e10baba4ea39c9a0) and immediately end the request with an error, which gives you a chance to tweak the server config and then reload your browser. Unfortuantely that’s the best we can do for now, as we don’t have access to any of the parameters that were cut off by PHP.

In the long run we will switch to submitting forms as JSON rather than URL-encoded vars, which will sidestep the issue, but that will take some doing.
