### ISSUE TITLE
Integrity constraint violation 1062 after updating to Craft 3

### ISSUE THREAD

**Issue by farrellScript** [craftcms/cms#3134]
### Description
Updated Craft 2.6.3019 to 3.0.16.1 using the 'Updating from Craft 2' instructions. Now when trying to add a field to a section (whether it existed before the update or not) I'm getting an error.

```SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2765-436' for key 'craft_fieldlayoutfields_layoutId_fieldId_unq_idx'```

### Steps to reproduce

1. Updated Craft 2.6.3019 to 3.0.16.1 following the Upgrading from Craft 2 instructions
2. Create a new section and add a field to that section
3. Try to edit that section, add a new field, and save

### Additional info

- Craft version: 3.0.16.1
- PHP version: 7.0.12
- Database driver & version: 5.6.34

**Comment by angrybrad** [comment]
Can you send a Craft 2 pre-update attempt database backup to support@craftcms.com so we can try to reproduce?

**Comment by angrybrad** [comment]
Looks like this is due to some missing foreign key constraints allowing some data inconsistently between tables in Craft.

After doing the Craft 3 update, go to the Plugin Store, install the "Fix FKs" plugin, go to Utilities->Fix FKs and click the "Restore Foreign Keys" button.  It'll put the FKs back in place and attempt to clean any orphaned data in your tables.

After I did that, I was able to successfully save fields to sections.
