### ISSUE TITLE
Structure In Unusable State

### ISSUE THREAD

**Issue by mattcdavis1** [craftcms/cms#3148]
### Description
At some point our structure has devolved into an unusable state. Reassigning an entry to a different parent doesn't work. Items show up under two parents at the same time.  Expanding contracting doesn't work. Chunks of hierarchy are missing.  [See screenshot](https://goo.gl/bTRxRX).

Also, [here is a screenshot](https://goo.gl/9s3My2) of an error i received when trying to remove a parent (to set element back to 
the root of the structure)

### Steps to reproduce

Still trying to figure this out. Structures in other areas of the CMS are working ok.  Possibly related to depth?

### Additional info

- Craft version: Craft Pro 3.0.17
- PHP version: 7.2.7
- Database driver & version: MySQL 5.7.22

**Comment by mattcdavis1** [comment]
Comparing with another area of the CMS where the structures are working, it looks like folding up items should not trigger an ajax call for `get-more-elements` but in the broken structure folding and unfolding both generate ajax calls form `get-more-elements`

**Comment by brandonkelly** [comment]
Can you send a database backup to support@craftcms.com ? We can look into it from there.

**Comment by brandonkelly** [comment]
@jcherniak I just added a `mutexTimeout` property to the Structures service class. Your queue jobs can either set this on the `Craft::$app->structures` singleton, or instantiate their own instances, with a custom `mutexTimeout` property.

It’s set to `0` by default, so there’s no change in behavior by default here. There’s no sense in giving it a timeout by default, because the structure UI isn’t collaborative. So if there’s a scenario where the structure is already locked, then one/both of the users are likely viewing inaccurate structure views.

**Comment by jcherniak** [comment]
@brandonkelly Thanks for the amazingly quick resolution here!

**Comment by jcherniak** [comment]
So looking into this further, it seems that Craft uses a yii\mutex\FileMutex.  This doesn't work across load-balanced or worker-queue hosts.  Any thoughts about using a DbMutex instead?
