### ISSUE TITLE
Debug toolbar gets cached when </body> is within {% cache %} tag.

### ISSUE THREAD

**Issue by souvikdg** [craftcms/cms#3157]
### Description

When `</body>` is within a `{% cache %}` tag, the debug toolbar gets cached as well. Ideally, the debug toolbar should be inserted when the final twig template is being rendered (post-retrieving from cached page).

### Steps to reproduce

1. Turn on debug toolbar.
2. Add a full page cache tag with `</body>` inside `{% cache %}`
3. Load the page on the browser. The second refresh onwards the cached toolbar will be rendered.

### Additional info

- Craft version: 3.0.17.1
- PHP version: 7.1

**Comment by rungta** [comment]
Our template structure currently extends a `_layouts/base` which has the `html`, `head` and `body` tags. The `_layouts/base` in turn extends a `_layouts/init` template which has no HTML tags but sets up a bunch of variables, handles the full page caching (because we do have dynamic things going on in the opening `html` and certainly in the `head` tags), HTML minification etc. We want to cache the entire page, ideally.

We’d assumed Craft would be looking for a `</body>` in the _final_ output of the primary template call, but it appears that it is doing this for every intermediate template that it encounters and inserting the toolbar as soon as `</body>` is emitted. (Right?)

**Comment by brandonkelly** [comment]
The Debug toolbar JS will be output by the [endBody()](https://docs.craftcms.com/v3/dev/functions.html#endbody) template function along with any other JS code that’s queued up at that position. If your template doesn’t have an `endBody()` function then one will be added for you right before the `</body>` tag.

So one approach you could try is to just manually add a `{{ endBody() }}` tag from your `init` template, after the `{% endcache %}` tag.

**Comment by brandonkelly** [comment]
That wil only work if you aren’t relying on other JS scripts to be cached though.
