### ISSUE TITLE
Search & replace: search inside links & give feedback

### ISSUE THREAD

**Issue by jkorff** [craftcms/cms#3321]
### Description
When using the Find & Replace tool it appears it cannot find strings within links. I wanted to replace "/resources/books/anthologies/" with "/resources/books/".

I also like to suggest to update the tool to report back what it did, or couldn't do, e.g.:
"Updated 15 entries."
"Found no entries matching your search."

Presently it just does its thing, but I don't know what happened or how many entries have been changed.

### Steps to reproduce

1. Utilities > Find and Replace
2. Try to search for link URLs

### Additional info

- Craft version: 3.0.21
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by jkorff** [comment]
That was a Redactor field within a Matrix.

**Comment by brandonkelly** [comment]
Yeah @andris-sevcenko has a point, @jkorff. Redactor saves entry/category/asset URLs as [reference tags](https://docs.craftcms.com/v3/reference-tags.html) (e.g. `{entry:123}`) rather than full URLs. That way the resulting URLs will always be updated based on the actual entry/category/asset URLs, if they change over time – no Find And Replace action needed.

**Comment by jkorff** [comment]
I wasn't using Redactor's links. This was EE content that I'd imported into the Redactor field, so it was plain HTML.

**Comment by brandonkelly** [comment]
@jkorff Hm in that case it should have worked. Can you send me a database backup, plus your `composer.json` and `composer.lock` files over to support@craftcms.com, and tell me which Matrix/Redactor field it’s not working on?
