### ISSUE TITLE
Rename Deprecation Errors => Deprecation Warnings (or at least clarify to non-developer users what they intend to communicate)

### ISSUE THREAD

**Issue by BenParizek** [craftcms/cms#3357]
During times of transition, we consistently get support requests from users who place too much emphasis on Deprecation Errors, seeing them as a potential source for a problem they are trying to troubleshoot.

These "Errors" are meant to be informational. In some cases, users can act on them, in other cases, they just communicate to plugin developers that they should plan for a change in the future – often times very far in the future.

Right now, the naming of these warnings confuse users who don't understand what they are and often trick users into thinking that they could be the source of a potential problem a user is trying to troubleshoot. Some users also perceive a higher number of Deprecation errors as a source of panic, where often it could just mean that a single file with several issues that is not commonly accessed hadn't been updated.

Renaming these "Deprecation Errors" to "Deprecation Warnings", or at least somehow clarifying the intended meaning of the messages shown to users who may not understand their underlying use, could help users stay closer to the trail of a real problem instead of a perceived problem and, in some cases, help reduce unnecessary panic.

**Comment by narration-sd** [comment]
A quick reaction, from many years being the consultant responsible for saves with confidence, in deep situations with customers -- 

- I think you have a very excellent point, @BenParizek, and  that it's very good you brought it up, as Craft's presence is so clearly expanding into worlds beyond the initial one
- must equally feel the wise thing, and from the customer's point of view first of all, would be to enable the ability to _completely_ have disabled any screen visibility of such messages.

Log them, of course, what databases are for. But config them out, preferably with the .env, so there's not temptation to turn them on in production. This way, also you immediately have them back and current, in staging or dev.

Leaving them up in any form, softened or not, will not assuage the emotions of persons responsible on the other end.  I think with imagination, that will be clear.

Hope I am not coming on too strong, but memories are very present...and I guess the sense to help...

**Comment by brandonkelly** [comment]
@BenParizek I’d consider this, but logging them is actually a bit taxing on performance, so you should just fix them :)

**Comment by BenParizek** [comment]
@brandonkelly I'm not at all trying to avoid fixing these at all! 

The update would mainly help those who are out of their comfort zone and trying to explain totally unrelated phenomena by guessing that "Deprecation Errors" are part of their problem.

**Comment by narration-sd** [comment]
Hey, Brandon @brandonkelly  -- you really surprise me here!

First, the technical;  I'm not talking about  any extra, expensive logging. You already log these deprecations once and leave them -- it's how the warnings can show on the CP.

So all you would need to do is to condition _showing_ resultant deprecation warnings on the CP Utils.  Again I suggest this by the devops means of the .env file, for all the obvious reasons.

Now, why. 

I think you can hear in Ben's @BenPsuarizek 's voice alone.  

Maybe as important to you, this voice is one you, @angrybrad , Sam , or Leslie are likely to hear about such things, as you gain traction in the business of consulting on Craft's larger uses.

I hear it as the very upset speaking of a line executive at a large aerospace firm in Britain, not British Aerospace this time but a supplier, coming to find me after hours when I was on his site sorting out another problem, out of my consultancy.

He told me he was ready to shut down the entire plant, because he couldn't get a status communicated out of the ERP system entirely operating it, that I represented. It's reverse judo here, compared to too much misleading information we are talking about, but the panic level was clear -- and about, for heaven sakes, a printout....aand thus I'm sure you will see the principle.

I went out  with him, also in my suit, and quietly was able to say that in fact I didn't know about that aspect of the system, but  because  of how it was designed, I felt there would be a record of the report available, even though he'd failed to print it. And indeed there was. 

Connecting the dots, he calmed right down, but what you want to remember is the anxiety and explosion. This is how people with responsibility for things feel and react, when they don't understand them and are presented with evidence matters aren't right.

Can a CMS generate such situations? I  am sure it can, in a world ever more engaged in critical and public communication.

Ok -- you get the story, am sure. I hope you won't pass it over as passé. And in fact its the same source of intuition that has had me holding on to Live Vue until it can be adequately rounded  out to survive, or have its own project forfeited -- not least because I watch the rising tide of what and with who Craft is getting involved in....

Thanks for listening,
Clive

**Comment by brandonkelly** [comment]
Alright alright

**Comment by narration-sd** [comment]
haha - good man :)     (I knew you were...)

Nice little black hole with all the translations; always something like this, isn't there :profi: (that's Deutsch)
