### ISSUE TITLE
Asset paths do not include subfolder, causing confusion

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3360]
There is no consistent way to get an asset's path, relative to the volume's root.

Both `craftcms/aws-s3/` and `craftcms/google-cloud` have `subfolder` options, which which nest the folder they are stored in.

`craft\elements\Asset::getPath` gives you the "folderPath + file", but this isn't really helpful without the subfolder.

You could manually prepend `$volume->subfolder`, as both `craftcms/aws-s3/` and `craftcms/google-cloud` use that…but that doesn't seem like a very good solution.

It seems like either `craft\elements\Asset::getPath` should contain "subfolder + folderPath + file", or there should be some other consistent way to get the full, valid path to an asset.

**Comment by andris-sevcenko** [comment]
You're confusing volume with something else. If you're creating a volume on an S3 bucket, subfolder setting tells Craft where the volume is located in the bucket. It is not a subpath in the volume itself.

So, `craft\elements\Asset::getPath()` actually does get you the asset's path relative to the volume's root.

What's the use case here?

**Comment by timkelty** [comment]
@andris-sevcenko Right, I get that…
The use case is wanting to access to the full s3 path (e.g. for passing to a image resizer: https://github.com/nystudio107/craft-imageoptimize/pull/114/files)

**Comment by andris-sevcenko** [comment]
Hmm. Honestly, that pull request has it as good is it can get without breaking any abstraction.

`craft\elements\Asset::getPath()` should not return anything else, because it returns the path in its volume and it should have no awareness of the whereabouts of the volume at all.

If I understand correctly, then you need the path on an S3 bucket otherwise you'd just use the URL. So, I'm not sure if there's anything wrong with using an S3 volume plugin-specific property?

**Comment by timkelty** [comment]
Talked this over with @andris-sevcenko and not sure there is a great solution, other than explicitly supporting those volume interfaces with whatever plugin code is using them.

If other cases come up it might be worth addressing, but right now the use-case is pretty isolated.
