### ISSUE TITLE
Project config: single section created incorrectly

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#3377]
### Description
I was playing around with the developer preview and project config for a blogpost and noticed that a single section doesn't get created correctly through the project.yaml.

### Steps to reproduce

1. In site A, create a new single section
2. Commit the changes to project.yaml
3. Pull down the changes in site B
4. Apply the changes
5. The single section will be shown as having 0 entry types on site B. Clicking "edit entry types" also takes you to an empty screen.

![screenshot 2018-10-14 at 16 08 08](https://user-images.githubusercontent.com/755428/46917828-7bf89700-cfcb-11e8-8132-4e1adbb18c0f.png)

### Additional info

- Craft version: 3.1.0-alpha.1
- PHP version: 7.2.1
- Database driver & version: MySQL 5.6.38
- Plugins & versions: None

**Comment by narration-sd** [comment]
hey, @andris-sevcenko  -- besides long time no see, thus greeetings, noticing again a recent habit of  closing issues with no note back that we can see.

I've been guessing that in such cases you've had offside conversation with the originator. If not, imagine they would feel a bit lost or surprised.

But either way, seems it would always be good to have a closing comment, no? Then when we email monitor the repo, we can see closure, and know it was a fault fixed, or a non-fault  explained...

Useful, no?

Thanks, then,
Clive

**Comment by andris-sevcenko** [comment]
I mean. There was a bug where applying changes from the project.yaml wouldn't be fully applied because in sections there are multiple data points which must be reacted to.

There are two sets of configuration - the existing configuration and the incoming configuration. Whenever there's reason to suspect new configuration is coming in, those two data sets are compared.

In this case before you can add an entry type, you must have a section to which the entry type belongs to. For some reason (read: airhead me) project config service was modifying the existing configuration before it was done with all the changes, so when saving section data, entry type data was saved into the existing configuration, without actually saving it to the database. This was fixed.

Or, as the commit message that was supposed to close this issue (but didn't for some reason) says:

> Don’t update the stored config immediately after processing a subset of changes. Fixes #3377

I'm not sure why GitHub didn't close the issue based on the commit, so I manually closed it causing it to look like an "eh, closed." response, which it was not.

**Comment by janhenckens** [comment]
Github did close the issue, and since this is a new feature and clearly a bug, this was perfectly fine for me :), commit messages says enough in this case  @andris-sevcenko.

**Comment by narration-sd** [comment]
Good man, Andris ;) , and it doesn't always have to stretch your ink - just a succinct comment can guide us to look at the code if apropos.

@janhenckens yes, the commit did show if moving to look on GitHub; just not in the mail.

For me, the the reasons to always comment are to aid our community learning, and not less important, let especially newer recruits see how well and consistently the Craft team supports.

Good to have the benefit out of all that work, seems right?

**Comment by brandonkelly** [comment]
> I'm not sure why GitHub didn't close the issue based on the commit

That only happens automatically if/when the fix is pushed to the default branch (`develop`).

**Comment by brandonkelly** [comment]
It’s awkward because if you do push a commit with `Fixes #<Num>` to the default branch, then GitHub will send an email notification out to everyone with something like

> Andris closed `#<Num>` via `<Hash>`

but if it’s not happening on the default branch, then GH just treats the `Fixes #<Num>` thing as a reference to the issue, but not a command to close it (yet), so all you get is that “Andris added a commit that referenced this issue” line on the issue page – but it _won’t_ send an email notification out about that. So if you’re following along via email all you’re going to see is the email notification that said

> Andris closed `#<Num>`

which could be a little confusing. So yeah, maybe as a general rule when we have to manually close an issue due to the fix not being on the default branch, we should go ahead and close it with a “Fixed via `<Hash>`” comment.

**Comment by narration-sd** [comment]
@brandonkelly interesting quandary, and yes, I held back from suggesting your way of answering 'fixed by', but in fact I think that's very effective on the points, and is what I missed for a while from expert in Europe ;)
