### ISSUE TITLE
"This page isn’t working"

### ISSUE THREAD

**Issue by Johnsalzarulo** [craftcms/cms#3451]
### Description
Hey Craft Community - I'm a new craft developer and I've spent hours trying to get my install up and running. I'm really under the gun to deliver something to a client and I've totally out of options. 

High level: When I run MAMP and point it to my project I keep getting: 

````
This page isn’t working localhost is currently unable to handle this request.
HTTP ERROR 500
````

I've tried [stack exchange](https://craftcms.stackexchange.com/questions/28349/this-page-isn-t-working-i-think-its-my-env/28350#28350) and everywhere to try to solve this. Any guidance or help would be completely incredible. I'm so desperate to get this project shipped. 

Detail: 

- I set up the initial craft project with craft create
- This got pushed to Github and other devs have been continuing work
- We were collaborating just fine on the project back and fourth with changes.
- In my development I somehow deleted my .env file.
- Now - I can't get my /admin/dashboard to show up or the craft site at all.
- I've been playing with the settings in the .env I've been going back and fourth with the /phpMyAdmin/?lang=en page trying to set up and link a database.
- It seems: the project is fine, the database is fine, but I can't seem to link my database and the craft project and get craft to run at all.

**HOWEVER:**

- I could set up and run a totally new craft project without any issue. So I know I have the correct  dependencies and approach. 

Any tips? Help? Please!

### Additional info

- Craft version: `1.0.8`
- PHP version: `7.2.11`
- Database driver & version: `Not sure how to get this`
- Plugins & versions: `none that I know of`

**Comment by narrishinsd** [comment]
John, not running MAMP here and have never seen a message like that, which looks like it's own (obfuscating) rewrite of what's going on; possibly just the 500 itself, which is a server error saying it failed 'internallly' trying to run the php code overall. 

There's not much detail there, and Craft nor any other framework can help, because the server crashed.

What often causes such blind errors like this often, especially on new installations or re-installs, is not having enough memory etc. configured for the php runtime  of the server.

You can try the settings Brad of the head team recommends, in his reply on another issue posting here: https://github.com/craftcms/cms/issues/3447#issuecomment-436682692

Good fortune  -- this is what I can suggest at this hour.  Let us know if these or higher values get you running, and others  can chime in when they see.

**Comment by Johnsalzarulo** [comment]
@narrishinsd - Thanks so much for the tips. I'm trying to figure out how to config the `php.ini` and struggling. 

Where do I set this memory limit? I just searched my whole repo for `memory_limit` and a `php.ini` file and I can't find any of this. 

I think my issue is I'm not experienced at all in `Apache` or `MAMP` - I've only worked with Rails / Node in the past. I'm really struggling to find any good docs or info on localhost config. 

So sorry to be such a N00B. Really appreciate the direction and help.

**Comment by narrishinsd** [comment]
John, don't concern at all at being new at this one of the many angles of today's software. We've all been there.  And we each get to be there again, when we involve in another package.

Let's look at MAMP - and it looks like this php.ini matter is a little obscure there. Kind what tends to happen in an 'I'll do it for you' system. I turned up this page by googling `mamp php.ini`:

[https://stackoverflow.com/questions/11691767/where-does-mamp-keep-its-php-ini](https://stackoverflow.com/questions/11691767/where-does-mamp-keep-its-php-ini)

In it you'll find:
- a great way to find the _active_ php.ini(s) on any sysstem, running a tiny php file with one function call in it, after the <?php> introducer:  phpinfo(); That will find the file -- and in MAMP, it's apparently not simply named php.ini...
- Then, keep reading, and you'll  find out that probably you don't want to directly edit that file, as MAMP seems to be managing it, thus  will overwrite. There are explanations then of how to edit the values that will be used,  which is what you want.

Let me fire just this information off to you, as I know you're wanting to start moving forward, and I'll come back with items to set.

And  before long, there should be  one of the Mac-using community, which is quite large, to come back who also still uses MAMP, and can give you good  advice on the tricks there...

**Comment by narrishinsd** [comment]
Ok, coming right back, if you're using MAMP Pro, here's what the online manual says, directly to change php's `memory_limit`:

    https://documentation.mamp.info/en/MAMP-PRO-Mac/How-Tos/General/IncreasePHPmemoryLimit/

Yes, the doc is out of date, talking about php 5, but this likely hasn't changed.

Following Brad's advice, this is likely what you need, once you've used their editor to find it:
```
    memory_limit = 256M ;
```

I think they're a little confused in the doc, having  that single '-quote beginning the example, but if the editor has such quotes, then you'd just replace the number to 256M anyway, so keep what it shows.

And it should be the same procedure, to find and set `max_execution_time`.  I doubt that's your issue here, but it's good to know how to do this generally.

Ok, and would mention i'd looked up your company last night -- great things you work on, actually, was impressed....

**Comment by turnstylerj** [comment]
You won't find `php.ini` in your repo - this is a configuration file for MAMP's PHP installation. You can edit it by going to the PHP tab in MAMP, and clicking the right arrow icon next to the PHP version. This opens a window where you can edit and save the file, and afterwards you'll want to restart your MAMP server(s).

<img width="446" alt="screen shot 2018-11-08 at 9 22 46 am" src="https://user-images.githubusercontent.com/42223501/48216096-ab839080-e338-11e8-8e3f-8f8497ea7669.png">

**Comment by Johnsalzarulo** [comment]
@turnstylerj - Thanks so much!

**Comment by Johnsalzarulo** [comment]
Ahhh! Ok following the above I was able to come up with a different error - progress! 

````
Warning: require_once(/Users/johnsalzarulo/code/poplar-blog/vendor/autoload.php): failed to open stream: No such file or directory in /Users/johnsalzarulo/code/poplar-blog/web/index.php on line 11

Fatal error: require_once(): Failed opening required '/Users/johnsalzarulo/code/poplar-blog/vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php7.1.20/lib/php') in /Users/johnsalzarulo/code/poplar-blog/web/index.php on line 11
````

Any thoughts? 

Here is my index.php: 

````php
<?php
/**
 * Craft web bootstrap file
 */

// Set path constants
define('CRAFT_BASE_PATH', dirname(__DIR__));
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH.'/vendor');

// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH.'/autoload.php';

// Load dotenv?
if (file_exists(CRAFT_BASE_PATH.'/.env')) {
    (new Dotenv\Dotenv(CRAFT_BASE_PATH))->load();
}

// Load and run Craft
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
$app = require CRAFT_VENDOR_PATH.'/craftcms/cms/bootstrap/web.php';
$app->run();

````

**Comment by turnstylerj** [comment]
Does `/Users/johnsalzarulo/code/poplar-blog/vendor/autoload.php` exist in your project? If not, have you run `composer install` in your project root directory?

**Comment by Johnsalzarulo** [comment]
👍 🏅 🎆 Success. That was my issue `composer install` in my root directory fixed my issue. Thank you so much to @turnstylerj @narrishinsd and the craft community. 

For real. Thank you thank you.

**Comment by narrishinsd** [comment]
Most welcome, John, I am sure from @turnstylerj as well. 

In future, you may want to join the Craft Slack -- lots of good information and discussion therve, plus works best for problems which aren't Craft's software releases, but about usage and so forth.

https://craftcms.slack.com

and there's an app for it... ;)

**Comment by narrishinsd** [comment]
p.s. http://turnstyle.studio/ is quite a website, as well...
