### ISSUE TITLE
Saving block of a matrix with propagate false writes to all sites

### ISSUE THREAD

**Issue by larsboldt** [craftcms/cms#3470]
### Description
I am updating a matrix block programatically through PHP with propagate set to false. I am working on an entry with siteId 2, block has siteId 2, after save, both entries in matrixcontent_*** is updated (siteId 1 and siteId 2). I expected only the db entry with siteId 2 to be updated because of propagate false on saveElement. 

### Steps to reproduce
```php
foreach ($matrixBlocks as $block) {
    if ((int) $block->id === (int) $richTextBlock->id) {
        $block->setFieldValue('richText', $richTextBlock->text);
        Craft::$app->elements->saveElement($block, true, false);
```

### Additional info

- Craft version: 3.0.27.1
- PHP version: 7.2
- Database driver & version: MySQL 5.7
- Plugins & versions:

**Comment by brandonkelly** [comment]
They’re supposed to only get saved in the sites that the owner entry supports.

Are you seeing this same behavior when saving the entry + blocks from the Control Panel? If not, how are you fetching the blocks to begin with?

**Comment by larsboldt** [comment]
It happens in the Control Panel as well, saving richtext blocks in matrix fields write the same data across all sites while fields like title do not.

**Comment by brandonkelly** [comment]
Cool, consistently wrong is better than inconsistently wrong :) Looking into it.

**Comment by brandonkelly** [comment]
Sorry, I misunderstood the issue. I thought you meant that the section had its “Propagate entries across all enabled sites?” setting disabled. Ignore everything I’ve said so far!

So… looking at your code, you’re right, by passing `false` to `$propagate`, the block will only be saved for the site it’s currently set to. If that’s not the case, I’m guessing it’s because those blocks are getting re-saved some other way later on. Perhaps the entry itself is getting saved?

If you have Xdebug running, you could setting a breakpoint in `craft\services\Elements::_propagateElement()`, with the condition `$element instanceof \craft\elements\MatrixBlock`, and see when that is getting triggered.
