### ISSUE TITLE
How to use yii request parsers via config/app.php

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#3478]
I was trying to use `\yii\web\JsonParser` like so:

```php
return [
    'components' => [
        'request' => [
            'parsers' => [
                'application/json' => \yii\web\JsonParser::class,
            ],
        ],
    ],
];
```

However, it appears it isn't compatible with Craft requests:

```
An Error occurred while handling another error:
yii\base\UnknownMethodException: Calling unknown method: yii\web\Request::getIsCpRequest() in /app/vendor/composer/yiisoft/yii2/base/Component.php:300
```

Any way to get this working?

**Comment by brandonkelly** [comment]
Craft can only _merge_ your component config overrides into its own when both configs are arrays. Which isn’t the case for `request`:

https://github.com/craftcms/cms/blob/0173df72c13d33aff3d9ffd3c9ec8e03f1bda39b/src/config/app.web.php#L10-L16

So whatever you do here is going to completely replace Craft’s `request` config. Which is why we’ve moved all of our dynamically-generated component config definitions into `craft\helpers\App` methods – so you can call that to get the core config from your own `app.php` (actually should be `app.web.php` in this case), and then make changes to the array it returns.

```php
return [
    'components' => [
        'request' => function() {
            $config = craft\helpers\App::webRequestConfig();
            $config['parsers'] = [
                'application/json' => yii\web\JsonParser::class,
            ];

            /** @var craft\web\Request $request */
            $request = Craft::createObject($config);
            $request->csrfCookie = Craft::cookieConfig([], $request);
            return $request;
        },
    ],
];
```

**Comment by timkelty** [comment]
ah hah – makes sense – same thing I'm doing when I add targets to `log`, thanks @brandonkelly!
