### ISSUE TITLE
Inconsitent PHP code

### ISSUE THREAD

**Issue by TheFox** [craftcms/cms#3524]
The PHP code is very inconsistent. On some objects I can use `...->getId();`, on others there is only `...->id` available.

Sometimes I can use `...->theObject = $theObject;`, on other cases I have to use `...->theObjectId = $theObject->id` to make a reference.

This is very confusing. Why can we not get Getters and Setters for all classes?

**Comment by brandonkelly** [comment]
We use plain class properties as often as possible because they are more performant. Where we can’t, you should still be able to treat them as properties thanks to Yii’s magic getter/setter implementation (see https://www.yiiframework.com/doc/guide/2.0/en/concept-properties). Generally those should be annotated as `@property`, `@property-read`, or `@property-write` tags on the class so they show up in your IDE’s autocomplete menus, etc.
