### ISSUE TITLE
Missing error message on required asset field

### ISSUE THREAD

**Issue by elfacht** [craftcms/cms#3545]
### Description

If an asset field is required and the will be saved, there's no error message popping up. Only when someone will try to publish the entry a message will be shown.

![screenshot 2018-12-11 um 14 49 54](https://user-images.githubusercontent.com/529443/49805364-364f1500-fd55-11e8-8cfd-24fa172beeac.jpg)

### Steps to reproduce

1. Add an asset field to a entry type.
2. Make it required.
3. Disable entry per default (no publishing on save).
4. Add a new entry and save (not publish) the entry without selecting a file.

### Additional info

- Craft version: 3.0.34
- PHP version: 7.1.20
- Database driver & version: MySQL 5.7.23
- Plugins & versions: no plugins

**Comment by brandonkelly** [comment]
That’s expected behavior. Craft never enforces required fields (besides Title) until the entry is actually attempting to go live. This gives authors a chance to save in-progress entries without needing to dot every `i` and cross every `t` until it’s time to publish.

**Comment by narration-sd** [comment]
Seems it could be useful for Craft to have a preflight for such things, as DTP software does. So that there won't be surprises when a publish date comes around.

To keep life simple, how about a simple 'Do you really want to leave this page' dialog as you get with unsaved entries? Red-typing/redlining the missing fields the extra step...cheers.

**Comment by brandonkelly** [comment]
I could see Craft giving better visibility into an entry's publishability within a larger governance effort. Not something we’d change or add out of the blue though.
