### ISSUE TITLE
Automatically apply database changes across cluster instances

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#3551]
### Description
We have a load-balanced environment with a cluster of 2 Craft 3 servers using the same database. Craft runs inside docker containers which images are pre-built and later deployed in a rolling manner to AWS ECS.

The challenge becomes clear when we perform Craft version update and database changes need to be applied.  The replacement of containers is managed by the environment and for some time site becomes unavailable with update pending.

It would be great to have a way to configure Craft to apply DB changes automatically and use some locking mechanism to avoid concurrent updates in the cluster.

### Additional info

- Craft version: 3
- PHP version: 7.2
- Database driver & version: Postgres

**Comment by angrybrad** [comment]
@acehead Do you have a way to detect with the first container is replaced?  If so, you could have a script make a cURL POST request to https://github.com/craftcms/cms/blob/develop/src/controllers/AppController.php#L123, which would trigger any pending database migrations.

**Comment by acehead** [comment]
@angrybrad Yes, this is definitely an option. For AWS this will mean the need of configuring ECS events to be sent to custom lambda which does the thing.

It would be great, however, that you would consider such option for the core product. It could be something similar to `generateTransformsBeforePageLoad`, which runs migrations if needed before the page is rendered.

I believe this is also aligned with the overall Craft 3.1 strategy where you try to avoid any manual administrative changes on live environment. Developers can do any admin changes (including version upgrade) on their local env, test pending migrations if any and when release is deployed to live it should be considered safe to update db automatically as well.

**Comment by angrybrad** [comment]
We can't blindly let front-end requests trigger database migrations because even if we detect the database schema version has changed (in src/config/app.php), we can't be sure that all of the files are in place yet in the case, for example, of someone uploading via FTP and it's still transferring.

Adding a config setting (similar to `generateTransformsBeforePageLoad`) has so that it might work in your scenario has drawbacks, too.

1.  It further complicates some already pretty complicated logic.
2.  After the first request triggers a migration, we'd still have to serve a 503 to subsequent requests on the front-end until the update/migrations finish.
3.  If a migration fails, now users are potentially receiving a 500 internal server error in the response instead of a controlled 503.
4.  Users will set the config setting to true without fully understanding the implications of what that means (causing more support).

> when release is deployed to live it should be considered safe to update db automatically as well.

Assuming completely identical local/production environments like Docker provides.  In reality outside of Docker, that's almost never the case.

In this case, I'm going to favor the more controlled workaround that people can set up as needed on a case-by-case basis.
