### ISSUE TITLE
Sensitive data exposed in logs and debugging toolbar

### ISSUE THREAD

**Issue by acehead** [craftcms/cms#3619]
One of the main intentions of 3.1 is to move sensitive data from database into environmental variables referenced from project config.

The side effect here is that the values of environmental variables (including keys and passwords) are exposed at least in 
- Logs
- Yii2 debug panel

They are masked in PHP info though.

Is it an expected beahviour and are there any plans to mask sensitive data all across the Craft?

**Comment by brandonkelly** [comment]
Can you provide specific examples of where you’re seeing sensitive data in the logs / Debug toolbar?

**Comment by jwb009** [comment]
I just noticed this too but I'm not on 3.1 yet. In **phperrors.log** my 'SECURITY_KEY', 'S3_API_KEY' and 'S3_SECRET' are exposed in plain text. In **web.log** these same values are replaced with ••••'s.

**Comment by acehead** [comment]
@jwb009 exactly. I was testing on 3.0 as well, not sure this behavior changed in 3.1.
Another place where you can see real environment variable values is Yii Debug Toolbar. You can find them by maximizing debug toolbar in CP -> select any of the recent requests -> Request on the left menu -> $_SERVER tab

**Comment by brandonkelly** [comment]
Thanks. I was able to override the Request panel to redact any sensitive info within it.

We don’t have any control over _what_ gets logged to `storage/logs/phperrors.log`, but I just added support for a new `CRAFT_LOG_PHP_ERRORS` PHP constant you can set from `index.php` to prevent Craft from forcing PHP errors to be logged there in the first place.

```php
// Don't send PHP error logs to storage/logs/phperrors.log
define('CRAFT_LOG_PHP_ERRORS', false);
```

**Comment by brandonkelly** [comment]
Craft will automatically redact environment variables that look sensitive based on the variable name, via this list of sensitive-sounding keywords:

https://github.com/craftcms/cms/blob/43ee7a72b0aeeb08ddd14f3efd492752c128a489/src/config/app.php#L118-L126

I [just added](https://github.com/craftcms/cms/commit/52bc7657e522a978e41e8b2eeb8a443ba48efac0) `PK` to that list for the next v3 and v4 releases.

Worth noting that it’s not a perfect solution: there are still ways that sensitive environment variables could be logged out that Craft doesn’t have any control over, as well as `phpinfo()`. Which is why we added [secrets support](https://craftcms.com/docs/4.x/config/#secrets) in Craft 4.5, which provides a more secure way of defining sensitive environmental values.

**Comment by brandonkelly** [comment]
Craft 3.9.2 and 4.5.4 are out with `SK` added to the sensitive keywords list.
