### ISSUE TITLE
Project Config always creates site with default name and handle

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/cms#3661]
### Description

Project Config always creates a site with default name and handle. When renaming the default site's name and handle it saves to project.yaml, but when installing a new site with this file it still uses the default name and `default` handle, and saves that back to project.yaml

<img width="416" alt="screen shot 2019-01-18 at 08 34 10" src="https://user-images.githubusercontent.com/378974/51373218-fa4f6280-1aff-11e9-8f98-167698455fe3.png">

### Steps to reproduce

1. Set up Craft and rename default site and its handle
2. Install new Craft with that project.yaml
3. See project.yaml changed to default site and handle again

### Additional info

- Craft version: 3.1.1
- PHP version: 7.3.1
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Yeah this is a little awkward because the installer lets you choose the site name, so we should be respecting that over whatever is in `project.yaml` I think. That said I suppose we can update the installer to set the _default_ site name value to the value in `project.yaml` if that’s present. And we can leave the handle alone – that was never user-submitted anyway.

In Base URL’s case that might be a step in the wrong direction though, as the default value is based on the current request’s URL, which is more likely to be correct than whatever is in `project.yaml`.

**Comment by brandonkelly** [comment]
3.1.2 is out with the fix.
