### ISSUE TITLE
Users cant upload Profile pictures

### ISSUE THREAD

**Issue by RainerZarth** [craftcms/cms#3735]
### Description
Users without permission "edit Users" cant upload their own Profile Picture in the Backend, the Error Message is: "User is not permitted to perform this action".

### Steps to reproduce

1.Create an Usergroup without Permission to edit other users.
2.The Group has all rights on the Volume to the Profile pictures.
3.When the User wants to edit his Account (upper left dropdown) in Backend, he is not allowed to upload a profile Picture.
4.the right to edit Users allows the User group to edit all Profiles

### Additional info

- Craft version: 3.1.5
- PHP version: 7.2 fpm
- Database driver & version: psql 10
- Plugins & versions: none

**Comment by mattrothenberg** [comment]
@brandonkelly @andris-sevcenko I'm fairly certain this is still broken. I'm on `3.1.8` and non-admin users still cannot upload user photos. I think it's because the return value of the following expression is a string, and that will never be equal to the `userId` that gets cast to a string in the lines prior.
```php
Craft::$app->getUser()->getIdentity()->id
```

**Comment by brandonkelly** [comment]
Yep, fixed for 3.1.9.
