### ISSUE TITLE
unexpected problem worked around in Event

### ISSUE THREAD

**Issue by narration-sd** [craftcms/cms#3761]
### Description
I use a lot of Events, and so the trouble here seems unusual. Yet because it happens, I'd like to understand what I may possibly be missing about namespace formats in Yii/Craft. 

There's no hurry, as I won't be using this Event after all -- the code was part of discovery in adapting Live Vue to Gatsby, which has some challenges to be solved in other ways.

The code below relates to documentation here, which is standard practice for Events: https://docs.craftcms.com/v3/extend/template-roots.html
- the first two lines commented out would be by that practice, but I couldn't use this form as I already have an Event on `yii\web\View`, with its `use `statement. 
- the also-commented line below it is what failed -- simply fully pathing with namespace, in what felt like a normal way
- the uncommented code is what worked: using a plain string instead of the result of `name\spaced\Class:class` as the argument. 
- it appears that `name\spaced\Class:class` and php `get_class()` differ, at least in this case. Yet all the code involved is within Yii, hence the puzzlement -- and that many Event registrations in the same plugin which employ unpathed `Class:class` followiing `use name\space\Class` above work fine.

### Steps to reproduce

```      
     // use  yii\base\View;
     // Event::on(View::class,

     // Event::on(craft\web\View::class,

        Event::on("craft\web\View",
            craft\web\View::EVENT_REGISTER_SITE_TEMPLATE_ROOTS,
            function(RegisterTemplateRootsEvent $event) {
                $event->roots['_gatsby'] = '/home/vagrant/lv-gatsby_html/public';
            }
        );
```

1. the fully pathed object:class version resulted in the Event never getting triggered, so that templates on the alternate path weren't found.
2. Digging down with a debugger on the layers for my case, I found that though the registry was accomplished, the registered closure was labelled as  'Craft\web\view' -- notice the capitalization.
3. However, the compare value obtained in Event::trigger(), via get_class(), was the expected 'craft\web\View'.
4. Thus, the registered closure wasn't found, and so the template couldn't be either. 

A picture being better than words, I've recreated the situation and taken a screenshot. This will also give you line numbers in Event.php. The watch vars show the failing array match, using $name, vs. successful match above it if I manually capitalize what's in $name.

When I use the string argument for the class, the mismatch doesn't happen, the compare in line 305 matches, the trigger fires and the template in alternate path is eventually found, all after this working as it's supposed to.

![event-trigger-miss](https://user-images.githubusercontent.com/247945/52102130-a038ad80-2593-11e9-97a1-78926f1d85d1.png)

### Additional info

PHP version	7.1.26
Database driver & version	MySQL 5.7.24
Image driver & version	GD 7.1.26
Craft edition & version	Craft Pro 3.1.6.1
Yii version	2.0.15.1
Twig version	2.6.2
Guzzle version	6.3.3
Imagine version	0.7-dev
Plugins
Asset Rev	6.0.2
CraftQL	dev-master
Element API	2.5.4
Live Vue	v0.9.61
Redactor	2.3.1

**Comment by brandonkelly** [comment]
> the first two lines commented out would be by that practice, but I couldn't use this form as I already have an Event on `yii\web\View`, with its `use` statement.

Whenever our code examples start with `use` statements, those are intended to go at the top of your files, right after the `namespace` line (as PHP will do automatically when using its class importing features, and also as demonstrated in [PHP’s aliasing/importing docs](http://php.net/manual/en/language.namespaces.importing.php)).

You only need to import a class from a different namespace once per file, at the top of it, and then you can reference it by its non-namespaced name as many times as you want throughout the rest of the file (e.g. `View` or `View::class`).

> it appears that `name\spaced\Class:class` and php `get_class()` differ, at least in this case. Yet all the code involved is within Yii, hence the puzzlement -- and that many Event registrations in the same plugin which employ unpathed `Class:class` followiing `use name\space\Class` above work fine.

The difference is that `get_class()` (as well as the first argument of `Event::on()`) are always expecting a fully qualified class name string (e.g. `'craft\web\View'`), whereas `::class` must be added to an actual class reference, just like `ClassName::someStaticMethod()` or `new ClassName()`, etc.

If your code was at the root namespace (no `namespace` line at the top), then `craft\web\View::class` would work, because that would be an accurate relative path to the View class.

But since your code likely has a namespace, when you type `craft\web\View::class` PHP is actually interpreting it as `your\namespace\craft\web\View::class`, and it will return the string `'your\namespace\craft\web\View'`.

So you can either add a `\` to the beginning, to clarify that this is an absolute path to the class, not relative (`\craft\web\View::class`) or you can import the class by adding a `use craft\web\View;` line to the top of your file after your `namespace` line, and then just use `View::class`.
