### ISSUE TITLE
Customize “Title” label when using title format

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#3814]
### Description

It would be really helpful if it was possible to override the “Title” label used on the element index table, for entry types where the title format feature is used.

For generated titles “Title” is often the wrong term, and therefore, confusing.

Remotely related to #3804

**Comment by carlcs** [comment]
I think this is resolved by https://github.com/craftcms/cms/commit/746eaff0300e7cee8a837b10a34efe4f933abf31

**Comment by brandonkelly** [comment]
Sortof… all entry types can now define a custom Title field label regardless of whether the Title field will be shown or not. If the Title field is hidden it will only have an effect if Craft needs to show a validation error for the title. Either way, entry tables will still call the first heading “Title”.

It’s a little tricky because table headings are defined globally for each element type, and even if they were per-source, title labels are defined per-entry type, not per-section, and the default sources are for each section.

I think the best way we could actually solve this would be with a new setting within the element index settings modal.

**Comment by brandonkelly** [comment]
Just added a new “Header Column Heading” element source setting, which will override the “Title” heading for the selected source.

<img width="1111" alt="Element source settings" src="https://user-images.githubusercontent.com/47792/88303979-82e22c80-ccbc-11ea-90a1-3d673981565f.png">

**Comment by brandonkelly** [comment]
Craft 3.5 RC2 is out now with that change.

**Comment by Mosnar** [comment]
@brandonkelly Wait... wouldn't it make more sense to be called "Title Column Heading"?

**Comment by brandonkelly** [comment]
@Mosnar Not all element types have “titles”, and the first column is only generally “Title” by convention, but it’s still up to each element type to say what its (default) heading should be.
