### ISSUE TITLE
Assets fields not restricted to single folder - allow creating directory based on entry while using file selection modal

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3855]
On website i am working on, client wants to have ability to browse files assigned to all entries in his asset fields. But still, if he uploads new file, he wants these files to be uploaded to correct folder, one with name same as entry files are assigned to.

If i check "Restrict uploads to a single folder?", directory is created correctly, but client cannot choose files from other entries. 
If i uncheck "Restrict uploads to a single folder?", client can create directory assigned to entry, but only dropping files directly into field, without opening file selection modal. If he opens modal and tries to upload files using it, files will end up in some other folder.

What i propose is adding new button to file selection modal, avaible if asset field has "Restrict uploads to a single folder?" not checked. This button would just automaticly create directory with name based on current entry and make this directory selected. So user can choose modal to upload his files and make them end up in correct place.

**Comment by brandonkelly** [comment]
> This button would just automaticly create directory with name based on current entry and make this directory selected.

That’s not exactly possible since the correct directory name/path may not be knowable until after the entry has been saved (for instance if it contains `{id}`).

I just posted #3861, which I think provides a better solution to this problem. Assets fields could continue to leave “Restrict uploads to a single folder” checked, and just duplicate assets into it from other places via the Upload button.
