### ISSUE TITLE
Element action to get an asset file URL

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#3859]
The new “Preview file” action is a nice addition, but I don’t think it should have replaced “Open in browser”. There’s currently no way to get an assets URL from the asset index in the CP.

**Comment by andris-sevcenko** [comment]
Hmm. "Open in browser" is tricky, as some file types could force a download.

What do you think about "Display URL" or something worded in a nicer way that would display the URL similar to how it's possible to see an asset's reference tag?

**Comment by carlcs** [comment]
I’d like that even better, I think.

**Comment by brandonkelly** [comment]
We replaced “View file” with “Preview file” because the former posed an XSS attack vector. It’s still possible to access files directly by enabling the “Link” table column, though:

<img width="640" alt="screen shot 2019-02-19 at 11 22 47 am" src="https://user-images.githubusercontent.com/47792/53041391-b9b57280-3438-11e9-95a3-3dd0a3288c43.png">

Then you can either click on the link icons, or copy their URLs via right-click → “Copy Link”.
