### ISSUE TITLE
Searching for entries doesnt work while displaying trashed

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3863]
### Steps to reproduce

1. display trashed entries
2. try to search for some entry using search bar
3. no trashed entry can be found

**Comment by brandonkelly** [comment]
They aren’t showing up because Craft deletes elements’ search indexes when soft-deleting elements. As of the next release that will no longer be the case, and Craft will wait until elements get hard-deleted before clearing out their search indexes. So going forward the search bar will work as expected for soft-deleted elements.
