### ISSUE TITLE
cli says "No project.yaml file found" if project.yaml is faulty

### ISSUE THREAD

**Issue by jorenvanhee** [craftcms/cms#3866]
### Description

The cli command `./craft project-config/sync` says "No project.yaml file found..." if the project.yaml file is faulty. It then generates a new one (project.yaml.XY8oA9hM8k). Syncing the project-config file through the admin behaves differently. This only happens if you sync the project-config file for the first time.

#### My situation
I have a plugin listed in the project-config that is not installed with composer. `./craft project-config/sync` generates a new project-config file. The admin interface shows an error instead.

> The following plugins are listed in project.yaml, but appear to be missing or installed at the wrong version: schematic
> Try running composer install from your terminal to resolve.
> Try again

I think the error should be shown in the cli as well.

### Steps to reproduce

1. Add a plugin to the project-config file
2. Make sure the plugin is not installed through composer
3. Use the project.yaml file in a fresh Craft installation, where the sync has never run before. It only happens in this situation.
4. Run `./craft project-config/sync`

### Additional info

- Craft version: 3.1.12
- PHP version: 7.2
- Database driver & version: MySQL 5.7

**Comment by andris-sevcenko** [comment]
Is this still a problem? Tried locally following the steps and I got

>  ./craft project-config/sync
> Installing plugin "aws-s3" ... error: No plugin exists with the handle "aws-s3".
> Aborting config sync

**Comment by jorenvanhee** [comment]
The issue is still there. But it's not that big of a deal. It is probably an edge case. I think this issue can be closed. But here's a screenshot anyways.
![Screenshot 2019-03-21 at 16 14 57](https://user-images.githubusercontent.com/231202/54763202-d7bbf180-4bf5-11e9-9c4d-13721f593947.png)

**Comment by andris-sevcenko** [comment]
Ah no, that behavior is exactly as expected.

When installing the site, Craft determines it cannot use the existing project.yaml file, because required packages don't exist. If they do, Craft will install the plugins.

So, when it figures out since it can't install the plugin, it can't use the existing project.yaml file, so it renames the existing project.yaml file to a different one (going to be moved to `storage/config-backups` as of next release).

So, syncing does not behave differently, it's just that if you try to install a new Craft site with a project.yaml file that cannot be used, it gets renamed.
