### ISSUE TITLE
Updates showing in CP but command line says there are none

### ISSUE THREAD

**Issue by mikeebee** [craftcms/cms#3886]
### Description

In the control panel in `/utilities/updates` I can see I have a Craft update and several plugin updates available. I prefer to update via the command line to avoid browser timeouts etc so ran `./craft update` but I get this output:

```
    Craft isn’t installed yet!

Fetching available updates ... done
You’re all up-to-date!
``` 
I also noticed if I run `./craft help` it _does_ output the help options but it says `Craft isn’t installed yet!` before the help options.

### Steps to reproduce

1. See available updates in the CP
2. Run `./craft update`

### Additional info

- Craft version: 3.1.12
- PHP version: 7.1
- Database driver & version: MySQL 5.6.35
<details>
 <summary>Plugins & versions:</summary>
<ul>
  <li>Cloner 1.0.1</li>
  <li>Command palette 3.1.4</li>
  <li>Control Panel Nav 2.0.9</li>
  <li>CP Field Inspect 1.0.5</li>
  <li>Craft Cheat Sheet 2.0.3</li>
  <li>Entry Instructions 1.0.4</li>
  <li>Expanded Singles 1.0.7</li>
  <li>Field Manager 2.0.5</li>
  <li>Imager v2.1.4</li>
  <li>Navigation  1.1.3</li>
  <li>Neo 2.2.3</li>
  <li>Redactor 2.3.1</li>
  <li>Redactor Tweaks 2.0.2</li>
  <li>SEOmatic 3.1.43</li>
  <li>Super Table 2.1.7</li>
  <li>Typed link field 1.0.17</li>
  <li>Wordsmith 3.0.4</li>
</ul>
</details>

**Comment by brandonkelly** [comment]
Yeah the `update` command isn’t going to give accurate results if the CLI thinks Craft isn’t installed yet, as is the case here.

Couple things to check, to get that working:

- Make sure you’re running the terminal command from the same environment that Craft is actually installed in. For example if Craft is running in a Vagrant box, make sure that you’re SSH’d into the Vagrant box before running it.

- Try changing the `DB_SERVER` environment variable from `localhost` to `127.0.0.1`.

**Comment by mikeebee** [comment]
The site is running through MAMP, I'm assuming I'm in the correct environment.

I ran the `./craft migrate` command successfully on another similar project. I did have to change the `DB_SERVER` variable to `127.0.0.1` on that occasion but I had already tried that for this site too and it didn't change anything.

**Comment by brandonkelly** [comment]
Do you still have the other project around? If so can you update it to the latest version and then try running the `migrate` command again on it, and see if you get the same `Craft isn’t installed yet!` output? (Ignoring whether the command works in general or not).

**Comment by mikeebee** [comment]
All sorted! I turned on the setting in MAMP to `Allow network access to MySql` which I've never touched before so no idea why it was fine before!

Anyway, all good. Thanks for pointing me in the right direction :)

**Comment by brandonkelly** [comment]
Ah great! I’ve never noticed that setting either :) Thanks for the update, we’ll have to remember that one.

**Comment by away86** [comment]
> All sorted! I turned on the setting in MAMP to `Allow network access to MySql` which I've never touched before so no idea why it was fine before!
> 
> Anyway, all good. Thanks for pointing me in the right direction :)

Anyone know a WAMP equivalent solution to this?

**Comment by angrybrad** [comment]
@away86 not tested, but try https://dba.stackexchange.com/questions/186301/how-to-enable-remote-access-to-wamp-mysql

**Comment by wei2go** [comment]
I realised that each person may have different cause for the same symptom.

For me, I'm using WAMP on Windows, and I was getting the following message in console.log:

`[craft\services\Updates::getUpdates] Couldn't get updates: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

It was weird because I previously fixed this issue for the web version for the local Plugin Store / Craft Updates (in the CP), based on [this post](https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate). Not sure why it still happened for the CLI version.

I eventually fixed it by adding the following code to config/guzzle.php:

<?php

```
return [

	'*' => [
		'verify' => true, // this is Guzzle / Craft default setting anyway.
	],

	'dev' => [
		'verify' => "C:/wamp/bin/php/cacert.pem", // change it to the path for your own cacert.pem, or it can be **false** if you don't have a cacert.pem
	],

];
```

References:

- [https://craftcms.com/docs/3.x/config/#guzzle-config](https://craftcms.com/docs/3.x/config/#guzzle-config)
- [https://craftcms.com/docs/3.x/config/#guzzle-config](https://docs.guzzlephp.org/en/latest/request-options.html#verify)

Hope this helps someone using WAMP with the same issue as me.
