### ISSUE TITLE
Use nl2br on fields instructions

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#3928]
Changing newlines to `<br>`s would make intructions more readable.

**Comment by brandonkelly** [comment]
Easy enough. Just added this for the next release!

**Comment by putyourlightson** [comment]
Hmm, this seems to have broken all info tooltips that my plugins use, likely because `nl2br` pre-escapes HTML. I realise the original request is valid, but probably not worth it if it will break a bunch of plugins. Craft used to use these info tooltips but it seems to have done away with most if not all of them.

![screenshot 2019-03-06 at 14 14 28](https://user-images.githubusercontent.com/2318222/53883873-908d0880-401a-11e9-9adf-3357f2946215.png)

**Comment by piotrpog** [comment]
@putyourlightson 
Then how about simple config variable that would enable or disable nl2br on field instructions?

**Comment by brandonkelly** [comment]
@putyourlightson Nothing a `|raw` filter can’t fix :)
