### ISSUE TITLE
Setting craft\events\UserEvent::$isValid to false is permanent and can no longer be activated

### ISSUE THREAD

**Issue by myriago** [craftcms/cms#3936]
### Description
I have posted detailed description on Stack Exchange , as I thought its my code, but now I'm confident this is to do with Craft itself. 

https://craftcms.stackexchange.com/questions/29686/how-to-pragmatically-set-registered-user-status-to-pending-and-then-manually-sen

### Steps to reproduce

1. Set craft\events\UserEvent::$isValid to false to prevent the user from getting activated.
```
Event::on(
          Users::class,
          Users::EVENT_BEFORE_ACTIVATE_USER,
          function (UserEvent $event) {
              if (Craft::$app->request->getIsSiteRequest()) {
                // Only trigger when request comes from the specified form
                $formName = Craft::$app->getRequest()->post('group');
                if($formName==='ypo' || $formName==="yp") {
                  logMessage('Activation Withold');
                  $event->isValid = false;
                }
              }
          }
      );
```
Note that $event->isValid = false; does not trigger during email or link activation, only after custom user registration form.

2. Sent activation email - link in it will fail to activate
3. Use activation link - it will go to reset password instead

I did a lot of testing, If I remove EVENT_BEFORE_ACTIVATE_USER code and register a user, and then put it back in and send email, activation works. This means that setting craft\events\UserEvent::$isValid to false is permanent and can no longer be activated.  I wasn't expecting such behaviour is this by design? 

### Additional info

- Craft version: Craft Pro 3.1.15
- PHP version:  7.1.26
- Database driver & version: MySQL 5.5.62
- Plugins & versions:

**Comment by brandonkelly** [comment]
I’m not able to reproduce this. If a user is initially registered but activation is cancelled via `$event->isValid = false`, they just remain in a pending state, and then when I access the activation URL, so long as `isValid` isn’t modified Craft doesn’t have any trouble activating the account at that point.

> This means that setting craft\events\UserEvent::$isValid to false is permanent and can no longer be activated.

I can assure you that Craft does not store that `isValid` was set to `false` anywhere.

I assume that you have disabled email verification in Settings > Users > Settings? Otherwise Craft wouldn’t be attempting to activate newly registered users to begin with.

Once a user has been registered (but not activated) and you’ve got their activation URL, try putting a breakpoint at this line:

https://github.com/craftcms/cms/blob/81e712ccf8f1a9b0a65426c70769229f20dc6b26/src/services/Users.php#L574

Or if you don’t have Xdebug running, just put this right before that line:

```php
Craft::dd($event->isValid);
```

Then click the activation link and see what `isValid` ends up being set to at that point.

**Comment by myriago** [comment]
Switching off email verification in panel skipped populating of the unverified email field, which in turn made any further attempts at verification futile. Adding $user->unverifiedEmail = $user->email; fixed that.

**Comment by brandonkelly** [comment]
Was that setting disabled to begin with, as I suspected? Otherwise, how exactly was your event getting fired in the first place? (If user verification is enabled, then users are not activated until they’ve verified their email.)

**Comment by myriago** [comment]
Yes the setting was disabled, then I went on sending the email manually from CP (after manually checking users), but the email link didn't work, and if I copy the link from the CP, I'll go to password change page instead of verification. It was really confusing. Maybe hiding the send activation email option in CP when the unverified email is not set would be more intuitive.

**Comment by brandonkelly** [comment]
> Anyway it is not a bug, per se, albeit some improvements to handling this would help, like disabling the 'send activation email' option in CP when the unverified email is not set.

In my testing, “Send activation email” worked fine for a pending user where `unverifiedEmail = null`.
