### ISSUE TITLE
Cannot download an asset locally under a Windows environment

### ISSUE THREAD

**Issue by jamesmacwhite** [craftcms/cms#3990]
### Description

I think this might be related to the following issues and this is possibly a Yii issue:

https://github.com/yiisoft/yii2/issues/16603
https://github.com/yiisoft/yii2/pull/16604

I'm unable to download an asset from an asset source in Craft CP when running under a Windows-hosted Unix VM (nanobox with VirtualBox), due to the following PHP exception occurring related to the unlink() function. A temp file is created in `/storage/runtime/temp` when attempting to download an asset but because of the unlink() exception, the download action returns a server error.

```
2019-03-13 13:12:00 [-][43903][51b97db60ebb60aebd1239f015978078][error][yii\base\ErrorException:2] yii\base\ErrorException: unlink(/app/storage/runtime/temp/example.jpg): Text file busy in /app/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:407
Stack trace:
#0 /app/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(407): ::unlink()
#1 /app/vendor/craftcms/cms/src/controllers/AssetsController.php(812): yii\helpers\BaseFileHelper::unlink()
#2 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): craft\controllers\AssetsController->actionDownloadAsset()
#3 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): ::call_user_func_array:{/app/vendor/yiisoft/yii2/base/InlineAction.php:57}()
#4 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#5 /app/vendor/craftcms/cms/src/web/Controller.php(109): craft\controllers\AssetsController->runAction()
#6 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\controllers\AssetsController->runAction()
#7 /app/vendor/craftcms/cms/src/web/Application.php(297): craft\web\Application->runAction()
#8 /app/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction()
#9 /app/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest()
#10 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#11 /app/web/index.php(21): craft\web\Application->run()
#12 {main}
```
I have implemented the `isWindows` config for the environment, so Yii is aware this is a Windows FS:
```
'components' => [
	    'mutex' => function() {
		    $config = \craft\helpers\App::mutexConfig();
		    $config['isWindows'] = filter_var(getenv('WINDOWS_FS'), FILTER_VALIDATE_BOOLEAN);

		    return \Craft::createObject($config);
	    },
    ],
```
This config is having a positive impact for other areas like DB migrations, because these also fail without this, but downloading assets which ultimately get written to a Windows FS is failing.

Interestingly if I remove the following lines from the `BaseFileHelper.php` https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseFileHelper.php#L406-L408 the download of the asset is successful, so I'm not sure what to make of that.

### Additional info

- Craft version: 3.1.17.2
- PHP version: 7.1
- Database driver & version: 5.6

**Comment by jamesmacwhite** [comment]
Ultimately, running Nanobox with the netfs mount type, will prevent these issues from happening. My environment was running under the native option, because netfs never worked. I have finally got it working and using netfs avoids all this Windows related mess.

**Comment by narration-sd** [comment]
James, it's seldom that something you find out and communicate isn't useful, sometimes to a surprising   number of others. So thanks for doing it.

I had an interest in Nanobox a while back when they started, and tried it out. On Win10 my memory is  that it worked then. Now your post made me realize another possibility, but dcouldn't quite understand how you got a resolution here. A few trackdowns, and find, unfortunately:

- The way you got it to work was by RE-enabling SMBv1. Which as you say in your postings elsewhere, is  such a well-known internet security hazard that MS automatically defeats it these days on any maintained machine. So this doesn't sound an idea for most, anyway.
- Nanobox itself has apparently boxed itself up behind a wall, gotten rid of the fremium, open facts business model, and is now one of those 'let our salesman call you' kind of operations. These are typically very overpriced, tricky so that consulting is involved to even get it to work, and for big boy companies. Unless I really missed something, but that's how their site presents.

So, it was great to see you figured the problem out, and also great to discover rapidly why I'm not going to be able to use this path -- the only thing further I think you could have done would have been to be clear about the SMB hazard here. You did that on the Nanobox forum, and so I found it there.

Take care, and I hope the working situation is also fully workable for you. Or, maybe an alternative, depending on what you use Nanobox for? Matt Stein has just put me on to DDEV for a containerized development environment as he likes, and I'm thinking about it, could be a backstop anyway for the Vagrant boxes I've long ago tamed to great performance, using them daily, but which have their own wanderings to problems.

Best fortune,
Clive

**Comment by narration-sd** [comment]
DDEV, if you want to have  a look,  is [here](https://www.drud.com/).
