### ISSUE TITLE
Entry On Front-end But "Not Found 404" On Backend

### ISSUE THREAD

**Issue by theskyfloor** [craftcms/cms#4006]
### Description

I have an entry that disappeared on the backend section when I am trying to view it in it's section type it is not listed. I can see it under All Entries but clicking on the link produces a 404. Everything I can see in the DB looks normal.

### Steps to reproduce

1. As described, have no idea how to reproduce in another installation

### Additional info

- Craft version: 
- PHP version: 7.3.3
- Database driver & version: PostgreSQL 10.7
- Plugins & versions:

**Comment by brandonkelly** [comment]
What version of Craft are you running? And can you try updating to the latest release (3.1.19) and see if that fixes it? Otherwise, the easiest way for us to help is if you send in a database backup, your composer.json and composer.lock files, over to support@craftcms.com , and point us to the offending entry.

**Comment by theskyfloor** [comment]
It didn't fix it. Dump coming

**Comment by theskyfloor** [comment]
Sent.

**Comment by theskyfloor** [comment]
Any luck on this? Thanks!

**Comment by olivierbon** [comment]
Fixed via support
