### ISSUE TITLE
Add limit functionality to category fields

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#4034]
### Description
Entry fields allow you to set a limit:

![screenshot](https://user-images.githubusercontent.com/6672331/54835535-33e84980-4cba-11e9-80e4-d70cb425d84e.jpg)

Category fields do not seem to offer this.

### Additional info

- Craft version: Craft CMS 3.1.19

**Comment by brandonkelly** [comment]
Categories fields have a “Branch Limit” setting. If your category group is limited to 1 level, then Branch Limit operates identically to Limit. Otherwise, it is a limit on the number of unique branches in the hierarchy that can be selected, which is the only practical way we can allow a limit to be set on hierarchical category groups. (Craft 2 had a Limit setting like Entries fields and it caused a lot of confusion, because it wasn’t possible to select a nested category when Limit was set to 1, for example.)

**Comment by jamiewade** [comment]
@brandonkelly Thanks for the clarification, Brandon.
