### ISSUE TITLE
Craft CMS super slow every now and then; information_schema problems?

### ISSUE THREAD

**Issue by shuckster** [craftcms/cms#4037]
### Description

The following SQL query runs "every now and then" throughout the day on my Craft CMS site. It takes between 20 and 30 seconds to run whenever it does.

Apparently, the speed has something to do with accessing the `information_schema` table. Unfortunately, since I'm on a shared server, there's no way I can either `optimize tables` or play around with global variables like `innodb_stats_on_metadata`, which seems to be a common solution to this.

Is there anything else I can try please?

    SELECT `kcu`.`CONSTRAINT_NAME` AS `name`,
           `kcu`.`COLUMN_NAME` AS `column_name`,
           `tc`.`CONSTRAINT_TYPE` AS `type`,
           CASE
               WHEN NULL IS NULL
                    AND `kcu`.`REFERENCED_TABLE_SCHEMA` = DATABASE() THEN NULL
               ELSE `kcu`.`REFERENCED_TABLE_SCHEMA`
           END AS `foreign_table_schema`,
           `kcu`.`REFERENCED_TABLE_NAME` AS `foreign_table_name`,
           `kcu`.`REFERENCED_COLUMN_NAME` AS `foreign_column_name`,
           `rc`.`UPDATE_RULE` AS `on_update`,
           `rc`.`DELETE_RULE` AS `on_delete`,
           `kcu`.`ORDINAL_POSITION` AS `position`

    FROM `information_schema`.`KEY_COLUMN_USAGE` AS `kcu`,
         `information_schema`.`REFERENTIAL_CONSTRAINTS` AS `rc`,
         `information_schema`.`TABLE_CONSTRAINTS` AS `tc`

    WHERE `kcu`.`TABLE_SCHEMA` = COALESCE(NULL, DATABASE())
        AND `kcu`.`CONSTRAINT_SCHEMA` = `kcu`.`TABLE_SCHEMA`
        AND `kcu`.`TABLE_NAME` = 'resourcepaths'
        AND `rc`.`CONSTRAINT_SCHEMA` = `kcu`.`TABLE_SCHEMA`
        AND `rc`.`TABLE_NAME` = 'resourcepaths'
        AND `rc`.`CONSTRAINT_NAME` = `kcu`.`CONSTRAINT_NAME`
        AND `tc`.`TABLE_SCHEMA` = `kcu`.`TABLE_SCHEMA`
        AND `tc`.`TABLE_NAME` = 'resourcepaths'
        AND `tc`.`CONSTRAINT_NAME` = `kcu`.`CONSTRAINT_NAME`
        AND `tc`.`CONSTRAINT_TYPE` = 'FOREIGN KEY'

    UNION

    SELECT `kcu`.`CONSTRAINT_NAME` AS `name`,
           `kcu`.`COLUMN_NAME` AS `column_name`,
           `tc`.`CONSTRAINT_TYPE` AS `type`,
           NULL AS `foreign_table_schema`,
           NULL AS `foreign_table_name`,
           NULL AS `foreign_column_name`,
           NULL AS `on_update`,
           NULL AS `on_delete`,
           `kcu`.`ORDINAL_POSITION` AS `position`

    FROM `information_schema`.`KEY_COLUMN_USAGE` AS `kcu`,
         `information_schema`.`TABLE_CONSTRAINTS` AS `tc`

    WHERE `kcu`.`TABLE_SCHEMA` = COALESCE(NULL, DATABASE())
        AND `kcu`.`TABLE_NAME` = 'resourcepaths'
        AND `tc`.`TABLE_SCHEMA` = `kcu`.`TABLE_SCHEMA`
        AND `tc`.`TABLE_NAME` = 'resourcepaths'
        AND `tc`.`CONSTRAINT_NAME` = `kcu`.`CONSTRAINT_NAME`
        AND `tc`.`CONSTRAINT_TYPE` IN ('PRIMARY KEY',
                                       'UNIQUE')

    ORDER BY `position` ASC;

### Steps to reproduce

1. Wait a few hours
2. Load site with Debug Toolbar enabled
3. Notice really slow DB query in the log

### Additional info

- Craft version: Craft Pro 3.1.19
- PHP version: 7.2.16
- Database driver & version: MySQL 10.1.38
- Plugins & versions:
    - AsyncQueue 2.0.0
    - Delete Entry Versions  2.0.0
    - Twig Perversion 2.0.7

**Comment by shuckster** [comment]
Seems I've isolated the issue to this function in Yii: `loadTableConstraints()`

It's running the query above, but while it looks impressive it shouldn't take any time to run. Indeed, when I test with just a basic `SELECT * FROM KEY_COLUMN_USAGE;` it takes 7 whole seconds to run. :(

**Comment by brandonkelly** [comment]
Not much we can do about this; that’s a core Yii function that needs to run for things like [upsert()](https://www.yiiframework.com/doc/api/2.0/yii-db-command#upsert()-detail). 

You could increase the schema cache duration from `config/app.php` like this:

```php
<?php
return [
    'components' => [
        'db' => function() {
            $config = craft\helpers\App::dbConfig();
            $config['schemaCacheDuration'] = 60 * 60 * 24; // 1 day
            return $config;
        },
    ],
];
```

(You can also set `schemaCacheDuration` to `0` to have it be cached indefinitely.)

Note that by increasing the schema cache, you’re increasing the risk of running into SQL errors if Craft or a plugin isn’t clearing the schema cache after making a schema change. If that happens you can fix by clearing Craft’s data caches from Utilities → Clear Caches.

Alternatively you could get off of shared hosting :)

**Comment by shuckster** [comment]
Ah, thanks for the tip! I'll give that a go.

And yes, the shared hosting can be a bit of a bind indeed. :D

**Comment by shuckster** [comment]
Just in case someone else uses your example, I had to change the last line from this...

`return $config;`

To this...

`return Craft::createObject($config);`

Thanks again!

**Comment by brandonkelly** [comment]
Sorry, yep! Just updated the original example.

**Comment by shuckster** [comment]
Thanks Brandon.

I just wanted to report back and say that this has *really* worked for me.

I wonder if it's worth mentioning in your docs somewhere? Is it possible to write a plugin that would expose this setting to the UI?

**Comment by brandonkelly** [comment]
Meh… shared hosting is a hacky situation in the first place (quite literally!) so it seems fitting that the fix for this particular symptom of it is a little bit hacky as well (modifying the application config).

**Comment by khalwat** [comment]
Obligatory -> [How Agencies & Freelancers Should Do Web Hosting](https://nystudio107.com/blog/web-hosting-for-agencies-freelancers)

**Comment by shuckster** [comment]
I appreciate your points of view, but I'm disappointed that the discovery of a demonstrable real-world performance improvement can be dismissed so flippantly, because apparently throwing money at the problem should have been the real fix.

Being poor is also part of the real-world, and the company I'm doing this Craft site for was stretched enough to pay for the Pro license in the first place. Yes, I do hope they can one day afford their own dedicated hardware. That time isn't now, but they need something now.

I do understand the argument against unnecessary optimisation. I think riding-out Moore's Law is the right way to solve many of our problems. But as someone who knows what it's like to optimise code for an 8086, hearing this kind of stuff every now and then does grate a bit.

**Comment by brandonkelly** [comment]
You can get a Craft-optimized VPS starting at just $6.25 a month from Arcustech - https://www.arcustech.com/managed/craftcms-hosting/

**Comment by narration-sd** [comment]
Hello Conan, @shuckster ,

Just to add another path, if it's more comfortable with your expertise, I've been running a small site on a DigitalOcean droplet for more than a year that's costing $5/mo, and it's quite zippy. I've also had a lot of work with the Arcustech guys, and that's a very good answer if you (or the client) want keeping up a safe Linux out of your hair.

I think the reason for the answers dismissive of shared hosting is that this is quite often kind of a disaster for more than a static website. I did a lot of that early on Craft, and made it work, but not without going down to bare metal often enough with top-tier fellows who could deal about the things they hide.

Often those are what makes them feel security themselves, for a business under constant attack, which happens anywhere in the world. They don't just sniff, they crush executions for obscure reasons, they clear out or block Ajax returns, they bring down your attached email because their IPs get blacklisted due to nefarious others also on the servers. 

Someone 'here' (a sharp and experienced guy in France) just brought up one of those he couldn't get to the bottom of, raising as that will a Craft support instance. And I ran across an explained tale of just what  he ran into the other evening -- zapped Ajax silently and with no reason, on GoDaddy. Which is one I actually could make work well, but only in conversation with the accurate persons they actually have.

Which is a roundabout way of saying why even the mature guys around here can show that faraway look, or get bombastic, when the subject comes up. It causes anyone responsible a lot of pain.

Smooth sailing by what's recommended to you, I think, and this should be particularly true for a worthy customer who's not able to pay for a lot of support, or need an undue amount of even donated time.

The other thing is that bringing what Brandon et al are, into the world and keeping it even a small step ahead of the advancing needs it serves, is an experience with its margin of stress. In raising families, in colors of intents, in going the extra mile so many times -- and in donating privileges on what they've built to good causes, I have a long experience seeing Brandon, Brad, and the others as particularly decent and upstanding persons. 

And then you'll know from an amount of experience, sometimes there are moments when the intent slips from being a shield, and what is actually a frustration pops out. We learn to look past, keep the bigger picture out there, don't we.

Best,
Clive

**Comment by shuckster** [comment]
Thanks for the recommendation, Brandon. Believe it or not, it's still more than we're paying currently, but it's the best-priced VPS I've seen.

If any of Clive's points ring with you, I didn't mean to offend. I just had an angry moment. I have the luxury of looking at the problem from the outside and complaining about it from a birds-eye view, and in such cases the bird-guano isn't necessarily going to land on the responsible person!

I'm not going to apologise too much for my original feelings, though. I mean, this particular issue can be seen as a regression, since there's a specific version number it can be traced back to. I know it's from Yii, but the good folk at Craft are responsible for implementing Yii and inheriting its baggage.

Anyway, in trying to turn this into a more helpful reply, I guess what I'm saying is that, for me, the bigger picture that Clive talks about also includes taking performance regressions seriously. Even on my own hardware, the performance hit of this thing is measurable. On sites with many more transactions than my little client has to deal with, surely this translates to wasted electricity of not insignificant amounts? Would be good for the world in general to save on that. :)

**Comment by verbeeksteven** [comment]
With CraftCMS 3 you need

```
<?php
return [
    'components' => [
        'db' => function() {
            $config = craft\helpers\App::dbConfig();
            $config['enableSchemaCache'] = true;
            $config['schemaCacheDuration'] = 60 * 60 * 24; // 1 day
            return Craft::createObject($config);
        },
    ],
];
```
