### ISSUE TITLE
project-config/sync wrong exit code at failure

### ISSUE THREAD

**Issue by jorenvanhee** [craftcms/cms#4069]
### Description

`craft project-config/sync` can show an error without returning the right exit code. We use a deploy script and it just continued at the error. Here's a screenshot.

![Screenshot 2019-03-28 at 16 22 16](https://user-images.githubusercontent.com/231202/55170364-ace21800-5176-11e9-910a-a975bead95ac.png)

We've had project config errors before that stopped the deployment process.

I can't reproduce the issue but maybe it is something obvious, fingers crossed. Feel free to close the issue if you need it to be reproducible.

### Additional info

- Craft version: 3.1.15
- PHP version: 7.2

**Comment by brandonkelly** [comment]
Here’s the exact code where your exception is getting run:

https://github.com/craftcms/cms/blob/3.1.15/src/console/controllers/ProjectConfigController.php#L61-L67

As you can see, immediately after that error is output, the controller returns `ExitCode::UNSPECIFIED_ERROR` (which is set to `1`).

From the looks of it, you’ve got a post-deploy script that is running multiple commands. Most likely that script is just not checking the response codes, and continues on even if a `1` is returned.

Regarding the error you’re getting, _most_ project config sync errors happen because the database is out of sync with the project config to begin with, which can happen if any changes are made to the database directly without going through the appropriate service that would have also updated the project config in the process. If that’s the case, you can fix it by rebuilding your project config based on the latest database data, by running the `./craft project-config/rebuild` command (added in Craft 3.1.20). I’d also recommend you go through the steps listed in [Enabling the Project Config File](https://docs.craftcms.com/v3/project-config.html#enabling-the-project-config-file) in the Project Config docs, to ensure all environments are in sync with each other, across databases and project.yaml files.
