### ISSUE TITLE
Make singles translatable in CP

### ISSUE THREAD

**Issue by vandres** [craftcms/cms#4077]
### Description

I use translate keys for all my labels in the CP. The CP in mostly all cases translates these labels correctly from the translations-files. But singles are not translated in every place.

<img width="562" alt="Bildschirmfoto 2019-03-30 um 13 46 05" src="https://user-images.githubusercontent.com/1436383/55280354-a24c8d80-52f2-11e9-854e-e66f08654509.png">
<img width="550" alt="Bildschirmfoto 2019-03-30 um 13 46 16" src="https://user-images.githubusercontent.com/1436383/55280355-a24c8d80-52f2-11e9-8fc3-104b207182ca.png">
<img width="916" alt="Bildschirmfoto 2019-03-30 um 13 50 09" src="https://user-images.githubusercontent.com/1436383/55280369-ce680e80-52f2-11e9-840d-78337e9c71e2.png">
<img width="622" alt="Bildschirmfoto 2019-03-30 um 13 50 19" src="https://user-images.githubusercontent.com/1436383/55280370-ce680e80-52f2-11e9-9496-72439535a69f.png">

### Steps to reproduce

1. Use a translate key like section.home and translate in a translation file
2. Click through the CP

### Additional info

- Craft version: 3.1.x
- PHP version: 7.2.x
- Database driver & version: -
- Plugins & versions: -

**Comment by brandonkelly** [comment]
When you create a Single section, three things are created:

- The section
- An entry type
- The one entry that belongs to the section

Like other entry types, Single sections’ entry types give you the option on whether to show a Title field, or have the title be dynamically generated based on a Title Format. By default, Single sections will opt to _not_ show the Title field, and use this as the default Title Format:

```
{section.name|raw}
```

So when you see the section name not getting translated, that’s because in those cases it’s technically not the section name; it’s the entry title, which had been dynamically generated based on that Title Format.

Craft doesn’t translate entry titles because they are translatable fields to begin with, so we aren’t going to change anything on our end here.

One thing you could do is change your Title Format to this, though:

```
{section.name|t|raw}
```

Adding that `|t` filter in there will cause the dynamically-generated entry titles to be saved to the translated section names.

**Comment by vandres** [comment]
@brandonkelly Ok, I understand. But why is the Single translated in the Sections list? Isn't that inconsistent?

**Comment by brandonkelly** [comment]
Because that is the section name, not the entry title.
