### ISSUE TITLE
Request: Allowing for same handle usage for multi-sites that require multiple languages

### ISSUE THREAD

**Issue by kellyannmcnamara01** [craftcms/cms#4099]
**Context:**
We are currently using the multi-site functionality. Site A and Site B are two different designs and therefore use two different site handles and template folders. Our client has requested we offer Site A in English, Spanish and French. Site B does not have any other languages. Due to the new way languages are set up in Craft 3 we have to create "new sites" for each language Site A comes in but the design of Site A and the templates within Site A will not change visually.

**Current requirement for template setup:**
`templates/
|– – site_a
|– – site_a_en_ca
|– – site_a_fr_ca
|– – site_a_es_us
|– – site_a_es_mx
|– – site_b`

**Problem:**
We currently have to duplicate Site A's template folder four more times when we aren't changing the code, creating duplicated code within our project. This is not ideal and can become out-of-sync easily if someone doesn't update all the template folders when making changes.

**Would love to see:**
We would love to use the same handle for different sites, so they can share the same templates and then have languages queue off of the language shortcodes.

**Template setup we would love to see:**
`templates/
|– – site_a
|– – site_a/es_us (if there's a unique layout required)
|– – site_b`

Craft Verison: 3.1.14

_– Side note, we are loving Craft 3!_

**Comment by brandonkelly** [comment]
We couldn’t possibly allow multiple sites to have the same handle, otherwise when you specify you want to load content from a specific site by its handle, that handle would become ambiguous.

That said, it sounds like #3101 would work nicely for you (site group-specific templates) if you were to organize the “Site A” sites and “Site B” site into two different site groups. I’ve just gone ahead and added it to the 3.2 milestone.
