### ISSUE TITLE
Add a permission for users to purchase plugins

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#4132]
Currently the only way that a client can purchase licenses for Craft and Plugins is to give them full Admin access, something that I don't believe clients should ever have. Could we have a permission setting so they're able to pay for licenses without giving them access to settings, utilities, fields etc?

**Comment by Anubarak** [comment]
The thing is: Licenses are stored in the project config thus your live environment needs the ability to change those settings -> as soon as you sync your environments the key will be overwritten. Creating an exception for this use case doesn't seem to be a good way either and in my opinion clients should not have the ability to buy plugins since they can't install them anyway. So buying only plugins that are already installed seems to be the only way but this is still in conflict with the project config.

A workflow I could imagine would be to let them buy the key via web plugin store and inform the system admin about it so he can insert it or something.
Just providing the ability to buy a key with an additional permission could cause too many conflicts in the deployment workflow.

**Comment by darylknight** [comment]
Yeah I understand what you're saying (although I'm not using project config) - but whatever the solution is, the current problem is that you have to make a client a full administrator if you want them to pay for their own plugins instead of re-selling them.

**Comment by Anubarak** [comment]
Your client can buy the license and send you the key as well. There is no need to grant them admin permissions

**Comment by brandonkelly** [comment]
We are working on making it possible to buy things on [id.craftcms.com](https://id.craftcms.com) anonymously, at which point we will give in-app shopping carts a link you can share with your client, so they can access the same cart in a browser, and complete the purchase there.
