### ISSUE TITLE
Make Craft trigger re-deploy via AWS CodePipeline

### ISSUE THREAD

**Issue by bobbymart1n** [craftcms/cms#4144]
### Description
I'm using Craft CMS as a headless CMS for Gatsby. What I want to do is...when I make a new post through the CMS and click save, trigger a re-build and deploy via AWS CodePipeline. Would anyone know how to go about doing that? I'm having trouble finding anyone who is trying to do the same. My site files are stored in an S3 bucket that I have CI setup on and was wondering how I could setup something similar with Craft after making a new post through the CMS.

I hope that this is the right place for this type of discussion. 

### Additional info

- Craft version: 3.1.22
- PHP version: N/A
- Database driver & version: N/A
- Plugins & versions: N/A

**Comment by narration-sd** [comment]
Bobby, I won't be able to suggest on AWS, with or without Gatsby's thoughts, but I can suggest something that I'm imagining will be a lot closer to what persons making Craft content for Gatsby (and others...) would really like, if that will be a help.

Here's a tweet with a link to a short screen movie of Live Vue, operating after one of the members of our Beta group had just got it up and running.  

 [https://twitter.com/narration_sd/status/1115792876862967809](https://twitter.com/narration_sd/status/1115792876862967809)

Live Vue is a plugin that will be up in the Craft Store shortly -- I am running faster than I can ;)

I think we know from the way persons respond to the web, and especially from software experience that seeing what you do in 'instant' real time is very pleasant, and effective just as much.

Live Vue has none of the awkwardness or delays any push-to-server solution must, because it's (very properly) integrated with Craft. It's doing Gatsby for first release, with other platforms to follow.  I just did a Gridsome website for release, and that will likely be next for its fluidity and porting ease. 

Why so long in gestation (it's been working well and shown to the Craft Bend fellows a year ago)?

The key is in how easy it can be to set up. The last breakthroughs for this came through careful listening with the Beta clan, and from some other background I have. I'm very satisfied, even a little surprised, and I think that will lbe a general reaction as this gets out to the community. How I did it will become a product of its own, because it's something I've pushed for many times in other Craft areas, and now can contribute a tool.

How soon? Soon. I'm doing the last part of in-Craft presentation I think this special setup tool needs to accomplish best what it does, alongside the release site and (very much simplified) documentation. No doubt a little loss of hair getting the Store to cooperate the first time. So you can see where my thinking is at present.

**Comment by brandonkelly** [comment]
@bobbymart1n If there’s a webhook URL you could hit to trigger the site regeneration? If so you could use our [Webhooks](https://plugins.craftcms.com/webhooks) plugin to solve this.

**Comment by jurriaanr** [comment]
No hands on experience, but I believe S3 can be a trigger for code build. So uploading a simple file on entry save a s3 bucket could perhaps trigger the build process?

**Comment by angrybrad** [comment]
@bobbymart1n I think [Brandon's suggestion](https://github.com/craftcms/cms/issues/4144#issuecomment-483815295) is probably the cleanest.

I don't know what CI you're using, but (for example), buddy.works has a way to trigger a pipeline build using a webhook: https://buddy.works/blog/webhook-pipeline-trigger

**Comment by bobbymart1n** [comment]
Awesome, I'll try this out. I appreciate the feedback!
