### ISSUE TITLE
`omitScriptNameInUrls` is not overriding `usePathInfo`

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#4281]
### Description

There are two general config settings:
 - `omitScriptNameInUrls`
 - `usePathInfo`

When `omitScriptNameInUrls` is set to `true`, it should override the `usePathInfo` value (automatically treating it as `true`).

Indeed, this is how the docs describe the behavior:

<img width="775" alt="Ω 2019-05-17 at 9 48 09 AM" src="https://user-images.githubusercontent.com/5309692/57943577-3a91d800-7889-11e9-80ec-692fa1000e1d.png">

Which is logical... because if we're using non-query base URLs, then `usePathInfo` should inherently be considered `true`.

### Steps to reproduce

1. Use `?p=something` in a URL.
2. Toggle the `omitScriptNameInUrls` config value.
3. Toggle the `usePathInfo` config value.

Notice that `omitScriptNameInUrls` does not override `usePathInfo`. An error will be thrown if `usePathInfo` is not `true`.

<img width="805" alt="Ω 2019-05-17 at 9 59 25 AM" src="https://user-images.githubusercontent.com/5309692/57944025-842ef280-788a-11e9-8323-616179ad9497.png">

### Additional info

- Craft version: 3.1.27

**Comment by brandonkelly** [comment]
By “path info” we are referring to the Apache concept that is enabled via its [AcceptPathInfo directive](https://httpd.apache.org/docs/2.4/mod/core.html#acceptpathinfo). When that’s enabled, if you were to access the following URL:

```
http://example.com/index.php/foo/bar
```

The `foo/bar` bit would be stripped out of the URL and made available to PHP as a `PATH_INFO` environment variable.

(Worth mentioning that Nginx doesn’t have a similar concept.)

So the only time Craft would even consider whether it should set the path part of a URL in the “path info” (after the script filename), as opposed to a `p` query string param, is if the URL it’s generating has a filename to begin with.

Said differently, it would not be possible to set a “path info” URL component if there is no filename to begin with.

> Indeed, this is how the docs describe the behavior:

The docs say that `usePathInfo` only works when `omitScriptNameInUrls` is **false**, because that’s the only time it could even be an option.

**Comment by lindseydiloreto** [comment]
Thanks Brandon. Though I'm not sure I understand.

In Craft 2, I could do this... `/mypage?p=1` without any problems. In Craft 3, that throws an error (see above).

Setting `usePathInfo` to `true` fixes it, and the error goes away. This happens _regardless_ of whether `omitScriptNameInUrls` is set to `true` or `false`.

I am on Valet, which I believe is strictly Nginx.

**Comment by brandonkelly** [comment]
Issue is that `p` is the param Craft uses internally to define the requested path. So the above URL is actually telling Craft to load the URI `1` rather than `mypage`. Either change that parameter name, or change your [pathParam](https://docs.craftcms.com/v3/config/config-settings.html#pathparam) config setting to something else.

**Comment by lindseydiloreto** [comment]
Right, that part makes sense to me.

I guess I'm wondering, why did it work on Craft 2 and not Craft 3? Why does `usePathInfo` seem to fix the problem (on Nginx)?

**Comment by brandonkelly** [comment]
Craft 2 and 3 are almost identical in terms of how they tread those config settings, so I’m not really sure, and suspect maybe it’s more of an environmental thing than the Craft version. In any case, if you are on Nginx than `usePathInfo` is definitely not going to ever work how it is intended to work, because it is for a concept that only exists on Apache.

**Comment by lindseydiloreto** [comment]
Weird, setting that to `true` is definitely solving my problem.

Alright, I'll take another approach. Thanks Brandon! 🍺
