### ISSUE TITLE
Default week start day is still Sunday even if setting is overridden

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/cms#4293]
### Description

Default week start day is still _Sunday_ even if setting is overridden (example: _Monday_).

### Steps to reproduce

1. In _config/general.php_, the `defaultWeekStartDay` value is set to `1` (Monday)
2. In _admin/myaccount#prefs_ the `Week Start Day` field is set to `Monday`
3. On front-end, while browsing a French localized website `craft.i18n.getLocaleData().getWeekDayNames` still outputs `Sunday` as first day instead of `Monday` (I know this method is deprecated, but I didn't found the equivalent for Craft 3 🤷‍♂️)
4. I'm also getting the same value within plugins (for example, _Calendarize_)

### Additional info

- Craft version: Craft Pro 3.1.27
- PHP version: 7.1.8
- Database driver & version: MySQL 5.6.35
- Plugins & versions: Calendarize 1.2.12

**Comment by brandonkelly** [comment]
The `defaultWeekStartDay` config setting only sets the default value for the Week Start Day user preference, for users that haven’t saved their own account settings yet. And the Week Start Day preference only affects what day comes first within date pickers in the Control Panel. It won’t change the order of days returned by `getWeekDayNames()`, or have any effect on the front-end. You would need to configure whatever calendar view you’re using on the front-end separately.

> (I know this method is deprecated, but I didn't found the equivalent for Craft 3 🤷‍♂️)

As the deprecation error says, you should use `craft.app.locale` instead of `craft.i18n.getLocaleData()`. They both return the same thing, so anything passed that point would be the same – e.g. `craft.app.locale.getWeekDayNames()`.
