### ISSUE TITLE
Craft 3.2 Requires PHP 7.1

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/cms#4365]
Just a heads-up, looks like a Symphony/YAML upgrade is requiring PHP 7.1+ which will obviously bump Craft's [system requirements](https://docs.craftcms.com/v3/requirements.html).

![Screen Shot 2019-06-05 at 10 34 15 AM](https://user-images.githubusercontent.com/3707869/58969570-8c899780-877d-11e9-92d5-184fc41e9b31.png)

It's taking adavantage of the new [Nullable Types](https://php.net/manual/en/migration71.new-features.php) feature in PHP 7.1.

```
ParseError: syntax error, unexpected '?' in /fake/path/vendor/symfony/yaml/Inline.php:660
Stack trace:
0 /fake/path/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Volumes/ProBea...')
1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
2 /fake/path/vendor/symfony/yaml/Dumper.php(62): spl_autoload_call('Symfony\\Compone...')
3 /fake/path/vendor/symfony/yaml/Yaml.php(99): Symfony\Component\Yaml\Dumper->dump(Array, 20, 0, 0)
4 /fake/path/vendor/craftcms/cms/src/services/ProjectConfig.php(1390): Symfony\Component\Yaml\Yaml::dump(Array, 20, 2)
5 /fake/path/vendor/craftcms/cms/src/services/ProjectConfig.php(654): craft\services\ProjectConfig->_storeYamlHistory(Array)
6 [internal function]: craft\services\ProjectConfig->saveModifiedConfigData(Object(yii\base\Event))
7 /fake/path/vendor/yiisoft/yii2/base/Component.php(627): call_user_func(Array, Object(yii\base\Event))
8 /fake/path/vendor/yiisoft/yii2/base/Application.php(389): yii\base\Component->trigger('afterRequest')
9 /fake/path/public_html/index.php(21): yii\base\Application->run()
10 {main}
```

For those of us who run Ubuntu/Debian or CentOS LTS releases, I guess this will bump our server upgrades ahead of schedule. ;)

**Comment by DomLip94** [comment]
> It's taking adavantage of the new Nullable Types feature in PHP 7.1.

Wouldn't say new! 7.1 EOL's in December!

**Comment by brandonkelly** [comment]
I just verified that noting in Craft 3.2 is _requiring_ PHP 7.1+, even in the new dev dependencies. The `symfony/yaml` package, for example, is required at `^3.2|^4.0`, which means 4.0+ will be used if possible (e.g. if running PHP 7.1+), but otherwise 3.2+ will be used as a fallback.

If you’re getting syntax errors, maybe your project’s base `composer.json` no longer has [this line](https://github.com/craftcms/craft/blob/master/composer.json.default#L15), which tells Composer to install PHP 7.0-compatible dependencies regardless of what the system is running:

```json
"platform": {
  "php": "7.0"
}
```

We include that line to protect you from this sort of thing, where maybe you had PHP 7.1 or 7.2 installed locally where the `composer.lock` was generated, but something lower installed on production.

**Comment by RitterKnightCreative** [comment]
@DomLip94 New in PHP 7.1 but yes not new in general.
