### ISSUE TITLE
Root level section entry doesn't supply correct pathname for headless live preview.

### ISSUE THREAD

**Issue by dictions** [craftcms/cms#4377]
### Description

The live preview uses a different URI for root level sections (homepage with empty section URI).

### Steps to reproduce

1. Create a single section with an empty URI, Title `Home`, handle `home`
2. Leave URI as blank, and add a template path.
3. Live preview, the requested URL is `/__home__`. Rendering out `{{ craft.request.path }}` also outputs `__home__`.

### Additional info

- Craft version: `^3.2.0-beta.1`
- PHP version: `7.0.31`
- Database driver & version: `MySQL 5.7.23`
- Plugins & versions: 
<img width="634" alt="Screenshot 2019-06-06 13 33 28" src="https://user-images.githubusercontent.com/4307278/59057297-b0250e80-885f-11e9-9887-5bf31ee17e2b.png">

**Comment by dictions** [comment]
Also related, it appears `{{ craft.app.request.isLivePreview }}` always returns an empty string now.

**Comment by brandonkelly** [comment]
This is fixed for the next release, thanks for reporting!

It’s expected that `craft.app.request.isLivePreview` would return `false` when previewing entries in Craft 3.2. Generally when templates need to check that, it’s because they need to do something hacky to work around Live Preview bugs (e.g. #1787 and #2801), and those workarounds are no longer necessary in Craft 3.2, and those hacks would actually start breaking if `isLivePreview` continued to return `true`.
