### ISSUE TITLE
[3.2] Confusion over "Update Entry" button

### ISSUE THREAD

**Issue by tinchalamo** [craftcms/cms#4384]
### Description
I've done some informal testing around the office with 3.2 and there is some confusion when creating a new entry. The button to save a new entry reads "Update Entry". I've seen people go under the dropdown to "Save as new entry" instead. 

I propose that the initial state of creating a new entry the button should read "Save Entry" and then after that, it reads "Update Entry".

**Comment by theskyfloor** [comment]
Second this!

**Comment by brandonkelly** [comment]
Craft 3.2 Beta 2 (ETA tomorrow) should fix this. Now when creating a new entry, it is initially saved as an “unsaved draft”, and the UI will resemble that:

- The page H1 will say “Create a new entry” rather than “Edit entry”.
- The submit button label will be “Save entry” rather than “Update entry”.
- There won’t be an action menu for duplicating the entry or deleting it.

From there you can either click “Save entry” to convert it to a real entry, or just discard it. Craft will eventually delete the draft via garbage collection, per the new `purgeUnsavedDraftsDuration` config setting (unsaved drafts must be 30 days old by default, before they will be purged).
