### ISSUE TITLE
[3.2] Live preview doesn’t keep scroll position

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#4410]
### Description

It seems like the new Live Preview in 3.2 isn’t able to keep the scroll position any more.

### Additional info

- Craft version: 3.2.0-beta.2

**Comment by brandonkelly** [comment]
Content previewing has changed in a lot of ways in Craft 3.2. One of them is that preview iframes are normal iframes now, with a tokenized URL in the `src` attribute. Previously Craft would take the rendered HTML and build its own iframe document with it. The new way offers a couple advantages though:

- It’s faster.
- Root-relative URLs within the HTML now always resolve to the correct host, whereas before they would always resolve to the main window’s host, rather than the selected site’s host.

The only downside to it was that it’s not impossible to maintain scroll position if the selected site’s host is different than the main window, as JavaScript doesn’t allow you to call `reload()` or `scrollTo()` on cross-domain iframe.

So the tl;dr is that this is expected behavior if you are previewing a site with a different host name than the main window.

**Comment by narration-sd** [comment]
Given what Brandon @brandonkelly says, I'll post a js solution later at
home. It's pretty easy, and had to make it because of something Gatsby
'just did'...

**Comment by narration-sd** [comment]
@carlcs  Carl, here's a a little scroll memory package as promised: [ScrollMemNonEs6.js](https://gist.github.com/narration-sd/a10c5855cb0c06d562d7eb290b3251d3)

I've just carved out what I'm doing for Live Vue previews in ES6/React, as presently about to release for Gatsby,, which has been very smooth. This should be as the title suggests, a version suitable for ordinary JS, as used in Craft and Twig.

You may not need all the helper functions, and anyway, please feel free to modify this however appeals to you, and/or add suggestions as how it's best applied. That result is likely to be even better for Twig and Craft, and you can add it to the gist so others can share.

Best, Clive

**Comment by carlcs** [comment]
@narration-sd thank you! I didn’t even know that window triggers unload events, this definitely is making creative use of it. With the event listener I’m using I can see the page scrolled to the top for a split second, so I’m thinking about adding a fade in animation for those preview requests.

@brandonkelly I didn’t realize this is due to me using different hosts for my site and the CP, makes this issue far less problematic. Maintaining the scroll position is pretty important, so I’m glad to see it’s here to stay.

Would you be open to release something like Clive’s helpers as an official package on npm? I think it would be nice to have something easy installable, somthing that you could reference in docs.

**Comment by brandonkelly** [comment]
Certainly a clever script, @narration-sd, and I agree we should be recommending that in the docs. Would you be open to publishing that as an NPM package? And if not, would you be OK with us using it (with credit)?

**Comment by narration-sd** [comment]
Ah, @brandonkelly, think you should just take it, and welcome, esp. as I
think you'll want to internalize it.

For example, Carl would like perhaps to be able to reset a page to top, on
first edit opening. I've done related on the Vue version of Live Vue, but
keeping scroll positions around a while for convenience, against a timeout
via a cookie.

I was considering such a thing. would want to be consolidated in one of
Craft's cookies, though then thought after could just stick it in with the
scroll position, changing over the an object.

But you see my point - there will be needs, so better this actor is inside
Craft where you can control and extend it, no?

Sleep now, then see what you think on the morrow.

**Comment by brandonkelly** [comment]
We wouldn’t want to inject it into the HTML automatically; just make it available as a recommended thing to include in your JS build. Perhaps it would also make sense to bundle a helper function for getting the token out of the query string, while we’re at it.

**Comment by carlcs** [comment]
In that script @narration-sd is storing separate values for every previewed URL by using `window.location.pathname` in the key. This is because there’s currently nothing in place to reset the scroll position to the top when a new preview session is started. With this trick it at least makes sure that you don’t open a preview with the scroll position stored from a different entry.

I was thinking about possibilities to improve this, and the only idea I had would require adding another param to the query string only for the first request that is made. Something like `?token=aaa&initial` that tells the script that we don’t want to go to a stored position.

**Comment by narration-sd** [comment]
@brandonkelly  Yeah, but just take it, huh, with my blessings? indeed this kind of thing, is just what I've spent the many months designing support out of Live Vue. Where the need for such infrastructure is even (by far) larger than I told you. 

My deviation last night was seeing one further way the robot could and needed to get smart. Now it's just getting the doc (and positioning) written on line, because I've thought  the responsibility and  thus that clearly out. Nextt item supports my view....

@carlcs  Carl, just too tired and on phone to get it in last night, but your interest in keeping straight two actual refreshes is something I also had to do -- it'll soon be clear from source why and where.  That's why this little library has the service functions as it does. I don't actually set up the events except on the proper content display to remember, so when only it closes, we trap. React lifecycle and how I use it with events I produce makes an evident  point, but am sure you can identify one for yours.

The other aspect is where you were Discording to me about a flash of unwanted content. I just combine css hiding in not displaying that. By experience  and for experience, it's felt a lot better than using fades, which I also tried out for a while. 

You can hit a fairly narrow critical fade length/shape regime for a reasonably usable look, but then that doesn't really allow previews their snappiness, which is important in overall feel. Plus, the latency due to browser layout calculations/internal holdoff of threads we know happens, plus any actual latency in the wire or routers/cable modems etc., means you're going to see short bursts of text anyway from fast typing or other actions, and again, this feels best just allowed to snap up as it does.

I kind of went around the circle on this, trying things out -- but anyway, the need to allow or make adjustments is why I'm suggesting to Brandon he keep the ability inside, which fits also his healthy instinct to separate, componentize really, no?

**Comment by narration-sd** [comment]
(in short  discussion at first, _thought => thought out_, and _doc: becomes very succinct_ (because architecture mutations, and that much of it is  hidden until presented with a little wit by Hal.)

I should  know better by now to use the Preview here rather than after-send editing, but bad habits die hard, don't they...

**Comment by khalwat** [comment]
@brandonkelly Was this included with 3.2 in some capacity?

**Comment by brandonkelly** [comment]
@khalwat I haven’t released a scroll position maintainer library on npm or anything yet, no. But you could use @narration-sd’s code as a starting point if you need it. (Craft 3.2 will try to maintain scroll position for same-host preview URLs, though.)
