### ISSUE TITLE
Project config should alphabetize entries.

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#4425]
### Description

Project config diffs can get unwieldy and ugly pretty quickly. In an enterprise environment where multiple developers are contributing to a Craft project, this can create some very ugly and misleading diffs of the `project.yaml` file. Alphabetizing entries would help mitigate this.

**Comment by brandonkelly** [comment]
We used to sort everything in the project config, but that led to a couple issues such as #3997, so then we switched to only sorting top-level items.

As of the next release, we will also start sorting any arrays when all of the nested keys are UIDs, which seems safe.

**Comment by tprobinson** [comment]
To add to @ryanpcmcquen 's description of the unwieldy diffs, this can also cause merge errors-- if two sections that contain mostly the same stuff are moved around, Git's merger can tend to really munge them up since it's not data-structure-aware.

@brandonkelly With that issue you referenced, some of Craft's resources have keys like `sortorder`, right? Would it solve this to extend that approach to all (or more) things?

**Comment by brandonkelly** [comment]
@tprobinson Yes, but the issue is that it was a breaking change for plugins as well. We’ll probably go back to sorting all indexed arrays by keys again in Craft 4. In the meantime I suspect that 1e808dc6624715bd5d5731007575929cca713681 is going to go a long way in helping.
