### ISSUE TITLE
Request: Add option to completely overwrite `config` and `configMap` in `info` table.

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#4464]
### Description

Occasionally, we end up in a state where a new branch has been deployed to an environment, and Project Config has been 'synced', but there are still fields or changes that exist in `project.yaml` that do not appear in the environment. The only reliable workaround we have found for this scenario, is to:

- Empty `config` and `configMap` in the `info` table.
- Sync Project Config again.
- Run any other migration/provisioning steps.

It'd be nice if Craft had a built-in 'nuclear' option, to overwrite these fields completely.

### Additional info

- Craft version: 3.1.x
- PHP version: 7.x

**Comment by ryanpcmcquen** [comment]
@brandonkelly, #4465 should solve this.

**Comment by brandonkelly** [comment]
@ryanpcmcquen Thanks for the PR! We will need to take some time to review it and think over the ramifications, once 3.2 is out the door.

**Comment by andris-sevcenko** [comment]
@ryanpcmcquen have you tried running `./craft project-config/sync --force` to resolve that? (https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#3123---2019-04-16)

**Comment by ryanpcmcquen** [comment]
@andris-sevcenko, `--force` is not working for my currently broken state. The _nuclear_ option does work though.

**Comment by brandonkelly** [comment]
Ah good point @andris-sevcenko.

@ryanpcmcquen This is the intended effect of using `--force`. If it’s not working, please email a database backup and your `composer.json`, `composer.lock`, and `config/project.yaml` files over to support@craftcms.com so we can look into why it’s not working.

**Comment by ryanpcmcquen** [comment]
@brandonkelly, email sent. This issue should probably remain open until we've determined this is _not_ an issue.

**Comment by andris-sevcenko** [comment]
What this issue describes is pretty much what the `force` option does.

When using `force`, the `project.yaml` file is loaded and:
* for every entry in the file but not in internal version, it's added to the site
* for every entry not in file but in internal version, it's removed from the site
* for _every_ other entry it's treated like an incoming change.

This, in essence, should be solving the problem you have.

So, if it's failing for some reason, then that's an issue with the `--force` option. Or, rather, a problem with the project config serialized in the database. Since we have you now over the email about this specific thing, keeping this open would have no benefit.
