### ISSUE TITLE
Duplicate slug on "save as new entry"

### ISSUE THREAD

**Issue by mstichel** [craftcms/cms#4478]
### Description

Duplicate an entry from the entries list works fine. Duplicate via 'save as a new entry' on detail view also duplicates the slug (which must be unique, right?).

### Steps to reproduce

1. Select and edit an entry
2. Choose 'Save as a new entry' on right upper corner
3. Check both slugs

### Additional info

- Craft version: Craft Pro 3.1.30
- PHP version: 7.2
- Database driver & version: MySQL

**Comment by brandonkelly** [comment]
This should have been fixed in 3.1.27 per 5858b0e5a424395f47042b7872224c5c011a09a4, and I confirmed it’s working for me in 3.1.33.

It will only work if the section’s Entry URI Format contains `{slug}` though. Otherwise there would be no point in incrementing the slug.

Try updating to 3.1.33. If you’re still having this issue (and you’ve verified that the section’s Entry URI Format contains `{slug}`), please send in your `composer.json` and `composer.lock` files, and a database backup, to support@craftcms.com and we can look into it from there.
