### ISSUE TITLE
folderId on Asset element is a string

### ISSUE THREAD

**Issue by lukasgeiter** [craftcms/cms#4497]
### Description

I'm working on a site with some custom code that hooks into the `beforeSave` even of the `Asset` element. Examining the `folderId` property of the instance, I've noticed that it is a string instead of an integer. Additionally I've discovered that `Assets::parseFileLocation` returns a string for the folder ID as well.

The folder ID is documented everywhere as integer and in many places the value actually is an integer. It seems the main reason this doesn't have any big effect is PHPs type juggling with non-strict comparisons.

In my case I'm able to circumvent the problem by simply converting the value to an int. But of course it would still be nice to see this fixed properly.

### Additional info

- Craft version: 3.1.33
- PHP version: 7.2.19

**Comment by brandonkelly** [comment]
If the value was set by POST data, or from a MySQL database, then it will be a string, but the string value will still be numeric, so you can still treat it as an integer in your code. (This goes for all ID properties, not just `folderId`.)

It will definitely be fixed by the time craft requires PHP 7.4, at which point we will be able to declare class properties as integer when appropriate, and PHP will automatically typecast them when set. I’m the meantime we also may consider a code based solution. Expected behavior for now though.
