### ISSUE TITLE
FR: Config to disable auto draft saving

### ISSUE THREAD

**Issue by blackstalk** [craftcms/cms#4500]
### Description

Feature request to disable auto saving of entries to a draft in background. When making changes to an entry i now notice a draft gets produced in the background and a spinner indicates changes are being saved. Would like a config option to disable this.

I notice that in some environments the "Update Entry" button does not always disable when a draft is saving in the background and causes issues if the user clicks on "Update Entry" before the draft finishes saving.

### Steps to reproduce

1. Make changes to an entry
2. A spinner appears indicating changes are saving in the background
3. Click "Update Entry" before the spinner disappears
4. This causes issues with content not getting saved properly

### Additional info

- Craft version: 3.2.0-RC3

**Comment by jan-dh** [comment]
The auto save also triggers `Elements::EVENT_BEFORE_SAVE_ELEMENT` regularly. Have some data-conversion going on attached to that event that now gets triggered with a very high frequency. A config setting to disable this would be great.

**Comment by brandonkelly** [comment]
You can check if an element is a draft or revision from your event with this condition:

```php
if (!\craft\helpers\ElementHelper::isDraftOrRevision($element)) {
    // ... 
}
```

**Comment by minyangu-bgl** [comment]
Can't agree more. **Please simply add an option to disable the current auto-saving** so we can upgrade to 3.2 and use other features. The current auto-saving implementation creates too many unnecessary wastes. 

1. The Auto-Saving should listen on content change and **should NOT create a DRAFT if nothing is changed.**
Currently, when create/update an entry, the title input box get auto focused-in by default, as soon as we focus-out the title input box, CRAFT just creates a draft regardless if we made any change or not. The better approach would be, when focus-in, the javascript should capture the current value, and when focus-out, it compares the value inside the box with previous captured value and see if there is any change made. If yes, create a Draft, if currently not in draft mode; otherwise, DO NOT CREATE DRAFT!!!

2. When exit the entry page w/o saving, please prompt a dialogue box **with option to delete current draft.** (If a draft was created by this edit attempt)

3. We also use **Craft webhook** official plugin. Please provide a way to **filter out DRAFT saving events**. We only want to monitor if the current entry get updated and disregard any draft saving events in the webhook configuration. Likewise, when deleting a draft, we also want to filter out the deletion of drafts.

**Comment by amityweb** [comment]
Personally I don't mind draft saving, if it was fast/instant. But the issue we face is often the page could take something like 20 or more seconds to save the draft, I dont know why, but the actual Update button does not appear until thats complete, at which point its another 20 seconds or so. So for us the draft is causing frustrating delays and so we would like to disable it. 

Sometimes the draft saves quick, maybe a few seconds, and so its not so bad. If our long saving continues I may look into the reasons for that as opposed to disabling draft, but until then, disabling draft would speed up our process. Our customer also wants it disable. He, like us, have a habit of saving often so we are OK to not have it whilst it has a visible and time impact.

**Comment by minyangu-bgl** [comment]
See here, they will change the code to disable the auto draft saving. Hope they can make a release v soon.

https://github.com/craftcms/cms/commit/a658ad42b76c2a367e962b8d2fdac5f886d591f4

**Comment by brandonkelly** [comment]
Yeah we’ve removed draft auto-creation in Craft 3.2.3 (just released). See more details here: https://github.com/craftcms/cms/issues/4535#issuecomment-511613774

Drafts can still be manually created, and drafts do still get autosaved, but I assume this request is more about wishing to disable the draft auto-creation than ongoing draft autosave, so going to close it.

**Comment by minyangu-bgl** [comment]
@brandonkelly you rock!!
