### ISSUE TITLE
[3.2] Saving via Cmd+S causes Update Entry button to lock

### ISSUE THREAD

**Issue by gregorterrill** [craftcms/cms#4519]
### Description
In 3.2, when saving an entry using Cmd+S, you can sometimes get stuck in a Draft with the "Update Entry" button greyed out even though the draft has unpublished changes. You then have to switch to another revision and then back to the draft to publish it.

This does not happen if you only save using the Update Entry button - I believe this happens only if you press Cmd+S while a previous save is still in progress (so if you try to do back-to-back saves quickly).

### Steps to reproduce
- Make a field change
- Press Cmd+S / Ctrl+S to save
- Make a field change
- Press Cmd+S / Ctrl+S to save before the first save completes

### Additional info
Craft version: 3.2
PHP version: 7.1.18
Database driver & version: MySQL 5.7.21

**Comment by clarknelson** [comment]
i'm also experiencing this :)

**Comment by nathanedwards** [comment]
I'm also getting this, but just to add to the diagnosis I can also recreate the issue reliably by quickly creating a new post, writing something in a field, CMD+S to save, and then because autosave is already whirring away, I get the Chrome notification to say "Are you sure you want to navigate away from this page?

My reflex has sometimes been to click cancel and at that point, the button greys out, I'm unable to save via that method. The Autosave completes so the content is there, but the flow is ruined somewhat. I wonder if CMD+S should always just cancel the Autosave AJAX, since you're posting a save anyway?

**Comment by cityzen** [comment]
Having issues with this as well. If I create a new entry and try to do "Save and add another" I get the js "are you sure you want to leave" message and the entry doesn't get saved. Now I have to add an entry and just click Save Entry and then click save and create new. Otherwise I have to save, click entries, New entry, etc.

**Comment by brandonkelly** [comment]
This should be mostly resolved in Craft 3.2.4.

**Comment by gregorterrill** [comment]
Can confirm, I'm not having any problems with this in 3.2.4.

**Comment by brandonkelly** [comment]
Sweet!
