### ISSUE TITLE
[3.2] Select uri query not possible after upgrading

### ISSUE THREAD

**Issue by Antimated** [craftcms/cms#4544]
### Description
I have this "uris" object where I bundle all my URI's for specific sections. I limit my query to only pull the uri of a given section (to limit database queries) like so:

```twig
{% set uris = {
    about: craft.entries.section('contact').select('entries.id,uri').one().uri,
} %}
```

After upgrading to Craft CMS 3.2 I firstly get a `Undefined index: siteId` notice. So I add `siteId` to my query as such:

```twig
{% set uris = {
    about: craft.entries.section('contact').select('entries.id, uri, siteId').one().uri,
} %}
```

Which throws following error:

```
Integrity constraint violation: 1052 Column 'siteId' in field list is ambiguous
```

Does anyone have any idea on how to fix this issue?

**Comment by brandonkelly** [comment]
If you are going to customize the `select` param like that, you just need to also tell Craft to return the results as arrays using the `asArray` param, rather than instantiating actual element objects.

```twig
{% set uris = {
    about: craft.entries.section('contact').select('entries.id, uri').asArray().one().uri,
} %}
```

In case anyone else ends up here due to that `Column 'siteId' in field list is ambiguous` error, IF you had a good reason to add `siteId` to the `select` param, you just need to specify which table it should come from (`elements_sites.siteId`), similar to how you have `entires.id` rather than just `id`.

```twig
{% set uris = {
    about: craft.entries.section('contact').select('entries.id, uri, elements_sites.siteId').one().uri,
} %}
```
