### ISSUE TITLE
One of plugins got removed from composer while updating Craft

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#4624]
I'm not really sure what happened. I was updating Craft cms (using control panel) to latest pre-3.2 version. So, from `3.1.32.1` to `3.1.34`.

After the system got updated, I noticed that [asset rev](https://github.com/clubstudioltd/craft-asset-rev) plugin got missing. It was not in composer file, it was not in plugin list in `settings`. I'm fairly positive that it was installed before because without it my template breaks.

update:

I also checked composer file backups. There was no `asset-rev` plugin listed there before. But when i checked with project config backups, plugin WAS there. Maybe there was some kind of old composer file uploaded by mistake that did not have the latest plugins and this caused plugins that were not here to uninstall? But in such situation plugin SHOULD show up in composer files backups.

**Comment by brandonkelly** [comment]
You must have installed it at some point, and that Composer-uninstalled it before uninstalling it in the Control Panel, which means Craft still considers the plugin “installed” and will continue to use it, should the plugin ever be reinstalled from Composer. So that’s why you see it in the project config. But Craft will never Composer-uninstall a plugin if you didn’t tell it to.
