### ISSUE TITLE
Disable dd tag when dev mode is disabled.

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#4626]
When dev mode is disabled, `dump()` function is unavailable. 

For consistency, I propose doing the same for `{% dd %}` tag. 

Although I think that it would be better if when dev mode is disabled `{% dd %}` would just returned nothing instead throwing error - as it is now with `debug()`.

**Comment by brandonkelly** [comment]
`dump()` isn’t available because the entire Twig Debug extension isn’t registered with Twig unless running Dev Mode. `{% dd %}` on the other hand is registered as part of Craft’s core Twig extension. Had `dump()` been part of Twig’s core extension, I doubt anyone would complain about it being available when not running Craft in Dev Mode.
