### ISSUE TITLE
Enhancement: Save Entry and "Clean Up"

### ISSUE THREAD

**Issue by richhayler** [craftcms/cms#4636]
### Description
Again I'm running into issues where jumping in and out of live preview is causing unnecessary drafts to be produced.

This is then frustrating from an authoring perspective as each draft has to be opened to manually delete it. I'm wondering if in the "Save entry" dropdown there could be an option to "Save Entry and Clean Up" (better wording needed) that would save the entry and delete all drafts.

I'll be the first to admit that my proposal probably isn't a great approach either but there needs to be a better way to manage drafts when these need to removed in bulk or a change to live preview so it maybe prompts you if you want to discard the draft when navigating away from the entry edit page.

I appreciate this is a tricky one so if anyone else has some bright ideas it would be great to hear them.

Related to: #4619

**Comment by brandonkelly** [comment]
I’d be pretty worried that this option would be used irresponsibility and lead to unintended data loss.

**Comment by narration-sd** [comment]
Wonder if would work more familiarly if any re-entry to editing a draft would go to the latest draft on the entry for that author, instead of creating a new one? If they didn’t want this, select the draft they do want, or added-choice New Draft…

You may note I’m not fully au fait yet with all ways drafts presently will be created, but I would include ‘fresh’ new Entries in such a rule, so only one gets used no matter how many times an editor intends to begin one and then backs  out.
