### ISSUE TITLE
Saving entry in one site, clears matrix field content in other sites [multi-site]

### ISSUE THREAD

**Issue by studiosyntax** [craftcms/cms#4646]
### Description
We have a multi-site setup with 3 sites and 3 different languages. We started this setup before 3.1 and are currently in 3.2.5.1

After saving an entry in site 1, matrix content in the other sites gets cleared.
The matrix field has "Save blocks to other sites with the same language" as propagation method. This seems to be the automatically updated setting after updating Craft to 3.2.x

Before 3.2, when editing an entry and adding blocks to the matrix field for the first time, the blocks and their content would be "copied" from current site to the other sites. 
When you would save that entry in a later stadium, matrix content in sites 2 and 3 was not touched, nor deleted. 

_This was great for content translation purposes. You could go to site 2 and 3 and have a general layout of what content to translate._ 

Now in 3.2 when even saving an entry in site 1 — without any changes made — the "copied" matrix content in site 2 and 3 is deleted. 

This issue only seems to occur when the "copied" matrix content in other sites has not yet been changed to it's own content. When it has been changed, saving site 1 does not alter this content in sites 2 and 3.

Hope this explanation makes some sense. 

### Steps to reproduce

1. Have a 3.1.x multi-site setup
2. Have a section with a matrix field that is set to "Propagate entries across all enabled sites"
3. Edit entry for the first time, add blocks to the matrix field. Content for this matrix fields gets propagated to sites 2 and 3 also.
5. Update to 3.2
6. Saving an entry in site 1, clears the matrix content in sites 2 and 3 when it has been "copied" before but not changed 

### Additional info

- Craft version: 3.2.5.1
- PHP version: 7.1.30 && 7.2.20
- Database driver & version: MySQL 5.7.26 
- Plugins & versions:
    - Control Panel CSS 2.2.0
    - Dark Mode 1.1.0
    - Dumper 2.0.0
    - Element API 2.5.4
    - Environment Label 3.1.5
    - Feed Me 4.1.1
    - Field Manager 2.1.0
    - Freeform Pro 3.2.2
    - Imager 2.1.10
    - Incognito Field 1.1.1.1
    - Jason 1.0.2
    - Linkit 1.1.11
    - Mailgun 1.4.2
    - Position Fieldtype 1.0.14
    - Preparse Field 1.0.6
    - Queue Manager 1.1.0
    - Redactor 2.3.3.2
    - Sprout Reports 1.2.4
    - Super Table 2.2.1
    - User Manual 2.0.2
    - Video Embedder 1.1.3

**Comment by brandonkelly** [comment]
> The matrix field has "Save blocks to other sites with the same language" as propagation method. This seems to be the automatically updated setting after updating Craft to 3.2.x

Before 3.2, if your Matrix field had its “Manage blocks on a per-site basis” setting enabled, then in Craft 3.2 the Propagation Method will be set to “Only save blocks to the site they were created in” by default. Otherwise it will be set to “Save blocks to all sites the owner element is saved in”.

There is no case, however, where the Propagation Method setting should be automatically set to “Save blocks to other sites with the same language”. So someone must have manually changed that.

> Before 3.2, when editing an entry and adding blocks to the matrix field for the first time, the blocks and their content would be "copied" from current site to the other sites.

So sounds like “Manage blocks on a per-site basis” was **not** enabled. So in 3.2, Propagation Method should have been set to “Save blocks to all sites the owner element is saved in” initially.

> Now in 3.2 when even saving an entry in site 1 — without any changes made — the "copied" matrix content in site 2 and 3 is deleted.

This is expected behavior, and also how it worked in 3.1 if you had enabled the “Manage blocks on a per-site basis” setting.

If you want blocks to exist across all your sites, and just to have specific field content be translated, then set Propagation Method back to “Save blocks to all sites the owner element is saved in”.

**Comment by studiosyntax** [comment]
Thank you for responding so soon. We'll have to wrap our heads around this and investigate some more.
