### ISSUE TITLE
Make the shareUrl editable.

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#4652]
### Description

The `shareUrl` next to the 'Live Preview' button doesn't seem to editable, as far as setting the URI is concerned. Did I miss documentation on that or is it hard coded?

**Comment by brandonkelly** [comment]
If you are editing a **live** entry, then it will just be whatever the entry’s actual URL is (the same thing that `entry.url` or `entry.getUrl()` would give you in the templates). This is going to be the site URL, combined with the entry’s URI (`entry.uri`), which is auto-generated based on the section’s Entry URI Format for the site.

If the entry is **disabled**, **pending** (Post Date in the future), or **expired** (Expiry Date in the past), OR if you are editing an entry **draft** or **revision**, then the share URL will start out the same as the entry URL, with additional `token` and `x-craft-preview` query string params. The `token` param tells Craft to fetch the entry/draft/revision and use it instead of the real entry for the remainder of the request; and the `x-craft-preview` param is there to prevent CDNs from showing cached content, and also to indicate to Craft that this is a preview request (for `craft\web\Request::getIsPreview()`).

In addition to the main share URL, you can also define custom URLs that will also be available from the Share button and Live Preview, via the new Preview Targets section setting (only available for Craft Pro).

**Comment by ryanpcmcquen** [comment]
@brandonkelly, where are preview targets documented?

**Comment by brandonkelly** [comment]
@ryanpcmcquen We haven’t documented the feature yet (just came in 3.2) but the setting is relatively self-explanatory if you view it within any of your sections’ settings in Settings → Sections (provided that you are running Craft Pro).

**Comment by brandonkelly** [comment]
@ryanpcmcquen Forgot to update this issue, but Preview Targets have since been been documented here: https://docs.craftcms.com/v3/sections-and-entries.html#preview-targets
