### ISSUE TITLE
Show in UI which site a related entry belongs too

### ISSUE THREAD

**Issue by nickcobley** [craftcms/cms#4690]
### Description

When working with multisite, I'm consistently seeing issues were adding an entry relationship, in my case in a Matrix field, it's very easy to accidentally add an entry from a different site. If you do, in the list of related entries, it's not clear which site they are related too.

This could be improved if, in the field, the list of related entries also had a label showing which site the entry belongs too. As in my example, each site has a "Contact Us" page, all named the same, so there is no way visually to quickly pick up mistakes. Ideally, this label wouldn't require any interaction to view it, but worst case maybe a little info icon that if you hover it, you get some extended information about this entry. 

In addition, if you want to check they are all correct, this can't be done without checking the links on the frontend. It would be good if in addition to this, when you double click the related entry to open the edit entry modal, that it also identified here which site it belongs too. 

My very crude mockup shows roughly what I'm thinking would help.

![related-entry-multisite-example](https://user-images.githubusercontent.com/70206/62264535-dd9eca80-b452-11e9-8b20-78a87b06ea9e.png)

**Comment by nickcobley** [comment]
Oh no, looks like my use of grey in the mockup violates the guidelines established in Brads favourite github issue ever #921

**Comment by brandonkelly** [comment]
Relations don’t actually store which site the element was related in, and the site(s) elements are loaded in could differ between the Control Panel and the front-end, depending on the related elements’ site-specific statuses and the element query params used … SO, listing the site name right in the UI like that could lead to a little confusion, as it seems to imply that the relation is explicitly coded to pull the element in from that specific site.

That said, I’ve just made a couple changes for multi-site installs that should help you here:

First, all element references in the Control Panel are going to start having tooltips, with their name and the site they were queried from:

<img width="207" alt="Entries field with a visible tooltip over one of the related entries." src="https://user-images.githubusercontent.com/47792/62300951-884fc280-b42c-11e9-805f-44aad461c58c.png">

And second, when you double-click the elements to open their editor HUDs, the current site will always be shown in the header, even if the element is only editable in a single site:

<img width="617" alt="The top of an element editor HUD, displaying the entry’s current site." src="https://user-images.githubusercontent.com/47792/62301040-addccc00-b42c-11e9-9f5d-219afb7ce61b.png">

(Elements that are editable in more than one site will continue to show a site dropdown there, rather than a static heading.)
