### ISSUE TITLE
Downloading backups results in 404 on load balanced environment

### ISSUE THREAD

**Issue by jasonmccallister** [craftcms/cms#4699]
### Description
When using the Craft CMS control panel and asking to download backups, there are after times when the backup gets a 404. This makes sense as the backup file does not exist on the filesystem yet. 

### Steps to reproduce

1. Run Craft on ECS with multiple containers
2. Request a backup
3. Get a 404

### Additional info

PHP: 7.3.8
Craft: Pro 3.2.5.1
PostgreSQL

**Comment by nettum** [comment]
Also get this when running Craft on Heroku with multiple dynos (ephemeral filesystem).
Since the backup and download are done in different (ajax) requests it will sometime fails as it hits another filesystem. As a workaround I usually have devtools open to see the download request so I can just trigger it multiple times until it hits the correct dyno/filesystem.

Other than this functionality, I have not met any problem regarding horizontal scaling yet (using redis for cache/sessions), but I've sent an email to support with alot of questions to verify that e.g. project sync will not be a problem (currently using this on just a few projects).

**Comment by brandonkelly** [comment]
Just fixed this for the next release. Thanks for pointing that out!
