### ISSUE TITLE
Override Twig Template Class

### ISSUE THREAD

**Issue by markhuot** [craftcms/cms#4704]
In some instances I would love to be able to hook in to Twig's `display()` method on each template. A few examples of why:

- https://laravel-news.com/laravel-view-x-ray hooking in to the display and adding custom markup when in debug mode or something like that.
- adding specific variables to the `$context` based on the render. E.g., set up a "hook" that adds variables to all templates that start with `sidebar*` or something like that.
- call a "view model" on `display` to run PHP code prior to the template rendering.

Some thoughts, this _could_ be handled with an event. In `src/web/twig/Template.php` you could call `Event::trigger($this, 'beforeDisplayTwigTemplate', $event);` but then you're calling _a bunch_ of events and that would probably affect performance.

The other option, which I like more, in `src/web/View.php` add a way to override `_getTwigOptions` and/or customize the `base_template_class` via a configuration. This would then allow developers the ability to completely override the compiled template and save some performance because modifications would go in to the compiled template.

If you would consider exploring either of these, please let me know, and I will open a PR with a suggestion.

### Steps to reproduce

1. Install Craft
2. Attempt to override the `base_template_class` and/or hook in to the `Template::display` method in some way.

### Additional info

- Craft version: All
- PHP version: Any
- Database driver & version: Any
- Plugins & versions: None

**Comment by brandonkelly** [comment]
I like the event-based option better for two reasons:

- Changing the base class would only have an effect on newly-compiled templates. So you’d need to clear out the whole `storage/runtime/compiled_templates` folder as part of the plugin installation process or something. Likewise it would need to clear the folder out on uninstall as well, so sites don’t generate a bunch of Twig errors when that class is no longer available.

- Allowing plugins to change the base class could lead to plugin conflicts, if two separate plugins are trying to change the class to their own.

**Comment by markhuot** [comment]
Makes sense. The only issue I had with the event approach was the potential performance issues. But, boy, the extensibility of multiple plugins hooking in to a `beforeTemplateDisplay` seems _awesome_!

Want me to open PR for review? I’ve been messing around with it locally to work with some template-based view-models so I’m happy to push what I have.

**Comment by brandonkelly** [comment]
Sure. And as for performance, if you wrap `$this->trigger` with a `$this->hasEventHandlers()` condition, it shouldn’t have much of an impact unless there are actually any registered event handlers. Example:

https://github.com/craftcms/cms/blob/1239460455a61552510153fd249e48e3c325c27f/src/services/Sections.php#L422-L428

**Comment by brandonkelly** [comment]
Turns out that `base_template_class` is a deprecated setting as of Twig 2.7 (see #4755). Per https://github.com/twigphp/Twig/issues/3129 the best way to hook into before/after template rendering is with a node visitor that looks for the `ModuleNode` and swaps out its `display_start` and `display_end` nodes with new nodes that encompass the old nodes + custom nodes that compile whatever logic you need right into the template classes.

For example, here’s what we’re doing for Craft 3.3 (instead of overriding `Template::display()`):

https://github.com/craftcms/cms/blob/4540fdefc16a9a4b76ea8183ba0c94f3dfdb3c2c/src/web/twig/nodevisitors/Profiler.php#L39-L50

If you go this route with a plugin, make sure to call this from the install migration’s `safeUp()` and `safeDown()` methods:

```php
FileHelper::clearDirectory(Craft::$app->getPath()->getCompiledTemplatesPath(false));
```
