### ISSUE TITLE
"Getting unknown property: craft\\elements\\db\\AssetQuery::0"

### ISSUE THREAD

**Issue by ryanpcmcquen** [craftcms/cms#4717]
### Description

Some entry types are returning this error when using `[0]` instead of `->one()`, which feels a bit similar to: https://github.com/craftcms/cms/issues/4531

### Steps to reproduce

1. Upgrade from 3.1.x to 3.2.x.
2. Have Some kind of transformer prop like this:

```php
'figure' => $contentEntry->figure[0] !== null ? $this->getImageUrl($contentEntry->figure[0]) : null,
```

Switching everything to `->one()` resolves the issue.

### Additional info

- Craft version: 3.2.9
- PHP version: 7.x

**Comment by brandonkelly** [comment]
The change in behavior is due to a bug fix (858bf76390996e2eb150453a93752bef84c9d3ab) that we discovered over the course of investigating your issue #4505 

In Craft 3.1, if you call `$contentEntry->figure[0]` on an entry where there are no related assets, it was (bizarrely) returning the entry’s site’s handle as a fallback, and logging a deprecation warning (“The “locale” element query param has been deprecated. Use “site” or “siteId” instead.”).

An exception is the correct behavior, which is what you get in Craft 3.2.2+.

As you’ve noted, using `one()` is safer, since that doesn’t assume that there will actually be a result, and returns `null` if there isn’t one.

I’d recommend pre-fetching the asset though, so you’re not executing the same query twice.

```php
$figure = $contentEntry->figure->one();

return [
    'figure' => $figure !== null ? $this->getImageUrl($figure) : null,
    // ...
];`
```

**Comment by ryanpcmcquen** [comment]
Did you mean https://github.com/craftcms/cms/issues/4531?

**Comment by brandonkelly** [comment]
Sorry yes! Updated.
