### ISSUE TITLE
RFC: Stable release process (LTS releases)

### ISSUE THREAD

**Issue by mtnorthrop** [craftcms/cms#4721]
Would it be possible to consider a stable release schedule, similar to [the one used by the Symfony project](https://symfony.com/doc/current/contributing/community/releases.html)?

Craft and its plugins' current update process is one of the biggest pain points for me. I've used Craft on a number of commercial client projects and keeping them all updated is getting ever more difficult when new Craft/plugin updates are published multiple times a week.

I never feel confident upgrading Craft and its plugins as soon as the updates are released because it's common that an update will break something, and we often see a sequence of 2-3 updates within the space of 48 hours as bugs in the original update are fixed. (I generally leave a week or so before updating my sites just to be sure any wrinkles are smoothed out.)

In my case, the value I provide to my clients depends more on Craft being stable and reliable than it does on new features being added to the CMS, so a predictable and stable release process would be a major feature.

Symfony's backwards compatibility promise and practice of deprecating functionality a version or two before any BC-breaking changes are made make the framework a pleasure to work with, because you don't have to worry about breaking changes sneaking up on you, and plugin authors have the chance to update. (Maybe this would help avoid the recent issue with the 3.2 release, where Neo and SuperTable were late in implementing the BlockElementInterface.)

This issue isn't meant to be a complaint; Craft is still the best CMS I've used and is the only one I use for new CMS-based projects. I also acknowledge that a CMS is far more complex than a framework, so ensuring stability is more difficult, but I feel that a predictable release schedule would be a major selling point and would help developers like me convince their clients that Craft is the right choice.

**Comment by brandonkelly** [comment]
Appreciate the feedback!

I would love to get to a release process that is as straightforward as Symfony’s. At a high level we have a similar approach – patches are for bug fixes (which can include changes/corrections in behavior for existing features, and new APIs to support the changes); minor updates are for new features; and major updates are for major/breaking changes. And we are working toward having a more consistent release schedule for major & minor updates.

Due to Craft’s complexity and the wide variety of ways people use and extend it, it’s impossible for us to promise that nothing will ever break outside of a major update though. 3.2 was a good example: none of the documented APIs broke, and yet there are a few plugins that broke either because they are doing hacky things or they had preexisting bugs that were exposed by the update. (Not saying there weren’t other reasons to update plugins for better 3.2 compatibility e.g. BlockElementInterface; just that they weren’t *necessary* to avoid breakage.)

Considering that, we are starting to consider introducing LTS releases. The time to introduce that would be Craft 3.3, I think, at which point we will be pretty much wrapped up with Craft 3.x development and ramping up Craft 4. Craft 3.3 would then basically remain the LTS release up until the last 4.x update is out and we begin ramping up work on Craft 5, etc..

**Comment by mtnorthrop** [comment]
@brandonkelly 

Thank you very much for your response; a consistent LTS release schedule would be wonderful!

If or when an LTS release schedule is implemented, would it also be possible to consider a config setting that would allow developers to "pin" a project to a particular LTS release, so that update alerts are only shown for the LTS updates, and not for new major releases?

Regardless, thank you again for your comments. I'll close this issue and update the issue title so that others who are interested in LTS releases can easily find it and see that the question has been addressed.

**Comment by brandonkelly** [comment]
@mtnorthrop Yep we could do something like that.
