### ISSUE TITLE
Cannot deactivate the preview and share buttons since updating to 3.2

### ISSUE THREAD

**Issue by pablofernandezgh** [craftcms/cms#4730]
### Description
I can't deactivate the preview and share buttons since updating to 3.2
Before that, I used to put a wrong template path and those buttons would disappear 
Is there still a way to do that ?

### Additional info

- Craft version: 3.2.9
- PHP version: 7.3

**Comment by brandonkelly** [comment]
Just don’t fill in the Entry URI Format setting, since it's a bit pointless if Craft isn’t the one routing your entries to begin with.

If you are accessing the entry `uri` or `url`/`getUrl()` anywhere and you want that to be based on a pregenerated URI, then you can give your entry type a [Preparse field](https://plugins.craftcms.com/preparse-field) that does the same thing. For example if your Entry URI Format is `blog/{slug}`, then you could create a Preparse field with the template set to `blog/{{ element.slug }}`. Then replace any `uri` references with your Preparse field’s handle, and any `url` / `getUrl()` references with:

```php
\craft\helpers\UrlHelper::siteUrl($entry->yourPreparseFieldHandle)
```
