### ISSUE TITLE
Feature Request: devMode per user

### ISSUE THREAD

**Issue by tim-pixeldeluxe** [craftcms/cms#4765]
You should be able to enable devMode per user and globally using the general config. You would enable devMode from the user preferences tab, the same way you enable the Yii debug bar.

This is especially useful when trying to find the cause of an error on your production env without having to enable devMode. Because sometimes you encounter errors on your production site which you cannot reproduce locally.

**Comment by brandonkelly** [comment]
“Dev Mode” is really just the Craft name for the [YII_DEBUG](https://www.yiiframework.com/doc/guide/2.0/en/structure-entry-scripts#defining-constants) constant, which needs to be set very early on in the application bootstrap phase, well before we can find out if someone is logged in. So this isn’t possible unfortunately.

**Comment by gtettelaar** [comment]
@brandonkelly Whilst that may be true I think there is a middle ground. 

Obviously, you can use the debug toolbar on the Frontend to find errors when they pop up in production. However, the "Dev Mode` error view is far better IMO. 

@tim-pixeldeluxe 's underlying issue was specifically focusing on debugging in production. If an error happens there you get a pretty vague `Internal Server Error` which doesn't tell you much - unless you have a custom error template which should _still_ give a pretty vague message. This is perfect for the site's users. For dev's though, there is room for improvement. 

My suggestion is this:  Add an option to display the `Dev Mode` error view in production on a user by user basis (as the FR mentions).

Overriding `craft\web\ErrorHandler::renderException()` will allow us to add a condition that checks if a user has enabled that setting and render the specific error file - regardless of what Yii's error handler wants. That _should_ improve the debugging experience sufficiently. I don't think the other [Dev Mode](https://craftcms.com/guides/what-dev-mode-does) features are required on a production site. Just this one.

Already played around with this a bit so happy to submit a proposal PR for `3.3`. if you want.

**Comment by brandonkelly** [comment]
Yeah that wouldn’t hurt.

**Comment by brandonkelly** [comment]
Sorry, forgot to update this issue, but what @gtettelaar suggested/PR’d has been implemented for 3.3.
