### ISSUE TITLE
Improve Queue CLI Tasks

### ISSUE THREAD

**Issue by clarknelson** [craftcms/cms#4777]
### Description
I would very much like one or two more methods to add to the `./craft queue/*` tasks. Currently I have 360 failed tasks in the queue, how am I supposed to clear these out? The only tasks available seem to be "Exec", "retry" and "run" which all apply to one job not multiple jobs.

### Steps to reproduce

1. Type `./craft help queue`
2. Search for "clear", "run-all", or some other way to refresh the queue.

### Additional info

- Craft version: 3.2.10
- PHP version: 7.2.16
- Database driver & version: MySQL 5.7.25
- Plugins & versions: n/a

**Comment by clarknelson** [comment]
Thanks for taking a look! Ideally I would like to add a "clear" task to remove all failed tasks. 

"Retry" and "exec" seem to both run a task based on ID? How do you even get this ID? Maybe we can change "Retry" to "Retry all tasks that have failed"?

Open to thoughts on this, but I believe we should add a clear task :)

**Comment by gtettelaar** [comment]
@clarknelson You can already retry all Jobs by doing `php ./craft queue/retry all`. Have a look at the code [here](https://github.com/craftcms/cms/blob/develop/src/queue/Command.php). 

As for `clear` and `clear all`, there is a [PR open](https://github.com/craftcms/cms/pull/4419) which will be reviewed for `3.3` (don't worry about the `closed` status - that was because the base branch was deleted). 

This PR will give you the option to `clear` all jobs (or a specific one by ID).

**Comment by clarknelson** [comment]
Thank you!

**Comment by brandonkelly** [comment]
@gtettelaar’s PR #4419 has finally been merged for Craft 3.4, so going forward you will be able to use the new `queue/release all` command to release all jobs in the queue. There’s also a new Queue Manager utility (#2753) which provides a “Release all failed jobs” button.
