### ISSUE TITLE
FR: GraphQL storing schemas/tokens/permissions on project config

### ISSUE THREAD

**Issue by bzin** [craftcms/cms#4829]
### Description

Having GraphQL by default is awesome and it opens a ton of possibilities to use Craft CMS with different systems, languages etc.

One of the things that although it seems not be enabled by default is having the schemas stored in some way in the project config file. This makes the process of deployment that become super easy and smooth with the project config feature more difficult, specially if like me, you have `allowUpdates` enabled in `production` or `staging` environments. 

Before GraphQL been implemented I used and use CraftQL in production sites. I mentioned the same or somewhat related issue on the plugin github https://github.com/markhuot/craftql/issues/250

This for me seems crucial to have a smoother deployment (which was fixed with the `projectConfig` implementation). Hopefully we will continue to have that also when using Craft CMS with `headlessMode` on.

- Craft version: 3.3.0

**Comment by sebastian-lenz** [comment]
Just a basic and common scenario that should be synced: If I turn of the public GraphQL schema in my development environment (in order to turn of GraphQL altogether) we currently have to remember to repeat this on all environments as the change is not synced.

**Comment by narration-sd** [comment]
Probably best  not to get too excited here – from recent conversations with Andris, I believe History will be back in the line of progress soon. He’s just having fun with the React code, and the key Documentation ability was properly the first to get resolved.

History in fact is a pretty weak feature of iQL, and iQL is anyway limited in the things it can help with or display.

I’ve been using a tool I’m liking called Insomia, appropriately at https://insomnia.rest/, and apparently available across Mac, Linux, and Windows.

It takes a little thought to get used to and locate the features in its design, but then it’s very powerful – direct GraphQL queries handled nicely, as well as any sorts of api.

In particular you can explore tokens/schemas, _save_ any queries, labelled for later, and generally see a lot of important information about api interaction. And yes, it has very nice History as well…

You can try it and see.

From: Ruben Nascimento
Sent: Tuesday, August 27, 2019 2:42 PM
To: craftcms/cms
Cc: Subscribed
Subject: [craftcms/cms] GraphQL: feature request storingschemas/tokens/permissions on project config (#4829)

Description
Having GraphQL by default is awesome and it opens a ton of possibilities to use Craft CMS with different systems, languages etc.
One of the things that although it seems not be enabled by default is having the schemas stored in some way in the project config file. This makes the process of deployment that become super easy and smooth with the project config feature more difficult, specially if like me, you have allowUpdates enabled in production or staging environments.
Before GraphQL been implemented I used and use CraftQL in production sites. I mentioned the same or somewhat related issue on the plugin github markhuot/craftql#250
This for me seems crucial to have a smoother deployment (which was fixed with the projectConfig implementation). Hopefully we will continue to have that also when using Craft CMS with headlessMode on.
• Craft version: 3.3.0

**Comment by andris-sevcenko** [comment]
@narration-sd sounds like you were responding to #4844?

**Comment by narration-sd** [comment]
I'm not sure what I was responding to -- doesn't seem that one either, though it was something definite!  I'll figure it out and re-post, probably not tonight. 

Apologies to those on this set, and will have redacted...

**Comment by andris-sevcenko** [comment]
@narration-sd ah the perils of sleep deprivation!

**Comment by narration-sd** [comment]
Too true -- but this time not for Craftish, as I hung it up :)  Fixed now, after too-habitual edit of the post so nobody sees it correctly in email. It's a patented act...

**Comment by dangayle** [comment]
This makes more sense now that GraphQL is mainlined.

**Comment by FreekVR** [comment]
+1! would love to have the graphQL schema's be able to be versioned somehow, so it's easier to collaborate with multiple devs on the same project without telling them all how to configure their CMS.

**Comment by LarsDol** [comment]
+2!

**Comment by brandonkelly** [comment]
GraphQL schemas are now stored in the project config, for Craft 3.4!

> Maybe a good approach, but a larger change to the GraphQL and Project Config functionality, would be for each schemas permissions to be defined within the project config - but the tokens are stored/rotated in each environment.

That’s the approach we ended up taking, as we think it should be possible to create/regenerate/delete access tokens on production. So access tokens are now managed separately from the main schema definitions.

![An Edit GraphQL Token page](https://user-images.githubusercontent.com/47792/69960694-f67dc200-14be-11ea-84b9-d7f9ded819ad.png)

An added benefit of this approach is it’s now possible to create multiple tokens for the same schema.

To help test, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "3.4.x-dev",
  "...": "..."
}
```

Then run `composer update`.

> ⚠️ **Warning:** When you push this update to production, it will overwrite all GraphQL schemas with whatever is in `project.yaml`. If any of the incoming schema UIDs match the old ones, it will recreate new access tokens automatically based on the old schema settings. Otherwise you will need to recreate your tokens manually. So we recommend that you pull down a recent database backup from production before updating to Craft 3.4 locally, to ensure that you have the latest schema definitions, and that their UIDs will match what’s on production.

**Comment by CMeldgaard** [comment]
Why doesn't it store the Graphql token in project.yaml? I can see that it stores the schemas, but not the tokens. I did as described above, but when i deploy the code to production it says that no tokens exists yet.

**Comment by andris-sevcenko** [comment]
> Because if the tokens changes, how are you then gonna develop locally, making request to the Graphql, and the deploy it, since all references of the token in the code will be wrong.

I don't think that storing access tokens in your code is the best way to go, though.

**Comment by andris-sevcenko** [comment]
I mean, you wouldn't store database credentials in code, either. In a similar fashion, the access token to use should be a config setting.

**Comment by brandonkelly** [comment]
> Because if the tokens changes, how are you then gonna develop locally, making request to the Graphql, and the deploy it, since all references of the token in the code will be wrong.

Ideally you would store the token as an environment variable within your app’s environment, so it’s never hardcoded into your codebase.

**Comment by thijskaspers** [comment]
Bump on an old topic.

@brandonkelly how would we set the token in an environment variable? The CP doesn't let us.

We're having issues setting the correct GraphQL token over environments. We have a different token for every environment. When we import a production database on localhost however to do some testing, we have a GraphQL token mismatch locally, because our IDE for example uses the dev token. There isn't any way to fix the token mismatch though, because in the CP the token is generated instead of an input field we can put our correct token in.

Would be great to be able to generate the bearer token, but also allow it to be set in an environment variable? Would make working with the tokens cross-environments a lot easier :)

**Comment by brandonkelly** [comment]
You would store the Craft-generated token in an environment variable for your front-end app, not within Craft itself. Each front-end environment would get its own environment variable—let’s say it’s `CRAFT_GRAPHQL_TOKEN`—and their values would depend on what Craft’s expected bearer token is, for the Craft installation that front-end environment is talking to.

**Comment by thijskaspers** [comment]
> You would store the Craft-generated token in an environment variable for your front-end app, not within Craft itself. Each front-end environment would get its own environment variable—let’s say it’s `CRAFT_GRAPHQL_TOKEN`—and their values would depend on what Craft’s expected bearer token is, for the Craft installation that front-end environment is talking to.

Thanks for the reply, this is what we do now, but when importing an acceptance database into localhost for example, you can't get around updating the ENV var to match the acceptance token or GraphQL can't query. Then, a lazy developer can commit the wrong key into GIT, etc.. it's not a big deal of course, but would be great if we could input the ENV var into the CP, so the tokens are always aligned.
