### ISSUE TITLE
Feature Request: Markdown Directive in GraphQL

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cms#4832]
Sorry, I did this out of order—might have been quicker (and less overhead) to just suggest it, but it felt like a fun hacking project to get familiar with the internals of the new GraphQL API! ❤️ 

Basically, _it'd be great to be able to process a field in a GraphQL response as Markdown_, like we can with `{{ entry.myField | md }}` in Twig.

The PR I just issued (#4831) should address this.

**Comment by andris-sevcenko** [comment]
> This is something I hadn't considered, and I'd love to hear the team's thoughts. I suppose the best option might be to allow Directives to be registered via an Event by Plugins, so that developers will be fully aware of where they come from.

[If only... ](https://github.com/craftcms/cms/blob/develop/src/services/Gql.php#L106-L126) :)

I'm not sure if this would belong in the core, because, arguably, it assumes the end target is an HTML page/view/component. I'll leave this one open as a starting point for a conversation we should have internally, anyway.

**Comment by wsydney76** [comment]
I admit i have no idea of Graphql internals, so this may be a silly question...

Would it be somehow possible to add  methods of a custom behavior class as a field to the graphql schema?

We do this a lot in element-api, for example for unit/currency conversions, or complex matrix block queries with additional joins involved etc.

Currently i see no way of porting such stuff over to graphql...

(Could also be used for markdown, transforms etc.)

**Comment by brandonkelly** [comment]
I think we should add it. If it's not being consumed by an HTML page, they won't be adding the directive to the query in the first place. We're not assuming anything here.

**Comment by narration-sd** [comment]
It wouldn't expect to do it on a String returned from GraphQL, I think, thus be able.

The underlying thing about (not) using directives is I believe very important, and not going to be solved by the js packages. See note? 

As you probably know, Andris and I have been talking about it, so that we get back to being able to use image transforms. I could show you pictures ;) -- remind of Antonioni's 'Blowup'...

**Comment by wsydney76** [comment]
@AugustMiller Yes, i was thinking of Yii behaviors, just because it feels the most natural way for me. But anything would be welcome to overcome the limitations of this 1:1 representation of db content. You just need the api to be able to deliver the results of some business logic or complex querying.

Security: for sure you can't expose all behavior methods, instead you'll have to register them with something like `For entry type Actress add a field roles, resolved by $entry->getRoles(), returning an array of cast_role_BlockType` (By the way also some native fields may need be hidden...), 

And yes, in general this graphql headless thing has to mature a lot, more questions than answers right now. Sticking to old fashioned twig or element-api for now.

**Comment by andris-sevcenko** [comment]
@wsydney76 Can you open this as a new feature request, please?

Overall, I like the idea of being able to customize the fields available - whether it's to add new fields or to hide existing ones.

The question remains whether it should be in core or a "GraphQL power user" plugin, but for it to be a plugin, we'll need to add some events.

**Comment by andris-sevcenko** [comment]
Closing this issue as per #4831

**Comment by wsydney76** [comment]
@andris-sevcenko Thanks, FR done in #4850
