### ISSUE TITLE
FR: GraphQL query history and save favorites

### ISSUE THREAD

**Issue by bzin** [craftcms/cms#4844]
### Description

When working on some over complex GraphQL queries I really appreciate that I could have the ability to test queries out and experiment with its output. Having an historic reference of these queries and be able to store/save some as favorites would be a time saver for someone that uses CraftCMS as headless CMS. 

Another plus of this functionality could be that another 'developer' user with same rights could be able to see these and experimenting / test these and playaround also with these.

_PS: This feature comes out from CraftQL plugin and I heavily used it since it was super useful to me. Hopefully others thing the same._

**Comment by andris-sevcenko** [comment]
Right. We had to butcher the default GraphiQL toolbar when we added the token dropdown. It's just a matter of, uhh, putting it all back together in a clean manner.

**Comment by narration-sd** [comment]
@bzin, I guess it was actually here as @andris-sevcenko suggests, that I wrote an earlier reply.

You know now that he's busy at work to get the functionality back, fun with React.

Here's something you could use until its so, or later also, if it seems as good to you as it does to me.

This is a tool called Insomia, appropriately at https://insomnia.rest/, and apparently available across Mac, Linux, and Windows. 

It takes a little thought to get used to and locate the features in its design, but then it’s very powerful – direct GraphQL queries handled nicely, as well as any sorts of api. 

In particular you can explore tokens/schemas, _save_ any queries, labelled for later, and generally see a lot of important information about api interaction. And yes, it has very nice History as well… 

You can try it and see, cheers

**Comment by Jones-S** [comment]
I am not entirely sure but for a long time I was able to see the query history like here:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/7059580/76368374-5262ad00-6330-11ea-8a24-a7e17e937bdd.png">
(Craft 3.4)

I recently clicked on the closing cross on the history and was not able to make the history reappear. 

I have absolutely no idea why it was there in the first place, but never questioned its existence because I was using it with `CraftQL plugin` too.
No it disappeared, which makes me sad...

**Comment by andris-sevcenko** [comment]
Alright. Just added History and Prettify buttons for Craft 3.5.
