### ISSUE TITLE
404 Entry not found

### ISSUE THREAD

**Issue by jeffreyschmitz87** [craftcms/cms#4876]
### Description
I've updated multiple sites from Craft 3.1.34.3 or Craft 3.2.x to the latest version (3.3.0.1). Saving a new Entry which has a a new uploaded Asset results in the `HTTP 404 – Not Found – yii\web\NotFoundHttpException` error. When creating a new Entry and selecting an Asset which is already uploaded there are no problems.

I've looked inside the database to figure out what's going wrong and the Entry does get saved inside the Elements table but the `draftId` is not set to `NULL`.

If you like I can send you the project with a dump from the database.

### Additional info
- Craft version: Craft Pro 3.3.0.1
- PHP version: 7.2.16
- Database driver & version: MySQL 5.5.5

**Comment by futurefabric** [comment]
I'm seeing a similar issue which I suspect might be related. Since upgrading my site to the latest version of Craft (3.3.0.1), I'm finding I can't create any new entries at all (neither locally nor in production), without seeing the `HTTP 404 – Not Found – yii\web\NotFoundHttpException` error.

- Craft version: Craft Pro 3.3.0.1
- PHP version: 7.1.6
- Database driver & version: MySQL 5.6.35

**Comment by brandonkelly** [comment]
We have seen this on servers where query string parameters are not making their way to PHP for some reason.

If running Apache, it could be because your `RewriteRule` in `.htaccess is missing a `[QSA]` flag; if running Nginx, it could be because your `try_files` directive doesn’t pass along `$args` (see https://serverfault.com/a/382405).

**Comment by jeffreyschmitz87** [comment]
I actually _do_ see a value for the `$_SERVER['QUERY_STRING']`. It's set to `$_SERVER['QUERY_STRING'] | p=admin/utilities/php-info/&amp;foo=bar`. Should the value explicitly be `foo=bar`?

**Comment by brandonkelly** [comment]
Yeah if you are using Apache, then it’s expected that you’d also see that `p` param.

Still most likely something that is environmental; can you please get in touch at support@craftcms.com so we can look into it from there?

**Comment by futurefabric** [comment]
Thanks for the reply Brandon. Can confirm that in my case, my `.htaccess` file was indeed missing a `[QSA]` flag and that's resolved the issue. Cheers.

**Comment by jeffreyschmitz87** [comment]
Just an update on this issue if anyone else is having a 404 error. Turns out a part of the .htaccess file was causing the problem. The part in the .htaccess file redirects all URL's without a slash to URL's with a slash:
```
# Redirect URLs without slashes to those with slashes, skip URLs to files with extensions.
RewriteCond %{REQUEST_URI} !\.[a-z]+$
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)([^/])$ /$1$2/ [L,R=301]
```

Adding two conditions to the .htaccess file fixes the problem:
```
# Redirect URLs without slashes to those with slashes, skip URLs to files with extensions.
RewriteCond %{REQUEST_URI} !index.php
RewriteCond %{REQUEST_URI} !admin\/
RewriteCond %{REQUEST_URI} !\.[a-z]+$
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)([^/])$ /$1$2/ [L,R=301,QSA]
```
