### ISSUE TITLE
Quick Disable/Enable Does Not Trigger Full Cache Refresh

### ISSUE THREAD

**Issue by kgrote** [craftcms/cms#4952]
### Description
If an entry is set to enabled or disabled using the "quick edit" Set Status dropdown on the section listing page, a full template cache refresh is not triggered for all paginated listing pages. Only the paginated page where the entry exists is cleared in the cache. For example, if I have a cached and paginated listing template for a blog with 30 entries:

```
{% cache %}

{% paginate craft.entries({
    section: 'Blog',
    limit: 10
}) as pageInfo, pageEntries %}

Total Results: {{ pageInfo.total }}

<ul>
    {% for entry in pageEntries %}
        <li><a href="{{ entry.url }}">{{ entry.title }}</a></li>
    {% endfor %}
</ul>

{% endcache %}
```

This will cache three pages: `/blog`, `/blog/p2`, `/blog/p3`

If I enter into the full publish page for a blog entry, disable the entry, then click "Save", all three page caches will be cleared.

However, if I use the quick-disable dropdown on the most-recent blog entry, only the page that the entry was on (`/blog`) will be cleared. So `/blog/p2` and `/blog/p3` will still show 30 total entries, and the tenth entry in the listing will be duplicated at the end of page 1 and the beginning of page 2.

### Steps to reproduce

1. Cache a set of paginated pages
2. Use the quick-disable dropdown to disable an entry in the listing
3. Check to see that only 1 template cache was deleted instead of all of them

### Additional info

- Craft version: 3.3.1.2
- PHP version: 7.3.1
- Database driver & version: MySQL 5.7.25

**Comment by brandonkelly** [comment]
`{% cache %}` tag clearing happens in two steps:

1. Any caches that already included the element will be cleared immediately (page 1 in your example).

2. Any caches that included element queries will be checked one-by-one to see if they should be cleared, via the **Delete stale template caches** background job.

That job can take a while to run though, so it’s likely that the cache would be cleared eventually but was still ongoing when you were looking into it.

If you want caches to be cleared immediately (or if you’re having performance issues with that background job), I’d recommend switching over to the [Cache Flag](https://plugins.craftcms.com/cache-flag) plugin, which takes a bit more setup, but ultimately provides a faster & more scalable caching solution than Craft’s `{% cache %}` tag.

**Comment by kgrote** [comment]
So when I "slow" update the entry status within the publish page, I see a "Deleting Stale Template Caches" job run in the sidebar. When I use the "quick" status update, that process doesn't appear in the sidebar.

It doesn't make sense that it would take longer for the job to run when updating an entry one way vs another way. The entry has been updated so the same processes should run. I've watched the database rows clear themselves differently depending on whether I use the "slow" or "quick" update method.

**Comment by brandonkelly** [comment]
I just tested and the “Deleting stale template caches” job is getting run after changing an entry’s status from the Entries index page for me. And I verified that when enabling an entry, that the job does end up finding an appropriate cache where the entry should start appearing, and clears it. Note that it may never actually appear in the sidebar though, if the job runs really quickly.

That said, I do think there is a bug here with pagination – because the job is only checking if the saved entry is getting returned by the cached element queries; it is not checking whether the query in general returns the same results that it used to at the time the query was first cached. So if the entry is only going to show up on page 1, but not on subsequent pages, it would make sense from the current logic that only page 1’s cache would get cleared.

Obviously that’s not ideal, but I don’t think there’s a good solution right now. Comparing the entire query results would serve to make the job even less performant, and it’s already pretty terrible.

So again I think the best solution here is to switch to Cache Flag, and we should probably look into incorporating manual cache management into Craft 3.4 or 4.0 (#1689).
