### ISSUE TITLE
Issue with Matrix block handle when querying with GraphQL

### ISSUE THREAD

**Issue by jesuismaxime** [craftcms/cms#4961]
### Description
If a Matrix Block' handle contains a `_`, the system doesn’t recognize the fragment name and throw this error : "Invalid fragment name: builder_block_spacer_BlockType".

Not sure if it's a bug or maybe a lack in the documentation, but there's something here. Maybe parse the handle and allow this synthax in the query : `builder_blockSpacer_BlockType`

** Renamed my block handle `blockSpacer` in the CP and all is working fine - but take some time to figure out where the issue was.

### Steps to reproduce

1. Create a Matrix field with a block's handle containing a `_`
2. Try to query an entry containing this field.

### Additional info

- Craft version: 3.3.4.1
- PHP version: 7.2.20

**Comment by andris-sevcenko** [comment]
@jesuismaxime Yeah it's because when trying to figure out the appropriate matrix block type, Craft needs a way to figure it out based on the type name. The syntax for that is `<fieldHandle>_<blockTypeHandle>_BlockType`. If there's more than one underscore, well, there's no good of way of figuring out if that should go in the field or the block type handle.

This feels like a documentation issue to me.

**Comment by narration-sd** [comment]
Isn't this kind of thing supposed to be headed off at the pass by Craft's auto-build of handles as camel-case?  Maybe a better thing because active vs. passive would be to trap if anyone writes/re-writes their own with snakes or kebabs, and refuse to save it with a message?

**Comment by andris-sevcenko** [comment]
Handle validation currently allows underscores as well. I'll see if I can make this work in a magical, non-performance-degrading way, but leave this as a documentation issue until I do.
