### ISSUE TITLE
Running craft resave/matrix-blocks makes matrix content disappear

### ISSUE THREAD

**Issue by ryanmasuga** [craftcms/cms#5030]
### Description
We ran `./craft resave/matrix-blocks` because we made a change to a field in one of the blocks and now the matrix blocks no longer appear, either in the control panel or the front end. 

The Matrix data/rows still appear in the database, but it appears the relationships to their entries no longer exist.

### Steps to reproduce

1. Run CLI command ./craft resave/matrix-blocks
2. Matrix content is empty in the CP, and does not display on front-end.

### Additional info

- Craft version: 3.3.4.1
- PHP version: 7.2.22
- Database driver & version: MySQL 5.6.44
- Plugins & versions:
Comments	1.1.10
CP Field Inspect	1.0.6
Guide	2.1.2
Imager	v2.2.0
Inventory	2.0.3
KeyChain	1.0.0
Linkit	1.1.11
Redactor	2.4.0
SAML Service Provider	2.0.4
Super Table	2.3.0
Upvote	2.0.3

**Comment by brandonkelly** [comment]
There was a very similar-sounding bug that was introduced in 3.3.4 but fixed in 3.3.4.1 (#4951); I know you said you’re already running 3.3.4.1 but I wonder if the update didn’t install completely, or perhaps Opcache/etc is still using the old files.

Try running `composer update` manually and see if that helps.

**Comment by ryanmasuga** [comment]
Locally, we reverted to a backup DB, then upgraded the site to Craft 3.3.6. We made sure to run `composer update` as well. We then ran `php craft resave/matrix-blocks` and the blocks remained on the entries, but the content of the RTE fields (Redactor, same version) was wiped out.

**Comment by brandonkelly** [comment]
Can you send that database backup and your `composer.json` & `composer.lock` files over to support@craftcms.com?

**Comment by ryanmasuga** [comment]
We just sent those things your way. Thanks for taking a look.

**Comment by brandonkelly** [comment]
The issue here is that, when you run `./craft resave/matrix-blocks` without any arguments, the Matrix block query isn’t given enough information to know which content table to join into the query. So the blocks are loaded without any content. And then they are passed off to `Elements::resaveElements()` to be resaved as-is, without their content.

I’ve added a guard to prevent this from happening in the future – now `resaveElements()` checks to make sure the element’s `contentId` is set; otherwise it will skip the element.

To get your blocks resaved with their content in-tact, you could run this instead:

```bash
./craft resave/matrix-blocks --field=entryContent
```

**Comment by ryanmasuga** [comment]
Did I miss it in the docs, that an argument was required? Are there any docs/examples out there  other than what is found directly in the command line via `./craft help resave/matrix-blocks`?

**Comment by brandonkelly** [comment]
I just added this to the help output for that command, for the next Craft release:

> Note that you must supply the --field or --element-id argument for this to work properly.

The closest thing to explaining this in the docs is this warning on the [Matrix Block Queries](https://docs.craftcms.com/v3/dev/element-queries/matrix-block-queries.html) page:

> In order for the returned Matrix block(s) to be populated with their custom field content, you will need to either set the [fieldId](https://docs.craftcms.com/v3/dev/element-queries/matrix-block-queries.html#fieldid) or [id](https://docs.craftcms.com/v3/dev/element-queries/matrix-block-queries.html#id) parameter.

**Comment by ryanmasuga** [comment]
Cool, thanks Brandon!
