### ISSUE TITLE
[FR] Being able to create INDEX on specific fields from Craft CP

### ISSUE THREAD

**Issue by naboo** [craftcms/cms#5066]
### Description
I don't know if this is a good idea or not to bring to Craft core. I'll let the Craft brain trust decide.

When working with large amounts of entries and you query these from modules, plugins or even Twig you might do so on specific fields (for filtering, getting a set of entries with a specific field value etc.). As you entry count grow your queries start to decrese in performance. After a while you might want to set an INDEX on some specific field, or group of fields, that you query often.

If you know your way around a database you can easily do this yourself using your favourite database manager. But wouldn't it be great to be able to set INDEX for fields from within Craft? So Craft knows about the INDEX and keeps control over the database schema for future version updates and so on.

**Comment by brandonkelly** [comment]
We’ve thought about this but it’s not possible unfortunately, since the actual index you need is going to depend on what else is in the query. You can’t just put an index on individual field columns and expect to get better performance; you really need to create indexes that include multiple columns, in the exact same order they are queried in, for it to be effective.
