### ISSUE TITLE
Custom element exports

### ISSUE THREAD

**Issue by lukeholder** [craftcms/cms#5090]
Plugins and modules should have a way to define custom element export options.

Would resolve craftcms/commerce#976

**Comment by brandonkelly** [comment]
This has been added for Craft 3.4. There is now a new `ElementExporterInterface` that custom element export classes can implement, and they can be registered with a new `EVENT_REGISTER_EXPORTERS` event on element types.

```php
use craft\elements\Entry;
use craft\events\RegisterElementExportersEvent;
use yii\base\Event;

Event::on(Entry::class, Entry::EVENT_REGISTER_EXPORTERS, function(RegisterElementExportersEvent $e) {
    $e->exporters[] = MyElementExporter::class;
});
```

**Comment by bwatabu55** [comment]
Is it possible to only show your custom export type option when viewing specific entry listings or is there no way to control the display? Since the data I am customly exporting only pertains to a specific entry type, it produces an error when trying to execute it while viewing a different entry listing.

I tried to register a JS code snippet to try and hide the export option but its unable to do so since the JS executes before the entry listing is fully loaded. Any solutions? Thanks!

**Comment by brandonkelly** [comment]
@bwatabu55 The available exporters are defined per source. So yes, your event handler can conditionally register the exporter, when a particular source is selected:

```php
use craft\elements\Entry;
use craft\events\RegisterElementExportersEvent;
use yii\base\Event;

Event::on(
    Entry::class,
    Entry::EVENT_REGISTER_EXPORTERS,
    function(RegisterElementExportersEvent $event) {
        if ($event->source === 'someSourceKey') {
            $event->exporters[] = MyElementExporter::class;
        }
    }
);
```

**Comment by jonleverrier** [comment]
For CMS it was easy
```
$event->exporters = [];
$event->exporters[] = elements\exporters\MyExporter::class;
```
              
Commerce is being a little bit more stubborn!

**Comment by brandonkelly** [comment]
Yep, or just
```php
$event->exporters = [
    elements\exporters\MyExporter::class,
];
```
