### ISSUE TITLE
Question / [FR] Disable Plugins in Config

### ISSUE THREAD

**Issue by hiasl** [craftcms/cms#5107]
### Description
Not sure if this is possible, but in addition to #5106 it would really be great if it was possible to disable plugins via config. Why? Because certain plugins are meant to be used in DEV environments, but not useful or wanted on production systems. E.g. Cloner, CP-Field-Inspect, Dumper, ...

If not possible yet, maybe like this in general.php config:
`        'disablePlugins' => ['*'], // all plugins (like #5106)
`
or
`        'disablePlugins' => ['cloner', 'cp-field-inspect'], // only certain plugins addresses by handle
`

### Additional info
- Craft version: 3.3.9
- PHP version: 7.2

**Comment by gtettelaar** [comment]
@hiasl Not sure this is what you are looking for but Craft already has a [disabledPlugins](https://docs.craftcms.com/v3/config/config-settings.html#disabledplugins) setting that allows you to do this. Because it's like any other Craft config setting you can also use [multi environment config](https://docs.craftcms.com/v3/config/environments.html#config-files) to disable certain plugins on production only for example.

**Comment by hiasl** [comment]
Cool, this is what I needed. Thanks a lot!
