### ISSUE TITLE
Frontend asset uploads in wrong volume

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#5131]
### Description
The site in question has 3 asset volumes, the user only has permissions for 1 of them. But when uploading assets through a frontend entries form, those uploads end up in the first created volume, for which this user doesn't have permissions.

The asset field in question is enable for all volumes as it is shared across sites (and thus shared across volumes/usergroups)

Is this a bug or is there a way to tell the frontend form which volume (and if possible which folder) it should use?

Thanks!

### Additional info

- Craft version: 3.3.11
- PHP version: 7.3.7
- Database driver & version: 5.7
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
The files are uploaded whatever the "Default Upload Location" setting is pointing to (or, the "Upload Location" setting, in case you've enabled the "Restrict uploads to a single folder?" setting.)

**Comment by janhenckens** [comment]
What if the user in question doesn't have permission to access the "default upload location"?

**Comment by andris-sevcenko** [comment]
Hmm. If the field is rendered in the control panel, the user gets the permission to write to that volume for the session duration. I am not sure about front-end, though. Gut feeling says that it should still work. Can you check, please?

**Comment by janhenckens** [comment]
The upload itself works, then the file is in the "wrong" volume. 
We're trying to separate out uploads from the different sites in the install with different volumes, and by giving the user persmission for 1 site and 1 volume. 

With the "default upload location" set to site A's volume, a user from site C doesn't have permissions for that volume but the uploads they submit still end up in A.

**Comment by andris-sevcenko** [comment]
> With the "default upload location" set to site A's volume, a user from site C doesn't have permissions for that volume, but the uploads they submit still end up in A.

So that would be the expected behavior here. If a file is uploaded from the front-end along with the POST data, it goes in the default upload location path.

I'm not sure if using the same assets field in three different sites, but using the permissions to wall off some Volumes is a great idea. For example, in the control panel, drag and drop uploads for asset fields will always get uploaded to the default upload location, too, regardless of permissions.

You could use your own Ajax file uploader, for example, which would allow you to use the [`assets/save-asset` action](https://github.com/craftcms/cms/blob/develop/src/controllers/AssetsController.php#L63), for example.

**Comment by handplant** [comment]
I don't get it. That can't be the expected behavior. The user has no permissions to view the volume. Therefore I assume that the user does not see the volume anywhere. That's logical, isn't it?

But I'm afraid it's not. The user can view the volume and use the images without any problem.

Please solve the issue!

![Bildschirmfoto 2019-12-12 um 10 25 27](https://user-images.githubusercontent.com/2598962/70699657-c22db100-1cc9-11ea-8aef-74674c82f816.png)

![Bildschirmfoto 2019-12-12 um 10 26 48](https://user-images.githubusercontent.com/2598962/70699921-2d778300-1cca-11ea-970f-e683296c2b24.png)

**Comment by brandonkelly** [comment]
@handplant Just addressed this for Craft 3.4 with a new “Show permitted volumes” setting on Assets fields. See https://github.com/craftcms/cms/issues/887#issuecomment-565152805 for more details.
