### ISSUE TITLE
Override max-length on the Title format field

### ISSUE THREAD

**Issue by superdonpan** [craftcms/cms#5132]
We're using entry properties in the Title format field to automate titles for some channels. However we've ran into the issue of this field having a max-length set on it. I understand why this exists when you create an entry. But when you're setting up the code to auto generate titles you can easily run longer than the allowed 255 characters.

![image](https://user-images.githubusercontent.com/23033257/67189699-ff26a700-f3ee-11e9-8921-5e5855af7cec.png)

Is there a way to change the max length or some way to get around this issue?

We've looked but haven't found any plugins to deal with this issue nor any clever ways to get around the current limitation. I've seen some posts about the max length but they relate to when you add entries. This is just about when you setup automated titles.

**Comment by narration-sd** [comment]
Brandon may well have a better idea, but having done something as you 
are once before, another way occurs to me.

What if you generate these mammoth 'titles' into a secondary field, 
which not being bound up in Craft's internal usages could be set for a 
longer length?

You'd then build unique code to stuff into the actual title field, which 
surely shouldn't need to take 256 characters.

A late-night thought, anyway.

**Comment by superdonpan** [comment]
This solution would mean that we have to copy in the code into that new field every time we add a new entry. So it's not an ideal solution for us. But I still wanted to try it out and I'm sad to say that unfortunately it doesn't work.

But thanks for the suggestion narration-sd. A lot of times the late night thoughts are the best ones!

**Comment by brandonkelly** [comment]
Since Craft 3.3.1 you can actually include a front-end template from that field, which is handy for longer title formats.

So move your current template to something like `_formats/bonuses-title.twig`.

Note that the `{` shortcut won’t exist there so you will need to replace those with proper Twig syntax, and refer to the entry as `object`. So for example, instead of `{partnerSelector.one().title}` you would need to do `{{ object.partnerSelector.one().title }}`.

Once you’ve created that template, replace your current title format with `{% include '_formats/bonuses-title' %}`.

**Comment by superdonpan** [comment]
Ideally Craft would either: not have a limitation for the title field setup in the back end or have a setting allowing you to override it if you know what you are doing.

But for now, this seems like a viable work around for this issue. Thanks for the help @brandonkelly
