### ISSUE TITLE
Headless action URLs can not be routed to baseCpUrl

### ISSUE THREAD

**Issue by markhuot** [craftcms/cms#5145]
### Description

Currently action URLs are routed to the "site" side of the house. Unfortunately, I'm running Craft headless where Craft lives at [cms.site.com](cms.site.com) and the website lives as static HTML at [www.site.com](www.site.com). 

What I'd like to do is allow Craft's action URLs to function and route to [cms.site.com/index.php?p=actions/action/path](cms.site.com/index.php?p=actions/action/path). Unfortunately, this doesn't seem to be possible today as all action URLs are forced to the "site" domain.

Note: ideally I think there'd be an `actionUrl` general config override like we have for `siteUrl` and `baseCpUrl`.

### Steps to reproduce

1. Install `dukt/social`
2. Set your `siteUrl` to www.site.com and your `baseCpUrl` to cms.site.com
3. Notice that cms.site.com/admin/login creates an action URL of http://www.site.com/index.php?p=actions/social/login-accounts/login&provider=google and doesn't keep your on the `cms.` subdomain

### Additional info

- Craft version: 3.3.0.1
- PHP version: 7.2.1
- Database driver & version: MySQL 5.6.38
- Plugins & versions: dukt/social 2.0.1

### Possibly related…?
- #4349 
- #2581

**Comment by brandonkelly** [comment]
Action URLs will be CP URLs if they were generated from a Control Panel request.

https://github.com/craftcms/cms/blob/6bcc6538dcabfa2601b851a461b055efc779015c/src/helpers/UrlHelper.php#L347-L349

So this would need to be a Dukt Social feature request.

**Comment by brandonkelly** [comment]
Ah, yeah you’re right.

**Comment by brandonkelly** [comment]
Will look into this for 3.4 alongside #5122.

**Comment by markhuot** [comment]
Perfect, thanks!

**Comment by brandonkelly** [comment]
Just got around to this, and I think this is just a misconfiguration issue on your part.

Per the code snippet you pasted, the base URL should begin with the results of `static::host()`:

https://github.com/craftcms/cms/blob/21d5b5eb8648570efa507c842d780489d9b215fc/src/helpers/UrlHelper.php#L630

which returns the host info from the current base URL:

https://github.com/craftcms/cms/blob/21d5b5eb8648570efa507c842d780489d9b215fc/src/helpers/UrlHelper.php#L493-L496

which, if a CP request, will return the base CP URL:

https://github.com/craftcms/cms/blob/21d5b5eb8648570efa507c842d780489d9b215fc/src/helpers/UrlHelper.php#L423-L427

which will return everything up to the first `/` if the `baseCpUrl` config setting is set, otherwise return the base URL of the current request:

https://github.com/craftcms/cms/blob/21d5b5eb8648570efa507c842d780489d9b215fc/src/helpers/UrlHelper.php#L460-L470

I just tested this locally and action URLs are consistently using the correct host name. If I access the CP from `cms.craft3.test`, that is what’s returned; if I use a custom `baseCpUrl` config setting, that will be returned instead, regardless of what domain I’m actually accessing Craft from.

> 2\. Set your `siteUrl` to [www.site.com](http://www.site.com) and your `baseCpUrl` to cms.site.com

Did you literally set `baseCpUrl` to `cms.site.com`? You will need to include the URL scheme in there for it to work properly.

```php
'baseCpUrl' => 'https://cms.site.com',
```

Without the scheme, I’m able to reproduce the behavior you described, where the hostname in the `baseCpUrl` config setting is ignored. Even still, it should have defaulted to the current request’s hostname, unless your server is configured with `SERVER_NAME` set to `site.com` instead of `cms.site.com`.
