### ISSUE TITLE
GraphQL exclude by id

### ISSUE THREAD

**Issue by jan-thoma** [craftcms/cms#5161]
It looks like there it's not possible at this point to exclude elements by their id. This Feature would be really great especially when fetching related entries.

**Comment by narration-sd** [comment]
another good suggestion, I think. I had excellent reason to need and request this fully functional on 'another GraphQL'. That's gone away with Craft 3.3's abilities, but could well come up for other projects.

It may be that there's a kind of standard naming for this query modifier:  `idNot:`

**Comment by andris-sevcenko** [comment]
You know what. Thank you for prodding on this. I thought it wouldn't be possible in a clean manner since an array of integers cannot contain strings and vice-versa.

But, as it turns out, there is a way to do that to make `["not", 20, 120]` possible. Just have to add this to every query argument that can accept `not`.

![giphy](https://user-images.githubusercontent.com/1891118/67470468-73af4f00-f656-11e9-87fb-70e6d1e1b009.gif)

**Comment by andris-sevcenko** [comment]
<img width="717" alt="Screenshot 2019-10-24 at 12 12 56" src="https://user-images.githubusercontent.com/1891118/67471173-a1e15e80-f657-11e9-99a8-2d3253b4db0d.png">

Coming to a release to you soon.

**Comment by andris-sevcenko** [comment]
Alright, with the next release you'll be able to that.

**Comment by toddpadwick** [comment]
Hi @andris-sevcenko  is there a way of doing this with handles, or slugs as well as IDs?

 For example, I would like to display all entries apart from two specific entry types:

`entries(type:[not: "article", "podcast"]) {
    ...
}`

I tried the following two variations as well and it didn't work:

`entries(type:[not "article", "podcast"]) {
    ...
}`

`entries(type:["not", "article", "podcast"]) {
    ...
}`

**Comment by andris-sevcenko** [comment]
```graphql
entries (type: ["not", "article", "podcast"]) {
  ...
}
```
 Is the correct way and works for me locally. What Craft CMS version are you on and what's the result you're seeing?

**Comment by plcdnl** [comment]
> <img alt="Screenshot 2019-10-24 at 12 12 56" width="717" src="https://user-images.githubusercontent.com/1891118/67471173-a1e15e80-f657-11e9-99a8-2d3253b4db0d.png">
> 
> Coming to a release near you soon.
Hi @andris-sevcenko, where can i get a list of which logical operators can i put at the starts of the array ? For example "not", "or", "*"

**Comment by brianjhanson** [comment]
For most situations, `not` is about all that's useful. You can technically throw `or` as well as `and` in there, but `or` is better achieved with just an array (`id: [154, 157]`) whereas `and` will return no results because there should never be an entry with the `id` of 157 and 154. 

The argument gets passed directly to the query, so it follows the same docs [as an entry query](https://craftcms.com/docs/4.x/entries.html#id).

If you're talking about more than just an `id` query and the `QueryArgument` in general, that type can be either an integer, string, or boolean. How the query reacts to each type will vary a bit based on where it's used.

**Comment by thijskaspers** [comment]
About the 'not' option, should it work for fields too?

```
{
    guids: entries(
        section:"researches",
        hideResearchInFilter: false,
        productGUID: ["not", "null", "0"],
        groupField: ["not", "XXX"]
    ) {
        ...on researches_research_Entry {
            productGUID
        }
    }
}
```

Somehow the groupField 'not' doesn't work. It does show all entries where it is something different than `XXX`, but it also does not return entries where `groupField` is blank. Should return them right because blank != 'XXX'. Or am I sleeping and missing something here?

**Comment by brianjhanson** [comment]
@thijskaspers blank/empty fields are a little different. But you should be able to pull off what you're looking for with the `search` parameter. 

```graphql
{
    guids: entries(
        section:"researches",
        hideResearchInFilter: false,
        productGUID: ["not", "null", "0"],
        search: "-groupField:'XXX' OR -groupField:*"
    ) {
        ...on researches_research_Entry {
            productGUID
        }
    }
}
```

You'll just need to make sure `groupField` is configured [to be searchable](https://craftcms.com/docs/4.x/searching.html#configuring-custom-fields-for-search). You can read more about the search syntax [in the docs](https://craftcms.com/docs/4.x/searching.html#supported-syntaxes)
