### ISSUE TITLE
3.3.13 breaks Element API endpoint

### ISSUE THREAD

**Issue by tinchalamo** [craftcms/cms#5167]
### Description
Updated to 3.3.13 and our Element API endpoints started to return 404 errors.

### Steps to reproduce

1. Check an endpoint to verify a good response
2. Update to 3.3.13
3. Recheck endpoint to get 404 error

### Additional info

- Craft version: 3.3.13
- PHP version: 7.3.10
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
    "craftcms/redactor": "2.4.0",
    "mmikkel/incognito-field": "1.1.1.1",
    "rias/craft-position-fieldtype": "1.0.14",
    "verbb/super-table": "2.3.0",
    "marionnewlevant/match-input": "v2.0.1",
    "fruitstudios/linkit": "1.1.11",
    "nfourtythree/entriessubset": "1.2.2",
    "craftcms/aws-s3": "1.2.5",
    "doublesecretagency/craft-cpcss": "2.2.0",
    "craftcms/store-hours": "2.1.1.1",
    "elivz/craft-single-cat": "1.2.1",
    "fortrabbit/craft-copy": "1.0.0-RC7",
    "aelvan/preparse-field": "v1.1.0",
    "rias/craft-password-policy": "1.0.4",
    "craftcms/element-api": "2.6.0",
    "craftcms/feed-me": "4.1.2",
    "verbb/workflow": "1.2.3",
    "robuust/craft-reverserelations": "1.1.5",
    "mmikkel/cp-field-inspect": "1.0.7",
    "doublesecretagency/craft-inventory": "2.0.3",
    "putyourlightson/craft-sendgrid": "1.2.0",
    "doublesecretagency/craft-cpjs": "2.2.0",
    "doublesecretagency/craft-cpbodyclasses": "2.1.1",
    "aelvan/imager": "v2.3.0",
    "craftcms/webhooks": "2.2.0"

**Comment by narration-sd** [comment]
It might be something else, but if you're using the standard site.com/api connection for your Element Api, you could try simply `curl your.site.com/api`, substituting your site, and see what you get.

If the result's something  like this:
```
{"name":"Forbidden","message":"Invalid authorization token.","code":0,"status":403}
```

then you're possibly accessing Craft's new internal GraphQL instead of your expected Element API. (the actual status can vary with version, would be 40x)

If that's the case, I'd have a look at your config/routes.php file, and either change or add appropriately so that you have a different route for the internal Gql. 

Something like the following:
```
return [
    'gql' => 'graphql/api'
];
```
Again, it could well be something else, and then the Craft people  will help you, but since it's Friday,  thought to suggest...

**Comment by narration-sd** [comment]
Or, could also be your Element API plugin managed to disable or de-install on the upgrade...

**Comment by brandonkelly** [comment]
Element API is still working fine on my end with Craft 3.3.13. If you write into support@craftcms.com we can help troubleshoot from there.
