### ISSUE TITLE
Element Indexes - Prevent switching to "score" for ordering

### ISSUE THREAD

**Issue by engram-design** [craftcms/cms#5170]
It'd be nice if the dropdown for ordering elements didn't switch when you started searching for something, instead of switching automatically to "Score". I know _why_ its doing it the way it does.

https://d.pr/free/i/f3DjnP

For our use-case, its for Commerce, where we might be ordering by Date Ordered, but also want to search for a customers name - but still have orders shown in the Date Ordered order. But this is a core issue, as its doing this for all elements.

This is also probably related to more thorough filtering behaviour for element indexes.

**Comment by brandonkelly** [comment]
Not sure about this; when you have multiple results, I expect most people would prefer the most relevant results to be sorted to the top.

**Comment by engram-design** [comment]
@brandonkelly I think for a plain search, it makes sense to show relevant stuff off the top. Which is how things act at the moment, and is probably due to the lack of proper filtering, as per the scenario above.

Happy for some more thought

**Comment by brandonkelly** [comment]
Gotcha, yeah so I’ll go ahead and close this, as Craft 4 / Commerce 4 are already planned to have much better filtering on element indexes.

**Comment by gojira32** [comment]
@brandonkelly Not quite sure if this is the place since this is closed, but just wanted to build on what @engram-design was saying. Generally the filtering in Commerce needs a to be improved quite a bit.

Some examples include the "Date Ordered" column being able to be set to a date range via a date picker for instance. Or a payment method column where you can select to sort by a single payment method or multiple payment methods via a drop down.

Magento's UI, while quite ugly, is pretty functional in this regard, much more so than it is in Commerce currently:
https://d.pr/i/DLCzGu

I understand why this type of search works better for entries, categories etc. but using the Orders screen in Craft day-to-day as a customer service rep / store manager is not very intuitive.

**Comment by brandonkelly** [comment]
@gojira32 👍 Yeah it will be much better in Craft 4 / Commerce 4.
