### ISSUE TITLE
Craft queue has more then 100.000 UpdateSearchIndex records

### ISSUE THREAD

**Issue by dolphiq-vincent** [craftcms/cms#5195]
### Description
The craft queue has more then 100.000 records the the database with `craft\queue\jobs\UpdateSearchIndex` jobs. 

`O:34:"craft\queue\jobs\UpdateSearchIndex":6:{s:11:"elementType";s:20:"craft\elements\Entry";s:9:"elementId";s:3:"189";s:6:"siteId";s:1:"1";s:11:"description";N;s:30:"craft\queue\BaseJob_progress";i:0;s:35:"craft\queue\BaseJob_progressLabel";N;}`

### Steps to reproduce

1. Start queue and wait to build up the queue

### Additional info

- Craft version: 3.3.12
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7.27
- Plugins & versions: Element API 2.6.0 & Redactor 2.4.0 & Retour 3.1.26 & SEOmatic 3.2.28 & Title Entries Field 1.0.6

**Comment by brandonkelly** [comment]
Did you recently update from Craft < 3.2? If so this is probably related to that, especially if you have Super Table or Neo installed and didn’t update those at the same time, or just have a lot of entries/revisions/drafts.

Going forward you should only see one of those jobs added whenever an element is saved (including nested blocks). They execute relatively quickly though, so if you are seeing them build up, it may be because you have [runQueueAutomatically](https://docs.craftcms.com/v3/config/config-settings.html#runqueueautomatically) disabled, and haven’t set up an alternative queue worker.
