### ISSUE TITLE
New draft is created anytime entry live view is used

### ISSUE THREAD

**Issue by lexislav** [craftcms/cms#5201]
### Description

If user decides to check, how new content would look like.  Opens the entry in CP, the goes/open live view. New draft is created. User doesn't save the entry, because he has not changed anything.

Is there a way to prevent this behaviour? I would prefer new concept would be created only on demand. Thanks

### Additional info

- Craft version: 3.3.14 (Pro)
- PHP version: 7.2.24
- OS version: Linux 4.15.0-65-generic
- Database driver & version: MySQL 5.5.5

**Comment by brandonkelly** [comment]
I’ll see what I can do about this for v3.4.

**Comment by lexislav** [comment]
Thanks.

**Comment by brandonkelly** [comment]
Alright, this is resolved for the next 3.4 release. Going forward, clicking the “Preview” button will only immediately create an entry draft if the content has already changed on the page. Otherwise the Current revision of the entry will be shown instead. If the content ends up getting changed while the preview frame is open, then a draft will be auto-created at that point.
