### ISSUE TITLE
Feature request: alt tag field for assets by default

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#5203]
### Description

At the moment assets have `title` and `filename` fields by default.

Adding an `Alt text` field out the box will improve Craft's accessibility standards out the box for a lot of devs that may not remember to add this field for every project.

**Comment by carl-evans** [comment]
I was about to request this. I feel it's a wonderful enhancement which I would love to see.

**Comment by mattstein** [comment]
I add an _Alt Text_ field to Asset field layouts intended for images—which is most of them—but there are cases like PDFs and .zip archives where it's not relevant.

I think this would be a healthy default as long as it could be turned off/removed for special cases.

**Comment by JayBox325** [comment]
> I add an _Alt Text_ field to Asset field layouts intended for images—which is most of them—but there are cases like PDFs and .zip archives where it's not relevant.
> 
> I think this would be a healthy default as long as it could be turned off/removed for special cases.

Hi @mattstein, came to log this ticket again and I was correct in remembering I already logged it some time ago 😂. I usually add an 'alt text' field to my assets, but it would be great if it was added by default in the image config:

![image](https://user-images.githubusercontent.com/13233809/90647251-08131f80-e230-11ea-940b-70299923b33c.png)

Hoping this eventually makes it's way into Craft 4 or even a version of 3.5!

**Comment by mattstein** [comment]
I think it’s a great idea to promote accessibility considerations for content editors @JayBox325, I was just arguing for cases where it *wouldn’t* make sense to expose an _Alt Text_ field by default since Craft purposefully doesn’t make assumptions about the front end. `alt` and `role` might make sense for `img` tags, but the asset could be a non-image or used in a CSS background or something. Though the `title` would be moot at that point too, so maybe it’s already a self-defeating argument.

Ultimately I don’t know whether it’d be best handled by Craft core or an opinionated plugin focused on accessibility tools—but luckily for both of us it’s not up to me! :)

**Comment by brandonkelly** [comment]
I would say that alt text is part of the content of the image, not really file metadata, so it makes the most sense as a custom field that lives alongside other content. And we can’t add custom fields to assets by default in an installation because they are added via the volume’s field layout, and there aren’t any volumes in a default Craft install.
