### ISSUE TITLE
Searching excludes results based on usage of apostrophe

### ISSUE THREAD

**Issue by Harry-Harrison** [craftcms/cms#5214]
### Description
Searching's "fuzziness" is rendered pointless when an apostrophe (curly or otherwise) comes in to the mix. We have an entry titled `A Dogg’s Tale`. If you search `A Doggs Tale` (in the CMS and front-end) it will not show. If you rename it to be `A Dogg's Tale` (straight apostrophe) it will still not show in search results with the query `A Doggs Tale`.

In either case, adding either type of apostrophe in the query shows it. So if the title has a curly one, searching with a straight shows it and vice-versa.

This is the case regardless of `defaultSearchTermOptions` config options, but we typically have subLeft and subRight set true.

Looking at the searchindex table, it seems as though the apostrophe is replacing the apostrophe with a space resulting in the row storing keywords:`a dogg s tale` and  keywords_vector:`'a' 'dogg' 's' 'tale'`

### Steps to reproduce
1. Create an entry called `A Dogg’s Tale`
2. Search for that entry in the CMS as `A Doggs Tale`

### Additional info
- Craft version: Craft Pro 3.3.11
- PHP version: 7.3.2
- Database driver & version: PostgreSQL 11.5
- Plugins & versions: Numerous custom plugins and modules, but removing these does not change this.

**Comment by brandonkelly** [comment]
I’ve fixed this, but the fix will only start working once entries have been resaved, and in the meantime it could actually make things a little worse. For example your `A Dogg’s Tale` entry’s title keywords were stored as `a dogg s tale`, but now searching for `a dogg's tale` will normalize to `a doggs tale`, which won’t turn up any results.

Because of that, I decided to push the fix to the 3.4 branch, so it will come with Craft 3.4, along with a recommendation to update all entry search indexes after updating.

**Comment by Harry-Harrison** [comment]
@brandonkelly Thanks for that!
