### ISSUE TITLE
Translatable field change creates new entry revisions across all sites/languages

### ISSUE THREAD

**Issue by membla** [craftcms/cms#5231]
### Description

Editing a translatable field in a multi-site setup with propagated entries creates a revision for the entry across on all sites. Expected behaviour would be that only the entry that was actually updated would have a new revision created.

### Steps to reproduce

1. Create a number of sites
2. Let entries in a section propagate through all sites
3. Create a translatable field for the section 
3. Edit the field in an entry on one of sites
4. Revisions are created for the entry through all sites

### Additional info

- Craft version: 3.3.15
- PHP version: 7.3.11
- Database driver & version: MySQL 8.0.18
- Plugins & versions: -

**Comment by brandonkelly** [comment]
As of Craft 3.2, revisions are no longer site-specific like they used to be, which I think is better because there’s a good chance that each entry change will have an effect on all of the sites, directly or indirectly.

- Directly: because entry drafts are multi-site as well now, and so it’s possible to publish an entry draft with content changes that were explicitly made across multiple sites.
- Indirectly: because if any of the fields are not translatable, then their new values will be copied across other sites.

That said, we plan to make it easier to see what exactly changed from revision to revision as part of our plan to tackle #4642, so that should help.
