### ISSUE TITLE
Requests against craft install (frontend and backend) times out when api.craftcms.com is down

### ISSUE THREAD

**Issue by nettum** [craftcms/cms#5232]
### Description
Today we got alot of strange 504 gateway timeout from our nginx and it only happend to our craft sites. The server itself did not have any high load or other resources that take up cpu/mem/php-processes. Then I realised that craftcms.com and plugins.craftcms.com was down and it had to be related.

### Steps to reproduce

1. Take down *.craftcms.com (lol no, please don't)
2. Run craft queue the standard craft way (e.g. no `'runQueueAutomatically' => false,` in config)
3. Go to a craft site none have visited the latest days and log into admin (to prevent cache) or clear cache.
4. Click on some of the tabs in cp (e.g. articles or users) and wait for a slow request. It will timeout after a while.
5. Watch you whole site get unresponsive for some time.

The reason for this might be the following code that seems to phone home to https://api.craftcms.com/v1/...?
https://github.com/craftcms/cms/blob/d01d0afdb3c2132e6cbd0a0cde0a20988efd08c0/src/templates/_layouts/cp.html#L193
https://github.com/craftcms/cms/blob/e8f4f60706cfddb549ea89ae20ed9e74ec21c1c2/src/web/assets/cp/src/js/CP.js#L432

**Comment by CreateSean** [comment]
Yeah during the current plugin store issue it's taking 60+ seconds to load any page in my control panel for all of my sites. 

Ideally if there is a timeout of, say, 15 seconds on the plugin store then the CP should stop looking for it and work normally. 

Currently working with the CP is impossible.

**Comment by angrybrad** [comment]
@CreateSean there are legitimate use cases where everything is working normal and a Craft install would need to take 15-30 seconds for a request to complete (slow internet connection, very remote countries, etc.).  That could be alleviated by us making our Craft ID stuff more multi-regional (it's all very US based right now).

**Comment by CreateSean** [comment]
@angrybrad I hadn't considered that. Good point.

**Comment by brandonkelly** [comment]
We just released Craft 3.3.16 with a fix for this!

Now all API requests go through JS rather than PHP, with only two exceptions:

- Sending support requests from the dashboard (that generally involves sending a DB backup, templates, and logs, and sending those down to JS first would not be a good idea)
- Determining which specific Composer packages to whitelist, when updating Craft/a plugin, or installing/removing a plugin (it wasn’t worth the added complexity to move this to JS considering you wouldn’t have gotten as far as updating/installing/removing something if the API was down to begin with)

See https://github.com/craftcms/cms/issues/5194#issuecomment-548780871 for an explanation of why moving the API requests to JS will fix this issue, as this and #5194 are really the same root problem; this one is just a more dangerous symptom.

**Comment by nettum** [comment]
Awesome,  thanks!
