### ISSUE TITLE
CraftCMS is requiring a package that has been abandoned

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#5252]
### Description
I just updated craft 3.4 alpha to 75cd5d3 and I am now getting the warning:

```
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
```

This is a dependency required by `mrclay/props-dic`, which is another dependency required by `mrclay/minify`, which in turn is a dependency required by `craftcms/cms`

### Steps to reproduce

1. Install 3.4 alpha 
2. 'composer update' to get warning

### Additional info

- Craft version: 3.4.x-alpha

**Comment by brandonkelly** [comment]
`container-interop/container-interop` is only abandoned because its interfaces have been rolled into `psr/container`. (In fact in its current version, it’s basically just a shell for `psr/container`. So it’s not inherently terrible that the Minify package are requiring it. Though I’ve submitted mrclay/Props#7 to move it onto `psr/container`.

**Comment by brandonkelly** [comment]
Next 3.4 Beta release will require mrclay/minify ^3.0.7, which pulled in mrclay/Props#7.
