### ISSUE TITLE
Craft 2 control panel broken when using PHP 7.4 (Twig issue)

### ISSUE THREAD

**Issue by craftedsystems** [craftcms/cms#5322]
### Description

The control panel of Craft 2 has layout and functional issues when used with PHP 7.4.
Twig does not render white spaces anymore and as a result HTML is broken.

Example of control panel HTML source:
```html
<divid="container">
```
The space between div and id is missing.

related posting @ [stackoverflow](https://stackoverflow.com/questions/59248533/twig-problem-with-php-7-4-in-write-variable)

### Steps to reproduce

1. install PHP 7.4
2. open Craft 2 control panel

### Additional info

- Craft version: 2.7.10
- PHP version: 7.4
- Database driver & version:
- Plugins & versions:

**Comment by pazion** [comment]
Update Twig, check: https://github.com/twigphp/Twig/pull/3004/commits/1fb0f9701d8443083495cd2645e8a0c45d54c34d

**Comment by brandonkelly** [comment]
That commit came in Twig 1.42.1, however there were additional PHP 7.4 fixes in 1.42.3, which bumped the PHP requirement to 5.5, so we have been weighing whether it’s worth increasing Craft 2’s PHP requirement to 5.5, so that we can better support 7.4. Decided to go for it, so we will be releasing Craft 2.8.0 shortly with Twig 1.42.4 and requiring PHP 5.5+.

**Comment by brandonkelly** [comment]
Craft 2.8.0 is out now, with the Twig update.
