### ISSUE TITLE
GraphQL: numbers should be a Integer value and lightswitches should be a boolean value

### ISSUE THREAD

**Issue by aquafun** [craftcms/cms#5344]
### Description
I tried to query a table and found a big issue.
My table has a lightswitch field, a number field and a title field.
But if I take a look at the schema, I see that the number field is a string type and the lightswitch too.

This means my response looks like that:

`{
           "name": "Titel",
            "price": "999",
            "active": "1"
          },`

But to use that data correctly I need a response like that:

`{
           "name": "Titel",
            "price": 999,
            "active": true
          },`

and it would be great if there would be a option to print the id of each row

### Steps to reproduce

1. create a table with a number field and a lightswitch field
2. try to query your table through GraphQL

### Additional info

- Craft version: 3.3.18.1
- PHP version: 7.4

**Comment by andris-sevcenko** [comment]
Just pushed a new `Number` GraphQL type that can be an int, a float, or null for the next 3.4 beta release.

As far as lightswitch being boolean - [that's been like that since Craft 3.3.2](https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#332---2019-09-11).

Are you sure you're using a Lightswitch field there?

**Comment by andris-sevcenko** [comment]
Actually, hang on. In a table, you say.

**Comment by andris-sevcenko** [comment]
Okay, this is fixed for the next raft 3.4 beta release.
