### ISSUE TITLE
Volume Top Folder fails

### ISSUE THREAD

**Issue by TheFox** [craftcms/cms#5482]
### Description

Here: https://github.com/craftcms/cms/blob/40aa339e1dc120f7c5d0735afc9b9d95d7e8f3a4/src/helpers/Assets.php#L277 if the `$topFolder` is `false` the `getVolume()` will not work.

### Additional info

- Craft version: 3.3.20.1
- PHP version: 7.2
- Database driver & version: MySQL 5.7

**Comment by andris-sevcenko** [comment]
Can you provide the context for how you're calling this method?

The functions docbloc indicates that it expects an array of `VolumeFolder` objects.

**Comment by TheFox** [comment]
@andris-sevcenko Sorry. I do not call this by myself. It's when I'm in the CMS, in the Assets submenue, for example https://example.com/admin/assets

**Comment by andris-sevcenko** [comment]
@TheFox That's odd. Looking at the code and it seems like the only way this could happen is if there was a volume with no root folder in the `volumefolders` table. Can you check if this is the case, please?

Which, still, would not answer the question of how it could have happened. 

Is this in a fresh Craft install or did it just start occurring?
Any updates to Craft or changes to the hosting environment, recently?
Are there any volumes that were created programmatically, perhaps, or that differ from what you'd expect on a Craft site?

**Comment by TheFox** [comment]
@andris-sevcenko That's correct. The Volume has no `volumefolder` entry. No it's an existing CraftCMS installation running on a production server for one year. We created a volume using a migration so this volume is available on all environments.

**Comment by andris-sevcenko** [comment]
@TheFox how did you create the volume? Just by inserting a record in the database?

**Comment by TheFox** [comment]
Using `craft\records\Volume`, setting the attributes and then `$vol->save(false)`.

**Comment by brandonkelly** [comment]
@TheFox That explains it. You should be creating new volumes using [Volumes::saveVolume()](https://docs.craftcms.com/api/v3/craft-services-volumes.html#method-savevolume). (Example provided in the API docs.) Otherwise, you won’t get the root level folder created automatically for the volume, and the volume definition won’t make its way into your [project config](https://docs.craftcms.com/v3/project-config.html) (which is important regardless of whether you have [useProjectConfigFile](https://docs.craftcms.com/v3/config/config-settings.html#useprojectconfigfile) enabled or not.)

Assuming you haven’t gotten too far with managing assets in the volume, your best course of action here is to just delete the row you created in the `volumes` table, and try again using `saveVolume()`.

**Comment by TheFox** [comment]
@brandonkelly @andris-sevcenko Thank you!
