### ISSUE TITLE
[3.4] Editable table rows order not saved

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#5505]
### Description

In an editable table form field, reordering the rows does not work. I couldn't find any instances of `forms.editableTableField` that did _not_ have `staticRows` enabled, but this is causing issues in my plugins.

### Steps to reproduce

1. Create an editable table field.
```twig
{{ forms.editableTableField({
    id: 'values',
    name: 'values',
    cols: [{type: 'text'}],
    rows: values,
}) }}
```
2. Add 2 or more rows and save.
3. Reorder the rows and save.
4. The row order does not reflect the changes.

### Additional info

I'm testing this with the Blitz plugin.

<img width="533" alt="Screenshot 2020-01-27 at 23 09 47" src="https://user-images.githubusercontent.com/57572400/73218430-3c22d800-415a-11ea-9732-72e8bffafe36.png">

- Craft version: 3.4.0-RC3

**Comment by brandonkelly** [comment]
This is happening because the Project Config now sorts all associative arrays by their keys, recursively. (See #5147.)

If you’re storing your editable table value directly in the Project Config, you can “pack” it with the new `craft\helpers\ProjectConfig::packAssociativeArray()` method, which will protect it from losing its original order.

```php
$myArray = ['foo' => 1, 'bar' => 2];

// "Pack" the array so it doesn't get reordered to [bar=>2,foo=>1]
$packedArray = \craft\helpers\ProjectConfig::packAssociativeArray($myArray);

Craft::$app->projectConfig->set($configKey, $packedArray);
```

I’ve just updated the 3.4 branch of the docs with a tip about this (https://github.com/craftcms/docs/commit/0a81c1a1cf54e1b75eedba0901b7d906d63ddbb6), and published a new [Updating Plugins for Craft 3.4](https://craftcms.com/guides/updating-plugins-for-craft-34) guide that also talks about it.

**Comment by bencroker** [comment]
This is a plugin setting though, so I'm not sure why it is not working, will do some testing and update you with my findings.

**Comment by brandonkelly** [comment]
Are you saving the value directly on a plugin setting property?

**Comment by bencroker** [comment]
Yes. The problem appears to be that the value is a non associative array. Submitting the setting:
```
[
    'excludedUriPatterns' => [
        1 => [
            'siteId' => ''
            'uriPattern' => '2'
        ]
        0 => [
            'siteId' => ''
            'uriPattern' => '1'
        ]
    ]
]
```

Is changed to :
```
[
    'excludedUriPatterns' => [
        0 => [
            'siteId' => ''
            'uriPattern' => '1'
        ]
        1 => [
            'siteId' => ''
            'uriPattern' => '2'
        ]
    ]
]
```

**Comment by brandonkelly** [comment]
Ahhh, right, because that’s the table _data_. We were mainly concerned with table _column config_, as the order of Table field columns weren’t getting saved in the right order. But those arrays are in fact associative, whereas in this case, even if you set the array using strings as keys (e.g. `['0' => 'foo', '1' => 'bar']`, because they are numeric, PHP will convert them to actual ints. So it is not considered an associative array.

I’ve just updated our check so that it specifically looks for whether the array is out-of order, rather than just whether it contains any string keys, when determining whether it should apply our packing logic. So this is fixed now.

**Comment by bencroker** [comment]
That update looks good except for an incorrect conditional:
https://github.com/craftcms/cms/blob/0e014510f52cc4c3480930c29bd6a993547b3ee8/src/helpers/ProjectConfig.php#L230-L233

I believe the `!` should be removed:
```php
         // Don't pack this array if its keys are in numerical order 
         if (ArrayHelper::isOrdered($array)) { 
             return $array; 
         }
```

**Comment by brandonkelly** [comment]
Doh, good catch! I had undone that change as I was committing some other changes to the methods (853d29ba4682be3aef1e9b10dcac16585cb7b760), and forgot about the `!` :)
