### ISSUE TITLE
[3.4] Additional LivePreview target template are not found

### ISSUE THREAD

**Issue by scandella** [craftcms/cms#5519]
### Description
I've just upgraded to craft 3.4.0.1 and all the additional LivePreview target template are not found when selecting them in the CP livePreview of an entry: the live preview return a "template not found".
I've reset all Craft caches.
Another trouble: since the upgrade, all my previous live preview template URL are lost in the section entry.

### Steps to reproduce

1. add additional livre preview URL in a section entry
2. select this LivePreview in one of this section's entries
3. the live preview template is not found

### Additional info

- Craft version: 3.4.0.1
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Preview Targets should be configured with _URLs_, not templates. Did you enter a URL or a template path?

**Comment by scandella** [comment]
Sorry for using the wrong terms.
The fact is that I had a couple of url set in the additional LivePreview section field of some sections with their appropriate route defined and they are all gone since 3.4. When I recreate them, I’ve got a « template not found » in the CP LivePreview entry, for the very  same URL as in 3.3.x. 
Any other Url I enter in the additional LivePreview section are also not found even if the template exist.

**Comment by mmikkel** [comment]
I'm able to reproduce what I think is the same issue. After updating a site from 3.3.20.1 to 3.4.0.1, all Preview Targets added to sections with URLs are gone (the Preview Targets table in the Section's settings now only lists the "Primary entry page" target). Preview Targets in Sections without URLs are fine.

To confirm, I set up a fresh 3.3.20.1 install (no plugins, `useProjectConfigFile` is `false`), added a Section with a URL format and a single Preview Target (URL format set to `preview/cards/{uid}`), then updated the site to 3.4.0.1. After updating, the preview target is gone.

**Comment by scandella** [comment]
@mmikkel 
And when you populate your now empty Preview Targets in 3.4 with their previous URLs (like your `preview/cards/{uid}`), does the preview works? It does not for me.

**Comment by mmikkel** [comment]
@scandella Uh, no, I get the same error as you – but I think I figured out what's going on.

Apparently, Preview Targets need to be absolute now - i.e. the Preview Target `preview/card/{uid}` will throw a 404 because Craft will request the URL `example.com/admin/preview/card/{uid}` when triggered from the CP (notice the `/admin` part), unlike in 3.3 where the preview URL would be `example.com/preview/card/{uid}`.

Making the Preview Target's URLs absolute by adding a forward slash to the URL Format (i.e. `/preview/card/{uid}` works as expected.

Not sure if this is actually a bug or the way it was always supposed to work, but I find it a bit weird that the behaviour would change like this between minor versions. Also not sure if this is the reason for the preview targets being removed in upgrading to 3.4 (no time to test any further).

**Comment by brandonkelly** [comment]
Neither of those are expected, so will look into this.

**Comment by brandonkelly** [comment]
Alright! Got to the bottom of both of those issues, and just released Craft 3.4.0.2 with fixes. Unfortunately the lost preview targets aren’t recoverable, so if you need those back and can’t remember what you had, you’ll need to re-run the 3.4 update.
