### ISSUE TITLE
Previous and Next item (id) in GraphQL

### ISSUE THREAD

**Issue by ilicmarko** [craftcms/cms#5571]
## Description
Currently, there isn't a way to retrieve the previous and next posts with GraphQL. If we look at how to do this in twig it would look like this:

```twig
{# Set custom parameters for prev/next elements #}
{% set params = craft.entries.section('blog').order('title asc') %}

{# Get the prev/next elements #}
{% set prevEntry = entry.getPrev(params) %}
{% set nextEntry = entry.getNext(params) %}
```
I know this requires additional queries but still provides a solution to get the posts based on the current entry.

From the top of my head, this can be done in two ways.

### Return only the IDs
The entry query can return only the ID of `next` and `prev`. With that info, you can make two `entry` quires to return the previous and next posts. For example:

```graphql
query getEntryData($id: [QueryArgument]){
    entry(id: $id) {
    	id,
    	title,
    	previous,
    	next
    }
}
```

Where:

```
previous: ID
The id of the previous entry.

next: ID
The id of the net entry.
```
### Return entry
This is a more complex solution where `prev` and `next` are Entries.

```graphql
query getEntryData($id: [QueryArgument]) {
  entry(id: $id) {
    id,
    title,
    previous {
      id,
      title
    },
    next {
      id,
      title
    }
  }
}
```

## Problem
The problem with this is what are previous and next posts? For this reason, `getPrev` and `getNext` receive query arguments. Should we provide arguments here also?

```graphql
query getEntryData($id: [QueryArgument]) {
  entry(id: $id) {
    id,
    title,
    previous(section: "blog", orderBy: "title asc") {
      id,
      title
    },
    next(section: "blog", orderBy: "title asc") {
      id,
      title
    }
  }
}
```

**Comment by ilicmarko** [comment]
This has been asked multiple times on Discord and on StackExchange.

Ref: https://craftcms.stackexchange.com/questions/33124/how-to-get-previous-and-next-entry-using-the-native-graphql-api

**Comment by andris-sevcenko** [comment]
This _might_ be coming in 3.5.

I cannot make any promises yet, because the core requirement behind this is that there has to be eager-loading support for it, otherwise the performance of it will be sub-optimal, to say the least.

Currently, the recommended approach would be to have a separate query to build the pager component which is then displayed in the footer. Basically, just do a query to fetch an ordered list and then display two links from that list based on the page currently viewed.

As of 5dce9252a85675fb4ab1afbc7cd24cc616de3340 you can also use the approach outlined in the [SE answer here](https://craftcms.stackexchange.com/a/33512/258), but that will only work for entries in a structure and will not work on a result set based on some parameters that you wish to paginate.

**Comment by michtio** [comment]
@ilicmarko that's about CraftQL, this issue is about GraphQL in Craft CMS itself. So that answer is completely unrelated.

**Comment by andris-sevcenko** [comment]
Alright, I added this for 3.5

Keep in mind, though, that each `prev` or `next` usages with criteria will incur 2 queries per element - one to get all the ids with the criteria and another one to fetch the element next to the current element based on that list. Also, those two queries apply to each invocation, so if your query returns three elements and for both you are fetching `prev` and `next` with criteria, that's 12 extra DB queries.
