### ISSUE TITLE
[request] Add locale to formatDateTime directive

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/cms#5593]
Hello,

Could be great to add  `locale` argument to the formatDateTime directive to set the language :)

Thanks !

**Comment by andris-sevcenko** [comment]
It's tricky. Setting the locale sets it for the entire php process, not the current thread, so there's a chance, however small, that the changes might bleed over to some other page being rendered on the same server in some circumstances.

Due to this, I recommend just returning the number of the day of the week and then translating it accordingly on the frontend.

**Comment by andris-sevcenko** [comment]
This has been added for Craft 3.5
