### ISSUE TITLE
Should new entry drafts with no edits be saved?

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/cms#5597]
### Description
Creating a new entry in a section creates a draft by default as per Craft 3.2's Autosave feature.

I believe that this is intentional as it's needed for live preview to work. However, it's possible that users create a new entry, then change their mind (due to wrong section, misclick, or whatever else). This creates an unnecessary draft that is saved with a title of the incremented ID of the entry.

Ideally, Craft would know that this draft had no fields populated and delete the unnecessary draft.

### Additional info

- Craft version: 3.4.3

**Comment by brandonkelly** [comment]
That unsaved draft will in fact be deleted by garbage collection, per the [purgeUnsavedDraftsDuration](https://docs.craftcms.com/v3/config/config-settings.html#purgeunsaveddraftsduration) config setting (30 days by default).

**Comment by jsunsawyer** [comment]
Ah, must've missed that one.

What would be the proper setting to make this immediately get purged? Setting to `1` doesn't seem to do it.

**Comment by jsunsawyer** [comment]
Oops, looks like I found what I was looking for. Garbage Collection! Had no idea how this worked until now. https://docs.craftcms.com/v3/gc.html#forcing-garbage-collection

So the way this reads, with a 1 in 100,000 chance, there's a chance that garbage collection never runs, huh?

**Comment by brandonkelly** [comment]
You can adjust the probability by overriding [craft\services\Gc::$probability](https://docs.craftcms.com/api/v3/craft-services-gc.html#probability) property in `config/app.php`. Or create a cron job that runs the `./craft gc --delete-all-trashed=1` command every day or so.

I would not recommend setting `purgeUnsavedDraftsDuration` to anything lower than maybe a day or so (`86400`). Otherwise there’s a good chance that a draft could be deleted while someone is working on it.

**Comment by jsunsawyer** [comment]
Good call. Didn't think about that scenario. Seems like I need to do some research into garbage collection and get things set up better for our needs. Thanks!
