### ISSUE TITLE
[3.4] Queue manager, all tasks are "reserved" forever.

### ISSUE THREAD

**Issue by faradaytrs** [craftcms/cms#5612]
### Description

I have already got 230 jobs in queue manager and they are never completed. Restart doesn't help at all.

All jobs are two types:
Deleting stale template caches
Updating search indexes

Only first type seems to be stuck, second one is completed if i release job of the first type: 

Content is always similar to this:

```
{
    "elementId": [
        5987
    ],
    "description": null
}

```
### Steps to reproduce

1. Edit something
2. See the job stuck in queue manager

### Additional info

- Craft version: Craft Solo 3.4.4.1
- PHP version: 7.4.2
- Database driver & version: MySQL 5.5.5
- Plugins & versions: 

Craft CMS Easy MDE Markdown Editor | 0.1.3
Entry Count | 2.0.2
HTTP2 Server Push | 1.0.1
Imager | 2.3.1
Instagram Feed | 1.0.4
Phone Number | 1.3.0
Redactor | 2.5.0
SEO | 3.6.3
Wordsmith | 3.1.1

![Screenshot 2020-02-07 at 10 51 53](https://user-images.githubusercontent.com/3426470/73997110-90b72600-4998-11ea-92f4-6d22543e103b.png)

**Comment by brandonkelly** [comment]
The “Deleting stale template caches” job may be getting overwhelmed due to a large number of cached element queries.

Unfortunately there’s no good way to solve that, besides [disabling element query caching](https://docs.craftcms.com/v3/config/config-settings.html#cacheelementqueries), and clearing template caches manually (Utilities → Clear Caches) when needed.

Alternatively, you can switch from using the built-in `{% cache %}` tag to the [Cache Flag](https://plugins.craftcms.com/cache-flag) plugin. Setup is more involved with that, but it’s a much better cache-busting solution in the long run.
