### ISSUE TITLE
Upload Location setting is set to an invalid volume.

### ISSUE THREAD

**Issue by nmsdvid** [craftcms/cms#5624]
### Description
When creating a new assets field via the project.yaml file I'm getting the error message:  `The XY field’s Upload Location setting is set to an invalid volume`. Re-saving the asset field in the control panel solves the issue but I believe this is still a bug.

### Steps to reproduce

1. Install Craft
2. enable project.yaml
3. Add the following yaml code to the project.yaml file: https://gist.github.com/nmsdvid/a7a8fc1cead1c91fd3ebde936453ceeb
4. Install changes
5. Go to the image field and see error.

### Additional info

- Craft version: Craft CMS 3.4.2
- PHP version: PHP 7.3.5

**Comment by andris-sevcenko** [comment]
Where did you get that yaml code? Folders are not stored in Projet Config, so the settings were migrated to volume UIDs.

The one case where that would not happen is[ if the setting was incorrect already and the volume could not be found](https://github.com/craftcms/cms/blob/develop/src/migrations/m190108_113000_asset_field_setting_change.php#L120).

**Comment by nmsdvid** [comment]
@andris-sevcenko This happens when I create a new project and I copy the project.yaml file from another project. Imagine a scenario, when I have a local craft site running and I would like to create another craft site with the same fields by copying the project.yaml file over. This error seems to happen every time.

**Comment by andris-sevcenko** [comment]
Right. The field settings should not have any folder references, as they get converted to volumes on save. What version is the "source" project (the one from which you're taking `project.yaml` from) on?

**Comment by nmsdvid** [comment]
What version you are after ? Can you please be a little bit more specific ?

**Comment by andris-sevcenko** [comment]
Sorry, Craft version.

**Comment by nmsdvid** [comment]
Currently using:
Craft: 3.4.11
php: 7.4.3

but it was also happening on 3.4.2 & 3.1.0-beta.5.1

**Comment by andris-sevcenko** [comment]
Ah, well that is helpful! The [change to store the volume UIDs instead of the folder UIDs ](https://github.com/craftcms/cms/commit/05ab09213460c6a717734b5cb77ed8d2fee2ff25)was introduced in Craft 3.1.0-beta.6.

So, if you update the Craft version for the installation that has the source `project.yaml` you should see the `folder:<UID>` change to `volume:<UID>` in [this block](https://gist.github.com/nmsdvid/a7a8fc1cead1c91fd3ebde936453ceeb#file-project-yaml-L14-L20) at which point the config will be safe for migrating between installations.
