### ISSUE TITLE
Using Category custom field values in Section Entry URI changes entries field value

### ISSUE THREAD

**Issue by john-henry** [craftcms/cms#5637]
### Description

This is quite a big showstopper for us right now.

When using a category custom field value(s) in the entry URI it has direct influence on the values of the entries category field when section save triggers resaves entries.

Not quite sure how the uri is affecting the value of the field in the entry

### Steps to reproduce

1. Create new section
1. Create category group
2. Create category group with a parent and child category
3. Add field (primaryCategory) to entry type in new section
4. create new entry with child category selected
5. Entry is save with tree in view and parent selected.
6. change entry URI format for section to `test/{primaryCategory.level('2').one().slug}`
7. Save section
8. Go back to entry and parent has been removed from category tree

### Additional info

- Craft version: 3.4.5
- PHP version: 7.2.20
- Database driver & version: MySQL 5.7.26
- Plugins & versions:

**Comment by angrybrad** [comment]
If you change this:

    test/{primaryCategory.level('2').one().slug}

To this:

    test/{{clone(object.primaryCategory).level('2').one().slug}}

It should be the behavior you're expecting.

**Comment by AugustMiller** [comment]
For context, @john-henry, the reason this is happening is that the `Entry`'s field handle returns an `ElementQuery` object—by calling methods on the `ElementQuery`, you're effectively changing the criteria attached to the field, which then must be used during the `save` operation.

If this hunch is right (@angrybrad?), I see this as a really weird side effect.

[We recently had a conversation on Discord about this](https://discordapp.com/channels/456442477667418113/456442867163070466/671453177354125332), and it seemed as though it's "right" from a design perspective, but super confusing to anyone who doesn't have a grasp on the relationship between Twig (template files and/or strings) and the OO/PHP code under the hood.

**Comment by narration-sd** [comment]
Well done to explain it, @AugustMiller -- .had earmarked to go back and figure it out...

**Comment by angrybrad** [comment]
@AugustMiller exactly correct.

It's basically [this](https://docs.craftcms.com/v3/changes-in-craft-3.html#element-queries), which was a change in behavior from Craft 2, but has behaved like this since 3.0.

So technically, it's expected behavior, but as you can see, it's caused some confusion.

We're evaluating options, but since any chance would likely be breaking, it would have to wait until Craft 4 at the earliest.

**Comment by narration-sd** [comment]
well, being alert to explain it is not being confused... :p

I suspect the reference link that clarifies was actually [here]( https://docs.craftcms.com/v3/changes-in-craft-3.html#cloning-element-queries) , no?  

Anyway, once understood, it's kind of an entertaining side effect to something that otherwise is a convenience. Interesting thoughts withheld, on what you might be planning for Craft 4...

**Comment by angrybrad** [comment]
@narration-sd oops, you're correct... fixed link.

**Comment by narration-sd** [comment]
Good man :)
