### ISSUE TITLE
Registered js is not injected for HTML fragment templates

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#5705]
Not sure if this is a bug or expected behavior, but I'm making an issue because it is different that how Craft 2 handled it and I didn't see anything in https://docs.craftcms.com/v3/changes-in-craft-3.html#rich-text-fields

In Craft 2, registered JS (presumably css as well?) would still get dumped into templates if they were fragments (no html/body tags, meant for ajax reqs).

Seems to not be the case in Craft 3, which I think may actually the preferable behavior.

If you want it to render for a fragment template, you can do so like this:

```
{{ view.getBodyHtml()|raw }}
```

So if the behavior is as desired/expected, go ahead and close, but the docs should probably mention it.

**Comment by brandonkelly** [comment]
Both Craft 2 and Craft 3 look for certain HTML code used to anchor the CSS/JS code/include injection.

In Craft 2, CSS would be injected right before `</head>` and JS code/includes would be injected right before `</body>`, but you could override where those go using [getHeadHtml()](https://docs.craftcms.com/v2/templating/functions.html#getheadhtml) and [getFootHtml()](https://docs.craftcms.com/v2/templating/functions.html#getfoothtml).

In Craft 3, CSS is still injected before `</head>`, but you get more flexibility for JS code/includes, using the `$position` argument on [registerJs()](https://docs.craftcms.com/api/v3/craft-web-view.html#method-registerjs), [registerJsFile()](https://docs.craftcms.com/api/v3/craft-web-view.html#method-registerjsfile), and [registerScript()](https://docs.craftcms.com/api/v3/craft-web-view.html#method-registerscript) (a more flexible alternative to `registerJs()`). And like Craft 2, you can customize where they get injected using [head()](https://www.yiiframework.com/doc/api/2.0/yii-web-view#head()-detail), [beginBody()](https://www.yiiframework.com/doc/api/2.0/yii-web-view#beginBody()-detail), and [endBody()](https://docs.craftcms.com/api/v3/craft-web-view.html#public-methods). (The new method names are covered under [Template Functions](https://docs.craftcms.com/v3/changes-in-craft-3.html#template-functions) in the Changes in Craft 3 doc.)

> If you want it to render for a fragment template, you can do so like this:
> 
> ```
> {{ view.getBodyHtml()|raw }}
> ```

So you probably wouldn’t want to call that method directly, unless you are calling it from a controller in order to send the raw result in an Ajax response. Instead you would use `head()`, `beginBody()`, and `endBody()`.

Does that help?

**Comment by timkelty** [comment]
yes! thanks for the clarifcation
