### ISSUE TITLE
Add `beforeApplyChanges` Project Changes event

### ISSUE THREAD

**Issue by nateiler** [craftcms/cms#5802]
We experienced some issues applying project config changes in our master/slave database configuration (AWS RDS).  It appears there is a small lag between the read and write instance propagation which results in various errors (field column not found, etc).  

If a `beforeApplyChanges` event were available to us, we could disable the read-only database while performing the project config changes.

Ref: https://github.com/craftcms/cms/blob/92abeeb94eaca78737f9c3560b9057636ad97b5f/src/services/ProjectConfig.php#L143

**Comment by brandonkelly** [comment]
I wonder if this is something we can solve directly in core, rather than making everyone that uses read/write splitting have to implement their own workaround.

Seems like it wouldn’t be quite as simple as disabling the slave connections for the duration of the sync request though, because even once that’s done, there will still be a lag before all changes have been fully copied over, where subsequent requests could still get SQL errors. So maybe it would be best to restore the slave connections via a delayed queue job, perhaps delayed by 60 seconds by default.

Thoughts? What were you planning on doing, given this event?

**Comment by nateiler** [comment]
In our case (AWS RDS) I'm thinking we're talking in milliseconds and seems to be tied to schema changes (add/rename columns/tables).

Our approach would be to use the before and after events to toggle the 'enableSlaves' connection value.  https://www.yiiframework.com/doc/api/2.0/yii-db-connection#$enableSlaves-detail

**Comment by brandonkelly** [comment]
Alright, in that case, just went with the ultra simple option here. As of Craft 3.4.14, `applyYamlChanges()` will disable read/write splitting for the remainder of the request.

To get the fix early, change your `craftcms/cms` requirement in composer.json to:

```json
"require": {
  "craftcms/cms": "dev-develop#bf9ff1eab9dfd8d50a9b22c6be5e32513dfe5924 as 3.4.13",
  "...": "..."
}
```

Then run `composer update`.

**Comment by nateiler** [comment]
Awesome!  Love the simple solution.  We'll do some testing and report back if this doesn't seem to help.

Thanks Brandon.

**Comment by brandonkelly** [comment]
Craft 3.4.14 is out now with that change.
