### ISSUE TITLE
Craft draft/versioning has unexpected results

### ISSUE THREAD

**Issue by 919Studios** [craftcms/cms#5815]
# Craft draft/versioning has unexpected results
By default, Craft will continually create drafts/versions of page edits… I was expecting the changes made to field content to update the page *not create additional versions/drafts of it*

Here is a screenshot of the drafts/versioning I'm referring to:
![trying_to_stop_these_drafts_from_being_created](https://user-images.githubusercontent.com/20955174/77109663-afc6c000-69fa-11ea-80d0-eb23a4b8fafb.png)

## THINGS I HAVE TRIED TO SOLVE THIS:
- [x] Using **[your config](https://github.com/craftcms/cms/blob/2613dc758987a2d986ccf0a0c4f59b4c303eef1c/src/config/GeneralConfig.php#L467-L479)**.

- [x] I tried a bunch of composer snippets from the [Composer Docs](https://getcomposer.org/doc/06-config.md).

- [x] Built-in checkbox option in CraftCMS Section settings: **"Enable versioning for entries in this section?"**
![enable_versioning_for_entries_option](https://user-images.githubusercontent.com/20955174/77109709-d258d900-69fa-11ea-9059-51713f2adc26.png)

-----

**I may just be missing something really simple, Thank you for your help!**
- *Craft version: 3.3.20.1*
- *PHP version: 7.1.6*

**Comment by brandonkelly** [comment]
Drafts are unrelated to versioning.

Craft will create drafts when “Save as a draft” is selected, or if the Preview button is clicked and there are unsaved changes. Though, there was a bug where Craft could mistakingly think that content had changed even when it hadn’t for fields like Redactor, which was fixed in in this week’s 3.4.10 release.
