### ISSUE TITLE
FR: Ability to deactivate sending of verification mail on public registration

### ISSUE THREAD

**Issue by lukasNo1** [craftcms/cms#5830]
Regarding \craft\controllers\UsersController::actionSaveUser

**As it:**

A verification mail can be hold back, if a user is logged in and the sendVerificationEmail parameter is set to false in the registration request.

In case of public registration there wont be a user logged in normally, so the mail cant be hold back with this parameter.

--

Maybe you can ignore the current logged in user if sendVerificationEmail parameter is set?

I need this for a project, where guests can register in the frontend, but they should't have the ability to activate their accounts on their own. So a user in the backend can manually approve registrations.

**Comment by brandonkelly** [comment]
Preventing the activation email from being sent immediately is not a means of locking the user out of the system. They will still be able to self-activate their account if they go through a password-reset flow, for example.

If you want to lock someone out of their account, that’s what user suspension is for. So I just added a new “Suspend by default” user registration setting at Settings → Users → Settings for Craft 3.5, which you will be able to enable in order to have new user accounts be suspended automatically on self-registration. It will also prevent the activation email from being sent right away, since there would be no point in getting an activation email for an account you can’t even access yet.
