### ISSUE TITLE
PDOStatement::execute(): MySQL server has gone away

### ISSUE THREAD

**Issue by BramBeekman** [craftcms/cms#5862]
### Description

After the update to 3.4.11 i get this error

### Steps to reproduce

1. Delete Vendor en reinstall
2. Downgrade

### Additional info

- Craft version: 3.4.11 
- Commerce: 3.0.3
- PHP version: 7.1.3
- Database driver & version: MYSQL 8.0

![screenshot](https://user-images.githubusercontent.com/37911406/78003864-9c402100-7339-11ea-8fd5-b55dd03b8868.png)

**Comment by angrybrad** [comment]
Unfortunately this is one of those unhelpful MySQL error messages that means "something went wrong".

They have a whole page in their docs on it: https://dev.mysql.com/doc/refman/8.0/en/gone-away.html

But usually, when we see it, it's because the server's [max_allowed_packet](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_max_allowed_packet) and/or [wait_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout) settings are too low.
