### ISSUE TITLE
Distinguish Between Language and Locale for Date and Number Formatting

### ISSUE THREAD

**Issue by kerns** [craftcms/cms#5874]
### Description

In some future version of Craft it could also be nice if we could account for the fact that English speaking/reading people in, say, Scandinavia would like to have the cp in English, but still need to see numbers formatted according to local conventions.

As you know Denmark (like other parts of Europe) flipped the script ...so `100,000` dollars is represented as `100.000` dollars, or more precisely at today's rate `681.633,50` DKK. 🤷🏻‍♂️

I guess this is where a distinction between _language_ and _locale_ that most operating systems make becomes really important. Because a mistake with a , or a . could cost a lot of money.

I can think of many situations where a user in Europe today would want the cp to be in English, but where (as a consequence of this choice) having decimal separation completely turned on it's head would be jarring.

Hope this makes sense. Possibly but not necessarily related to #5873.

**Comment by brandonkelly** [comment]
This doesn’t really make sense because locales are a combination of country _and_ language. If a language tends to be spoken in a country, then there tends to be an established locale for the combo.

And in fact an `en-DK` locale does exist. Craft just doesn’t show it by default because the default Language dropdown only includes the languages Craft has been explicitly translated for. You can still add it in yourself though, via the [extraAppLocales](https://docs.craftcms.com/v3/config/config-settings.html#extraapplocales) config setting:

```php
'extraAppLocales' => ['en-DK'],
```

If you have the I18n extension enabled, that should work right off the bat. Otherwise you will need to download [en-DK.php](https://github.com/craftcms/locales/blob/master/locales/en-DK.php) to `config/locales/en-DK.php`.

With that config setting in place, all users will have the option to select “English (Denmark)” in their Language preference.

**Comment by kerns** [comment]
This works exactly as one would want / expect. Thanks!
