### ISSUE TITLE
Date picker + American English = Weird date handeling

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#5899]
### Description
In our case, some editors have American English as their preferred language. But they work in the European timezone, and use European date formats.

When you open the date picker, it shows it's on April for instance. You select to schedule an article on the 7th op April. After clicking the date,  it will schedule for 07/04 (US format).

This is solved by changing the language to British English. But the fact of the matter is, when you use a date picker to choose a date, it should select that specific date, no matter the language preference.

**Comment by brandonkelly** [comment]
The datepicker is in fact configured with the current locale’s date format. And 07/04 is actually the 7th of April, in the `en-GB` locale format, so I suspect at the time the entry page was loaded, your language preference was actually set to “English (United Kingdom)”.

(I can tell that `07/04` is not the 4th of June because the `en-US` format doesn’t use 2-digit days/months except for numbers 10 or higher. With `en-US` that would have been `7/4`.)

If the data ended up getting saved as the 4th of June, then I suspect what happened was something like this:

1. User loaded the Edit Entry page while their Language preference was set to “English (United Kingdom)”
2. In a separate browser tab, user changed their Language preference to “English” or “English (United States)”
3. User saved the entry from the first browser tab

In that scenario, the date would have been submitted in the `DD/MM` format, but by the time it was processed by the back-end, it was expecting a `MM/DD` format due to the newly selected Language preference.

**Comment by lenvanessen** [comment]
@brandonkelly I'm sure that this is not the case here. The users haven't changed this setting and it's actually happening to +- 15 content editors in our cms. Maybe my analyses around the cause is off, but the bug sure is present.

**Comment by brandonkelly** [comment]
I’m not able to reproduce on my end… are you? And are you running the latest version of Craft?
