### ISSUE TITLE
Cmd + S shortcut should handle another entry being created from an entry better

### ISSUE THREAD

**Issue by architchandra** [craftcms/cms#5916]
### Description
Cmd + S is extremely helpful when working on Craft, but if there is an `Entries` field being used and a new entry is created from within an entry (original entry), Cmd + S does not wait for the new entry to be created or ensure that it is saved.

It only saves the original entry while leaving the new entry unsaved and thus lost. It leads to needless headaches and repetition of work.

![Screenshot_2020-04-14_at_6_46_09_PM-2](https://user-images.githubusercontent.com/8830075/79230091-b6bde280-7e81-11ea-878e-5093aa7eba22.png)

### Steps to reproduce

1. Set up a Craft site with multiple entries and an `Entries` field assigned to the entry type
2. Edit an entry and click on 'Add an entry'
3. Instead of selecting an existing entry, create a new entry (as highlighted in the screenshot)
4. Enter some data for the new entry but do not save it
5. Click on Cmd + S

### Additional info

- Craft version: 3.4.13
- PHP version: 7.2.23
- Database driver & version: mysql  Ver 14.14 Distrib 5.7.28, for macos10.14 (x86_64) using  EditLine wrapper

**Comment by brandonkelly** [comment]
Just fixed this for the next release (3.4.16). Going forward, when the <kbd>Ctrl</kbd>/<kbd>Command</kbd> + <kbd>S</kbd> save shortcut is used and an element editor HUD is open, it will save the element editor HUD instead of the main entry. (And the shortcut will be completely ignored if any other HUDs/modals/menus are currently open).

**Comment by brandonkelly** [comment]
Craft 3.4.16 is out now with this change.
