### ISSUE TITLE
"# months ago" in German is apparently wrong

### ISSUE THREAD

**Issue by proimage** [craftcms/cms#5931]
In German:

- "1 month" = "1 monat"
- "6 months" = "6 monate"
- "6 months ago" = "Vor 6 monaten" (note the added "n")

In Craft, when I do `Vor {{ entry.dateField.diff(now)|duration(false)|split(', ')[0] }}` on a German-language site, I get "Vor 6 monate".

What's the best way to get that "monate" to be "monaten" under those circumstances? Keep in mind that of course, it also has to handle "Vor 1 monat" scenario. Is a straightforward string replace (monate ➡️ monaten) really the best solution?

Craft 3.4.5

**Comment by brandonkelly** [comment]
I think our translation is fine since **your template** is the thing adding that `Vor`.

https://github.com/craftcms/cms/blob/2fc56f0bcd70a1ae67e9338512e053b896f4a47e/src/translations/de/app.php#L1194

So either write your own custom duration logic instead of using Craft’s [duration](https://docs.craftcms.com/v3/dev/filters.html#duration) filter, or [replace](https://docs.craftcms.com/v3/dev/filters.html#replace) `Monate` with /`Monaten`:

```twig
Vor {{ entry.dateField.diff(now)|duration(false)|split(', ')[0]|replace('Monate', 'Monaten') }}
```

**Comment by proimage** [comment]
Ok thanks Brandon... I'll just do the text replace then. I guess I was wondering if there was a more official way to output the entire "# [duration] ago" string aside from hardcoding "ago" into the template—a way that would adjust the datetime string to account for the linguistic difference. ¯\_(ツ)_/¯

**Comment by brandonkelly** [comment]
Not currently, feel free to post a new GH issue requesting it.

Another route you might consider taking is the [timestamp](https://docs.craftcms.com/v3/dev/filters.html#timestamp) filter, which will output “Today” / “Yesterday”, “<Week day name>” if within the past 7 days, otherwise it will just output the full date as if you used the [date](https://docs.craftcms.com/v3/dev/filters.html#date) filter.

```twig
{{ entry.dateField|timestamp('long') }}
```
