### ISSUE TITLE
Automatically append namespace to "getQueryParam" if used inside "namespace" tag

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#5936]
Today I tested `{% namespace %}` tag. I create simple form with input which would be filled with content of URL param corresponding to inputs `name`:

```twig
{% namespace 'xxx' %}
<form action="">
<label for="someId"></label>
<input type="text" id="someId" name="someName" value="{{craft.app.request.getQueryParam('someName')}}">
</form>
{% endnamespace  %}
```
Unfortunetly it did not worked. I needed to append namespace manually to `getQueryParam`:

```twig
{% set someNamespace = 'xxx' %}
{% namespace someNamespace %}
<form action="">
<label for="someId"></label>
<input type="text" id="someId" name="someName" value="{{craft.app.request.getQueryParam(someNamespace~'.someName')}}">
</form>
{% endnamespace  %}
```
I have proposal that would allow avoiding that - adding third param to `getQueryParam` that would automatically append namespace to `getQueryParam` function if it was used within `namespace` tag.

**Comment by brandonkelly** [comment]
This is what the [namespaceInputName](https://docs.craftcms.com/v3/dev/filters.html#namespaceinputname) filter is for:

```twig
{{ craft.app.request.getQueryParam('someName'|namespaceInputName) }}
```

(As long as you put that code within your `{% namespace %}` tag pair, it will default to using the active namespace defined by that tag.)

**Comment by piotrpog** [comment]
@brandonkelly 
`nameSpaceInputName` returns format `namespace[name]`. `getQueryParam` requires format `namespace.name`.

That's why `namespaceInputName` cannot be used in this situation.

**Comment by brandonkelly** [comment]
You’re right, sorry. Will reopen for now, but I think the solution here is maybe to make `getQueryParam()` support the square bracket syntax.

**Comment by piotrpog** [comment]
@brandonkelly 
Wouldn't it be project breaking change?
Maybe it would be simpler to add a new filter like `namespaceInputName ` that uses dot notation.

**Comment by brandonkelly** [comment]
Actually this isn’t going to be possible at all, because Craft can’t always reliably know what a parameter name is going to end up as, solely based on its form input name.

For example, let’s say the input name is `fields[myEntriesField][]`. The actual value could end at `$_GET['fields']['myEntriesField'][0]`, or `$_GET['fields']['myEntriesField'][1]`, or any other index. (And that’s assuming that some other input further down in the form doesn’t completely override `fields` or `fields[myEntriesField]`, which we can’t be sure of either.)

That makes me think this isn’t a good idea to address directly in Craft, but you could hack around it using a combination of [namespaceInputName](https://docs.craftcms.com/v3/dev/filters.html#namespaceinputname), [replace](https://docs.craftcms.com/v3/dev/filters.html#replace), and [trim](https://twig.symfony.com/doc/2.x/filters/trim.html):

```twig
{% macro namespaceParam(param) %}
    {{- param|namespaceInputName|replace('/[\\[\\]]+/', '.')|trim('.') -}}
{% endmacro %}

{{ craft.app.request.getQueryParam(_self.namespaceParam('someParam')) }}
```
