### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ashikp** [craftcms/cms#5971]
### Description
I have Transfer My website one to another hosting. After transfer all was ok. After one day.
I got a problem. I am getting .

Internal Server Error
Unknown "injectInstaller" filter.

I don't know what is the problem is.
Any one help please

### Additional info

- Craft version: Craft CMS 2.7.10
- PHP version: 7.0.33
- Database driver & version: lastest Updated

**Comment by narration-sd** [comment]
My guess is that you should have a straight talk with your hosting provider, @ashikp .

'injectInstaller' appears to be advertisment inserter that they are probably trying to force into your site, so that it will display ads to make them money from your visitors.

Or, someone has put such an intruder into their system, perhaps?

Here's an apparent link speaking to injectInstaller:  https://mymediads.com/profiles/34615 

I would tread carefully, if I were you.  Ad networks can be a great source of malware, also, probably you know.  Best fortune.

>

**Comment by brandonkelly** [comment]
That error looks like it’s coming from Twig, as the error format matches this code:

https://github.com/twigphp/Twig/blob/18772e0190734944277ee97a02a9a6c6555fcd94/src/ExpressionParser.php#L772

So, search your template files for `injectInstaller` and see if it shows up anywhere. That’s not a filter that Twig or Craft give you in core, and I don’t know of any plugins in Craft’s Plugin Store that add it, so most likely it was provided by a custom module that didn’t make it to the new server.
