### ISSUE TITLE
Ability to specify filename for project.yaml

### ISSUE THREAD

**Issue by mildlygeeky** [craftcms/cms#5982]
Per discussion in Discord, I have a complex build that would really benefit from being able to rename the project.yaml file (it involves needing the use multiple currencies for Commerce, and running multiple databases because of it).

Would appreciate if it were possible in a future version of Craft to be able to override the filename for project config, either in general.php, app.php, wherever.  I’d also be happy to write a PR for it, if you tell me where you’d want to make it possible (app.php or general.php).

**Comment by brandonkelly** [comment]
This will be possible in Craft 3.5 via `config/app.php`:

```php
return [
    'components' => [
        'projectConfig' => function() {
            $config = craft\helpers\App::projectConfigConfig();
            $config['filename'] = 'project-foo.yaml';
            return Craft::createObject($config);
        },
    ],
];
```

**Comment by brandonkelly** [comment]
As of Craft 3.5 Beta 4, the project config is going to start getting stored across multiple files so it gets its own _directory_ rather than a single yaml file. So I’ve replaced that `$filename` property with a new `$folderName` property instead. Note that you will get a PHP error if you still are trying to configure `craft\services\ProjectConfig` with a `$filename` property.

Example above has been updated to reflect the change.
