### ISSUE TITLE
Unable to load dynamic library :: mysql.so

### ISSUE THREAD

**Issue by stephanedemotte** [craftcms/cms#5986]
### Description
Hello I try to make craft work on a (Funio) server.
After change permission, and activate some extension. Craft cms finally work but i can't get access to the store (and cannot buy a licence)

In the network status, i got this message from axios

```
message: "PHP Startup: Unable to load dynamic library '/opt/alt/php71/usr/lib64/php/modules/mysql.so' - /opt/alt/php71/usr/lib64/php/modules/mysql.so: cannot open shared object file: No such file or directory"
```

But it's weird, sometime i got a crash on the admin page, with the same message, but when i reload the page, everything work, the crash is "random"

But for the store page, it's always here. I never get access to the store.

I've check on the server and mysql.so it's not here, but craft have to use mysqli.so instead ?

<img width="794" alt="Screen Shot 2020-04-28 at 12 31 59 PM" src="https://user-images.githubusercontent.com/2158130/80513157-a101f000-894c-11ea-93c1-dd0b763bff92.png">

My php extension
<img width="1336" alt="Screen Shot 2020-04-28 at 12 35 31 PM" src="https://user-images.githubusercontent.com/2158130/80513334-e8887c00-894c-11ea-9650-8c1c8792039b.png">

Thanks !!

### Additional info

- Craft version: 3.4.17.1
- PHP version: 7.1.33
- Database driver & version: MySQL 10.1.44
- Plugins & versions:

**Comment by angrybrad** [comment]
The only thing Craft is explicitly checking for as far as MySQL extensions is `pdo_mysql` to see if it's loaded: https://github.com/craftcms/server-check/blob/master/server/requirements/requirements.php#L23

Maybe try disabling the `mysqlnd`, `mysqli` and `mysql` extensions since they are legacy and see if that helps with the random error message.

Outside of that, have you tried contacting Funio?

**Comment by stephanedemotte** [comment]
Working when i disable  `mysqlnd` `mysqli` `mysql` thanks man !
