### ISSUE TITLE
URL generating bug from Cyrillic to Latin

### ISSUE THREAD

**Issue by markxxv** [craftcms/cms#5989]
### Description

I found a bug while URL generating (from Cyrillic to Latin). The URL generator leaves without transliteration the Cyrillic symbol "ь", when I create the title.

I have stetted config/general like limitAutoSlugsToAscii' => true.

Thus, the symbol “ь” is a modifier in the Cyrillic alphabet and is not the letter “B” or “b” analogue. The Cyrillic character “ь” should be skipped during transliteration, otherwise the URL will be incorrectly encoded

### Steps to reproduce

1. Create entry with this symbol, for example: "как начать бизнес"
2. The Cyrillic character "ь" encodes as «% D1% 8C».
3. The url will be encoded like:  "kak-nachat% D1% 8C-biznes" instead "kak-nachat-biznes"

This is a critical bug which affects the SEO positioning and sharing through social networks

### Additional info

- Craft version: 3.4.17.1
- PHP version: 7.3
- Database driver & version: MySQL 5.7

**Comment by brandonkelly** [comment]
I’ve just fixed this for Craft 3.5 by updated Stringy to ^6.2.2, which contains improved ASCII character mappings including `'ь' → ''` for Russian.

(Craft was previously using Stringy 5.1, and Stringy 5.2 contained breaking changes that affected Craft, which is why I can’t update Stringy until Craft 3.5.)
