### ISSUE TITLE
Inconsistent data with matrix field values in the before save event.

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#6008]
Getting some inconsistent data returned when working with matrix blocks in the before save event for an entry.

`editions` is our matrix field, within the before save event, we are getting the blocks, modding the data and then setting the value again. This is all working fine but as soon as we add params to the matrix block query the data returned is inconsistent.

Before save we updated the value of `archiveId` (a field within the matrix block) in the cp.

This example appears to correctly return the new value for `archiveId`:

```
$editions = (clone $entry->editions)
    ->all();

foreach ($editions as $edition)
{
    var_dump($edition->archiveId);
}
```

Although as soon as we add the `orderBy` param to the query, `archiveId` returns data that is currently saved or `null` for a new block:

```
$editions = (clone $entry->editions)
    ->orderBy('date DESC')
    ->all();

foreach ($editions as $edition)
{
    var_dump($edition->archiveId);
}
```

Is this a bug, or something we are doing wrong?

- Craft version: 3.4.17.1
- PHP version: 7.3

**Comment by brandonkelly** [comment]
Matrix field values are always normalized as block queries. So the way that Matrix transports its posted block data around before it’s saved is by caching it on the block query, via [setCachedResult()](https://docs.craftcms.com/api/v3/craft-elements-db-elementquery.html#method-setcachedresult). That function will take an array of elements (the posted Matrix blocks) and cache them internally, along with the current query params.

As soon as the query params change, the cached result is discarded. Which is why changing the `orderBy` is discarding your changes.

So you will just need to do your own manual ordering of the blocks.
