### ISSUE TITLE
Exclude certain entry to referenced entries fields.

### ISSUE THREAD

**Issue by dharnell-abluyen** [craftcms/cms#6016]
### Description
Hello, I'm new to craft 3 and I've been struggling on how to exclude certain entry to a created entries field.

### Steps to reproduce

1. Create Entries Field 
<img width="1377" alt="Screen Shot 2020-05-03 at 6 45 29 PM" src="https://user-images.githubusercontent.com/48315691/80912277-7067ef00-8d6e-11ea-818e-232e0a6868ad.png">

2. Added created field to certain entry types.
3. Create new entry to entries and add entry to the field created.

In my example, I have an Article page entry type and added an Entries fields.

I created an article, clicked on edit article,  add entry on my entries field.
<img width="1428" alt="Screen Shot 2020-05-03 at 6 57 42 PM" src="https://user-images.githubusercontent.com/48315691/80912858-8a0b3580-8d72-11ea-8ad3-405c05ccbc0e.png">
<img width="1453" alt="Screen Shot 2020-05-03 at 7 01 10 PM" src="https://user-images.githubusercontent.com/48315691/80912862-92fc0700-8d72-11ea-8538-06668a496f82.png">

**Issue here is I don't need to self reference same article.**
<img width="1450" alt="Screen Shot 2020-05-03 at 7 01 26 PM" src="https://user-images.githubusercontent.com/48315691/80912899-e2dace00-8d72-11ea-8aaa-c5ebd96d43a3.png">

Thanks in advance!

**Comment by Mosnar** [comment]
I'm guessing this type of functionality won't come around until Craft 4 where fields are created as instances and are more context-aware. I wanted to do something similar where an entry select field in a Matrix block is modified to show only entries related to the selection in another entry select field in the same block. It's pretty tricky but very do-able. Here's my code for that:
https://gist.github.com/Mosnar/1a9f5909303ca945c28b1fc48fa6a434

I _would_ suggest using Craft 3.4.16,
`craft\fields\BaseRelationField::EVENT_DEFINE_SELECTION_CRITERIA`
https://github.com/craftcms/cms/issues/4299#issuecomment-615192553

HOWEVER; this event doesn't have context of the owner element, so it wouldn't do you any good since you don't know which element to exclude. Maybe that's something @brandonkelly could add to the event?

**Comment by brandonkelly** [comment]
You shouldn’t be able to relate an entry to itself, so that’s a bug. I found two cases where it wasn’t working as expected:

- When editing an entry draft
- When the relation field was within a Matrix field or other block-based field.

@dharnell-abluyen I’m not sure what type of field “Content Carousel” is, but if its block elements implement [BlockElementInterface](https://docs.craftcms.com/api/v3/craft-base-blockelementinterface.html#public-methods) then 8d5ce92ac1130e788ab17fac34a412a72a43fad1 will fix this for you.

**Comment by brandonkelly** [comment]
Craft 3.4.18 is out now with this fix.

**Comment by dharnell-abluyen** [comment]
great, It worked. thanks!
