### ISSUE TITLE
Project confing sync fails: Couldn't save single entry due to validation errors on the slug and/or URI

### ISSUE THREAD

**Issue by nflorentin** [craftcms/cms#6051]
Hi,

I'm having a very frequent problem when I create single entries. I tried to investigate a lot digging into the code run by project-config/sync and the validation process but I could not find any solution.

The steps to reproduce are the following:
1. I create a single entry without any problem, so the project.yaml is updated
2. I push the project.yaml to the repo
3. Another developer does a git pull and get his project.yaml updated
4. He runs ./craft project-config/sync and gets the following error: {"error":"Couldn't save single entry due to validation errors on the slug and/or URI: Comité d'investissement"}
5. His database is now in a inconsistant state because the **entry type** is created but the **entry** is not. 

One thing I'm 100% sure is that he has not created another page with the same slug (he only does frontend work so never creates new entries or entry types). I reproduced the same bug on the pre-production site which has allowUpdates set to false.

I think the problem comes some data in my DB which clashes with the new single entries but I don't know how to find it. It happens with any single entry type (no matter the URI I set). I tried to explore the DB by hand and did not find any entry with the same slug.

Another problem is that I did not find any solution to fix the problem by hand. I can't create the entry manually. Probably because the entry is created when the entry type is created, only once, so Craft does not provide any way to create it manually.

I'm worried because the site will continue growing while in production and we will obviously add new single entry types in the future.

If anyone has a solution or a means to find the objet which clashes and triggers the validation error, that would be awesome.

Thanks you!

### Additional info

- Craft version: Craft Pro 3.4.9
- PHP version: 7.3.8
- Database driver & version: PostgreSQL 11.3

**Comment by andris-sevcenko** [comment]
Can you try updating Craft to the latest Craft 3.4 version and see if the problem persists, first?

**Comment by nflorentin** [comment]
Thanks for your quick answer @andris-sevcenko.

I just updated my app to the last Craft version (3.4.19) and I still have the issue.

**Comment by nflorentin** [comment]
I think I could be on the track of the cause!

I create a Section "Single", then I configure the entry type. For the title, the default is `{section.name|raw}`. If I stay with this default, I'm not having the issue.

But I want my client to have the control over that title, so I have a field named "customTitle" I use for various Section Single.
So the title input value is `{customField}`. I also tried `{customField|raw}` but it does not help.
With that value for the title input, It fails everytime.

I'm not sure if it is a bug or an expected behaviour. As the value of the customField is not saved into the file `project.yaml`. When syncing, the value of the customField is empty, which could be the cause of the error ... ? 

Thanks for your help and sorry for my bad english.

**Comment by nflorentin** [comment]
Hallelujah, I think I just found a workaround. 

I replaced the value of the title input `{customTitle}` with `{% if object.customTitle %}{object.customTitle}{% else %}{{ 'A DEFAULT AND UNIQUE TITLE' }}{% endif %}`.

I hope it will help someone in the future because it took me something around 10 hours to find it 😄.

**Comment by andris-sevcenko** [comment]
Nice detective work!

Sounds like the expected behavior resulting in a confusing behavior. We'll talk this over internally!

**Comment by brandonkelly** [comment]
I can see how this happened: when you create the Single section initially, it’s created with the default Title Format of `{section.name|raw}`, so the title (and slug) can be determined right away.

When new environments are applying these changes, the entry type is immediately created with your custom Title Format, based on a custom field that doesn’t have a value yet. So the entry never has a chance to be saved under valid circumstances, like it did on your original environment.

I’ve just fixed this via 09d2654cc3167becb2d9a265ef31d58aa1d2c018, which tweaks entries a bit so they only apply their custom title format if the result of it is not blank. Otherwise it will fall back to whatever the currently-stored title is, which in the case of a single entry will be the section’s name.

That fix has already been released as part of Craft 3.4.19.1, so if you update Craft you should avoid this issue going forward, without needing to include a fallback value in your title format to work around it.
