### ISSUE TITLE
Uploading image to asset volume causes 502 error on Craft 2 and Craft 3

### ISSUE THREAD

**Issue by adamseabrook** [craftcms/cms#6144]
### Description
Trying to upload the attached file fails with a POST 502 error in the browser. The upload seems stalled visually but you can see the 502 in dev tools.

### Steps to reproduce

1. Try to upload the attached image to an asset volume

### Additional info

- Craft version: Craft Pro 3.4.20
- PHP version: 7.4.1
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Anchors 2.2.0, Architect 2.3.3, Field Manager 2.1.6, Google Cloud Storage 1.3.0, Linkit 1.1.11, Minify 1.2.10, Navigation, 1.3.15, Position Fieldtype 1.0.15, SEOMatic 3.3.4, Super Table 2.4.9, Workflow 1.5.1 
- Server logs:
```
2020-05-27@13:31:51
nginx-staging
123.123.123.123 - - [27/May/2020:03:31:51 +0000] "GET /admin/assets/temp HTTP/1.1" 200 18414 0.162 "https://domain.com/admin/settings" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" upstream
2020-05-27@13:31:51
nginx-staging
123.123.123.123 - - [27/May/2020:03:31:51 +0000] "POST /index.php/admin/actions/element-indexes/get-elements?v=1590550311599 HTTP/1.1" 200 10148 0.114 "https://domain.com/admin/assets/temp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" upstream
2020-05-27@13:31:52
nginx-staging
123.123.123.123 - - [27/May/2020:03:31:52 +0000] "POST /index.php/admin/actions/element-indexes/count-elements?v=1590550311977 HTTP/1.1" 200 43 0.065 "https://domain.com/admin/assets/temp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" upstream
2020-05-27@13:31:56
nginx-staging
123.123.123.123 - - [27/May/2020:03:31:56 +0000] "POST /index.php/admin/actions/assets/upload HTTP/1.1" 502 565 0.867 "https://domain.com/admin/assets/temp" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" upstream
2020-05-27@13:31:56
nginx-staging
2020/05/27 03:31:56 [error] 7#7: *17500 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 123.123.123.123, server: , request: "POST /index.php/admin/actions/assets/upload HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "domain.com", referrer: "https://domain.com/admin/assets/temp"
2020-05-27@13:31:56
php-staging
[27-May-2020 03:31:56] WARNING: [pool www] child 4014 exited on signal 9 (SIGKILL) after 15.797270 seconds from start
2020-05-27@13:31:56
php-staging
[27-May-2020 03:31:56] NOTICE: [pool www] child 4015 started
```
![causes-502-7426x5304-20200526](https://user-images.githubusercontent.com/368555/82975265-49c06f80-a01f-11ea-8b87-fce02bbb5de4.png)

**Comment by adamseabrook** [comment]
Adding a ZIP incase Github tries to fiddle with the image.
[causes-502-7426x5304-20200526.png.zip](https://github.com/craftcms/cms/files/4686331/causes-502-7426x5304-20200526.png.zip)

**Comment by andris-sevcenko** [comment]
Well, there are a number of things here.

First - it ends up being a configuration issue, since I can upload that file locally and the error you're getting indicates `php-fpm` timing out.

Now, the file does get blown up to 8MB from 800kb, which is curious, so I took a closer look at what's what.

I'll save you the twists and turns, but here the ending - that file is a JPG file, not a PNG file.

This has two consequences:

1) PNG files don't have EXIF data so it cannot be cleansed by cleansing the EXIF part, so this means that to cleanse it, the file must be re-saved as an image, which takes up some time, and obviously space. This also leads to the second consequence:

2) Craft has no other option for cleansing than to re-save it. As a PNG. Turns out a 5300x7400 image is not ideal for PNG. If you convert that specific JPG (posing as PNG) to a PNG file online, the outcome is a whopping 7.4MB file.

Also on https://github.com/craftcms/cms/issues/3287#issuecomment-634410423 you say
> Our images are cropped and compressed in our own editor before we upload them so we just want Craft to display the images as provided.

What editor are you using? It seems like the solution for you is to stop using the wrong extension :)
