### ISSUE TITLE
Craft CMS allows duplicated entry slug even with 'maxSlugIncrement' preset

### ISSUE THREAD

**Issue by bruno-canada** [craftcms/cms#6152]
### Description
We had an issue with one of our clients where he was having multiple entries with the same slug.

After some investigation, I was able to find that saving an entry with disabled status would not pass through Craft auto-incrementing slugs function, even with `maxSlugIncrement` preset.

Please, note that `maxSlugIncrement` It is by default 100 and we should not have this type of issue even not presetting that in our config.

**Reason for saving entry with disabled status:**
This particular website receives stories submission from the user and they are reviewed before being enabled by the client; however, once enabled it does not regenerate the slug nor throw an error to be changed causing issues to load on the frontend.

### Steps to reproduce

1. Save multiple entries passing the same title using status disabled:
$entry = new Entry();
**$entry->enabled = false;**
$entry->title = "test";
$return = Craft::$app->elements->saveElement($entry);

### Additional info

- PHP version 7.2.28
- MySQL 5.7.30
- Craft Pro 3.3.13

**Comment by brandonkelly** [comment]
This is expected behavior. Craft actually never cares about duplicate slugs, only duplicate URIs (so there’s no ambiguity when Craft is trying to route a request for an element based on the requested URL). Slugs only get automatically incremented in Craft’s attempt to find a unique URI for an element.

There was a _slight_ change in behavior in 3.4.6, where we no longer enforce unique URIs for disabled elements, to avoid situations where an element can’t be created/saved properly due to a duplicate URI when duplicating an existing entry (see #5510). Maybe that’s the change you’re noticing?
