### ISSUE TITLE
EVENT_BEFORE_EXECUTE_GQL_QUERY query not modified

### ISSUE THREAD

**Issue by jan-thoma** [craftcms/cms#6186]
### Description

We need to protect some fields which should never be returned from the GraphQL-API. ` Gql::EVENT_BEFORE_EXECUTE_GQL_QUERY` seems to be appropiate event to alter a query before it's get executed and remove the fields from the query.

### Steps to reproduce

In a Module try to run this code to remove the query. The query gets executed without modification in it's initial state

```
        Event::on(Gql::class,
            Gql::EVENT_BEFORE_EXECUTE_GQL_QUERY,
            function(ExecuteGqlQueryEvent $event) {
                $event->query = null;
            }
        );
```

### Additional info

- Craft version: 3.4.22.1 Pro
- PHP version: 7.1.33
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Setting the query to `null` would lead to a PHP error down the line, and by the time this event has been fired we’ve already finished validating that the query is not `null`, so doesn’t make a ton of sense to have to do that all over again.

I’d say maybe instead of trying to overwrite the `$query`, just throw an exception from there – either `yii\base\BadRequestHttpException` (400) or `yii\base\ForbiddenHttpException` (403).

**Comment by andris-sevcenko** [comment]
Another approach would be to use an event to remove the available fields from the schema altogether: https://github.com/craftcms/cms/blob/develop/src/gql/TypeManager.php#L32-L47
