### ISSUE TITLE
Overwrite success flash message for specific frontend entry form

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6192]
It would be useful if we had the ability to overwrite success flash message for specific entry form. For example by using hidden input with specific `name` value.

**Comment by stenvdb** [comment]
👍 

This has recently been implemented in commerce (https://github.com/craftcms/commerce/commit/427ddb009dda6dc8f151755dd0c529291a29a42d) and craftcms (https://github.com/craftcms/cms/commit/0e4d4988cf7477bb0003c6109c67f72cbdb699ac). But this will start to get complicated of we have a separate name for each type of flash message I think (ie "cartUpdatedNotice", "userRegisteredNotice", ...). 

Wouldn't it be better to have a more generic way of passing flash messages like so?

``` {{ hiddenInput('flash', 'My custom flash notice') }}```

**Comment by brandonkelly** [comment]
For 3.5, I’ve just added new `setSuccessFlash()` and `setFailFlash()` messages to the base web controller class, which will check for hashed `successMessage` and `failMessage` params on the request, and use those if provided rather than the default message. All of Craft’s flash messages now go through that, and we’ll update Commerce as well.

```twig
{{ actionInput('entries/save-entry') }}
{{ hiddenInput('successMessage', 'Custom success message'|hash) }}
{{ hiddenInput('failMessage', 'Custom fail message'|hash) }}
```

I’ve also deprecated support for the `userRegisteredNotice` param for the next 3.4 release, and it has been fully removed in 3.5. I’d keep it around longer, but it poses a slight security risk, since it doesn’t require the value to be hashed.

**Comment by piotrpog** [comment]
@brandonkelly 
nice, thanks!
