### ISSUE TITLE
Users cannot activate themselves on headless mode. Activation email redirects to a 404 

### ISSUE THREAD

**Issue by bzin** [craftcms/cms#6226]
### Description

In a project we use Craft CMS with `headless` mode enabled. 

We want the users to be able to activate their account and update their passwords in the CP.

Not sure if this is a bug or not but when a user is added in `headless` mode it seems that some cp templates are not available anymore. I would assume or expect some exceptions unless overwritten by the developer. It is strange that a user receives the activation email with a link that does not work

### Steps to reproduce

1. Have Craft CMS in Headless Mode
2. Create an user account
3. The user activation email contains the setpassword link but this route is a 404

**Comment by brandonkelly** [comment]
If you grant the user access to the control panel as part of the initial save, then their activation email will link to a control panel page. Otherwise it will link to the front-end. If you’re using Craft in headless mode, then it’s just on you to provide that front-end page. Craft can only provide it for you if Craft is the one that is responsible for handling front-end requests, which is not the case with headless mode.

**Comment by bzin** [comment]
Oh ok, thanks for the explanation @brandonkelly.

Maybe as an idea but I would see it very useful if this type of information could be be added somewhere on Craft documentation. There is probably more people that want to use Craft in `headless` mode and still be able to use some of this functionality for the users flow?

**Comment by brandonkelly** [comment]
Agree, we should do a better job explaining the ramifications of headless mode. We’ve added it to our list :)

**Comment by mcclaskiem** [comment]
@brandonkelly In the case where the CMS is hosted on a different domain, it feels weird that we would have to drive people to a different domain just to activate an account or build another React app just to let someone set/reset a password. Since the pages/templates already exist in Craft I would assume that an exception can be made to still leverage the Craft default templates for a few routes on the "CMS" domain. Is there any way to easily override this via a module or plugin or possibly adjust `headlessMode` in a future release?

**Comment by brandonkelly** [comment]
@mcclaskiem what do you mean “drive them to a different domain”?

**Comment by mcclaskiem** [comment]
Right now our CMS is hosted at `admin.domain.com` and the front-end is hosted at `domain.com`. If we were to use our front-end to let them set/reset password that means that they would be trying to access `admin.domain.com` but need to be driven to `domain.com` and have routes set up to handle the tokens, form fields, etc. on what is simple a static marketing website. Maybe I am misunderstanding the earlier comments but it seemed like we had to build pages to handle this functionality if we are going to use `headlessMode`.

**Comment by brandonkelly** [comment]
@mcclaskiem Activation emails will only link to the control panel IF the user has permission to access the control panel. Otherwise they will link to the front-end site.

Typically with headless mode setups, the front-end lives on a completely separate web server (like Netlify), so there’s nothing Craft can do to provide a default activation page, as it’s not getting invoked in the first place.

**Comment by mcclaskiem** [comment]
Ok so we just need to make sure we give permissions before we hit inital save or resend the activation email after they have been given permissions?

**Comment by brandonkelly** [comment]
@mcclaskiem only if you have a good reason to give them access to the control panel. And from your initial comment, it doesn’t seem like you want them being sent to `admin.domain.com` in the first place.

**Comment by mcclaskiem** [comment]
In this case, it is the client team that is going to be managing the content post-handoff so they will need CP access in order to do so.

**Comment by bzin** [comment]
@mcclaskiem the case you described is the exact use case I give in some of my projects. 

We use a subdomain for the admin. They could even be in different servers so this do not use the same resources as the frontend.

What I start doing has soon as @brandonkelly described how this works was that I decided to disable the `headless` mode. 
I basically set a redirect in the index on the admin subdomain that sends the user to the frontend website. This way the emails for activating an account they are still working and use the CP routes. Any other route that gets into the `templates` directory of the admin is redirected to the frontend website.

**Comment by fThues** [comment]
> Activation emails will only link to the control panel IF the user has permission to access the control panel. Otherwise they will link to the front-end site.

I've created a user that belongs to a group with control panel access, but the activation link still goes to the frontend (as defined in `PRIMARY_SITE_URL`). Running Craft Pro 3.5.9 in headless mode. Shouldn't the activation link be using the CP URL instead in this scenario?

**Comment by devanflaherty** [comment]
Hey there,
Just seeing this thread as I'm working on moving our craft/vue site to a craft/nuxt site with headless mode enabled.

I've had everything working magically until I hit this email verification issue.

I'm able to register a new user, receive the activation email, but the link to activate looks like so:
`http://localhost:3000/verifyemail?code=gobble-de-gook"

A couple of things here.
1. I can't seem to find a place to update the link to confirm the email. No config settings, nothing, so I'm assuming I'm forced to handle the activation of the email on my front-end at the route `/verifyemail`, which is just slightly annoying to not be able to set this.
2. I'm not following in the documentation how to actually process the confirmation of the users account/email. Is there some other craft action I should be hitting and sending the `code` to? or could someone point me to some insight on how to handle this for our front-facing users?

Any help would be super appreciative.

**Comment by brandonkelly** [comment]
@devanflaherty It should be based on your site’s Base URL. Go to **Settings** → **Sites** → [your site] to verify that.

**Comment by eriknygren** [comment]
@devanflaherty I have resolved this by using a nuxt proxy like this:

```
  proxy: {
    '/verifyemail': {
      target: process.env.API_URL,
    },
```
If you have the `$PRIMARY_SITE_URL` set to your front end server, you can forward it on from your front end, and craft will redirect you back to your root page. This will successfully activate accounts, however: This does not create a session, so you still have to prompt the user with a login form after. I'm sure there's a better way

Is there a craft config option available to change the  email verify link? ideally I would like to have the email point towards something like `myfrontend.test/confirm?code=<code>` and I'll call the `verifyemail` endpoint myself in an ajax call from there. In other words: it would be great to be able to name these endpoints ourselves

**Comment by riccardolardi** [comment]
I was hoping to find a solution for this using a nuxt proxy as @eriknygren described but it's out of question for me since I'm using static nuxt build and nuxt proxy doesn't work with `nuxt generate`. Is there any other solution to this? It seems all that would be needed is a field for headless users to define a backend URL?

**Comment by brandonkelly** [comment]
We just released Craft 3.6.12 with an improvement for this: now user activation and password reset links will point to the control panel when Craft is running in headless mode, regardless of whether the user has permission to log into the control panel.

This is consistent with another change made in 3.6.0, where asset transform generation URLs always link to the control panel for headless mode (#5553).

**Comment by Anubarak** [comment]
@brandonkelly Please provide a way to revert that change.
Most of our projects in headless mode work via REST APis with external sources but those activation links should indeed point to an external URL with our custom style (which was the case) This is kinda a breaking change (again) because it has unwanted side effects

**Comment by brandonkelly** [comment]
@Anubarak How were you handling the activation / password reset requests?

**Comment by Anubarak** [comment]
@brandonkelly thanks for your fast reply. I created routes in my frontend (vue) for all those paths and the urls from craft point to those with reset forms.
Those forms then perform ajax request to my custom controller that handle the activation.

**Comment by brandonkelly** [comment]
@Anubarak Interesting, thanks.

I’ve just tweaked this a bit for the next release. General behavior stays the same, however you can now set the `setPasswordPath` and `verifyEmailPath` config settings to absolute URLs, in which case Craft will respect them even if it’s running in headless mode.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"3.6.13.x-dev"` and run `composer update`. Then adjust those config settings to be absolute URLs.

**Comment by Anubarak** [comment]
@brandonkelly thank you so much 🤗
You cannot imagine how grateful I am because of your great support

**Comment by brandonkelly** [comment]
Craft 3.6.13 is out with this change.

**Comment by eriknygren** [comment]
Thanks @brandonkelly, FYI, in our scenario as well we'd like the average front end user to not be aware of the control panel url at all, and only talk to our FE nuxt app. So this makes more sense for us

This should sort out your issue too @riccardolardi right? If I understand your scenario correctly you should now be able to do this on a static nuxt app via setting the `verifyEmailPath`

**Comment by riccardolardi** [comment]
@eriknygren actually in my case it was enough to change `baseCpUrl` to the backend URL https://craftcms.com/docs/3.x/config/config-settings.html#basecpurl - now the emails sent by Craft do point to the CMS URL.

**Comment by julianklotz** [comment]
Dear folks,

thank you, this discussion helped me a lot.

I think it would make sense to provide a full headless example in the docs, like this (feel free to copy-paste and edit):

For this example, we assume CraftCMS is running under https://cms.example.org, the public-facing frontend is running under https://example.org.

1. Set up new CraftCMS installation
2. For localized content, create one site per language and set the base URL according to your needs:
  * https://example.org/en/
  * https://example.org/fr/
  * […]
  This step is important, otherwise tools like redactor won’t be able to build proper URLs.
3. Set `'headlessMode' => true` in `config/general.php`
4. [At this point, password reset emails still point to the frontend route. Which other steps are necessary?]

**Comment by BrandonJamesBorders** [comment]
@julianklotz Set this config: https://craftcms.com/docs/3.x/config/config-settings.html#basecpurl
