### ISSUE TITLE
Matrix blocks duplicated the first time an element is saved after creating a new site group, with propagation method "Save blocks to other sites in the same site group"

### ISSUE THREAD

**Issue by benface** [craftcms/cms#6244]
### Steps to reproduce

1. Create a matrix field with only one block type containing a plain text field, and set its propagation method to "Save blocks to other sites in the same site group".
2. Add that matrix field to an entry type inside a section with the propagation method "Save entries to all sites enabled for this section", and add the field to a global set as well (only one of them should be necessary to reproduce, but let's make sure).
3. In the default site, create an entry of that type and add some blocks with some content in the matrix field. Do the same in the global set.
4. Create a new site group, then create two sites in it, with two different languages.
5. Enable the new sites in the section you added an entry in (under Settings > Sections > [The Section] > Site Settings).
6. Edit the entry in one of the two new sites. Don't make any change, just re-save the entry.
7. Edit the entry in the other new site (in the same site group as the first one). Notice every block in the matrix field has been duplicated.
8. Edit the global set in one of the two new sites. Don't make any change, just re-save the set.
9. Edit the global set in the other new site. Again, notice every block in the matrix field has been duplicated.

### Additional info

- Craft version: 3.4.24
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
When you add a new site, Craft adds new “Propagating [element type]” jobs to the queue for global sets, assets, categories, and tags. Each of those jobs load up all of the current elements in the original site ID, and save them for the newly added site.

Similarly, when you enable new sites for a section, a “Resaving entries” job will be added to the queue, which loops through all the entries for the section and re-saves them, ensuring they get propagated to the newly-enabled site.

In both cases, each time an entry is finished getting saved/propagated, your Matrix field gets looped in to ensure that all of its blocks are saved/propagated—or duplicated—as well. In your case, since A) you have the Matrix field’s propagation method set to save blocks for each site group, and B) you’ve added a new site from a different site group, Matrix will opt to duplicate the existing blocks over to the new site.

All of this happens via the queue, so there is a race condition where if you happen to start editing a global set / entry _before_ the element gets saved/propagated, it could result in duplicate data like you’re seeing.

I did verify that everything works as expected if you just let the job complete before editing any additional content.

**Comment by benface** [comment]
Hey @brandonkelly, thank you for the explanation. My repro steps were not exactly right, it looks like the primary site has something to do with it as well. I recorded my screen while reproducing the issue for you, I think it's going to be much easier to understand this way: https://www.youtube.com/watch?v=3L_LX40KfgI. The unexpected duplication happens at 1:44. After that, I am just showing that the bug doesn't seem to extend further.

Let me know if you need more information.

**Comment by brandonkelly** [comment]
Aha, thanks for that! Was able to reproduce. Turns out what was happening was:

1. When you create “Group 2 EN”, the blocks from the primary site are duplicated over to it – as expected.
2. When you create “Group 2 FR”, the blocks from the primary site are duplicated over to it as well, not accounting for the fact that blocks in Group 2 FR should be shared with blocks in Group 2 EN.

I’ve just fixed this for the next release. Now Matrix will check if the new site should be sharing blocks with any preexisting sites, and if so, it will resave blocks from one of those preexisting sites (which will cause them to be propagated to the new site), rather than duplicating the primary site’s blocks.

**Comment by benface** [comment]
Awesome, thanks Brandon!

**Comment by brandonkelly** [comment]
Craft 3.4.26 is out now with the fix.
