### ISSUE TITLE
RFC - Consider a primary key for templatecacheelements

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/cms#6246]
Hi There,

To scale our application, we use a databasecluster. The only pitfall with Crafts default db setup is that `templatecachelements` does not have a primary key.

Can you consider setting a multi-column primary key for this table?

**Comment by brandonkelly** [comment]
We just released Craft 3.4.25 which adds a primary key on that table – but the change will only affect **new** Craft installs, because it’s generally not needed unless you’re on an environment that requires primary/composite keys on tables, and that table is deprecated in Craft 3.5, so I didn’t feel it was worth a (potentially long-running) migration for existing installs.

Feel free to add a PK to that table yourself, if an existing install is affected by this.
