### ISSUE TITLE
Twig "switch" tag - allow using single code block for multiple "case" statements

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#6255]
Branch CMS which also implements `{% switch %}` Twig tag, allows using single code block for multiple `{% case %}` statements:

```
{% set value = 'value2' %}
{% switch value %}
    {% case 'value1' %}
        <p>value is "value1"</p>
    {% case 'value2' %}
        <p>value is "value2"</p>
    {% case 'value3' %}
    {% case 'value4' %}
        <p>value is "value3" or "value4"</p>
    {% default %}
        <p>value is something else</p>
{% endswitch %}
```

Heres link to docs:
https://www.branchcms.com/learn/docs/developer/twig/tags/item/switch

It would be useful if Craft implementation also allowed this.

**Comment by brandonkelly** [comment]
I’d say that allowing multiple `{% case %}` tags come hand-in-hand with requiring explicit `{% break %}` tags, so we’re fully matching the normal `switch` block flow.

Normal switch blocks will process all code from the first matching `case` statement up until the first `break` statement that follows it. For example:

```js
let myVariable = 'foo';
let counter = 0;

case myVariable {
  case 'foo':
    counter++;
  case 'bar':
    counter++;
    break;
  default:
    counter++;
}
```

… `counter` will equal `2` by the end, because there was no `break` statement before `case 'bar'`.

But the combination of multiple matching `case` statements plus `break` statements feels too cumbersome for a templating system. So instead of going that route, Craft’s `{% case %}` tags support multiple matching values, separated by `or` operators.

I just realized that wasn’t actually documented, though, so I’ve just fixed that:

https://docs.craftcms.com/v3/dev/tags.html#checking-multiple-values-from-a-single-case-tag

**Comment by piotrpog** [comment]
@brandonkelly `or` solution is actually better than this one used by branch cms, thanks for letting me know about it.
