### ISSUE TITLE
status=disabled conflicts with enabledForSite param

### ISSUE THREAD

**Issue by timkelty** [craftcms/cms#6273]
### Description

from @brandonkelly on Discord:
> enabled:false = globally disabled elements (which are enabled for the selected site)
> enabled:false + enabledForSite:false = globally disabled elements (regardless of site status)
> status:"disabled" = shortcut for enabled:false + enabledForSite:false

However, this is NOT currently true.

In a multi-site, if an ElementQuery contains `status: 'disabled'`, `enabledForSite:false` should be implied, but is not. This is causing disabled elements to not show in circumstances like: https://github.com/craftcms/redactor/issues/236

Instead, you will end up with conflicting conditions in your query like:

```
[
  'elements_sites.enabled' => true,
  [
    'or',
    ['elements.enabled' => false],
    ['elements_sites.enabled' => false],
  ]
]
```

- Craft version: 3.4.24

**Comment by brandonkelly** [comment]
This is working as expected, and is why element indexes are passing `enabledForSite: null` as well. We will look into what’s missing and why for Redactor, but most likely it’s not a bug with Craft.

**Comment by timkelty** [comment]
Still doesn't make much sense to me…

In a multi-site, that means to query for disabled elements, `status=disabled` would never be sufficient, and you'd always have to include `enabledForSite=false` as well.

Also seems weird that things are explicitly passing `null`, when `enabledForSite` seems to explicitly expect a bool (https://github.com/craftcms/cms/blob/develop/src/elements/db/ElementQuery.php#L1011).

**Comment by brandonkelly** [comment]
Alright agreed, this is all pretty confusing. I’ve admittedly never been super happy with the `enabledForSite` param, since it only lets you determine whether the site status should be factored in or not. (Setting it to `false` or `null` won’t give you elements that are disabled for the current site; that will just omit the site status from being a factor.)

I’ve just made the following changes for Craft 3.5:

- The `enabledForSite` param is now deprecated, and set to `false` by default (as in “don’t worry about it”).
- It is now solely the `status` param’s responsibility to worry about elements’ site statuses.
  - `enabled` will give you elements that are enabled both globally and for the current site.
  - `disabled` will give you elements that are disabled either globally or for the current site (or both).

That should be a lot more clear.
