### ISSUE TITLE
[3.5 beta 3] Activation email includes link to wrong URL

### ISSUE THREAD

**Issue by daltonrooney** [craftcms/cms#6300]
### Description

The site's base URL is different from the CP URL. When I create a new user and send the activation email, the link points to the site base URL and not the CP URL.

### Steps to reproduce

1. Create a new user
2. Send registration link or copy registration link from CP

### Additional info

- Craft version: 3.5 beta 3
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
The control panel URL will only be used if the user has permission to access the control panel, at the time the email is sent.

**Comment by daltonrooney** [comment]
@brandonkelly Can you tell me what looks incorrect here? Sorry for the obfuscated URLs, the site is not public yet. 

![Screen Shot 2020-07-01 at 4 47 52 PM](https://user-images.githubusercontent.com/742045/86301502-e942c600-bbba-11ea-98af-73c8b861ffd3.png)

![Screen Shot 2020-07-01 at 4 48 03 PM](https://user-images.githubusercontent.com/742045/86301684-50f91100-bbbb-11ea-896d-7ad2eb482808.png)

**Comment by brandonkelly** [comment]
@daltonrooney Couple things to check:

- Do you have the [baseCpUrl](https://docs.craftcms.com/v3/config/config-settings.html#basecpurl) config setting set?
- Go to Utilities → PHP Info, and search for `$_SERVER['HTTP_HOST']`. What is its value?

**Comment by daltonrooney** [comment]
Thanks, baseCpUrl fixed it. 

The value for `$_SERVER['HTTP_HOST']` was correct, but that's not what was being used for the the activation URL. Not sure if that's of interest or not.

**Comment by brandonkelly** [comment]
Were the activation emails being sent from the control panel or from the front-end?

**Comment by daltonrooney** [comment]
Right from the CP.

**Comment by brandonkelly** [comment]
Huh, strange. Well, glad the `baseCpUrl` config setting fixed it.

**Comment by FreekVR** [comment]
This has been closed, but it seems to issue still persists unless a `baseCpUrl` is hardcoded. Seems to be a regression, since I know this was working before.

Have the same issue as OP:

1. Create a new account with "Admin" AND "send activation URL" checkbox ticked
2. URL in mail is set to primary-site.com/admin/set-password[...] where cms-url.com/admin/set-password is expected

Checked the `HTTP_HOST` and this is set correctly, and no explicit `baseCpUrl` is defined. I will, however, add this as a workaround for now, but I don't think this was needed before.

**Comment by brandonkelly** [comment]
Just looked into that. Here’s where this logic lives:

https://github.com/craftcms/cms/blob/5ef456281de838d9180c6bfb2f1b8de74268b424/src/services/Users.php#L1302-L1316

That code has been refactored a bit over the years, but the logic has been in place since 2.6.2976, via commit 38c594badc8efc468b6162ec921d645011a50d35:

https://github.com/craftcms/cms/blob/38c594badc8efc468b6162ec921d645011a50d35/src/services/UsersService.php#L1681-L1691

That release had the following security note in its release notes:

> Fixed a potential security vulnerability that made it possible to fire off a forgot password email with a modified URL.

In other words, Craft is guarding against a host header attack.

**Comment by FreekVR** [comment]
Yeah, so if I'm reading the code there correctly it will always use the default site URL, unless the user has access to the CP AND an explicit baseCpUrl has been defined.

If this is "as designed" perhaps it would be good to mention this in the docs for headlessMode, as I feel that having the CMS and frontend on different domains may be quite common, and it currently doesn't mention this, instead it just says:

> With Headless Mode enabled, users may only set passwords and verify email addresses via the control panel or controller actions. Be sure to grant “Access the control panel” permission to content editors and administrators that should be able to log into the control panel unless you’re providing your own auth forms.

Perhaps change it to something like this;

> With Headless Mode enabled, users may only set passwords and verify email addresses via the control panel or controller actions. Be sure to grant “Access the control panel” permission to content editors and administrators that should be able to log into the control panel unless you’re providing your own auth forms. If your CMS and default site frontend run on different domains, make sure to also set the [`baseCpUrl`](https://craftcms.com/docs/3.x/config/config-settings.html#basecpurl) configuration value to whatever domain your CMS runs under.

**Comment by brandonkelly** [comment]
Good call. [Done](https://craftcms.com/docs/3.x/config/config-settings.html#headlessmode).
