### ISSUE TITLE
[3.4] rememberedUsername when useEmailAsUsername is true

### ISSUE THREAD

**Issue by jamiewade** [craftcms/cms#6312]
### Description
The [starter login form](https://docs.craftcms.com/v3/dev/examples/login-form.html) shows how you can set the saved username as a value, which is great:

```
<input id="loginName" type="text" name="loginName" value="{{ craft.app.user.rememberedUsername }}">
```

However this doesn't play great for sites that have the `useEmailAsUsername` [config option](https://docs.craftcms.com/v3/config/config-settings.html#useemailasusername) enabled.

By setting `useEmailAsUsername` to true, we don't want our users to even be aware of the concept of usernames on this site. And we would ideally like for their saved email address to be populated on the login form, rather than a username.

Also, even with this config enabled Craft still stores a username for accounts, comprised of the first letter of your first name and your surname (jwade).

Am I missing something, or is this something new that needs to be added?

**Comment by brandonkelly** [comment]
> By setting `useEmailAsUsername` to true, we don't want our users to even be aware of the concept of usernames on this site.

Yeah, that’s exactly what the config setting is intended for.

> Also, even with this config enabled Craft still stores a username for accounts, comprised of the first letter of your first name and your surname (jwade).

I’m guessing that username was created before `useEmaiAsUsername` was enabled, and the user hasn’t been saved since. Once it’s enabled, users’ usernames will always be set to their email address on save:

https://github.com/craftcms/cms/blob/06416c24cfd4e03c16a1364a6aa9b6073b369d9a/src/controllers/UsersController.php#L1040-L1045

**Comment by RitterKnightCreative** [comment]
> I’m guessing that username was created before useEmailAsUsername was enabled, **and the user hasn’t been saved since.** Once it’s enabled, users’ usernames will always be set to their email address on save...

@brandonkelly  Holy cow, so this little nugget of information would be useful to have in the docs. 

During dev, I used usernames on a recent client build, but before the site went live, switched everything over to email addresses to make it easier for Commerce customers. 

However, even to this day, almost a year later, Craft was still spitting out my old username instead of the email address in login spots.  I thought I was going mad, resetting cookies, trying different browsers, etc.  However, going into my user account in the CP, and just hitting save, It fixed everything.

FWIW now that 3.5 has some support for detecting config changes, I wonder if a task worker could be kicked off it it notices that config change and simply resaves any affected accounts that aren't email addresses?

**Comment by brandonkelly** [comment]
@RitterKnightCreative Yeah good call. I just added a new `utils/update-usernames` command that ensures all usernames match email addresses.

```bash
$ php craft utils/update-usernames
10 usernames updated.
```

**Comment by jamiewade** [comment]
Thanks both, what @RitterKnightCreative is describing is exactly what happened with me.

`useEmailAsUsername` was enabled _during the build of the project_, by which point my account was already created and therefore had a username of `jwade`.

Thanks for adding that @brandonkelly

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with the new `utils/update-usernames` command.
