### ISSUE TITLE
No successful flash message when account is verified by email

### ISSUE THREAD

**Issue by icreatestuff** [craftcms/cms#6333]
### Description
I have public user registrations enabled and a form setup to handle the registration details.
In that form I've added `{{ hiddenInput('successMessage', 'Please check your email to confirm account.'|hash) }}` to customize the flash message when this registration is successful. This works perfectly, the users sees the custom message once the form submits and receives the email to verify/activate their account. 

When the user clicks on the link in that email they are taken to the site and their account is successfully activated **but** the user doesn't get any message to tell them anything has been successful. 

I have the following code in my template
```twig
{% if craft.app.session.getFlash('error') %}
    <div class="flash-message flash-message--error">{{ craft.app.session.getFlash('error') }}</div>
{% elseif craft.app.session.getFlash('notice') %}
    <div class="flash-message">{{ craft.app.session.getFlash('notice') }}</div>
{% endif %}
```
I've also tried dumping out all the flash data in case the message was under a different key to `notice` or `error`:
```twig
{{ dump(craft.app.session.getAllFlashes()) }}
```
but it returns an empty array.

_Should_ there be a message showing at this step in the registration process?

I've spotted the `activateAccountSuccessPath` config variable and set that to the frontend login page. If possible I'd prefer to not have to setup an alternative interim 'activation successful' template.

### Steps to reproduce
1. Enable public registrations
2. Create registration form on the frontend
3. Register a user
4. Click the link in the verify/activation email
5. See no flash message

### Additional info
- Craft version: 3.4.27
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26

Thanks,
Matt

**Comment by brandonkelly** [comment]
If we were to add a notice, you wouldn’t have any control over its message, since email verification happens immediately when they click the link in the email – there’s no form you can submit custom params from in this case. So I would say it’s best to take advantage of the `activateAccountSuccessPath` config setting. You can set it to something like `?activated=1`, and that will redirect them to the homepage with that query string – and you can check for that via `craft.app.request.getQueryParam('activated'`.

Or you could set it a path that routes to a custom controller action, and you can set the flash notice from there, and then redirects them to your homepage or wherever.
