### ISSUE TITLE
Feature request - Allow admin changes during migration

### ISSUE THREAD

**Issue by TimvanDijkhuizen** [craftcms/cms#6404]
### Description

I think it would better if project config changes were allowed during a migration. I've recently had trouble migration because the plugin was trying to change its own settings. I don't think there is any other way for plugins to migrate settings, which is why I've created a feature request here instead of reporting this to the plugin author.

**Comment by Anubarak** [comment]
The plugin can check for the environment and if those changes are allowed. 
In case they are, do the plugin settings changes so they'll update the project config and be synced to live environment. In case it's not allowed (live environment) the project config will handle it. 

Imagine the other case - the migration that will update the project config runs twice. That's much more fatal

**Comment by brandonkelly** [comment]
Yeah this isn’t possible. Migrations are run before incoming project config changes are applied, and since Craft doesn’t support two-way syncing (nor could it), if a migration were to make a project config change while other changes were pending, it would leave your loaded/pending project configs in conflicting states.

Plus, in theory if you need to run a migration on an environment that has `allowAdminChanges` disabled, then whatever changes the migration wants to make to the project config will have already been made on another environment, and should already be pending in `project.yaml`. Which is why we [recommend](https://docs.craftcms.com/v3/extend/project-config.html#project-config-migrations) that your migration checks the incoming schema version before making any project config changes. If you strictly stick to what we’ve outlined in the docs, then you shouldn’t ever have to worry about whether `allowAdminChanges` is disabled or not.
