### ISSUE TITLE
[3.5-RC3] Problems with `bodyClass`?

### ISSUE THREAD

**Issue by lindseydiloreto** [craftcms/cms#6459]
### Description

I have a plugin called [CP Body Classes](https://github.com/doublesecretagency/craft-cpbodyclasses) which injects additional classes into the `<body>` tag. It doesn't seem to work properly with Craft 3.5, and I'm trying to get to the bottom of why not.

Right off the bat, it throws an error about an "Array to string conversion". I worked through that easily by converting the type of my value.* But then I hit another problem...

**The classes I'm applying simply don't appear.** They don't get added at all. Regardless of whether `bodyClass` is being set as an array or as a string, the new values just don't seem to appear in the source code.

> \* Side note... I believe the conversion to an array was done by mistake. [Searching the codebase](https://github.com/craftcms/cms/search?q=bodyClass&unscoped_q=bodyClass) for other signs of `bodyClass` seemed to imply that it is generally still being treated as a string. Perhaps the array conversion was unintentional?

### Steps to reproduce

1. Install Craft 3.5
2. Install CP Body Classes
3. Possibly see "Array to string conversion" error. Make simple changes to fix that.
3. Notice that the dynamic `<body>` classes are not appearing in the source code.

### Additional info

- Craft version: 3.5-RC3
- Plugins & versions: CP Body Classes (v2.2.0)

**Comment by brandonkelly** [comment]
I was able to fix the “Array to string conversion” error – there were a couple places in CP layout templates where `bodyClass` was assumed to be a string, though in 3.5 it can also be an array.

You can update to that right away by changing your `craftcms/cms` requirement to `3.5.x-dev`, and then running `composer update`.

Not able to reproduce your main issue though. I suspect the issue is that you have something in your HTML that is cutting off the `<head>` section prematurely – browsers will kill the `<head>` and start the `<body>` as soon as it hits an element that isn’t allowed inside the `<head>` (which is why we never see any new tag types ever added to the `<head>` – it would be a backwards compatibility nightmare). If this happens, the `<body>` tag in the HTML will be ignored. So maybe try going to `view-source:http://example.com/...` and search for `<body` and see if the classes are getting added there as expected. If so, whatever the first element you see in your browser’s DOM inspector after the opening `<body>` tag is probably your culprit.

**Comment by lindseydiloreto** [comment]
I've pushed a fix for partial compatibility. It at least fixes the "Array to string conversion" error popping up in the plugin. You can grab that patch here...

```
"doublesecretagency/craft-cpbodyclasses": "dev-v2-dev"
```

But I'm still seeing the main issue. I'm 99% confident that the HTML tags are being output normally. I've also updated to the latest Craft `3.5.x-dev`.

### Steps to reproduce (bonus)

**2.5)** Go into the settings of CP Body Classes, and check every single box. This should make it more obvious, since it'll try to jam a whole bunch of additional classes into the `body` tag.

#### Craft 3.4
```html
<body class="ltr userlevel-admin userid-1 currentsection-settings currentpage-settings">
```

#### Craft 3.5
```html
<body  class="ltr" dir="ltr">
```

You'll see that the custom styles simply aren't getting added to the collection.

You can hack the plugin here (where we just added 3.5 compatibility), and dump the value of `$context['bodyClass']`...

https://github.com/doublesecretagency/craft-cpbodyclasses/compare/v2-dev

You'll see that `$context['bodyClass']` correctly contains a bunch of new classes. Any idea why those classes aren't being included when the `body` tag is eventually rendered?

**Comment by brandonkelly** [comment]
Ah I see, it’s happening because by the time the `cp.layouts.base` template hook is triggered, the `bodyClass` variable is no longer needed:

https://github.com/craftcms/cms/blob/3.5/src/templates/_layouts/base.html#L11-L19

I could shuffle things around so the hook gets called earlier, but it’s more powerful the way it is – now you can add _any_ attributes to the `<body>` tag, not just modify `class`. So you should just change this code:

```php
if (is_array($context['bodyClass'])) {
    // Craft >3.5, merge with existing array
    $context['bodyClass'] = array_merge($context['bodyClass'], $c->bodyClasses);
} else if (is_string($context['bodyClass'])) {
    // Craft <3.4, merge with existing string
    $allClasses = implode(' ', $c->bodyClasses);
    $context['bodyClass'] .= " $allClasses";
} else {
    // Fallback, set as new array
    $context['bodyClass'] = $c->bodyClasses;
}
```

to:

```php
// Determine current structure of body classes
if (isset($context['bodyAttributes'])) {
    // Craft >3.5, append to bodyAttributes.class
    array_push($context['bodyAttributes']['class'], ...$c->bodyClasses);
} else {
    // Craft <3.4, merge with existing string
    $allClasses = implode(' ', $c->bodyClasses);
    if (isset($context['bodyClass']))
    $context['bodyClass'] .= " $allClasses";
}
```

**Comment by lindseydiloreto** [comment]
Ahh, good to know. That snippet worked perfectly, thanks @brandonkelly! 🍺

**Comment by brandonkelly** [comment]
Craft 3.5 RC4 is out now with the “Array to string conversion” error fixes.

**Comment by lindseydiloreto** [comment]
Fantastic, thanks Brandon!

**Comment by whiteiswhite** [comment]
Hey guys, I know it's been a while, but I'm stuck for a few days with the exact same problem.... Except that i've the 3.5.0 release version with your fixes included, but the problem is still here.
Just upgraded from Craft 2 to Craft 3.5.0, and had to upgrade CPBodyClass to 2.2.1 with that.
If I check every parameter on CPBodyClass, no class is added to the body, but it was working on craft 2.

I didn't encounter the Array to string conversion message as original files already include :

` if (isset($context['bodyAttributes'])) {
                        // Craft >3.5, append to bodyAttributes.class
                        array_push($context['bodyAttributes']['class'], ...$c->bodyClasses);
                    } else {
                        // Craft <3.4, merge with existing string
                        $allClasses = implode(' ', $c->bodyClasses);
                        if (isset($context['bodyClass']))
                            $context['bodyClass'] .= " $allClasses";
                    }`

I'm nowhere close to a craft expert so I'm running out of ideas to explore. Maybe you can help me solve this.
Thank you very much, 
Have a nice day

**Comment by whiteiswhite** [comment]
@lindseydiloreto Hey Lindsey, do you think that could help solve the problem ? Does craft 3.7 have an inner Body class system ? 
I inherited from this project that had so many dependancies problems, actually upgrading to 3.5 was an achievement to me. (It was a craft 2, with many deprecated modules), that's why I didn't push further, but I might try if you think it can help with this problem

**Comment by lindseydiloreto** [comment]
Yeah, I'd recommend bringing everything up to the latest version. Some of the bugs you are encountering may have already been worked out.

The transition from Craft 3.5 to 3.7 is a piece of cake compared to what you just did. Might as well go all the way to the end before you iron out any wrinkles.

**Comment by whiteiswhite** [comment]
Ok, thanks for the infos, i'll try and make my way to 3.7 and start working from there then. Still have a clone from my current app anywy.
Have a good day Lindsey.

**Comment by whiteiswhite** [comment]
Hey guys. I've made it to Craft 3.7.20 and my site is stable, but my Body Classes still won't appear. 
CP Body Class 2.2.1, Craft 3.7.20, so both are at their latest version.
When you say "I suspect the issue is that you have something in your HTML that is cutting off the <head> section prematurely", how could I check this effectively ? 
Thanks for your precious help.

**Comment by lindseydiloreto** [comment]
@whiteiswhite DM me on Craft Discord and I'll help you sort it out. 👍
