### ISSUE TITLE
[3.5.0-RC3] Add 'Delete' button to contextual menu on Field Layout editor

### ISSUE THREAD

**Issue by joshua-martin** [craftcms/cms#6467]
### Description

I feel like there should be a 'delete' button on the Field Layout editor. 

![image](https://user-images.githubusercontent.com/1694957/88646290-e99c8700-d0bc-11ea-8b23-4cadd1be6c63.png)

The current click + drag functionality to remove is not immediately intuitive–it took me a minute or so to figure out that I needed to just drag the element off into the ether.

You could also present a drop-zone area that says 'Trash' or similar to capture the drop element. At the moment there is no feedback to the user about what they should do.

**Comment by mmikkel** [comment]
This is probably mostly due to muscle memory after using the old field layout designer for years, but even after some days of using the new one I consistently click the cogwheel when I want to remove an element :)

In any case, I agree the popup should probably include a remove/delete button, in addition to retaining the current drag-to-remove behaviour.
