### ISSUE TITLE
GraphQL - Field permissions

### ISSUE THREAD

**Issue by TimvanDijkhuizen** [craftcms/cms#6479]
### Description

I've recently used the GraphQL API for the first time and its really great. However, I think its pretty essential to be able to define which fields can be queried per entry type. This because some fields contain sensitive data while the others need to be accessible from the frontend.

My current project doesn't have any fields with sensitive information, but a lot of other projects I've worked on do. For those other projects I cannot use GraphQL because it would expose those sensitive fields too.

I'm not sure if this is possible in GraphQL but I sure hope it is :)

**Comment by andris-sevcenko** [comment]
This can be pulled off with a custom module or a custom plugin, since [there is an event for modifying available fields](https://github.com/craftcms/cms/blob/develop/src/gql/TypeManager.php#L21-L50).

There's definitely room for a small GraphQL helper plugin, which would expose such configuration options via UI, but I'm not sure it belongs in the core Craft CMS.

I'll leave this open, though, so it's not lost between the cracks.

**Comment by brandonkelly** [comment]
I think this will be covered by #947, which I’m going to try to get into 3.6.
