### ISSUE TITLE
upscaleImages=false not respected when using relative transform sizes

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/cms#6530]
Let's say we have an image that is 500x500. We request a transform of 200x200, with sizes 1x, 2x, 3x. This means we will end up with three transforms - 200x200, 400x400 and 600x600. The last transform is larger than original image, which means that image was upscaled. Even if `upscaleImages` setting is set to false.

Maybe there should be some possibility of preventing that? So in that case the last transform would become 500x500 - original size of image.

_Originally posted by @piotrpog in https://github.com/craftcms/cms/issues/5774#issuecomment-668228511_

**Comment by andris-sevcenko** [comment]
@piotrpog What Craft version are you experiencing this on? Can't reproduce it locally and it looks to be fixed at least on Craft 3.4.21.

**Comment by piotrpog** [comment]
@andris-sevcenko 
Tested on `3.6.x-dev`. 

But it turns out that picture was not actually upscaled, I just checked generated transform filename which was as if itw as upscaled - something like `_600x600_crop_center-center_none/image.jpg`. but didn't checked actual transformed picture size. The image itself was not upscaled. Sorry for the false report!
