### ISSUE TITLE
[3.5] New 'language' field breaks existing custom field

### ISSUE THREAD

**Issue by wsydney76** [craftcms/cms#6564]
### Description

There is a new `craft\base\ElementInterface::getLanguage()` method, which turns out to be a breaking change in case you have set up a custom field `language`. Might not be so uncommon e.g. as a category field for the language of a book/document

`{% set language = entry.language.one %}`

`Impossible to access an attribute ("one") on a string variable ("en-US").`

It is still possible to create a new field with the handle 'language'.

So:
* `language` should be a reserved word
* Should be documented as a breaking change in the upgrade guide
* The changelog says `Added the language field when querying elements via GraphQL.`, which is a bit misleading because the field is obviously also available in twig/php too.

Same for `localized` ?

### Steps to reproduce

1. create a new category field with the handle 'language'.
2. try to access it

### Additional info

- Craft version: 3.5.0
- PHP version:
- Database driver & version:
- Plugins & versions:

**Comment by andris-sevcenko** [comment]
Looking at the code, it seems like an oversight. Any _magic_ field access [should return a content field if such a field exists](https://github.com/craftcms/cms/blob/develop/src/base/Element.php#L1411). 

It seems like a simple `$this->getFieldValue($name);` there would suffice since it also normalizes the content field value, however, the code around there is 2 years old and I might be unaware of some logic why it's deferring further to `parent::_get()` there, so I'll kick this up the food chain to @brandonkelly.

Until this is resolved, you can work around this by calling `{% set language = entry.getFieldValue('language').one() %}`

**Comment by brandonkelly** [comment]
Good call, @andris-sevcenko. Just made that change for the next release, as well as adding `language` (and `localized`) to the reserved field handles list.

**Comment by brandonkelly** [comment]
Craft 3.5.2 is out now with those changes.
