### ISSUE TITLE
Assets Relocated on ./craft resave/entries

### ISSUE THREAD

**Issue by kerns** [craftcms/cms#6599]
### Description

I have a dynamic asset path in an asset field that uses `{entry.postDate}` among other things to organize files a little more coherently.

But I noticed that running `resave/entries` needlessly relocates assets to a new location based on the _current_ date, ...which seems like a needless operation in my S3 bucket, one that also disrupts the cache.

I have no idea if there is a bug with the plugin, or in the command line script that interacts with the plugin, or both or...

- Craft version: Pro 3.5.2
- PHP version: 7.4.4
- Database driver & version: MySQL 5.6.47
- Plugins & versions: Amazon S3 | 1.2.9

**Comment by brandonkelly** [comment]
@kerns Is it doing this for _all_ entries, or just those that don’t have post dates yet?

**Comment by kerns** [comment]
@brandonkelly I don't have any entires without postDates afaik. (i.e. no drafts, disabled posts or post on/after date x.)

**Comment by andris-sevcenko** [comment]
I'm able to reproduce this. How strange. Looking into this!

**Comment by andris-sevcenko** [comment]
Ugh. I feel like I'm having a toxic relationship with Twig's `date` filter - every time I swear I'll remember it's quirks for the next time - I forget.

Anyway. You should be using`{postDate|date('<FORMAT>')}` instead of `{entry.postDate|date('<FORMAT>')}`. There is no `entry` object in that context, so `entry.postDate` renders to null and, whenever you apply the `date` Twig filter to a null value, it assumes the current date, causing the dynamic folder to be different depending on the time you run `./craft resave/entries`.

🤦‍♂️

**Comment by kerns** [comment]
Same here. 🤦🏻‍♂️ Well spotted – sorry for sending you down that rabbit hole. Thanks. 🙏
