### ISSUE TITLE
When Updating from 3.4.30 a bunch of the project config files did not get created.

### ISSUE THREAD

**Issue by simeon-smith** [craftcms/cms#6609]
### Description
When I updated from 3.4.30 to 3.5 a bunch of the project config files did not get created. I ended up having to run a `./craft project-config/rebuild` to fix it.

### Steps to reproduce

1. Update from 3.4.30.
2. Some of the project config files will be missing.
3. Run `./craft project-config/rebuild` and you will see additional files being created.

### Additional info

- Craft version: 3.4.30 to 3.5
- PHP version: 7.4
- Database driver & version: 8.0 MySQL

**Comment by brandonkelly** [comment]
Which files were created? Were the values in those files removed from another file at the same time?

Some amount of this is expected on `rebuild` in 3.5, since the components are now directly involved in producing their configs, so the rebuilt configs should be more thorough than before. And it’s also possible that the public GraphQL schema access settings will be _created_ at the time of the rebuild, if that’s the first thing to ever try to access them.

**Comment by brandonkelly** [comment]
For example, all of the changes here are expected, which is the result of running `rebuild` for the first time after updating to 3.5: https://github.com/craftcms/demo/commit/b149487110c7353e2ea39195eef08fbe50b01cf3

**Comment by simeon-smith** [comment]
Yes, a bunch of these are similar to items you have in your commit where it updated the structure of the data and included more details on the project config file.
![Screen Shot 2020-08-11 at 4 46 57 PM](https://user-images.githubusercontent.com/43895851/89959908-4be3a480-dbf2-11ea-900c-b523f01327a4.png)

It appears that the files that were created were all for Commerce. Particularly the order statuses which without was causing this issue: https://github.com/craftcms/commerce/issues/1639.

There were several duplicate (but with different guid) files there were deleted.

**Comment by brandonkelly** [comment]
So yeah the sorts of things you see added in that Happy Lager commit, and in your screenshot, are totally expected due to config normalization.

With Commerce, sounds like your config may have been in a bad state to begin with. Try doing the following:

1. Restore a pre-3.5 database backup, and Composer files.
2. Run `composer install` so you get the old software versions.
3. Delete your `storage/runtime/cache/` and `storage/runtime/compiled_classes/` folders.
4. Ensure that `useProjectConfigFile` is set to `true` in `config/general.php`.

Then run `php craft project-config/rebuild` and see whether you end up with similar changes (albeit all in `project.yaml` since we didn’t start splitting the project config into multiple files until 3.5).

**Comment by simeon-smith** [comment]
I did something similar which worked for me.
