### ISSUE TITLE
[FR] Partial Project Config

### ISSUE THREAD

**Issue by OscarBarrett** [craftcms/cms#6633]
### Description

We have a multisite project that is currently using a project config file.
Non-developers want to be able to create new sites, and so at the moment that involves us asking them to create it on a staging environment (that allows admin changes), then a developer making the same changes and committing an updated project config file.
If we're not made aware that they created a new site in our staging environment and we deploy an unrelated change, these new sites are also wiped out.

Ideally we'd like to continue using a project file but exclude sites from being included in it. Would this be possible in the future, or is there a way that we could prevent the project config sync process from removing sites that don't appear in the project config?

**Comment by brandonkelly** [comment]
The way to do this would be to treat your staging server as a development environment, with its own copy of the repository checked out. When new sites are added there, commit the project config changes just like you would on any other dev environment, and then those changes can be merged with the other repo clones.

**Comment by OscarBarrett** [comment]
I started writing a plugin that would PR the project config changes, but I see [the ability to download the project config](https://github.com/craftcms/cms/issues/3979) has been added in 3.5.6 which is an easy alternative :+1:

**Comment by wallacio** [comment]
I'd like to open this back up again, since in my case the solution or reason for closing doesn't necessarily address the initial feature request of a 'partial project config'.

I've asked this on [StackExchange](https://craftcms.stackexchange.com/questions/36410/maintaining-and-deploying-many-multi-site-from-a-single-codebase) but to summarise:

I'm developing a headless Craft-based application which will be deployed as distinct, multi-site instances to each client. Each client has their own freedom in Staging to add new sites using common sections, entry types and fields. I have an event handler that enables all sections for that site when it's created. The creation of a site and enabling sections for it is a project-config change, so syncing this untouched back to the repo that will ultimately be deployed to all other clients is a no-no. 

My current, hacky thinking is that I manually parse and edit YAML (outside of Craft, or using the Service?) before syncing, such that the workflow is as follows:
We know that there should only be one site in project-config in the repo, the 'default'.
- Remove any dev-added sites from sites
- Remove any  dev-added sites from siteGroups
- Remove any dev-added sites from sections->siteSettings:<site>
After deployment to staging, deployed project-config is the 'truth', so:
- Read existing client-added sites data from sites (anything that's not 'default')
- Merge client-added sites into sites
- Merge client-added sites into siteGroups
- Merge client-added sites into sections->siteSettings:<site>

This falls down if any kind of non-sites related updates are made to project config on staging. Ideally this would be prevented by setting allowAdminChanges to false on staging too but project config needs to be enabled there so that sites can be created.

Being able to exclude additional sites from config would do away with a potential mess. There would however need to be a matching ability to create sites (on Staging) whilst allowAdminChanges is false.

**Comment by OscarBarrett** [comment]
@wallacio We're in a similar situation where we have some multi-tenant projects where we'd rather not have to include sites in the project config and need to allow the creation of demo sites.

Our current solution is to have completely separate staging and demo environments. Staging is for testing new features and bug fixes (that require project config changes unrelated to sites) whereas the demo environment is used for demoing sites, may not have the latest changes and is reset to the true project config when appropriate.

I agree that the ability to exclude sites from the project config would be very useful but with the way the project config is set up with Craft I don't believe it's an easy fix at this stage.

**Comment by brandonkelly** [comment]
There are too many inter-dependencies between sites, sections, etc., for us to make certain aspects of it opt-out-able. It’s got to be all or nothing.
