### ISSUE TITLE
Craft 3.5.5 - New entry doesn't auto focus the Title field

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#6662]
In previous versions of Craft (before 3.5), clicking New Entry would give you an edit screen with the Title field auto-focused to start typing.
Now that the field layout designer has changed and allows you to move the Title field, it no longer auto-focuses it. As this would be impossible if the title field moves to the second tab, perhaps it could auto-focus the first field on the new entry?

**Comment by brandonkelly** [comment]
Just re-added the `autofocus` attribute to Title fields, so they will get autofocused so long as they are on the first tab. Would prefer to autofocus the first text input on the page, but that would be significantly more complex and probably not worth it since Title fields will typically be listed first anyway.

**Comment by brandonkelly** [comment]
Craft 3.5.6 is out now with that change.
