### ISSUE TITLE
Single tries to generate URI

### ISSUE THREAD

**Issue by niels-vormenvorm** [craftcms/cms#6684]
### Description

I've got a multy language page. When I try to save it,  it can't active the dutch version of the single. it gives the following error when I try to activate the page:
'Kan geen unieke URI genereren op basis van de URI-indeling.' the translation would b somehting like: 'cannot generate an unique URI based on the URI'.. IT's a signle so why is it generating an URI in the first place?

it's just that one page for that one language, everything else works fine.

### Steps to reproduce

1. Save an entry
2. active a entry for a langaue

### Additional info

- Craft version: 3.5.2
- PHP version: 7.3.20
- Database driver & version: MySQL 5.5.5
- Plugins & versions:

**Comment by angrybrad** [comment]
This was because two elements in the database already have the URI for the site the Single was being saved in.  That should never happen because a URI has to be unique on a per-site basis.

The two elements that happened to have that URI for that site were coming from the Navigation plugin. Deleting the two nodes that were using that handle allowed us to save the Single section without issues.

My guess is there is or was a bug in the plugin because it sounds suspiciously similar to https://github.com/verbb/navigation/issues/180

**Comment by Jan10** [comment]
I had the same problem with a section that I had deleted. After I deleted the entry in the database (thanks @brandonkelly for the SQL), I could create a new section with the same name.

But I could not reproduce the problem with the current version.
