### ISSUE TITLE
EntryQuery::typeId() does not accept array syntax with `not` anymore

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#6754]
### Description
After Updating to Craft 3.5 the `typeId` syntax stated in the PHPDoc via `['not', 1, 2]`
https://github.com/craftcms/cms/blob/develop/src/elements/db/EntryQuery.php#L417
does not work anymore, cause `not` is not a string in `_normalizeTypeId` https://github.com/craftcms/cms/blob/develop/src/elements/db/EntryQuery.php#L921

### Steps to reproduce

1. Run `Entry::find()->typeId(['not', 1, 2])->all();`
2. see an exception `yii\base\InvalidConfigException: Invalid typeId param value` because `is_numeric('not')` returns false

### Additional info

- Craft version: 3.5.x

**Comment by brandonkelly** [comment]
Whoops, sorry about that. Fixed for the next release.

**Comment by Anubarak** [comment]
Thank you. But what's the point in querying for the correct ids again? My whole point in passing ids instead of the handle is to reduce the amount of queries.
If you keep it like that I wouldn't use the `not` syntax anymore but add a custom `and where` to achieve the same functionality as before

**Comment by brandonkelly** [comment]
In 3.5 we need to know the exact entry type IDs (if specified) so we can register them as cache invalidation tags, if a cache is actively being created:

https://github.com/craftcms/cms/blob/b6280588722e1ee67bb810e8027f0c53b7cc9ea2/src/elements/db/EntryQuery.php#L1019-L1022

That way if the query is surrounded by `{% cache %}` tags or used within a GraphQL query, the cache will only be cleared when an entry with the exact same type is saved/deleted, rather than any entry in the same section.

**Comment by brandonkelly** [comment]
Craft 3.5.8 is out now with that fix.
