### ISSUE TITLE
Make updates via the CP safer and more user friendly

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#6770]
### Description

Helllo,

I feel that updating in Craft, while very easy and convenient to do via one-click in the CP, can sometimes feel like a "black-box" to the user: no visible steps, no real progress indicator apart from the "spinner" and some text that you might miss, and if something goes wrong, you are not sure if you have to roll-back the DB or whatnot. This is especially problematic in shared hosting environments (I know) where there may be no ssh access, or the db backup via the CP can fail for various reasons. So a lazy person like me can (ahem..will) sometimes decide to do a cowboy update, with no up-to-date DB backup. And get burned :)

What I suggest, as a very "low-hanging-fruit" partial solution is to at least have a "backup-database" first step visible in the update screen, and if that fails, give the option to proceed on your own risk, or abort. You could do the same for composer files etc or whatever you feel that makes sense.

That's it! Thanks for your great CMS :)

**Comment by brandonkelly** [comment]
We are most likely going to be dropping the web-based installer in Craft 4, because it often runs into memory/time limits, which are typically much more restrictive for web requests than for the CLI. Ideally, you should be running (and testing) updates locally, and pushing the new `composer.lock` file to your server and running `composer install` from there. Or if you don’t have SSH access, use a deploy tool like [Buddy](https://buddy.works). See our [Deployment Best Practices](https://craftcms.com/knowledge-base/deployment-best-practices) knowledge base article for more details.

> What I suggest, as a very "low-hanging-fruit" partial solution is to at least have a "backup-database" first step visible in the update screen, and if that fails, give the option to proceed on your own risk, or abort. You could do the same for composer files etc or whatever you feel that makes sense.

The updater does this already, after Composer has finished updating the files, right before it starts making database changes. By holding off until then, we can keep your site online for the longest possible time.
