### ISSUE TITLE
Pagination broken in VueAdminTable

### ISSUE THREAD

**Issue by goraxan** [craftcms/cms#6835]
### Description
I have a working VueAdminTable (the table shows the correct data, but without the pagination element at the bottom) which throws the following error (paginationData is null apparently) when data is received from the server
![image](https://user-images.githubusercontent.com/8337784/93202832-aa50f500-f753-11ea-8dea-52dd3b85de31.png)
![image](https://user-images.githubusercontent.com/8337784/93202879-bd63c500-f753-11ea-99c8-b1361b10dbf8.png)

The server response is the following:
![image](https://user-images.githubusercontent.com/8337784/93203070-09af0500-f754-11ea-9b88-1161ae08e14d.png)

### Steps to reproduce

1. Create a VueAdminTable with the following code
```
{% do view.registerAssetBundle('craft\\web\\assets\\admintable\\AdminTableAsset') -%}
{% block content %}
    <div id="actions-vue-admin-table"></div>
{% endblock %}
{% js %}
    var columns = [...];
    var actions = [...];

    new Craft.VueAdminTable({
        actions: actions,
        checkboxes: true,
        columns: columns,
        container: '#actions-vue-admin-table',
        emptyMessage: Craft.t('No actions exist yet.'),
        perPage: 5,
        tableDataEndpoint: '/api/actions'
    });
{% endjs %}
```

### Additional info

- Craft version: 3.5.7
- PHP version: 7.2.24
- Database driver & version: 
- Plugins & versions:

**Comment by nfourtythree** [comment]
Hi @goraxan 

I believe this issue here was actually some outdated docs. I have just pushed an update to the admin table readme (424c548febdd2c6650b487af3ae6f7ad4ff86d8e), we had removed the `links` key in the return response as it was creating an extra level for no real reason.

If you move you `pagination` key to the top level you should find that this all works as expected.

A good place to cross-reference your implementation of an admin table that uses an endpoint is the [Customers controller in Commerce](https://github.com/craftcms/commerce/blob/develop/src/controllers/CustomersController.php#L109-L183). Hopefully this gives a decent example of how we have used this functionality.

Thanks!

**Comment by goraxan** [comment]
Awesome, thanks!
