### ISSUE TITLE
{% nav %} not properly working inside {% ifchildren %} after {% children %} on last element

### ISSUE THREAD

**Issue by Dollhopf** [craftcms/cms#6841]
### Description
Inside the `{% nav %}`, inside the `{% ifchildren %}` and after the `{% children %}` the recursive variable of the last element is off by one recursion.

#### Twig File
```twig
<ul>
    {% nav page in craft.entries.section('page').all() %}
        <li>
            Start {{ page.id }}
            {% ifchildren %}
                <br>Start {{ page.id }} children
                <ul>
                    {% children %}
                </ul>
                End {{ page.id }} children
            {% endifchildren %}
            <br>End {{ page.id }}
        </li>
    {% endnav %}
</ul>
```

#### Outcome
```HTML
<ul>
  <li>
    Start 5
    <br>End 5
  </li>
  <li>
    Start 212
    <br>Start 212 children
    <ul>
      <li>
        Start 227
        <br>End 227
      </li>
      <li>
        Start 230
        <br>End 230
      </li>
      <li>
        Start 233
        <br>End 233
      </li>
    </ul>
    End 212 children
    <br>End 212
  </li>
  <li>
    Start 245
    <br>Start 245 children
    <ul>
      <li>
        Start 440
        <br>Start 440 children
        <ul>
          <li>
            Start 470
            <br>End 470
          </li>
        </ul>
        <!-- Everything before as expected -->
        End 470 children
        <br>End 440
      </li>
    </ul>
    End 440 children
    <br>End 245
  </li>
</ul>
```

#### Expected Outcome
```HTML
<!-- Everything before same as real outcome -->
        End 440 children
        <br>End 440
      </li>
    </ul>
    End 245 children
    <br>End 245
  </li>
</ul>
```

### Steps to reproduce

1. Create mutliple entries with multiple layers of hierarchy.
2. Use `{% nav page in craft.entries.section('page') %}`.
3. Access `page` variable inside `{% ifchildren %}` and after `{% children %}`.

*(See code above)*

### Additional info

- Craft version: Craft Solo 3.5.8
- PHP version: 7.4.9
- Database driver & version: MySQL 5.7.31
- Plugins & versions:
  - Redactor 2.7.4 
  - Super Table 2.6.2 
  - Typed link field 1.0.23

**Comment by brandonkelly** [comment]
This is happening because `{% ifchildren %}` and `{% endifchildren %}` are not normal conditional tags. They are only used to establish what HTML should be output before/after the nesting level increases/decreases as the `{% nav %}` tag is looping through the elements. But the actual context at the time when the code between `{% ifchildren %}` and `{% children %}` is output will actually be the first child element; not the parent element. And the context at the time when the code between `{% children %}` and `{% endifchildren %}` is output will be the subsequent element with a higher level than the former element (or the end of the loop, if the last element’s level is greater than `1`). 

I’ve just updated the [docs](https://craftcms.com/docs/3.x/dev/tags.html#nav) that warns against doing anything special between these tags:

> The `{% nav %}` tag requires elements to be queried in a specific (hierarchical) order, so make sure you don’t override the `order` criteria parameter in conjunction with this tag.

**Comment by AdrianDrechsel** [comment]
Quick follow up question: I guess this behavior will remain the same in Craft 4?

**Comment by brandonkelly** [comment]
Yeah.
