### ISSUE TITLE
laminas-stdlib has removed support for < PHP 7.2

### ISSUE THREAD

**Issue by joshua-martin** [craftcms/cms#6876]
### Description

We've started noticing that we're getting errors on our pipeline deployments for our sites running PHP 7.2
```Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for laminas/laminas-stdlib 3.3.0 -> satisfiable by laminas/laminas-stdlib[3.3.0].
    - laminas/laminas-stdlib 3.3.0 requires php ^7.3 || ^8.0 -> your PHP version (7.2.33) does not satisfy that requirement.
  Problem 2
    - laminas/laminas-stdlib 3.3.0 requires php ^7.3 || ^8.0 -> your PHP version (7.2.33) does not satisfy that requirement.
    - laminas/laminas-feed 2.12.3 requires laminas/laminas-stdlib ^3.2.1 -> satisfiable by laminas/laminas-stdlib[3.3.0].
    - Installation request for laminas/laminas-feed 2.12.3 -> satisfiable by laminas/laminas-feed[2.12.3].
```
The `laminas-feed` dependency in Craft pulls `^2.12.3`, which has a dependency of `laminas-stdlib^3.2.1`. However, `laminas-stdlib` has just been pushed to `3.3.0` which [forces the version of PHP to 7.3](https://github.com/laminas/laminas-stdlib/releases/tag/3.3.0).

**Comment by brandonkelly** [comment]
Composer won’t pull in dependencies the environment is not capable of running. So if you ended up with version 3.3 of this library, then it’s likely because you ran `composer update` on an environment that is running at least PHP 7.3.

The way to guard against that is to set the `config.platform.php` property in your `composer.json` file, which tells Composer which PHP version it should look for compatible dependencies for, overriding the currently installed PHP version.

The `craftcms/craft` project [sets that to `7.0`](https://github.com/craftcms/craft/blob/master/composer.json#L37), for example, since Craft 3 requires PHP 7.0+. But you can change it to whatever the minimum PHP version is across all of your environments.

**Comment by joshua-martin** [comment]
Perfect, thanks Brandon. I did search but couldn't find any info.

**Comment by mattstein** [comment]
Noted in the [Deployment Best Practices](https://craftcms.com/knowledge-base/deployment-best-practices#mind-php-versions-across-environments) article. Thank you @joshua-martin.
