### ISSUE TITLE
Blocks disappearing in Preview when changes are made to Matrix

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#6902]
### Description
Sorry I can't be more accurate in the title. I've got an issue where opening preview and making changes will just remove certain content blocks. I think it might be related to Drafts, because they appear when you open Preview, then they disappear as soon as you make changes. Recording below - I'll also email templates/DB/composer to support.

![Screen Recording 2020-09-25 at 14 18 48](https://user-images.githubusercontent.com/1250017/94261330-5f489600-ff3a-11ea-8e60-204c9bfd5e78.gif)

### Steps to reproduce

1. Open preview
2. Make changes to a matrix field (could also be related to having images, or SuperTable, or Freeform)
3. The blocks in Preview disappear.

It looks like a basic block with redactor inside it works, but I can't track down what's making most other blocks disappear. No errors in web.log.

### Additional info

- Craft version: 3.5.11.1
- PHP version: 7.4.8
- Database driver & version: MySQL
- Plugins & versions:

Admin Bar   3.1.10
Control Panel Nav   3.0.13.1
Entry Instructions   1.0.7
Feed Me   4.2.3
Freeform   3.8.1
Knock Knock   1.2.13
Mix   1.5.2
Redactor   2.7.5
Retour   3.1.41
SEOmatic   3.3.18
Super Table   2.6.2
Typed link field   1.0.23

**Comment by brandonkelly** [comment]
This was happening because the SEO Description Source setting in SEOmatic → Content SEO → Pages → [section name] was setting the `type` param on the Matrix field’s block query, and that was sticking around further down the request when looping through the blocks within the page. Cloning the query before setting `type` fixed it (`entry.matrixField.type(...)` → `clone(entry.matrixField).type(...)`).

#5640 will fix this sort of thing in Craft 4.
