### ISSUE TITLE
Filter matrix field by type once, filter stays for next query

### ISSUE THREAD

**Issue by olsp** [craftcms/cms#6904]
### Description
I just tried this the first time and it seems like a bug to me.I have a matrix field with two blocks: text and image.For the meta description I want the first text block and so I did the following: "entry.projektInhalt.type('text').one"It works, the problem is just that when using "{% for block in entry.projektInhalt.all() %}" afterwards, I only get the text blocks.

### Additional info

- Craft version: 3.5.11.1 (Pro)
- PHP version: 7.3.7
- OS version: Darwin 18.7.0
- Database driver & version: MySQL 5.7.26
- Image driver & version: Imagick 3.4.3 (ImageMagick 6.9.6-2)
- Plugins & versions: 
    - Redactor 2.7.4

**Comment by Mosnar** [comment]
This is actually expected behavior - if you're coming from Craft 2, you used to be able to do exactly what you're suggesting; however, this is no longer the case for Craft 3. You need to clone your original query each time you want to modify it. The exact docs regarding the change are here:
https://craftcms.com/docs/3.x/upgrade.html#cloning-element-queries

In your case, you'll want to do:
```twig
{% set textBlock = clone(entry.projektInhalt).type('text').one() %}
{% set allBlocks = entry.projektInhalt.all() %}
```

Alternatively, you can avoid an additional query entirely by filtering the full block list using the [where](https://craftcms.com/docs/3.x/dev/filters.html#where) filter:
```twig
{% set allBlocks = entry.projektInhalt.all() %}
{% set textBlocks = allBlocks|where(block => block.type.handle == 'text') %}
```

There's additional docs about cloning near the bottom of this section: https://craftcms.com/docs/3.x/matrix-fields.html#working-with-matrix-field-data

**Comment by olsp** [comment]
Thank you very much for the detailed information and the example code.

Works like a charm now!

**Comment by brandonkelly** [comment]
This will start working as expected once again in Craft 4, per #5640.

**Comment by cherrykoda** [comment]
@brandonkelly thank you! this gets me every time and confuses all the new devs since it's outside the pattern of other queries.
