### ISSUE TITLE
Add an Event in craft/web/View before Cp::elementHtml()

### ISSUE THREAD

**Issue by Anubarak** [craftcms/cms#6912]
### Description

I used to display my custom records via Element index table by creating a dummy Element + a dummy Element query to wrap my custom records around it in order to have a good looking table with sort and search abilities. 
Furthermore it was a great way to use ElementRelation fields for my custom records just for displaying and frontend purpose.

Your last Update breaks my current usage, because instead of just accepting everything, your latest commit in `craft/web/View` now only accepts instances of `ElementInterfaces` while this is of course totally correct usually, I still only work with custom Models/Records and not with elements so this will throw an exception. 

Now I have 2 options... 

1. overwrite the entire field template to remove the hook
2. beg to include an event or some other way to revert this breaking change so I can still render my models instead of elements.

So please, could you allow me to remove the hook or bypass it somehow?
It would be totally fine to add an additional static attribute for `craft/base/Elements` that's default set to `_elements/element` and you include the template via that variable

**Comment by brandonkelly** [comment]
Sorry for the inconvenience. FTR what you are doing is definitely unsupported, and won’t be possible in Craft 4, however we will be enhancing the Vue-powered admin tables in Craft 4, so that will become a more compelling alternative for non-element indexes.

I’ve juts made a couple improvements to the template hook system, so as of the next release you will be able to do the following:

- Register your own custom `cp.elements.element` hook method, which gets called _before_ `craft\web\View::_getCpElementHtml()`.
- Prevent `craft\web\View::_getCpElementHtml()` from ever getting called, if you want to override the output.

Here’s what that looks like:

```php
Craft::$app->view->hook('cp.elements.element', function(&$context, &$handled) {
    // ...

    if ($isCustomRecord) {
        // prevent _getCpElementHtml() from getting called
        $handled = true;

        // ...
        return $customHtml;
    }
}, false); // <-- the `false` tells hook() to prepend your method instead of append it
```

**Comment by Anubarak** [comment]
> however we will be enhancing the Vue-powered admin tables in Craft 4
That's actually all I need. Thank you very much.
I can see why you limit everything to Elements via ElementInterfaces, but it would be so awesome if you were able to simply enhance Admintables to be able to work the same way as ElementIndex Tables.

All the endpoints via PHP are actually no problem since I already have them because of my REST API, 
I also thought about create my custom index table via Vue Admintables but I don't have time right now.
I knew but I do is not supported and never will be, it was just the easiest way to display nice selects for non-element things.

**Comment by brandonkelly** [comment]
Yep. In fact the plan for v4 is to make element indexes just an extension of admin tables, with pre-plugged-in endpoints, etc.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with those hook system changes.
