### ISSUE TITLE
Field Deleted When Changing the Redactor Config Type

### ISSUE THREAD

**Issue by isomglobal** [craftcms/cms#6913]
### Description
I noticed I chose the wrong redactor config type for the text block in a matrix field. I changed the redactor config type from Simple to Standard and saved the changes. After saving, the matrix field was deleted, and I lost all of the associated data.

### Steps to reproduce

1. Install Redactor plugin
2. Create a matrix field with text block/redactor field (config type: simple)
3. Associate field with section
4. Create an entry
5. Change the text block/redactor field config type to standard
6. Field and associated data is deleted

### Additional info

- Craft version: 3.5.11.1
- PHP version: 7.4.9
- Database driver & version: MySQL 8.0.20
- Plugins & versions: 
Freeform 3.8.2
Redactor 2.7.5
SEOmatic 3.3.18
Video Embedder 1.1.4

**Comment by brandonkelly** [comment]
I’m able to reproduce this if the Matrix field’s YAML file in `config/projects/fields/` is somehow deleted before saving the field. We’ll look into it.

**Comment by isomglobal** [comment]
Thank you.

**Comment by brandonkelly** [comment]
Alright, this should be fixed for the next release. In the meantime, if you have a database backup, you can restore it, and clear out your `config/project/` folder so your project config YAML files get regenerated in their entirety. If I’m right that the way this happened for you was due to a missing file within there, then you shouldn’t have any issues after that, even without waiting for the next Craft update.

**Comment by brandonkelly** [comment]
Craft 3.5.12 is out now with that fix.

**Comment by isomglobal** [comment]
Thanks for the update!
