### ISSUE TITLE
Upload a file has confusing behaviour

### ISSUE THREAD

**Issue by NixonGit** [craftcms/cms#6939]
### Description

The new "Upload a file" button shows even when the Assets field has reached it max file limit, I think this should follow the same behaviour as "Add an asset" and be hidden as it doesn't make much sense from a users perspective why one option is available and the other not.

It may also encourage "sloppy" behaviour from the user who will now have a much easier way of uploading directly to the default location rather than the upload modal where they at least _might_ choose a subfolder, rather than a single folder accumulating 1000s of files. Reading the issue https://github.com/craftcms/cms/issues/2778 that this update resolves I can see why it was added but I think now Craft somewhat encourages uploading to the default location.

The button text itself also isn't consistent if you've set a custom selection label e.g. "Add an image" vs "Upload a file". I would also go onto argue that it is a little confusing that both buttons can be displayed at the same time and from the users perspective do a very similar thing. I can see the benefit of uploading and selecting with a single click but am not sure it out ways the potential for confusion. 

### Additional info

- Craft version: Craft Pro 3.5.12

**Comment by TheFunkyMonk** [comment]
Agreed particularly on the first point. This screen is the most confusing to me; at the least, Upload should be hidden if max file limit has been reached so it's not hanging out on its own without the Add an asset button.

![Screen Shot 2020-10-02 at 9 51 33 AM](https://user-images.githubusercontent.com/1728770/94949408-b9df7600-0495-11eb-9e56-ccd3fef235b5.png)

**Comment by brandonkelly** [comment]
Sorry, it was a bug that the button could remain visible even when the limit had been reached. Just released Craft 3.5.12.1 with a fix for that.

Regarding the label, “Upload files” is consistent with the upload button within the asset selection modal, as well as the upload button on the Assets index page.

<img width="201" alt="The “Upload files” button within an asset selection modal" src="https://user-images.githubusercontent.com/47792/94971249-70098680-04bb-11eb-8f86-e29381d4641f.png">

We call them “files” in this case because that’s exactly what they are. We only start calling them “assets” once the file is in the system with a corresponding element record.

**Comment by TheFunkyMonk** [comment]
@brandonkelly Thanks for the super quick fix, as always!
