### ISSUE TITLE
Lots of temporary column names in matrixcontent_contentblocks table

### ISSUE THREAD

**Issue by howells** [craftcms/cms#6948]
I've had a problem for a while whereby once in a while, a project file sync leads to a database column disappearing. It's next to impossible to reproduce it, however, so I just wanted to know if you knew what was happening.

In my matrixcontent_contentblocks tables, there's a whole bunch of columns with random appended names, and its these matrix fields which seem to fail after a project sync:

<img width="334" alt="CleanShot 2020-10-03 at 17 41 54@2x" src="https://user-images.githubusercontent.com/145849/94996997-0dd68180-05a0-11eb-84a9-cc030e7dacd5.png">

Are the columns with random strings safe to remove, and do you think their existence is messing up project syncs?

**Comment by brandonkelly** [comment]
Columns get renamed like this when a new field is being added or renamed in a way that requires Craft to create/rename a `content` table column that would conflict with an existing column name. When that happens, Craft will rename the existing column in case it contains any data that shouldn’t get deleted. (Note that as of Craft 3.5.12 the columns will be renamed to `_old`, `_old2`, etc., rather than a random string.)

See #6922 for a better explanation, plus how we plan to fix it in Craft 4.

If you review the contents of these columns and don’t see any values that would be missed, go and and delete them. They are not actually being used anymore.

**Comment by howells** [comment]
@brandonkelly ah okay thanks Brandon. It's odd that it's just these fields that haven't been updated/renamed that often (not to necessity so many renamed columns), and its these ones that are often mangled up when I apply project config changes, so figured there was something. As I say I'm really struggling to consistently replicate the issue, it just happens occasionally (and never when these specific fields are touched). Odd one!

**Comment by brandonkelly** [comment]
@howells Most likely you are sharing a project config with another environment(s) that may have the same general fields / field handles, but not the same UIDs. That can happen if you start propagating project config changes without following the [environment setup instructions](https://craftcms.com/docs/3.x/project-config.html#environment-setup) first.

**Comment by howells** [comment]
@brandonkelly ah, great - thanks!
