### ISSUE TITLE
Ability to view all registered aliases

### ISSUE THREAD

**Issue by mattstein** [craftcms/cms#6992]
### Description

Since [aliases](https://craftcms.com/docs/3.x/config/#aliases) can be registered by Craft, the project’s general config, and by custom plugins and modules it’d be useful to review a comprehensive list of those ultimately available—similarly to how you can check on all existing environment variables from the **Environment** section of **Utilities** → **PHP Info**.

This would speed up the process of orienting yourself (or other developers) to a new Craft project in addition to taking the pressure off various documentation (Craft, plugin, project).

**Comment by wsydney76** [comment]
Just stumbled upon this one from a security perspective: Aliases may contain sensitive information, like '@SMTP_PASSWORD' or '@TRELLO_TOKEN', that should not be revealed in the CP (happens here because dotenv is not allowed on production servers).

So the values of aliases that contain something like PASSWORD, APIKEY, TOKEN should be hidden/obfuscated.

**Comment by brandonkelly** [comment]
🤔  On one hand it wouldn’t be too hard to start checking the alias names for sketchy-sounding names and redact their values, but on the other, that is absolutely not what aliases are for, and you are going to run into bugs using them that way. (Trailing slashes will get removed automatically, for example, which could be how your security key ends.) And redacting sensitive info would only serve to encourage this unsupported use.

**Comment by narration-sd** [comment]
An also thought -- that this blacklisting while a good idea would need to have a local way to define the list -- who can tell what key names would be dangerous; and in languages??

Maybe this would also be an opportunity to be able to define what keys not to touch, thus @brandonkelly 's insight could be provided for?

**Comment by wsydney76** [comment]
@narration-sd 

> who can tell what key names would be dangerous

If there is a short list of strings(or just one like SECRET) the aliases could be named accordingly, so  no local way needed imho.

@brandonkelly 

> you are going to run into bugs..

Thanks for that info, didn't see any issues in the past though. 

Couldn't  find another way to pass through environment specific (yes gitignored) values to CP setting fields, without  the use of environment variabes.  (I think dotenv is not wanted because it caused stability issues under heavy load on specific Windows server setups,)

**Comment by narration-sd** [comment]
@wsydney76  yes, a good way, can be better 👍

**Comment by brandonkelly** [comment]
@wsydney76 PHP Dotenv has stopped warning against being used in production since v3. Make sure you are running that (see https://github.com/craftcms/craft/blob/master/composer.json#L23 and https://github.com/craftcms/craft/blob/master/web/index.php#L13-L16 for example code), and make sure your config files are pulling in environment variables using `craft\helpers\App::env()` instead of `getenv()` (e.g. https://github.com/craftcms/craft/blob/master/config/db.php#L14-L22).

**Comment by wsydney76** [comment]
@brandonkelly Thanks, yes, we've seen and tested that, and i just verified again with a fresh Craft install: unfortunately it is still not 100% reliable in our environments. 

Sporadic errors like the following when trying to upload a bunch of images at once, obviously the db credentials were not pulled in:

`2020-10-15 10:13:06 [-][-][-][error][craft\db\Connection::open] SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)

2020-10-15 10:13:06 [-][-][-][error][craft\base\ApplicationTrait::getIsDbConnectionValid] There was a problem connecting to the database: Craft CMS can’t connect to the database with the credentials in config/db.php.
`

100% sure it has to do with the specific environment, the devops just won't spend time for this while there is a rock solid and simple workaround like `'user' => Env::DB_USER,`, just using aliases when needed for cp settings fields.

**Comment by brandonkelly** [comment]
`craft\helpers\App::env()` checks both `$_SERVER` as well as `getenv()`

https://github.com/craftcms/cms/blob/142e988624dcb0405a6e4baf126e1207e6b084fd/src/helpers/App.php#L63-L66

So whatever PHP script is currently setting those `Env:X` constants should be able to easily set `$_SERVER` values as well/instead, which would solve this for you.

**Comment by wsydney76** [comment]
Enx::X is simply an environment specific gitignored class holding the values as constants that otherwise would be in .env.

But this is leaving the context of this issue, your input and effort is very much appriciated, hopefully we will find time to dig deeper into this later.

At the moment, just seeing `SMTP_PASSWORD = *****` instead of `SMTP_PASSWORD = 123456`, with the same rules as in the PHP Info section for variables, would make us very happy.

**Comment by brandonkelly** [comment]
> Enx::X is simply an environment specific gitignored class holding the values as constants that otherwise would be in .env.

OK, but my last comment still stands. If that same file started setting `$_SERVER` keys, such as:

```php
$_SERVER['SMTP_PASSWORD'] = '123456';
```

then you could safely start referencing those “environment variables” in your CP settings (e.g. `$SMTP_PASSWORD`), as well as optionally replacing your `Env:X` references with `craft\helpers\App::env('X')` calls if you wanted.

> At the moment, just seeing `SMTP_PASSWORD = *****` instead of `SMTP_PASSWORD = 123456`, with the same rules as in the PHP Info section for variables, would make us very happy.

I don’t want to do that, sorry. Aliases are very specifically only meant for storing file paths and URLs, and I don’t want to enable unintended (and error-prone) use of them.

**Comment by brandonkelly** [comment]
Craft 3.5.13 is out now with the new Aliases list ✨

**Comment by wsydney76** [comment]
@brandonkelly Ok, thanks. Will try to adjust.
