### ISSUE TITLE
Support Guzzle 7

### ISSUE THREAD

**Issue by Mosnar** [craftcms/cms#6997]
### Description

Guzzle 6 support is starting to be phased out of use and Craft's current version requirements are making it difficult to require some modern packages that require Guzzle 7, which just released PHP 8 support.

**Comment by brandonkelly** [comment]
Guzzle 7 contains a couple breaking changes, so we can’t pull it in until Craft 4.

**Comment by brandonkelly** [comment]
Since Guzzle 7.2+ is needed to get Craft 3 fully compatible with PHP 8 (#7050), we’ve decided to pull in Guzzle 7.2+ for environments that can run it (PHP 7.2.5+), for Craft 3.6.0. (That release will focus exclusively on Guzzle and potentially other dependency updates for the sake of PHP 8 compatibility.)

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
