### ISSUE TITLE
Project config merge helper

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/cms#7002]
### Description

I frequently have merge conflicts with just the `dateModified` field. It would be cool if there can be a command that would automatically overwrite just this location with the current `dateModified` to prevent accidentally not incrementing the timestamp.

Example:
```
<<<<<<< HEAD
dateModified: 1602515640
=======
dateModified: 1602576059
>>>>>>> master
```

To merge this manually I always pick the highest timestamp (1602576059) and add 1 second to make sure that everyone gets notified of config changes (1602576059 + 1 = 1602576060).

I think it might be handy to have a command that would just specifically resolve this issue, bumping the `dateModified` by one second. Of course other parts cannot be automatically merged as easily, but this alone would resolve 90% of my merge conflicts!

**Comment by brandonkelly** [comment]
I’ve been thinking since 3.5 came out that it would be good to add a `project-config/touch` command, which just updates the `dateModified` value to the current timestamp, which would be handy when you make project config changes outside of `project.yaml` itself (e.g. to a custom field’s config file), and you need a quick way to get Craft to notice that there are pending project config changes.

If the `dateModified` is currently in a conflicted state, you would probably want the conflict resolution to result in an updated `dateModified` value as well, so all environments will pick up the changes you were merging.

So I’ve just implemented that `project-config/touch` command, and it is capable of resolving a `dateModified` conflict while it’s at it.

If there are any additional lines as part of the same conflict, those won’t be affected. For example, if you had this:

```yaml
<<<<<<< Updated upstream
dateModified: 1603054241
foo: bar
=======
dateModified: 1603054240
>>>>>>> Stashed changes
```

You would end up with this after running the command:

```yaml
dateModified: 1603131603
<<<<<<< Updated upstream
foo: bar
=======
>>>>>>> Stashed changes
```

**Comment by brandonkelly** [comment]
Craft 3.5.14 is out now with that new command ✨
