### ISSUE TITLE
loginPath, logoutPath, setPasswordPath, and verifyEmailPath, setPasswordRequestPath  - allow setting to element ID

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#7043]
Right now these settings accept hardcoded URL. They could also accept ID of the element, for example ID of login entry in `loginPath` setting.

Use case:
when we want to change the login page URL without having to change anything in config file.

There could also be some small info attached to this element edit page if its ID was used in that way - something in sidebar, like "this element is used in `loginPath` setting".

**Comment by Anubarak** [comment]
I don't think it's best practice to set this value to an element id.
You can set these attributes to functions that return the correct url, so in your config file, include a function that will return the url of that entry (by unique field, via single entry or whatever). Passing an ID will likely break sooner or later. Imagine that entry is deleted for whatever reason (maybe the author will be deleted and so the entry) or whatever. Furthermore ids are usually different in different environments.

What if I want to set the path to `10` because I like to redirect to `www.example.com/10` Craft would search for an element in that case. I highly doubt someone would do that but it's still a breaking change.

**Comment by brandonkelly** [comment]
They double as template paths so this wouldn't be possible.
