### ISSUE TITLE
Micro-project paid option

### ISSUE THREAD

**Issue by JayBox325** [craftcms/cms#7105]
### Description
I am finding myself falling in the middleground where the Pro licence has too many features & is too much of an expense for smaller projects/clients, but I am still keen to pay you guys for the software I am providing them.

This is where an entry level license between Solo and Pro would be ideal. Something like **$99** that only has the following Pro features:
- Two or three user accounts (Dev & Client)
- System Branding

This gives me the opportunity to provide a paid version of CraftCMS for clients that would usually only _really_ need Solo features, but also support you.

**Comment by brandonkelly** [comment]
Sounds pretty close to the “Client” edition that we had in Craft 2. We did away with it in favor of the `allowAdminChanges` config setting. If that’s set to `false` then you can safely give the client the admin account, and not have to worry about them making unexpected admin changes.

Appreciate the sentiment, but if Solo otherwise works for you, it’s all good :)
