### ISSUE TITLE
Caches not being set/cleared properly for Global sets

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#7166]
### Description

Updating a Global set in the Control Panel does not cause its caches to be cleared (or set) properly.

### Steps to reproduce

1. In a template, add `{% cache %}`/`{% endcache %}` tags around the output of a global.
2. Modified the content in the Control Panel → save.
3. Refresh front-end.

### Additional info

- Craft version: latest
- PHP version: 7.4

**Comment by mmikkel** [comment]
I've been bit by this, but I didn't figure it to be a _bug_ as much as a side-effect of the new tag-based caching system in 3.5. 

It only appears to happen with global sets that don't have any relational fields, which makes sense since cache tags are derived from element queries, and the global sets themselves aren't usually queried for in Twig.

It would be nice if this could work like pre-3.5, though – i.e. if Craft automatically collected appropriate cache tags for global sets, similarly to how it collects them for the matched element (i.e. `entry`).

**Comment by brandonkelly** [comment]
Just fixed this for the next release. Going forward, whenever you access the property of an element within a `{% cache %}` tag (e.g `globalSetHandle.fieldHandle`), the element will be included as a dependency of the cache.

**Comment by brandonkelly** [comment]
(You will need to invalidate all template caches before this change will take effect.)

**Comment by brandonkelly** [comment]
Craft 3.5.16 is out now with that fix.
