### ISSUE TITLE
Drafts workflow

### ISSUE THREAD

**Issue by olivierbon** [craftcms/cms#7216]
When opening an entry form and entering content, you will get an indication that a draft gets created.

If you carry on inputting then close the form (e.g clicking **Entries** in the main nav) without ever clicking **Create**, the draft is saved and remains accessible for further editing under **Drafts**.

Some users get used to this workflow and carry on working on the drafts this way, hitting **Create** only at the time of publishing. 

However, if garbage collection happens to run on the site, those drafts will get deleted as they are seen as _unsaved drafts_ and a user would lose all content.

The `purgeUnsavedDraftsDuration` ([docs](https://craftcms.com/docs/3.x/config/config-settings.html#purgeunsaveddraftsduration)) allow to change this behaviour but only in the sense that unsaved drafts _never_ get deleted.

We should probably document this and/or maybe notify users _inline_ (before being able to navigate away) that if not _Created_, the draft could disappear after X days (as per config).

Another option could be to change `purgeUnsavedDraftsDuration` to `0` by default so that the behaviour has to be manually enabled and therefore explained with authors.

**Comment by mmikkel** [comment]
In my opinion, the real issue isn't that authors don't understand how auto-drafts work, or that they're not aware that auto-drafts can be deleted by garbage collection. The problem is that there's currently no way to save a new entry as an actual, non-ephemeral draft – which is a common use case, especially for content editors coming over from other CMSes like WordPress.

A better way to solve this than displaying a notification/confirm dialog would be to actually have a "Save (as) draft" button for new entries, as suggested in #5661.

**Comment by brandonkelly** [comment]
Thanks for pointing that out @olivierbon! Definitely an unexpected critical flaw in the way things worked.

Now resolved for 3.6. Details here: https://github.com/craftcms/cms/issues/5661#issuecomment-739084173

**Comment by rob-baker-ar** [comment]
Glad my support ticket sparked this. Many thanks to all, this will be a great help to our content editors.

**Comment by brandonkelly** [comment]
Craft 3.6 RC2 is out now with that change.

**Comment by brandonkelly** [comment]
Craft 3.6 has now been officially released ✨
