### ISSUE TITLE
Users without delete entries permission can delete entries

### ISSUE THREAD

**Issue by carlcs** [craftcms/cms#7233]
### Description

The user doesn’t have “Delete entries” permissions for a section. The “Delete entry” action shows on Edit Entry pages and on the Entry index page for that section (see related issue https://github.com/craftcms/cms/issues/7232), and clicking those does actually delete the entry.

The user does have the “Delete other authors’ entries” permission and the entry in question is actually created by another user. This shouldn’t be of relevance though as “Delete entries” should overrule “Delete other authors’ entries”.

### Additional info

- Craft version: 3.5.16

**Comment by brandonkelly** [comment]
The way the permissions are currently laid out, I’d say this is expected behavior. As you mentioned, the “Delete entries” permission is not a prerequisite for the “Delete other authors’ entries”.

<img width="379" alt="User permissions for a section, showing that it’s possible to grant someone permission to delete other authors’ entries without having permission to delete entries in a general sense" src="https://user-images.githubusercontent.com/47792/101968509-69db0900-3bd4-11eb-9f86-0908709a27cb.png">

Perhaps for Craft 4 we could come up with some way of establishing cross-hierarchical permission prerequisites, so if “Delete entries” isn’t checked, then “Delete other authors’ entries” is greyed out.

**Comment by carlcs** [comment]
So you’re saying „Delete entries“ basically means „Delete his own entries“? Could you please name it like this then?

**Comment by carlcs** [comment]
Does it work the same for „Publish live changes“? If this is unchecked and „Publish live changes for other authors entries“ is checked, the user can publish entries just not their own?

**Comment by carlcs** [comment]
If you don’t want to rename these permission settings, can you please provide this information (setting can be overruled) in an info tooltip?

**Comment by brandonkelly** [comment]
> Does it work the same for „Publish live changes“? If this is unchecked and „Publish live changes for other authors entries“ is checked, the user can publish entries just not their own?

Sorry, good point, it was not consistent with Edit or Publish permissions. So I do agree this is a bug, and have fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with this fix.
