### ISSUE TITLE
setPassword action for a pending user returns success even if activation is cancelled

### ISSUE THREAD

**Issue by OscarBarrett** [craftcms/cms#7239]
### Description

When performing the `setPassword` action for a pending user, it will activate them. However it [ignores the return value of the call to `activateUser`](https://github.com/craftcms/cms/blob/develop/src/controllers/UsersController.php#L491) and returns success instead.
Ideally we should get a failure response so it can be handled.

### Steps to reproduce

1. Add an event handler for `EVENT_BEFORE_ACTIVATE_USER`:
```php
Event::on(Users::class, Users::EVENT_BEFORE_ACTIVATE_USER, static function (UserEvent $event) {
    $event->isValid = false;
}
```
2. Hit `actions/users/set-password` for a pending user. Response is `{ success: true }` with a 200 code but the user is not activated.

### Additional info

- Craft version: 3.5.16
- PHP version: 7.4
- Database driver & version: MySQL
- Plugins & versions: N/A

**Comment by brandonkelly** [comment]
Whoops, thanks for pointing that out! Fixed for the next release – Craft will no longer redirect the user as if they’d been activated, for normal web requests.

For JSON requests, I think `{"success": true}` + 200 status is still appropriate, as the password setting was successful if it got to that point. So instead of changing that, I’ve added a new `status` key to the response, which will be set to `active` or `pending`, depending on whether activation was successful.

**Comment by brandonkelly** [comment]
Craft 3.5.17 is out now with that change.
