### ISSUE TITLE
CP Search Results Not Returning Expected Results

### ISSUE THREAD

**Issue by spencech** [craftcms/cms#7248]
### Description
When searching on a newly created entry, titled "Use a Word You Know", searching for "Use a Word You Kno" includes this entry in the search results. Oddly, the search phrase "Use a Word You Know" excludes the entry.  These entries were imported via FeedMe from a google sheet (300 entries). I've noticed similar issues on other entries.

### Steps to reproduce

1. See above, not sure if fresh entries will be reproducible
2.

### Additional info

- Craft version: Craft Pro 3.5.16
- PHP version: 7.4
- Database driver & version: MySQL 8.0.22
- Plugins & versions: Feed Me 4.3.1, Redactor 2.8.5, Redactor Custom Styles 3.04, AWS S3 1.2.11

<img width="332" alt="Screen Shot 2020-12-10 at 9 02 32 PM" src="https://user-images.githubusercontent.com/673194/101853966-8b81b500-3b2e-11eb-8aae-56dce58574b4.png">
<img width="603" alt="Screen Shot 2020-12-10 at 9 02 42 PM" src="https://user-images.githubusercontent.com/673194/101853968-8b81b500-3b2e-11eb-8a0d-d1505f4772f6.png">

**Comment by swordinthestone** [comment]
I experienced similar situation.
After some debugging, I found that the SQL executed is completed different for searching.
I hidden remove the elementIDs for a easier reading. 

When search with "wel":
`SELECT * FROM `craft_searchindex` WHERE (`keywords` LIKE '% wel%')` 

When search with "well":
`SELECT * FROM `craft_searchindex` WHERE MATCH(`keywords`) AGAINST('+well*' IN BOOLEAN MODE)`

<img width="266" alt="01" src="https://user-images.githubusercontent.com/50087720/101856509-90d81180-3bb9-11eb-9f7d-c8ba93504e6f.png">
<img width="288" alt="02" src="https://user-images.githubusercontent.com/50087720/101856514-933a6b80-3bb9-11eb-8d5f-d62385461a9a.png">

**Comment by angrybrad** [comment]
@spencech in your "use a word you know" example, "use", "you", and "know" are all on MySQL's MyISAM full-text default stop-word list: https://dev.mysql.com/doc/refman/8.0/en/fulltext-stopwords.html#fulltext-stopwords-stopwords-for-myisam-search-indexes

MySQL will effectively ignore those words.  You can edit the stopword list on your server to remove them or if you're on MySQL 5.6+, swap that table to InnoDB, which has a much smaller stopword list: https://dev.mysql.com/doc/refman/8.0/en/fulltext-stopwords.html#fulltext-stopwords-stopwords-for-innodb-search-indexes

@swordinthestone in your "well" example, you're running into the default MySQL full-text min word length, which is 4 by default: https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_ft_min_word_len

Craft will attempt to work around that limitation by falling back to a "like" based SQL search instead of a full-text search with words < that limit. Looks like you might have found a bug when the word is _exactly_ that limit, though. Will do some testing.

**Comment by spencech** [comment]
Thanks @angrybrad I had been looking at the innodb list, not the MyISAM... so that definitely makes sense. Thanks so much for the insight.

**Comment by angrybrad** [comment]
Gah, sorry @swordinthestone... "well" is in the MyISAM stop word list, too - must have overlooked it before: https://dev.mysql.com/doc/refman/8.0/en/fulltext-stopwords.html#fulltext-stopwords-stopwords-for-myisam-search-indexes

**Comment by swordinthestone** [comment]
@angrybrad Thank you for your reply. I have tested other queries for validation. I found there may be a bug to match keywords.
As the MySQL document said, MATCH ... AGAINST work for stop word at the beginning or end of search query. I think that may the cause when I search with keywords that are in the stop word list, it search result will only return with result started with stop word.
https://dev.mysql.com/doc/refman/8.0/en/fulltext-boolean.html

Example in my case.

Search: self raising flour
Return nothing
![image](https://user-images.githubusercontent.com/50087720/102418693-5c010a00-4052-11eb-8ff0-bc0d76d2f3dd.png)

Search: *self raising flour
Return result we excepted, because the product title is not started with "Self"
![image](https://user-images.githubusercontent.com/50087720/102418684-57d4ec80-4052-11eb-8e54-4d38b516c430.png)

Hope it can help to improve. For my project, I can apply query changes for searching, but I think it would be a better solution to handle by Craft.
