### ISSUE TITLE
[Feature Request] GraphQL should be a plugin (or at least not forced on all Craft CMS installations)

### ISSUE THREAD

**Issue by antom** [craftcms/cms#7253]
I've just updated to the latest version of Craft (3.5.16 from 13.15.1) & noticed the GraphQL option forcibly added to the sidebar for Admin users & the related DB tables added to the site.

Right now it's not in use on the site I'm working on & to be honest, I cannot actually see it being used in the foreseeable future. After disabling it with the `enableGql` config option, it still leaves artefacts such as the `gqlschemas` & `gqltokens` tables that are just clutter in sites not utilising them.

Ultimately, I don't get why this has been deemed to be core functionality that needs to be on by default? Something like Redactor, for example, is installed on a large number of Craft CMS installs but is properly separated out into a plugin instead of being a core field.

I get why it may be useful to have GraphQL functionality available in Craft CMS, but it really should have been wrapped up into an plugin to allow for opt-in use rather than baking it in & forcing it across the board.

Failing moving the functionality to a plugin, can you at least add the option for removing the unused tables & any other artefacts if `enableGql` is set to `false`? Or have `enableGql` defaulting to `false` in the first place?

**Comment by brandonkelly** [comment]
> Ultimately, I don't get why this has been deemed to be core functionality that needs to be on by default?

The GraphQL API requires coordination with plugins, which is much harder to pull off if it’s implemented as a plugin as opposed to core functionality. So that’s why it’s in the core.

> Something like Redactor, for example, is installed on a large number of Craft CMS installs but is properly separated out into a plugin instead of being a core field.

Redactor actually used to be in core, but we removed it for Craft 3 after Imperavi simultaneously released Redactor II (with breaking changes) and EOL’d Redactor “I” – forcing us to choose between including a breaking update to Rich Text fields in Craft ~2.5, or continuing to ship an EOL’d editor. Now that it’s a plugin, we can roll with those situations a lot easier (release breaking Redactor plugin updates independently of major Craft updates). The same situation doesn’t really apply to GraphQL, since it’s not susceptible to browser rendering engine changes over time like a WYSIWYG editor.

> Failing moving the functionality to a plugin, can you at least add the option for removing the unused tables & any other artefacts if `enableGql` is set to false?

There’s no obvious way we could pull that off, and I’m not sure what the gain would be. Your DB will not grow in size or become less performant just because there’s a couple unused tables in there.

> Or have `enableGql` defaulting to `false` in the first place?

That would be a minor breaking change, in that every Craft site that is currently using GraphQL and hasn’t explicitly set `enableGql` to `true` in `config/general.php` (why would they?) would unexpectedly lose their GraphQL API after updating Craft.
