### ISSUE TITLE
PHP 7.3 required in laminas/laminas-feed >= 2.13.0

### ISSUE THREAD

**Issue by markdrzy** [craftcms/cms#7310]
Craft documentation currently lists PHP 7.0+ as the minimum requirement.

`craftcms/cms/composer.json` requires `"laminas/laminas-feed": "^2.12.0"`. If I understand versioning in Composer well enough (big if), `^2.12.0` is satisfiable by any version `>= 2.12.0` and `< 3`. The most recent version of `laminas/laminas-feed` is `2.13.1`, which satisfies the `^2.12.0` requirement.

Starting with version [2.13.0](https://github.com/laminas/laminas-feed/blob/2.13.0/composer.json#L24), `laminas/laminas-feed` has a hard requirement of PHP 7.3:

```
    "require": {
        "php": "^7.3 || ~8.0.0",
        ...
```

This stands at odds with Craft's "minimum requirement" for PHP 7.0+.

**Comment by brandonkelly** [comment]
Composer will get the latest version of each dependency _that is compatible with the other dependencies as well as the system requirements_. In this case, that means that if you have PHP 7.0 - 7.2*, you are going to get `laminas/laminas-feed` 2.12.x; if you have 7.3* or later, you will get the latest 2.13.x.

(*Note that if your `composer.json` has `config.platform.php` set, it will reference _that_ version when determining which packages to install, rather than the actual installed PHP version.)
