### ISSUE TITLE
Arrays packed by utils/repair/project-config unpacked by CP edits

### ISSUE THREAD

**Issue by gbowne-quickbase** [craftcms/cms#7395]
### Description
I ran the utils/repair/project-config to resolve an issue, and all the double packed arrays were cleaned up. Great! Then I touched a field in the settings, and they unpacked again. And not just the sections/entryTypes/fields I edited. A lot of files changed and unpacked again. It seems to happen with `fruitstudios/linkit`, `supertable` fields and dropdown fields too. A bunch of screenshots from git diffs attached. Also, there's a lot of toggling between `true`/`1` and `false`/`0` 

### Steps to reproduce

1. Run `./craft utils/repair/project-config`
2. Commit your changed project config files
3. Edit a matrix field or field
4. See all the unpacked config in your files again

### Additional info
![image](https://user-images.githubusercontent.com/39066452/104824021-85ad7c80-581c-11eb-9915-45c258a6ce7e.png)
![image](https://user-images.githubusercontent.com/39066452/104824044-ac6bb300-581c-11eb-9905-c9cd0e590d3c.png)
![image](https://user-images.githubusercontent.com/39066452/104824055-c73e2780-581c-11eb-9b51-a29ad1406391.png)
![image](https://user-images.githubusercontent.com/39066452/104824070-df15ab80-581c-11eb-8462-ef624e9ee361.png)
![image](https://user-images.githubusercontent.com/39066452/104824475-f7d39080-581f-11eb-9b83-cf53ba864628.png)

- Craft version: 3.5.17.1
- PHP version: 7.3.20
- Database driver & version: MySQL 5.7.29
- Plugins & versions:

1. Amazon S3	1.2.11
2. Canary	3.0.4
3. Cloudflare	0.6.0
4. Cookie Consent Banner	1.2.7
5. Delete Entry Versions	2.0.0
6. Element API	2.6.0
7. Feed Me	4.3.4
8. Field Manager	2.2.1
9. GeoMate	v1.2.1
10. Icon Picker	1.1.10
11. ImageOptimize	1.6.21
12. Linkit	1.1.12.1
13. Matrix Finder	1.0.2
14. quickbase-process	1.0.9
15. Redactor	2.8.5
16. Redactor Anchors	1.1.0
17. Retour	3.1.45
18. SEOmatic	3.3.28
19. Similar	1.0.6
20. Simple Sharing	1.0.8
21. Smith	1.1.10
22. Sprig	1.3.0
23. Super Table	2.6.5
24. Tags	1.0.7
25. Twigpack	1.2.7
26. Workflow	1.5.7
27. XML Sitemap	1.3.1

**Comment by brandonkelly** [comment]
That’s all working as expected. If you run `utils/repair/project-config`, it should leave those “packed” arrays in-tact this time around, since they aren’t _double_-packed.

Everything in the project config gets sorted alphabetically by key, but there are areas (like field type settings) where the order actually mattered. So we use that array-packing logic to lock in the order.

> A bunch of screenshots from git diffs attached. Also, there's a lot of toggling between `true`/`1` and `false`/`0`

Yeah that’s awkward but it’s a result o how MySQL stores “boolean” values. Craft 4 is going to require PHP 7.4, which adds typed property support, so at that point even if a boolean value comes back as `'1` from MySQL, it will automatically be converted to `true` when set on an object, at which point we’ll stop seeing all this type juggling in the project config.
