### ISSUE TITLE
Automatically add proper "COLLATE" option to "orderBy" element query method

### ISSUE THREAD

**Issue by piotrpog** [craftcms/cms#7403]
This is related to this https://github.com/craftcms/cms/issues/7392 issue which deals with sorting element query results with different languages. This will sort results using german special characters and their specific position in alphabet:

```
.orderBy('(title COLLATE utf8_german2_ci)')
```

I belive it would be useful if we had option to automatically append such option to sorting, depending on current language. Or maybe setting such option globally using config?

**Comment by brandonkelly** [comment]
If you want to use a particular collation by default, you should be setting it on the database table directly, rather than complicating the queries every time. Plus it [looks like](https://stackoverflow.com/a/637235) adding `COLLATE` to the query will prevent MySQL from being able to use existing indexes.

**Comment by piotrpog** [comment]
@brandonkelly 
"Plus it looks like adding COLLATE to the query will prevent MySQL from being able to use existing indexes."
Can you elabolare what would be practical effects of that?

**Comment by wsydney76** [comment]
>  adding COLLATE to the query will prevent MySQL from being able to use existing indexes

It takes an additional sort step, so it is potentially slower. But unless you have many thousands of records, it should not make a significant difference, because a typical entry query reads the relevant records anyways, and probably the sort can be done in memory without using temporary disc access.

>  automatically append such option to sorting, depending on current language.

As always, things aren't that easy in German... 

In general we use `uft8_unicode_ci` (dictionary order, ä= a, ß = ss) except for names, where it should be `uft8_german2_ci` (phone book order, ä = ae, ß =ss). So it's not depending on the language alone.

But maybe the db collation for a field can be specified when creating a plain text field?

**Comment by angrybrad** [comment]
@piotrpog @wsydney76 

> Can you elabolare what would be practical effects of that?
> It takes an additional sort step, so it is potentially slower. But unless you have many thousands of records,

Indexes are collation specific, so the default indexes that Craft creates to make sure queries run efficiently for databases of all sizes are created using whatever the default collation for the database was when Craft was installed.

In our testing using the main element query, for example, mixing collations caused those indexes to not be selected and performance to greatly suffer, for even moderately sized databases.

> But maybe the db collation for a field can be specified when creating a plain text field?

You'd run into the same issue, I think.

My guess is the best way to solve this would be to at the server level and add extra indexes in the collation you're looking for to all of the indexes that are involved in the specific element queries you're trying to execute.

**Comment by wsydney76** [comment]
@angrybrad Thanks, (no answer required, we do not experience significant performace hits in the cases where we use this)

> add extra indexes in the collation you're looking

Oh, that idea did not come to my mind, however it looks like adding an index that uses a different collation is only possible in PostgreSQL and not in MySQL? (at least without the use of secondary indexes on a generated pseudo-column) https://www.w3resource.com/sql/creating-index/sql-creating-index.php
