### ISSUE TITLE
Categories section Accessibility

### ISSUE THREAD

**Issue by ajanec01** [craftcms/cms#7447]
### Overview of accessibility issues found on the Categories page

-Status update for enabling and disabling categories not picked up by screen reader software
![status-update](https://user-images.githubusercontent.com/47136246/105920097-a94ba080-602e-11eb-8294-4fed5ab59c5e.png)
-Status update for not being able to save a category not picked up by screen reader software
![status-update2](https://user-images.githubusercontent.com/47136246/105920180-d1d39a80-602e-11eb-8e46-b3925b71c584.png)
- Dialog for choosing a parent category would benefit from `role="dialog"` and an accessible name
![parent-dialog](https://user-images.githubusercontent.com/47136246/105920451-51fa0000-602f-11eb-9483-8343dc18b9d1.png)
- It's not possible to select a parent category using the keyboard only
- The New Category button in the parent category dialog is not keyboard accessible
![new-category](https://user-images.githubusercontent.com/47136246/105920427-4575a780-602f-11eb-9081-8771bb2eaae9.png)

### Additional info

- Craft version: 3.5.18

**Comment by gcamacho079** [comment]
This issue is being closed due to its broad scope. However, several issues here have already been addressed. For example, status update messages for enable, disable, and error saving are now accessible to screen readers

Accessibility issues pertaining to modals will be addressed in upcoming updates to the Garnish library, and category selection using the keyboard is being looked into.
