### ISSUE TITLE
Craft 3.6 updates not reading credentials from auth.json

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#7466]
### Description

As of Craft 3.6, updates happen using Craft's version of composer, which appears to _not_ be reading credentials from `auth.json`.

According to [Authentication for privately hosted packages and repositories](https://getcomposer.org/doc/articles/authentication-for-private-packages.md):

> Credentials can be stored on 3 different places; in an auth.json for the project, a global auth.json or in the composer.json itself.

However, in my tests, _only_ credentials stored in `composer.json` are being loaded.

### Steps to reproduce

1. Require a private repository in `composer.json`.
2. Run `composer config --auth http-basic.example.org username password` to create a local copy of `auth.json` (or global with the `--global` flag).
3. Run `./craft update all`.
4. See the error `Performing update with Composer ... error: The 'https://example.org/packages.json' URL could not be accessed: HTTP/2 403`.

### Additional info

- Craft version: 3.6.1
- Composer version: 2.0.9
- PHP version: 7.4

**Comment by brandonkelly** [comment]
I’m almost certain this couldn’t have worked before 3.6 either. Just looking at Craft 3.5 / Composer 1.x code, Composer will look for `auth.json` in the same directory as `composer.json` here:

https://github.com/composer/composer/blob/32966a3b1d48bc01472a8321fd6472b44fad033a/src/Composer/Factory.php#L305-L309

But `$composerFile` will only be set if the path to `composer.json` was passed to `Factory::createComposer()`:

https://github.com/composer/composer/blob/32966a3b1d48bc01472a8321fd6472b44fad033a/src/Composer/Factory.php#L275-L276

And Craft has always passed a config array instead of a `composer.json` path (because we need to make a couple adjustments to the config):

https://github.com/craftcms/cms/blob/2c6ef1afa23aefaefc95b19ed823769cc2a8f8c5/src/services/Composer.php#L520-L521

**Comment by bencroker** [comment]
After doing some digging, you're right that `auth.json` in the project was not being respected previously.

However, the global `auth.json` _was_ being respected pre Craft 3.6. Here are the lines that were removed that changed this behaviour:

```php
        $alt = Platform::isWindows() ? 'APPDATA' : 'HOME';
        if (App::env($alt) !== false) {
            return;
        }
```

Diff: https://github.com/craftcms/cms/commit/bc9a880828a43a5f2b20adf82f7d8084ed848e91#diff-c676cf5501a712a70267a87251ccff31a9281b403fbf7e94abcdef306bcf93ccL352-L355

In Craft 3.6, instead of the global `auth.json` being looked for in `/Users/me`, it is being looked for in `/Users/me/Sites/craft3/storage/runtime/composer`.

Here is where composer looks for the `HOME` environment variable:
https://github.com/composer/composer/blob/03dcb6df3dd643a6851d83afde0660584cf8cb0f/src/Composer/Factory.php#L673-L681

**Comment by brandonkelly** [comment]
Ah-ha. Well, per that diff we are still ensuring that a `COMPOSER_HOME` environment variable exists

**Comment by brandonkelly** [comment]
Ah-ha! Should be fixed now for the next release.

**Comment by bencroker** [comment]
That works, thanks Brandon!

**Comment by brandonkelly** [comment]
Craft 3.6.4 is out now with that fix ✨
