### ISSUE TITLE
Bug when duplicating draft entries

### ISSUE THREAD

**Issue by robinbraibant** [craftcms/cms#7508]
### Description
A new wonderful feature in the new release is that new entries are first saved as a draft. I think I found an issue with duplicating the draft entries.
I have created an entry and saved it as a draft. When I duplicate this entry and change the content of the fields of this new (draft) entry something goes wrong when saving this new entry. The entry where this duplicated entry is based on gets changed instead of the duplicated entry.

Secondly, when you publish the initial entry, all the copies are being removed.

### Steps to reproduce

1. Create a new entry in a channel
2. Enter the necessary content and click 'save draft'
3. Select this entry by enabling the checkbox
4. Dupicate this entry
5. Open this new entry
6. Change the content
7. Click 'save draft'
--> The first entry has been changed
1b. Open the initial entry
2b. Click 'Publish draft'
3b. In the overview of the channel all the duplicated entries are deleted

### Additional info

- Craft version: 3.6.3
- PHP version: 7.4.14
- Database driver & version: mysql
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.4 is out now with that fix ✨

Note that the fix is not retroactive, and your existing drafts that were in this situation are in a bit of a fickle state. After updating to 3.6.4, you should go back and re-duplicate them, and delete the original.

So for eaxamlpe if you currently have:

- My Entry [DRAFT]
- My Entry (copy) [DRAFT]

Duplicate one of those (shouldn’t really matter which if their content is identical), and then delete both of those.
