### ISSUE TITLE
invalidUserTokenPath instead of activateAccountFailurePath

### ISSUE THREAD

**Issue by shornuk** [craftcms/cms#7520]
### Description
I'm updating some areas of an older site. In the config I have a setting of `activateAccountFailurePath` which I'm guessing is now depreciated in favour of `invalidUserTokenPath`.

However, the docs seem to mention that you can get to the `invalidUserTokenPath ` from a variety of ways. Is there a way to specifically determine that it was an account activation failure? Ideally I want to show a specific message if that is the case (like I was doing on `activateAccountFailurePath `)

### Additional info

- Craft version: 3.6.4.1
- PHP version: 7.3

**Comment by brandonkelly** [comment]
This is a little tricky because there is no explicit “activation” controller action. Just `users/set-password` and `users/verify-email` – both of which will end up activating the user if they aren’t already activated.

`actionSetPassword()`:

https://github.com/craftcms/cms/blob/8b0dee8ebc864059a98eab9fb6721ccda1237979/src/controllers/UsersController.php#L579-L586

`actionVerifyEmail()`:

https://github.com/craftcms/cms/blob/8b0dee8ebc864059a98eab9fb6721ccda1237979/src/controllers/UsersController.php#L638-L641

That said, I’ve just made it possible for you to achieve your desired output with a new `EVENT_INVALID_USER_TOKEN` event, which will get triggered by UsersController whenever an invalid user token is passed to it, before it decides how to handle it.

That event is given the user in question (if a valid user UID was passed), so you can add an event handler that adds its own logic to detect if this would have been an activation request (had the token been valid), and take over the response if so.

```php
use craft\controllers\UsersController;
use craft\helpers\UrlHelper;
use yii\base\Event;

Event::on(
    UsersController::class,
    UsersController::EVENT_INVALID_USER_TOKEN,
    function (\craft\events\InvalidUserTokenEvent $event) {
        // Would this have been a (front end) activation request?
        if ($event->user && $event->user->pending && Craft::$app->getRequest()->getIsSiteRequest()) {
            Craft::$app->getResponse()->redirect(UrlHelper::siteUrl('my-activation-failure-path'));
            Craft::$app->end();
        }
    }
);
```

**Comment by shornuk** [comment]
👍 That's great, thanks @brandonkelly - looks like this will cover it and appreciate that being added to make it possible. Just so I'm understanding it, are these the only two ways that you'd end up at the `invalidUserTokenPath ` then?

- A bad password reset
- Verifying email (either through updating an email for an already activated user, or though the activation link for a pending user)

Are there any other ways to get to that path?

**Comment by brandonkelly** [comment]
Mostly correct. The `set-password` action could be invoked for a brand new user that hasn’t set their password yet (depending on whether the registration screen expects them to set one) – so not just because they forgot it.

**Comment by brandonkelly** [comment]
Craft 3.6.5 is out now with that new event ✨
