### ISSUE TITLE
Project config: fields deleted, content lost after changing field groups

### ISSUE THREAD

**Issue by degraaf** [craftcms/cms#7526]
### Description

Deployed project config yaml changes and lost fields/content. 

### Steps to reproduce

1. Moved 2 fields into new field group (a drop down, and an asset field)
2. Deleted old field group
3. Restored yaml changes in second environment (using Apply Changes option)
4. Fields were deleted, content lost

Additional:
1. Rolled back
2. Reverted (via Git) the Yaml change that removes the field group
3. Left the change that moved the fields into the other field group
4. Applied yaml changes
5. Fields moved into other group, not deleted, no content deleted
8. Old empty field group remains, but can now be removed in future deployment

It appears the delete of the field group is occurring first, causing the fields to be removed before they get moved into the other group.

### Additional info

- Craft version: 3.6.3, upgraded and found same problem in 3.6.4.1
- PHP version: 7.4
- Database driver & version: MySQL (locally), Aurora (QA site)
- Plugins & versions:

**Comment by brandonkelly** [comment]
Thanks for reporting this. It’s now fixed for the next release.

What happened was, the `fields` table rows were cascade-deleted when the field group was deleted. Then they should have been re-added when Craft got around to applying their new field groups – but by then they were treated as _new_ fields rather than existing fields. The fix was to add soft-delete support to field groups, so when they are “deleted”, their rows will stick around for a while still, avoiding the cascade delete issue.

The good news is, that cascade-deletion would _only_ affect the fields’ rows in the `fields` table. It would not have deleted the fields’ actual content (their columns in the `content` table). So when the “new” fields were added, Craft would have seen that there were existing database columns named after the fields, and it would have renamed the existing columns to `*_old`, to preserve their content.

So your content is still in there – just renamed. If you need to salvage it, you should be able to go into your database’s `content` table, identify the duplicate `content` table columns, delete the new ones (or rename to `*_tmp`), and then rename the old ones by dropping the `_old` suffix from their names.

If you have any Matrix/Neo/Super Table fields, the process may be a bit more complicated. Either way, feel free to send a database backup over to support@craftcms.com and we can help put it back together for you.

Or, if you have a database backup from before applying your project config changes, maybe it would be easier to just restore that.

**Comment by brandonkelly** [comment]
Craft 3.6.5 is out now with that fix.
