### ISSUE TITLE
Cannot set empty color field to black

### ISSUE THREAD

**Issue by realjoshharrison** [craftcms/cms#7529]
### Description
An empty colour field can't be set to `#000000` via the colour chooser popup. 

### Steps to reproduce

1. On an empty colour field, click the circular swatch to open the colour chooser. A javascript error is thrown tracing back to ColorInput.js:40 but I'm not sure if it's relevant to the issue:

```
Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at U (jquery.js? [sm]:4216)
    at V.get (jquery.js? [sm]:4297)
    at Object.trigger (jquery.js? [sm]:8711)
    at HTMLInputElement.<anonymous> (jquery.js? [sm]:8793)
    at Function.each (jquery.js? [sm]:381)
    at b.fn.init.each (jquery.js? [sm]:203)
    at b.fn.init.trigger (jquery.js? [sm]:8792)
    at s.constructor.<anonymous> (ColorInput.js:40)
```

2. The colour picker appears with R0 G0 B0 selected by default. You can drag the dot around to another pure black, or manually re-enter R0 G0 B0 to no effect. When you press enter or click off, it doesn't detect any changes and leaves the colour field blank. Expected behaviour is to insert `#000000`.

Screenshots:

![Screenshot 2021-02-09 at 16 48 32](https://user-images.githubusercontent.com/3930056/107397567-ae145800-6af6-11eb-8f4f-f256d7da8052.png) 

⬇️

Press enter or click off colour chooser 

⬇️

![Screenshot 2021-02-09 at 16 50 53](https://user-images.githubusercontent.com/3930056/107397934-09464a80-6af7-11eb-8d46-80bd6e0f9103.png)

### Additional info

- Craft version: 3.6.4.1
- PHP version: 7.4.2
- Database driver & version: MySQL 5.7.26
- Plugins & versions: None

... and thanks for making a CMS that is a genuine delight to work with!

**Comment by brandonkelly** [comment]
The reason that’s happening is because color inputs are set to `#000000` by default, if they don’t have a `value` attribute. So the input isn’t sending a `change` event when you close it with `#000000` “still” selected.

I’ve worked around this for the next release by updating the text input on the color input’s `input` event rather than `change`, which will get fired even when the color picker is still visible. You still have to get it to register that you want `#000000` by temporarily changing the color and then changing it back, but it’s a bit easier than selecting a different color, closing the color picker, and then (re-)selecting black.

![A screen recording of the color picker, showing that the text input is selected in real time while the color picker is still open](https://user-images.githubusercontent.com/47792/107428864-11db5880-6ad8-11eb-99e6-cd31169fa9e4.gif)

That JS error was unrelated, but it’s fixed as well now.

**Comment by brandonkelly** [comment]
Craft 3.6.5 is out now with that change ✨

**Comment by realjoshharrison** [comment]
Speedy. That works great in my opinion. Thanks 👌
