### ISSUE TITLE
CP search with "MYSQL stop word" not returning results unless quoted

### ISSUE THREAD

**Issue by spencech** [craftcms/cms#7538]
### Description
We're finding that some text searches that include MySQL ISAM stop words are returning empty results sets; on the other hand those same searches when enclosed in quotations, or searches that explicitly remove the stop word, are returning results as expected. Not sure if this is a MySQL thing or something that could be tweaked in Craft. 

### Steps to reproduce

1. Enter a search term that begins with a MySQL stop word, in our case _different perspectives_, into the CP entries search field
2. Note that no results are returned, this is not expected (we see the same results via the api)
3. Enter the same term in quotations, in our case "different perspectives"
4. Note that results are returned, in our case 6 results are presented and expected
5. Remove the stop word and quotations
6. Note that results are returned, in our case _perspectives_, 10 results are presented and expected

### Additional info
I've noticed and previously reported some issues with Stop words in the search, and I think at least one of them was fixed. Interestingly, simply placing a single quotation or asterisk (but not any character) in front of our search term also yields expected results.

Update: in coding a work around for this (prefixing matched stop words with an asterisk ahead of submission), it occurred to me that "perspectives" is also prefixed by a stop word (i.e., "per")... not sure if that's relevant  here or a coincidence.

- Craft version: Craft Pro 3.6.4.1
- PHP version: 7.4.3
- Database driver & version: MySQL 8.0.23
- Plugins & versions: Amazon S3 (1.2.11), Redactor (2.8.5), Feed Me (4.3.5.1), Redactor Custom Styles (3.0.4)

**Comment by brandonkelly** [comment]
This is expected. When you wrap the term in quotes, it turns into an exact phrase match, which doesn’t use a fulltext search, so stopwords aren’t a factor.

If you’re running MySQL 5.6+, you can switch your `searchindex` table’s engine to InnoDB instead of MyISAM, which has a significantly smaller stopwords list.

**Comment by spencech** [comment]
Ok thanks for the quick feedback @brandonkelly , just want to confirm that you're saying the following scenario is expected: in our cms where the term _different perspectives_ is used across several indexed entry fields, we should see zero results appear unless the phrase is quoted in the search field. Is that right?

**Comment by brandonkelly** [comment]
Fulltext searching is a bit of a black box, so I’m not sure why “perspectives” is being ignored as well. But in general InnoDB is a more modern DB engine than MyISAM, and I’m guessing that switching to it will give you closer to desired behavior (in large part because of the significantly smaller stopwords list).

**Comment by spencech** [comment]
Got it thanks so much!
