### ISSUE TITLE
Enable the DELETE option for entries in "all entries" index.

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#7545]
Hi! Is there a reason that you can't delete entries in the "all entries" index? 

It sure would be convenient with all the authors currently trying to clean-up their drafts (and maybe getting confused by the lack of the delete option in this view)!

**Comment by brandonkelly** [comment]
It hasn’t been possible because there could be Single entries, or entries that the user doesn’t have permission to delete, in there. However nowadays that Delete action is a bit smarter, and will only enable itself for entries that say they are actually deletable by the current user (which will always be `false` for singles). So there’s no good reason to keep it out anymore. Just added it for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.6 is out with this change ✨
