### ISSUE TITLE
Maybe also display drafts of unpublished entries in the "My Drafts" widget?

### ISSUE THREAD

**Issue by thupsi** [craftcms/cms#7546]
I'm not sure if this is a bug. Is it by design that drafts of unpublished entries do not appear in the widget?

**Comment by brandonkelly** [comment]
I’m not exactly sure what you’re referring to. Unpublished drafts can’t have their own sub-drafts – only _published_ entries can have subdrafts.

Both unpublished drafts _and_ drafts of published entries will show up in the My Drafts widget, though. Perhaps you’re not seeing one because it wasn’t actually created by your user account?

**Comment by thupsi** [comment]
Sorry, my terminology was incorrect. I meant  unpublished drafts. So, I tested it again, and having deleted all other drafts, saw the widget's empty state and solved the mystery: "You don’t have any **active** drafts." Sure enough, I activated the draft and it appeared in the widget. Ok.. but, does it make sense to make that distinction in the first place? I'm sure that the activation toggle is meant for published entries only, right? You even ommit the "status" indicator for drafts in the index.

**Comment by thupsi** [comment]
Of course I might be wrong about the last part. Just asking 🙂

**Comment by brandonkelly** [comment]
Oh I see… it’s not showing _disabled_ drafts. That wasn’t intended.

**Comment by thupsi** [comment]
Yep! I thought initialy that it didn't display all unpublished drafts, but it actually isn't showing disabled drafts...

**Comment by brandonkelly** [comment]
Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.6 is out now with the that bugfix.
