### ISSUE TITLE
Can delete singles when in ENVIRONMENT="production"

### ISSUE THREAD

**Issue by OwenMelbz** [craftcms/cms#7547]
### Description
We had a big client confusion today, when they accidently deleted a single, even though production mode was on.

Although the Settings area is closed, and although you cannot from the entries page select a single and delete it.

When you're editing the single the dropdown still allows you to delete

This then obviously can break the site.

### Steps to reproduce

1. Edit a single when in production mode
2. Click the "Save" dropdown and pick "Delete"

![image](https://user-images.githubusercontent.com/1094740/107622875-6a356600-6c50-11eb-9a64-0c1b67d5db7b.png)

### Additional info

- Craft version: Craft Pro 3.6.4.1
- PHP version: 7.4
- Database driver & version: Mysql 8
- Plugins & versions: N/A ?

**Comment by brandonkelly** [comment]
Yikes, thanks for reporting that. Just fixed for the next release. Looks like this has been looming since 3.5.17 (b77607a769e5f72601901dbb2565cb6c66ca8656).

It should have only been possible in two cases, though:

- The author is an admin
- The section used to be a Channel/Structure, at which point the author (or one of their user groups) had been granted permission to delete entries within the section, and the author/group’s permissions haven’t been resaved since the time the section was converted to a Single.

Anyway, you should be able to bring the entry back by doing the following:

1. Go to the Project Config utility
2. Click the “Rebuild” button (this is just a precaution)
3. Once that’s done, click the “Reapply everything” button

“Reapply everything” (same as the `project-config/apply --force` command) will end up re-saving the section, and ensuring that its single entry exists.

**Comment by brandonkelly** [comment]
Craft 3.6.6 is out now with that bugfix.
