### ISSUE TITLE
date error in plugin store changelog

### ISSUE THREAD

**Issue by successgo** [craftcms/cms#7612]
### Description

There is date error in plugin store changelog.

### Steps to reproduce

1. Install craftcms locally
2. Go to plugin store and search "prefetch", then go to the plugin detail page, and slide down to changelog part
3. Go to the above plugin github repo repleases page https://github.com/ryssbowh/craft-prefetch/releases

### Additional info

- Craft version: Craft Solo 3.6.7
- PHP version: v7.4.15
- Database driver & version: mysql v5.7
- Plugins & versions: none

**Comment by brandonkelly** [comment]
The release dates are meant to match the ones in the plugin’s changelog (e.g. https://github.com/ryssbowh/craft-prefetch/blob/master/CHANGELOG.md). Turns out that could be off by a day if your timezone was < UTC (e.g. PST = UTC-8).

That’s now fixed for plugin changelogs, both on plugins.craftcms.com (e.g. https://plugins.craftcms.com/prefetch) as well as the in-app Plugin Store.

The Updates utility also had a similar bug, which has been fixed for the next release.

**Comment by successgo** [comment]
Great @brandonkelly , thank you !

**Comment by successgo** [comment]
Oh, you give me the answer that date error is in the changelog, and which I means the error is that the *year* should be 2021 instead of 2020 in recent releases.

The prefetch craft plugin is the one, and the craft commerce plugin too.

**Comment by successgo** [comment]
So this should be called a typo other than a bug, right?

**Comment by brandonkelly** [comment]
Ahh, I see what you mean. These are just due to typos in the plugins’ changelogs. I’ve just fixed it for Commerce, and submitted a PR to Prefetch (https://github.com/ryssbowh/craft-prefetch/pull/3).

**Comment by successgo** [comment]
Well done, and thanks for your attention!
