### ISSUE TITLE
Remembered User Session Duration Not Respected

### ISSUE THREAD

**Issue by bencroker** [craftcms/cms#7619]
### Description

I've been struggling to debug this behaviour, which I am seeing on multiple sites, but it's hard to imagine that nobody else has brought this up. Users are being logged out of the CP when `userSessionDuration` expires, even if they check the `Keep me logged in` option.

My guess is that this is somehow to do with `authTimeout` being set to the value of `userSessionDuration`, very possibly related to https://github.com/craftcms/cms/issues/3951

### Steps to reproduce

1. Set the general config settings as follows:
```
'rememberedUserSessionDuration' => 180,
'userSessionDuration' => 30,
```
2. Log in to the CP, checking `Keep me logged in`.
3. Close the browser tab and reopen it after 30 seconds have passed.
4. You are now logged out.

### Additional info

- Craft version: 3.6.x
- PHP version: 7.3, 7.4

**Comment by brandonkelly** [comment]
Thanks for pointing that out! That was a hairy one to debug. I honestly think it’s been an issue since 3.1 due to 0d9b389744a5946cfe63c7da0d6ca8bfbd07ce74. I didn’t realize that when you pass a higher duration than normal into `yii\web\User::login()`, that duration is _only_ stored on the identity cookie, which is only checked if your normal user session goes away (browser reboot) or expires. And since that 3.1 commit, Craft will remove the session token from the `sessions` table on logout. So what was happening was:

1. Load a web page once you’ve passed the normal session duration
2. `yii\web\User::renewAuthStatus()` sees that your session has expired and logs you out
3. Craft removes the session token from the `sessions` row
4. `yii\web\User::renewAuthStatus()` calls `$this->loginByCookie()`
5. `yii\web\User::loginByCookie()` fails because the cookie is no longer considered valid, because the session token is gone
6. (User remains logged out)

Fixed by storing the actual requested session duration passed to `login()` in a new PHP session variable, and overriding `yii\web\User::$authTimeout` with its value before `yii\web\User::renewAuthStatus()` is called.

**Comment by bencroker** [comment]
Thanks @brandonkelly, thought I was going round the bend trying to debug this one!

**Comment by brandonkelly** [comment]
Craft 3.6.8 is out now with that fix. Thanks again for reporting! ❤️
