### ISSUE TITLE
Using env-variable with pre- or postfix

### ISSUE THREAD

**Issue by bencresty** [craftcms/cms#7620]
### Description

Currently it is possible to use environment variables in more and more fields, like in the base Url field of sites.
But it seems not to be possible to use the environment variable with a prefix or postfix. Especially when using the baseURL field I would like to do things like this:

``` text
$DEFAULT_SITE_URL/en
```

Because only the last part of the URL changes to a locale.

But when doing that it doesn't recognise the env. var anymore and Craft uses it as a literal string instead.

The same goes with volumes. At the moment we are forced to use aliases to add folders to a base path defined as environment variable. So now we need to add an alias to the general.php and in CP enter things like:

``` text
@uploadsBasePath/blog-images
```

It would be a lot more streamlined and less extra code IMO if we could just do this in the CP:

``` text
$UPLOADS_BASE_URI/blog-images
```

There can never be a slash/backslash in an environment variable I believe, so it should be an easy addition to make this possible?  And it would make environment variables way more usefull so we can skip a lot of aliases and extra code in general.php

Would be very welcome! Thanks for considering it!

(Or am I missing something and is this possible and I am doing something wrong?)

**Comment by brandonkelly** [comment]
Technically, `/` characters are allowed in environment variable names, which is why we didn’t do this.

Also, aliases are generally a bit better suited for paths and URLs, because Yii does some normalization on them, such as ensuring trailing slashes are removed so you can safely append additional segments without worrying about double `//`s even if your alias does end in a `/`, etc. Whereas we just find/replace environment variables as-is.

You can set an alias to an environment variable, though, so you get the best of both worlds.

```php
'aliases' => [
    'uploadsBasePath' => \craft\helpers\App::env('UPLOADS_BASE_PATH'),
],
```
