### ISSUE TITLE
Save SiteID to the project config files.

### ISSUE THREAD

**Issue by edwwaarrdd** [craftcms/cms#7634]
### Description
We are working on a multi language site that gets its content via the graphQL api.
When adding new languages we started noticing the siteID on our local environment and on the server where not matching.
So as an example it-it would have siteID 4 locally but once deployed to the server it would have siteID 5.
When looking at the yaml files for sites I don't see any mention of the site ID.
We hardcode these values in the Front-end.
SiteID 4 = Italy
SiteID 5 = ... and so on.
So we can access the entries with a graph query like this.

`
query MyQuery {
  entry(siteId:4, uri:"example"){
    id
  }
}
`

So it would be handy if these values would be saved to the project.yaml files so they would stay the same across different environments.

**Comment by andris-sevcenko** [comment]
The id is not saved to the project config files precisely because they often will not match across environments, as there can be soft-deleted sites from local changes. There's no way to guarantee that the primary key auto-increment values will match, so no IDs are used anywhere in the project config, as they would often cause conflicts.

In your case, I would suggest using the `site` argument, which allows passing the site handle. It is also less reliant on magic numbers and implied knowledge that 4 equals Italy, so is a better solution in the long term, anyway.
