### ISSUE TITLE
Enabling/disabling categories in multisite isn't working correctly

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#7636]
### Description
Not sure exactly where the cause of this is, but if I select a category from admin/categories/group with the checkbox, then use the "set status" dropdown to change it to/from enabled/disabled, the change isn't consistent. It looks like categories can only be enabled or disabled in all sites (Rather than site-specific on/off), but I'm now seeing some enabled and some disabled depending on where/how I changed that:

![image](https://user-images.githubusercontent.com/1250017/109614324-2771fa00-7b3b-11eb-8ec1-bd4b93bf3c5e.png)

![image](https://user-images.githubusercontent.com/1250017/109614330-2b058100-7b3b-11eb-8bd2-74caa4f6cb89.png)

### Steps to reproduce

1. Select all categories with the 'select all' checkbox
2. Change the status to enabled/disabled
3. Click on one of the cateogries
4. Status hasn't changed

### Additional info

- Craft version: 3.6.7
- PHP version: 8.0.2
- Database driver & version: mariadb

**Comment by brandonkelly** [comment]
Well that’s awkward. Since 3.4, the Set Status action will primarily toggle the element’s site-specific status rather than its global status (see https://github.com/craftcms/cms/issues/2899#issuecomment-573330898), however I didn’t consider that Edit Category pages don’t show the site-speciic statuses; only their global ones. So if you disable a category from the index page, the only way to re-enable it (for that site) is from the index page.

I’ll update categories to use the new edit-element layout used by entries and categories in v3.7, which will resolve this.

**Comment by brandonkelly** [comment]
This is resolved now for Craft 3.7.
