### ISSUE TITLE
'Save and Add Another' retains parent entry

### ISSUE THREAD

**Issue by tommysvr** [craftcms/cms#7643]
### Description

When creating a new entry in a Structure via 'Save and Add Another', the Parent entry is retained, even after it is explicitly removed and the entry is saved.

### Steps to reproduce

1. Create an entry in a Structure
2. Create another entry that is a child of the first entry
3. Click 'Save/Publish and Add Another'
4. New entry is also set as a child of the first entry
5. Remove Parent and Save
6. Parent is still set

### Additional info

- Craft version: 3.6.8
- PHP version: 7.4
- Database driver & version: MySQL 5.7

**Comment by Mosnar** [comment]
I hope this isn’t a bug! This functionality saves me so much time.

**Comment by brandonkelly** [comment]
@Mosnar _“ even after it is explicitly removed”_ was the critical part.

I was able to reproduce, when the newly created entry was still an unpublished draft. Turns out entry drafts in general weren’t capable of dropping their parent entry relationship; only replacing it with a new parent entry. Fixed for the next release.

**Comment by brandonkelly** [comment]
Craft 3.6.9 is out now with that fix.
