### ISSUE TITLE
Cant use matrix block twice in twig template

### ISSUE THREAD

**Issue by joomkit** [craftcms/cms#7650]
### Description
Using matrix loop once on a page effects the block display in the second use of the matrix block

### Steps to reproduce

1. Create a matrix block with 3 types of block
2. Output twice in twig like:

      {% for block in entry.contentBlock.type('text').all %}
        {{ block.type }}
    {% endfor %}

    {% for block in entry.contentBlock.all %}
        {{ block.type }}
    {% endfor %}

3. Second output only shows one block type

### Additional info

- Craft version: 3.6
- PHP version:7.3
- Database driver & version:mysql5.7
- Plugins & versions: SEOMatic

**Comment by andris-sevcenko** [comment]
Fields that hold relations to elements (even Matrix fields, because a Matrix field is a collection of Matrix Blocks, which are elements) return that field as an element query, so in essence, you are filtering down that element query and then running it twice. This behavior is [better explained here.](https://craftcms.com/docs/3.x/upgrade.html#cloning-element-queries)

```twig
{% for block in clone(entry.contentBlock).type('text').all() %}
    {{ block.type }}
{% endfor %}

{% for block in entry.contentBlock.all() %}
    {{ block.type }}
{% endfor %}
```

This should do the trick.
