### ISSUE TITLE
Yii to Laravel?

### ISSUE THREAD

**Issue by kevadamson** [craftcms/cms#7752]
Read somewhere you might be changing from Yii to Laravel. Any mileage in this? If so, is there an ETA on this happening. Thanks :)

**Comment by brandonkelly** [comment]
Thinking about it, but not something we‘ll seriously start looking into until after 4.0.

**Comment by acalvino4** [comment]
Sounds like almost definitely a painful migration.....but in this case totally worth it and something I (and many others) would happily go through! Hope to see it some day!

**Comment by acalvino4** [comment]
Because Laravel is great at doing what it does and bc of it's popularity / likelihood of long-term support, originally I hoped for something like this. However, I've come across a number of reasons that I suspect sticking with Yii is actually the right choice:
* Craft is already on Yii / migrating would be a pain (the obvious point)
* Yii uses static analysis where possible for type checking and such, whereas Taylor has basically refused to implement it on Laravel (unless something changed recently)
* Alongside [Yii Cache](https://github.com/yiisoft/cache), Yii 3 will implement every currently accepted PSR. I don't know of any other php framework that can say as much.
* Yii seems to take the approach of taking the time to do things right, rather than rushing anything to production. While the obvious con is long time-to-production (Yii 3 and Craft 4, looking at you), this philosophy is in line with what has made Craft so awesome.
* Yii 3 aims to be super flexible and pluggable in its architecture. In contract, Laravel is less so, and its direction is somewhat tied to Taylor's opinions / what Laravel deems to be the right way for things.

Anyway, that's my lowly opinion, and others may know details I don't that influence the best choice. Ultimately, however, Brandon and the Craft team have an impeccable track record of making good choices, so I trust whatever ya'll decide!

**Comment by brandonkelly** [comment]
Appreciate the thoughts, @acalvino4!
