### ISSUE TITLE
{% js %} / {% script %} inside {% cache %} only works on first page load

### ISSUE THREAD

**Issue by ttempleton** [craftcms/cms#7758]
### Description

On a new Craft install, when using either the `{% js %}` or `{% script %}` tags inside a `{% cache %}` tag, the `<script>` is output to a page on the first load, but not on subsequent loads of that page.

### Steps to reproduce

1. Use a `{% js %}` or `{% script %}` tag inside a `{% cache %}` tag
2. Load a page where that template is used, open the browser's developer tools and see that the `<script>` tag has been output
3. Reload the page, open the browser's developer tools and see that the `<script>` tag hasn't been output

### Additional info

- Craft version: 3.6.11.2
- PHP version: 8.0.3
- Database driver & version: PostgreSQL 13.2
- Plugins & versions: None

**Comment by brandonkelly** [comment]
That’s expected; those tags can only capture direct tag output, but `{% js %}` and `{% script %}` will register JS code which gets output once the rest of the page has been rendered. You should avoid calling those tags within `{% cache %}` tags.

**Comment by ttempleton** [comment]
I appreciate that it shouldn't be done, but a user definitely shouldn't expect to see something work once and never again, if it wasn't intended to work at all.

**Comment by brandonkelly** [comment]
Yeah fair enough. This has come up a few times, so I agree it’s probably not expected behavior, and tricky to debug.

Just went ahead and added JS & CSS code caching for `{% cache %}` tags, for Craft 3.7.

**Comment by schwarzdesign** [comment]
@brandonkelly Just noticed that caching only works for inline code, not JS / CSS files. Is this by design or is there something stopping this from working correctly? It would be a great improvement if the cache tag worked with the JS / CSS tags when registering files. At least for us, inline code is not used very much, but it's very common to have a component (that may be included in a part of the page that's cached) that needs to register its own JS / CSS files. Not being able to do that inside components that may be cached is a rather hefty limitation. Is there any chance to get this in the future?

**Comment by brandonkelly** [comment]
@schwarzdesign It’s doable. Can you please post that as a new [feature request](https://github.com/craftcms/cms/discussions/new?category=ideas)?
