### ISSUE TITLE
Translated section names can cause data-loss in permissions form

### ISSUE THREAD

**Issue by robbeman** [craftcms/cms#7771]
### Description

When translating section names in `translations/[locale]/site.php` and you (by chance or by choice) have two sections with the same name it can cause the permissions form to overwrite the first section with the second.

### Steps to reproduce

1. Create `site.php` translations file in your language
2. Add two items with the same name like:
    ```php
      'Jobs' => 'Jobs',
      'Jobs Index' => 'Jobs',
    ```
    ![image](https://user-images.githubusercontent.com/3245659/113851806-2bc5ae80-979c-11eb-9e44-cfc9b4645c79.png)
3. Edit permissions `http://you-are-wonderful.local/admin/settings/users/groups/1`
4. Save permissions
5. Check git differences
6. See things go away

### Cause

In my specific case this is happening here: https://github.com/craftcms/cms/blob/decad72fafe8b0da0650f899bc952eab9a9f34dc/src/services/UserPermissions.php#L163-L172

### Fix?

```diff
        foreach ($sections as $section) {
            $label = Craft::t('app', 'Section - {section}',
                ['section' => Craft::t('site', $section->name)]);

            if ($section->type == Section::TYPE_SINGLE) {
-                $permissions[$label] = $this->_getSingleEntryPermissions($section);
+                $permissions[$section->handle] = $this->_getSingleEntryPermissions($section);
            } else {
-                $permissions[$label] = $this->_getEntryPermissions($section);
+                $permissions[$section->handle] = $this->_getEntryPermissions($section);
            }
        }
```

This fix may have unintended side-effects, I'm not very well acquainted with the source code, but at least it's a starting point.

### Additional info

- Craft version: 3.6.8
- ~PHP version:~
- ~Database driver & version:~
- ~Plugins & versions:~

**Comment by brandonkelly** [comment]
That’s a tricky one. Your proposed fix would certainly fix the underlying issue, but those array keys are the human-facing group headings, so the unintended side effect would be that the group headings would start showing the section handles rather than their titles, which isn’t desired.

The only good fix for this is to stop indexing the array by headings, and move the headings into a nested key. That’s a breaking change, though, so unfortunately can’t be done for 3.x. I’ve just made the change for Craft 4, though (d3d20ba6e4f145d8da78989372ec1e5103678b8e). In the meantime, you’ll just have to avoid using identical section names.
