### ISSUE TITLE
GraphQL returning 'null' for draft entries with a future post date

### ISSUE THREAD

**Issue by taow80** [craftcms/cms#7775]
### Description
GraphQL API responds with "null" for an entry if it is a draft and the postDate is in the future .  If the entry is published with a future postDate(ie status: pending) GraphQL returns the entry values requested.  This is only an issue when attempting to preview drafts when utilizing Craft as a headless CMS.

### Steps to reproduce

1. Create entry with Post Date set to a future date/time and save as draft
2. Use the GraphQL API Explorer and run a query such as:

query draftEntry {
  entry(draftId: insert draftId value) {
   id
  }
}

or

query draftEntry {
  entry(id: insert id value, drafts: true) {
   id
  }
}

### Additional info

- Craft version: Craft Pro 3.6.11.2
- PHP version: 7.4.16
- Database driver & version: MySQL 5.7.31
- Plugins & versions:
Google Cloud Storage | 1.4.0
Image Resizer | 2.1.0
Redactor | 2.8.5
Workflow | 1.5.9

**Comment by andris-sevcenko** [comment]
This is not exclusive to GraphQL and  happens for element queries, as well.

This is because the status parameter defaults to `enabled`. However, if an entry (not just a draft) has the post date set in the future, it has a status of `pending`.

You can query for future entries by setting the status argument to `"pending"`, or you can set it to `null`, to allow all statuses, such as
```graphql
query draftEntry {
  entry(draftId: <draftId> status: null) {
    id
  }
}
```
