### ISSUE TITLE
Use baseCpUrl as the hostname in @transform with immediately: false and pathParam: true

### ISSUE THREAD

**Issue by Zae** [craftcms/cms#7783]
### Description
This is basically the same bug as #5553 but with `$generalConfig->pathParam = true;`

My action urls to transform the image are still generated with the baseurl of the website instead of the baseurl of the Cp.

What we noticed during debugging is that when we set `$generalConfig->pathParam = false;` then everything seems to work fine.

It always works when using the GraphiQL UI to run the GQL, but it's broken on real requests.

frontend url of my website: https://doen.test
url of the cp: https://cms.doen.test

url that is generated: https://doen.test/index.php?p=admin/actions/assets/generate-transform&transformId=3
url I want: https://cms.doen.test/index.php?p=admin/actions/assets/generate-transform&transformId=3

### Steps to reproduce

1. set headlessmode = true
2. set pathParam = 'p'
3. do an asset GQL query from the frontend with `w1920: url @transform(width: 1920, immediately: false)`

Now it's broken, the actionUrl is generated using the baseurl of the website not the Cp.

1. set headlessmode = true
2. set pathParam = null
3. do an asset GQL query from the frontend with `w1920: url @transform(width: 1920, immediately: false)`

It works!

### Additional info

- Craft version: 3.6.11.1
- PHP version: PHP 7.4 
- Database driver & version: MySQL 5.7.33
- Plugins & versions:

**Comment by brandonkelly** [comment]
`pathParam` should be set to a string or `null` – not `true` or `false`. It’s `'p'` by default. Maybe the invalid value has something to do with this?

**Comment by Zae** [comment]
Hi Brandon,

You are right I was confused, when I leave out pathParam from my config (so default 'p'), my paths are wrongly generated.

When I set pathParam in my config to a falsy value (null or false) the actionUrl is correctly generated.

What we noticed during debugging is that the method `UrlHelper::actionUrl` calls `UrlHelper::_createUrl` and passes the value from `(bool)$generalConfig->pathParam` then in `UrlHelper::_createUrl` this variable is used to generate the `$baseUrl`, but in the branch if `$showScriptName` is thruthy (p), the `$baseUrl` is generated using `static::host()` and the 
truthy `$cpUrl` branch is not taken.

When I make pathParam falsy, the `$cpUrl` branch is taken and the `$baseUrl` is correctly set to the cpUrl.

So setting the `$cpUrl` to true in `actionUrl` when headless mode or cpRequest is true is ignored.

**Comment by brandonkelly** [comment]
Gotcha. It works that way because `actionUrl()` is sometimes used to generate a URL that will be used by a POST request, and for POST requests, we _must_ include the script name (`index.php`) if Craft hasn’t been explicitly told it’s not necessary (by setting `pathParam => null`). Otherwise the POST requests may not make it to Craft in-tact, if using Apache.

But there are plenty of cases where action URLs are used for GET requests, `assets/generate-transform` URLs included. So I’ve just added a new `$showScriptName` argument to `actionUrl()` which can be set to `false` in cases where it’s not necessary, and updated calls to it to pass `false` where appropriate.

**Comment by brandonkelly** [comment]
We just released Craft 3.6.12 with this change.
