### ISSUE TITLE
Searching for entries with a date earlier than current date does not work as expected

### ISSUE THREAD

**Issue by brycekirk** [craftcms/cms#7789]
### Description
I'm trying to filter my entry loop with a search for entries earlier than today's date, based on a date field that each entry has. It works to search by dates _later_ than today, and checking the same logic inside the loop with an if statement works as well.

So this correctly displays events in the future:
`{% set futureEvents = craft.entries({section: 'events', date: '> ' ~ now|date()}) %}`

And within a loop of ALL events, this works as expected
```
{% if entry.date < now|date() %}
  <h1>This event is in the past</h1>
{% endif %}
```

But this, which should display entries in the past, doesn't display any
`{% set pastEvents = craft.entries({section: 'events', date: '< ' ~ now|date()}) %}`

### Steps to reproduce

1. Create a date field and a bunch of entries using it. Set some dates to the past and some to the future
2. Test the loop with the above logic

### Additional info

- Craft version: Craft Solo 3.6.11.2
- PHP version: tested on 7.3.9 and 7.4.2
- Database driver & version: MySQL 5.7.26

**Comment by brandonkelly** [comment]
Looks like your problem is that you are using the [|date](https://craftcms.com/docs/3.x/dev/filters.html#date) filter, which will output a human-friendly date format by default. Try using the [|atom](https://craftcms.com/docs/3.x/dev/filters.html#atom) filter instead, as the examples use in the [Date field docs](https://craftcms.com/docs/3.x/date-time-fields.html#querying-elements-with-date-fields):

```twig
{% set pastEvents = craft.entries({section: 'events', date: '< ' ~ now|atom}) %}
```
