### ISSUE TITLE
Plugin Neo v.2.9.5 javascript error

### ISSUE THREAD

**Issue by schmidtsonian** [craftcms/cms#7797]
### Description
I just upgrade to craft Solo  3.6.12 and now there is a javascript error with `.pill` selector

### Steps to reproduce

1. When I add a "block" from a "Neo" field the field crash and I can't save any content or disable/remove/move the current block

![image](https://user-images.githubusercontent.com/2094546/114658874-2c88a400-9cb8-11eb-99af-e8cc70a54a13.png)

### Additional info

- Craft version: 3.6.12 
- PHP version: 7.2.34
- Database driver & version: MySQL 5.5.5
- Plugins & versions:
```
Amazon S3 1.2.11
Element API 2.6.0
Reasons  2.9.5
Reasons  2.2.4
Redactor  2.8.6
Super Table 2.6.7
```

https://github.com/spicywebau/craft-neo/issues/441

**Comment by brandonkelly** [comment]
The `pill` component was never fully implemented; there were no styles associated with it and the JS code that was there was producing errors when invoked. So it was removed in Craft 3.6.11 to avoid conflicts with third party code that may want to introduce a “`pill`” component (see #7705).

Thanks for also reporting the error to Spicy Web. Looks like this only affected Neo because it contained some JS code that had been copied from Craft which included the same reference to the unfinished `pill` component; not because they were actually trying to use the component somehow. And it’s already fixed in Neo 2.9.6.
