### ISSUE TITLE
Resave entries when a field is added

### ISSUE THREAD

**Issue by bengreenbank** [craftcms/cms#7802]
### Description
I'm adding a field with a default value to an entry type. However I find I have to run the 'resave all entries (https://craftcms.com/docs/3.x/console-commands.html#resave)' command if I want that default value to save across all entries with that field.

It would be good if Craft had a way of detecting if a new field with a default value has been added and then intelligently resaved all the entries automatically.

**Comment by brandonkelly** [comment]
Actually default field values don’t apply to existing elements, even after resaving them. The only exception is Dropdown fields, and only when resaved via the control panel UI, simply because `<select>` inputs _must_ submit a value, so Craft will go with the default if it’s forced to come up with _something_ for the UI.

We’re considering making it possible to apply default values to existing elements for Craft 4, though – see #2446.
