### ISSUE TITLE
Duplicated entry not visible after duplication

### ISSUE THREAD

**Issue by jkorff** [craftcms/cms#7830]
### Description
When I check an entry and click Actions > Duplicate, the new entry is nowhere to be seen, and the search box has disappeared. To find the duplicated entry I need to click on Entries and then search for words of the heading of the duplicated entry.

### Steps to reproduce

1. Go to Entries
2. Check an entry
3. Click on the Actions cog, then select Duplicate

### Additional info

- Craft version: 3.6.11.1
- PHP version: 7.4.16
- Database driver & version: MySQL 10.2.37
- Plugins & versions: n/a

**Comment by brandonkelly** [comment]
I guess this depends on how your entry index is sorted. Duplicated entries get the same Post Date as the original, so if you’re sorting by Post Date, it should show up right next to it. Not really a bug though.

**Comment by jkorff** [comment]
Hi Brandon,
I don't think that a requirement to sort by date is very practical. My use case is that I have a keyword in mind which belongs to the entry I need to copy. So I search for that keyword, check the box in front of the entry and duplicate.
I believe this to be a fairly common scenario Craft should accommodate. Otherwise I might have to go through pages of entries before I find the one I'm looking for (because it's older already).

**Comment by brandonkelly** [comment]
Ah that makes sense. Unfortunately the issue here is that element search indexes are updated via a background job after the element was saved, so the duplicate entry won’t turn up in search results until its keywords have been indexed.

This is a good argument for us implementing #7815 or preserving the search query in the URL via a query string param, so you can try reloading the page if the entry doesn’t show up immediately.

**Comment by jkorff** [comment]
Thank you Brandon, I'd love to see #7815 implemented. (I always open entries in new tabs so I can keep my search results.)
