### ISSUE TITLE
getCpEditUrl for draft entry doesn't work

### ISSUE THREAD

**Issue by janhenckens** [craftcms/cms#7832]
### Description
We're trying to set up a "submit entry for approval" type workflow, where the e-mail to the admin contains an edit link straight to the draft. 

The url generated by `getCpEditUrl()` doesn't include the `draftId=1` parameter, which causes it to 404

### Steps to reproduce

1. Create a draft
2. Get the cpEditUrl for that draft

### Additional info

- Craft version: 3.6.12
- PHP version: 7.4

**Comment by brandonkelly** [comment]
Are you creating the draft programmatically? Can you share the code?

**Comment by janhenckens** [comment]
No, from the CP. Our code so far is a template hook to show a button in the entry edit details section. 

There we pass the ID to a controller, get the entry through a query with 'draft(true)' and that cpEditUrl seems to be wrong. I'll look up the query tonight!

**Comment by brandonkelly** [comment]
Sorry, I misremembered how this works… I thought `Entry::getCpEditUrl()` was adding the `draftId` param, since it does get added to entry edit links when you are filtering the Entries index by drafts, but that’s actually coming from `craft\helpers\Cp::elementHtml()`:

https://github.com/craftcms/cms/blob/06a2e1d78b8b097f824efede5a6b36807a5bed5a/src/helpers/Cp.php#L394-L398

I’ll refactor the code a bit in 3.7 so `getCpEditUrl()` starts including `draftId` / `revisionId` params.

**Comment by janhenckens** [comment]
Thanks! We'll add it manually for now since our use-case will only cover drafts so that should be ok.

**Comment by brandonkelly** [comment]
Got this in for 3.7 ✨

**Comment by janhenckens** [comment]
Great, thanks!
