### ISSUE TITLE
'descendantsOf' and 'ancestorOf' GraphQL Arguments only accepts type 'Int', when (unless I'm misunderstanding the docs) it should be of type QueryArgument to access the Entry Modal

### ISSUE THREAD

**Issue by toddpadwick** [craftcms/cms#7969]
### Description

I am attempting to use `descendantsOf` to get the child entries of their parent in GraphQL. The [documentation](https://craftcms.com/docs/3.x/graphql.html#the-entries-query) is pretty sparse on this, but by my understanding of the below description of this argument quoted from the docs, `descendantsOf` should be the right argument for the job:

> "**descendantsOf:** Narrows the query results to only elements that are descendants of another element."

But, unless I am misunderstanding something, of type `Int` doesn't seem like the right type for it's purpose? I would expect to be able to pass an ID (which I've tried with no luck) or a slug into this argument  - and therfore would need to be of type `QueryArgument` or `String`.
 
I believe the twig version of the `descentantsOf` argument does, as expected, accept the Entry Modal parameters.

I believe this is also the case with `ancestorOf`,  `nextSiblingOf`, `prevSiblingOf`, `positionedAfter`, `positionedBefore`.

If I am mistaken in some way here, however, please let me know what I am missing. it would also be helpful for a little more detail in the docs for each query argument.

**Comment by andris-sevcenko** [comment]
Twig accepts either an Element or element id for this parameters. In GraphQL it's not really possible to pass an Element as an argument, so the parameter (and all the others you mentioned) have been reduced to the element id.

It's impossible to pass a slug with Twig to this argument, too, and, since GraphQL wraps around Element Queries, it's not very straightforward to add that functionality, either.

I'll go ahead and update the docs to clarify that an id is expected.
