### ISSUE TITLE
Add new EVENT when checking if an element is editable.

### ISSUE THREAD

**Issue by samhibberd** [craftcms/cms#8023]
### Description

Much like the super useful new purchasable event that was recently added to commerce (https://github.com/craftcms/commerce/issues/2106), would it be at all feasible to add a similar EVENT to the element `getIsEditable()` method.

Being able to hook into this method would be soooo useful, especially where an element does not implement that method or, like commerce products, does not have an author and would thus allow us to restrict permission to edit an element dependent on our own custom scenario (most likely a custom value set on the element).

Would fix this related commerce issue for us https://github.com/craftcms/commerce/issues/174

Is also think, as an added bonus, it would also mean that saving elements respect any permissions too, which means any custom permission logic would not have to be recreated in custom controllers, of behaviours etc etc.

Thanks.

**Comment by brandonkelly** [comment]
Just pushed up a new `EVENT_DEFINE_IS_EDITABLE` event to the 3.7 branch (as well as `EVENT_DEFINE_IS_DELETABLE`): 994345a5dcbf74d2cc298e6b5430a2f01db909a8.

Note that it’s up to each element type to add support for these events, by implementing the new protected `isEditable()` and `isDeletable()` methods, rather than the public `getIsEditable()` and `getIsDeletable()` ones. (I’ll inform the Commerce team about that.)

**Comment by samhibberd** [comment]
Awesome, insane service as usual!!! 🎉
