### ISSUE TITLE
Slow GraphQL queries on larger schemas

### ISSUE THREAD

**Issue by andrewfairlie** [craftcms/cms#8035]
### Description
When a schema has multiple sections and entry types, every query seems to be a lot slower. For example

```graphql
{
    ping
}
```

On an empty public schema takes `48ms`. Once that schema has access to sections and entry-types, the exact same query shoots up to `203ms`. Even when GraphQL caching is enabled, the difference persists. Fewer sections = faster queries, even if those sections have nothing to do with the query at hand. 

It _feels_ like something to do with parsing or generating the schema is happening on the fly in each query. I might be mistaken. We see the increase in execution time creep up with each new section added.

### Steps to reproduce

1. Run a ping test on an empty schema
2. Run a ping test on a schema attached to a bunch of sections

### Additional info

- Craft version: Craft CMS 3.6.16
- PHP version: 8.07
- Database driver & version: MySQL 5.7.0
- Plugins & versions: I've disabled all plugins for the purpose of this experiment

**Comment by andris-sevcenko** [comment]
The GraphQL schema needs to be generated for every query (no matter how simple) so that the query can be validated, which incurs overhead, that increases as the site's complexity increases.

There's a whole discussion about this over at https://github.com/craftcms/cms/issues/7222, so I'm closing this as a duplicate.
