### ISSUE TITLE
Missing content-length header forces chunked response

### ISSUE THREAD

**Issue by maknapp** [craftcms/cms#8070]
### Description
All craft entry responses seem to not set the content-length header, forcing the response to have "transfer-encoding: chunked" header. It is more efficient to set a content-length when available. I thought twig renders then entire page before being sent, so content-length should be known. Is there a reason the header does not get set?

### Steps to reproduce

1. Go to: https://craftcms.com/
2. All responses have no content-length and are chunked (I am assuming craftcms.com runs on craft since headers look the same as mine).

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4.3
- Database driver & version:
- Plugins & versions:

**Comment by brandonkelly** [comment]
Made this change for the next 3.7 release.

**Comment by brandonkelly** [comment]
3.7.0-beta.2 is out now with that change.

**Comment by brandonkelly** [comment]
It turns out there are cases where this change was problematic, as the actual content length could be smaller than expected due to gzipping, etc. Usually when that happens, the header is overwritten, but that’s apparently not always the case.

At best that will result in a “Premature end of Content-Length delimited message body” validation error, and at worst it turns out Safari will just bail on displaying the page, instead showing a “‘cannot parse response’ (NSURLErrorDomain:-1017)” error.

So I’ve [just added](https://github.com/craftcms/cms/commit/00b4d61f0067c36fd960cc04d48026aeeb79f0ae) a new config `sendContentLengthHeader` config setting for the next release, which will determine whether Craft should send `Content-Length` headers or not, and defaulted it to `false`.

**Comment by maknapp** [comment]
I am curious where gzip happens without adjusting the content length header. Is that a Yii option or Craft?

**Comment by brandonkelly** [comment]
It would be either on the web server or via a proxy; not something Craft or Yii would do directly.

**Comment by brandonkelly** [comment]
Craft 3.7.3 is out now with that new config setting.
