### ISSUE TITLE
[3.7 Beta] Can slider meta data toggle be sticky per element? 

### ISSUE THREAD

**Issue by RitterKnightCreative** [craftcms/cms#8075]
### Description
Had a chance to play with the new 3.7 beta and I have to say... you guys keep coming up with features that a I didn't know we needed! Kudos.

A subtle improvement might be to save the state of the slider meta data drawer/column per element. 

For entries, you probably don't need to have the drawer open because your content takes center stage—having the slider closed by default probably makes sense. However, on assets, the actual image, for example, is hidden unless you toggle the sidebar. 

One issue with that is we commonly need to set crop or focus point on an asset and it's another click to get into the image. Those extra clicks add up if you do this a lot. And I've noticed I sometimes forget what image I just clicked on. If the sidebar were sticky,  meaning the sidebar meta data drawer defaulted to open if it was dismissed that way last, it would default to open for the next slider (provided it's the same sort of element). 

I think this would give some flexibility without breaking too much.

One other way to improve the UI is perhaps move the asset thumbnail to the main content area instead of being in the meta data drawer which would be more like it is in previous versions of Craft. I'm guessing you had reasons to do it this way which is why a sticky meta data drawer could make more sense.

**Comment by mmikkel** [comment]
As awesome as the slideouts are, I completely agree that as-is, they make less sense for Assets.

We rarely add lots of custom fields to Assets, and in my experience, most of the time when authors double-click Asset thumbnails, they either want to see a bigger preview image, edit the title or filename, or launch the image editor. 

I think that for Assets specifically, the slideouts is a step backwards to the old element editor HUDs, in making all of these less accessible than before.

**Comment by brandonkelly** [comment]
Not sure how I feel about remembering the sidebar state, or whether that would even be very helpful if it’s remembered per-element. Leaning toward no, but maybe adding a keyboard shortcut that opens it quickly.

If you just want to see a larger image thumbnail, you can select an asset within a relational field and press <kbd>Shift</kbd> <kbd>Space</kbd> to open up a Quick Look-style preview of it.

> I think that for Assets specifically, the slideouts is a step backwards to the old element editor HUDs, in making all of these less accessible than before.

Hard disagree with that. Asset slideouts

- link to the asset’s dedicated edit page (#3448, #5857)
- display metadata like the location, file size, image dimensions, etc. (#3930, #6918)
- show the full field layout w/ tabs and UI elements (#6587, #4129, #4245, #6647, #7811)

Even if you aren’t assigning a lot of custom fields to assets, the first two still apply.

**Comment by mmikkel** [comment]
> Even if you aren’t assigning a lot of custom fields to assets, the first two still apply.

Don't disagree with that, the asset slideout is certainly more _powerful_ than the old HUD. "A step backwards" was probably too strong – _two steps forwards and one step back_ is maybe more to my point; that it'd be great if the asset preview, filename (well, all the meta data, I guess) and image editor link wasn't hidden behind an additional click. The old HUD didn't have the additional metadata and was a bit small, but it did allow authors to view the preview, launch the image editor and/or edit both the filename and any custom fields, without any additional clicks or panels needing to open.

Back to the issue at hand – instead of retaining the sidebar state, could it be an idea to simply not make it an expandable panel (i.e. display it at all times, similarly to how the dedicated edit pages work, for all element types) if the viewport is sufficiently wide to accommodate both the custom fields/tabs container and the meta panel?

**Comment by RitterKnightCreative** [comment]
> Hard disagree with that. Asset slideouts
> 
> * link to the asset’s dedicated edit page (#3448, #5857)
> * display metadata like the location, file size, image dimensions, etc. (#3930, #6918)
> * show the full field layout w/ tabs and UI elements (#6587, #4129, #4245, #6647, #7811)

In every way they're superior to the HUDs if you're editing content. But in the case of assets, especially images, if we have to engage the sidebar (with a click or someone using a keyboard) just to see the image and then click again to finally get to a point where we can edit it, that's a little  more clunky than it needs to be.

Take a common example of an image gallery. Author uploads a bunch of images to an asset field inside an entry. Does a Live Preview to see what they're going to look like on the site.  Got a few of them that are going to need their focus points set. Do this 10 times and that extra click or keyboard shortcut to engage adds up. 

And  FWIW it's really another step in a training manual/video that doesn't really need to be there that adds friction. AT least if the sidebar were sticky or the asset was shown by default, we wouldn't be having this discussion.

> If you just want to see a larger image thumbnail, you can select an asset within a relational field and press Shift Space to open up a Quick Look-style preview of it.

That's nice to know but it's a one-trick pony.  If there's some other shortcut to quickly get to the image editing window from within an entry editing screen (eg option?), that would be very helpful. Right now, it's taking 3 clicks to get there. Previously it took 2.

> what about making the meta sidebar visible at all times (for all element types), if the viewport is sufficiently wide to accommodate both the custom fields/tabs container and the meta panel – and only render it in a collapsed/expandable state when the horizontal space gets too narrow?

I could get behind this idea as well.

**Comment by brandonkelly** [comment]
Always showing the sidebar on larger screens is a good idea. Will look into that.

Another thing we could look into is adding element popovers (like what you get when hovering over an avatar / username / issue number here on GitHub). Asset popovers could include a larger thumbnail with a “Edit” button on top of it, so accessing the image editor becomes a one-click action.

**Comment by brandonkelly** [comment]
Just made the sidebar change. Went with a `min-width: 1536px` breakpoint, which is Tailwind’s default `2xl` size.

<img width="1540" alt="An asset editor slideout, showing that the sidebar is visible by default when the screen is wide enough" src="https://user-images.githubusercontent.com/47792/122439629-abb48580-cf50-11eb-95b8-1be5d33fcc1a.png">

**Comment by rynpsc** [comment]
Unable to test right now but would this also apply to other elements? I'm thinking that with other elements the field layouts are likely to be more complex e.g. a matrix content builder or product variants, where the user would probably appreciate the extra space being given to the main content given how visually "busy" those are.

Would making the whole sliders default width wider meet everyones needs? I'm thinking making it so it's just a little narrower than the main element window.

**Comment by mmikkel** [comment]
I tested it out, and I'm a big fan of the always-visible sidebar (on larger screens) – but I also wouldn't mind if the actual slideout panel width was a little bit wider, especially on >1536px when the sidebar kicks in.

**Comment by brandonkelly** [comment]
@rynpsc All element types, yes. I think in general fields should be able to look good on thinner widths (you don’t get a choice on mobile), so not too worried about the width.

**Comment by brandonkelly** [comment]
3.7.0-beta.2 is out now with the sidebar change.

**Comment by rynpsc** [comment]
I've now had to chance to test and I think showing the sidebar is the right decision on larger screens but and do think the experience isn't as good for other elements as it was in 3.7-beta-1 due to the narrower field width.

I think the whole slideout should be wider so the content to sidebar ratio is higher given the available inactive space to the left. It would make drag and drop easier as the user doesn't have as far to scroll, table and matrix fields would have more room and line lengths more comfortable.

Also one of the quirks of any responsive layout is that only a pixel separates having a much wider content area to work with vs a more "cramped" layout as illustrated in the screenshots below.

I've tried using a width of 75% which make things better in my eyes. It does however make it so that the field layout area is extra wide that in that in-between size. This could be solved with CSS alone but the `updateStyles` function in `Craft.slideout` has a hard coded value of 50 for the vw calculation. Would it be feasible to calculate that value with something like the below? 

```js
Craft.Slideout.openPanels.forEach((panel, i) => {
  var vw = (1 - panel.$container.outerWidth() / $(window).width()) * 100;
  panel.$container.css(Garnish.ltr ? 'left' : 'right', `${vw * ((totalPanels - i) / totalPanels)}vw`);
});
```

With that in place we could then override the CSS should a developer chose, and it also decouples styling somewhat to allow imposing max-widths and changing width in media queries without complicating the JS.

The new slideouts are great and are going to be a huge improvement for our clients. Thanks.

<img width="1680" alt="1" src="https://user-images.githubusercontent.com/5955881/122607934-44432680-d073-11eb-8542-93b04b9c820b.png">
<img width="1536" alt="2" src="https://user-images.githubusercontent.com/5955881/122607940-46a58080-d073-11eb-85c3-67434fb1e23e.png">
<img width="1537" alt="3" src="https://user-images.githubusercontent.com/5955881/122607944-47d6ad80-d073-11eb-92a9-027448d99540.png">
<img width="1680" alt="4" src="https://user-images.githubusercontent.com/5955881/122607953-49a07100-d073-11eb-9839-2a7b6c758786.png">

**Comment by brandonkelly** [comment]
Not interest in increasing the width of the slideout, but we will revisit the product variant UI.
