### ISSUE TITLE
Better options to sync content across locales

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#828]
> Created by: Christian (seelbach@gmx.de) on 2015/03/09 00:49:13 +0000
> Votes at time of UserVoice import: 58

-----------------------------------

Right now, the content of all fields which are marked as translatable are only copied over to the other locales on the very first entry save.

Wouldn't it be great if there was a checkbox right next to each field that triggers another synchronization (of that field) across all locales?

There are lots of cases where you need a field to be translatable, but only make locale specific edits in very rare situations. Being able to trigger another synchronization after making edits to such a field saves you from extensive and error-prone copy and past actions.

I can imagine this being a really complex and complicated feature to implement. So an alternative suggestion would be to just provide an indication whether a field is still in sync or not.

To list some example cases: fields for proper names of things that are almost (!) never translated like city names, fields where you only occasionally list things and include conjunctions like "and", date fields that are usually the same across locales but can differ in special cases like release dates.

**Comment by tinchalamo** [comment]
I like the idea of a checkbox for "Synch across Sites" next to a translatable field so you can choose which sites should have totally different data while still having the ability to synch data across other sites.

**Comment by timkelty** [comment]
@tinchalamo have you tried https://github.com/timkelty/craft-localesync? Will probably port to Craft 3 soon.

**Comment by dougstjohn** [comment]
We use a custom twig variable solution for one of our clients. This doesn't sync content between locales, but it does allow for individual entry fields to fallback to en-us if no content is set on the current user's locale.

Content managers fill out en-us entries and other locale entries (ex. en-au, en-nz, etc) can stay empty and then if those locale's entries are ever set, that data will be used instead of en-us.

`{{ withEnUsFallback(entry, 'termsOfUseContent') }}`

It would be nice to have a UI where you could easily compare one entry field across all locales.

**Comment by christianruhstaller** [comment]
A similar but different strategy for the sync: https://github.com/Goldinteractive/craft3-sitecopy :)

**Comment by outline4** [comment]
There is no logic to synch content across sites until the first save. 

My guess is you've chosen this path because it's easier to program. But nobody in their right mind would do this because it's best practice. It just doesn't make any sense! 

In my opinion, content should be synched to the original content (the one you've started with), until there's a change in any field of other sites. There should be some sort of indicator in which site relies the original content, and that it's not edited yet, respectively still in synch. 

If this is too complex for now, you could maybe start by only checking the title field:  
if the title field has changed, stop synching the content to the "master" content and mark it "translated" or something. 

Also: As soon as the title in another site is changed you should empty the slug that was prefilled from the other site. 

You can do better. And I believe this should be core.  

P.s. we have 4 official languages in our country. We need to take translations serious ;)

**Comment by brandonkelly** [comment]
Craft is going to start tracking dirty fields in 3.4 (#4149), so this is something we could potentially do with that info. May pair well with a fix for #4642 as well.

**Comment by piotrpog** [comment]
@brandonkelly Does it mean that there will be option to copy one locale contents to another locale (cloning sites)?

**Comment by brandonkelly** [comment]
@piotrpog that’s the idea, yeah.
