### ISSUE TITLE
Open Source Craft

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#842]
> Created by: Nathan Doyle (natetronn@gmail.com) on 2015/03/11 04:20:14 +0000
> Votes at time of UserVoice import: 44

-----------------------------------

The title says it all!

This idea for this came from Brandon in fact (to a degree anyway) when we were talking about plugin pricing and business models. He stated, and I'm paraphrasing, if revenue from the Plugin Store commissions and Craft Commerce (presumably) reached a point of success it would allow P&T to lower the price of Craft itself.

I'd like to see this happen and hope such business models could be implemented with such success that Craft could become FOSS FTW!!! 

(yes I triple exclamation pointed)

Here is what BK said: http://monosnap.com/image/OKgkwHqfN8EXu8ALcIzPlbvkKOX9sk

**Comment by frob** [comment]
With all the comments being posted here referencing some sort of comfort in the fact that a body is responsible for the source code. That is already the purview of the service agreement and not the source code license. 

From the CreaftCMS [source code license](https://github.com/craftcms/cms/blob/develop/LICENSE.md).

> THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES, OR OTHER LIABILITY, INCLUDING SPECIAL, INCIDENTAL AND CONSEQUENTIAL DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

**Comment by brandonkelly** [comment]
@frob Right, if Craft source code were to go MIT, we would absolutely still own its branding and the master repository, and maintain our status as its chief maintainers.

**Comment by frob** [comment]
If Craft went GPL then any derivative would also be forced to be open source. This would further protect the source project (Craft) and allow for derivatives to be rolled back into Craft. MIT has its benefits too, but I am no lawyer and you will definitely want to talk to one of those before re-licensing your project.

I will have to say, as someone who uses OSS for most of my work, it is always difficult when I am forced to use something that is closed source. I am always coming across stuff where I think "I could fix this. No wait, its closed source."

**Comment by brandonkelly** [comment]
GPL would require all plugins and websites built with Craft to also be GPL, and released publicly. So that’s a non-starter :)

> I am always coming across stuff where I think "I could fix this. No wait, its closed source."

Craft isn’t closed _source_ – all the source code is right here on GitHub, and the [license](https://github.com/craftcms/cms/blob/develop/LICENSE.md) is pretty unrestrictive as proprietary software goes. Want to change something? Fork it. Want to push the change back up to us? Submit a PR. Just like any other (F)OSS project.

**Comment by frob** [comment]
> GPL would require all plugins and many websites built with Craft to also be GPL, and released publicly. So that’s a non-starter.

This is an incorrect assumption. If this where true, no site could be built on WordPress or Drupal. Currently whitehouse.gov is built with WordPress, but you cannot download the source code. GPL code can be used with non-GLP code and any entity can use GPL code (so long as they are not redistributing it) without releasing the source code. Plugins don't have to be GLPed either, though the marketplace economy might complicate things.

> Craft isn’t closed source – all the source code is right here on GitHub, and the license is pretty unrestrictive as proprietary software goes. Want to change something? Fork it. Want to push the change back up to us? Submit a PR. Just like any other (F)OSS project.

Yes, don't get me wrong. That statement didn't refer you this project. Trust me that I would be submitting PRs if I was using CraftCMS. I am a little hesitant to recommend Craft with a custom open source license. Even if this was a MIT+ license that added the license and payment, much like React used to have. I am hesitant because the standard open source licenses have been tested. 

Please don't take this a harsh criticism. From what I have seen, CraftCMS is well done and I was stoked to see the source available for download and PRs being accepted.

**Comment by ryanpcmcquen** [comment]
> GPL would require all plugins and many websites built with Craft to also be GPL, and released publicly. So that’s a non-starter :)


@brandonkelly, have you considered the MPL license?

**Comment by brandonkelly** [comment]
@ryanpcmcquen No but that’s an interesting one!

**Comment by Mu9tafa-Online** [comment]
Any news on this? 😅

**Comment by glenux** [comment]
Ok, from what I understand so far, CraftCMS is not (yet) open source, so who has the intellectual property for the resulting mix of all that contributed code & PRs ?

**Comment by brandonkelly** [comment]
It’s commercial open source, just not FOSS (yet anyway). All contributed IP is owned by us, per the [contributing notes](https://github.com/craftcms/cms/blob/develop/CONTRIBUTING.md).

**Comment by mgifford** [comment]
@brandonkelly what do you gain by owning all of the contributed IP? How does that fit into your business model? 

I'm a fan of the GPL, but if you are releasing the code and wanting to scale the project with more users and developers, it just seems that owning the IP is just a default condition that you've fallen into.  

Maybe I'm wrong. You'd absolutely want to hold onto the branding and manage control of the repo.  None of that is in question as far as I'm concerned.

**Comment by brandonkelly** [comment]
@mgifford The right to do what we want with the code w/out needing to get permission from each contributor. That’s the way all proprietary-licensed software works.

If we are ever able go FOSS with Craft ([working on it](https://twitter.com/brandonkelly/status/1279121533076746240)), that will no longer be the case.
