### ISSUE TITLE
Minimum number of rows in Matrix fields

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#850]
> Created by: Jérôme Coupé (jercoupe@gmail.com) on 2015/03/12 05:21:11 +0000
> Votes at time of UserVoice import: 35

-----------------------------------

Its is very nice to be able to specify the max number of rows in a Matrix but I think specifying the minimal number of rows would be interesting too in many cases.

By combining those two settings you would be able to create Matrix fields needing 3 and only 3 components. That would give you tighter control over your content model / data structure while letting users benefit from the reordering / add / delete capabilities of Matrix.

Use cases:

1. a simple grid of icons, titles and text. If your wide screen layout calls for three items or more, there is currently no way to enforce that with Matrix

2. when building more complex data grids (2 items, 3 items, 4 items per "row") having such a parameter would allow for a simpler data structure while preserving the reorder / add / delete and configure options currently given by Matrix

**Comment by brandonkelly** [comment]
To improve the AX, Matrix fields with less than the minimum should get placeholder blocks instead of the Add Block buttons. Placeholder blocks just show a list of the available block types, and when you choose one, it will become that block type. (Placeholder blocks will reappear if a block is deleted, as well.)

If a Matrix field has both Min Blocks and Max blocks set to identical values, then the Add Block buttons should never be shown.

**Comment by dotmeta** [comment]
Would love this feature as well.

**Comment by Laslo89** [comment]
Are there any updates on this feature. I would love to have it. I run into this need quiet frequently.

**Comment by brandonkelly** [comment]
Just added it for Craft 3, albeit without my "placeholder blocks" idea.

Unfortunately I couldn’t add it for Craft 2, because in Craft 2, custom field validation only gets triggered if the field value is not empty. Assumption being that if you don’t want an empty value, you should mark the field as required, which is a fair assumption in most cases, but not if the field happens to have a “Min Blocks” setting, which should effectively make the field required everywhere it’s used.

**Comment by davidhellmann** [comment]
@brandonkelly 

> To improve the AX, Matrix fields with less than the minimum should get placeholder blocks instead of the Add Block buttons. Placeholder blocks just show a list of the available block types, and when you choose one, it will become that block type. (Placeholder blocks will reappear if a block is deleted, as well.)

> If a Matrix field has both Min Blocks and Max blocks set to identical values, then the Add Block buttons should never be shown.


This feature is not implemented right now? 
When I set `min` and  `max` to `1` it would be soooooooooooooooo nice to show the Fields instantly.

**Comment by brandonkelly** [comment]
@davidhellmann I suppose we could do that if there’s only one block type.

**Comment by brandonkelly** [comment]
And done: https://github.com/craftcms/cms/commit/2c2ea355

Also: https://github.com/craftcms/cms/commit/86d4dbe4

**Comment by davidhellmann** [comment]
@brandonkelly 
Nice try :P
Now just to fix the min max 1 bug on existing Fields :D

**Comment by narration-sd** [comment]
@davidhellmann:  shake of head hear, about  your approach.

Brandon  & co, and the community here, do and deserve better, no?

**Comment by davidhellmann** [comment]
@narration-sd don't know what you mean and my last commend was a bit l fun.
The update from yesterday has an Bug when I set Min Block to 1 and Max Blocks to 1.
When I change that for existing Matrix Fields > The Matrix Field is completely empty.

**Comment by brandonkelly** [comment]
lol, no worries @davidhellmann ! @lukeyouell created a dedicated issue for this too (#2353), and it's fixed for the next release. (FFR please create new issues for new bugs 🙏 thanks!)
