### ISSUE TITLE
Native markdown field for Craft

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#854]
> Created by: Jason McCallister (themccallister@gmail.com) on 2015/03/20 17:34:31 +0000
> Votes at time of UserVoice import: 31

-----------------------------------

It would be absolutely excellent if Craft included a native Markdown field when creating fields.

There are a lot of libraries and standards for Markdown but this is a nice one: http://commonmark.thephpleague.com

Or even better, supporting Github flavor markdown would be ideal...

**Comment by proimage** [comment]
I absolutely love how Github handles posting in Markdown. By providing the familiar WYSIWYG buttons, people don't have to go hunting for those wily Markdown docs.

Also, not only is the result of clicking the buttons is functional (does what the user wants), but it's educational as well, since the Markdown code to achieve the formatting the user just asked for is _right there_ for them to see and—hopefully—learn from.

Finally, a preview function, whether in a separate tab like Github, or a parallel pane like [this interface](https://jbt.github.io/markdown-editor/), is essential IMHO. Craft's Live Preview is marvelous and all, but there's no reason to not provide an even more instant feedback for Markdown formatting.

**Comment by brandonkelly** [comment]
Even better – we are working on a new editor field type powered by [CKEditor 5](https://ckeditor5.github.io/) which has [Markdown support](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/api/markdown-gfm.html). So clients won’t even need to know they are editing Markdown; it will just look like any other rich text editor.

**Comment by mashaal** [comment]
any word on this @brandonkelly?

**Comment by brandonkelly** [comment]
@mashaal We’ve got our [CKEditor](https://plugins.craftcms.com/ckeditor) plugin in the plugin store as a beta, but isn’t currently being maintained and doesn’t have the Markdown stuff yet. It’s still something we want to get to, but we’ve had bigger fish to fry.
