### ISSUE TITLE
Craft could check to make sure POST requests aren't missing fields due to insufficient max_input_vars

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#876]
> Created by: Michael (michael@michaelrog.com) on 2015/03/11 15:06:07 +0000
> Votes at time of UserVoice import: 20

-----------------------------------

Frequently, when I'm editing a complex Matrix field with many block types, I'll run up against PHP's max_input_vars limit, and some fields will simply be lost to the ether.

This can be really frustrating, as it isn't always immediately apparent that some fields were displaced. (For example, if I add a block type in the middle of the list, fields on the block types at the end of the list may simply vanish. I'm not paying attention to those fields, however, so I don't realize it until hours later, when I start seeing "missing property" errors.)

It'd save a lot of grief if Craft could check to make sure POST requests are complete — i.e. that they contain all of the expected fields.

The simplest way I could envision to do this would be for Craft to include two extra hidden fields — one as the first field in a form, and one as the last — and expect that if the first is present, the last should also be present and should contain a matching value.

If Craft detects that some fields may be missing, it could decline to process the request and show me a warning urging me to increase the `max_input_vars` limit.

**Comment by karlmacklin** [comment]
We've suffered from this issue both while editing complex field types, and when clients are saving pages with much content.
In both cases, content/settings are lost without a warning.

PHP's implementation of handling exceeding of max_input_vars is not the best, as it throws an E_WARNING that you specifically have to search for in the code. So I can confirm it's not a super easy workaround.

See example here: https://stackoverflow.com/a/21601349/1049287

Angrybrads suggestion sounds good to me, even though there might be some other way to handle it. In any case, it's a serious issue since content is lost without warning.

Increasing max_input_vars helps, but is a bandaid at best and doesn't bring back already lost content.

Craft 3 seems to work the same way in this regard vs Craft 2.

**Comment by brandonkelly** [comment]
@karlmacklin Thanks for posting that SE post out - it’s a tiny bit unreliable but certainly a lot better than nothing! Just implemented for the next Craft 2 & 3 releases.

**Comment by karlmacklin** [comment]
Why thank you good sir!
