### ISSUE TITLE
Ability to batch edit field values on multiple entries/assets at once

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#893]
> Created by: Emyr Thomas (emyr.thomas@gmail.com) on 2016/01/10 23:16:08 +0000
> Votes at time of UserVoice import: 15

-----------------------------------

It would be a huge time-saver if Craft has the ability to edit multiple items at once. Currently, you can bulk delete elements on the Entries index listing in the Control Panel by selecting multiple entries and selecting Delete from the Actions dropdown, but it would be very useful to change the values of any fields the selected entries have in common.

As an example, I have added an Artist (Element) field to Assets in my project. When I bulk upload a ton of images, it would be great if I could select multiple assets and edit the Artist field for each in one go.

WordPress has an implementation of this kind of functionality, see https://en.support.wordpress.com/posts/edit-posts-screen/#bulk-edit

**Comment by blacksaltstudio** [comment]
This would be amazing!!!!!! +1

**Comment by j-greig** [comment]
Would love this feature - for Commerce products too!

**Comment by RitterKnightCreative** [comment]
Had a client asking for this today.  Will try the plugin but this definitely needs to be in core!

**Comment by brandonkelly** [comment]
Added to the 3.3 milestone.

**Comment by blacksaltstudio** [comment]
Will this be for Assets as well as Entries @brandonkelly ?

**Comment by brandonkelly** [comment]
Yeah we would implement it for all element index pages.

**Comment by Mosnar** [comment]
FWIW, we through together a free plugin that does bulk editing for arbitrary elements with certain fields: https://github.com/venveo/craft-bulkedit/

@brandonkelly Here are some gotchas I ran into while developing this, hopefully it saves you some time!
- Validation gets funky very quickly, especially with the introduction of our "strategies" feature. For example, you can "subtract" the selected elements from an element relation field, which can result in the field no longer validating if there's a minimum requirement. You don't know this is going to be an issue until the element is being edited in the queue.
- I had to scrap custom field and matrix support altogether, as there wasn't a good/clean way of handling when a field tried to reference the element it's on in its template. Most basic custom fields were fine, but I recall having issues with the Typed Link Field plugin. I tried "mocking" an element for the field, but quickly abandoned that route. 
- Non-custom fields (element properties) are actually trickier to handle than custom fields since you can't generate the inputs dynamically (for example, how do we render the author vs the post date?). A template would need to be supplied for each property.
- Field layouts were pretty funky to work with since they're stored in different ways per element. I introduced the concept of **Element Processors** to handle determining where to find field layouts:
https://github.com/venveo/craft-bulkedit/tree/master/src/elements/processors
- There wasn't a great way to determine when a job was completed in the queue in the CP, so I could automatically refresh the element index when the job progressed/finished. This leads clients to thinking the plugin doesn't work or multiple jobs in the queue from multiple attempts
- Paginated element indexes don't maintain previous selections, so even with batch editing, you're bottlenecked by the number of results on the current page. (Related: #4603)

**Comment by MaximilianSchwarz** [comment]
> Yeah we would implement it for all element index pages.

Any news for this feature?

**Comment by brandonkelly** [comment]
Just changed the milestone to Craft 4, where this will fit nicely with some other element index improvements we’re going to be making.

**Comment by lexislav** [comment]
Would be great if the entry title could be batch edited as well. It would come handy at least for assets (image titles).
