### ISSUE TITLE
Streamed cpresources are not browser cached

### ISSUE THREAD

**Issue by andygrn** [craftcms/cms#9140]
### Description

We're running Craft in a load-balanced environment, where cpresources are not publically accessible, and therefore Craft is streaming them on-demand (as outlined in https://craftcms.com/knowledge-base/configuring-load-balanced-environments#cpresources-folder).

However these files are being served with anti-cache headers (e.g. Expires: 0), so every file is being re-downloaded on every CP request. Obviously this leads to very slow CP page loads compared to a directly-served copy of the site.

Cpresource URLs are already versioned so presumably this isn't intended behaviour.

### Steps to reproduce

1. Run Craft in an environment without public /cpresources access.
2. Load CP pages with a network inspector, see each cpresource downloaded every time.

### Additional info

- Craft version: 3.6.17
- PHP version: 7.4.14
- Database driver & version: Mysql 5.5.5
- Plugins & versions: craftcms/aws-s3 1.2.11, craftcms/redactor 2.8.7

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by jmortlock** [comment]
Hi @brandonkelly 

I'm not entirely sure this is a safe change as its likely for those that are running in a Load Balanced environment are also deploying with a rolling type mechanism, i.e. During a craft update there could be 2 different versions of Craft serving assets at the same time.

Due to the ability for assets to be looked up in the database its conceivable for an old node during this deployment phase to serve up its old (outdated) version of an asset via the newly published hash, which after this change will get cached at the client.

This is not a new issue but due to the non-client cached behaviour it is relatively short lived (minutes) until all nodes settle on the new version.

**Comment by brandonkelly** [comment]
@jmortlock Any time any assets change, they get republished to a new URL, so this change won’t have any effect on updates.

**Comment by jmortlock** [comment]
Maybe i misunderstand the whole cpresources caching mechanisim, but from my understanding old nodes will still happily publish assets that match that new URL, as the Hash / Source is stored in the database as per changes made in this PR https://github.com/craftcms/cms/issues/2500

For example The new server say Craft 3.8 publishes a new jquery Asset, this is now the hash stored in the database, however during a rolling update with say Craft 3.7 / 3.8 running concurrently the older version will happily accept the new hash value, read the source from the database and publish up its version of the asset using the newer hash value.

**Comment by brandonkelly** [comment]
@jmortlock Sorry yeah, you’re right. I thought we were verifying that the requested file hash matched the newly-published one, but we weren’t. Just fixed that as well, so going forward the resource request for an unknown hash would give you a 404.

**Comment by jmortlock** [comment]
Thankyou @brandonkelly much appreciate you looking into this and providing a fix, look forward to the next release :)
