### ISSUE TITLE
users with the "Assign User Groups and Permissions" permission should not be able to grant permissions that their creator did not grant them

### ISSUE THREAD

**Issue by takobell** [craftcms/cms#915]
> Created by: brad (brad@pixelandtonic.com) on 2015/03/06 19:07:45 +0000
> Votes at time of UserVoice import: 11

-----------------------------------

Currently the "Assign user groups and permissions" permissions in an all or nothing thing.  In the context of creating a new user, it should be aware of the _existing_ user's permissions (or lack of) and should impose those same restrictions on the new user as well

**Comment by jordanlev** [comment]
This is a *huge* problem for us. We paid the extra $100 for the pro version solely for the user management features, but this is a pretty glaring oversight that has already bitten us a few times.

**Comment by tidy** [comment]
This is an issue for us as well. The Client licence with just one client login usually suffices for us so we hadn't encountered this until now, but I had assumed that with the Pro licence, clients could manage users at just their own level. As it stands, I don't think we can offer clients the ability to manage user permissions, because it's just too risky.

**Comment by tidy** [comment]
Many thanks for fixing this Brandon - really appreciate it!

**Comment by brandonkelly** [comment]
@tidy 👍 

Would love to get some feedback on #2087 as well. Similar bug (for user group assignment rather than permission assignment), but there isn’t a clear cut solution like there was with this one.

cc @takobell @bartrylant @tjdraper @stevenvandemoortele @kgrote @jordanlev

**Comment by smockensturm** [comment]
Please see my comment on [#2087](https://github.com/craftcms/cms/issues/2087)
