### ISSUE TITLE
Duplicate or copy an entry from entries page

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#923]
> Created by: Anonymous (chrstblt@gmail.com) on 2015/11/24 15:54:53 +0000
> Votes at time of UserVoice import: 10

-----------------------------------

There is an option to duplicate an entry by editing and then "Save as", but that's not possible from the UI in the entries (overview) page. It would be nice to select two or three entries, click duplicate, and then move them to the desired plage. Optionally, a modal could pop up with the question "Where would you like the duplicates?" (duplicate in current parent; duplicate in different parent)

**Comment by engram-design** [comment]
+1 on this, and I think it could be as simple as an element action for Duplicate/Clone/Copy. A lot of the time, we advise clients to use the "Save as a new entry" for things, but they almost always forget to make changes and overwrite things - which is a bit of a disaster!

**Comment by gojira32** [comment]
https://d.pr/i/yOEKX9

**Comment by brandonkelly** [comment]
It has been possible to bulk-duplicate entries from the Entries index page since v3.0.30, so going to close this.

<img width="370" alt="An Entries index page with three entries selected, and the action menu expanded to reveal a “Duplicate” option" src="https://user-images.githubusercontent.com/47792/68025297-a9ad8e00-fc69-11e9-8a2f-27ba52a75996.png">

**Comment by gojira32** [comment]
@brandonkelly It'd still be good to be able to duplicate within an entry / product.

It's just that the UX is very dicey at the moment.

It is very easy to:
- Accidentally click "Save" instead of clicking the drop down arrow
- Accidentally click "Save & continue editing" instead of "Save as new product"

As @engram-design suggests, a dedicated "Duplicate" or "Clone" button would make things a lot easier.

**Comment by engram-design** [comment]
@brandonkelly Good call, actually forgot about this! This was actually more related to products, so have raised this for Commerce - https://github.com/craftcms/commerce/issues/1107

**Comment by bossanova808** [comment]
I'll chime in and agree the UI is poor in this area in general.  

I think literally everyone in our office has at some point yelled expletives across the office because of this system of 'save' vs 'save as new entry' in the drop down.  Just far, far too easy to forget you're working on something new.  We tell everyone 'first change the slug, then save as new entry, and THEN edit' - but it is super error prone.  (Entries, products, whatever).

Element actions being hidden under the tiny cog arrow is just generally a bit crappy for discoverability too - I'd really like to see more dedicated buttons for common actions, like e.g. duplicate - and the cog should be saved for rarer or more dangerous things that should be a bit more hidden.

**Comment by brandonkelly** [comment]
@bossanova808 what would you expect a “Duplicate” button to do, if you’ve already started editing content?

**Comment by bossanova808** [comment]
Well the duplicate button I mentioned was instead of being hidden under the element action cog so one would not have started editing at that point, right?

But inside the entry I think simply two buttons, save and save as new, would make the flow much more obvious those options being hidden under a drop down.  (The button could be labelled duplicate until any edits are made, then change to save as new, maybe). 

My general feeling is the craft ui is a bit _too_ clever/neat ... There's a lot of functionality but it tends to be hidden under cogs and drop downs so editors tend to miss it.  

Eg for months I used Commerce without realising you can change order status off the main orders index cog thing.  I'm dumb enough to be a great example of issues like that it seems!  But actually no order processor has found that on their own to date.  (They all expect it to be an action (drop down menu) on the actual status itself in this case).

I don't know how often you sit with new editors using craft and watch them try and do stuff with only relatively basic instruction, but I find that super useful to see where the common issues are...

**Comment by gojira32** [comment]
Agree with @bossanova808 on this.

Our customer service reps who are in and out of the Orders overview and order detail view have similar feedback after being live for a couple of weeks.

They've gotten the hang of things but the way things are laid out are a bit too atypical compared to Magento, Shopify and BC and things are a bit too hidden.
