### ISSUE TITLE
Allow users with permissions to administrate users to manually activate users

### ISSUE THREAD

**Issue by angrybrad** [craftcms/cms#942]
> Created by: Dylan Jones (info@d13creative.co.uk) on 2015/04/10 15:45:41 +0000
> Votes at time of UserVoice import: 8

-----------------------------------

The option to either "Copy activation URL" and "Activate account" are not available for non-admins who have been granted permissions to administrate users.

I don't know whether this is by design or it is a bug but it has caused some confusion.

My client needs the ability to be able to manually activate accounts so in order to enable her to do this the only option I have is to give her full admin access to the control panel, which is not ideal.

**Comment by cliveportman** [comment]
Please. I can understand Brandon's view with regards to erring on the sie of caution but if the alternative is we have to give clients full admin access then the decision is actually making things worse.

Can it be made it a permissions option that's not selected automatically when hitting 'Select All' for users?

**Comment by brandonkelly** [comment]
@cliveportman We’re definitely not going to add it to Craft 2 at this point, but a plugin could add it as an option using the [addUserAdministrationOptions](https://craftcms.com/docs/plugins/hooks-reference#addUserAdministrationOptions) hook.

**Comment by TomDeSmet** [comment]
Just noticed this at the end of a very large project which relies on this to activate new members. Major bummer! I understand the security risks, but wouldn't it seem likely that a client needs to be able to decide who gets access to his website's walled off content?

**Comment by billythekid** [comment]
I've thrown together a plugin to handle exactly this: https://github.com/billythekid/activateusers

**Comment by aarmitage** [comment]
I’d like to add our voice to this as well please. An option to enable this for a specific member group would be really useful.

Going beyond this, accepting the security argument, an extra option for ‘login as member’ would also be helpful for one of our use cases, but appreciate the extra concerns this might add.

**Comment by john-henry** [comment]
+1 For this. 3 projects recently where this became a massive issue for client

**Comment by jwmatlock** [comment]
+5 Adding to this. We just launched a Craft Commerce project and not having this ability is a customer support nightmare.

**Comment by brandonkelly** [comment]
The reason this isn’t currently possible is because the ability to manually activate users would introduce a new permission escalation vector.

1. Admin user creates new user account (“User A”) with various permissions including “Edit users” (or perhaps even a new admin account).
2. A user with “Administrate users” permission (“User B”) can now copy User A’s activation URL, go to it, and set their password / activate their account.
3. Now User B can log into User A’s account with the password they just set, edit their own account (User B), and grant themselves whatever permissions User A has (or grant themselves Admin status if User A is an admin).

That said, a similar vector already exists, via the “Change users’ emails” permission.

1. Admin user creates new user account (“User A”) with various permissions including “Edit users” (or perhaps even a new admin account).
2. A user with “Change users’ emails” permission (“User B”) can now edit User A’s email to an email address that they control, and then resend an account activation email, or a password-reset email, etc., and set their password that way.
3. Now User B can log into User A’s account with the password they just set, edit their own account (User B), and grant themselves whatever permissions User A has (or grant themselves Admin status if User A is an admin).

Considering that, I’m thinking maybe we should rename the “Change users’ emails” permission to “Activate user accounts and change emails”; there won’t be a significantly increased risk of permission escalation for users that already have that permission.

**Comment by brandonkelly** [comment]
This will be resolved in Craft 3.1 (currently in Dev Preview).

- The old “Administrate users” permission has been renamed to “Moderate users”.
- The old “Change users’ emails” permission has been renamed to “Administrate users”, and now comes with the ability to activate user accounts and reset their passwords.

**Comment by bytebrain** [comment]
This is broken on my Craft CMS 3.3.0.1 Pro version. When a pending user has already set a password, the option "Copy activation URL" is still available in the CP. 
The `$user->password` in `vendor/craftcms/cms/src/controllers/UsersController.php` on line 648 is empty, but the user record in the db has a password set.

**Comment by brandonkelly** [comment]
@bytebrain How did the user have a password set without activating their account?

**Comment by bytebrain** [comment]
@brandonkelly Through the frontend, with a registration form.

**Comment by brandonkelly** [comment]
@bytebrain Duh, of course. Just fixed that for the next release, thanks for pointing it out.
