### ISSUE TITLE
Can't add .xsd files to extraAllowedFileExtensions

### ISSUE THREAD

**Issue by darylknight** [craftcms/cms#9600]
### Description
I'm in the middle of importing some client assets from the old site to Craft. I've added this to general.php:

`'extraAllowedFileExtensions' => 'xml, xsd',`

XML is now showing in the list of "Restrict allowed file types", but XSD files aren't. Is this intended? Should i tell them they can't add those files to the new site?

1. Add `'extraAllowedFileExtensions' => 'xml, xsd',` to general.php
2. Try to add an asset field that restricts allowable file types
3. XSD is not in the list

Craft 3.7.3.2

Self reference: BoG - IR

**Comment by lenvanessen** [comment]
@darylknight it seems that it's not merging the extraAllowedFileExtensions into the list of supported extensions for the Assets field: https://github.com/craftcms/cms/blob/develop/src/helpers/Assets.php#L300-L319

Not sure if by design intended or not, but if you put the xsd into extraAllowedFileExtensions, and don't limit the Assets field itself to any specific file type (by leaving the "Restrict allowed file types" unchecked), I think you should just be able to upload the files and select them.

**Comment by mmikkel** [comment]
Assets fields aren't possible to restrict by extensions, only by _file kinds_. Each file kind can represent one or several extensions; for example, the file kind "Image" includes the `jpg`, `gif`, `png` etc extensions.

Craft has a built-in file kind for XML (which shows up if you add `xml` to `extraAllowedFileExtensions`) but that doesn't include the `xsd` extension. So, in order to restrict fields to XSD files you'll need to add a new file kind using the [`extraFileKinds`](https://craftcms.com/docs/3.x/config/config-settings.html#extrafilekinds) config setting (in addition to adding `xsd` to `extraAllowedFileExtensions`):

```php
'extraFileKinds' => [[
    'label' => 'XSD',
    'extensions' => [
        'xsd',
    ],
]],
```

**Comment by darylknight** [comment]
That makes sense, thank you! The only reason I filed it as an issue if that if you add XML as an extra file kind, it suddenly appears in the list of file kinds you can restrict by. XSD doesn't appear in that list, but this makes sense. @lenvanessen 's point also stands; it works fine if you don't restrict it at all.
