### ISSUE TITLE
Assets are not relocated after entry has been saved

### ISSUE THREAD

**Issue by owldesign** [craftcms/cms#9619]
### Description
My assets are not being moved out of Temporary Uploads folder after the element has been saved and a dynamic folder based on the {slug} has been created on the volume.

I tried this on all 3 of these: _DigitalOcean Spaces_, _Amazon S3_ and _Local Folder_. All created the dynamic folder based on entry {slug} but assets never relocated after save. Looking at the entry page (frontend) I am unable to get the asset urls to display them. However, they do display in the CP edit entry page.

**Note**: At some point I played around with changing the **Temp Uploads Location** setting and I noticed that assets got relocated to the correct dynamic folders. However, the issue is back when I start creating new entries.

### Steps to reproduce

1. My asset fields have a dynamic path that create a subfolder based on "{slug}"
 
<img width="517" alt="CleanShot 2021-07-21 at 16 28 28@2x" src="https://user-images.githubusercontent.com/438764/126572391-2c88f194-6606-4551-bb64-603782aed164.png">

2. Those dynamic folders get created based on the {slug} after the element is saved.

<img width="503" alt="CleanShot 2021-07-21 at 16 28 56@2x" src="https://user-images.githubusercontent.com/438764/126572412-1c1772d7-d00e-4b29-b345-5b8a396ead8e.png">

3. Assets never move out of Temp location to the appropriate final folder. 

<img width="606" alt="CleanShot 2021-07-21 at 16 29 43@2x" src="https://user-images.githubusercontent.com/438764/126572459-110b1cc9-e3f6-490a-a440-418c5c7f9014.png">

### Additional info

- Craft version: 3.7.4
- PHP version: 8.0.8

**Comment by andris-sevcenko** [comment]
I'm unable to reproduce this. Are you seeing any errors in the log files?

**Comment by owldesign** [comment]
Ahh, no errors in the logs. 

Another note is that if I first save the entry without uploading any assets, then try adding assets, it goes into the correct folder as expected. 

I'll continue troubleshooting, maybe there is something obvious that I'm not seeing.

**Comment by andris-sevcenko** [comment]
If you have no luck, perhaps you can shoot over the credentials for CP access over email to support@craftcms.com and reference this issue?

**Comment by moteey** [comment]
I have the same issue (also v3.7.4). I'm using AWS S3 plugin (v1.2.12) to create an upload volume.

Some additional details:

- When I upload to a field for the first time, the file doesn't get uploaded to S3 (stays in temp).
- When I remove the file and re-upload on the same field, it gets uploaded to S3 immediately.

**Comment by moteey** [comment]
After further testing, here are my findings:

- For me, this only seems to happen with the uploads inside of the **matrix** fields
- Upload fields outside of matrix fields seem to work fine.

**Error scenario:**

1. Add a new block (with an upload field) inside of matrix field
2. Upload a file to the new upload field
3. Image does not get uploaded to S3

**Success scenario 1:**

1. Add a new block (with an upload field) inside of matrix field
2. Save the entry before uploading to the new field
3. Re-open the entry
3. Upload a file to the upload field that was added before saving the entry
4. Image gets uploaded to S3

**Success scenario 2:**

1. Upload a file to an upload field outside of the matrix field
2. Image gets uploaded to S3

**Comment by skoften** [comment]
Same issue here. We're using assets in Matrix fields, but the entry has to be saved first WITH an empty matrix field, before assets end up in the right folder. If the entry (and empty matrix field) is not saved before the upload, the asset ends up permanently in the temporary folder.

**Comment by brandonkelly** [comment]
Was able to reproduce this, and just got it fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.4"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.5 is out now with the fix.

**Comment by skoften** [comment]
@brandonkelly 3.7.5 fixed the issue, but we're experiencing the same issue on Draft entries.

So when you create an entry, save it, create a draft version, you have to create a matrix field first, save the entry again, so the matrix field has an **ownerId** and the files are not uploaded to the temporary folder.
 
When you don’t save the newly added matrix field first, the file are getting pushed to the temporary folder permanently.

**Comment by brandonkelly** [comment]
@skoften To clarify, are you saying they don’t get moved even once the draft is published?

**Comment by skoften** [comment]
@brandonkelly when the draft is "applied", the asset is indeed moved the the target location. That's a good thing, but, when the assets are in the temporary folder we can't seem to preview the assets on the frontend with the preview button; only when the assets are in the target folder they show up properly. We need to keep working in the draft version though, and be able to preview it of course. 

It happens with every new matrix block by the way. For now we can "solve" it by creating the element, save the draft, and upload the asset. Then it ends up in the target folder instead of the temporary. When it's not saved before uploading the asset, it ends up in the temp. folder, which results in not being able to preview the newly added content.

**Comment by brandonkelly** [comment]
@skoften OK, that’s working as expected then. Assets fields don’t bother relocating the related assets to the proper location until the entry is actually saved as a normal entry, not a draft.

You can fix the visibility issue by creating a dedicated “Temp” volume with a base URL, and then going to **Settings** → **Assets** → **Settings** and selecting it from the **Temp Uploads Location** field.

**Comment by joshwalsh** [comment]
I'm still seeing this same issue on 3.7.16.   I have an asset with a dynamic path just as @owldesign has setup, and an asset block in a matrix field.   When saving the entry (published, not draft) the assets are stuck in the temporary uploads folder.

I think my variation of this issue may be related to the fact that my asset has an additional required field (textAlternative), and the matrix block is set to enforce validation of the asset when saving the entry.   When I save the entry (including the required textAlternative field -- they are valid) the posts publishes successfully, but the asset does not move from temporary uploads.

As a result, the images are broken in the rendered output,   Also, the content entered into the required textAlternative field is lost since they are never assigned the proper asset store where the field is defined.

No errors are thrown in the process, only a broken image output in the template.

The issue is fixed by moving the files into the correct asset store location manually, and then re-entering the textAlternative field contents.

**Comment by KarlBishop** [comment]
I'm still seeing this issue occasionally on Craft 3.7.34

E.g. one of my Assets fields within a Matrix block has Default Asset Location: `{owner.section.handle|kebab}`

After adding a couple of blocks to an existing Entry and saving, I had one image stored in the proper place but the other one stayed in the Temp Uploads Location, in a folder like `user_1`.

**Comment by brandonkelly** [comment]
@KarlBishop Do you mind sending your database backup and Composer files into support@craftcms.com? We can look into it from there.

**Comment by KarlBishop** [comment]
@brandonkelly Trying to get approval to share the data 😁 I'll email through when I can hopefully, thanks!

**Comment by ademers** [comment]
@KarlBishop Did you get this resolved on 3.7.34? I'm seeing something similar on 3.3.37. Thanks!

**Comment by KarlBishop** [comment]
@ademers I'm afraid I hit some walls with data sharing, so haven't been able to send anything to Craft Support for them to investigate yet 😞

**Comment by CMeldgaard** [comment]
@brandonkelly I seem to have narrowed down where the issues happens.

These lines: https://github.com/craftcms/cms/blob/076428986e1282c3ebc54e1d706e646c908146d1/src/fields/Assets.php#L564-L575

If the assets field isn't set to be a `useSingleFolder`, it will try to find assets where the volumeId is `:empty`, but it won't find any assets, because the asset we want to move, is associated to an volume - our temporary folder volume.

If i set the assets field to be `useSingleFolder` or comment out this line:
https://github.com/craftcms/cms/blob/076428986e1282c3ebc54e1d706e646c908146d1/src/fields/Assets.php#L573

then the assets gets moved from the temporary folder, to the correct volume folder. This also explains why switching back to `In the local temp folder` solves the problem, since the assets volumeId will be empty in that case

**Comment by brandonkelly** [comment]
@CMeldgaard Aha! The code overlooked that temp assets could have a volume ID if the “Temp Uploads Location” asset setting had been set to a volume.

Thanks to your pointer, this is now fixed for the next release 🎉

**Comment by brandonkelly** [comment]
Craft 3.7.39 is out with that fix.
