### ISSUE TITLE
Unsupported site – craft\errors\UnsupportedSiteException

### ISSUE THREAD

**Issue by loqus** [craftcms/cms#9664]
### Description
After upgrading to Craft Pro 3.7.7 some users reporting a 
Unsupported site – craft\errors\UnsupportedSiteException upon editing an existing entry.

Attempting to duplicate an element in an unsupported site.
This error does not come up as site owner, but does happen to other people with admin rights.

It seems to stumble over 
```php
// This is a new block, so duplicate it into the derivative owner
$elementsService->duplicateElement($canonicalBlock, [
    'canonicalId' => $canonicalBlock->id,
    'ownerId' => $owner->id,
    'owner' => $owner,
    'siteId' => $canonicalOwner->siteId,
    'propagating' => false,
]);
```
in vendor/craftcms/cms/src/services/Matrix.php at line 1013

The users are trying to edit an existing entry in another language that is not live yet

### Steps to reproduce

1.
2.

### Additional info

- Craft version: Craft Pro 3.7.7
- PHP version: 7.4.21
- Database driver & version: MySQL 5.5.68
- Plugins & versions:

**Comment by brandonkelly** [comment]
Any chance you can send over a database backup and your `composer.json` + `composer.lock` files to support@craftcms.com?

**Comment by jing-liu-anne** [comment]
I have the same issue when I use draft.

**Comment by jing-liu-anne** [comment]
@brandonkelly 

I have the same issue when using a draft after upgrading to Craft Pro 3.7.0.

**Steps to reproduce:**

1. Starts edits from Current and save as a draft.
2. Starts edits on the same field from Current and publishes them.
3. Switch to the draft version, the issue will appear.


https://user-images.githubusercontent.com/88373506/128153257-bd9aa471-0c9c-4805-8b29-ebb7467d7a06.mp4



I found it only happened on existing entry (I created them on Craft Pro 3.6.0.1 version or before). when I create a new entry now, the issue will not happen.

Thanks in advance!

**Comment by brandonkelly** [comment]
@jing-liu-anne I just tried exactly the same steps locally and didn’t get the error. If you are seeing this on 3.7.7, please send your database backup and `composer.json` + `composer.lock` files into support@craftcms.com, and I can try to reproduce with your site.

**Comment by brandonkelly** [comment]
The OP issue ended up being due to entries that weren’t fully saved across all the sites they were supposed to support (likely do to a “Propagating entries” background job that wasn’t able to complete, when new sites were enabled for the section or when its Propagation Method changed.

The fix was to run the following commands:

```bash
> php craft resave/entries --section=sectionHandle --site=workingSiteHandle
> php craft resave/entries --section=sectionHandle --site=workingSiteHandle --drafts
> php craft resave/entries --section=sectionHandle --site=workingSiteHandle --provisional-drafts
```

**Comment by rob-baker-ar** [comment]
@brandonkelly I'm seeing this same effect with a very slightly different trigger: 

_(on Craft 3.7.5 with an entry created when still in Craft 3.6.x)_

Very soon after upgrading to 3.7.5 a single entry within a structure section was switched to a newly created Entry Type. In terms of contained fields, the new entry type is the same except a single field: We swapped a content-builder style of Matrix field (`body`) for one with the same fields inside, except named `translatableBody` and with a different propagation method: old field has "Save blocks to all sites the owner element is saved in", new field has "Only save blocks to the site they were created in".

The odd thing is that admin users are able to view the affected entry, but other types of users are not and get the above exception. i.e. it does not happen while saving, it's something that happens when Craft ought to be reading from the database.

Trace indicates it's while saving a Matrix block (an automatic merge of something into it?):

```
2021-08-09 12:23:20 [-][90046][bledc7u654ugl5ig2596v4v0qf][error][craft\errors\UnsupportedSiteException] craft\errors\UnsupportedSiteException: Attempting to duplicate an element in an unsupported site. in [...]/vendor/craftcms/cms/src/services/Elements.php:1156
Stack trace:
#0 [...]/vendor/craftcms/cms/src/services/Matrix.php(1009): craft\services\Elements->duplicateElement()
#1 [...]/vendor/craftcms/cms/src/fields/Matrix.php(1043): craft\services\Matrix->mergeCanonicalChanges()
#2 [...]/vendor/craftcms/cms/src/base/Element.php(3967): craft\fields\Matrix->afterElementPropagate()
#3 [...]/vendor/craftcms/cms/src/elements/Entry.php(1670): craft\base\Element->afterPropagate()
#4 [...]/vendor/craftcms/cms/src/services/Elements.php(833): craft\elements\Entry->afterPropagate()
#5 [internal function]: craft\services\Elements->craft\services\{closure}()
#6 [...]/vendor/yiisoft/yii2/db/Connection.php(810): call_user_func()
#7 [...]/vendor/craftcms/cms/src/services/Elements.php(834): yii\db\Connection->transaction()
#8 [...]/vendor/craftcms/cms/src/controllers/EntriesController.php(675): craft\services\Elements->mergeCanonicalChanges()
#9 [...]/vendor/craftcms/cms/src/controllers/EntriesController.php(80): craft\controllers\EntriesController->_prepEditEntryVariables()
#10 [internal function]: craft\controllers\EntriesController->actionEditEntry()
#11 [...]/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#12 [...]/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams()
#13 [...]/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#14 [...]/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction()
#15 [...]/vendor/craftcms/cms/src/web/Application.php(276): yii\base\Module->runAction()
#16 [...]/vendor/yiisoft/yii2/web/Application.php(104): craft\web\Application->runAction()
#17 [...]/vendor/craftcms/cms/src/web/Application.php(261): yii\web\Application->handleRequest()
#18 [...]/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest()
#19 [...]/web/index.php(15): yii\base\Application->run()
#20 {main}
```

I have tried resaving entries for drafts, provisionals (there are none in this case) and normal entries for the section and site handles in question. They run without error, but don't help.

I could supply db but it's huge, so if possible to avoid that, awesome!

**Comment by brandonkelly** [comment]
@rob-baker-ar I would either need a DB backup or very specific steps to reproduce, starting with a fresh install of Craft.

**Comment by rob-baker-ar** [comment]
DB backup it is. I'll email support in the next hour referencing this. Thanks.

**Comment by internetztube** [comment]
I have the exact same issue.

**Comment by mmikkel** [comment]
Happening on our end, too (have contacted support w/ db dump etc).

**Comment by internetztube** [comment]
Looks like you can still duplicate such an entry.

**Comment by brandonkelly** [comment]
Thanks all! Was able to track this down and get it fixed for the next release.

To get the fix early, change your `craftcms/cms` requirement in composer.json to `"dev-develop as 3.7.8"` and run `composer update`.

**Comment by brandonkelly** [comment]
Craft 3.7.9 is out now with the fix. Thanks again everyone.
