### ISSUE TITLE
Front End Debug Toolbar Doesn't Show when Using the `{% tag %}` tag for the `<body>`

### ISSUE THREAD

**Issue by kylecotter** [craftcms/cms#9667]
### Description

With "Show the debug toolbar on the front end" enabled on an account, the toolbar will not show on the front end if the template uses a `{% tag %}` tag for the `<body>` tag of the page.

### Steps to reproduce

1. Enable "Show the debug toolbar on the front end" for an account
2. Use this as your template
```
<!DOCTYPE html>
<html>
    <head>
        <title>Foo</title>
    </head>
    {% tag 'body' %}
        Foo
    {% endtag %}
</html>
```
3. No debug toolbar appears
4. Swap `{% tag 'body' %}` for a `<body>` and it appears

### Additional info

- Craft version: 3.7.7
- PHP version: 7.4
- Database driver & version: mysql 8
- Plugins & versions: craftcms/craft boilerplate install

**Comment by brandonkelly** [comment]
That’s expected. Craft needs to be able to find the `</head>`, `<body>`, and `</body>` tags when rendering your template, in order to know where to output dynamically-registered `<link>` and `<script>` tags. If those aren’t hard-coded into your layout template, then you will need to hold Craft’s hand a little, by adding [head()](https://craftcms.com/docs/3.x/dev/functions.html#head), [beginBody()](https://craftcms.com/docs/3.x/dev/functions.html#beginbody), and/or [endBody()](https://craftcms.com/docs/3.x/dev/functions.html#endbody) function calls to the template.

For example:

```twig
{% tag 'body' %}
    {{ beginBody() }}

    <!-- ... -->

    {{ endBody() }}
{% endtag %}
```
