### ISSUE TITLE
Incorrect CP translations in some languages

### ISSUE THREAD

**Issue by nstCactus** [craftcms/cms#9785]
### Description
Some languages (like french or italian) have gendered nouns and require the associated (in)definite article to be different according to the gender (or other rules).

This makes translations such *Delete {type} for this site* incorrect in some cases. 

### Example
In french it is currently translated by *Supprimer le {type} for this site*.

This is correct for most masculine words but is incorrect for feminine words and words that begin with a vowel regardless of their gender.

The correct translations would be:

| english | Incorrect current french translation | Correct french translation |
| --|--|--|
| Delete the entry for this site | Supprimer le entrée sur ce site | Supprimer l'entrée sur ce site |
| Delete the category for this site | Supprimer le catégorie sur ce site | Supprimer la catégorie sur ce site |
| Delete the user for this site | Supprimer le utilisateur sur ce site | Supprimer l'utilisateur sur ce site |

### Additional info

- Craft version: 3.7.11
- PHP version: Irrelevant
- Database driver & version: Irrelevant
- Plugins & versions: Irrelevant

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just updated the transition to use `l’` when `type` is set to `entrée` (which is really the only thing it ever will be at this point), otherwise sticks with `le `, as before.

<img width="318" alt="The Save button menu on an Edit Entry form, showing that the “Delete entry for this site” option is now translated to “Supprimer l'entrée sur ce site”." src="https://user-images.githubusercontent.com/47792/132020542-80b1a798-585f-48bd-9bff-4f702311a0a2.png">

**Comment by brandonkelly** [comment]
Craft 3.7.12 is out now with that fix. Thanks again.
