### ISSUE TITLE
Prune-revisions and structureelements

### ISSUE THREAD

**Issue by Geestig** [craftcms/cms#9977]
### Description
On a website with around 700 entries with a lot of data there seems to be an issue when I try to prune the revisions. It shows to be pruning exactly as it should however while the process is running the structureelements table starts to increase in size. At one point this table alone was over 1.5GB which caused the DB to crash.

Even when I only prune 1 single revision and try to do it gradually it still increases too much in size. This is quite a big problem since we rely on cronjobs with feed-me feeds. Which automatically prune revisions after running the feed.

This problem seems to have started to become worse when the structure section that is being filled by feed me was changed into a channel. Perhaps there is still some remnant in de database that causes an issue with this?

EDIT: Have been able to complete a pruning. Pruned 1 revision of each entry - structureelements is now 450MB in size. And after completion did not seem to get cleaned. So those 450MB are now stuck in that table.

EDIT: Another thing I noticed is that row count in structureelements actually lowers whilst the size of the table grows. Very weird.

EDIT: Disabling Blitz does not help, running gc afterwards does not work. There are no errors in any log files. Structureelements just keeps on getting bigger.

EDIT: SELECT RELEASE_ALL_LOCKS(); does not help with the "Unable to acquire a lock for the structure 2" error i'm getting when trying to save an entry that no longer is a structure but now a channel.

### Steps to reproduce

1. Create section as structure.
2. Populate section with 600+ entries.
3. Change from structure to channel.
4. Trigger prune-revisions (through CLI or Dashboard is the same result)
5. Watch the structureelements database grow in size.

EDIT: When placing back a backup where the section is still a structure the same issue takes place. However it's only when deploying that it seems to increase the database. If i prune locally there do not seem to be any issues.

### Additional info

- Craft version: 3.7.16
- PHP version: 7.4
- Database driver & version: MySQL 5.7.33
- Plugins & versions:
Asset Rev 6.0.2
Blitz 3.10.4
CP Field Inspect 1.2.5
Feed Me 4.4.0
Guest Entries 2.4.0
Imager v2.4.0
Inlin 2.1.1
Notifications 1.1.4
Preparse Field 1.2.5
QRCode 1.0.5
Redactor 2.8.8
SendGrid 1.2.2
SEOMatic 3.4.16
Snaptcha 3.0.9
Style Inliner 2.3.0
Super Table 2.6.8
Umami 1.0.4

**Comment by brandonkelly** [comment]
Not really sure what to make of this. Are you still seeing that the row count is decreasing?

**Comment by brandonkelly** [comment]
The culprit is the sheer volume of structure operations, which can conflict with each other.

I have PR’d a fix, which should fix this by drastically reducing the amount of data that needs to be stored in the `structureelements` table, by removing (most) drafts and revisions from it.

https://github.com/craftcms/cms/pull/10040

If you want to help test, first make a database backup, then change your `craftcms/cms` requirement in `composer.json` to `"dev-feature/destructure as 3.7.18.2"`, and run `composer update`.

Once updated, you should see an immediate improvement, however you can fully prune the unnecessary draft/revision structure data by running the following command for each of your Structure sections:

```bash
> php craft utils/repair/section-structure <sectionHandle>
```

**Comment by Geestig** [comment]
Thanks for solving the issue!
